### ISSUE TITLE
Document method to use ALL service monitors, regardless of labels

### ISSUE THREAD

**Issue by dobesv** [prometheus-operator/prometheus-operator#1053]
**What did you do?**

I added a service monitor and it wasn't picked up by prometheus.  After much head-scratching and digging I realized it was not matched by the `serviceMonitorSelector`.  I had followed an example that required all service monitors to have a label `k8s-app`.

**What did you expect to see?**

I expected prometheus to pick up on ALL service monitors.  It was not intuitive to me that a label would be required.

**Environment**

kops

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.8", GitCommit:"2f73858c9e6ede659d6828fe5a1862a48034a0fd", GitTreeState:"clean", BuildDate:"2018-02-09T21:23:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
``
* Kubernetes cluster kind: 

kops AWS

Suggestion: change the examples to use an empty object for ` serviceMonitorSelector` instead of some arbitrary label.  Whatever the intention of `serviceMonitorSelector` is, I don't think its helpful for most users who probably won't have any service monitors that they don't want to be picked up by prometheus.

**Comment by brancz** [comment]
Note that the kube-prometheus manifests are purely an example, and they're absolutely supposed to be picked up by you and modified to your need.

That said, I do agree that it would probably be more intuitive for people to just have the "all" selector there. Would you like to create a PR to change this?

**Comment by bgagnon** [comment]
>  change the examples to use an empty object for ` serviceMonitorSelector` instead of some arbitrary label

Is using an empty object actually supported today? I was under the impression this resulted in _zero_ service monitors being matched.

**Comment by brancz** [comment]
We/Kubernetes differentiate in:

* no selector / “null” : no servicemonitors selected
* empty selector “{}” : all servicemonitors in a namespace selected 
* specified selector: select all matching servicemonitors in same namespace

**Comment by dobesv** [comment]
Created https://github.com/coreos/prometheus-operator/pull/1065

**Comment by zbialik** [comment]
is the same true for the `ruleSelector` field? we can just set that to `{}` and `Prometheus` will get ALL `PrometheusRules` in the defined `ruleNamespaceSelector`?
