### ISSUE TITLE
kubelet endpoint isn't created if a single node fails

### ISSUE THREAD

**Issue by jpiper** [prometheus-operator/prometheus-operator#1084]
**What did you do?**
When you manually add a node to kubernetes that hasn't yet come up (i.e. `kubectl describe node <node>` only shows an `ExternalID` and not `InternalIP` or `Hostname`) this prevents the kubelet endpoint from being generated,

**What did you expect to see?**
I expect the endpoint object to come up with the rest of the nodes.

**What did you see instead? Under which circumstances?**

> ts=2018-03-14T11:46:49.899778242Z caller=operator.go:342 component=prometheusoperator msg="syncing nodes into Endpoints object failed" err="failed to determine hostname for node (myhost.domain.com): host address unknown"

**Environment**
prometheus operator 0.17.0
kubernetes v1.9.3

**Comment by brancz** [comment]
This should be fixed. @ant31 could you have a look at this?

**Comment by jpiper** [comment]
Just want to clarify, this is the case of manually adding a node resource before the cluster has ever seen the node. In this case, I was applying node labels before a node had come up.

**Comment by brancz** [comment]
Sorry for not being very elaborate. I think you're request is legitimate, we should log that this happened and increase a counter to a metric (which we have to introduce in the first place), but continue to reconcile further as if everything was ok.

**Comment by jpiper** [comment]
Sounds good :) I was re-reading my bug report which had some typos/omissions in it (I was up late debugging when I wrote it) and wanted to make sure that it was clear :)

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think the issue is still valid, please reopen it.
