### ISSUE TITLE
Allow monitoring of service as one instance instead of many endpoints

### ISSUE THREAD

**Issue by mxey** [prometheus-operator/prometheus-operator#1091]
prometheus-operator only configures Prometheus for Kubernetes-SD of endpoints of services. Prometheus can discover other resources as well: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#<kubernetes_sd_config>

For some services, like kube-state-metrics in particular, it would be useful to run multiple instances for redundancy, but have Prometheus only query one of them, to avoid duplicate metrics.

**Comment by brancz** [comment]
I understand your reasoning, but at the same time I wonder how much an HA setup of kube-state-metrics is actually worth, unless there is something wrong with the host it runs on, I don't see the value of having kube-state-metrics HA, a new Pod, kube-state-metrics is a mirror of the API/etcd, so if it has a memory leak all HA pairs would be affected in the same way.

At one point we actually did run kube-state-metrics HA, but moved away from it as the possible additional complexity was not worth it.

I wonder if people have more than this use case?

**Comment by mxey** [comment]
My intent was to avoid it going down if there is something wrong with the host, yes.

**Comment by paulfantom** [comment]
I believe this will be possible after introducing generic ScrapeConfig from #2787. Closing in favor of that issue.  If you think this issue is still valid, please reopen it.
