### ISSUE TITLE
Add `--node-exporter-service` cmd arg to automatically create service and endpoints for node-exporter

### ISSUE THREAD

**Issue by whypro** [prometheus-operator/prometheus-operator#1104]
**What did you do?**
Our cluster deploy node-exporter by raw deb pkg instead of daemonset because k8s 1.7 is not support mount propagation. So we have to create node-exporter endpoints manually and maintain a list of cluster nodes. It would be a nightmare when add/delete node to/from cluster frequently.

**What did you expect to see?**

So I suppose it would be better if prometheus-operator give a choice to automatically create service and endpoints for node-exporter like for kubelet.
It can also be implemented more extensible to support more  exporters.

**What did you see instead? Under which circumstances?**

**Environment**
Ubuntu 16.04 
prometheus-operator: v0.16.1
prometheus: v2.1.0

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.12-27+6f9a2e3cb6d4f3", GitCommit:"6f9a2e3cb6d4f3f23188921ad4debfc37371daaa", GitTreeState:"clean", BuildDate:"2018-02-10T05:52:07Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

	kubeadm

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
Are you thinking of the hack scripts or helm?

**Comment by paulfantom** [comment]
This is out of scope for prometheus-operator.
