### ISSUE TITLE
Deploying kube-prometheus from master branch causing "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by ayashjorden** [prometheus-operator/prometheus-operator#1116]
**What did you do?**

1. Checkout branch master
2. From `contrib/kube-prometheus` run hack/cluster-monitoring/self-hosted-deploy
3. Watch pod's `prometheus-k8s-0` (or 1) logs shouting: `x509: certificate signed by unknown authority`
4. Checkout tag 0.17.0
5. run hack/cluster-monitoring/self-hosted-deploy
6. Prometheus is successfully gathering metrics, strange.

**What did you expect to see?**
Regular Prometheus logs

**What did you see instead? Under which circumstances?**
```
level=error ts=2018-03-19T18:30:33.545378997Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:269: Failed to list *v1.Service: Get https://10.2.0.1:443/api/v1/namespaces/monitoring/services?resourceVersion=0: x509: certificate signed by unknown authority"
level=error ts=2018-03-19T18:30:33.549321906Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:269: Failed to list *v1.Service: Get https://10.2.0.1:443/api/v1/namespaces/monitoring/services?resourceVersion=0: x509: certificate signed by unknown authority"
level=error ts=2018-03-19T18:30:33.556083243Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:269: Failed to list *v1.Service: Get https://10.2.0.1:443/api/v1/namespaces/monitoring/services?resourceVersion=0: x509: certificate signed by unknown authority"
level=error ts=2018-03-19T18:30:33.567372077Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:269: Failed to list *v1.Service: Get https://10.2.0.1:443/api/v1/namespaces/kube-system/services?resourceVersion=0: x509: certificate signed by unknown authority"
```

**Environment**
Kubernetes 1.9.0, 3 Masters, 3 Workers, AWS us-east-1
WeaveNet CNI plugin

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
k8s cluster 1.9.0 from scratch, built it my self.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:
Sorry, lost the bad-state logs.

**Comment by brancz** [comment]
> k8s cluster 1.9.0 from scratch, built it my self.

This is likely the problem, your TLS certificates seem like they are not valid for this IP, they should be valid here.

**Comment by ayashjorden** [comment]
Its hard for me to believe so.
As I explained: Deploying from `master` was failing with the error in the OP, **but** deploying tag `0.17.0` worked perfectly

**Comment by brancz** [comment]
hmm interesting ... which versions of Prometheus are those?

**Comment by ayashjorden** [comment]
For `master` branch -> Prometheus `v2.2.1`
For the `0.17.0` tag -> Prometheus `v2.2.0-rc.0`

**Comment by brancz** [comment]
Can you share the Prometheus config that both of those end up generating on the `/config` page of the Prometheus UI? (maybe 1 or 2 gists as they are probably rather large)

**Comment by ayashjorden** [comment]
How can I get the `commit id` that is deployed for PrometheusOperator, this will allow me to try and reproduce the issue.

**Comment by brancz** [comment]
The container image tag corresponds to the git tag of the GitHub release.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.
