### ISSUE TITLE
Helm install prometheus-operator will collection kube-dns's metrics，but grafana doesn't have graph.

### ISSUE THREAD

**Issue by woshihaoren** [prometheus-operator/prometheus-operator#1128]
**What did you do?**
Helm install prometheus-operator will collection kube-dns's metrics，but grafana doesn't have graph.
1.Can add some useful graphs?
2.use hack/cluster-monitoring/deploy command install kube-prometheus doesn't  collection kube-dns‘’s metrics.

**Comment by brancz** [comment]
we should fix this, would you like to create a PR for this? :slightly_smiling_face:

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
