### ISSUE TITLE
Grafana dashboar 'node' - add number of cpu available per server

### ISSUE THREAD

**Issue by sebglon** [prometheus-operator/prometheus-operator#1151]
**What did you do?**
On Node grafana dashboard can you add available CPU line for system load?
This is more easily to compare system load with available CPU on each node.

We can make the same on "all node" dashboard.

**Comment by brancz** [comment]
Happy to have this added, if you do want to add this, would you mind contributing it here: https://github.com/brancz/kubernetes-grafana

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.
