### ISSUE TITLE
Grafana pod metrics for statefulsets not separated by namespace 

### ISSUE THREAD

**Issue by mikisseth** [prometheus-operator/prometheus-operator#1182]
**What did you do?**
* Deployed a multi node statefulset (Elasticsearch), so node pods are named consistently between namespaces for the deployed ss (elasticsearch-data-0, elasticsearch-data-1...).
* Go into the Pod dashboard in Grafana, select a namespace and select a pod.

**What did you expect to see?**
Metrics for the selected pod in the selected namespace

**What did you see instead? Under which circumstances?**
Aggregated metrics for all pods with the selected pod name across all namespaces. 

For non-statefulset pods this is not a issue as the pods will have a unique name across the cluster

**Environment**

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-16T19:13:55Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5+coreos.0", GitCommit:"b8e596026feda7b97f4337b115d1a9a250afa8ac", GitTreeState:"clean", BuildDate:"2017-12-12T11:01:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
NA

* Manifests:
Exressions like:
```
sum by(container_name) (container_memory_usage_bytes{pod_name="$pod", container_name=~"$container", container_name!="POD"})
```
should have a namespace parameter added, eg: 
```
sum by(container_name) (container_memory_usage_bytes{namespace="$namespace", pod_name="$pod", container_name=~"$container", container_name!="POD"})
```
* Prometheus Operator Logs:
NA

**Comment by caleb15** [comment]
The dashboards come from the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) project. I would suggest transferring this issue over there BTW.

**Comment by paulfantom** [comment]
As @caleb15 mentioned, dashboards are sourced from kubernetes-mixin project. If this is still a problem, please open an issue there.
