### ISSUE TITLE
StatefulSet of Alertmanager is created without Service Account

### ISSUE THREAD

**Issue by FaKod** [prometheus-operator/prometheus-operator#1186]
**What did you do?**

Used the HELM chart: alertmanager together with PodSecurityPolicy Admission Controller

**What did you expect to see?**

A alertmanager-kube-prometheus StatefulSet with a ServiceAccount, that I am able to bind to a PodSecurityPolicy

**What did you see instead? Under which circumstances?**

I had to bind my PodSecurityPolicy to SA default

**Environment**

* Kubernetes version information:

```bash
~ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3+coreos.0", GitCommit:"f588569ed1bd4a6c986205dd0d7b04da4ab1a3b6", GitTreeState:"clean", BuildDate:"2018-02-10T01:42:55Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	my own Ansible scripts

**Comment by brancz** [comment]
That's fair, I think every application should have it's own ServiceAccount.

**Comment by gianrubio** [comment]
Will https://github.com/coreos/prometheus-operator/pull/1187 fix this issue?

**Comment by crandles** [comment]
@gianrubio It will apply the required PodSecurityPolicy to the `default` service account, instead of an account specific to the alertmanager instance.

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
