### ISSUE TITLE
prometheus-k8s-service-coredns-metrics throws an error due to namespace not matching monitoring

### ISSUE THREAD

**Issue by lpzdvd** [prometheus-operator/prometheus-operator#1195]
**What did you do?**

./hack/cluster-monitoring/deploy

**What did you expect to see?**

all manifests deployed properly 

**What did you see instead? Under which circumstances?**

prometheus-k8s-service-coredns-metrics throws an error due to metadata.namespace definining kube-system

namespace "monitoring" created
clusterrolebinding "prometheus-operator" configured
clusterrole "prometheus-operator" configured
serviceaccount "prometheus-operator" created
service "prometheus-operator" created
deployment "prometheus-operator" created
Waiting for Operator to register custom resource definitions...done!
clusterrolebinding "node-exporter" configured
clusterrole "node-exporter" configured
daemonset "node-exporter" created
serviceaccount "node-exporter" created
service "node-exporter" created
clusterrolebinding "kube-state-metrics" configured
clusterrole "kube-state-metrics" configured
deployment "kube-state-metrics" created
rolebinding "kube-state-metrics" created
role "kube-state-metrics-resizer" created
serviceaccount "kube-state-metrics" created
service "kube-state-metrics" created
secret "grafana-credentials" created
secret "grafana-credentials" unchanged
configmap "grafana-dashboard-definitions-0" created
configmap "grafana-dashboards" created
configmap "grafana-datasources" created
deployment "grafana" created
service "grafana" created
servicemonitor "node-exporter" created
servicemonitor "prometheus" created
servicemonitor "kube-apiserver" created
servicemonitor "kube-controller-manager" created
servicemonitor "kube-state-metrics" created
service "prometheus-k8s" created
**error: the namespace from the provided object "kube-system" does not match the namespace "monitoring". You must pass '--namespace=kube-system' to perform this operation.**
servicemonitor "prometheus-operator" created
servicemonitor "kubelet" created
serviceaccount "prometheus-k8s" created
configmap "prometheus-k8s-rules" created
servicemonitor "alertmanager" created
servicemonitor "coredns" created
servicemonitor "kube-scheduler" created
prometheus "k8s" created
role "prometheus-k8s" created
role "prometheus-k8s" unchanged
role "prometheus-k8s" unchanged
clusterrole "prometheus-k8s" configured
rolebinding "prometheus-k8s" created
rolebinding "prometheus-k8s" unchanged
rolebinding "prometheus-k8s" unchanged
clusterrolebinding "prometheus-k8s" configured
secret "alertmanager-main" created
service "alertmanager-main" created
alertmanager "main" created

**Environment**

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+coreos.0", GitCommit:"4292f9682595afddbb4f8b1483673449c74f9619", GitTreeState:"clean", BuildDate:"2017-11-21T17:22:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Manifests:

```
prometheus-k8s-service-coredns-metrics
```

**Comment by mxinden** [comment]
@lpzdvd Thanks for reporting this.

@brancz If you don't mind, I would hardcode the namespace value in every manifest of kube-prometheus. People that want a custom namespace can still `sed` through the project.

**Comment by brancz** [comment]
I’m actually working on generating everything with jsonnet which will make off of this much much nicer. Pull request should be out in a few days.
