### ISSUE TITLE
Helm Chart namespace mismatches

### ISSUE THREAD

**Issue by NicolasT** [prometheus-operator/prometheus-operator#1245]
The `kube-prometheus` Helm chart hard-codes `kube-system` as a namespace selector for various `ServiceMonitor`s, even though one can deploy all the exporters in another namespace (`helm install --namespace ...`, which overrides any `meta.namespace` set in the manifest).

Would a patch switching those for `{{ .Release.Namespace }}`, to match the actual deployment, be accepted?

I believe this is related to #1195. Of course, when using Helm, 'running sed' is not really an option, and forking this repository to use a different namespace, serving a Helm repo,... adds quite some overhead.

**Comment by gianrubio** [comment]
@NicolasT would you like to send a PR to allow namespace customization?

**Comment by NicolasT** [comment]
Sure, was just checking whether such PR would be accepted upfront :wink: Will work on it.

**Comment by lilic** [comment]
Closing as helm was moved out of this repo and is now in the Prometheus community org.
