### ISSUE TITLE
In Kubernetes Capacity Planning Dashboard of Grafana, no of pods are not showing beyond 1300.

### ISSUE THREAD

**Issue by nikhilagrawal577** [prometheus-operator/prometheus-operator#1265]
**What did you do?**
We did a scalability test in a cluster . . 

**What did you expect to see?**
No of pods available in the cluster utilization and pod utilization section in "Kubernetes Capacity Planning" dashboard 

**What did you see instead? Under which circumstances?**
Even though we have more than 1300 pods in the cluster. In Grafana Dashboard, it is not showing beyond 1300.
![image](https://user-images.githubusercontent.com/5903934/39302714-32aa4b88-4971-11e8-8e8c-76937eb8ea7c.png)

**Environment**

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
	
```
* Kubernetes cluster kind: 

Kubernetes Cluster in AWS.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
Is your Prometheus server answering the request? With this amount of pods, you will likely have to increase the request and limit of the Prometheus server :slightly_smiling_face: .

**Comment by nikhilagrawal577** [comment]
Yes. Prometheus Server answered all request . 
In our first test, prometheus server was down, so we increased the resources and limit in second test.
Still the issue was there in Grafana.
Where as all other metrics in dashboards were showing.

**Comment by brancz** [comment]
Strange! But this is more something you should report to the Grafana team, if the Prometheus server serves the query.

**Comment by nikhilagrawal577** [comment]
Grafana installation was done from kube-prometheus manifests. So we raised the issue here.
if it is not relevant , kindly suggest where to report this issue ?

**Comment by brancz** [comment]
> Grafana installation was done from kube-prometheus manifests. So we raised the issue here.

Sure that makes sense, but since Prometheus answers and Grafana shows other dashboards, it sounds like there is not a problem with the setup but with Grafana. I recommend opening an issue on the Grafana repo.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.
