### ISSUE TITLE
Unable scrape application metrics

### ISSUE THREAD

**Issue by jithinraj89** [prometheus-operator/prometheus-operator#1303]
@brancz Is prometheus.yml in Prometheus-operator capable of scraping application metrics.
Example from my python or Ruby apps in kubernetes pod.?
I have a python app already exposing it's metrics but unable to scrape those metrics by Prometheus, can't query them in Prometheus UI. Help

**Comment by brancz** [comment]
As mentioned in the other thread, you need a ServiceMonitor for this, the custom configuration is only for non-Kubernetes targets, like AWS ec2 VM discovery for example. Everything within Kubernetes should be done via ServiceMonitors.

**Comment by jithinraj89** [comment]
@brancz Thanks for the reply. Just now I found your page.
https://coreos.com/tectonic/docs/latest/tectonic-prometheus-operator/user-guides/application-monitoring.html hopefully, this may help.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.
