### ISSUE TITLE
Pod Utilization, alerts are missing in Updated Grafana v5.1.0

### ISSUE THREAD

**Issue by nikhilagrawal577** [prometheus-operator/prometheus-operator#1307]
**What did you do?**
Deployed the Prometheus operator.
And other manifests by executing command :  

``
kubectl create -f manifests/ 
``

**What did you expect to see?**

Wanted to see the no of pods available, alerts in the cluster.

**What did you see instead? Under which circumstances?**

Grafana is updated to Grafana v5.1.0, there are lots of changes in the dashboards. 
As comparison to previous Grafana.
Few things that i didn't find in the new Grafana : 
1. No of Pods available 
2. Maximum pods that Cluster can accomodate 
3. No of alerts.

Is it possible to include these metrics ?

**Comment by brancz** [comment]
there are still some dashboards left to be migrated, I suggest to start here: https://github.com/brancz/kubernetes-grafana/tree/1d5427f5cfdd47549a0502f071320312acb20330/src/kubernetes-jsonnet/grafana/configs/dashboard-definitions

and migrate them into https://github.com/kubernetes-monitoring/kubernetes-mixin
