### ISSUE TITLE
Use configmap for the externalLabels field in prometheus-k8s.yaml file.

### ISSUE THREAD

**Issue by deboshrestha** [prometheus-operator/prometheus-operator#1325]
**What did you do?**
I am trying to set up an `externalLabels` field in `/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s.yaml`  using a ConfigMap I created in the cluster. 

_ConfigMap Creation_
`kubectl create configmap special-config --from-literal=cluster-name=sre-k8s-5`

_Prometheus pod manifest i.e. prometheus-k8s.yaml_
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
spec:
  replicas: 1
  version: v2.2.1
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  externalLabels:
    cluster:
      - name: SPECIAL_LEVEL_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: cluster-name
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: k8s
  nodeSelector:
    prometheus-node: "1"
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 400Mi
    retention: 4h
  storage:
    volumeClaimTemplate:
       spec:
         selector:
           matchLabels:
             lvm-volume: database-prometheus
         resources:
           requests:
             storage: 10Gi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web

```

**What did you expect to see?**
I expected the Prometheus CRD pod to be created here with the `externalLabels` field.

**What did you see instead? Under which circumstances?**
The pod isn't getting created this way i.e. if I specify the `externalLabels` value coming from a configmap.

**Environment**

* Kubernetes version information:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Its created using kubespray.

I am kind of new to the ConfigMaps world. So I am following the instructions here - https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-pod-environment-variables-using-configmap-data.
Any help on this will be deeply appreciated. Thanks!

**Comment by deboshrestha** [comment]
Also I just noticed in the logs for the `prometheus-operator` pod I see the following error -


```
...

E0517 19:06:05.339513       1 reflector.go:205] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:290: Failed to list *v1.Prometheus: json: cannot unmarshal array into Go struct field PrometheusSpec.externalLabels of type string
E0517 19:06:06.343498       1 reflector.go:205] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:290: Failed to list *v1.Prometheus: json: cannot unmarshal array into Go struct field PrometheusSpec.externalLabels of type string
E0517 19:06:07.346646       1 reflector.go:205] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:290: Failed to list *v1.Prometheus: json: cannot unmarshal array into Go struct field PrometheusSpec.externalLabels of type string
E0517 19:06:08.349914       1 reflector.go:205] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:290: Failed to list *v1.Prometheus: json: cannot unmarshal array into Go struct field PrometheusSpec.externalLabels of type string
E0517 19:06:09.353661       1 reflector.go:205] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:290: Failed to list *v1.Prometheus: json: cannot unmarshal array into Go struct field PrometheusSpec.externalLabels of type string
E0517 19:06:10.357250       1 reflector.go:205] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:290: Failed to list *v1.Prometheus: json: cannot unmarshal array into Go struct field PrometheusSpec.externalLabels of type string
E0517 19:06:11.365064       1 reflector.go:205] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:290: Failed to list *v1.Prometheus: json: cannot unmarshal array into Go struct field PrometheusSpec.externalLabels of type string
...
```

Am I missing something here in the syntax? The pod specification written in Go for the `prometheus-k8s` pod does it even supports an entry like this? 

```
   externalLabels:
    cluster:
      - name: SPECIAL_LEVEL_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: cluster-name
```

for the `externalLabels` section?

**Comment by brancz** [comment]
The `externalLabels` field is simply a map of strings, so something like:

```
externalLabels:
  cluster: cluster1
```

I think what you wanted to do would be neat, but unfortunately would be a breaking change, that we cannot introduce.

**Comment by mxinden** [comment]
@deboshrestha As of right now, we are using the [Thanos config reloader](https://github.com/coreos/prometheus-operator/blob/master/vendor/github.com/improbable-eng/thanos/pkg/reloader/reloader.go#L240), which automatically expands any env variables inside the Prometheus configmap.

So you could do something like this is the Prometheus CRD:
```yaml
externalLabels:
  cluster: $MY_ENV_VAR
```

But this still leaves you with the problem on how to get your environment variable defined inside the promtheus-reload-container.

**Comment by deboshrestha** [comment]
Is there any known solution for defining environment variable inside the prometheus-reload-container?

**Comment by mxinden** [comment]
@deboshrestha None that I am aware of.

Are you trying to federate metrics of each of your K8s clusters into a master Prometheus? If so, how about instead of adding an externalLabel to each sub Prometheus, add a label to each sub metric in the master Prometheus via its service discovery.

**Comment by deboshrestha** [comment]
@mxinden Not yet, right now we are running one Prometheus Operator instance per cluster. However since we have multiple clusters and we are sending alerts to a single Slack channel(each for dev/prod etc)  for notification , we need some kind of identification mechanism to find which cluster it's coming from and take appropriate actions. Also based on the cluster names in the Alertmanager we are grouping our alerts and deciding severity levels etc. That's why getting the cluster name passed to Alertmanager is extremely crucial for us at this point. Right now, what I have done is while deploying the Prometheus Operator, get the current context using kubectl  and substituting the cluster name value in the `externalLabels` parameter in the `prometheus-k8s.yaml` file. I know its a real bad hack but we don't have any other better solution at this point of time.

**Comment by mxinden** [comment]
@deboshrestha would it be possible for you to solve this in a cleaner way with whatever configuration management you are using?

How would the configmap with the cluster name be created?

**Comment by caarlos0** [comment]
it would be nice to have something like this with thanos, mostly because of the `--query.replica-label`, so metrics can be properly deduplicated.

I'm using the prometheus operator helm chart, to launch my prometheus instance, is there any way to do that?

Could even be the pod name or something... don't need to be something "fixed" elsewhere 🤔

**Comment by gracedo** [comment]
> Is there any known solution for defining environment variable inside the prometheus-reload-container?

BTW, it looks like env variables can now be passed into containers, see https://github.com/coreos/prometheus-operator/pull/2445. Went out in v0.30.0

**Comment by paulfantom** [comment]
Overriding external_labels is already possible with `replicaExternalLabelName` and `prometheusExternalLabelName` in [PrometheusSpec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec).
