### ISSUE TITLE
Wrong prometheus address in grafana config when routePrefix configured

### ISSUE THREAD

**Issue by dm3ch** [prometheus-operator/prometheus-operator#1337]
**What did you do?**
I have installed prometheus-operator and kube-prometheus from helm and added routePrefix option
Try to open any dashboard.
**What did you expect to see?**
Working dashboard
**What did you see instead? Under which circumstances?**
No graphs and templating error

If I right understood this problem is caused by 
https://github.com/coreos/prometheus-operator/blob/master/helm/grafana/templates/dashboards-configmap.yaml#L27
in this line routePrefix (of prometheus) is not considered. But this value is stored in another chart so we can't use specified variable.

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
