### ISSUE TITLE
[kube-prometheus] NOTES.txt fails without deployGrafana

### ISSUE THREAD

**Issue by mxey** [prometheus-operator/prometheus-operator#1342]
**What did you do?**

```
helm fetch coreos/kube-prometheus
helm template kube-prometheus-0.0.66.tgz --set deployGrafana=false
```

**What did you expect to see?**

Rendered templates of kube-prometheus

**What did you see instead? Under which circumstances?**

```
Error: render error in "kube-prometheus/templates/NOTES.txt": template: kube-prometheus/templates/NOTES.txt:1:83: executing "kube-prometheus/templates/NOTES.txt" at <.Values.grafana.ingr...>: can't evaluate field ingress in type interface {}
```

**Environment**

only Helm client locally.

```
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

**Notes**

From looking at the NOTES.txt template, I assume the same would happen with deployAlertmanager=false

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
