### ISSUE TITLE
Use recommended Labels

### ISSUE THREAD

**Issue by ant31** [prometheus-operator/prometheus-operator#1441]
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

app.kubernetes.io/name | The name of the application | mysql | string
-- | -- | -- | --
app.kubernetes.io/version | The current version of the application (e.g., a semantic version, revision hash, etc.) | 0.20.0| string
app.kubernetes.io/component | The component within the architecture | XYZ | string
app.kubernetes.io/part-of | The name of a higher level application this one is part of | prometheus-operator | string

for resources created by the operator:

app.kubernetes.io/name | The name of the application | mysql | string
-- | -- | -- | --
app.kubernetes.io/managed-by | The tool being used to manage the operation of an application | prometheus-operator | string

**Comment by mxinden** [comment]
Cool. This way we can also remove the `operated-by: prometheus-operator` [label](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L50).

Do you want me to apply this to both the Prometheus Operator as well as Kube Prometheus?

**Comment by brancz** [comment]
Sounds good to me regarding both prometheus-operator as well as kube-prometheus.

**Comment by ant31** [comment]
cc @metalmatze

**Comment by mxinden** [comment]
Closing here as https://github.com/coreos/prometheus-operator/pull/2427 was merged.

**Comment by ant31** [comment]
I think it doesn't add the labels of resources generated by the PO yet.

**Comment by brancz** [comment]
This has yet to be done.

**Comment by brancz** [comment]
We're about half way there, most manifests do this but not everything the operator generates.

**Comment by brancz** [comment]
Still some work outstanding for this.

**Comment by paulfantom** [comment]
I do believe we finally have all labels in 0.48.1 :)
