### ISSUE TITLE
Any support for the emptydir volume claim for Prometheus resource and stateful set?

### ISSUE THREAD

**Issue by RudyBone** [prometheus-operator/prometheus-operator#1474]
I'm guessing the answer is no, however just to be clear I am working on a small 3 node cluster that does not have persistent storage.  I have a persistent volume claim (which remains in the pending state), but the Prometheus stateful set never creates any pods (probably because of the missing volume claim).  Am I correct in assuming that this is a stateful set issue?  Couldn't find anything in the StatefulSet API spec for emptydir.

**Comment by dimm0** [comment]
Here's the example of a statefulset with emptydirs:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/testing-manifests/statefulset/mysql-galera/statefulset.yaml#L76

**Comment by mxinden** [comment]
You can specify an EmptyDir storage via the Prometheus [`StorageSpec`](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#storagespec).

Let me know if this solves your problem.

**Comment by brancz** [comment]
If you just don't define the `storage` field, then the Prometheus Pods will default to using emptydir volumes.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.
