### ISSUE TITLE
alertmanager send duplicate repeated emails

### ISSUE THREAD

**Issue by jiuchongxiao** [prometheus-operator/prometheus-operator#1502]
my alertmanager ha send repeated emails.
![default](https://user-images.githubusercontent.com/13093730/41572381-14eb2a3c-73aa-11e8-9ed9-2bc67fcccdd7.png)

**my config as follow**:
 

config:
    global:
      resolve_timeout: 5m
      # The smarthost and SMTP sender used for mail notifications.
      smtp_smarthost: 'smtp.ym.163.com:25'
      smtp_from: 'xxxx'
      smtp_auth_username: xxxx'
      smtp_auth_password: 'xx'
      smtp_require_tls: true
    route:
      group_by: ['__name__','alertname', 'cluster', 'service']
      group_wait: 100s
      group_interval: 5m
      repeat_interval: 3h
      receiver: email_alert
      routes:
      - match_re:
          severity: ^(none)$
          alertname: ^(host_cpu_usage|node_filesystem_free|host_down)$
        receiver: email_alert

    inhibit_rules:
      # Mute critical when down is fired for given service
      - source_match:
          severity: 'down'
        target_match:
          severity: 'critical'
        equal: ['cluster', 'service']
      # Mute warning when down is fired for given service
      - source_match:
          severity: 'down'
        target_match:
          severity: 'warning'
        equal: ['cluster', 'service']
      # Mute warning when critical is fired for given alert
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'cluster', 'service']
    receivers:
    - name: email_alert
      email_configs:
      - to: xxx@xxx
        send_resolved: true

please help me,how should i config ? to sure not recive repeat email?

**Comment by jiuchongxiao** [comment]
i setted Number of Alertmanager replicas  replicaCount =3   i will recived 3 eamils.
when i set replicaCount =1 i will recived 1 email.

why ? should not it be set replicaCount?

**Comment by brancz** [comment]
Which version of the Alertmanager are you using? Could you check the UI of the Alertmanager and check that there are multiple peers in the `/#/status` page listed?

**Comment by jiuchongxiao** [comment]
@brancz 
![default](https://user-images.githubusercontent.com/13093730/41587097-f4b9b260-73e0-11e8-8a0f-ccc60f725148.png)

**Comment by brancz** [comment]
Which version of the Prometheus Operator are you using? (could you try `v0.15.0-rc.3` of the Alertmanager as well, there are numerous bugs that have been fixed from `0.14.0` to `0.15.0-rc.3`)

**Comment by brancz** [comment]
What about the prometheus-operator Pod?

**Comment by mxinden** [comment]
@jiuchongxiao thanks a lot for filing this issue and helping us triage the problem.

In addition to the Prometheus Operator definition, would you mind posting the definition of the alertmanagers as well?

```
kubectl get deployment -n monitoring prometheus-operator -oyaml
kubectl get statefulset -n monitoring alertmanager-kube-prometheus -oyaml
```

You probably need to adjust the names of the resources, as I am not fully aware of how you configured your deployment configuration.

**Comment by jiuchongxiao** [comment]
@mxinden 

**the prometheus-operator as below:**
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-06-19T01:34:50Z
  generation: 1
  labels:
    app: prometheus-operator
    chart: prometheus-operator-0.0.26
    heritage: Tiller
    operator: prometheus
    release: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
  resourceVersion: "2730304"
  selfLink: /apis/extensions/v1beta1/namespaces/monitoring/deployments/prometheus-operator
  uid: f50ba0b4-7360-11e8-b5a8-005056a55893
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: prometheus-operator
      operator: prometheus
      release: prometheus-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-operator
        operator: prometheus
        release: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.20.0
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.20.0
        imagePullPolicy: IfNotPresent
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus-operator
      serviceAccountName: prometheus-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-06-19T01:34:51Z
    lastUpdateTime: 2018-06-19T01:34:51Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-06-19T01:34:50Z
    lastUpdateTime: 2018-06-19T01:34:51Z
    message: ReplicaSet "prometheus-operator-d75587d6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

**the alertmanager-kube-prometheus as bleow:**

apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: 2018-06-19T08:54:31Z
  generation: 1
  labels:
    alertmanager: kube-prometheus
    app: alertmanager
    chart: alertmanager-0.1.2
    heritage: Tiller
    release: kube-prometheus
  name: alertmanager-kube-prometheus
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Alertmanager
    name: kube-prometheus
    uid: 618d1996-739e-11e8-b5a8-005056a55893
  resourceVersion: "2892143"
  selfLink: /apis/apps/v1/namespaces/monitoring/statefulsets/alertmanager-kube-prometheus
  uid: 61a14dfb-739e-11e8-b5a8-005056a55893
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      alertmanager: kube-prometheus
      app: alertmanager
  serviceName: alertmanager-operated
  template:
    metadata:
      creationTimestamp: null
      labels:
        alertmanager: kube-prometheus
        app: alertmanager
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  alertmanager: kube-prometheus
                  app: alertmanager
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - --config.file=/etc/alertmanager/config/alertmanager.yaml
        - --mesh.listen-address=$(POD_IP):6783
        - --storage.path=/alertmanager
        - --web.listen-address=:9093
        - --web.external-url=http://kube-prometheus-alertmanager.monitoring:9093
        - --web.route-prefix=/
        - --mesh.peer=alertmanager-kube-prometheus-0.alertmanager-operated.monitoring.svc
        - --mesh.peer=alertmanager-kube-prometheus-1.alertmanager-operated.monitoring.svc
        - --mesh.peer=alertmanager-kube-prometheus-2.alertmanager-operated.monitoring.svc
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: quay.io/prometheus/alertmanager:v0.14.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/v1/status
            port: web
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: alertmanager
        ports:
        - containerPort: 9093
          name: web
          protocol: TCP
        - containerPort: 6783
          name: mesh
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/v1/status
            port: web
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          requests:
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
        - mountPath: /alertmanager
          name: alertmanager-kube-prometheus-db
      - args:
        - -webhook-url=http://localhost:9093/-/reload
        - -volume-dir=/etc/alertmanager/config
        image: quay.io/coreos/configmap-reload:v0.0.1
        imagePullPolicy: IfNotPresent
        name: config-reloader
        resources:
          limits:
            cpu: 5m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 0
      volumes:
      - name: config-volume
        secret:
          defaultMode: 420
          secretName: alertmanager-kube-prometheus
      - emptyDir: {}
        name: alertmanager-kube-prometheus-db
  updateStrategy:
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: alertmanager-kube-prometheus-7b6c64b4cf
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: alertmanager-kube-prometheus-7b6c64b4cf

**Comment by mxinden** [comment]
According to the Alertmanager UI your Alertmanager cluster is not properly established. This would explain the duplicated notifications.

In order to debug this you could try the following:

1. Test the network connection between the Alertmanager pods.
Exec into the container:
`kubectl exec -it -n monitoring alertmanager-kube-prometheus-0 -c alertmanager -- /bin/sh`
Check if the peer urls get resolved inside the container:
`dig +short alertmanager-kube-prometheus-1.alertmanager-operated.monitoring.svc`
Try to connect to one of the peers cluster endpoints:
`curl  alertmanager-kube-prometheus-1.alertmanager-operated.monitoring.svc:6783`
2. Check the log output of the alertmanager pods.
3. Try the newest Alertmanager version `v0.15.0`.

Let us know how it goes!

**Comment by johnzheng1975** [comment]
Same issue for me. 
Version:
0.9.1

**Comment by paulfantom** [comment]
This seems like a very old issue. It is entirely possible this was already fixed in recent prometheus-operator versions. If you think this issue is still present please reopen or comment in this thread.

**Comment by tangjizhou** [comment]
have the same issue in  centos 7.9 (kernal: 3.10.0-1160.el7.x86_64), kubernetes 1.18.9,docker 19.03,  alertmanager 0.20.0 ,prometheus 2.15.2 , seem like all pods alert .
one pod --> one email, three pods --> three emails .

**Comment by tangjizhou** [comment]
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2021-10-16T08:58:25Z"
  generation: 1
  labels:
    alertmanager: main
    manager: operator
    operation: Update
    time: "2021-10-16T08:58:25Z"
  name: alertmanager-main
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Alertmanager
    name: main
    uid: 19ca923a-820e-4071-b0c1-d7e0b791fbe2
  resourceVersion: "1087079"
  selfLink: /apis/apps/v1/namespaces/monitoring/statefulsets/alertmanager-main
  uid: 6abd2272-efeb-42e9-901b-4b4d98669cac
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      alertmanager: main
      app: alertmanager
  serviceName: alertmanager-operated
  template:
    metadata:
      creationTimestamp: null
      labels:
        alertmanager: main
        app: alertmanager
    spec:
      containers:
      - args:
        - --config.file=/etc/alertmanager/config/alertmanager.yaml
        - --cluster.listen-address=[$(POD_IP)]:9094
        - --storage.path=/alertmanager
        - --data.retention=120h
        - --web.listen-address=:9093
        - --web.external-url=http://192.168.160.36:30005
        - --web.route-prefix=/
        - --log.level=debug
        - --cluster.peer=alertmanager-main-0.alertmanager-operated.monitoring.svc:9094
        - --cluster.peer=alertmanager-main-1.alertmanager-operated.monitoring.svc:9094
        - --cluster.peer=alertmanager-main-2.alertmanager-operated.monitoring.svc:9094
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: 192.168.160.47:8888/public/alertmanager:v0.20.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /-/healthy
            port: web
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: alertmanager
        ports:
        - containerPort: 9093
          name: web
          protocol: TCP
        - containerPort: 9094
          name: mesh-tcp
          protocol: TCP
        - containerPort: 9094
          name: mesh-udp
          protocol: UDP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /-/ready
            port: web
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 4m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
        - mountPath: /alertmanager
          name: alertmanager-main-db
          subPath: alertmanager-db
      - args:
        - -webhook-url=http://localhost:9093/-/reload
        - -volume-dir=/etc/alertmanager/config
        image: 192.168.160.47:8888/public/configmap-reload:v0.3.0
        imagePullPolicy: IfNotPresent
        name: config-reloader
        resources:
          limits:
            cpu: 100m
            memory: 25Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: alertmanager-main
      serviceAccountName: alertmanager-main
      terminationGracePeriodSeconds: 120
      volumes:
      - name: config-volume
        secret:
          defaultMode: 420
          secretName: alertmanager-main
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: alertmanager-main-db
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: nfs-storage
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: alertmanager-main-885cddc9f
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: alertmanager-main-885cddc9f
  updatedReplicas: 3

**Comment by tangjizhou** [comment]
by the way , when i post alert to one pod manually , only one mail received , when i post alert to each pod (3 pods) , three mails received , and no error logs occurred
