### ISSUE TITLE
Unhandled error received. Exiting..." err="communicating with server failed: Get https://10.0.0.1:443/version: dial tcp 10.0.0.1:443: i/o timeout

### ISSUE THREAD

**Issue by ghost** [prometheus-operator/prometheus-operator#1506]
**What did you do?**
Installed Prometheus Operator 0.20.0 on an Azure acs-engine generated Kubernetes 1.10.4 cluster.

**What did you expect to see?**

Expected for `prometheus-operator` pod to be able to talk to the API server.

**What did you see instead? Under which circumstances?**

```
k logs prometheus-operator-5996867847-8dwbd -n monitoring
ts=2018-06-19T16:38:56.397696851Z caller=main.go:130 msg="Unhandled error received. Exiting..." err="communicating with server failed: Get https://10.0.0.1:443/version: dial tcp 10.0.0.1:443: i/o timeout"
```

**Environment**

* Kubernetes version information:

```
☁  kube-prometheus [features/outputdirs] ⚡ k version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

acs-engine

* Manifests:

* Prometheus Operator Logs:

**Comment by brancz** [comment]
Thanks for opening this issue!

I feel like this issue might be better opened with the azure support, this seems like a problem with the underlying cluster. Reaching the apiserver should be possible.

**Comment by dongwangdw** [comment]
@neurot1cal did you get this issue resolved? I got the same issue now.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.
