### ISSUE TITLE
System Load visualization sh shown as percentage instead of number

### ISSUE THREAD

**Issue by datarace** [prometheus-operator/prometheus-operator#1511]
**What did you do?**
Installed prometheus with default dashboards
**What did you expect to see?**
System Load graph to have numerical value on vertical axis to 2 decimal places - matching load average shown on linux 'top' utility

**What did you see instead? Under which circumstances?**
System Load graph displays percentage. For example instead of showing load as 7.23, it is showing as 723%
 
**Environment**
All
* Kubernetes version information:
1.8
	insert output of `kubectl version` here

* Kubernetes cluster kind: 
kops
	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

**Comment by brancz** [comment]
Which dashboard are you referring to? The Pod dashboard is intentionally done this way, because in Kubernetes CPU requests and limits are specified in # of cores available to the Pod, so it makes sense to show utilization in this unit as well.

**Comment by datarace** [comment]
Hi,

Thanks for following up this issue. Some further detail:

Dashboard: Nodes
Visualization: System Load

Dashboard: Kubernetes Capacity Planning
Visualization: System Load

These use the metrics node_load1, node_load5, and node_load15

From
https://blog.freshtracks.io/a-deep-dive-into-kubernetes-metrics-part-2-c869581e9f29
"node_load1, node_load5 and node_load15 represent the 1, 5 and 15 min load averages."

Check out https://www.tecmint.com/understand-linux-load-averages-and-monitor-performance
for description of "load average".  These figures are returned from linux 'uptime' command (i.e numbers to 2DP not percentages) so should be graphed as such.

Thanks

**Comment by Pamir** [comment]
In SystemLoad tab system load queries are  sum(node_load1) sum(node_load5) sum(node_load15). What is the aim of using sum instead of avg. Using sum functions makes the empty system load average to 200% 300% in graphics.

**Comment by paulfantom** [comment]
If this is still present, please reopen in https://github.com/kubernetes-monitoring/kubernetes-mixin/
