### ISSUE TITLE
(Cross-)namespaced Alertmanager configuration

### ISSUE THREAD

**Issue by brancz** [prometheus-operator/prometheus-operator#1528]
Similar to how Prometheus can be configured using the ServiceMonitor and PrometheusRule objects, it would be nice if users could configure Alertmanager routes and receivers within their own namespace, for their respective alerts.

This is not as easy as it sounds, as typically when an Alertmanager route matches it does not continue to match any further routes, unless the `continue: true` field is set. This means that if we were to give people the control over these they could be either misconfigured and other teams don't receive alerts, or worse in a multi tenancy environment it could cause alerts that should be sent not to be sent.

The question is whether we should just enable users to configure everything like in the upstream configuration or a subset, or an entirely different abstraction. Ideally I'd like to not restrict users in any way, but I currently don't see a way without doing so, without also violating the requirements above.

There has been some discussion around this in #1498.

@mxinden @Quentin-M

**Comment by mxinden** [comment]
I can see two ways here:

1. Inject the `continue: true` into each route configuration.
2. Create one top level route per Kubernetes namespace and have each alert-route-crd be a sub-route to its namespaced route.

**Comment by nukepuppy** [comment]
still a needed feature honestly

**Comment by s-urbaniak** [comment]
Just as a heads-up that this feature is probably going to be bumped in priority.
/cc @simonpasquier @pgier

**Comment by simonpasquier** [comment]
Hello! I've started a design document:
https://docs.google.com/document/d/1aVVttvocop8zNezwrNFbHh_HKRW_fhJUZqhmrr8fGK0/edit?usp=sharing

Feel free to comment there...

**Comment by brancz** [comment]
Design is done, implementation still outstanding.

**Comment by simonpasquier** [comment]
Closed by #3451
