### ISSUE TITLE
Create federated prometheus with operator

### ISSUE THREAD

**Issue by sebglon** [prometheus-operator/prometheus-operator#1530]
**What did you do?**
I want to manage 2 type of prometheus on the same cluster:
- one (statefull set)for collecting metrics 
- one for federeted.

Is it possible use use 2 prometheus definition to manage that?
How can i specify for each servicemonitor if it's for federation or collector?
Is it better to have alertmanager on federation or on collector?
Is it possible to re-use or extend existing Helm chart to create that?

Can i have help? I can create a doc or contribution if needed to implement that.

**Comment by brancz** [comment]
Yes you can create a federated Prometheus with the Prometheus Operator. There is nothing special about it. As far as I understand you don't care about persistence of the federated Prometheus, so you can just not configure the `storage` field for it.

Your `ServiceMonitor` simply needs to have the `metricsPath: /federate` and use the `params` field to configure the federation parameters you would like to use.

> Is it better to have alertmanager on federation or on collector?

Can you elaborate what you mean by this?

> Is it possible to re-use or extend existing Helm chart to create that?

My feeling is that this is too specific, so I don't think we can or need to include any of this in a helm chart, but it would be nice if you could write up some documentation! :slightly_smiling_face:

**Comment by mxinden** [comment]
> Is it better to have alertmanager on federation or on collector?

Depends whether your alerting rules are based on a specific data set, that a single Prometheus collector can serve, or if they require a global data set that only the federated Prometheus has.

**Comment by sebglon** [comment]
Yes my rules are based on specific data set, that can be scaped by one
statefulset scaled at 4.
I explane, i have a big cluster with more than 500 nodes to use for the
continous integration.
On this cluster we create more 1000 pods / houre and delete it. Now only
one prometheus node crash with more data scraping with more than 10G memory

Now i can have an alert from one promemetheus that are fake because the
scraping 1 is on node A but the next scraping is not on the same prometheus
node.

And of course we want federation to consolidate all this data for alertingn
and graphe

**Comment by pault84** [comment]
> Your `ServiceMonitor` simply needs to have the `metricsPath: /federate` and use the `params` field to configure the federation parameters you would like to use.

Can you show me an example of the ServiceMonitor spec? all I see for endpoints is port. 
What if I want to specify a host outside of the current cluster? But still use this operator/alert manager
