### ISSUE TITLE
Grafana Dashboard CRD

### ISSUE THREAD

**Issue by sslavic** [prometheus-operator/prometheus-operator#1535]
Similar to ServiceMonitor and operator/controller for configuring Prometheus, please support configuring Grafana dashboards to be used by Grafana instance.

E.g. say there's one team managing monitoring infra with help of Prometheus Operator, and multiple other teams manage different apps/services on same Kubernetes cluster, with those apps/services exposing custom metrics they will likely need also custom Grafana dashboards. Once created these dashboards can be exported and properly managed (version controlled) and deployed/provisioned on different clusters where same apps could be running.

**Comment by brancz** [comment]
We agree that this is a problem that needs to be solved, however we will not be solving it in the Prometheus operator, as this is a concern that revolves around deploymend and lifecycle management of Grafana. Related to https://github.com/coreos/prometheus-operator/issues/115.

We would be happy to collaborate around a Grafana operator :slightly_smiling_face:.

**Comment by sslavic** [comment]
My bad, sorry for creating duplicate.

Saw Grafana YAMLs in https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/manifests so thought Prometheus operator was deploying it too.

[OLM](https://github.com/operator-framework/operator-lifecycle-manager) mentions

> OLM extends Kubernetes to provide a declarative way to install, manage, and upgrade operators and their dependencies in a cluster.

Would using OLM be the way to go for combining Prometheus operator and its dependency, Grafana operator?

**Comment by brancz** [comment]
> Would using OLM be the way to go for combining Prometheus operator and its dependency, Grafana operator?

Yes I think that's a great idea, although I would not couple the two operators at all. Grafana datasources should just be filled with pointers to Kubernetes Services, not directly coupled with Prometheus Operator objects.

The kube-prometheus object just happens to use the Prometheus Operator. We had it as a subproject of the Prometheus Operator as there was only poor tooling for vendoring manifests, etc., but now that there is jsonnet and the jsonnet-bundler, we should move kube-prometheus into it's own repository.

**Comment by sslavic** [comment]
Would you mind starting the grafana-operator repo under coreos org? Maybe initialized using operator-sdk?
I see you already have an idea about Grafana CRD https://github.com/coreos/prometheus-operator/issues/115#issuecomment-289001896

**Comment by agolomoodysaada** [comment]
This project seems relevant: https://github.com/integr8ly/grafana-operator

**Comment by brancz** [comment]
Yes that's what I'd currently recommend :)

**Comment by paulfantom** [comment]
Closing as this is not something we would like to have in prometheus-operator. It should be a separate operator as mentioned above.
