### ISSUE TITLE
Port config-reloader logic back into prometheus-config-reloader

### ISSUE THREAD

**Issue by mxinden** [prometheus-operator/prometheus-operator#1580]
We currently have two sidecars for each Prometheus Pod.
1. Prometheus config reloader: Templating and reloading Prometheus configuration
2. Rule config map reloader: Reloading rule configuration

The logic of the latter should be merged back into the former, reducing the amount of sidecars by one.

**Comment by brancz** [comment]
With https://github.com/coreos/prometheus-operator/pull/3128 merged, this should now be trivial to configure with one container.

**Comment by paulfantom** [comment]
Done in #3457
