### ISSUE TITLE
I don't have google based cluster, I have just configured kubernetes based setup on single node, what should I give user ID? I am facing error exrea previlliges forbidden..

### ISSUE THREAD

**Issue by salman-hayder** [prometheus-operator/prometheus-operator#1587]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
Attempting to grant extra privileges has nothing to do with google or the user id. It means that the user you are performing the action with does not that all the privileges you attempting to grant. You will need cluster-admin access to do this as there are privileges involved that don’t exist in the cluster yet.

**Comment by salman-hayder** [comment]
how to get cluster infor and cluser users who has privileges?

**Comment by brancz** [comment]
how did you bootstrap your cluster?

**Comment by salman-hayder** [comment]
its bare metal installation using kubeadm

**Comment by brancz** [comment]
Assuming you followed this guide: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#before-you-begin

Then your cluster admin configuration will be located at `/etc/kubernetes/admin.conf` on your node. Use that configuration and you should have cluster admin privileges.
