### ISSUE TITLE
The helm charts do not allow service port configuration

### ISSUE THREAD

**Issue by lli-hiya** [prometheus-operator/prometheus-operator#1613]
**What did you do?**
We’d like to use Prometheus Operator in our company's environment.. We expose apps outside the cluster via Kubernetes Services using annotations for ELB integration and external-dns for Route53 integration. We do not use Ingresses at this moment. This means that we need to be able to set the Services’ ports to expected http(s) standards (80 and 443). 

The problem is that the Helm charts for Prometheus, Alertmanager, and Grafana have  hardcoded ports in their Services. As a result, our users have to access the web UIs with these hardcoded ports, which is an unpleasant user experience. We'd like to make these ports configurable from `values.yaml` so that we can change them to be `443`.

We'd like to create a PR to support this feature. 

**What did you expect to see?**
Service ports that are configurable from `values.yaml`.

**What did you see instead? Under which circumstances?**
Service ports are hard-coded.

**Comment by openJT** [comment]
You just need to setup your service like this:

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-grafana-external
  name: kube-prometheus-grafana-external
  namespace: monitoring
  annotations: 
      "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:xxx"
      "service.beta.kubernetes.io/aws-load-balancer-ssl-ports": "443"
      "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "http"
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: "443"
    port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app:  kube-prometheus-grafana
status:
  loadBalancer: {}

Replace arn:xxx with your certificate info

**Comment by lli-hiya** [comment]
@openJT Thanks for your reply, and this is a functional workaround for the problem. But I think creating a PR for this problem can still benefit the community in the long run.

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
