### ISSUE TITLE
Not working after deleting/recreating kube-prometheus pod

### ISSUE THREAD

**Issue by jalberto** [prometheus-operator/prometheus-operator#1615]
**What did you do?**
I had a working prometheus-operator + kube-prometheus (using helm in AKS). I deleted `prometheus-kube-prometheus-0` pod (trying to force config reload because new service monitor).
After pod is recreated I get this logs:

```
 level=error ts=2018-07-13T15:33:23.688514234Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:268: Failed to list *v1.Endpoints: Get https://10.41.0.1:443/api/v1/namespaces/monit/endpoints?resourceVersion=0: dial tcp 10.41.0.1:443: i/o timeout"
level=error ts=2018-07-13T15:33:23.688512834Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270: Failed to list *v1.Pod: Get https://10.41.0.1:443/api/v1/namespaces/kube-system/pods?resourceVersion=0: dial tcp 10.41.0.1:443: i/o timeout"
level=error ts=2018-07-13T15:33:23.688577035Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:269: Failed to list *v1.Service: Get https://10.41.0.1:443/api/v1/namespaces/default/services?resourceVersion=0: dial tcp 10.41.0.1:443: i/o timeout" 
```

**What did you expect to see?**
A working prometheus

**What did you see instead? Under which circumstances?**
Error logs

**Comment by jalberto** [comment]
by some kind of dark-magic, it did back to normal ~43mins later

**Comment by mxinden** [comment]
> (trying to force config reload because new service monitor)

Do I understand correctly, that you restarted the Prometheus Operator in order for it to discover a new ServiceMonitor?

The Prometheus Operator watches ServiceMonitors by default and should notice any new ones. Did this not work for you previously?

**Comment by jalberto** [comment]
@mxinden you understood correctly, after a while new SM was not showing up in prometheus, so I "recreated" it, it did work.

I am more worried about that ~45mins waiting for prometheus to work again

**Comment by gianrubio** [comment]
> ```Failed to list *v1.Service: Get https://10.41.0.1:443/api/v1/namespaces/default/services?resourceVersion=0: dial tcp 10.41.0.1:443: i/o timeout```

This means your apiServer was down or not reachable from prometheus-operator, did you see any issue on the apiserver pod?

**Comment by jalberto** [comment]
no, everything else was working. Notice this is an AKS so masters are managed by azure

**Comment by mxinden** [comment]
Just to clarify, you restarted the Prometheus Operator pod, or the Prometheus pod?

Would you mind posting your:
- Prometheus version
- Prometheus Operator version
- Kubernetes version

here?

**Comment by jalberto** [comment]
@mxinden sorry for the delay.

- I deleted `prometheus-kube-prometheus-0` so the prometheus server created by kube-prometheus
- prometheus-operator-0.0.28
- kube-prometheus-0.0.102
- 1.10 (AKS)

I still have same problem, new 'servicemonitors' is not updating prometheus config

**Comment by mxinden** [comment]
If I understand the helm charts correctly, helm-prometheus-operator `v0.0.28` corresponds to prometheus-operator `v0.20.0`. Could you check if this issue still persists with prometheus-operator `v0.22.2`?

> I still have same problem, new 'servicemonitors' is not updating prometheus config

Before updating, could you post your ServiceMonitor and your Prometheus manifest here?

**Comment by paulfantom** [comment]
This seems like a very old issue. It is entirely possible this was already fixed in recent prometheus-operator versions. If you think this issue is still present please reopen or comment in this thread.
