### ISSUE TITLE
Add support docs for Cortex

### ISSUE THREAD

**Issue by lilic** [prometheus-operator/prometheus-operator#1641]
It would be good to have some documentation on how to use [Cortex](https://github.com/weaveworks/cortex) with the prometheus-operator.

From what I understand all it would take is to add documention on how to configure the `RemoteWrite` feature in the prometheus-operator to point to an instance of [Cortex](https://github.com/weaveworks/cortex) (or for example [Weave Cloud](https://cloud.weave.works/)).

cc @brancz

**Comment by brancz** [comment]
A lot of people have asked for `RemoteRead` and `RemoteWrite` documentation so I think this could be a nice example. I think we should primarily make this about `RemoteRead` and `RemoteWrite`, but I'm fine with having something along the lines of "You will need a service that accepts the `RemoteRead`/`RemoteWrite` interface, see the [official Prometheus documentation on services that support `RemoteRead`/`RemoteWrite`](https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage)".

If weaveworks can provide an endpoint that needs no signup or anything I'm also happy to include that in the documentation provided weaveworks owns this document and fixes things as they come up. Same goes for other providers cc @tomwilkie @bcotton. Probably a win-win if the user guide is easy to follow.

RE #352

**Comment by paulfantom** [comment]
Seems like it is still valid. Right @lilic ? :smile:

**Comment by zhifanl** [comment]
I am interested in this issue :)

**Comment by simonpasquier** [comment]
Closing as too specific. We could have more detailed documentation on configuring remote-write in general though.
