### ISSUE TITLE
Error seen when override `.Values.prometheusLabelValue` in helm chart

### ISSUE THREAD

**Issue by lli-hiya** [prometheus-operator/prometheus-operator#1645]
**What did you do?**
I am using the code from `release-0.22`, and after I deployed Prometheus-Operator and Prometheus using the provided **Helm chart**, everything's working well and I can see this tag: `Promethus: <Helm-Release-Name>` appears in all of the following resource definitions: Prometheus (CRD), prometheus Service, prometheus StatefulSet and prometheus Pod.  

However, If I override the `.Values.prometheusLabelValue`, I noticed that `Promethus: <Helm-Release-Name>` is updated in Prometheus (CRD), prometheus Service, prometheus StatefulSet, but still remains unchanged in prometheus Pod definition. 

This is a problem because at this time prometheus Service will no longer be able to locate the pod due to the inconsistent tags. 

**What did you expect to see?**
I expect overriding the `.Values.prometheusLabelValue` will not break things. 
**What did you see instead? Under which circumstances?**
Prometheus service is no longer able to find prometheus pod, and `kubectl get endpoints` shows `<none>` as well. 

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6+coreos.0", GitCommit:"c2aac694c2c7373dfe3ad81f47fc3cbc70a5a8fa", GitTreeState:"clean", BuildDate:"2018-03-21T21:54:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by lli-hiya** [comment]
FYI, the original error was seen in Prometheus: v2.2.1, and it still persists after I upgrade to the latest version of Prometheus: v.2.3.2.

It looks like the label: `Prometheus:<xxx>` in Prometheus pod is tightly related to the helm release name.

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
