### ISSUE TITLE
Alert mismatch b/w helm and contrib/kube-prometheus

### ISSUE THREAD

**Issue by aleerizw** [prometheus-operator/prometheus-operator#1662]
I just noticed that a number of alerts defined in contrib/kube-prometheus are not defined in the helm exporter charts. For example none of the CronJob alerts are in the helm charts ( e.g KubeCronJobRunning ). Is this behavior intended?

**Comment by brancz** [comment]
I think this is a fundamental problem about helm. Honestly I don't know how this can ever be done and kept up to date without gigantic maintenance required. Maybe for the charts alerts should be completely external @gianrubio ?

**Comment by aleerizw** [comment]
I am not sure if this is possible but can the prometheus rules be dynamically generated?

**Comment by brancz** [comment]
Using jsonnet, yes :slightly_smiling_face: .

**Comment by aleerizw** [comment]
Yes, I was thinking if can we render the *.libsonnet files to helm compatible yaml, that would remove the maintenance right?

**Comment by brancz** [comment]
Yes and no, jsonnet will always only render json (or yaml as it's a compatible format), but we can't add additional templating, which I believe is something people want.

**Comment by aleerizw** [comment]
Ok, I can make a PR to try and sync the alerts in the helm charts, is this something that you would be open to merge?

**Comment by brancz** [comment]
I don't maintain the charts, @gianrubio does. Unless it's very small changes, I generally don't review or merge them, it's up to @gianrubio.

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
