### ISSUE TITLE
Pod security policies allow running as root

### ISSUE THREAD

**Issue by carlpett** [prometheus-operator/prometheus-operator#1663]
There's a typo in the PSP in the helm charts that allows running as root, instead of disallowing it:

https://github.com/coreos/prometheus-operator/blob/e82f7bbd51eeb821746864e03adf4eeeda59a36a/helm/prometheus-operator/templates/psp.yaml#L36-L47

`min` should be 1, not 0.

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
