### ISSUE TITLE
Prometheus-oparator is not able to retrieve pod data

### ISSUE THREAD

**Issue by e-manrique** [prometheus-operator/prometheus-operator#1686]
Hello, 

I'm having a real hard time trying to get the pod metrics, i have kubernetes 1.11 and metric-server, actually i cannot find a way to get it work, every time i create the service-monitor and then the Prometheus to get the data from this service monitor, nothing happen, i believe it's because /metrics it's not sending the actual usage data, i read that i need to use cAdvisor, but i also cannot find a way to setup the serviceMonitor to access this data, there is a lot of different information everywhere, so in the end of the day i cannot find a way to retrieve the info from the pod, can you give me some light,

Thanks in advance

**Comment by brancz** [comment]
There are a few concepts/components mixed here, I'll try to clear up the confusion.

metrics-server is completely independent from anything Prometheus. The metrics-server is a minimal components that will work in any Kubernetes cluster, it requests all kubelet's `/stats` endpoints every 60 seconds and just keeps all those results in memory. When you do `kubectl top pod` for example you are requesting the metrics server (starting Kubernetes v1.10.x). Another case where you would use the metrics-server is when you do autoscaling on core metrics (cpu/memory).

cAdvisor is compiled into the kubelet's binary and the kubelet exposes the cAdvisor metrics under `/metrics/cadvisor`. That means if you want to collect those metrics with Prometheus, you need to create a `ServiceMonitor` that discovers the kubelets, to scrape those endpoints. As monitoring the cluster is something everyone has to do we assembled kube-prometheus a collection of manifests that you can apply against your cluster and you instantly get a full cluster-monitoring stack: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus

(if you're just interested in seeing the kubelet's `ServiceMonitor`, it's here: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus-serviceMonitorKubelet.yaml

Let us know if that clears things up or if you have any other questions! :slightly_smiling_face:

**Comment by mulakkalfaizal** [comment]
@brancz : i was able to start the prometheus-operator and kube-prometheus using helm (https://itnext.io/kubernetes-monitoring-with-prometheus-in-15-minutes-8e54d1de2e13).

After setting it up i add a test service monitor (nginx) and it was added to the target list .

The problem i am facing is my nginx container does not have a /metrics so it is showing down.
How can i start monitoring the cpu and mem of a pod which does not have a /metics.

Thanks in advance.

**Comment by brancz** [comment]
cpu, memory, etc. you will collect automatically through cAdvisor, which is already being scraped out of the box when you install the kube-prometheus stack, you should not have to configure anything for that

**Comment by mulakkalfaizal** [comment]
thank you for your reply.

i am getting cpu,mem metric for all the kubernetes component pods. But for the pod which i deployed ..i am not getting any metrics.

I also getting below error in the prometheus ui. 

Could you please help me on this error.

<img width="1501" alt="screen shot 2018-08-21 at 8 39 25 pm" src="https://user-images.githubusercontent.com/17142729/44415838-6f832f80-a582-11e8-9957-8d9bb3c51c09.png">

**Comment by brancz** [comment]
This is a common problem, have a look at this: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#troubleshooting

**Comment by mulakkalfaizal** [comment]
the reason i am not getting any metics for the pods which i deployed is because of the kublet target down?

**Comment by brancz** [comment]
yes
