### ISSUE TITLE
Grafana Helm Chart does not allow setting service ports to serve over https

### ISSUE THREAD

**Issue by michaelgeorgeattard** [prometheus-operator/prometheus-operator#1720]
As the following template:

https://github.com/coreos/prometheus-operator/blob/master/helm/grafana/templates/svc.yaml

Chart does not allow overriding service ports.

**Comment by s0enke** [comment]
Seems like https://github.com/coreos/prometheus-operator/pull/1711 would fix this.

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
