### ISSUE TITLE
HowTo configure the alartmanager allert receivers

### ISSUE THREAD

**Issue by m-gnaedig** [prometheus-operator/prometheus-operator#1739]
Hi
I have installed prometheus-operator successfully on my test kubernetes cluster
and everything works fine. Now I like to edit the alartmanager configuration to
add my alert receivers.

How can I edit this configuration?
In the Kubernetes Dashboard I didn't see the expected Config Map. 

Thanks in advance
Manfred

**Comment by brancz** [comment]
You installed the Prometheus Operator or the entire kube-prometheus stack? Alertmanager is configured using a `Secret` named `alertmanager-<alertmanager-object-name>`.

**Comment by ManCon** [comment]
Hi

Thanks for your reply.

I have installed my prometheus-operator by this way:
$ helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
$ helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring
$ helm install coreos/kube-prometheus --name kube-prometheus --set global.rbacEnable=true --namespace monitoring

At the moment it is just for my test installation.
Shall I use an other installation method?

**Comment by ManCon** [comment]
Normaly it should be possible to edit the yml config-files with this command:

$ kubectl edit <ressource-name> <obj-name0>

But what is in this case the right <ressource-name> <obj-name0> for the "alertmanager.yml"?

**Comment by brancz** [comment]
I would recommend using kube-prometheus directly. It is maintained by us and the helm charts can easily get out of date. You can find that here: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#kube-prometheus

The Prometheus Operator registers new types, among others the `Alertmanager` kind. When an `Alertmanager` kind object is created, the Prometheus Operator will manage that Alertmanager cluster for you, and expect the configuration to be presented in a Kubernetes Secret that is called "alertmanager-<the-name-of-the-alertmanager-object>", in the same namespace as the `Alertmanager` object.

In your case check the Alertmanager objects in the `monitoring` namespace:

```
kubectl -n monitoring get alertmanager
```

There you should see one alertmanager object, with that name you can then look at the associated secret:

```
kubectl -n monitoring get secret alertmanager-<the-name-of-the-alertmanager-object>
```

In that secret you will find the current Alertmanager configuration.

**Comment by bamb00** [comment]
@brancz I modified in the alertmanager & kube-prometheus values.yaml config section for the receiver to use the "webhook_configs:"  When I ran a new install "helm install kube-prometheus --name kube-prometheus --namespace monitoring" the /etc/alertmanager/config/alertmanager.yaml did not have the changes.  What steps am I missing?

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
