### ISSUE TITLE
Not able to use containers in kind Alertmanager

### ISSUE THREAD

**Issue by bamb00** [prometheus-operator/prometheus-operator#1774]
Hi,

I'm wanting to run additional container with Alertmanager Statefulsets.  Is it possible to run containers like this when the kind Alertmanager object is created? The containers field is set in the second to last line .

Did not see the additional containers once the statefulssets was deployed.  Only see the alertmanager and config_reloader.

https://github.com/coreos/prometheus-operator/blob/release-0.19/helm/alertmanager/templates/alertmanager.yaml

    apiVersion: {{ template "prometheus-operator.apiVersion" . }}
	kind: Alertmanager
	metadata:
	  labels:
	    alertmanager: {{ .Release.Name }}
	    app: {{ template "alertmanager.name" . }}
	    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
	    heritage: {{ .Release.Service }}
	    release: {{ .Release.Name }}
	{{- if .Values.labels }}
	{{ toYaml .Values.labels | indent 4 }}
	{{- end }}
	  name: {{ .Release.Name }}
	spec:
	  baseImage: "{{ .Values.image.repository }}"
	{{- if .Values.externalUrl }}
	  externalUrl: "{{ .Values.externalUrl }}"
	{{- else if .Values.ingress.fqdn }}
	  externalUrl: http://{{ .Values.ingress.fqdn }}{{ .Values.routePrefix }}
	{{- else }}
	  externalUrl: http://{{ template "alertmanager.fullname" . }}.{{ .Release.Namespace }}:9093
	{{- end }}
	{{- if .Values.nodeSelector }}
	  nodeSelector:
	{{ toYaml .Values.nodeSelector | indent 4 }}
	{{- end }}
	  paused: {{ .Values.paused }}
	  replicas: {{ .Values.replicaCount }}
	  resources:
	{{ toYaml .Values.resources | indent 4 }}
	{{- if .Values.storageSpec }}
	  storage:
	{{ toYaml .Values.storageSpec | indent 4 }}
	{{- end }}
	  version: "{{ .Values.image.tag }}"
	{{- if eq .Values.podAntiAffinity "hard" }}
	  affinity:
	    podAntiAffinity:
	      requiredDuringSchedulingIgnoredDuringExecution:
	      - topologyKey: kubernetes.io/hostname
	        labelSelector:
	          matchLabels:
	            app: {{ template "alertmanager.name" . }}
	            alertmanager: {{ .Release.Name }}
	{{- else if eq .Values.podAntiAffinity "soft" }}
	  affinity:
	    podAntiAffinity:
	      preferredDuringSchedulingIgnoredDuringExecution:
	      - weight: 100
	        podAffinityTerm:
	          topologyKey: kubernetes.io/hostname
	          labelSelector:
	            matchLabels:
	              app: {{ template "alertmanager.name" . }}
	              alertmanager: {{ .Release.Name }}
	{{- end }}
	{{- if .Values.tolerations }}
	  tolerations:
	{{ toYaml .Values.tolerations | indent 4 }}
	{{- end }}
	  containers:
	{{ toYaml .Values.sidecarsSpec | indent 4 }}  

Thanks in Advance.

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
