### ISSUE TITLE
Suspected error in included APIServerErrorsHigh alert rules

### ISSUE THREAD

**Issue by cpick** [prometheus-operator/prometheus-operator#1777]
**What did you do?**
Used `helm` to install "coreos/prometheus-operator" and "coreos/kube-prometheus" into a GKE cluster (following [these instructions](https://github.com/coreos/prometheus-operator/tree/master/helm#tldr) and using [these recommended values](https://github.com/coreos/prometheus-operator/tree/master/helm/kube-prometheus#installing-on-gkeeksaks)).
 
**What did you expect to see?**
Expected "[APIServerErrorsHigh](https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-kubernetes/templates/kubernetes.rules.yaml#L66-L82)" alerts to fire only when the API server had been returning 5xx HTTP status codes greater than 2% of the time for at least 10 minutes. 

**What did you see instead? Under which circumstances?**
APIServerErrorsHigh would fire (with "description = API server returns errors for 100% of requests") any time there were at least 3 5xx status codes spaced out about 5 minutes apart (irrespective of the total number of requests).

**Environment**

* Prometheus Operator version:
    Image:         quay.io/coreos/prometheus-operator:v0.20.0
    Image ID:      docker-pullable://quay.io/coreos/prometheus-operator@sha256:88cd66e273db8f96cfcce2eec03c04b04f0821f3f8d440396af2b5510667472d

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.3", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-08-04T03:45:50Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
GKE

**Hypothesis**

I believe the problem is that the [APIServerErrorsHigh rule](https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-kubernetes/templates/kubernetes.rules.yaml#L66-L82) is based on the expression:

    rate(apiserver_request_count{code=~"^(?:5..)$"}[5m]) / rate(apiserver_request_count[5m]) * 100 > 2

I interpret the intent here to be "alarm if 5xx status codes make up greater than 2% of all requests", however, in practice, the $value of the expression will only ever be empty or 100.  It will never be a value in the range of 0 through 99.

The denominator doesn't sum up the request rates across all `code`s, it produces a vector of rates for each input time series (eg at least one per `code`) and then the division operator matches only those time series that have the 5xx `code`s selected for in the numerator.  This results exclusively values of 1 (* 100).

Because of the above, a few 5xx `code`s spread over 10 minutes will cause the alert to fire even if they really make up a tiny fraction of the overall number of requests.

I'm still new to Prometheus' query language so I hesitate to suggest the correct expression, but I'm pretty sure the current one is incorrect as described above.

**Comment by brancz** [comment]
You are absolutely correct. The helm chart needs to be fixed. The "upstream" alerts from the `contrib/kube-prometheus/` project have long been [fixed](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/system_alerts.libsonnet#L104-L106), but seem to have never made it into the helm charts.

**Comment by cpick** [comment]
I took a crack at [importing the upstream change](https://github.com/cpick/prometheus-operator/commit/77b5dd0ee201a7c7a632d3988efb92503f91bbab), but I was left with a few questions:
1. From `without(instance, %(podLabel)s)`, why was `podLabel` a templated value in the numerator (especially when the denominator has an untemplated `pod`: `without(instance, pod)`)?  (I just dropped in `pods` in my patch).
1. In the same clause, why was extra care taken to add an "s" to make the `podLabel` plural?
1. Why are only `instance` and `pod` filtered out?  Why not `endpont`, `subresource`, `verb`, and especially `code`?  Doesn't `code` have to be filtered to sum the values properly and not run into the same issue?  (I may not understand how the sum operator works and that could be the source of my confusion.)

**Comment by brancz** [comment]
1) because for the better or worse a lot of users use a different label than "pod" to uniquely describe a workload, this is more typical when mixed (kubernetes and non kubernetes) workloads are monitored with the same Prometheus server.
2) it's not actually, for the better or worse `%(var)s` means that `var` is a string and is replaced within the template, the `s` just stands for string.
3) if I understand correctly you are proposing to look at the API errors for all errors summed up divided by all requests total, instead of looking at each API resource individually, I think that would be a reasonable request, that we should open on the kubenetes-mixin, and discuss there.

**Comment by cpick** [comment]
Thanks for the quick and detailed replies!

> because for the better or worse a lot of users use a different label than "pod" to uniquely describe a workload

It's odd that it was only templated in the numerator then.

> `%(var)s` means that var is a string

I was wondering if that might be the case.

> we should open on the kubenetes-mixin, and discuss there

Sensible.

OK, from those answers it sounds like my branch probably does at least match up with current upstream.  I'll submit it as a PR.

**Comment by MichaelKorn** [comment]
#1799 did not solve the problem because we still don't get a sum over all requests as 'code' ist not mention in the without() clause.  The result ist an empty vector or a vector with (one or more) 100% elements.
I would like to recommend the following formula:
`sum(rate(apiserver_request_count{code=~"^(?:5..)$"}[5m])) without(instance, pod, code)
          / sum(rate(apiserver_request_count[5m])) without(instance, pod, code)`

**Comment by brancz** [comment]
I believe these rules have actually been removed recently from the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) (where these rules are now defined and just imported into this repo in form of a dependency), in favor of mult-window error burn rate type alerts. Nevertheless your suggestion would indeed have been good.

**Comment by paulfantom** [comment]
That alert is no longer shipped.
