### ISSUE TITLE
Uncomment predefined vars in values.yaml resulted in error

### ISSUE THREAD

**Issue by bamb00** [prometheus-operator/prometheus-operator#1778]
I uncomment the block 'tls:' variables from kube-prometheus/values.yaml resulted in error,
  
       ): error converting YAML to JSON: yaml: line 74: did not expected key

https://github.com/coreos/prometheus-operator/blob/release-0.19/helm/kube-prometheus/values.yaml

       ingress:
          ## If true, Alertmanager Ingress will be created
          ##
          enabled: false

          ## Annotations for Alertmanager Ingress
          ##
          annotations: {}
            # kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"

          fqdn: ""

          ## TLS configuration for Alertmanager Ingress
          ## Secret must be manually created in the namespace
          ##
          tls: []
             - secretName: alertmanager-general-tls
               hosts:
                 - alertmanager.example.com

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
