### ISSUE TITLE
alert but the pod were exist

### ISSUE THREAD

**Issue by lpf190** [prometheus-operator/prometheus-operator#1827]
**i install the k8s with kops, and install prometheus-operator with ` /contrib/kube-prometheus/manifests/`**

* Prometheus Operator version:

	` 0prometheus-operator-deployment.yaml`-image: quay.io/coreos/prometheus-operator:v0.23.1
        ` prometheus-prometheus.yaml`-baseImage: quay.io/prometheus/prometheus

* Kubernetes version information:
	v1.9.8
* Kubernetes cluster kind: 

	insert how you created your cluster: kops.

* Manifests:

```
/contrib/kube-prometheus/manifests/*
```

* The Alarm expression:

```
ALERTS{alertname="KubeClientErrors"}
Element | Value
-- | --
ALERTS{alertname="KubeClientErrors",alertstate="firing",instance="172.20.47.151:10250",job="kubelet",severity="warning"} | 1
ALERTS{alertname="KubeClientErrors",alertstate="firing",instance="172.20.56.97:443",job="apiserver",severity="warning"} | 1
ALERTS{alertname="KubeClientErrors",alertstate="firing",instance="172.20.57.60:10250",job="kubelet",severity="warning"} | 1


vector(1)
Element | Value
-- | --
{} | 1


ALERTS{alertname="KubeControllerManagerDown"}
Element | Value
-- | --
ALERTS{alertname="KubeControllerManagerDown",alertstate="firing",severity="critical"} | 1
```

** I want how the value access, what mistake i did? **

**Comment by brancz** [comment]
Kops has different labellings on the pods/services, but we already have a mixin prepared for kops so you can just follow this: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#cluster-creation-tools
