### ISSUE TITLE
two charts, can't decide

### ISSUE THREAD

**Issue by yosefy** [prometheus-operator/prometheus-operator#1842]
question:
how if at all this helm install is related to this one:

https://github.com/helm/charts/tree/master/stable/prometheus

(just don't understand which one is the "right one")

thanks

**Comment by metalmatze** [comment]
The helm chart you linked to is for Prometheus on its own. The helm chart in this repository is explicitly for the Prometheus Operator.

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
