### ISSUE TITLE
changing digests for release tarballs

### ISSUE THREAD

**Issue by ensonic** [prometheus-operator/prometheus-operator#1848]
**What did you do?**
we're building using bazel (http://bazel.build) as our build system. We pull in kube-prometheus as
```
http_file(
    name = "kube_prometheus_chart",
    sha256 = "ab67d0985d8f2dbbd2569feaf02ffe595fe132f8ffec005de7b6c3f11c7ce844",
    urls = [
        "https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/kube-prometheus-0.0.105.tgz",
    ],
)
```

**What did you see instead? Under which circumstances?**

The sha256sum of the tgz file keeps changing from time to time. Are you regenerating the downloads?

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
