### ISSUE TITLE
prometheus-config-reloader is confused by symlinks in rules directory (mounted ConfigMap)

### ISSUE THREAD

**Issue by seh** [prometheus-operator/prometheus-operator#1864]
**What did you do?**

Mount a directory of rules from a Kubernetes _ConfigMap_, yielding a directory with two extra entries:
- at least one directory with a name encoding the time at which it was written, and
- a symbolic link named _..data_ that points to one of the aforementioned time-based directories.

For example, for a mounted _ConfigMap_ that defines no rule files:
```
/etc/prometheus/rules $ ls -al
total 28
drwxrwxrwx    3 root     root          4096 Sep  6 14:30 .
drwxr-xr-x    1 nobody   nogroup       4096 Sep  6 14:30 ..
drwxr-xr-x    2 root     root          4096 Sep  6 14:30 ..2018_09_06_14_30_17.485373332
lrwxrwxrwx    1 root     root            31 Sep  6 14:30 ..data -> ..2018_09_06_14_30_17.485373332
```
I started the _prometheus-config-reloader_ container in a pod alongside Prometheus, supplying the command line flag `--rule-dir=/etc/prometheus/rules`.

**What did you expect to see?**

The _prometheus-config-reloader_ program should start and walk the _/etc/prometheus/rules_ directory, ignoring directories and symbolic links, or possibly ignoring symbolic links that don't transitively point to regular files.

**What did you see instead? Under which circumstances?**

The _prometheus-config-reloader_ program crashes repeatedly, each time logging the following message:
> build hash: read /etc/prometheus/rules/..data: is a directory

That's occurring in function `reloader.(*Reloader).apply` when [it walks the rules directory](https://github.com/coreos/prometheus-operator/blob/v0.23.2/vendor/github.com/improbable-eng/thanos/pkg/reloader/reloader.go#L146-L166). If it encounters a file entry that's a directory, [it accepts it](https://github.com/coreos/prometheus-operator/blob/v0.23.2/vendor/github.com/improbable-eng/thanos/pkg/reloader/reloader.go#L153-L155). However, for entries that aren't directories, it assumes that the entry is a file, and proceeds to [call `os.Open` on it](https://github.com/coreos/prometheus-operator/blob/v0.23.2/vendor/github.com/improbable-eng/thanos/pkg/reloader/reloader.go#L198) in `reloader.(*Reloader).hashFile`. That attempt fails, because you can't open a directory.

We can test whether a file entry is a symbolic link by calling `f.Mode() & os.ModeSymlink != 0`, or don't bother chasing symbolic links and use `f.IsRegular()` to only read files likely to be accepted by `os.Open`. Unfortunately, inspecting the `os.PathError` returned by `os.Open` doesn't reveal enough to isolate this case of trying to dereference a link that doesn't point to a file—at least not without inspecting its string form.

Another approach to consider: if a file entry is not a regular file and it's not a directory, use [`path/filepath.EvalSymlinks`](https://godoc.org/path/filepath#EvalSymlinks) to get a final path, and see whether that path is a regular file or directory.

**Environment**

* Prometheus Operator version:  

  I'm not using the Prometheus Operator, and am only using the _prometheus-config-reloader_ image, but the version is _v0.23.2_.

* Kubernetes version information:  

  _Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}_
  
  _Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}_

* Kubernetes cluster kind:  

  _kubedm_ in AWS

**Comment by seh** [comment]
That fix for the Thanos looks good. Would you be opposed to adapting it into this project?

> What is your reasoning for manually configuring the prometheus-config-reloader?

I'm not using Prometheus Operator, and got tired of manually issuing the HTTP POST request against Prometheus to get it to take an updated _ConfigMap_ into account. It looks like it's intended to handle both the main configuration file and the rule files.

Should I not be configuring it?

**Comment by mxinden** [comment]
> Should I not be configuring it?

It is fine to use it. Just please keep in mind that it is an implementation detail of the Prometheus Operator. We don't give any stability guarantees on it. In case you really just want to reload on a config map change, I would use https://github.com/jimmidyson/configmap-reload.

> Would you be opposed to adapting it into this project?

Not at all, we were actually planning to do so in the long run (see https://github.com/coreos/prometheus-operator/issues/1580). Would you like to give this a shot @seh? I am more than happy to help.

**Comment by seh** [comment]
I may have some time to work on this adaptation this week. My main concern is being able to test the changes as I go, as I'm not using the Prometheus Operator in any of my projects yet.

In the meantime, I'll also look at _configmap-reload_ to see if it would meet our current needs.

**Comment by mxinden** [comment]
@seh Cool. I think a first step would be to just update the vendored version of Thanos resolving the above mentioned symlink issue.

**Comment by seh** [comment]
With #3457 merged, I think it's safe to close this now, given [the current implementation of the Thanos reloader](https://github.com/thanos-io/thanos/blob/master/pkg/reloader/reloader.go#L299-L324).
