### ISSUE TITLE
Grafana dashboards missing node data

### ISSUE THREAD

**Issue by weikinhuang** [prometheus-operator/prometheus-operator#1887]
**What did you do?**

Went to the nodes dashboard in the preconfigured grafana dashboards.

**What did you expect to see?**

Graphs with data points

**What did you see instead? Under which circumstances?**

All graphs say `No data points`.

**Environment**

* Prometheus Operator version:

	running the helm chart @ 0.20.0

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	bootkube, self hosted

---

I see that data is being collected into prometheus by manually running queries:

![screen shot 2018-09-12 at 3 19 28 pm](https://user-images.githubusercontent.com/794658/45448273-e7370c80-b69f-11e8-836b-b06d72266424.png)

However this is what I see in grafana:

![screen shot 2018-09-12 at 3 19 46 pm](https://user-images.githubusercontent.com/794658/45448281-f28a3800-b69f-11e8-9511-728074811f40.png)

Dashboards relating to pods/deployments/statefulsets & cluster health all are working fine.

**Comment by joaovrodrigues** [comment]
Hey,

You probably updated the image of node_exporter. Prometheus Helm instalation comes, by default, with 0.15 version whereas the latest version, 0.16, brings many breaking changes. Queries changed a lot across the board and the default Prometheus Operator grafana dashboards are no longer valid.

I recommend you install a different dashboard from the repositories and try again.

**Comment by weikinhuang** [comment]
I see, thank you

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
