### ISSUE TITLE
Prometheus datasource in grafana is missing the -prometheus

### ISSUE THREAD

**Issue by ricktbaker** [prometheus-operator/prometheus-operator#1912]
**What did you do?**

Default helm install of kube-prometheus with release name of "mon"

**What did you expect to see?**

Was expecting the data source url to be http://mon-prometheus:9090

**What did you see instead? Under which circumstances?**

```
  prometheus-datasource.json: |
    {
      "access": "proxy",
      "basicAuth": false,
      "name": "prometheus",
      "type": "prometheus",
      "url": "http://mon:9090"
    }
```

```
kubectl get services -n monitoring
NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
mon-alertmanager          ClusterIP   10.100.110.69    <none>        9093/TCP            1d
mon-exporter-kube-state   ClusterIP   10.100.149.64    <none>        80/TCP              1d
mon-exporter-node         ClusterIP   10.100.99.14     <none>        9100/TCP            1d
mon-grafana               ClusterIP   10.100.37.2      <none>        80/TCP              1d
mon-prometheus            ClusterIP   10.100.228.221   <none>        9090/TCP            1d
```

From my services above, I need to get that url changed to http://mon-prometheus:9090.   I can change it via the console and all is good, but then if I need to recreate, update I have to remember to change it again.

EDIT: Edited question to designate this was installed via helm.

**Comment by brancz** [comment]
Are you talking about the helm charts?

**Comment by ricktbaker** [comment]
Yes, installed via helm.

**Comment by cmachler** [comment]
I am seeing the same issue.

**Comment by cmachler** [comment]
Looks like #1413 caused the regression.

**Comment by ricktbaker** [comment]
Looks that way.   I renamed my release from mon to mon-prometheus and it's working now.   Definitely needs fixing however since that shouldn't be required.

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
