### ISSUE TITLE
FR: support "role: pod" for deployments without explicit Service

### ISSUE THREAD

**Issue by dilyevsky** [prometheus-operator/prometheus-operator#1913]
I have a bunch of various deployments that just do some data pipelining and so don't have any services attached to them since they don't serve any traffic. They do however export /metrics and I would like to scrape them using Prometheus Operator.

It's not a big deal I guess but it seems silly having to add Service (that is not even used because Prometheus goes to Endpoints directly) just for metrics collection. Can "role: pod" from kubernetes_sd_configs be supported in addition to Endpoints? I could take this on of that's in line with the overall design vision.

**Comment by brancz** [comment]
> I could take this on of that's in line with the overall design vision.

It is! :slightly_smiling_face: In fact it's one of our longest standing open issues: https://github.com/coreos/prometheus-operator/issues/38.

If you want to get started on this we're more than happy to talk through and review designs.

**Comment by dilyevsky** [comment]
Great! I looked through #38 and agree with general idea of having separate `PodMonitor` (also maybe `StaticMonitor`) objects. I can start on this next week and will send design for review first.

**Comment by paulfantom** [comment]
PodMonitors are already implemented.
