### ISSUE TITLE
Generate the default kube-prometheus configuration from the jsonnet sources

### ISSUE THREAD

**Issue by dlespiau** [prometheus-operator/prometheus-operator#1924]
The default configuration as described in the [kube-prometheus README.md](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#configuration) file is currently maintained by hand, which lead to the documentation being out of sync with reality as shown by PR #1914.

From that PR emerged a plan to improve the situation. We could generate that part of the readme from the actual jsonnet code.

- Write jsonnet that dumps the _config object. It's all hidden fields and objects and we need to recursively traverse the config and convert it to non-hidden fields (for jsonnet to actually render it) and then somehow (maybe regex replace is good enough) replace all : with +:: for all non-value fields. 
- A way to template the README.md file so template + _config -> README.md. We can use [embedmd](https://github.com/campoy/embedmd) which we already use to include it into the readme with the generate make target.
- a test that ensure the README.md has been regenerated when something in _config changes.

**Comment by paulfantom** [comment]
Seems like #1914 solved the issue
