### ISSUE TITLE
How Can I add a different matchExpressions for my serviceMonitorSelector?

### ISSUE THREAD

**Issue by manuprometheus** [prometheus-operator/prometheus-operator#1940]
**What did you do?**
I have a service with a label other than k8s-app.
**What did you expect to see?**
Prometheus should discover my label.
**What did you see instead? Under which circumstances?**
I can see the Dropped status in Target Labels.
**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by manuprometheus** [comment]
Please let me know, How can I add my matchExpressions in the prometheus?

**Comment by brancz** [comment]
The selector you mentioned (`serviceMonitorSelector: {}`) will select all ServiceMonitors. Otherwise you are going to have to be more specific about your request. What exactly are you talking about? The kube-prometheus stack, helm, completely self-built?
