### ISSUE TITLE
Support for disabling default external_labels

### ISSUE THREAD

**Issue by crandles** [prometheus-operator/prometheus-operator#1961]
I have a use-case where I intend to deploy a Prometheus instance and need its external_labels to be empty, or possibly just skipping the labels added by default, so it can properly match against data through a remote_read configuration that is generated by a separate system.

Currently, I have been generating a custom config, but per the documentation this approach seems to be deprecated. Not sure how I'd introduce this to the API yet, but is this something that would be accepted? Offhand, this might require a new field to disable the generation of extra external_labels

**Comment by mxinden** [comment]
> properly match against data through a remote_read configuration

Can you further elaborate on this? Is dropping the labels on the second system also an option?

**Comment by crandles** [comment]
We are leveraging remote_write's from n unique Prometheus instances and utilizing remote_read queries from a much smaller set of "aggregated" Prometheus instances, which would require the ability to match against Prometheus' with varied `prometheus`/`prometheus_replica` labels. 

I realize we might be heading towards un-supported use cases, and that there are other methods for aggregating / federating data (thanos, m3, etc); we are evaluating those products but intend to use remote_read & remote_write in the interim.

**Comment by brancz** [comment]
You can use remote write relabelling to remove these, this is actually the recommended way as you still want the external labels in other cases (this is very similar to alert relabelling being necessary in this case).

**Comment by yhekma** [comment]
I have a similar use case, but removing write is not an option. I want prometheus to keep using the labels when writing, but don't want the labels to be applied as a filter when using remote_read. My first thought was to move `external_labels` to the `write_relabel_configs` so the metrics end up in the remote backend with the correct label, but I can query metrics put there by other prometheus's (promethii?), but currently this is not possible.

**Comment by brancz** [comment]
Is this still a use case you have not been able to solve otherwise?

**Comment by weisdd** [comment]
There are two options now that can be useful for removing default external labels: prometheus.prometheusSpec.eplicaExternalLabelNameClear and prometheus.prometheusSpec.prometheusExternalLabelNameClear.

**Comment by paulfantom** [comment]
Closing as this is already possible with `prometheusExternalLabelName` and `replicaExternalLabelName` in [PrometheusSpec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) as mentioned in https://github.com/prometheus-operator/prometheus-operator/issues/1961#issuecomment-697890661
