### ISSUE TITLE
Option --set pspEnable=false doesn't allow kube-prometheus to be installed

### ISSUE THREAD

**Issue by caiobegotti** [prometheus-operator/prometheus-operator#1963]
**What did you do?**

```
helm install  --name prometheus-kube  \
--namespace monitoring -f yamls/prometheus-kube-values.yaml \
charts/kube-prometheus-0.0.96.tgz \
--set prometheus.image.repository=10.4.240.36:5000/quay.io/prometheus/prometheus \
--set alertmanager.image.repository=10.4.240.36:5000/quay.io/prometheus/alertmanager \
--set pspEnable=false  --set rbacEnable=false
```
**What did you expect to see?**

The chart to be installed with RBAC and PSP disabled. I thought #960 and PR 917 would have solved this.

**What did you see instead? Under which circumstances?**

During chart installation, I got this:

```
Error: release prometheus-kube failed: clusterroles.rbac.authorization.k8s.io "psp-prometheus-kube-alertmanager" is forbidden: attempt to grant extra privileges: \
[{[use] [extensions] [podsecuritypolicies] [prometheus-kube-alertmanager] []}] \
user=&{system:serviceaccount:kube-system:default 9b9efc11-972f-11e8-92ac-005056b95113 \
 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] \
map[]} ownerrules=[] ruleResolutionErrors=[clusterroles.rbac.authorization.k8s.io "cluster-admin" not found]
```
As if PSP was actually enabled, ignoring my `pspEnable=false` flag.

**Environment**

* Prometheus Operator version:

	kube-prometheus-0.0.96.tgz

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	Canonical CDK (upstream Kubernetes on-prem).

**Comment by caiobegotti** [comment]
Hey folks! Is there anything I can try or do to help you and debug this further?

**Comment by vsliouniaev** [comment]
@caiobegotti I think part of the issue is that the helm charts have been in the process of being migrated to https://github.com/helm/charts. This is now complete, could you see if this fixes your issue. There are significant changes to the way the chart is deployed between here and helm/charts

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
