### ISSUE TITLE
setting apiserverConfig in prometheus manifest changes all alertmanagers as well as the scrape_configs

### ISSUE THREAD

**Issue by sudomakeinstall2** [prometheus-operator/prometheus-operator#2012]
We have a kubernetes cluster called working cluster. We want to monitor services running in this cluster from another kubernetes cluster called monitoring cluster. We can access services and endpoints in working cluster from our monitoring cluster by:

1. Setting `apiserverConfig` in prometheus manifest. `host` is the address of working cluster apiserver and we use `bearer_token` an `caFile` of a `ServiceAccount` in working cluster that has access to the endpoints and services we want to monitor.
2. Creating a proxy pod in working cluster
3. Setting `proxyUrl` of the service monitors to the proxy pod

The problem is by setting `apiserverConfig` in prometheus manifest all of the alertmanagers and `scrape_configs` try to use that api_server. This leads to two problems:

1. We have to deploy our alertmanagers in the working cluster instead of the monitoring cluster.
2. We can't use different configs(api_server, tls_config) for different service monitors. This limits us to monitor only one cluster with one `ServiceAccount`.

We think setting `apiserverConfig` in prometheus manifest should set default value for alertmanagers and scrape_configs but the ability to override this default value for each service monitor and alertmanager will be a very good feature.

* Prometheus Operator version:

	quay.io/coreos/prometheus-operator:v0.24.0

* Kubernetes version information:
```

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```

* Kubernetes cluster kind: 

	kubeadm

**Comment by brancz** [comment]
Can you elaborate why you want to do this? The recommended way is to run another Prometheus server in the other cluster. There are too many failure scenarios that would prevent you from monitoring your workload in the other cluster.

**Comment by brancz** [comment]
I'd recommend going a different route. The recommended way to solve the problem you have is to setup a Prometheus server per cluster, and then use Prometheus federation to ingest all the metrics into a centralized Prometheus server. If this load is too high, then you may want to look into [Thanos](https://github.com/improbable-eng/thanos), which we're also integrating more tightly into :slightly_smiling_face: .

**Comment by sudomakeinstall2** [comment]
Thanks for your suggestion. But our requirements are different. We need isolated prometheus instances so that our users could only have access to their own metrics.

Currently we are considering using `additionalScrapeConfigs` and `additionalAlertManagerConfigs` to overcome our problems.

**Comment by brancz** [comment]
Those would allow you to set arbitrary Prometheus configuration. Given that you don't want to follow best practices I think it's your best choice :slightly_smiling_face: .

**Comment by Purushotham233** [comment]
> Can you elaborate why you want to do this? The recommended way is to run another Prometheus server in the other cluster. There are too many failure scenarios that would prevent you from monitoring your workload in the other cluster.

@brancz ,
Am trying to comprehend your recommendation against the common monitoring cluster for multiple  workload cluster? Could you point out the failure scenarios that you were referring to in this approach.

In the process of migrating our workloads to k8s, we are also planning to take common monitoring cluster approach which scrape the targets from multiple workload cluster and then relay the metric via remote-write to our existing metrics store which has its owning alerting and dashboard capabilities. Please share recommendation/concerns you could see w.r.to our scenario. Thanks.

**Comment by brancz** [comment]
Generally speaking Prometheus is designed to run as close as possible to the workload it monitors. This is to cut out any possibilities of failures between the Prometheus server and the workload, to truly monitor the workload, instead of the surrounding networking/proxies/etc. which can cause transient failures that nominally have nothing to do with the workload itself.
