### ISSUE TITLE
`Prometheus Operator` constantly overwrites `prometheus-operated` Service, which makes it impossible to add custom labels and annotations

### ISSUE THREAD

**Issue by yskopets** [prometheus-operator/prometheus-operator#2018]
**What did you do?**

I use `kubectl label` and `kubectl annotate` to add custom metadata to the `prometheus-operated` Service managed by `Prometheus Operator`.

**What did you expect to see?**

I expect `Prometheus Operator` to preserve my custom metadata.

**What did you see instead? Under which circumstances?**

`Prometheus Operator` constantly overwrites `prometheus-operated` Service (see the attached Kubernetes Master logs). As a result, my custom metadata get lost immediately.

**Other considerations?**

Notice that the above scenario (usage of `kubectl label` and `kubectl annotate`) is simply a minimal configuration to reproduce the issue.

In practice, I have another Operator who adds those custom labels and annotations.

Since `Prometheus Operator` reverts changes made from outside, `prometheus-operated` Service gets updated multiple times per second which has negative impact on other components inside Kubernetes cluster (namely, Istio and side-car Envoy proxies).

Would it be possible for `Prometheus Operator` to avoid reverting  external changes to metadata ?

**Environment**

* Prometheus Operator version:

v0.23.2

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.6", GitCommit:"06898a4d0f2b96f82b43d9e59fa2825bd3d616a2", GitTreeState:"clean", BuildDate:"2018-10-02T17:32:01Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

GKE

* Manifests:

N/A

* Prometheus Operator Logs:

N/A

* Kubernetes Master Logs

```
kubectl get --raw /logs/kube-apiserver.log
```

```
I1016 12:28:40.159052       1 wrap.go:42] PUT /api/v1/namespaces/monitoring/services/prometheus-operated: (4.260558ms) 200 [[operator/v0.0.0 (linux/amd64) kubernetes/$Format] 10.19.9.3:59198]
I1016 12:28:40.224666       1 wrap.go:42] PUT /api/v1/namespaces/monitoring/services/prometheus-operated: (5.032685ms) 200 [[operator/v0.0.0 (linux/amd64) kubernetes/$Format] 10.19.9.3:59198]
I1016 12:28:41.187665       1 wrap.go:42] PUT /api/v1/namespaces/monitoring/services/prometheus-operated: (4.718741ms) 200 [[operator/v0.0.0 (linux/amd64) kubernetes/$Format] 10.19.9.3:59198]
I1016 12:28:43.149276       1 wrap.go:42] PUT /api/v1/namespaces/monitoring/services/prometheus-operated: (4.391274ms) 200 [[operator/v0.0.0 (linux/amd64) kubernetes/$Format] 10.19.9.3:59198]
I1016 12:28:43.650184       1 wrap.go:42] PUT /api/v1/namespaces/monitoring/services/prometheus-operated: (4.502001ms) 200 [[operator/v0.0.0 (linux/amd64) kubernetes/$Format] 10.19.9.3:59198]
I1016 12:28:45.165035       1 wrap.go:42] PUT /api/v1/namespaces/monitoring/services/prometheus-operated: (5.077554ms) 200 [[operator/v0.0.0 (linux/amd64) kubernetes/$Format] 10.19.9.3:59198]
I1016 12:28:45.223850       1 wrap.go:42] PUT /api/v1/namespaces/monitoring/services/prometheus-operated: (4.605387ms) 200 [[operator/v0.0.0 (linux/amd64) kubernetes/$Format] 10.19.9.3:59198]
I1016 12:28:47.159427       1 wrap.go:42] PUT /api/v1/namespaces/monitoring/services/prometheus-operated: (4.468036ms) 200 [[operator/v0.0.0 (linux/amd64) kubernetes/$Format] 10.19.9.3:59198]
I1016 12:28:47.752966       1 wrap.go:42] PUT /api/v1/namespaces/monitoring/services/prometheus-operated: (5.045946ms) 200 [[operator/v0.0.0 (linux/amd64) kubernetes/$Format] 10.19.9.3:59198]
I1016 12:28:48.762769       1 wrap.go:42] PUT /api/v1/namespaces/monitoring/services/prometheus-operated: (6.850416ms) 200 [[operator/v0.0.0 (linux/amd64) kubernetes/$Format] 10.19.9.3:59198]
I1016 12:28:49.154670       1 wrap.go:42] PUT /api/v1/namespaces/monitoring/services/prometheus-operated: (4.940992ms) 200 [[operator/v0.0.0 (linux/amd64) kubernetes/$Format] 10.19.9.3:59198]
```

**Comment by brancz** [comment]
I think this is reasonable with the note that the labels that the operator puts on there today will always be overwritten should a user set it to a different value. Would you like to create a PR to allow doing this?

**Comment by yskopets** [comment]
@brancz Sure, I can do that.

**Comment by paulfantom** [comment]
Labels and annotations should be preserved during reconciliation. This issue is still valid.

**Comment by Szymongib** [comment]
Hi @paulfantom, could I work on that one?

From what I see the implementation is slightly different for some resources like Services and StatefulSets. I wonder if we would like to preserve labels and annotations for all resources, or just for Services and Endpoints for the start?

**Comment by paulfantom** [comment]
@Szymongib feel free to take it :+1: 

> I wonder if we would like to preserve labels and annotations for all resources

Yes :)
