### ISSUE TITLE
Documentation out-of-date

### ISSUE THREAD

**Issue by lswith** [prometheus-operator/prometheus-operator#2023]
After converting kube-prometheus to use kustomize instead of jsonnet, I've realised how hard it is to read and use the documentation for the Prometheus Operator.

I was hoping this could be improved as I think a large amount of issues could be resolved.

A Few key points:
- Thanos is mentioned in the repo but not on https://coreos.com/operators/prometheus
- v1 is now being used, but no update to the documentation or getting started guides
- RuleNamespaceSelector and ServiceMonitorNamespaceSelector are not mentioned in the docs at all
- no guidance into the specific kubernetes objects that the prometheus-operator creates (It took a while to figure out that the label 'operated-prometheus' was going to be added to the prometheus)

I may not be looking in the right spot or should just be reading the codebase but it would be lovely to have 1-place to read and understand how to use the operator.

**Comment by brancz** [comment]
Sorry for the divergence. The coreos.com docs are currently not being updated, so for the time being I'd recommend using GitHub as the source of truth (the `/Documentation` directory is exactly what is rendered on coreos.com, just and outdated version of it currently). If there is anything missing though that you think should be there, then please don't hesitate to open an issue, the core developers are often too close to the project to realize which details in docs are missing that users would like to know about, but we're more than happy to add those things :slightly_smiling_face: .

**Comment by elisiano** [comment]
@lswith off topic, did you publish your kustomize conversion anywhere?
I'd be curious to see how maintainable that is, given our engineering team developed a CI solution around kustomize/skaffold/bazel.

**Comment by lswith** [comment]
https://github.com/lswith/kustomize-prometheus-operator

**Comment by paulfantom** [comment]
Sadly this issue is still valid, however for a bit different reasons.

**Comment by simonpasquier** [comment]
We now have https://prometheus-operator.dev/ with all the operator's documentation. All improvements are welcome but this particular issue is too open-ended IMHO. Please file specific issues about what's missing/incomplete in the docs.
