### ISSUE TITLE
[Question] why setting different livenessProbeInitialDelaySeconds for different versions

### ISSUE THREAD

**Issue by christine-gong** [prometheus-operator/prometheus-operator#2106]
I checked the master branch and release 0.18 branch, they both treated the livenessProbeInitialDelaySeconds (0.18) or livenessFailureThreshold (master) differently.

The version >= 1.8 or 2+ always gets much less time for liveness probe check.
e.g. master https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L519-L561

release 0.18
https://github.com/coreos/prometheus-operator/blob/release-0.18/pkg/prometheus/statefulset.go#L492-L538

May I know why? We are using prometheus operator version 0.18 and prometheus 2.2. And we saw some issues on our side, and thought it could be not enough time to get ready and get restarted by failing the liveness and readiness check

And I checked the previous issues, looks like there is no way to configure those values from user side?

**Comment by brancz** [comment]
In Prometheus 1.x the recovery process of a crashed database is much more intense process, whereas in 2.x it is just linearly reading the write ahead log into memory which should be significant less long of an operation. If the time currently set is not good enough, we can treat that as a bug/feature request.

**Comment by christine-gong** [comment]
@brancz thanks for clarifying that! So is it possible to set those timeout / threshold from user side when launching prometheus pods using Prometheus operator by passing the those parameters under spec? I'd happy to create a feature request if it is not possible now

**Comment by brancz** [comment]
I’d prefer to keep config options to a minimum. Could you do some experiments and figure out what time-outs would work for you? (You can set the Prometheus object to “paused: true” and then you can modify the underlying StatefulSet) With the data you gather we can look at whether we should really make it configurable or just bump the value to something more reasonable. What do you think? :)

**Comment by krunalvora** [comment]
@brancz I am facing a similar issue but not sure how to troubleshoot the config options. Could you possible elaborate a bit more about how to use the paused:true feature to help troubleshoot the liveness probe and readiness probe timeouts we specifically need?

**Comment by brancz** [comment]
The PrometheusSpec has the `paused` field, when set to true then the Prometheus Operator will not attempt to reconcile that.

So within your Prometheus object something like this:

```yaml
spec:
  paused: true
```

**Comment by squat** [comment]
Hi @krunalvora, the process for determining an optimal `initialDelaySeconds` value that @brancz is describing is as follows:
1. create Prometheus Operator
2. create Prometheus object
    1. Prometheus Operator creates Prometheus StatefulSet
3. edit the Prometheus object and set `paused: true`
    1. Prometheus Operator will stop reconciling your Prometheus StatefulSet
4. adjust the `initialDelaySeconds` field to determine an optimal delay

**Comment by krunalvora** [comment]
Thank you @squat 😄 That's a step ahead for me.
Will let you guys know what optimal delay works for me.

**Comment by brancz** [comment]
We should probably just remove liveness probes to begin with or set them very high, compared to readiness probes.

**Comment by paulfantom** [comment]
liveness probes were removed in https://github.com/prometheus-operator/prometheus-operator/pull/3502
