### ISSUE TITLE
alertmanager and prometheus-k8s breaks podsecuritypolicy in 0.26

### ISSUE THREAD

**Issue by MarkDeckert** [prometheus-operator/prometheus-operator#2192]
It appears this commit removed security context required for common PodSecurityPolicy settings
https://github.com/coreos/prometheus-operator/pull/2109

Just wanted to create an actual issue for it.

**What did you do?**
Upgraded from 0.25 to 0.26

**What did you expect to see?**
All pods running

**What did you see instead? Under which circumstances?**
alertmanager and prometheus-k8s pods fail to start due to CreateContainerConfigError

* Prometheus Operator version:
0.26

* Kubernetes version information:
1.12.2

* Kubernetes cluster kind: 
kubeadm on bare metal

Copying and pasting a comment I made on the pull request referenced above:

> Also this breaks common PodSecurityPolicy rules that require explicitly setting runAsUser in the deployment.
> 
> I believe this is the default in openshift and gce, and most likely also in many bare-metal or self-managed k8s instances.
> 
> fsGroup would always need be set as well for mounted volumes although PodSecurityPolicy wouldn't explicitly require this setting in the yaml, it clearly would break PVs depending on what runAsUser is set to.

**Comment by brancz** [comment]
Yes we should fix this. I would suggest that we as a one off release set the security context of all prometheus objects to what we had before, and remove this "migration" for subsequent releases. What do you think?

**Comment by MarkDeckert** [comment]
It would make sense to just set the values as defaults.  I would go as far as to say it's always in general a good idea to explicitly define runAsUser and fsGroup options.  Just prevents a lot of edge cases.

**Comment by metalmatze** [comment]
Just letting you know in this issue that we merged a jsonnet/yaml based solution into the manifests: https://github.com/coreos/prometheus-operator/pull/2206

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.
