### ISSUE TITLE
Allowing duplicate rule names when collecting from different namespace should be prevented or optional

### ISSUE THREAD

**Issue by richerve** [prometheus-operator/prometheus-operator#2193]
**What did you do?**

Created PrometheusRules in several namespaces and gather them in a centralized cluster Prometheus.
Defined a rule in a namespace with the same name as another rule in a different namespace. Both rules are collected without errors even when they have the same name.

**What did you expect to see?**

The operator handles the duplicated Rule on creation time detecting that there's another rule in a different namespace with the same name.

**What did you see instead? Under which circumstances?**

The operator let the rule with the same name pass through and the last one definition overwrites the first one.

**Proposal**

Support an option to letting the operator decide if allowing duplicate rule names from different namespaces or not.

I basically want to have more isolation of PrometheusRules per namespace. Since the operator supports the collection of PrometheusRules from different namespaces, I think it makes sense to support options to isolate both rule groups (that must be unique anyway) and Prometheus rules too.

I know that Prometheus allows the definition of more than one rule with the same name because you can add more "dimensions" by using labels, for example, but in case of a multi-tenant cluster this is cumbersome because some people may define their own rules with the same name as others and therefore will overwrite them, in best case only changing labels, in worst case changing the expression and annotations. 

So I have the following proposal:

- Create a handler to check the rule names and if they're the same apply one of the following strategies:
    - Add the namespace name as prefix or suffix to the rule name on creation.
    - Fail immediately and let the user modify the name.
    - Allow duplicates.

**Comment by brancz** [comment]
Whatever the solution to this problem is, I think we should always apply it (if collision fix is to prefix the name, then we should always do that), my feeling was though that if rules are in different rule groups, that they would be able to be defined multiple times.

All problems aside, it feels to me that labelling alerts with their origin `PrometheusRule` object name and namespace sounds like a good idea, that would solve this and allow some more context to find where rules are defined when firing.

cc @mxinden

**Comment by richerve** [comment]
@brancz totally agree, we are doing that "manually" now by defining presets on Helm Charts but it's too hacky, not scalable and not dynamic so I think it's much better to do it in the operator itself.

**Comment by richerve** [comment]
@mxinden @brancz If this is of interest I think I can prepare a PR with this changes

**Comment by brancz** [comment]
I’m about to go on vacation. I’ll let @mxinden handle this, he also implemented the current PrometheusRule work.

**Comment by mxinden** [comment]
> I’m about to go on vacation. I’ll let @mxinden handle this, he also implemented the current PrometheusRule work.

Also on vacation till mid of January. Will come back to this afterwards. Sorry about the delay @richerve and thanks for the offer.

**Comment by richerve** [comment]
@mxinden is this still of interest?

**Comment by mxinden** [comment]
@richerve I am not involved in the Prometheus Operator development anymore. Maybe one of the maintainers can jump in?

**Comment by s-urbaniak** [comment]
@richerve yes, there is definitely still interest in this and we will actually have a more intense look at this issue :+1:

**Comment by pgier** [comment]
I was able to reproduce this, and I agree this is something we need to fix.  I created https://github.com/prometheus/prometheus/issues/6334 to potentially solve this in prometheus.
Currently, each prometheusrule object is mounted as a separate file in the configmap and is named according to the namespace and object where it comes from, so adding a label with this filename should be similar to what @brancz suggested previously.

**Comment by brancz** [comment]
Would just enforcing a label be sufficient or do we have to tinker with the rule (group) name?

**Comment by richerve** [comment]
@brancz I don't think I understand what you mean by "enforcing a label"? I think I would be happy if the rule names are prefixed with the namespace, and ideally the rule groups too, but I'm not completely sure about Prometheus' logic regarding duplicated groups with same name, is that possible? My only concern with this approach is that is sort of "magic" in the sense that alert names will have a new prefix and that could make difficult for silences and/or routing, but in any case if it's an optional parameter and correctly documented, don't think it's a big issue

**Comment by pgier** [comment]
The group names already won't conflict since they are also qualified by the rule filename which is based on the namespace and prometheusrule object name.  So you would only get a group conflict if you had two groups with the same name in the same prometheusrule.

**Comment by pgier** [comment]
> @brancz I don't think I understand what you mean by "enforcing a label"? 

@richerve I think he means could we just use a namespace label instead of modifying the rule names?

One potential problem with modifying the rule names is that recording rules that depend on the results of previous rules would not work correctly.
