### ISSUE TITLE
Allow ENV substitution in alertmanager config

### ISSUE THREAD

**Issue by robinro** [prometheus-operator/prometheus-operator#2213]
**What did you do?**
Use an alertmanager config that needs additional variables/secrets.

**What did you expect to see?**
A way to customize/extend a given config by substituting variables.

**What did you see instead? Under which circumstances?**
Only a static config is possible.

**Environment**

* Prometheus Operator version:
v0.25.0

Basically, I'd like to be able to specify the majority of the config via a field in the `Alertmanager` CRD (or a config map), while some parts (especially API keys for receivers) can be substituted from secrets that are already present in the cluster.

Potential solutions:
* Use something like the setup for prometheus with a config template and `prometheus-config-reloader` to substitute variables in the config before passing it to prometheus: This would need a replacement of config-reloader with prometheus-config-reloader (or sth. similar) for the alertmanager as well as a way to mount secrets as env (not files).
* Have another sidecar (user defined via the `containers` field?) that reads the secrets/configmaps and creates a final config: Sidecar/mounts are already possible (see #2028 and related), this would only need a way to pass the resulting config to alertmanager (common, writeable mount) and specify a different config name (like #2024).

I'll be happy to contribute a PR following one of the ideas above or another suggested solution. I'm looking forward to your feedback.

**Comment by brancz** [comment]
Can you be more specific in what you want to do, and why you can't have the values in the Alertmanager configuration directly?

**Comment by robinro** [comment]
We have the alertmanager config stored in the respository along the rest of the infrastructure code. This is reused for dev/testing/prod. Secrets are not allowed there.
The API keys depend on the environment they are deployed to and are stored in the cluster as secrets. I'd like to combine generic config and environment-specific secrets only in the cluster. For many services this is possible by mounting secrets into the pods as env variables or files.
Our current workaround for alertmanager (using the stable/prometheus chart) is to generate a configmap containing the final config in the cluster and load it via `configMapOverrideName`.
I'd much rather use prometheus-operator, though.

**Comment by richerve** [comment]
Hi @robinro,

I remember talking with @brancz about this in Kubecon Europe. If I understand correctly what you're asking is for having a "ServiceMonitor" kind of CRD for Alertmanager, or basically building the AM config based fields in a CRD. I had the same need for allowing custom definition of routes in a multi-tenant cluster and thought about building a PR to tackle that, then I soon realized that it will be somewhat complicated.

For specifying the receivers might not be that difficult because order doesn't matter but for building the routing tree it will require building a probably very complicated API in the CRD in order to define parent-child relationships.

As for splitting config and secrets, it will be a similar case as explained before, the Alertmanager config should be treated as a whole so for example in our case, we use a Secret for the whole config and that's managed by the cluster admins.

**Comment by nabadger** [comment]
One problem with treating alertmanager config as a whole is with code-reviews - you now have to decode the data in the file or un-encrypt it (if using SealedSecrets etc). 

This makes merge-requests to the config a real pain. As mentioned above, this is a specific issues (probably) with the receivers which tend to have auth. information in them.

**Comment by wy100101** [comment]
I actually like the idea of being able to supply a templated ConfigMap that gets converted to expanded version in the secret used by alertmanager. I'm currently planning to store the templated config in git and then have the ci-cd system hydrate the secrets from vault.

**Comment by kskewes** [comment]
Whilst it's not pretty, we have the same issue and have done some hacks as per the gist at bottom.

Can definitely be improved (`std.mapWithKey()`?, overrides location) and would appreciate suggestions too.

```
// environment files - must be last so can override defaults
local env_config = (import 'prometheus-config.jsonnet');
local prometheusSecrets = import 'prometheus-secrets.libsonnet';

local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') + snippets + mixins + env_config {
  _config+:: {
    // Alertmanager Config Overrides - such as custom routing based on sev/label/etc (per env)
    alertmanagerOverrides+:: {},

    alertmanager+:
      // Alertmanager uses a YAML file alertmanager.yaml for configuration, however:
      // 1. We store our secrets separately.
      // 2. We have overrides per environment (ie: staging don't page, redirect to slack).
      // So we have converted YAML to jsonnet (outside this workflow), then import jsonnet here and use standard
      // jsonnet object comprehension to inject secrets, environment overrides, etc.

      local alertmanagerConfigFile = import 'alertmanager-config-defaults.jsonnet'; // this could be done below as part of `local alertmanagerConfigJson`

      // Below function and temp variable walk an array and if index matches then update the contents
      // TODO: Something better not dependent on array order
      local add_by_index(i) = (
        if i == 1 then { pagerduty_configs: [{ routing_key: prometheusSecrets.alertmanager.pagerduty_routing_key_teamXYZ }] }
        else if i == 2 then { pagerduty_configs: [{ routing_key: prometheusSecrets.alertmanager.pagerduty_routing_key_sre }] }
        else if i == 3 then { pagerduty_configs: [{ routing_key: prometheusSecrets.alertmanager.pagerduty_routing_key_support }] }
        else {}
      );

      // Override Alertmanager config with our changes
      local alertmanagerConfigJson = alertmanagerConfigFile {
        global+: {
          slack_api_url: prometheusSecrets.alertmanager.webhook_url,
        },
        receivers: std.mapWithIndex(function(i, v) v + add_by_index(i), alertmanagerConfigFile.receivers),
        templates+: [
          '/etc/alertmanager/config/alertmanager-slack.tmpl',
        ],
      } + $._config.alertmanagerOverrides;

      // Output final Alertmanager YAML
      {
        config: std.manifestYamlDoc(alertmanagerConfigJson),
      },

    /* <snip> */
    },
  },
};
```

**Comment by ingvarm-gr** [comment]
What we do for this case is that the "secret" bits are stored in whatever vault solution the CI/pushing tool uses, then the secrets are template-expanded as part of the pushing.

Keeping the entire alertmanager config as secret isn't really a maintainable position, long-term.

**Comment by abursavich** [comment]
I was hoping for an Alertmanager Config custom resource to come out of this and #2258, but it's been a while now, so we've open sourced our solution to this problem: [ConfigMapSecrets](https://github.com/machinezone/configmapsecrets).  We've been running it in production for a few months without any issues.

A ConfigMapSecret is like a ConfigMap that includes your non-secret data, but it can reference Secret variables, similar to how container args can reference env variables. The controller will expand and render it into a Secret in the same namespace, keeping it updated to reflect changes to the ConfigMapSecret and its referenced variables.

 Hopefully, it will be useful to people here and in similar situations.

**Comment by paulfantom** [comment]
This is superseded by https://github.com/prometheus-operator/prometheus-operator/pull/3451 (Alertmanager CRD)
