### ISSUE TITLE
FR: Support []SecretVolumeSource in Prometheus spec

### ISSUE THREAD

**Issue by tamalsaha** [prometheus-operator/prometheus-operator#2251]
Currently Prometheus spec supports `Secrets []string` so that we can provide various TLS certificates needed for scraping. But usually those secrets have both tls.crt and tls.key in them. We would like to not mount the tls.key inside Prometheus StatefulSet pod. One option will be to create a separate secret containing only the tls.crt key.

I think a better option will be to add a new field to Prometheus spec called

`SecretVolumes []SecretVolumeSource`

Now, we can use `items` field to only mount the tls.crt inside Prometheus pod.

xref: 

- https://github.com/coreos/prometheus-operator/blob/77764ee4239f2a8a7917883651f9e92ea3c52924/pkg/prometheus/statefulset.go#L468

- https://github.com/coreos/prometheus-operator/blob/77764ee4239f2a8a7917883651f9e92ea3c52924/vendor/k8s.io/api/core/v1/types.go#L1044:6

What do you folks think?

**Comment by brancz** [comment]
I'm happy to have some kind of support for this. I'm not sure about the API though, but happy to discuss it.

**Comment by brancz** [comment]
Is first class API support still required for this? If not then I'd suggest to do this by merging content into the container by container name in the `containers` array.
