### ISSUE TITLE
Modifications to ServiceMonitor or it's dependencies not triggering reload

### ISSUE THREAD

**Issue by briantopping** [prometheus-operator/prometheus-operator#2346]
**What did you do?**

Set up Prometheus Operator and got it running. It was difficult to debug because the operator did not respond in a manner that I expected.

**What did you expect to see?**
If I create a `ServiceMonitor` that cannot result in a target being generated, it should generate log errors. If I change anything to do with a `ServiceMonitor` (including it's `Service` or `Endpoint`), the changes should regenerate immediately

**What did you see instead? Under which circumstances?**
* If the `ServiceMonitor` dependencies were insufficient to generate the Prometheus target, the process silently fails.
* Making changes to these dependencies (`Service`, `Endpoint`, etc) does not cause the configuration to regenerate. 
* Even if a change is made directly to a `ServiceMonitor`, it is only picked up every three minutes (at least on my machine). (This may be a misconfiguration on my end.)

**Environment**
```
# uname -a
Linux node.example.com 4.20.3-1.el7.elrepo.x86_64 #1 SMP Wed Jan 16 19:37:14 EST 2019 x86_64 x86_64 x86_64 GNU/Linux`
# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
```

* Prometheus Operator version:

```
quay.io/coreos/prometheus-operator:v0.25.0
quay.io/coreos/prometheus-config-reloader:v0.25.0
quay.io/coreos/configmap-reload:v0.0.1
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: `kubeadm`

**Comment by iMartyn** [comment]
I believe we have the same issue here, we set up with 0.20.0 originally, servicemonitors created config and reloaded prometheus with the new targets, all good.  a few months later (yeah, we've been busy) we changed the servicemonitors but the secret containing the scrape config hasn't changed.

Things we have tried to no avail :
* Delete service monitor and recreated it
* Upgraded the image to 0.28.0
* Enabled --loglevel=debug and did the same (see "Servicemonitor deleted" "Servicemonitor added" in the log)
* Emptied the secret of all scrape targets and then recreated servicemonitors
* Deleted the secret completely and recreated servicemonitors.

In *ALL* the above scenarios, the secret is untouched.

Our cluster is an AKS cluster fwiw.

**Comment by brancz** [comment]
> If the `ServiceMonitor` dependencies were insufficient to generate the Prometheus target, the process silently fails.

Could you be more specific about this? If you specify the `selector` in a `Service` object incorrectly, that also "silently" fails, how is this different, or how would you have expected it to work. So far the community has accepted this pretty well, as it works like all the rest of Kubernetes: with label selectors.

We would like to add some better diagnostics, such as a status in the `ServiceMonitor`, the only difficulty this brings with it, is the Prometheus Operator has to communicate with the Prometheus server, and we need to make sure this happens in a secure way. We definitely want to work on this, but it's a larger effort.

> Making changes to these dependencies (`Service`, `Endpoint`, etc) does not cause the configuration to regenerate.

This is because Prometheus itself discovers these, the configuration just tells it how to pick exactly those that you want.

> Even if a change is made directly to a `ServiceMonitor`, it is only picked up every three minutes (at least on my machine). (This may be a misconfiguration on my end.)

This is unfortunately because of how Kubernetes works. When you update a secret/configmap it takes up to 5 minutes for this configmap/secret to be re-mounted into the running pod/container.

**Comment by briantopping** [comment]
> Could you be more specific about this? If you specify the `selector` in a `Service` object incorrectly, that also "silently" fails, how is this different, or how would you have expected it to work. So far the community has accepted this pretty well, as it works like all the rest of Kubernetes: with label selectors.

Sure. I appreciate that things are passable as they stand, my notes on the issue were just what I found difficult to connect. Sometimes that's harder to see one one has gotten used to a system, so I thought I would share.

> If I create a `ServiceMonitor` that cannot result in a target being generated, it should generate log errors. 

What I mean by this is it would be beneficial if the target could be preflighted before the configuration is sent off to Prometheus. If the connection to the target could not be made by the controller, a warning could be generated. Of course, there are endless configurations and network policies, so the configuration shouldn't fail, but if it was able to automate a warning, users could be more productive.

>> If I change anything to do with a `ServiceMonitor` (including it's `Service` or `Endpoint`), the changes should regenerate immediately

> This is unfortunately because of how Kubernetes works. When you update a secret/configmap it takes up to 5 minutes for this configmap/secret to be re-mounted into the running pod/container.

Couldn't a watch be placed on the resource through the API endpoint? I haven't written one yet, but it does seem possible.

**Comment by brancz** [comment]
I don't think a pre-flight is realistic for various reasons, but we do definitely need _some_ status information on targets discovered by a ServiceMonitor, I think how we gather that is a detail. I have some ideas in mind, I hope we can get to this rather sooner than later, I agree and understand this is a missing piece for ServiceMonitor's UX.

> Couldn't a watch be placed on the resource through the API endpoint? I haven't written one yet, but it does seem possible.

Yes this is possible, but has various scalability implications. My idea about this is that if we had a secure channel between the Prometheus Operator and the Prometheus servers (which doesn't exist today, but seems viable) then we could build a similar level trigger as the kubelets with the apiserver to update Prometheus servers and communicate status back and forth. This would make the Prometheus Operator somewhat similar to how vitess works. This is a pretty significant effort, but I think the right one.

**Comment by briantopping** [comment]
Great, thanks for the consideration, @brancz. I definitely didn't want to create more work or dwell on solutions where I have no experience, just provide feedback on the most difficult part of the deployment experience. Even little hints like "checking again in X minutes" could give users who bothered to look at the logs the feedback they needed to be successful.

**Comment by iMartyn** [comment]
I agree, the log lines are very sparse even in debug mode there's nothing telling us why our servicemonitors have been ignored.  That's just mean really.  In our particular case I know it's reading the servicemonitor, but the secret is no longer being updated, there's no log saying "writing prometheus config of x scrape targets" or anything along these lines that would help me debug the issue, even in debug mode.

**Comment by brancz** [comment]
I still think the UX deserves to be worked on here.

**Comment by jecnua** [comment]
Please remove the stale label again.

**Comment by simonpasquier** [comment]
This sounds similar to #3335.
