### ISSUE TITLE
Additional Scrape Configuration only with service monitor attached

### ISSUE THREAD

**Issue by Deshke** [prometheus-operator/prometheus-operator#2452]
**What did you do?**

created a additional configuration without a service monitor

-> https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md

**What did you expect to see?**

the additional configuration within prometheus

**Environment**

* Prometheus Operator version:

	0.29.0

**steps to reproduce** 

* create a prometheus configuration without a serviceMonitor configuration but with a additonal scrape configuration
* watch the secret being created by the prometheus-operator
* the secret is empty     
![image](https://user-images.githubusercontent.com/1473225/53720940-38aba180-3e62-11e9-9f5c-20e01c3585c8.png)
* add a dummy serviceMonitor configuration (just within prometheus, config must not exist)
* watch the secret again     
![image](https://user-images.githubusercontent.com/1473225/53720986-56790680-3e62-11e9-9241-593a6769cd35.png)

**Comment by brancz** [comment]
Before additional scrape configs skipping the servicemonitorselector was an undocumented side effect that allowed users to manage the config themselves. With the addition of additionalScrapeConfigs and gzipping the config this has become completely unreasonable though, I believe.

I think we should remove this behavior, and treat an unspecified (`nil`) selector just as not selecting any `ServiceMonitor` objects but still managing the rest of the config.

What do you think @squat @mxinden @s-urbaniak @metalmatze ?

**Comment by abh** [comment]
Just for what it's worth, I ran into this too when upgrading a setup from a very old version of the operator. I use the operator to, uh, operate Prometheus instances that scrape targets outside Prometheus.

**Comment by Deshke** [comment]
issue is still there, not sure if anyone worked on it

**Comment by LiliC** [comment]
@Deshke do you want to work on it, we happily accept PRs :)

**Comment by paulfantom** [comment]
I do believe this is implemented already. If you think this issue is still valid, please reopen it.
