### ISSUE TITLE
Prometheus/Alertmanager have no custom port mapping

### ISSUE THREAD

**Issue by Tzrlk** [prometheus-operator/prometheus-operator#2487]
**What did you do?**
Deployed the manifests and attempted to narrow the port usage to fit within the security group ranges open between worker nodes in my cluster.

**What did you expect to see?**
The CRDs for Prometheus and Alertmanager containing a property allowing me to specify which port the internal service gets exposed on.

**What did you see instead? Under which circumstances?**
There is no property like this, though I can probably work around it by using `spec.listenLocal` and adding a sidecar container to proxy the connection.

**Environment**

* Prometheus Operator version:

	af2718f64082cb86afb661c13acef1598f57c904
        quay.io/coreos/prometheus-operator:v0.29.0

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	EKS via CloudFormation

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind:       Alertmanager
metadata:
  namespace: monitoring
  name:      main
  labels:
    alertmanager: main
spec:
  baseImage:          quay.io/prometheus/alertmanager
  version:            v0.16.0
  replicas:           3
  serviceAccountName: alertmanager-main
  securityContext:
    fsGroup:      2000
    runAsNonRoot: true
    runAsUser:    1000
  nodeSelector:
    beta.kubernetes.io/os: linux
```

* Prometheus Operator Logs:

```
not relevant
```

**Comment by brancz** [comment]
Can you elaborate further why the default ports are not an option?

**Comment by Tzrlk** [comment]
It's not so much that they're not an option, it's that I have to add and maintain additional security rules in the AWS security groups because I can't just set it to 8080.

**Comment by brancz** [comment]
Aren't security groups for cross host communication? Why does that influence the choice of a port of a pod?

**Comment by Tzrlk** [comment]
Because my pods are running on different hosts in the cluster, and even if they weren't, the AWS CNI plugin causes all pods to have allocated ip addresses within the VPC. This means that even if the pods are only communicating with one another on the same node, I have to make sure there's a rule in place to allow the machine to communicate with itself.

**Comment by brancz** [comment]
Ok. I'm generally not against this. Would you like to give it a try at implementing this?

**Comment by Tzrlk** [comment]
Sure, though because I haven't done Go development before, it'll take me some time to get familiarised with the development environment and testing process. I also won't be able to get to it for a while, as I've already had to put a workaround in place, deprioritising any work time I could potentially spend on this.

**Comment by brancz** [comment]
Let us know if we can be of guidance :)
