### ISSUE TITLE
Add additionalPrinterColumns in CRDs

### ISSUE THREAD

**Issue by aylei** [prometheus-operator/prometheus-operator#2537]
**What is missing?**
`kubectl get prometheus` and `kubectl get alertmanager` prints less-informative message:
```shell
kubectl get prometheus
NAME   CREATED AT
k8s    11d

kubectl get alertmanger
NAME   CREATED AT
main   12d
```

Starting with Kubernetes 1.11, CRD spec supports [`additionalPrinterColumns` definition](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns), which helps printing more informations of `Prometheus` and `Alertmanager` resources.

**Why do we need it?**
For better `kubectl` exploring experience of custom resources provided by Prometheus Operator.

**Comment by brancz** [comment]
What do you think would be useful information to show? Replicas are an obvious one I'd say. Anything else? (maybe that's a start already)

**Comment by metalmatze** [comment]
I'd like to see retention and the configured Alertmanager to show up as columns. Something along the lines of `alertmanager.monitoring` (service name and namespace) would be helpful.

**Comment by brancz** [comment]
Yes I like the idea of covering retention

**Comment by bgagnon** [comment]
Namespace/ServiceMonitor selectors would be useful to see as well

**Comment by Mathis-Z** [comment]
additionalPrinterColumns uses JSONPath to find the information for the objects but this is limited to "simple JSONPath". Apparently it is not possible to print multiple elements of a list. This means it is not possible to print the names of the configured alertmanagers or the serviceMonitorSelectors. However it would be possible to output them in JSON format which would give you all information about the configured alertmanagers/serviceMonitorSelectors/... but would also mess up your cmd.
Maybe a "solution" to this was to output attributes that are lists only if "-o wide" is specified and then output them in JSON format.

**Comment by simonpasquier** [comment]
Prometheus, Alertmanager and ThanosRuler resources will now include additional columns. For the other CRDs, it depends on implementing the status sub-resource which isn't resolved yet (https://github.com/prometheus-operator/prometheus-operator/issues/3335).

Since this issue was specifically about the Prometheus (and alike) resources initially, we've decided during our bi-weekly office hours to close this issue for now.
