### ISSUE TITLE
Prometheus can't access node-exporter metrics

### ISSUE THREAD

**Issue by infyDavis** [prometheus-operator/prometheus-operator#2555]
**What did you do?**
```
git clone ...prometheus-operator
cd prometheus-operator/contrib/kube-prometheus
kubectl apply -f manifests/
```

**Did you expect to see some different?**
no data for node-exporter metrics through prometheus webapp ```https://IP:9090/graph```

All targets for node-exporter on webapp have state ```UP``` no errors here

I can see node-exporter metrics through ```curl localhost:9100/metrics``` on nodes

**Environment**

* Prometheus Operator version:

    `prometheus-operator:v0.29.0`
    

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:05:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: kubeadm

* Manifests: n/a

* Prometheus Operator Logs:

node-exporter logs (only issue I'm seeing)
```
time="2019-04-12T16:21:32Z" level=error msg="ERROR: ntp collector failed after 0.482846s: couldn't get SNTP reply: read udp 127.0.0.1:34190->127.0.0.1:123: read: connection refused" source="collector.go:132"
```

**Anything else we need to know?**:

The cluster doesn't have internet access.  I had to manually load all docker images.

**Comment by brancz** [comment]
> time="2019-04-12T16:21:32Z" level=error msg="ERROR: ntp collector failed after 0.482846s: couldn't get SNTP reply: read udp 127.0.0.1:34190->127.0.0.1:123: read: connection refused" source="collector.go:132"

This error can be safely ignored as you just don't seem to have an ntp daemon running (you probably should, but don't _have to_). All other node-exporter things are still functional. Can you explain what metrics you expected to see, but didn't see?

**Comment by infyDavis** [comment]
@brancz I expected to see any metrics from node exporter on the web-app.  

For example I see ```node_memory_Cached_bytes 5.0248482816e+10``` if I ```curl localhost:9100/metrics``` on one of the nodes but don't see this metric through the web-app.  I ultimately want to see the metrics in grafana but there is no data there either.

<img width="1680" alt="Screen Shot 2019-04-15 at 7 50 59 AM" src="https://user-images.githubusercontent.com/48572544/56142582-ca272c80-5f53-11e9-8f39-ad44b93be0d6.png">

**Comment by brancz** [comment]
That seems curious, are you sure all node-exporters are `up` and you are not missing any targets? As in you're seeing a node-exporter being up for each node in your cluster?

**Comment by infyDavis** [comment]
Yea all node-exporters are up.

I just restarted prometheus today.

One alertmanager target has an error ```Get http://172.17.0.14:9093/metrics: dial tcp 172.17.0.14:9093: connect: no route to host```

and grafana target has error ```Get http://10.244.6.91:3000/metrics: context deadline exceeded```

I've recreated prometheus on my cluster multiple times and these targets are sometimes up and sometimes down. I ignored it for now as I want to resolve the node-exporter issue.

One of the node-exporter pods on a specific node has always had a 
```Back-off restarting failed container``` error 
  and the logs say 
```time="2019-04-15T15:43:36Z" level=fatal msg="listen tcp 127.0.0.1:9100: bind: address already in use" source="node_exporter.go:114"```
but the node-exporter target for this node on the web-app is still up for some reason.

Do all the node-exporter pods for each node have to be running in order to get metrics?

**Comment by matkam** [comment]
I'm noticing something similar. No metrics are logged with Prometheus. I can kill and restart the `kube-state-metrics` pod and everything will work fine for about 15 minutes.

**Comment by brancz** [comment]
> Do all the node-exporter pods for each node have to be running in order to get metrics?

No. Any node-exporter that is running is scraped.

**Comment by jeffhoffman13** [comment]
I have Prometheus and Grafana running on localhost via docker-compose file.

I have node_exporters running on two other nodes and I can curl their metrics so the network between nodes semm ok.

How can I connect external node_exportters to a docker container on a diffrent host?

**Comment by brancz** [comment]
@jeffhoffman13 the Prometheus Operator is about running Prometheus on Kubernetes. I recommend you to ask your questions on the [Prometheus Users Mailing List](https://groups.google.com/forum/#!forum/prometheus-users).

**Comment by jeffhoffman13** [comment]
Never mind it is an issue I believe with the Prometheus container. You can't override the /etc/prometheus/prometheus.yml file in the container, so custom configs can't be used. the container needs to be rebuilt with a link to /tmp/prometheus.yml.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.

**Comment by Durgesh132** [comment]
> @brancz I expected to see any metrics from node exporter on the web-app.
> 
> For example I see `node_memory_Cached_bytes 5.0248482816e+10` if I `curl localhost:9100/metrics` on one of the nodes but don't see this metric through the web-app. I ultimately want to see the metrics in grafana but there is no data there either.
> 
> <img alt="Screen Shot 2019-04-15 at 7 50 59 AM" width="1680" src="https://user-images.githubusercontent.com/48572544/56142582-ca272c80-5f53-11e9-8f39-ad44b93be0d6.png">

I am facing same issue while integrating prometheus with aks-edge on windows virtual machine.
Same setup is working fine for azure kubernetes service.

Did u get any resolution to this problem ?

**Comment by SaverioFrancesco** [comment]
Same issue for me
