### ISSUE TITLE
Support hostNetwork api in prometheus and alertmanager crds

### ISSUE THREAD

**Issue by huangjiuyuan** [prometheus-operator/prometheus-operator#2630]
**What is missing?**
Support hostNetwork api in prometheus and alertmanager crds.

**Why do we need it?**
In our large scale Kubernetes cluster with VPC network, Prometheus need to monitor external Etcd clusters. However, Prometheus could not communicate with external Etcd clusters due to some restrictions of VPC network. We have a work-around by using host network for Prometheus.

**Comment by metalmatze** [comment]
Can you explain how moving Prometheus to the hostNetwork mitigates your problem? Shouldn't a change in etcd solve your problems instead?
Not sure we really need this in the Prometheus Operator, but I might be missing something right now.

**Comment by brancz** [comment]
If this is something you need to do, then I'd prefer if you deploy a proxy that has hostNetwork that forwards the request to etcd instead of exposing a potentially privilege escalation enabling feature in the prometheus operator.

**Comment by huangjiuyuan** [comment]
@metalmatze  We use two VPC networks for a cluster. One for Pod IP and one for Node IP. The VPC IP assigned to Pod cannot connect to external etcd clusters, yet the VPC IP assigned to Node (the IP bound to APIServer, Controller Manager, Scheduler, Kubelet, etc.) can because we do not allow our users to visit any external management services outside Kubernetes clusters for securoty reasons. We have admisson control webhooks to forbidden any privileged Pod creations by common users. Components such as Prometheus, Servicebrokers, Node Problem Detector, ELK and deployed on dedicated machines and maintained by us. Moving Prometheus to the hostNetwork allows Prometheus to use the Node VPC IP and connect to external Etcd clusters.

**Comment by huangjiuyuan** [comment]
@brancz Thank you for your advice. However, introducing a proxy would increase the complexity and using hostNetwork for Prometheus does not compromise the security in my opinion. I have noticed that securityContext is supported in the API document. Setting securityContext and setting hostNetwork both escalate privilege level of Prometheus operator.

**Comment by fyery-chen** [comment]
@metalmatze We also need this feature, so when it can be available?

**Comment by silenceper** [comment]
@metalmatze  We also need this feature too.

We customized the network in Kubernetes to isolate the pod network from the host network.
And we want prometheus to use the host network.

**Comment by Haleygo** [comment]
@metalmatze ,We also need this feature too.
In my scenario, prometheus need to scrap metrics(such as node-exporter which expose directly in hostnetwork) normally even when k8s cni(such as calico) down. And exposing prometheus directly in hostNetwork can solve that problem.
So can you evaluate this feature once again?

**Comment by almson** [comment]
The prometheus helm chart explains it well:

> Required for use in managed kubernetes clusters (such as AWS EKS) with custom CNI (such as calico),
> because control-plane managed by AWS cannot communicate with pods' IP CIDR

Expose a hostNetwork parameter! Most Helm charts do it, for this and other reasons.

This is why installing something through an operator is stupid--the operator maintainers might be dicks and there's little you can do about it.

**Comment by huzhengchuan** [comment]
we also this feature too. in my scenario, the pod network and hostnetwork is isotate, kube-apiserver, kube-controller-manager and other system component is deploy with hostnetwork.

**Comment by adamsb6** [comment]
I just found the need for this as well. Context is that we need to be able to scrape from pods that are IPv6 only. Prometheus is currently deployed in an EKS cluster that was IPv4 from the start, and with EKS we can't touch the bits of the control plane we'd need to convert it and enable dual stack Services.

However, we are able to run on dualstack nodes, and we can configure the Prometheus StatefulSet to use hostNetwork to give it both IPv4 and IPv6 connectivity. This appears to work without any problems, but I had to craft a janky Terraform resource to patch the StatefulSet.

I also had the pleasure of spending way too much time chasing down what was reverting the patches I was applying to the `prometheus-pop-kube-prometheus-stack-prometheus` StatefulSet. For awhile it was happening so quickly that my successful patch commands appeared to be having no effect whatsoever. I managed to catch my patch having an effect immediately after applying, read up a bit more on the components, disabled prometheus-operator, and the reverts stopped.

It'd be nice if you could add an annotation indicating that prometheus-operator edited a resource, and why.

Also, the cat's out of the bag here, but the way the values are structured led me to believe I could just add the necessary `hostNetwork` and `dnsPolicy` values underneath `spec`, because it appears to be a home for Kubernetes spec values. This also caused me to burn time trying to figure out why those values weren't appearing in the StatefulSet.

**Comment by simonpasquier** [comment]
>  disabled prometheus-operator, and the reverts stopped.

you could use the `paused` field in the spec to stop the operator from reconciling the underlying resources.

> It'd be nice if you could add an annotation indicating that prometheus-operator edited a resource, and why.

yes, the usual approach would be to provide a `FieldManager` value for all create/update/patch operations.

> the way the values are structured led me to believe I could just add the necessary hostNetwork and dnsPolicy values underneath spec, because it appears to be a home for Kubernetes spec values. This also caused me to burn time trying to figure out why those values weren't appearing in the StatefulSet.

Sorry to hear about this. While the CRD looks a bit like the StatefulSet, the reference API is at https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.Prometheus

**Comment by adamsb6** [comment]
Thanks, that helps a ton!

What are the consequences of setting `paused` to true? I'm guessing updates to Helm values will no longer be propagated to the prometheus StatefulSet, and changes/deletions won't be overwritten, is there anything else we'd need to watch out for if running this way?

**Comment by simonpasquier** [comment]
> What are the consequences of setting paused to true? 

The operator won't try to reconcile the statefulset and the Prometheus configuration. If your resources are static, it's not a big deal but if you add/update/remove monitor and rule objects then it's more problematic.

**Comment by adamsb6** [comment]
Thank you, that boost confidence that our workaround won't have unintended side effects.

The workaround I've come up with is to `helm upgrade` with `paused` set to false whenever have any changes to our values.yaml. After waiting for the upgrade to complete, we'll then run `helm upgrade --reuse-values --wait --set prometheus.prometheusSpec.paused=true`, and then after that completes we `kubectl patch` to set `hostNetwork` and `dnsPolicy`.

This works, but it's not ideal, and slightly extends the downtime for shipping any changes.

Would you be open to a PR that extends prometheusSpec to allow configuring `hostNetwork` and `dnsPolicy` on the Prometheus StatefulSet?

**Comment by simonpasquier** [comment]
> Would you be open to a PR that extends prometheusSpec to allow configuring hostNetwork and dnsPolicy on the Prometheus StatefulSet?

there's already a [PR](https://github.com/prometheus-operator/prometheus-operator/pull/3899) for adding `dnsPolicy` but it's stale. Feel free to revive it.
For `hostNetwork`, the main concern is around security. In general we prefer not to expose something that lowers the pod security. Having said that it looks like many folks are asking for it so I've added the item for discussion to our next office hours meeting [agenda](https://docs.google.com/document/d/1-fjJmzrwRpKmSPHtXN5u6VZnn39M28KqyQGBEJsqUOk/edit?usp=sharing).

**Comment by adamsb6** [comment]
That's great to hear, what did the team have to say at the office hours meeting?

**Comment by Rajpratik71** [comment]
> That's great to hear, what did the team have to say at the office hours meeting?

"**No opposition to get that in.**"

**Comment by Rajpratik71** [comment]
@simonpasquier and Team , please review #5010 which will cover  `hostNetwork`

**Comment by simonpasquier** [comment]
> That's great to hear, what did the team have to say at the office hours meeting?

We've discussed the topic in our last meeting and we agreed that while the documentation [discourages](https://kubernetes.io/docs/concepts/configuration/overview/#services) `hostNetwork`, we have several use cases which would benefit from it. Following our [maintainers policy](https://github.com/prometheus-operator/prometheus-operator/issues/4691#issuecomment-1123702982), it makes sense for the operator to support `hostNetwork`.
