### ISSUE TITLE
How Prometheus Operator has automated the task, which were done manually when using simple prometheus deployment?

### ISSUE THREAD

**Issue by aman1989v** [prometheus-operator/prometheus-operator#2640]
**What did you do?**

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by aman1989v** [comment]
Hi Prometheus Operator Team,  We are using prometheus to monitor our systems, I have started learning about Operators and finding ways how to configure Prometheus Operator. 
I am not convinced why I should shift to prometheus operator for monitoring purposes. Could you please give me some insights How prometheus operator is better than simple prometheus deployment? What are the use cases it covers?

**Comment by brancz** [comment]
It gives users self-serve mechanisms to configure Prometheus in the way they need through CRDs. It manages edge cases of storage handling that the StatefulSet controller can't generalize, but we know how Prometheus works so we can make certain opinionated decisions. It can validate recording/alerting rules at apply time against the API. Probably most notably we provide an extremely smooth update experience, so you don't need to worry about deprecated flags and so on. We can upgrade all the way from Prometheus 1.4 to 2.10, and we test this in every CI run.

**Comment by RiRa12621** [comment]
One thing i have valued a lot was a change of the concept: whilst on a single manual prometheus installation, you'll have to take care of scrape config as well as alerting rules and alertmanager rules, which involves reloading prometheus, making sure service discovery works and so on.
With the prometheus-operator and the corresponding CRDs you can abstract that away a bit. You can couple your alerting rules and and service discovery together with the services you deploy and if correctly configured, prometheus-operator makes sure that those will be added to the right prometheus/alertmanager instance.
That way rules and alerts can be owned by the teams that own the services they deploy.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.
