### ISSUE TITLE
How to use the relabelConfig

### ISSUE THREAD

**Issue by kengan** [prometheus-operator/prometheus-operator#2646]
I want to relabel some label, I set the yaml about prometheus.yaml as following. I want to set the value of label named namespace to 'DongGuang'. But It can not work.
Can someone help me? Thank you.

 apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
  remoteWrite:
    - url: "http://1.1.1.1:8086/api/v1/prom/write?db=prometheus"
  relabelConfig:
      targetLabel: namespace
      replacement: DongGuang

**Comment by kengan** [comment]
I also set in servicemonitor as following,but it does not work.

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web
  metricRelabelings:
    targetLabel: namespace
    replacement: DongGuang
  relabelings:
    targetLabel: namespace
    replacement: DongGuang

**Comment by brancz** [comment]
Could you use the linting tool we have available to check that your manifests are valid?

go get github.com/coreos/prometheus-operator/cmd/lint

**Comment by kengan** [comment]
@brancz  Thank you for your answer. But I do not know how to use lint. Can you tell me the detail. Thank you.

**Comment by kengan** [comment]
Let me take a example
For example
I have a metric  record as following

http_requests_total{code="0",endpoint="web",handler="api",instance="10.248.147.150:8080",job="example-app",method="get",namespace="default",pod="example-app-796bcbd7f9-7j7cp",service="example-app"}  17270449

I want to save the record into influxdb, I have used the remotewrite to save the record
I want to replace the label value about namespace from 'default' to 'DongGuang'  before the record being saved. Can you tell me how to do? Thank you.

**Comment by brancz** [comment]
You can use the above command that I shared to install the Prometheus operator lint tool. Once installed check your manifests with:

lint prometheus.yaml servicemonitor.yaml
