### ISSUE TITLE
kubernetes-nodes-kubelet target -403 after upgrade to EKS 1.12

### ISSUE THREAD

**Issue by GAHila** [prometheus-operator/prometheus-operator#2663]
**What did you do?**

Upgraded EKS to 1.12 and have prometheus v0.29.0. Now I get 403s on https://kubernetes.default.svc/api/v1/nodes/ip-10-124-0-32.ec2.internal/proxy/metrics. 
It seems that webhooks are actually enabled in kubelet.
**Did you expect to see some different?**
Expected to still retrieve metrics from kubernetes-nodes-kubelet target

**Environment**

* Prometheus Operator version:
v0.29.0

* Kubernetes version information:

EKS 1.12

* Kubernetes cluster kind:
EKS.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.
