### ISSUE TITLE
Unrecoverable OOM

### ISSUE THREAD

**Issue by smanpathak** [prometheus-operator/prometheus-operator#2670]
I tested prometheus-operator with avalanche https://github.com/open-fresh/avalanche.
This tool creates mock scrape points for prometheus to scrape data from. The prometheus instance was created with cpu and memory requests and limits set. This ensured the QoS was set to guaranteed by kubernetes. The instance was also configured with persistent storage.

Then I increased load in steps by increasing deployment size of avalanche, till at one point prometheus crashed due to OOM.
After OOM crash, it never recovered.

**Did you expect to see some different?**
Prometheus instance recover successfully after OOM

**How to reproduce it (as minimally and precisely as possible)**:
Configure prometheus instance as 1CPU 4G memory. Configure service monitor to scrape from avalanche.
Start avalanche deployment with size of 8.

**Environment**
Kubernetes running on AWS. (Non EKS)

* Prometheus Operator version:
quay.io/coreos/prometheus-operator:v0.29.0
    `Insert image tag or Git SHA here`
    

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T15:58:45Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
    `kubectl version`
    

* Kubernetes cluster kind:
Custom cluster on AWS.
    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
Prometheus, upon restart from crash reconciles data chunks. This process may take a while. Only after initial processing it starts accepting connections. The readiness and liveness probes configured by operator for prometheus pod only work on clean starts. On restart after OOM the probes are too aggressive.
I suggest adding an init pod which recovers all data chunks before starting prometheus normally.

**Comment by brancz** [comment]
Which version of Prometheus are you using?

**Comment by smanpathak** [comment]
The image used are : operator -- quay.io/coreos/prometheus-operator:v0.29.0
prometheus --  quay.io/prometheus/prometheus:v2.7.1

**Comment by smanpathak** [comment]
@brancz do you need any additional information on this?

**Comment by brancz** [comment]
Could you upgrade to latest versions of each? WAL replay has been significantly improved, so it might not be a problem in newer versions anymore.

**Comment by mayuresh108** [comment]
@brancz  Tried the tests conducted by @smanpathak with the new version of the operator 0.31.1 and I still see the crash after half an hour with the new operator version. 

Post crash the prometheus pod keeps on restarting due to liveness check which fails and does not give the pod enough time to come up. If liveness/readiness checks are removed the pod comes up fine post crash. 

Maybe the initial timeout for liveness readiness need to be increased or an Init pod might help.


I used the latest version of the operator: quay.io/coreos/prometheus-operator:v0.31.1  
but it still fetched the same version of prometheus:
quay.io/prometheus/prometheus:v2.7.1

I used a 3 node kube cluster with 4 cores and 4 gb memory for each node. 
The prometheus pod was given a Qos guarantee of 1 core and 3gb and 2 avalanche pods killed it in 30 minutes.

**Comment by mayuresh108** [comment]
A similar result was observed with latest version of prometheus: quay.io/prometheus/prometheus:v2.11.1

Prometheus version is hard coded in the prometheus operator code (pkg/prometheus/statefulset.go:37), had to manually change and recompile it.

**Comment by brancz** [comment]
> Prometheus version is hard coded in the prometheus operator code (pkg/prometheus/statefulset.go:37), had to manually change and recompile it.

You can set the prometheus version to use in the Prometheus object. What you referenced is just the default that's used.

We should look into optimizing this if it's still not good enough.

**Comment by mayuresh108** [comment]
Even with the default version set to v2.11.1, it correctly pulled the new image for prometheus and crashed. Let me still try by specifying it in the prometheus object.

**Comment by mayuresh108** [comment]
Nope, same issue after specifying image version in Prometheus object.

An immediate fix could be to increase the timeout for liveness/readiness probe. So liveness probe will not keep on killing the pod if it takes time to come up after a restart.

**Comment by brancz** [comment]
Happy to accept a PR to bump the liveness/readiness probe timeouts to something that works for you.

**Comment by mman** [comment]
I came across this issue recently. My prometheus deployment with everything default was working for about a week and then it started OOM crashing. I have tried to increase the initial delay of liveness and readiness probes, but the OOM happens during WAL replays like this:

The prometheus container log
```
level=info ts=2020-04-10T07:18:06.802Z caller=main.go:331 msg="Starting Prometheus" version="(version=2.16.0, branch=HEAD, revision=b90be6f32a33c03163d700e1452b54454ddce0ec)"
level=info ts=2020-04-10T07:18:06.802Z caller=main.go:332 build_context="(go=go1.13.8, user=root@7ea0ae865f12, date=20200213-23:50:02)"
level=info ts=2020-04-10T07:18:06.803Z caller=main.go:333 host_details="(Linux 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u2~bpo9+1 (2019-11-12) x86_64 prometheus-prometheus-0 (none))"
level=info ts=2020-04-10T07:18:06.803Z caller=main.go:334 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-04-10T07:18:06.803Z caller=main.go:335 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-04-10T07:18:06.809Z caller=main.go:661 msg="Starting TSDB ..."
level=info ts=2020-04-10T07:18:06.810Z caller=web.go:508 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-04-10T07:18:06.822Z caller=head.go:577 component=tsdb msg="replaying WAL, this may take awhile"
level=info ts=2020-04-10T07:18:06.823Z caller=head.go:625 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=132
level=info ts=2020-04-10T07:18:17.191Z caller=head.go:625 component=tsdb msg="WAL segment loaded" segment=1 maxSegment=132
level=info ts=2020-04-10T07:18:25.896Z caller=head.go:625 component=tsdb msg="WAL segment loaded" segment=2 maxSegment=132
level=info ts=2020-04-10T07:18:35.005Z caller=head.go:625 component=tsdb msg="WAL segment loaded" segment=3 maxSegment=132
level=info ts=2020-04-10T07:18:48.290Z caller=head.go:625 component=tsdb msg="WAL segment loaded" segment=4 maxSegment=132
level=info ts=2020-04-10T07:18:55.883Z caller=head.go:625 component=tsdb msg="WAL segment loaded" segment=5 maxSegment=132
```

The pod status
```
prometheus-prometheus-0                          2/3     CrashLoopBackOff    1          117s
prometheus-prometheus-0                          2/3     Running             2          2m13s
prometheus-prometheus-0                          2/3     OOMKilled           2          3m10s
prometheus-prometheus-0                          2/3     CrashLoopBackOff    2          3m12s
prometheus-prometheus-0                          2/3     Running             3          3m36s
prometheus-prometheus-0                          2/3     OOMKilled           3          4m33s
prometheus-prometheus-0                          2/3     CrashLoopBackOff    3          4m37s
```

**Comment by brancz** [comment]
The liveness or readiness probes aren't the problem here. You just need to give your Prometheus server more resources so it can replay the WAL. It's somewhat known that replaying the WAL can be expensive, improvements are being worked on but are complicated to implement so I can't tell when they will be available.

**Comment by karanmagdani1** [comment]
Hey guys, is there any development/workaround on this? Even after adding ~20Gi memory, replaying WAL is not an option for us as it still crashes. Currently, we are just deleting the WAL segments, and we lose metrics for a time period because of this.

**Comment by brancz** [comment]
@karanmagdani1 which version of Prometheus are you using?

**Comment by yuha0** [comment]
fwiw, I believe this is a Prometheus issue(prometheus/prometheus#6934), and is not related to the operator.

Patiently waiting for the operator's auto sharding to become mature... ;)
