### ISSUE TITLE
add multiple cluster support

### ISSUE THREAD

**Issue by venkatkriish** [prometheus-operator/prometheus-operator#2682]
I am using multiple kubernetes cluster as we need to have a single prometheus operator to collect the metrics from multiple clusters.
example config like below:
`kubernetes_sd_configs:
- api_server: <api server address>
  role: node
  bearer_token_file: <path to the token file>
  tls_config:
    ca_file: <path to the ca file>`
or
if there any flag to the operator to add multiple clusters.
can you please have a quick reply to use this further for multi k8s cluster monitoring support

**Comment by brancz** [comment]
Prometheus is intended to run as close to your targets as possible. I recommend running a Prometheus server in each cluster, and use something like [Thanos](https://thanos.io/) to allow global querying (if that's what you're looking for for multiple clusters).

**Comment by venkatkriish** [comment]
@brancz thanks for your reply 
my scenario is like i am running multiple kubernetes clusters on our environment 
i need to monitor by installing prometheus operator on one cluster and need to monitor other clusters as well with the same prometheus operator.
can you please have a solution for this is this possible with operator.

**Comment by ingvarm-gr** [comment]
As things stand, I don't think you can do this with a single prometheus-operator, in a single cluster.  Prometheus-operator can only spin up things in the cluster where it's running. and service-monitors can't really reach out to other clusters.

We're (sort of) in a similar situation, and what we have done is to deploy a "system prometheus" in all clusters, scraping things in the local cluster and doing as much aggregation we can in that cluster. Then, in a few clusters, we deploy a second "cross-cluster" prometheus that scrapes the "system prometheus" in all clusters, and does some higher-level aggregation.

We're also looking at dropping the cross-cluster prometheis and move to Thanos for this instead.

**Comment by venkatkriish** [comment]
@ingvarm-gr Thanks for your reply.
we are also have the same thing in mind but prometheus is supporting for the configs to integrate multiple clusters to collect the data from ,please follow this link below to see how can we connect multiple clusters to a prometheus.
`kubernetes_sd_configs:                         
- role: node`
`kubernetes_sd_configs:
- api_server: <api server address>
  role: node
  bearer_token_file: <path to the token file>
  tls_config:
    ca_file: <path to the ca file>`
this below blog gives much intresting in connecting multi clusters
[Multiple clusters monitoring with prometheus](https://medium.com/thg-tech-blog/monitoring-multiple-kubernetes-clusters-88cf34442fa3)

Like wise above if **prometheus operator** will able to update the configs like above so we can connect multi clusters in single prometheus operator domain and monitor with single point of collecting data.

**Comment by kazukousen** [comment]
I want it too.
Can APIServerConfig be set to ServiceMonitorSpec?
I have a reason i don't want to run Prometheus server in target clusters.
(e.g. want to monitor when the cluster goes down.)
can you consider it?

**Comment by lianghuiyuan** [comment]
+1
I also need a single prometheus operator to simply collect the metrics from multiple clusters, but without THANOS.

**Comment by val1715** [comment]
+1
I also need a single prometheus operator to simply collect the metrics from multiple clusters, but without THANOS.

**Comment by brancz** [comment]
Please let us know how you think that would work (Thanos was precisely created for this, so if it's the same strategy then Thanos continues to be the right answer, if there is a gap to fill I'm happy to listen).

**Comment by abelal83** [comment]
@brancz  would you recommend we install prometheus operator on every cluster with thanos sidecar? If so are there any guides on best practises with prometheus operator?

**Comment by paulfantom** [comment]
> would you recommend we install prometheus operator on every cluster with thanos sidecar?

Yes, that is the recommendation.

If you think this issue is still valid, please reopen it.
