### ISSUE TITLE
Operation cannot be fulfilled on apiservices.apiregistration.k8s.io "v1beta1.metrics.k8s.io"

### ISSUE THREAD

**Issue by zhangxingdeppon** [prometheus-operator/prometheus-operator#2693]
**What happened?**
Hi,I met a problem about api "metrics.k8s.io/v1beta1",there will be problems when this api is called，the following is apiserver error log：
<pre><code>
E0726 06:17:26.414572       1 controller.go:111] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: Error: 'net/http: TLS handshake timeout'
Trying to reach: 'https://10.101.27.47:443/openapi/v2', Header: map[]
I0726 06:17:26.414600       1 controller.go:119] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue.
E0726 06:17:27.359955       1 available_controller.go:316] v1beta1.metrics.k8s.io failed with: Get https://10.101.27.47:443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
E0726 06:17:32.363125       1 available_controller.go:316] v1beta1.metrics.k8s.io failed with: Operation cannot be fulfilled on apiservices.apiregistration.k8s.io "v1beta1.metrics.k8s.io": the object has been modified; please apply your changes to the latest version and try again
I0726 06:17:32.370400       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E0726 06:17:37.367583       1 available_controller.go:316] v1beta1.metrics.k8s.io failed with: Get https://10.101.27.47:443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
E0726 06:17:42.370399       1 available_controller.go:316] v1beta1.metrics.k8s.io failed with: Operation cannot be fulfilled on apiservices.apiregistration.k8s.io "v1beta1.metrics.k8s.io": the object has been modified; please apply your changes to the latest version and try again
E0726 06:17:45.334592       1 controller.go:111] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: Error: 'net/http: TLS handshake timeout'
Trying to reach: 'https://10.101.27.47:443/openapi/v2', Header: map[]
I0726 06:17:45.334617       1 controller.go:119] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue.
I0726 06:17:46.436231       1 controller.go:105] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
E0726 06:17:47.374293       1 available_controller.go:316] v1beta1.metrics.k8s.io failed with: Get https://10.101.27.47:443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
E0726 06:17:51.946445       1 memcache.go:135] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0726 06:17:52.378143       1 available_controller.go:316] v1beta1.metrics.k8s.io failed with: Operation cannot be fulfilled on apiservices.apiregistration.k8s.io "v1beta1.metrics.k8s.io": the object has been modified; please apply your changes to the latest version and try again
E0726 06:17:56.437299       1 controller.go:111] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: Error: 'net/http: TLS handshake timeout'
Trying to reach: 'https://10.101.27.47:443/openapi/v2', Header: map[]

</code></pre>

Record ip :10.101.27.47  in the log is belong to prometheus-adapter
![image](https://user-images.githubusercontent.com/16789841/62016002-1b48ec80-b1e2-11e9-96bb-bfbc18b99f2f.png)

when I installed the prometheus-operator,the metric-server api is also installed,
show as follows：
<pre><code>
[aipaas@ecs-5274-0318501 ~]$ kubectl api-versions 
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
apps/v1beta1
apps/v1beta2
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
ceph.rook.io/v1
certificates.k8s.io/v1beta1
coordination.k8s.io/v1beta1
events.k8s.io/v1beta1
extensions/v1beta1
metrics.k8s.io/v1beta1
monitoring.coreos.com/v1
networking.k8s.io/v1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
rook.io/v1alpha2
scheduling.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1

</code></pre>
 when I delete the api “metrics.k8s.io/v1beta1” resource，command “ kubectl delete apiservice v1beta1.metrics.k8s.io”，after that， there is no such error in the log，I have no idea about it ，can you give me some advice ? thanks.
**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:
<pre><code>
[root@D21114U24-61-149 ~]# kubectl -n monitoring describe deployment prometheus-operato
Name:                   prometheus-operator
Namespace:              monitoring
CreationTimestamp:      Wed, 24 Apr 2019 18:32:34 +0800
Labels:                 k8s-app=prometheus-operator
Annotations:            deployment.kubernetes.io/revision: 4
                        kubectl.kubernetes.io/last-applied-configuration:
                          {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{},"labels":{"k8s-app":"prometheus-operator"},"name":"prometheu...
Selector:               k8s-app=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           k8s-app=prometheus-operator
  Service Account:  prometheus-operator
  Containers:
   prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.28.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --logtostderr=true
      --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
      --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.28.0
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-574c849fdf (1/1 replicas created)
Events:          <none>

</code></pre>
    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    
<code>
[root@D21114U24-61-149 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"
</code>
* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
Can you share the status of the apiservice?

```
kubectl get apiservice v1beta1.metrics.k8s.io -oyaml 
```

**Comment by gautam2187** [comment]
@zhangxingdeppon curious if you found the solution.

**Comment by thibault-ketterer** [comment]
Hi
maybe a date / ntp issue ?
it was the case for me.
