### ISSUE TITLE
Make it easy to use console templates

### ISSUE THREAD

**Issue by shettich** [prometheus-operator/prometheus-operator#2699]
I read #1644, but the current solution of building a custom image is hard.

You seems to enforce SemVar on the image tag (to check for prom features?), so I can't have my own versioning of the custom image.

I understand the argument about configmaps being to small, but why not allow the side-car to fetch/sync the templates via http?  Or, at least make it easy to add more side-cars & volumes so one could do that on their own.

**Comment by brancz** [comment]
if there is a reasonable way to do this, I'd be open to it :)

**Comment by shettich** [comment]
Two options:

A) [more open-ended, more work for users]: add an option to the CRD to add more side-cars and volume mounts

B) [more narrow, easy for users] add a URL to a tar file in the crd, have the config side-car poll it for changes and unpack into the console dir

**Comment by brancz** [comment]
Sorry I should have been more specific about which parts I'm open to. I'd be ok with enabling the ability to configure a path to load a console template(s) from. Adding them to the container should just be via a ConfigMap I think.

**Comment by simonpasquier** [comment]
It is feasible to add custom console templates via `spec.configmaps`. It's also possible to add CLI args with `spec.additionalArgs` . As such we probably don't need anything more in the Prometheus CRD to support custom console templates if this is still needed.

**Comment by k8s-1** [comment]
A working fix to this is in https://github.com/prometheus-operator/prometheus-operator/issues/6880
