### ISSUE TITLE
Memory spike on starting Prometheus Operator

### ISSUE THREAD

**Issue by Sturgelose** [prometheus-operator/prometheus-operator#2709]
**What happened?**
Whenever we start Prometheus, we get a memory spike several times the allocated memory to Prometheus. This forces us to set unlimited max memory to Prometheus in Kubernetes, which I'd like to avoid. Our usual base consumption of memory is around 1.70 Gib, but during the initial spike, it goes up to whooping 9GiB (close to x5 times).

I've tried disabling all the Alert rules and alert manager, as the default prometheus-operator chart in Helm, seems to enable them by default. It still happens.

So, I'm not sure how we should tackle this, as a random restart in Prometheus would mean an OOM in one of our servers.

Right now we are running in a quite simple K8s cluster, with 2 nodes, and some batch Jobs running during the night (then the cluster scales to 6 nodes with node autoscaler). So 9GiB looks a bit big for us at start.

We ingest at peak 800k samples at night during the batch and when not running a batch (which is usually all the day and right now) 200k samples. 
(taken both from the query `max_over_time(prometheus_tsdb_head_series[1d])`)

And the average amount of samples ingested by prometheus in 5 min, is around 6.1k.

Following a bit the insights in this calculator (https://www.robustperception.io/how-much-ram-does-prometheus-2-x-need-for-cardinality-and-ingestion) seems that our memory use shouldn't be quite high.

Here I attach an image of the memory plots of the Prometheus instance. Blue lines are restarts done by me with different configurations. As you see, none of them affected the result, and after 10 min, it stabilizes to around 2 GB. An exception is the second reboot, but it's like this because I had set a memory limit and the container ended in boot loop, so it didn't fully start because it didn't have enough available memory.
![image](https://user-images.githubusercontent.com/244191/62703380-608eca80-b9e9-11e9-8313-d1c13d8ea30a.png)

I had to set the memory limit of the operator to undefined, and I have the the requested memory to 500MiB

**Did you expect to see some different?**
I'd expect the memory to rise a bit, but inside some reasonable limits, and the difference between start and standby shouldn't be too much different

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.31.1` (used from helm chart prometheus-operator)

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:05:01Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    with Kops over AWS

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

Note, logs are upside down, as I fetched them from Loki and it shows them in this backwards order.. Sorry!
```
019-08-08 14:05:12	
level=error ts=2019-08-08T12:05:12.148Z caller=endpoints.go:131 component="discovery manager scrape" discovery=k8s role=endpoint msg="endpoints informer unable to sync cache"
2019-08-08 14:05:12	
level=error ts=2019-08-08T12:05:12.148Z caller=endpoints.go:131 component="discovery manager scrape" discovery=k8s role=endpoint msg="endpoints informer unable to sync cache"
2019-08-08 14:05:12	
level=error ts=2019-08-08T12:05:12.148Z caller=endpoints.go:131 component="discovery manager scrape" discovery=k8s role=endpoint msg="endpoints informer unable to sync cache"
2019-08-08 14:05:12	
level=info ts=2019-08-08T12:05:12.147Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
2019-08-08 14:05:12	
level=info ts=2019-08-08T12:05:12.147Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
2019-08-08 14:05:12	
level=info ts=2019-08-08T12:05:12.142Z caller=main.go:730 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
2019-08-08 14:05:12	
level=info ts=2019-08-08T12:05:12.140Z caller=main.go:614 msg="Server is ready to receive web requests."
2019-08-08 14:05:12	
level=info ts=2019-08-08T12:05:12.140Z caller=main.go:758 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
2019-08-08 14:05:12	
level=info ts=2019-08-08T12:05:12.139Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
2019-08-08 14:05:12	
level=info ts=2019-08-08T12:05:12.136Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
2019-08-08 14:05:12	
level=info ts=2019-08-08T12:05:12.135Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
2019-08-08 14:05:12	
level=info ts=2019-08-08T12:05:12.124Z caller=main.go:730 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
2019-08-08 14:05:12	
level=info ts=2019-08-08T12:05:12.124Z caller=main.go:661 msg="TSDB started"
2019-08-08 14:05:12	
level=info ts=2019-08-08T12:05:12.124Z caller=main.go:660 fs_type=EXT4_SUPER_MAGIC
2019-08-08 14:05:08	
level=warn ts=2019-08-08T12:05:08.149Z caller=head.go:458 component=tsdb msg="unknown series references" count=480157
2019-08-08 14:04:22	
ts=2019-08-08T12:04:22.180193124Z caller=main.go:85 msg="Starting prometheus-config-reloader version '0.31.1'."
2019-08-08 14:04:22	
ts=2019-08-08T12:04:22.180193124Z caller=main.go:85 msg="Starting prometheus-config-reloader version '0.31.1'."
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.113Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1565251200000 maxt=1565258400000 ulid=01DHRE5BY7XRBM53XB8A2NMH31
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.112Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1565179200000 maxt=1565244000000 ulid=01DHR7BJ5VQBMKGNB7XX0RF1AQ
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.112Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1565244000000 maxt=1565251200000 ulid=01DHR79MNDYS812J0YA4RYF6C0
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.112Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1565114400000 maxt=1565179200000 ulid=01DHP9HNKDGTFVM67QSKB53N6Y
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.111Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1565049600000 maxt=1565114400000 ulid=01DHMBQ2YJYMMESNPV9MCXAD69
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.111Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1565042400000 maxt=1565049600000 ulid=01DHJ719PA81D90E18AB8513S2
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.110Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1565035200000 maxt=1565042400000 ulid=01DHJ05JDGM9EBB14VHMB2K7VJ
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.110Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1565006400000 maxt=1565028000000 ulid=01DHHSAHP95JEEAWX2WZDMS75Q
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.109Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1565028000000 maxt=1565035200000 ulid=01DHHS9V66PY4TKNVT50J9R5C5
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.108Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1564984800000 maxt=1565006400000 ulid=01DHH4QB8K1XSS0QGNCN2HBEB0
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.107Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1564920000000 maxt=1564984800000 ulid=01DHGG6YYDHXQYMY36PAE6VEEJ
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.107Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1564855200000 maxt=1564920000000 ulid=01DHEJB4KCZPF1K6XYBARNHH20
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.107Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1564790400000 maxt=1564855200000 ulid=01DHCMGTT511FEWP3SFJ0CY5JG
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.106Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1564725600000 maxt=1564790400000 ulid=01DHAPRMKRX7MC2NXEAJA5X3PH
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.106Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1564660800000 maxt=1564725600000 ulid=01DH8RZ9CYKSCRQR5NTHDCRX37
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.105Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1564654951877 maxt=1564660800000 ulid=01DH6NHDG3PK4T6VJ3N3QS8B2W
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.104Z caller=web.go:417 component=web msg="Start listening for connections" address=0.0.0.0:9090
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.104Z caller=main.go:645 msg="Starting TSDB ..."
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.103Z caller=main.go:326 vm_limits="(soft=unlimited, hard=unlimited)"
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.103Z caller=main.go:325 fd_limits="(soft=1048576, hard=1048576)"
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.103Z caller=main.go:324 host_details="(Linux 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 prometheus-prometheus-prometheus-oper-prometheus-0 (none))"
2019-08-08 14:04:22	
level=info ts=2019-08-08T12:04:22.103Z caller=main.go:323 build_context="(go=go1.12.5, user=root@a49185acd9b0, date=20190525-12:28:13)"
2019-08-08 14:04:22	
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
Do you also see this if you start with a blank storage?

**Comment by Sturgelose** [comment]
@brancz Luckily I had restarted the whole prometheus a week ago, so here I have a screenshot.
![image](https://user-images.githubusercontent.com/244191/62717337-00f1e880-ba04-11e9-9046-30c5c6bb3785.png)
As you see, the initial run works well, but I did a restart some time later and automatically I had a spike. It was couple of hours later so I guess it shouldn't be because of the amount of data.

**Comment by brancz** [comment]
Which version of Prometheus is this? (this sounds like it's caused by WAL replay, which was optimized in recent versions)

**Comment by Sturgelose** [comment]
@brancz sorry, didn't see your answer/question as we have been quite busy here. We are right now (as well as at that moment) using prometheus v2.10.

I've seen there is something that could be fixed in v2.12, with the `prometheus_tsdb_retention_limit_bytes` flag, though I'll give it a try now and see how it behaves.

**Comment by metalmatze** [comment]
To be honest, this seems more like a Prometheus issue rather than a Prometheus Operator one. Maybe the Prometheus community upstream is the better place to ask the question. :blush:

**Comment by paulfantom** [comment]
As mentioned earlier, this looks like WAL replay issue related directly to prometheus. In recent versions there were many improvements regarding this code path, but there is no option (apart from discarding data) to have WAL replay not consuming a significant portion of resources.

I am closing this as prometheus has improved WAL replay resource consumption and prometheus-operator has implemented sharding. Latter of which could distribute the load in a better way. However, if you think this issue is still valid, please reopen it.
