### ISSUE TITLE
Alert rule can't convert pending to firing

### ISSUE THREAD

**Issue by RacingDawn** [prometheus-operator/prometheus-operator#2721]
the alert rule never to be firing when i use the range query.
![image](https://user-images.githubusercontent.com/13477849/63081843-4029b780-bf77-11e9-8bc5-74c8ae911a2a.png)

although the for parameter is 1 second.

how can i do to make it be firing? Or What are the conditions for triggering an alarm？

**Comment by metalmatze** [comment]
This is a generic Prometheus question you should ask on the Prometheus mailing list: https://prometheus.io/community/

`for: 1s` seems extremely low. You probably want to increase that to at least 1m or 5m.
