### ISSUE TITLE
kubelet targets down - context deadline exceeded

### ISSUE THREAD

**Issue by andybo** [prometheus-operator/prometheus-operator#2733]
**What did you do?**
Open the targets list on prometheus web UI page, some kubelet targets are down.

**Did you expect to see some different?**
I expect all the targets are up unless something wrong.

**Environment**
* Prometheus Operator version:
prometheus-operator:v0.31.1

* Kubernetes version information:
v1.13.7-gke.19

* Kubernetes cluster kind:
gke

**Anything else we need to know?**:
The down kubelet k8s nodes actually were removed before, so the ip addresses don't exist. But the scape list  not refreshed.

![image](https://user-images.githubusercontent.com/2535711/63645036-752ccb80-c728-11e9-82ae-1a0e458d6845.png)

**Comment by yantsa** [comment]
It happened to me also cause I was using preemptible VMs . Most likely those kubelets with state DOWN come from not existing Nodes . You can confirm it by cross checking IPs .

**Comment by lkastenson** [comment]
I had this error after upgrading the K8s version of my GKE nodepools. It was caching old nodes.

Just needed to delete the prom pod and wait for it to reload and populate the new node IPs.

**Comment by jtslear** [comment]
I presume a good question to be asked here, is when are kubelet targets refreshed?  I am too running into this issue, and between a combination of node pools being rotated in and out of clusters, alongside preemptible instances, I have a lot of targets that are no longer available for scraping.  What configuration parameters are available to help assist the prometheus operator in refreshing the list of available kubelets that it should attempt to scrape from?

**Comment by brancz** [comment]
Kubelets are refreshed every 3min: https://github.com/coreos/prometheus-operator/blob/eea008c42a12ba3f050d840442c4bdd5942fb92f/pkg/prometheus/operator.go#L556. I wouldn't mind if this was moved to be informer based so it happens faster than delayed by up to 3 min.

**Comment by jtslear** [comment]
Is this the only way, currently, that kublet targets are refreshed?

In looking at one of my clusters, it's got two nodes configured as `targets` that haven't been attached to the cluster for at least 7 days if not longer.  When viewing details on the `service-discovery` endpoints, there are even more nodes that haven't been around for awhile.  If we are refreshing this data every 3 minutes, presumably successfully, this can only mean that the data being given to the operator is potentially stale.

We're using GKE, and I ponder if this stale data is being held in the API for some reason and we need to find some way to filter it out perhaps?

Is there a debug log option I can enable that might help us shed light on this issue?  Or perhaps a method for which I can query the API in the same fashion that we are updating this data?

**Comment by christianlafleur** [comment]
I have the same issue

**Comment by brancz** [comment]
I don’t know off the top of my head if debug mode prints much about node sync, but do give it a try.

**Comment by pbn4** [comment]
Sure issue here

**Comment by Iulian7** [comment]
Same issue on GKE. All the UNHEALTHY endpoints have existed in the past but have been removed from the cluster since days.

**Comment by brancz** [comment]
Do you see those when you do `kubectl get nodes` as well?

**Comment by christianlafleur** [comment]
> Do you see those when you do `kubectl get nodes` as well?

Nope they are gone.

**Comment by pbn4** [comment]
Nope, gone here too.

**Comment by msenmurugan** [comment]
@brancz I'm using GKE and using user defined nodepools to spin up and down nodes. Even for the nodes that are existing and not using preemptible VM's also having the same issue. Similar to others, some of the nodes that are spin down also in the kubelet target list.

Please find below one of an existing node's info

```
status:
  addresses:
  - address: 10.0.0.4
    type: InternalIP
  - address: ""
    type: ExternalIP
  - address: gke-mt-dev-us-east1-pool-1-XXXXXX.internal
    type: InternalDNS
  - address: gke-mt-dev-us-east1-pool-1-XXXXXX.internal
    type: Hostname
  conditions:
  - lastHeartbeatTime: "2020-05-26T07:10:43Z"
    lastTransitionTime: "2020-04-25T23:36:47Z"
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
  nodeInfo:
    architecture: amd64
    bootID: XXXXXX
    containerRuntimeVersion: docker://19.3.1
    kernelVersion: 4.19.104+
    kubeProxyVersion: v1.15.11-gke.5
    kubeletVersion: v1.15.11-gke.5
    machineID: XXXXXX
    operatingSystem: linux
    osImage: Container-Optimized OS from Google
    systemUUID: XXXXXXX
```
  
Please let me know for more details as well.

**Comment by brancz** [comment]
Could one of you try to put prometheus operator in debug mode and see if it prints something useful about the node sync?

**Comment by sdif** [comment]
Hi,
We had the same issue.

We are using GKE version v1.16.11-gke.5
Prometheus-operator version 0.40


We bumped the GKE and the prometheus-operator version to the last available ones, we updated the cluster role ressource to have access to ressources but we still have those info message (probably because a feature is not enabled inside GKE):

```
$ k logs -f prometheus-operator-6b75fc7c89-hgqkb
ts=2020-07-23T14:26:04.292184853Z caller=main.go:217 msg="Starting Prometheus Operator version '0.40.0'."
ts=2020-07-23T14:26:04.392873375Z caller=main.go:104 msg="Starting insecure server on [::]:8080"
level=info ts=2020-07-23T14:26:04.398954981Z caller=operator.go:295 component=thanosoperator msg="connection established" cluster-version=v1.16.11-gke.5
level=info ts=2020-07-23T14:26:04.399006446Z caller=operator.go:304 component=thanosoperator msg="CRD API endpoints ready"
level=info ts=2020-07-23T14:26:04.398967401Z caller=operator.go:200 component=alertmanageroperator msg="connection established" cluster-version=v1.16.11-gke.5
level=info ts=2020-07-23T14:26:04.399055047Z caller=operator.go:209 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2020-07-23T14:26:04.399196205Z caller=operator.go:461 component=prometheusoperator msg="connection established" cluster-version=v1.16.11-gke.5
level=info ts=2020-07-23T14:26:04.399249993Z caller=operator.go:470 component=prometheusoperator msg="CRD API endpoints ready"
E0723 14:26:04.495830       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:311: Failed to list *v1.ThanosRuler: the server could not find the requested resource (get thanosrulers.monitoring.coreos.com)
E0723 14:26:04.591720       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:479: Failed to list *v1.PodMonitor: the server could not find the requested resource (get podmonitors.monitoring.coreos.com)
level=debug ts=2020-07-23T14:26:05.3913129Z caller=operator.go:401 component=prometheusoperator msg="successfully synced Prometheus cache"
level=debug ts=2020-07-23T14:26:05.391562542Z caller=operator.go:401 component=prometheusoperator msg="successfully synced ServiceMonitor cache"
level=debug ts=2020-07-23T14:26:05.399335545Z caller=operator.go:165 component=alertmanageroperator msg="successfully synced Alertmanager cache"
level=debug ts=2020-07-23T14:26:05.399371829Z caller=operator.go:165 component=alertmanageroperator msg="successfully synced StatefulSet cache"
level=info ts=2020-07-23T14:26:05.399381514Z caller=operator.go:171 component=alertmanageroperator msg="successfully synced all caches"
level=debug ts=2020-07-23T14:26:05.399463969Z caller=operator.go:338 component=alertmanageroperator msg="Alertmanager added" key=monitoring/main
level=warn ts=2020-07-23T14:26:05.399539357Z caller=operator.go:484 component=alertmanageroperator msg="alertmanager key=monitoring/main, field spec.baseImage is deprecated, 'spec.image' field should be used instead"
level=info ts=2020-07-23T14:26:05.399583117Z caller=operator.go:427 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2020-07-23T14:26:05.597322998Z caller=operator.go:427 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
```

We removed the `kubectl` endpoint but it was not recreated, even if we deleted the prometheus-operator pod to force a "refresh" (as we thought).
From what we know, it should be updated every 3 minutes but it is not the case.

We found out the Kubernetes service `kubelet` is empty : ```
$ k describe service kubelet -n kube-system
Name:              kubelet
Namespace:         kube-system
Labels:            k8s-app=kubelet
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                None
Port:              https-metrics  10250/TCP
TargetPort:        10250/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```

Also, where should the `k8s-app=kubelet` should be present ? On each node ? 

This is a blocking issue as some of our metrics are not available anymore.

**Comment by pie-r** [comment]
> Hi,
> We had the same issue.
> 
> We are using GKE version v1.16.11-gke.5
> Prometheus-operator version 0.40
> 
> We bumped the GKE and the prometheus-operator version to the last available ones, we updated the cluster role ressource to have access to ressources but we still have those info message (probably because a feature is not enabled inside GKE):
> 
> ```
> $ k logs -f prometheus-operator-6b75fc7c89-hgqkb
> ts=2020-07-23T14:26:04.292184853Z caller=main.go:217 msg="Starting Prometheus Operator version '0.40.0'."
> ts=2020-07-23T14:26:04.392873375Z caller=main.go:104 msg="Starting insecure server on [::]:8080"
> level=info ts=2020-07-23T14:26:04.398954981Z caller=operator.go:295 component=thanosoperator msg="connection established" cluster-version=v1.16.11-gke.5
> level=info ts=2020-07-23T14:26:04.399006446Z caller=operator.go:304 component=thanosoperator msg="CRD API endpoints ready"
> level=info ts=2020-07-23T14:26:04.398967401Z caller=operator.go:200 component=alertmanageroperator msg="connection established" cluster-version=v1.16.11-gke.5
> level=info ts=2020-07-23T14:26:04.399055047Z caller=operator.go:209 component=alertmanageroperator msg="CRD API endpoints ready"
> level=info ts=2020-07-23T14:26:04.399196205Z caller=operator.go:461 component=prometheusoperator msg="connection established" cluster-version=v1.16.11-gke.5
> level=info ts=2020-07-23T14:26:04.399249993Z caller=operator.go:470 component=prometheusoperator msg="CRD API endpoints ready"
> E0723 14:26:04.495830       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:311: Failed to list *v1.ThanosRuler: the server could not find the requested resource (get thanosrulers.monitoring.coreos.com)
> E0723 14:26:04.591720       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:479: Failed to list *v1.PodMonitor: the server could not find the requested resource (get podmonitors.monitoring.coreos.com)
> level=debug ts=2020-07-23T14:26:05.3913129Z caller=operator.go:401 component=prometheusoperator msg="successfully synced Prometheus cache"
> level=debug ts=2020-07-23T14:26:05.391562542Z caller=operator.go:401 component=prometheusoperator msg="successfully synced ServiceMonitor cache"
> level=debug ts=2020-07-23T14:26:05.399335545Z caller=operator.go:165 component=alertmanageroperator msg="successfully synced Alertmanager cache"
> level=debug ts=2020-07-23T14:26:05.399371829Z caller=operator.go:165 component=alertmanageroperator msg="successfully synced StatefulSet cache"
> level=info ts=2020-07-23T14:26:05.399381514Z caller=operator.go:171 component=alertmanageroperator msg="successfully synced all caches"
> level=debug ts=2020-07-23T14:26:05.399463969Z caller=operator.go:338 component=alertmanageroperator msg="Alertmanager added" key=monitoring/main
> level=warn ts=2020-07-23T14:26:05.399539357Z caller=operator.go:484 component=alertmanageroperator msg="alertmanager key=monitoring/main, field spec.baseImage is deprecated, 'spec.image' field should be used instead"
> level=info ts=2020-07-23T14:26:05.399583117Z caller=operator.go:427 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
> level=info ts=2020-07-23T14:26:05.597322998Z caller=operator.go:427 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
> ```
> 
> We removed the `kubectl` endpoint but it was not recreated, even if we deleted the prometheus-operator pod to force a "refresh" (as we thought).
> From what we know, it should be updated every 3 minutes but it is not the case.
> 
> We found out the Kubernetes service `kubelet` is empty :
> 
> ```
> $ k describe service kubelet -n kube-system
> Name:              kubelet
> Namespace:         kube-system
> Labels:            k8s-app=kubelet
> Annotations:       <none>
> Selector:          <none>
> Type:              ClusterIP
> IP:                None
> Port:              https-metrics  10250/TCP
> TargetPort:        10250/TCP
> Endpoints:         <none>
> Session Affinity:  None
> Events:            <none>
> ```
> 
> Also, where should the `k8s-app=kubelet` should be present ? On each node ?
> 
> This is a blocking issue as some of our metrics are not available anymore.

Same issue with operator 0.29 and gke 1.16-gke.13

All kublet target are down and not reachable from prometheus

**Comment by lironrisk** [comment]
@brancz happens also on v0.38.1 prometheus operator on AWS (kops) - some kubelet targets are down for targets that are no longer exist

**Comment by maloochpich** [comment]
I am also facing the same issue any solution for this?

**Comment by simonpasquier** [comment]
@maloochpich can you try with the latest Prometheus operator version + debug log level enabled?

**Comment by ArtemPG** [comment]
I faced the same issue, and was able to debug it and find a solution. Probably, it won't help everyone, but my symptoms were exactly the same as for  @andybo .

So, ServiceMonitor uses the following selectors:
```
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kubelet
```
It means, it tries to scrape data from all endpoints with the `k8s-app: kubelet` label in the `kube-system` namespace.

In my case, I had 3 endpoints:
```
# kubectl -n kube-system get ep -l k8s-app=kubelet

kube-prometheus-stack-kubelet        10.1.0.20:10255,10.1.0.32:10255,10.1.0.34:10255 + 36 more...   2d
prometheus-operator-kubelet          10.1.0.32:10255,10.1.0.37:10255,10.1.0.46:10255 + 27 more...   245d
prometheus-test-kube-prome-kubelet   10.1.0.32:10255,10.1.0.37:10255,10.1.0.46:10255 + 24 more...   282d
```
And ServiceMonitor was trying to scrape data form all nodes with IP addresses from these 3 endpoints, but 2 endpoints left from previous installations of Prometheus Operator. As a result, some nodes were not existing anymore, and Prometheus showed the errors during reaching these targets. Mostly, they were GKE preemptible nodes, which were deleted long ago.

Sadly, I didn't save any screenshots from Prometheus for my case. But If you take a look at the screepshot from @andybo :

![](https://user-images.githubusercontent.com/2535711/63645036-752ccb80-c728-11e9-82ae-1a0e458d6845.png)

You can notice labels `service`. Those nodes, which are down, have `service=prometheus-operator-kubelet`, on the other hand, those nodes, which are up, have `service=kubelet`. It means that, first two nodes' IP addresses were taken from endpoint `prometheus-operator-kubelet`, and second two nodes' IP addresses were taken from endpoint `kubelet`. And I am sure, that `# kubectl -n kube-system get ep -l k8s-app=kubelet` will return something like that:
```
kubelet        10.140.0.14:10255,10.140.0.15:10255 + some more...   
prometheus-operator-kubelet          10.140.0.12:10255,10.140.0.13:10255 + some more...   
```
I my case, deletion of old endpoints helped, so Prometheus scrapes data only from existing nodes now.

As a suggestion for a fix, adding more labels to the endpoint and the selector with some dynamic values or values based on some kubernetes naming, to help prometheus identify to which installation related endpoints, e.g.:
```
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kubelet
      installation-name: prometheus-operator-kubelet
```
