### ISSUE TITLE
Support setting ImagePullPolicy for operand (prometheus, alertmanager) images

### ISSUE THREAD

**Issue by shettich** [prometheus-operator/prometheus-operator#2747]
A quick read of statefullset.go shows it never looks at the field from the CRD.

Could you propagate that over?

**Comment by brancz** [comment]
Can you share the object you created?

**Comment by shettich** [comment]
Not easily.  I could work out something close, but then I have no way to test it.

**Comment by brancz** [comment]
Then it's going to be hard for us to help you :)

**Comment by brancz** [comment]
would https://github.com/coreos/kube-prometheus help you?
