### ISSUE TITLE
High memory usage on prometheus operator pods

### ISSUE THREAD

**Issue by syst0m** [prometheus-operator/prometheus-operator#2759]
**What happened?**
The cached memory usage of the prometheus operator pods has been gradually increasing over time.
Currently it's ~15GB.

**Did you expect to see some different?**
Expected lower memory usage, considering the number of pods monitored and timeseries ibeing ingested.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy prometheus operator with helm chart.
Configure autodiscovery for application services.
Memory usage starts gradually increasing.

**Environment**
`EKS k8s v1.11 Platform version eks.5`

* Prometheus Operator version:

`Helm chart: prometheus-operator-6.1.1   	v0.31.1`
`Image: quay.io/coreos/prometheus-operator:v0.30.1`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-eks-7f15cc", GitCommit:"7f15ccb4e58f112866f7ddcfebf563f199558488", GitTreeState:"clean", BuildDate:"2019-08-19T17:46:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

Terraformed with terraform-eks-module

* Manifests:

N/A

* Prometheus Operator Logs:

Only seeing logs with:
```
invalid metric type
```

**Anything else we need to know?**:
Attaching screenshots of prometheus metrics from grafana:

![1](https://user-images.githubusercontent.com/15815107/64790411-f92ae400-d56d-11e9-9ed2-0b78d1100f90.png)
![2](https://user-images.githubusercontent.com/15815107/64790412-f92ae400-d56d-11e9-9b28-6e396aa4a4aa.png)
![3](https://user-images.githubusercontent.com/15815107/64790413-f9c37a80-d56d-11e9-9e82-76d9c1af8fa7.png)
![4](https://user-images.githubusercontent.com/15815107/64790414-f9c37a80-d56d-11e9-9130-5cb76a3c7ee7.png)

**Comment by mzupan** [comment]
I'm seeing the same thing with the same versions

**Comment by DORcode** [comment]
me too

**Comment by arslanbekov** [comment]
+1, very big cache ~12gb.

**Comment by brancz** [comment]
Which version of Prometheus is this? Generally this looks like it could be something that maybe should be reported on Prometheus itself. Although the up to 300k active series is likely what's causing this. 5k samples per second is not a lot. It looks like there is something that creates *a lot* of series churn (the spikes in created/removed) shows this.

**Comment by syst0m** [comment]
@brancz 

**Prometheus Operator version:**
Helm chart: prometheus-operator-6.1.1 v0.31.1
Image: quay.io/coreos/prometheus-operator:v0.30.1

Any suggestions on how to debug this?

**Comment by brancz** [comment]
cc @krasi-georgiev

Neither of those are Prometheus versions. What's the prometheus version? (we neither use nor maintain the helm charts so that version doesn't say anything to me)

**Comment by arslanbekov** [comment]
@brancz I have same in *v2.12.0* Prometheus.

**Comment by syst0m** [comment]
@brancz 

**Build Information**

```
Version | 2.7.1
-- | --
62e591f928ddf6b3468308b7ac1de1c63aa7fcf3
HEAD
root@f9f82868fc43
20190131-11:16:59
go1.11.5


```

**Comment by krasi-georgiev** [comment]
It looks like high churn to me as well.

**Comment by mzupan** [comment]
my build information

<img width="871" alt="Screen Shot 2019-09-20 at 6 31 16 AM" src="https://user-images.githubusercontent.com/205373/65327117-4b709400-db70-11e9-8c9b-853f01b82f96.png">

**Comment by krasi-georgiev** [comment]
as mentioned by @brancz high looks like the cause here so should focus on reducing it. Some additional relabeling rules wold probably fix this.

**Comment by brancz** [comment]
Starting with v2.10.0 the `scrape_series_added` metric exists. With it you can find out which targets are creating a lot of new time-series. Just graph that and you should be able to see something that produces the spikes you see on that graph.

**Comment by syst0m** [comment]
Thanks everyone, for the suggestions.
I used `tsdb` to analyze the prometheus db.
As you suggested, there seems to be high churn, primarily due to the ephemeral nature of the ci/cd agents.
```
Label pairs most involved in churning:
31569 job=buildkite-agents
27172 Queue=beefy
4480 instance=172.21.3.173:9100
```
```
Label names most involved in churning:
39311 __name__
39193 instance
39134 job
31567 Queue
30481 device
7564 service
```
I don't think high cardinality labels are a problem:
```
Highest cardinality labels:
1315 __name__
1058 address
989 mountpoint
985 device
757 id
```

I know the new prometheus storage engine has introduces some improvements for high churning.
But, I am not really sure how to approach this, in terms of lowering resource usage.
RAM usage is now ~19GB, and also CPU usage has grown from 0.1->0.6, with intermitent spikes.

**Comment by krasi-georgiev** [comment]
how about relabeling to drop or rename some of these labels?

**Comment by syst0m** [comment]
Dropping is not really an option, as we are using all fo those labels in queries.
As for relabeling, I don't really see how that would work.
Due to the ephemeral nature of the CI/CD agent workloads, they don't have a continuous identifier,
which could be used for relabelling.

Is it possible to scale up the prometheus deployment, creating more replicas?
So, that the load would be distributed across the replicas.

**Comment by tarunptala** [comment]
hey 

we also see high memory usage issue with `quay.io/prometheus/prometheus:v2.15.2` used prometheus operator to deploy prometheus. 
`k8s 1.11+`

**Comment by lilic** [comment]
@tarunptala yes this should be resolved in recent Prometheus versions, are you able to upgrade? If not just dropping the amount of series is another option.

**Comment by mzupan** [comment]
I solved it by forcing 2.19.3 in the helm chart to install and not the default one.

Also using victoriametrics as a backend and only having prometheus save 30min of metrics.

**Comment by nikolaistraessle** [comment]
I have the same problem with the Version `quay.io/prometheus/prometheus:v2.18.2`.
The memory consumption starts on 900M and 2 hours later the memory consumption is over 2G.

![image](https://user-images.githubusercontent.com/24289388/92475283-73239680-f1dd-11ea-8fca-00dff6726f69.png)

The amount of samples is only around 3k per second.

Is any stable solution available for this problem?

**Comment by brancz** [comment]
Prometheus flushes data to disk every 2h, can you keep watching this for a few hours? As it stands this looks normal.

**Comment by puzzloholic** [comment]
Hi @syst0m, could you share how to use tsdb analyze on prometheus on kubernetes pod, as I cannot exec into the pod itself

**Comment by softwolves** [comment]
my prometheus have  high Number Of Series ，its 10 millions ，so now its down ，more than 50Gi memory needed ，more than 2000 pod need monitor，but its really need so many memory？ how can i reduce  the  Series

**Comment by softwolves** [comment]
@brancz  how can i reduce series  from config
