### ISSUE TITLE
Add Alertmanager config options to Alertmanager crd

### ISSUE THREAD

**Issue by benjaminhuo** [prometheus-operator/prometheus-operator#2766]
**What is missing?**
Currently Alertmanager crd spec doesn't have config options like prometheus crd

Just wondering if it's reasonable to add alert manager config to alertmanager crd spec? 

And then regenerate the alertmanager secrets and then call alertmanager's reload interface?

**Why do we need it?**
Currently we've to edit the alertmanager secret manually and then reload

**Comment by brancz** [comment]
The reload should happen automatically. The reason we haven't added the Alertmanager configuration itself to the CRD is because we see similar collaboration potential with Alertmanager route configurations and receivers as there is with ServiceMonitors. As in each namespace should be able to specify these for themselves.

**Comment by benjaminhuo** [comment]
Thanks for the reply :)
Yes, the reload occurs whenever the secret is updated
You mean we should consider abstracting route and receivers as servicemonitor does?

**Comment by brancz** [comment]
Yes exactly. It'll be some time, but we already have some of this work planned.

**Comment by benjaminhuo** [comment]
Great! The route is kind of recursive, it's a bit complex. Break the big alert config into smaller parts is a good idea 👍

**Comment by midnightconman** [comment]
I would like to see this happen and would be willing to help out... would we first want to see schema, before we start working on code?

**Comment by LiliC** [comment]
Yes defining a schema in advance would be good, feel free to write up initial outline so we have something to start with. Thanks!

cc @simonpasquier

**Comment by brancz** [comment]
There are multiple discussions happening around this, I think we need to start deduplicating (https://github.com/coreos/prometheus-operator/issues/2927).

**Comment by simonpasquier** [comment]
Hello! I've started a design document:
https://docs.google.com/document/d/1aVVttvocop8zNezwrNFbHh_HKRW_fhJUZqhmrr8fGK0/edit?usp=sharing

Feel free to comment there...

**Comment by benjaminhuo** [comment]
@simonpasquier That's great! Will take a look at this!

**Comment by simonpasquier** [comment]
Closed by #3451
