### ISSUE TITLE
Cannot config thanos sidecar cluster.peers in Prometheus Operator

### ISSUE THREAD

**Issue by phuthinh2202** [prometheus-operator/prometheus-operator#2780]
**What did you do?**
Here my config promtheues operator with thanos sidecar:
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  retention: 1d
  serviceAccountName: prometheus
  baseImage: quay.io/prometheus/prometheus
  version: v2.11.0
  serviceMonitorSelector:
    matchLabels:
      release: istio-monitor
  resources:
    requests:
      memory: 400Mi
  thanos:
    baseImage: quay.io/thanos/thanos
    version: v0.7.0
    peers: thanos-peers.monitoring.svc.cluster.local:10900
    objectStorageConfig:
      key: thanos.yaml
      name: thanos-objstore-config
**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:
    v2.11.0

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0"
  
* Kubernetes cluster kind:
   EKS

* Issue
I cannot see "cluster.peers: thanos-peers.monitoring.svc.cluster.local:10900" in container args thanos-sidecar.

Here is result thanos-sidecar when i describe pod:

  thanos-sidecar:
    Container ID:  docker://c7d5d922ee0652aefd90c95184486c015a3a39fe275844d3ff24ac36998020f9
    Image:         quay.io/thanos/thanos:v0.7.0
    Image ID:      docker-pullable://quay.io/thanos/thanos@sha256:fe9cb36d0539f6b8a544e1a27fdb93bd67d533261443104476fa97ef41660b2e
    Ports:         10902/TCP, 10901/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      sidecar
      --prometheus.url=http://localhost:9090/
      --tsdb.path=/prometheus
      --grpc-address=[$(POD_IP)]:10901
      --http-address=[$(POD_IP)]:10902
      --objstore.config=$(OBJSTORE_CONFIG)

May I config wrong?
**Anything else we need to know?**:

**Comment by brancz** [comment]
Cluster peers has been removed in Thanos, gossip doesn't exist anymore, discovery happens just from the querier side.
