### ISSUE TITLE
Generic ScrapeConfig CRD

### ISSUE THREAD

**Issue by auhlig** [prometheus-operator/prometheus-operator#2787]
**What is missing?** **Why do we need it?**

The custom resources `ServiceMonitor`,`PodMonitor` can be used to specify a set of services and pods that should be monitored and for which the Prometheus operator generates the respective scrape config section.
That would also be very useful for k8s nodes.

I'd propose to add `NodeMonitor` generating the [scrape config for nodes](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#node) based on that definition.

I'd be willing to come up with a PR similar to #2566 if there's a general agreement.

**Comment by brancz** [comment]
Can you explain the use cases for this, and why they can't already be achieved with existing PodMonitor/ServiceMonitor objects (if they are Pods within the kubernetes cluster, then these should work no)? It feels to me like things that are outside of Kubernetes are things that should be solved with the `additionalScrapeConfigs` feature, or I'd be open to discussing a more generalized `ScrapeConfig` object.

**Comment by secustor** [comment]
@brancz 
We have the use case that we want to utilize the node role specific meta labels,  
`__meta_kubernetes_node_label_<labelname>` to be exact. 

Further could this be used for the monitoring of kubelets which are, at least in Azure, not by default referenced as service.

**Comment by brancz** [comment]
kubelets are nowhere by default referenced by a service, it's a prometheus operator thing, that syncs nodes into an endpoint object. But still, I expect the person to have access to node information that deeply to have access to the Prometheus used to monitor these, so I feel the additionalScrapeConfigs feature solves that problem.

**Comment by auhlig** [comment]
My initial use case was indeed about things outside of the cluster.
Within the cluster we're good with the existing Service-, PodMonitor + the upcoming BlackboxMonitor IMHO.

Using the `additionalScrapeConfigs` works but always feels "suboptimal" - I'd have to modify the additionalScrapeConfigs-secret and deploy the Prometheus again. 
Compared to using the *Monitor custom resources which I can deployed independently alongside my applications and for which the operator generates the scrape config in the relevant Prometheus. 

I think your idea of a more generic `ScrapeConfig` object is a way better solution for monitoring things outside of Kubernetes and to avoid a `*Monitor`-sprawl @brancz.
This would also cover my use case when it comes to federating metrics from a Prometheus in another cluster.

**Comment by brancz** [comment]
Happy to brainstorm ideas for a `ScrapeConfig` type resource. In my head this could eventually be the only resource that actually generates a Prometheus config, and ServiceMonitors/PodMonitors/BlackboxProbes just generate a `ScrapeConfig` object.

**Comment by bgagnon** [comment]
@brancz I find myself needing a `ScrapeConfig` object as well. Having consumed my only permitted `additionalScrapeConfigs` secret somewhere, I cannot use it again for more scrape configs. 

Combining the two in the same Secret is error prone because the targets are completely unrelated and the manifests are released on a different schedule.

**Comment by brancz** [comment]
Yep agreed. If anyways want to give it a stab, I'd be happy to review a proposal.

**Comment by auhlig** [comment]
So we stick with the 3 CRDs `ServiceMonitors`, `PodMonitors`, `BlackboxMonitors` providing an easy way with sane defaults (e.g. relabelings, out-of-the-box blackbox-exporter, etc.) for the resp. configuration sections.

We introduce a 4th CRD `ScrapeConfig`  which allows configuring any scraping configuration. But without defaults (like relabelings). Completely manual. The struct is pretty much [this](https://github.com/prometheus/prometheus/blob/master/config/config.go#L343-L374).

Internally the [config generation part](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/promcfg.go#L151) should be refactored to reduce code duplication (as currently in `generateServiceMonitorConfig`, `generatePodMonitorConfig`, etc.).
Not sure how much refactoring is actually possible here.

Makes sense or do you have something else in mind @brancz ?

**Comment by brancz** [comment]
That's pretty much exactly what I was thinking yes.

**Comment by Zenlil** [comment]
I'm also in need of scraping the node (i.e kubernetes_sd_configs.role = node)
The big impact of getting node-labels is getting info on different agentpools and GPU enabled nodes. These metrics are only exposed when scraping as a "node" ([prometheus.io](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#node))

The referenced code from @auhlig looks interesting to avoid the "hackish workaround" of additionalScrapeConfigs.
What is the current state of this and how would an example look to get the following rule?
```
- job_name: kubernetes-nodes
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  kubernetes_sd_configs:
  - role: node
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  relabel_configs:
  - separator: ;
    regex: __meta_kubernetes_node_label_(.+)
    replacement: $1
    action: labelmap
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: kubernetes.default.svc:443
    action: replace
  - source_labels: [__meta_kubernetes_node_name]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/$1/proxy/metrics
    action: replace
```

**Comment by omegas27** [comment]
Could we start by actually adding the scrape config CRD to actually deliver this and refactor the code in other PRs to reduce duplication? This might become too big otherwise

**Comment by Geethree** [comment]
This. Is of interest to me as well. Are any docs flying around about this? I'd be curious about jumping in and lending a hand.

**Comment by brancz** [comment]
@QuentinBisson I agree, adding it first and then refactoring the existing ones makes sense to me.

@Geethree I don't think there are design docs for this right now. I'm happy to bounce ideas though if you want to put one together. (if you want reach me on Kubernetes slack @brancz)

**Comment by slashpai** [comment]
I would like to work on it. I am still learning things around operators so will take some time to come with a PR :)

So we need to create new api for scrapeconfig and fields should be scrape_config fields listed in https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config?

**Comment by paulfantom** [comment]
@slashpai since it is quite a large change, it would be good to first start with a design document.

**Comment by iceman91176** [comment]
How can we start this ? @paulfantom - are there templates/examples for design-docs available that could be used ?

**Comment by paulfantom** [comment]
We don't have any design templates, but I can recommend one that is used by thanos and sometimes by prometheus org - https://thanos.io/tip/contributing/proposal-process.md/#template. Or in google doc form - https://docs.google.com/document/d/1AZ1tqk9qGIcVa369hE1J5bm_FTEz7mX1MhU4OJw3xCM/edit

**Comment by chinmaygupta28** [comment]
Are there any in-review proposals for implementing this change yet?

**Comment by fpetkovski** [comment]
We don't have anything yet on this topic, feel free to start a document if you would like to drive the initiative

**Comment by fpetkovski** [comment]
Yeah using the existing section makes sense. We don't have any strict designs process in place, so I am fine with whatever template you think is adequate for now. It's also completely fine that you don't have Golang skills, we can decouple the design from the implementation like we've done for the Prometheus Agent.

Initially we started the agent design as a GDoc, but I felt it was hard to exchange comments and collaborate. So I am fine if we only stick to git-related workflows. Any thoughts @simonpasquier @paulfantom.

**Comment by mddeff** [comment]
@fpetkovski in the interest in keeping this moving, I'll submit a PR for establishing the template/"how to create a proposal doc", we can use that as the comment/discussion mechanism for the process.  Once that's approved I'll push the proposal for this issue.

**Comment by xiu** [comment]
> Are there any in-review proposals for implementing this change yet?

I pushed one in #5279

**Comment by xiu** [comment]
The proposal has now been merged and the implementation can begin 🥳

**Comment by macetw** [comment]
Is this the same?
https://github.com/prometheus-operator/prometheus-operator/pull/5335

**Comment by xiu** [comment]
#5335 was just merged 🎉
