### ISSUE TITLE
How to setup HA using prometheus operator

### ISSUE THREAD

**Issue by nandeeshb09** [prometheus-operator/prometheus-operator#2791]
Hi Team,

Is there any workaround ,on how to setup HA on Prometheus using Prometheus operator.,

Please let us know the procedure or links.(required in eks cluster).

**Comment by brancz** [comment]
This is not currently possible. We are going to need to implement leader election among multiple instances of the prometheus operator. In reality though, if a prometheus operator is down, then it will get rescheduled on a different node and you won't even notice a downtime. If a prometheus operator is in a non-working state though then it's very unlikely that a different replica would be any different.

**Comment by brancz** [comment]
We have no concrete plans as we've never had reported problems where this could have helped. If you want to give it a go though I'd be happy to review it!

**Comment by jmckind** [comment]
I don't mean to confuse this discussion, but I happened upon this issue while looking into something that I am facing regarding the replicas property on the PrometheusSpec.

@nandeeshb09 Are you asking if it is possible to setup HA with regard to Prometheus itself when managed by the operator? For example, multiple Prometheus pods running? I would assume this would be possible using the Replicas property on the PrometheusSpec.

Or, do you mean you want multiple instances of the Operator running in HA, which was answered by @brancz?

**Comment by brancz** [comment]
This was about HA of the prometheus operator itself. Running prometheus HA is just a matter of having 2 or more replicas.

**Comment by bgagnon** [comment]
See earlier discussion in #2491

**Comment by paulfantom** [comment]
Closing as the issue appears to be answered. If you need additional clarification, please reopen it.
