### ISSUE TITLE
PodMonitor TLS configuration

### ISSUE THREAD

**Issue by secustor** [prometheus-operator/prometheus-operator#2802]
At the moment there is no possibility to deactivate the TLS validation when using the PodMonitor. 

Further the PodMonitorEndpoint is missing other features like Auth options.

https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#podmetricsendpoint
https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint

* Environment: AKS, PrometheusOperator community helm chart
* Prometheus Operator version: v0.32.0

**Comment by paulfantom** [comment]
We are open to PRs implementing mentioned features.

**Comment by dgrisonnet** [comment]
If nobody is looking into this right now, I'd be interested in taking over this issue.
