### ISSUE TITLE
Implement allow-list of ServiceMonitors which should be able to access secrets from FS

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#2810]
**What is missing?**
We are able to deny filesystem access for all ServiceMonitors, but we cannot allow-list ones that should have access to FS.

**Why do we need it?**
To allow greater control over secrets.

**Environment**
All

**Anything else we need to know?**:
This is a follow-up to https://github.com/coreos/prometheus-operator/pull/2716 and https://github.com/coreos/prometheus-operator/pull/2808

**Comment by simonpasquier** [comment]
The requirement could be fulfilled with #5618.
