### ISSUE TITLE
Dropping support for prometheus 1.x

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#2813]
Prometheus 2.0 was released almost 2 years ago, maybe it is time to move on and remove support for 1.x from the operator code base. 

Lots of the advanced features that this operator is bringing are not even available on prometheus 1.x. Additionally we test only upgrade path from 1.x to 2.x and not if features run on 1.x, which begs to question how much of operator features are supported in 1.4 (oldest version mentioned in [Documentation/compatibility.md](https://github.com/coreos/prometheus-operator/blob/master/Documentation/compatibility.md)?

cc: @brancz, @metalmatze, @s-urbaniak, @squat, @LiliC, @bwplotka

**Comment by brancz** [comment]
Given that only the upgrade path actually works and only starting with 2.x rules work. I think it’s time to let 1.x go.

**Comment by paulfantom** [comment]
While on subject of dropping support. Can we also drop kubernetes 1.7 (https://github.com/coreos/prometheus-operator/blob/master/pkg/alertmanager/operator.go#L574-L576) ? 

/cc @brancz

**Comment by brancz** [comment]
I think we long stopped supporting kube 1.7.
