### ISSUE TITLE
Expose ReadOnlyRootFilesystem/AllowPrivilegeEscalation options for config-reloader

### ISSUE THREAD

**Issue by ghost** [prometheus-operator/prometheus-operator#2825]
**What is missing?**

I want to set the above configs to comply with security requirements. I cannot do that due to the lack of configs on the operator.

**Why do we need it?**

To comply with security requirements.

**Environment**

Production

* Prometheus Operator version:

    `v0.32.0`

**Anything else we need to know?**:

**Comment by brancz** [comment]
Can this not be achieved with pod security policies?

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
