### ISSUE TITLE
How can I configure storage type to NFS in Thanos Prometheus operator?Any example would help.

### ISSUE THREAD

**Issue by raz08** [prometheus-operator/prometheus-operator#2849]
**What did you do?**

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
There is an example manifest here: https://github.com/coreos/prometheus-operator/blob/f9bc0aa0fd9aa936f500d9d241098863c60d873d/example/storage/persisted-prometheus.yaml

Would you like to write a quick user-guide documentation page documenting this? :)

**Comment by Rajashekharaiah-M** [comment]
Hi Brancz, Thanks for the example. I have done this for Prometheus operator alone, Does the same support for Thanos set up also?

**Comment by brancz** [comment]
All the prometheus operator does is add the Thanos sidecar, it doesn't run any of the other components, so it's orthogonal to the prometheus operator.
