### ISSUE TITLE
Prometheus: be able to modify the volumeMounts settings (prometheus-db data dir)

### ISSUE THREAD

**Issue by clausa20** [prometheus-operator/prometheus-operator#2861]
Prometheus volumes are saving data in the volume disk in a folder prometheus-db.
I would like to be able to customize the location of that data dir so I can reuse and existing old Prometheus data, maybe using volumeClaimTemplate and volumeMounts.

Is there a workaround to do that?
Thanks.

**Comment by brancz** [comment]
There is not, I would recommend to instead just manually once prepare the volume to be in the form the Prometheus operator setup expects it.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
