### ISSUE TITLE
Alertmanager config options issue 

### ISSUE THREAD

**Issue by jbrunetext** [prometheus-operator/prometheus-operator#2862]
**What happened?**
i haved Alertmanager config options issue  , the pods alertmanger wan't start 
**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:
kubectl create -f kube-prometheus/manifests/
**Environment**
K8S cluster 
* Prometheus Operator version:
latest
    `Insert image tag or Git SHA here`
    
Name:                   prometheus-operator
Namespace:              default
CreationTimestamp:      Sun, 17 Nov 2019 15:31:25 +0100
Labels:                 k8s-app=prometheus-operator
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               k8s-app=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:           k8s-app=prometheus-operator
  Service Account:  prometheus-operator
  Containers:
   prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.17.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
    Limits:
      cpu:     200m
      memory:  100Mi
    Requests:
      cpu:        100m
      memory:     50Mi
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-5fff966576 (1/1 replicas created)
Events:          <none>

* Kubernetes version information:

    `kubectl version`
 Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

    RKE

* Manifests:

apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  baseImage: quay.io/prometheus/alertmanager
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 1
  serviceAccountName: alertmanager-main
  version: v0.18.2

* Prometheus Operator Logs:
s=2019-11-17T15:39:27.852610728Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2019-11-17T15:39:27.871184509Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2019-11-17T15:39:27.882709752Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2019-11-17T15:40:00.220366067Z caller=operator.go:325 component=alertmanageroperator msg="Alertmanager updated" key=monitoring/main
ts=2019-11-17T15:40:00.220783248Z caller=operator.go:381 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
ts=2019-11-17T15:40:00.901033882Z caller=operator.go:328 component=prometheusoperator msg="Prometheus updated" key=monitoring/k8s
ts=2019-11-17T15:40:00.901122315Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2019-11-17T15:40:00.913366859Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2019-11-17T15:40:51.108281374Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2019-11-17T15:40:51.120094193Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2019-11-17T15:40:51.136090267Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2019-11-17T15:40:51.145491727Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2019-11-17T15:41:01.223774465Z caller=operator.go:325 component=alertmanageroperator msg="Alertmanager updated" key=monitoring/main
ts=2019-11-17T15:41:01.223856938Z caller=operator.go:381 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main

**Anything else we need to know?**:

i try this to change the statefulset but don't work really 

NAME                                 READY   AGE
statefulset.apps/alertmanager-main   0/1     21m
statefulset.apps/prometheus-k8s      2/2     69m

The issue is 
alertmanager: error: unknown long flag '--mesh.listen-address', try --help

i try to delete the statefulset and edit  by manualy 
rke@julien-SATELLITE-L70-A:/data/rke$ kubectl get statefulset -n monitoring alertmanager-main -o yaml --export=true
Flag --export has been deprecated, This flag is deprecated and will be removed in future.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"Alertmanager","metadata":{"annotations":{},"labels":{"alertmanager":"main"},"name":"main","namespace":"monitoring"},"spec":{"baseImage":"quay.io/prometheus/alertmanager","nodeSelector":{"beta.kubernetes.io/os":"linux"},"replicas":1,"serviceAccountName":"alertmanager-main","version":"v0.15.2"}}
  creationTimestamp: null
  generation: 1
  labels:
    alertmanager: main
  name: alertmanager-main
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Alertmanager
    name: main
    uid: f1e7fefb-72fc-48ba-8305-e64fdf612233
  selfLink: /apis/apps/v1/namespaces/monitoring/statefulsets/alertmanager-main
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      alertmanager: main
      app: alertmanager
  serviceName: alertmanager-operated
  template:
    metadata:
      creationTimestamp: null
      labels:
        alertmanager: main
        app: alertmanager
    spec:
      containers:
      - args:
        - --config.file=/etc/alertmanager/config/alertmanager.yaml
        - --web.listen-address=:9093
        - --mesh.listen-address=:6783
        - --storage.path=/var/alertmanager/data
        - --mesh.peer=alertmanager-main-0.alertmanager-operated.monitoring.svc
        - --web.route-prefix=/
        image: quay.io/prometheus/alertmanager:v0.15.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/v1/status
            port: web
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: alertmanager
        ports:
        - containerPort: 9093
          name: web
          protocol: TCP
        - containerPort: 6783
          name: mesh
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/v1/status
            port: web
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          requests:
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
        - mountPath: /var/alertmanager/data
          name: alertmanager-main-db
      - args:
        - -webhook-url=http://localhost:9093/-/reload
        - -volume-dir=/etc/alertmanager/config
        image: quay.io/coreos/configmap-reload:v0.0.1
        imagePullPolicy: IfNotPresent
        name: config-reloader
        resources:
          limits:
            cpu: 5m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: alertmanager-main
      serviceAccountName: alertmanager-main
      terminationGracePeriodSeconds: 0
      volumes:
      - name: config-volume
        secret:
          defaultMode: 420
          secretName: alertmanager-main
      - emptyDir: {}
        name: alertmanager-main-db
  updateStrategy:
    type: RollingUpdate
status:
  replicas: 0

**Comment by jbrunetext** [comment]
https://ibb.co/NCVW4gx

**Comment by jbrunetext** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/f8XKimd"><a href="//imgur.com/a/f8XKimd"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by simonpasquier** [comment]
` quay.io/coreos/prometheus-operator:v0.17.0` is a very old version that isn't compatible with Alertmanager >= v0.16.0. You should update to a recent of prometheus-operator.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.
