### ISSUE TITLE
There are 2 reloaders running when Thanos sidecar added

### ISSUE THREAD

**Issue by codwu** [prometheus-operator/prometheus-operator#2882]
**What is missing?**

Thanos sidecar can watch changes in Prometheus configuration and reload it, while Prometheus Operator also have a prometheus-config-reloader. We cannot disable any one of them now. 

**Why do we need it?**

One reloader is enough. so we should disable one of the reloaders. Unfortunately, it seems that Thanos sidecar cannot be disabled

**Environment**

* Prometheus Operator version:

    v0.34.0
    

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
AFAICT the Prometheus operator doesn't tell the Thanos sidecar about the Prometheus configuration file so the Thanos reloader is effectively inactive.

**Comment by brancz** [comment]
That is correct, also while they both have reload functionality the prometheus operator one is more specific and is able to prevent unnecessary reloads for example, so in some ways it's smarter. Some of these things are prometheus operator specific so they will never end up in the thanos reloader. I think it's fine as is. Is this actually a problem?

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
