### ISSUE TITLE
Can't specify retention only by size

### ISSUE THREAD

**Issue by ThePants999** [prometheus-operator/prometheus-operator#2883]
**What happened?**
I specified a `retentionSize` in my Prometheus resource and did not specify `retention`. The resulting Prometheus deployment had `--storage.tsdb.retention.size` set correctly, but also had `--storage.tsdb.retention.time=24h`.

**Did you expect to see some different?**
Prometheus allows retention time to be omitted if retention size is specified, so I expected to see retention time omitted from the Prometheus config since I omitted it from my Prometheus resource.

**How to reproduce it (as minimally and precisely as possible)**:
Create a Prometheus object with retentionSize and no retention.

**Environment**

* Prometheus Operator version:

quay.io/coreos/prometheus-operator:v0.34.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-41be3d", GitCommit:"41be3d46034bc1d637f82d35a6eee5df7efc5142", GitTreeState:"clean", BuildDate:"2019-11-20T17:19:16Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

EKS

**Comment by ThePants999** [comment]
Obviously this has a pretty simple workaround: specify a really really long retention time :-)

**Comment by brancz** [comment]
I think it would be correct to not add time retention when only size retention is configured. Would you like to create a PR to fix this? :)

**Comment by gleichda** [comment]
@petergood will you still work on that?
