### ISSUE TITLE
cross-namespace monitoring RBAC

### ISSUE THREAD

**Issue by aceeric** [prometheus-operator/prometheus-operator#2896]
I followed these steps:
1. Create a subscription to the Prometheus operator
2. Verify the operator is running
3. Create an additional scrape config secret and a `Prometheus` CR with `serviceMonitorNamespaceSelector: {}`
4. Wait for the Prometheus pod to come up
5. Observe the prometheus container logs with numerous "failed to list pods, services, etc."
6. Create a clusterrole and clusterrolebinding to allow the Prometheus pod's serviceaccount to get/list/watch resources in other namespaces
7. Observe that the RBAC errors no longer flow into the container logs

I think it would be reasonable for the Prometheus Operator to inspect the Prometheus CR `serviceMonitorNamespaceSelector` and if it indicates that other namespaces are being monitored, to also generate the cluster role and binding. It seems counter-intuitive to have to manage the RBACs manually when much of the other functionality is delegated to the Operator. (Or maybe I'm going about it the wrong way)

**Comment by brancz** [comment]
The reasoning here is the principle of least privilege, the RBAC roles have to be granted to the discovering Prometheus so the Prometheus only has exactly the roles it needs, as opposed to let's say list/watch on every namespace in a cluster, which could be far greater than what it truly needs.

**Comment by aceeric** [comment]
I guess what I'm trying to say - perhaps badly - is that if one declares the desired state of monitoring, then it seems reasonable to expect the operator to effect all the configurations that are required to implement that declared state - including RBAC. In this scenario, it would be up to the operator to assign least privileges. For example, if the Prometheus declaration is is to watch namespaces X, Y, and X, then the operator could grant list/watch to Prometheus on those namespaces. If the scrape configs indicate service scraping, then the operator assigns those RBACs. If the scrape configs indicate node scraping, then those RBACs are assigned. Same for pod, etc. (based on the kubernetes_sd_configs).

**Comment by brancz** [comment]
I get what you're saying but for the prometheus operator to be able to do that, it would need cluster wide access as it can only grant what it has permission for

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
