### ISSUE TITLE
Prometheus operator storage guide

### ISSUE THREAD

**Issue by eduartua** [prometheus-operator/prometheus-operator#2905]
**What did you do?**
Installed prometheus-operator with helm 3 and set the values in `storageSpec` from the `values.yaml`
Should I create the PV and PVC resources manually?
**Did you expect to see some different?**
The storage guide is not in the repo anymore. Is there a storage guide?
I was expecting to see that storage specification in the statefulset rendered manifest.
```
## Prometheus StorageSpec for persistent data
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md
```
**Environment**
GKE 1.14.7
* Prometheus Operator version:
    `v0.34.0`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/am
d64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.23", GitCommit:"81c87c699557fed991e292cd328b2129c2f242a2", GitTreeState:"clean", BuildDate:"2019-11-07T19:23:23Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platfor
m:"linux/amd64"}`
    

* Kubernetes cluster kind:

   GKE

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
It seems like we should bring those docs back. I can find the last released version here: https://github.com/coreos/prometheus-operator/blob/release-0.29/Documentation/user-guides/storage.md

Other than the kube-prometheus links I think everything should still be valid, and we can cross link to the new repository: https://github.com/coreos/kube-prometheus

Would you like to shoot us a PR with fixed links re-introducing these docs? :)

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
