### ISSUE TITLE
Add ability to set per-replica remote_write url

### ISSUE THREAD

**Issue by valyala** [prometheus-operator/prometheus-operator#2917]
**What is missing?**

There is no way to configure distinct `remote_write` url per each Prometheus replica created with `prometheus-operator`.

**Why do we need it?**

This functionality could be useful for HA setup, when each Prometheus replica writes data to its own remote storage instance. Such a setup prevents from data loss or delay in data delivery if certain remote storage instance is temporary unavailable.

**Comment by brancz** [comment]
I can see what you're aiming for, I think this could be generally useful also for geographical distribution. It's a bit difficult though just not super aligned with how the prometheus-operator works today in regards to consistency across replicas. One thing that comes to mind: what speaks against having all instances having all remote write targets? That would prevent configuration inconsistency across replicas.

The only place where we have something that goes in a similar direction but not quite the same characteristics, as it's automated templating rather than per replica config, would be the replica external label we add automatically.

Generally we try to be agnostic about workflows, so worst case would be creating a separate Prometheus object per remote write target, but I get that that's not ideal. If you have an idea for an API that would work elegantly I'm happy to review it and give it a thought.

Do you have some concrete examples of setups like this? That might make it easier to think of possible APIs.

**Comment by valyala** [comment]
> I can see what you're aiming for, I think this could be generally useful also for geographical distribution.

Yes, this is the main use case for distinct remote_write urls per Prometheus replica - replicating the data among distinct availability zones.

> One thing that comes to mind: what speaks against having all instances having all remote write targets?

This can be OK, but this multiplies the amount of transferred and stored data, which could be undesired in certain cases.

> The only place where we have something that goes in a similar direction but not quite the same characteristics, as it's automated templating rather than per replica config, would be the replica external label we add automatically.

This looks like good idea. For instance, we `prometheus-operator` could automatically generate prefix for the configured `remote_write` url if `replicaPrefixRemoteWriteURL` is set:
```
prometheus.prometheusSpec.remoteWrite.url: "http://foo.bar/baz"
prometheus.prometheusSpec.replicaPrefixRemoteWriteURL: true
prometheus.prometheusSpec.replicas: 2
```

Would generate the following `remote_write` url for each replica:
* `http://1.foo.bar/baz`
* `http://2.foo.bar/baz`

Then `external service` for each `*.foo.bar` could be configured for pointing to the real remote storage domain or IP.

> Do you have some concrete examples of setups like this? That might make it easier to think of possible APIs.

The setup is:
* Multiple Prometheus replicas write data to distinct remote storage instances for high availability purposes. When a certain remote storage instance is temporarily unavailable, the data continues to flow to healthy remote storage instance.
* [Promxy](https://github.com/jacksontj/promxy) is used for querying multiple remote storage instances and merging the replicated data. If certain remote storage instance is unavailable, then Promxy would continue working by querying data from the remaining remote storage instances.

**Comment by brancz** [comment]
I haven't tried this myself, but this should actually already work thanks to https://github.com/coreos/prometheus-operator/pull/2591. You should be able to specify the remote write URL with the `$(STATEFULSET_ORDINAL_NUMBER)` substitution within the URL and you should be all set. Could you try that?

**Comment by valyala** [comment]
This looks like the way to go! Thanks for the pointer! It would be great documenting this.

**Comment by brancz** [comment]
Agreed. Do you want to maybe write up a remote-write user-guide describing both the "single" and per-replica strategy?

**Comment by valyala** [comment]
I'll try creating the user guide for remote_write options in `prometheus-operator` and sending a pull request in the near future. Should it be published as a distinct doc or should it be incorporated into existing docs?

**Comment by brancz** [comment]
I think a distinct doc in the user guide directory would make sense. Thanks! :)

**Comment by samuelvl** [comment]
Was this feature finally implemented? Is it possible to enable remote_write only for one replica?

**Comment by brancz** [comment]
As described in the discussion, the requested feature is already possible. You cannot just enable remote write for one replica, but you can create two identical Prometheus objects and have the only difference be the remote write configuration.

**Comment by brancz** [comment]
I'm going to close this as the initial request in this issue is possible, and is at most lacking some documentation. If there are other issues please feel free to open a new issue describing is believed to be a problem with the prometheus operator. Thanks! :)
