### ISSUE TITLE
Strategy update for every prometheus/StateFullSet resources.

### ISSUE THREAD

**Issue by IKSIN** [prometheus-operator/prometheus-operator#2967]
**What is missing?**
Update sts from prometheus operator one by one (not all at the same time). Or implement some strategy update.

**Why do we need it?**
We have 22 instances of prometheus in our k8s cluster (11 of them are replicas with different external_labels and retentions). After upgrade prometheus-operator image all STS recreated/updated and all pods go to restart at the same time.

**Environment**

* Prometheus Operator version:

    `v0.35.0`
    

**Anything else we need to know?**:
Some ways to resolve problems:
1. Update/recreate STS from prometheus CRD's one by one (kind of maxUnavailable)
2. Something like k8s Pod Disruption Budgets for specify pairs of origin-replica instances.

**Comment by brancz** [comment]
I agree this would be nice. Do either of 1. or 2. you suggested work with a statefulset that has the parallel pod management policy enabled?

**Comment by IKSIN** [comment]
@brancz Not sure that I understood you right. We not use parallel pod management policy, because `replicas=1` in every statefulset. We can't use replicastion, becasuse every instance of prometheus has uniq parameters.

**Comment by d-ulyanov** [comment]
@brancz hello! We have at least different external labels on each Prom for deduplication on Thanos (replica=A, replica=B),

**Comment by brancz** [comment]
You will definitely need to run 2 replicas of Prometheus to get some form of high availability here during rollouts. The question then becomes how do we make the statefulset controller only update one pod at a time. This was previously the case when we used the `OrderedReady` pod management policy, but this caused problems where the statefulset stalled if there was any error and human intervention was required to get it to continue.

**Comment by IKSIN** [comment]
I think, that It must be internal logic of operator to connect few STS (i.e. by label) and recreate them consistently

**Comment by paulfantom** [comment]
This is more specifically covered by https://github.com/prometheus-operator/prometheus-operator/issues/3917, https://github.com/prometheus-operator/prometheus-operator/issues/2753, and https://github.com/prometheus-operator/prometheus-operator/issues/3875. Closing in favor of those issues. If you think this issue is still valid, please reopen it.
