### ISSUE TITLE
Consider making the `pkg/apis/monitoring` package a nested go module

### ISSUE THREAD

**Issue by pepov** [prometheus-operator/prometheus-operator#2988]
**What is missing?**
The ability to import only the monitoring apis from another project instead of the whole module.

**Why do we need it?**
There are several dependencies that could easily cause conflicts with existing local versions in a downstream project. This change would limit the affect of such conflicts.

Note: I would be glad to take a stab at it.

**Comment by LiliC** [comment]
@pepov Do you have another example of an operator where this is done this way?

**Comment by pepov** [comment]
@LiliC yes:
- https://github.com/banzaicloud/logging-operator/tree/master/pkg/sdk
- https://github.com/banzaicloud/bank-vaults/tree/master/pkg/sdk

Although these modules are not just for types, but the concept is the same.

**Comment by LiliC** [comment]
Sounds interesting, this would help us with any cycle dependencies as well. 

cc @coreos/team-monitoring thoughts?

**Comment by bwplotka** [comment]
Nested dependencies are hard to play with, but to me this case is very solid.

Looks like this is yet another use case for [`modularize`](https://github.com/Helcaraxan/modularise-example-core) @Helcaraxan (:

**Comment by simonpasquier** [comment]
I agree it would be useful.

**Comment by Helcaraxan** [comment]
Am still working hard (although in stealth mode) on `modularise`. Will follow up here as soon as I have a working first version. I don't know about the timelines here but I _hope_ that I can have something in 1-2 months based on my current progress.

**Comment by brancz** [comment]
I think modularise would be a very good use case!

**Comment by Helcaraxan** [comment]
Just to add to @bwplotka's point about nested modules being tricky: if there's the possibility to wait for `modularise` to be available and take a stab at this then that would be worthwhile in my opinion.

Based on my ever growing experience with projects and people going the nested modules way it is not something you'd want to do. It's more likely to hurt both project maintainers AND downstream projects than it is likely to benefit either. For what it's worth the Go team modules-experts themselves strongly recommend not using multiple modules per repository.

**Comment by simonpasquier** [comment]
This is available for a few releases now: https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/apis/monitoring/go.mod
