### ISSUE TITLE
AlertManager StatefulSet should support HostPort

### ISSUE THREAD

**Issue by yannh** [prometheus-operator/prometheus-operator#3011]
**What is missing?**

It is currently not possible to configure the AlertManager StatefulSet generated by Prometheus-operator to use hostPort.

**Why do we need it?**

We have multiple Kubernetes clusters, each running Prometheus deployed using the Prometheus Operator. To get cross-cluster alert deduplication, we would like those Prometheus servers to send alerts to a central AlertManager.

We're looking at using External-DNS to expose the AlertManager service using DNS (https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/hostport.md#kafka-stateful-set ), but for this we would need the AlertManager StatefulSet to expose ports with HostPort. 

Looking at https://github.com/coreos/prometheus-operator/blob/70c28704748bb63b794fcc0d76816e5f9ca64bb4/pkg/alertmanager/statefulset.go#L334-L354  it seems this is not supported yet? 

**Anything else we need to know?**:

**Comment by brancz** [comment]
Exposing Alertmanager on hostport is not a good idea for security reasons. Alertmanager as is is entirely unprivileged, hostport opens this door. We're unlikely to ever implement the support for this. There are other ways to expose Alertmanager, that would not require hostport, I recommend you to look into those.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
