### ISSUE TITLE
ISSUE : http://{appname}:9080/metrics: read tcp 1{ip}:54948->{ip}:9080: read: connection reset by peer

### ISSUE THREAD

**Issue by HanithaKrishnaraj** [prometheus-operator/prometheus-operator#3017]
Hi Team,

I have posted my question in google forum and it's been a week hitting my head.

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/prometheus-users/84P78yZ7opw/mwRDPegZAwAJ

I tried many ways but still facing issue **"target state is down"**

**Comment by brancz** [comment]
For us to be able to help you it would be good to explain exactly what you did and how we can reproduce it, however, from the mailing list thread it does not look like you're using the Prometheus Operator, so this is just a general Prometheus question.

If you want to try it with the Prometheus Operator, then I recommend our [getting started guide](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md).

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
