### ISSUE TITLE
CRD manifests are now generated with status field

### ISSUE THREAD

**Issue by omerlh** [prometheus-operator/prometheus-operator#3022]
**What happened?**
I update my jsonnet library to the latest version and noticed that now the CRDs contains a new field, `status`. This is problematic when using GitOps tools like flux/argo - as this field is updated by k8s and therefore the sync from Git to Kubernetes fails.

**Did you expect to see some different?**
No

**How to reproduce it (as minimally and precisely as possible)**:
Generate manifests using the latest jsonnet library:

![image](https://user-images.githubusercontent.com/6730584/74249931-93947c80-4cf2-11ea-82aa-ec58e880be4f.png)

**Comment by omerlh** [comment]
A workaround for the issue is by doing the following jsonnet magic (if using `kube-prometheus`):
```jsonnet
    local po = super.prometheusOperator,
    prometheusOperator:: 
    {
      
      [name]: std.mergePatch(po[name], {
          status: null,
        })
      for name in std.objectFields(po)
    },
```

**Comment by brancz** [comment]
@pgier can we make sure we remove this entirely? We’re not setting any status so let’s remove the connection until we do.

**Comment by lilic** [comment]
@omerlh you are also welcome to remove this by doing a PR! 😊
