### ISSUE TITLE
Prometheus-operator(version 0.36.0) status is showing "CrashLoopBackOff"

### ISSUE THREAD

**Issue by raonelakurti** [prometheus-operator/prometheus-operator#3072]
I've tried installing prometheus component by using helm:

**Command:** 
helm install --name prom-ns1 stable/prometheus-operator --set grafana.enabled=false,alertmanager.enabled=false,nodeExporter.enabled=false,prometheusOperator.enabled=false,kubeStateMetrics.enabled=false --namespace ns1

**Prometheus pod logs**: 
ometheus-0 (none))"
level=info ts=2020-03-09T19:56:16.211Z caller=main.go:333 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-03-09T19:56:16.211Z caller=main.go:334 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-03-09T19:56:16.214Z caller=main.go:648 msg="Starting TSDB ..."
level=info ts=2020-03-09T19:56:16.214Z caller=web.go:506 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-03-09T19:56:16.221Z caller=head.go:584 component=tsdb msg="replaying WAL, this may take awhile"
level=info ts=2020-03-09T19:56:16.304Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=17
level=info ts=2020-03-09T19:56:18.825Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=1 maxSegment=17
level=info ts=2020-03-09T19:56:20.803Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=2 maxSegment=17
level=info ts=2020-03-09T19:56:23.405Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=3 maxSegment=17
level=info ts=2020-03-09T19:56:23.803Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=4 maxSegment=17
level=info ts=2020-03-09T19:56:24.402Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=5 maxSegment=17
level=info ts=2020-03-09T19:56:24.705Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=6 maxSegment=17
level=info ts=2020-03-09T19:56:24.808Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=7 maxSegment=17
level=info ts=2020-03-09T19:56:26.304Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=8 maxSegment=17
level=info ts=2020-03-09T19:56:26.710Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=9 maxSegment=17
level=info ts=2020-03-09T19:56:27.605Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=10 maxSegment=17
level=info ts=2020-03-09T19:56:27.607Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=11 maxSegment=17
level=info ts=2020-03-09T19:56:28.013Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=12 maxSegment=17
level=info ts=2020-03-09T19:56:28.220Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=13 maxSegment=17
level=info ts=2020-03-09T19:56:28.230Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=14 maxSegment=17
level=info ts=2020-03-09T19:56:28.232Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=15 maxSegment=17
level=info ts=2020-03-09T19:56:28.303Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=16 maxSegment=17
level=info ts=2020-03-09T19:56:28.303Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=17 maxSegment=17
level=info ts=2020-03-09T19:56:29.630Z caller=main.go:663 fs_type=XFS_SUPER_MAGIC
level=info ts=2020-03-09T19:56:29.630Z caller=main.go:664 msg="TSDB started"
level=info ts=2020-03-09T19:56:29.630Z caller=main.go:734 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2020-03-09T19:56:29.703Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-03-09T19:56:29.705Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-03-09T19:56:29.706Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-03-09T19:56:29.907Z caller=main.go:762 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2020-03-09T19:56:29.907Z caller=main.go:617 msg="Server is ready to receive web requests."

**Prometheus-config-reloader:**
ts=2020-03-09T18:48:09.808760527Z caller=main.go:85 msg="Starting prometheus-config-reloader version '0.35.0'."
level=info ts=2020-03-09T18:48:09.809178389Z caller=reloader.go:127 msg="started watching config file for changes" in=/etc/prometheus/config/prometheus.yaml.gz out=/etc/prometheus/config_out/prometheus.env.yaml
level=error ts=2020-03-09T18:48:09.810388145Z caller=runutil.go:87 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post http://127.0.0.1:9090/-/reload: dial tcp 127.0.0.1:9090: connect: connection refused"
level=info ts=2020-03-09T18:48:15.313556522Z caller=reloader.go:258 msg="Prometheus reload triggered" cfg_in=/etc/prometheus/config/prometheus.yaml.gz cfg_out=/etc/prometheus/config_out/prometheus.env.yaml rule_dirs=

**Output:**

<img width="704" alt="Screen Shot 2020-03-09 at 2 59 39 PM" src="https://user-images.githubusercontent.com/35678373/76252376-a1b4ba80-6216-11ea-87b5-d2d9e754ceda.png">

**Comment by brancz** [comment]
Which of the 3 containers is actually crashlooping?

**Comment by raonelakurti** [comment]
It's crashing prometheus pod. When I've checked the events on the corresponding namespace, I've seen "OOMKILLED" status and after that CrashLoopBackoff. So I've tried passing CPU and Memory limits.
Command:
helm install --name prometheus-ns1 stable/prometheus-operator --set resources.limits.cpu=1,resources.limits.memory=1Gi,resources.requests.cpu=0.5,resources.requests.memory=512Mi,grafana.enabled=false,alertmanager.enabled=false,nodeExporter.enabled=false,prometheusOperator.enabled=false,kubeStateMetrics.enabled=false --namespace ns1

It worked for six days and after that it's showing CrashLoopBackOff status.

**Comment by brancz** [comment]
Sounds like you need to give prometheus more memory :)

**Comment by raonelakurti** [comment]
I've already assigned 1Gb memory and we are not what's causing the issue

**Comment by brancz** [comment]
Depending on how many time series you are collecting, 1gb might be very little. I recommend increasing it further and then understand how many time series are being ingested and how many sample. That will decide how much memory will be required to run prometheus.

**Comment by raonelakurti** [comment]
I've extended memory to 2gb even after that it's crashing. So we have decided to create one more replica and wanted to see the behavior.
helm install --name prometheus-test stable/prometheus-operator --set resources.limits.cpu=1,resources.limits.memory=2Gi,resources.requests.cpu=0.5,resources.requests.memory=1Gi,grafana.enabled=false,prometheus.prometheusSpec.replicas=2,alertmanager.enabled=false,nodeExporter.enabled=false,prometheusOperator.enabled=false,kubeStateMetrics.enabled=false --namespace test

To define resources requests and limits for the pod, I'm using the above command. Please correct me if I'm wrong.

**Comment by brancz** [comment]
Increasing replicas does not distribute load with Prometheus. You would be increasing availability as you would get more replicas with the same data, but you won’t need less memory.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
