### ISSUE TITLE
Clarify usage of VolumeMounts

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#3073]
Currently we have 2 methods of appending volumes to prometheus and alertmanager CRs:
- "hacky" strategic merge patch
- VolumeMounts CRD field

Can we refactor to promote only one method instead of both?

/cc @brancz @lilic

**Comment by pgier** [comment]
I think the container merge patch should always be the last option when nothing else works in terms of config.  Would be nice if this was clearer in the docs.

**Comment by brancz** [comment]
> "hacky" strategic merge patch

As @pgier said, this is already only the last resort and explicitly not a supported thing, just an escape hatch. VolumeMounts are the only supported feature here so I don't see a conflict. That said if we feel the docs aren't sufficient I also think they should be clearer. I do believe we say this explicitly in the containers strategic merge patch.
