### ISSUE TITLE
Question: How to remove all labels that are injected by the prom operator

### ISSUE THREAD

**Issue by eli-jordan** [prometheus-operator/prometheus-operator#3082]
What configuration do I need to define to avoid having the operator / prometheus inject additional metrics to scraped metrics. e.g. I'd like to prevent the `pod=<pod-id>` label from being added.

**Comment by brancz** [comment]
You need to define a relabeling rule with the `action: droplabel` matching the labels you want to drop.

**Comment by paulfantom** [comment]
Closing as the issue appears to be answered. If you need additional clarification, please reopen it
