### ISSUE TITLE
Admission controller - absent_over_time parses as a failure

### ISSUE THREAD

**Issue by allen13** [prometheus-operator/prometheus-operator#3087]
**What happened?**

When creating a PrometheusRule with an `absent_over_time` function it gets rejected by the admission controller as bad. This function was released in v2.16.0. Updating the prometheus dependency will get the latest version of rulefmt which will resolve this issue. https://github.com/coreos/prometheus-operator/blob/master/go.mod#L39

Prometheus Operator version:
v0.37.0

**Comment by brancz** [comment]
Would you like to take care of bumping the dependency? :)
