### ISSUE TITLE
Moving APIs to separate package

### ISSUE THREAD

**Issue by mnaser** [prometheus-operator/prometheus-operator#3097]
**What did you do?**
I've attempted to use the Prometheus Golang types inside another operator and due to the fact that means I have to import all of `coreos/prometheus-operator` -- It results in some conflicts with my own dependencies.

It would be nice if the project could look into moving it's types out to a seperate repo so users that interact with the Golang Kubernetes APIs can reference them

**Did you expect to see some different?**
Something similar to this: https://github.com/kubernetes/api

**Environment**
N/A

* Prometheus Operator version:
N/A

* Kubernetes version information:
N/A

* Kubernetes cluster kind:
N/A

* Manifests:
N/A

* Prometheus Operator Logs:
N/A

**Anything else we need to know?**:
I would be willing to do the work if this is something the team agrees with

**Comment by matthiasr** [comment]
We ran into this problem as well. I believe it is not necessary to move the package at all – adding a `go.mod` to `pkg/apis` would allow importing just the dependencies of those packages (k8s.io/api and k8s.io/apimachinery).

**Comment by matthiasr** [comment]
#3395 in an attempt to do this.
