### ISSUE TITLE
Provide arguments docs in the project. These should be generated from the code and should reflect operator --help output.

### ISSUE THREAD

**Issue by etcshad0vv** [prometheus-operator/prometheus-operator#3104]
Hello,

I am looking for documentation of arguments i can pass to prometheus-operator. Is this somewhere available?

Thank you

**Comment by lilic** [comment]
Yes, if you compile the binary you can do `operator --help` that should give you the list of them.

**Comment by etcshad0vv** [comment]
I guess that means the arguments are not documented, right?

**Comment by lilic** [comment]
Yes they are only available when you run the binary, so agreed we could have docs for them generated based on that. 

Do you mind editing the description of this issue to say something like "Provide arguments docs in the project. These should be generated from the code and should reflect operator --help output." or if you want to open a new issue. Thanks!

**Comment by etcshad0vv** [comment]
Sure, description has been updated @lilic .

**Comment by lilic** [comment]
Feel free to work on it, otherwise we can make it as help-wanted. 😊

**Comment by raptorsun** [comment]
I'm going to work on it.

**Comment by raptorsun** [comment]
Here is the pull request to generate documents for operator executable:
https://github.com/prometheus-operator/prometheus-operator/pull/4112
