### ISSUE TITLE
 PrometheusDuplicateTimestamps might not be actionable

### ISSUE THREAD

**Issue by omerlh** [prometheus-operator/prometheus-operator#3124]
See prometheus/prometheus#7091

**What did you do?**
The alert PrometheusDuplicateTimestamps triggered when there is any target with invalid timestamps (e.g.. same timestamp, different values). When running a single Prometheus with a lot of targets, this alert is not actionable - it does not contain the offending target, making it hard to route it to the relevant team/person owning this service.

**Comment by brancz** [comment]
Actually the alert is defined in the prometheus mixin which is in the prometheus repo. https://github.com/prometheus/prometheus/blob/34c7f6e3c4db66b6f630b2ba55f84b13f50cbb21/documentation/prometheus-mixin/alerts.libsonnet#L142

The alert is warning severity which generally means yes you should look at it, but it's not urgent. Definitely no one should be paged on it. I agree that it's harder to troubleshoot in a multi-tenant/user scenario, but doesn't Prometheus log which target caused this? That should help figuring out which target is acting up.

**Comment by omerlh** [comment]
Yes it is, the question is - does the alert actionable enough? The runbook is something like "look for the offending service in the log and ping the relevant team responsible for it". This is why I feel it might not be a very actionable alert.

**Comment by brancz** [comment]
I think what you described is actionable, but not urgent. Warning severity seems appropriate here.

**Comment by gna582** [comment]
Ok, I'm legit confused. I get this error. There is no log regarding which are the targets that are providing the duplicates. The alert also doesn't specify this in any manner.

Could you help me figure out which of my targets are providing these duplicates?

Thanks a lot!

**Comment by paulfantom** [comment]
@gna582 try checking services listed in promql: `scrape_samples_scraped-scrape_samples_post_metric_relabeling > 0` and you can also check this article for more help: https://www.robustperception.io/debugging-out-of-order-samples

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
