### ISSUE TITLE
Remove `context.TODO()` used in Kubernetes client function calls

### ISSUE THREAD

**Issue by joelanford** [prometheus-operator/prometheus-operator#3158]
**What is missing?**
After https://github.com/coreos/prometheus-operator/pull/3154 merges, the prometheus-operator repo will contain `context.TODO()` in all Kubernetes client function calls.

We should follow up by plumbing real contexts through the call stack so that `context.TODO()` can be removed.

**Why do we need it?**
See https://github.com/coreos/prometheus-operator/pull/3154#issuecomment-617758087

**Environment**
Kubernetes 1.18+

* Prometheus Operator version: N/A

**Anything else we need to know?**: Don't think so :)

**Comment by arghya88** [comment]
So create `context.Context` somewhere at the beginning and use the same everywhere?

**Comment by simonpasquier** [comment]
yes the main context is created [here](https://github.com/prometheus-operator/prometheus-operator/blob/467d744ca9e892da7c5bea1cfb364420986e8d53/cmd/operator/main.go#L258)

AFAICT it's almost done for the operator's code (except one function in `pkg/listwatch/listwatch.go`). I'm not sure what should be done for monitoring informers. And for e2e tests we don't have a concrete context to pass...

```
$ find . -name "*go" | xargs grep -l context.TODO 
./pkg/listwatch/listwatch.go
./pkg/client/informers/externalversions/monitoring/v1/podmonitor.go
./pkg/client/informers/externalversions/monitoring/v1/prometheusrule.go
./pkg/client/informers/externalversions/monitoring/v1/probe.go
./pkg/client/informers/externalversions/monitoring/v1/alertmanager.go
./pkg/client/informers/externalversions/monitoring/v1/thanosruler.go
./pkg/client/informers/externalversions/monitoring/v1/servicemonitor.go
./pkg/client/informers/externalversions/monitoring/v1/prometheus.go
./test/framework/probe.go
./test/framework/admission-webhooks.go
./test/framework/secret.go
./test/framework/deployment.go
./test/framework/namespace.go
./test/framework/role-binding.go
./test/framework/crd.go
./test/framework/alertmanager.go
./test/framework/thanosruler.go
./test/framework/prometheus_rule.go
./test/framework/pod.go
./test/framework/helpers.go
./test/framework/ingress.go
./test/framework/service_account.go
./test/framework/config_map.go
./test/framework/framework.go
./test/framework/prometheus.go
./test/framework/cluster_role.go
./test/framework/replication-controller.go
./test/framework/cluster_role_binding.go
./test/framework/service.go
./test/framework/event.go
./test/e2e/alertmanager_test.go
./test/e2e/prometheus_instance_namespaces_test.go
./test/e2e/prometheus_test.go
./test/e2e/alertmanager_instance_namespaces_test.go
./test/e2e/main_test.go
./test/e2e/denylist_test.go
```

**Comment by slashpai** [comment]
I would like to take this one, some starting points would be helpful

**Comment by simonpasquier** [comment]
@slashpai there are least 2 "easy-to-fix" places where we should replace `context.TODO()` by the context passed to the function
https://github.com/prometheus-operator/prometheus-operator/blob/2b93704fc1d1d5dbc4e7aa98c2a1425a48bbca42/pkg/prometheus/operator.go#L1421
https://github.com/prometheus-operator/prometheus-operator/blob/2b93704fc1d1d5dbc4e7aa98c2a1425a48bbca42/pkg/prometheus/operator.go#L1338

Regarding the testing framework (for instance [here](https://github.com/prometheus-operator/prometheus-operator/blob/2b93704fc1d1d5dbc4e7aa98c2a1425a48bbca42/test/framework/alertmanager.go#L125)) and since the Go tests have no context wrapping them, my suggestion would be to add a `context.Context` field to the [Framework](https://github.com/prometheus-operator/prometheus-operator/blob/2b93704fc1d1d5dbc4e7aa98c2a1425a48bbca42/test/framework/framework.go#L52-L61) struct, initialize it to `context.Background()` and pass it wherever needed in place of `context.TODO()`.

**Comment by slashpai** [comment]
After #4104 merged we have context.TODO() now in following files

```bash
░▒▓    ~/gi/s/prometheus-operator  on   remove_context_todo ⇣3⇡3   find . -name "*go" | xargs grep -l context.TODO      ✔  2.7.17   1.16.4   2.7.3   at admin/openshift-monitoring ⎈  at 17:59:31  ▓▒░
./test/framework/deployment.go
./test/framework/service.go
./test/framework/role-binding.go
./test/framework/cluster_role.go
./test/framework/service_account.go
./test/framework/ingress.go
./test/framework/admission-webhooks.go
./test/framework/cluster_role_binding.go
./test/framework/secret.go
./test/framework/helpers.go
./test/framework/namespace.go
./test/framework/replication-controller.go
./pkg/alertmanager/amcfg_test.go
./pkg/k8sutil/k8sutil_test.go
./pkg/client/informers/externalversions/monitoring/v1/podmonitor.go
./pkg/client/informers/externalversions/monitoring/v1/prometheusrule.go
./pkg/client/informers/externalversions/monitoring/v1/servicemonitor.go
./pkg/client/informers/externalversions/monitoring/v1/alertmanager.go
./pkg/client/informers/externalversions/monitoring/v1/probe.go
./pkg/client/informers/externalversions/monitoring/v1/prometheus.go
./pkg/client/informers/externalversions/monitoring/v1/thanosruler.go
./pkg/client/informers/externalversions/monitoring/v1alpha1/alertmanagerconfig.go

░▒▓    ~/gi/s/prometheus-operator  on   remove_context_todo ⇣3⇡3 
```
