### ISSUE TITLE
Supporting prometheus 2.17.2

### ISSUE THREAD

**Issue by benjaminhuo** [prometheus-operator/prometheus-operator#3172]
There are 2 minor prometheus releases 2.17.1 and 2.17.2 since 2.17.0 in which memory leak or cpu/memory consumption fixes are included.
Is it safe to add v2.17.2 to operator's compatibility matrix and then update kube-prometheus?

Thanks
Ben

**Comment by brancz** [comment]
Feel free to add them, I don’t see a reason why not.

**Comment by benjaminhuo** [comment]
Sure :)
