### ISSUE TITLE
Unable to mount EFS volume 

### ISSUE THREAD

**Issue by vrathore18** [prometheus-operator/prometheus-operator#3189]
I am started getting this error(previously it was working) and prometheus stucked at container creating.
`prometheus-qa-prometheus-operator-k8s-prometheus-0           0/3     ContainerCreating   0          2m35s`
PS. DNS is enabled in VPC
```
Output: Running scope as unit run-8299.scope.
mount.nfs: Failed to resolve server xxxxxx.efs.eu-west-1.amazonaws.com: Name or service not known
mount.nfs: Operation already in progress
```

**Comment by brancz** [comment]
This doesn't seem like a problem with the prometheus operator, but rather with your cluster or volume provisioning/mounting. Can you mount these volumes with other Pods?

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
