### ISSUE TITLE
How to create storage provisioning(persistent storange) automatically 

### ISSUE THREAD

**Issue by vrathore18** [prometheus-operator/prometheus-operator#3215]
In my current setup, I created efs volumn then pv, pvc, sc manually and then using the created sc(ie. k8s-utils-efs-provisioner-sc) in value.yaml.

prometheus:
   prometheusSpec:
     storageSpec:
       volumeClaimTemplate:
         spec:
           storageClassName: k8s-utils-efs-provisioner-sc
           accessModes: ["ReadWriteOnce"]
           resources:
             requests:
               storage: 10Gi
But I think prometheus-operator can automatically do the provision for me as I am using AWS. Could you guy help me to do so. I am not able to figure out what could be the values in need to modify

**Comment by brancz** [comment]
The prometheus operator actually doesn't take care of any of this itself, it just makes use of dynamic volume provisioning that the StatefulSet does. You need to ensure that your storageclass supports dynamic volume provisioning.

**Comment by paulfantom** [comment]
Closing as the issue appears to be answered. If you need additional clarification, please reopen it.
