### ISSUE TITLE
Errors in log when watching multiple namespaces 

### ISSUE THREAD

**Issue by pgier** [prometheus-operator/prometheus-operator#3218]
While watching more than one namespace for any resource (Prometheuses, PrometheusRules, Alertmanagers, etc.)  The custom multiListerWatcher Watch() function will occasionally run into an error where the `resourceVersion` string does not match the expected format.  This produces a log error and invokes some internal error handling code.
```
E0304 20:47:27.926789       1 reflector.go:280] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:467: Failed to watch *v1.PrometheusRule: expected resource version to have 33 parts to match the number of ListerWatchers
```
This is due to an interaction between the kubernetes client-go cache code and the prometheus-operator multiListerWatcher.  The `multiListerWatcher` expects that the resourceVersion string passed to the `Watch()` function, which is used to determine the list of recent object updates, will always be the same one returned from the custom `List()` function.  However, this is not the case, as the client-go cache will update the `resourceVersion` directly from one of the event objects to ensure we're only watching the latest changes.

The error message doesn't currently cause any serious issues, as the built in error handling successfully restarts the watch after the error is detected, however it would be better if we didn't get these errors.  Also it seems that our modifications to the `resourceVersion` goes against recommendations in the kubernetes documentation.

> [Resource versions must be treated as opaque by clients and passed unmodified back to the server.](https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions)

We discussed this issue and some possible solutions with some of the team more familiar with the API server internals, and the recommended solution instead of using a custom `MultiNamespaceListerWatcher` we should use a separate `Informer` for each namespace.  This would avoid any modifications of the `resourceVersion` and would limit our interaction with the client_go libraries to the higher level and more commonly used API.

**Comment by lilic** [comment]
Still valid.

**Comment by lilic** [comment]
@s-urbaniak I believe we can close this now since the new listwatch was merged?

**Comment by simonpasquier** [comment]
Yeah, it should be fixed by https://github.com/prometheus-operator/prometheus-operator/pull/3440.

**Comment by KielChan** [comment]
I have encounter with same problem in kube-state-metrics.
