### ISSUE TITLE
timeout config field in AlertmanagerEndpoints

### ISSUE THREAD

**Issue by macroscopicentric** [prometheus-operator/prometheus-operator#3227]
**What is missing?**

A timeout field in the AlertmanagerEndpoints API endpoint.

Right now, you can only define limited parts of Prometheus' Alertmanager config (ie, [this block of config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alertmanager_config)) via prometheus-operator's PrometheusSpec, via the `alerting` or `additionalAlertManagerConfigs` fields. However, the AlertmanagerEndpoints endpoint `alerting` uses doesn't allow us to define a timeout for Prometheus for Alertmanager. And while you can add a timeout to `additionalAlertManagerConfigs`, this only appends a new section of config rather than merging with the pre-existing Alertmanager config for the primary Alertmanager pods. It would be great to add timeout as a field to the AlertmanagerEndpoints.

**Why do we need it?**

Right now Prometheus is extremely sensitive to a single Alertmanager pod going down, as [it blocks sending a batch of alerts for a default of 10 seconds](https://github.com/prometheus/prometheus/blob/f3c6d26781c4d099fad1fb2009dbc8d5f2ad4fcb/notifier/notifier.go#L519-L528) if it can't send the batch successfully to all Alertmanager pods. Under periods of heavy alerting stress, an Alertmanager pod being restarted can severely back up the Prometheus notification queue. It would be nice to also be able to decrease the timeout to help mitigate this when we have heavy load issues.

**Environment**

* Prometheus Operator version:

v0.35.1

**Comment by brancz** [comment]
I think this makes sense to be added. Do you want to contribute this?

**Comment by mickael-carl** [comment]
If @macroscopicentric doens't, I'd be happy to give it a try 🙂

**Comment by macroscopicentric** [comment]
I'd love to! I probably won't have the time this week but I'll look into the contributing guidelines and find something to use as a template for a PR next week.

**Comment by macroscopicentric** [comment]
Resolved by https://github.com/prometheus-operator/prometheus-operator/pull/3385
