### ISSUE TITLE
Docker images mirror on docker hub

### ISSUE THREAD

**Issue by jbfavre** [prometheus-operator/prometheus-operator#3234]
**What is missing?**
Prometheus-operator docker image should be made available on docker hub https://hub.docker.com/u/coreos and identified as official image.
This would allow image mirroring on Google Cloud Registry (mirroring only works from docker hub AFAIK)

**Why do we need it?**
Currently, we used quay.io as docker registry.
Since quay.io is currently experiencing an outage (https://status.quay.io/), we're looking to fallback on docker hub (from which we can mirror images on Google Cloud Registry).
We could not find any prometheus-operator docker image there.

**Environment**
GKE

**Comment by jbfavre** [comment]
To be exhustive, same applies to:
* `quay.io/coreos/configmap-reload`
* `quay.io/coreos/prometheus-config-reloader`
* `quay.io/coreos/kube-state-metrics`

Do I need to open separate issues ?

**Comment by granular-ryanbonham** [comment]
Agreed this would be a huge win. Quay.io has been very unreliable.

**Comment by carlwoodhouse** [comment]
and its down again ...

**Comment by blakewatters** [comment]
+1 This is ridiculous. How is there no mirror out there?

**Comment by lilic** [comment]
You can always build the image from the release and push to a registry :)

> How is there no mirror out there?

@blakewatters @jbfavre are you willing to work on adding the automation part to build the images? :)

**Comment by lilic** [comment]
cc @coreos/team-monitoring ^

**Comment by jbfavre** [comment]
@lilic Sorry for not answering sooner.
I'd be glad to help, but my understanding is that I'll need kind of "root" access to your CI setup/config.
Not sure you'll want that to ever happen :)
Anyway, again, I'll be happy to help

**Comment by paulfantom** [comment]
> I'd be glad to help, but my understanding is that I'll need kind of "root" access to your CI setup/config.

Most configuration is done in code contained in this repository. Admin access is necessary only for adding credentials.

**Comment by lilic** [comment]
We already have the PR for it, see the latest status there :) https://github.com/coreos/prometheus-operator/pull/3258

**Comment by paulfantom** [comment]
Closing as packages are now built and published to 2 registries and images are available at:
- Quay - [`quay.io`](https://quay.io/organization/prometheus-operator)
- GitHub Container Registry - [`ghcr.io`](https://github.com/orgs/prometheus-operator/packages?repo_name=prometheus-operator)
