### ISSUE TITLE
Problem to enable api in Prometheus

### ISSUE THREAD

**Issue by Stealthguard** [prometheus-operator/prometheus-operator#3238]
Hello!

I started currently playing around with prometheus.
I have not much experience with this kind of software. But I succeeded to install prometheus in the proxmox environment and connect it to grafana. 

Everything works fine and stable.

Till now, I could find many answers to my questions here in the forum. Thanks for that.

But now I have a little problem to enable the web api function and I can't find a solution for this problem.

I want to delete all measurement data. So I find the following manual.
https://www.shellhacks.com/prometheus-delete-time-series-metrics/

In the first step I have to activate the web api function.

When I type in the command "prometheus --web.enable-admin-api to the console" I get the attached output.

For me it looks like that he have a problem to start the server because the bind address is already in use.
So I stopped Prometheus with the kill term command and try it again.
But I still get the same error message.

Can somebody help?

Thanks a lot!

BR

Stealthguard

**Comment by lechen26** [comment]
as you wrote it on prometheus-operator i assume you are using prometheus.
if you do i guess you can add ' enableAdminAPI: true' on the prometheus spec.

**Comment by Stealthguard** [comment]
Thanks for your fast reply. Yes you are right im using prometheus. Sorry about that.
Do you mean that I only have to add the line to the prometheus.yml file?

**Comment by paulfantom** [comment]
Closing as the issue appears to be answered. If you need additional clarification, please reopen it.
