### ISSUE TITLE
Target shows up but alert shows firing

### ISSUE THREAD

**Issue by rborsaru** [prometheus-operator/prometheus-operator#3245]
Hi,

I have Installed prometheus-operator 8.13.7 and blackbox-exporter 3.5.0.
I have two blackbox targets that i will ping to check avaialability. 
The targets show as up if i look at status/targets/endpoints.
However the targets are down and they show firing if i look under Alerts. 
What do i do wrong?

Thank you!! 
RB

**Comment by brancz** [comment]
What alert is firing?

**Comment by rborsaru** [comment]
Here are the settings from my values file:
*****
additionalPrometheusRules:
  - name: myrule-file
    groups:
    - name: alert.rules
      rules:
      - alert: EndpointDown
        expr: probe_success == 0
        for: 10s
        labels:
          severity: "critical"
        annotations:
          summary: "Endpoint {{ $labels.instance }} down"

*****
additionalScrapeConfigs:
    - job_name: 'blackbox-exporter'
      metrics_path: /probe
      scrape_interval: 1m
      params:
        module: ['http_pingresult']
      static_configs:
      - targets:                             # targets to be tested by the blackbox exporter
        - https://mytesthost/app/ping
      relabel_configs:
        - source_labels: [__address__]     # set param 'target' to the original target
          target_label: __param_target
        - source_labels: [__param_target]  # set label 'instance' to it as well
          target_label: instance
        - target_label: __address__
          replacement: prometheus-blackbox-exporter:9115

*****
  config:
    global:
      resolve_timeout: 5m
      smtp_from: 'Monitoring Alert <alertmanager@mytesthost>'
      smtp_smarthost: exch-smtp2.mytesthost:25
      smtp_require_tls: false

    route:
      group_by: ['instance', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'oncall-team'
      routes:
      - match:
          alertname: EndpointDown
        receiver: 'oncall-team'
    receivers:
      - name: oncall-team
        email_configs:
          - to: 'radu.borsaru@mytesthost'
            send_resolved: true

**Comment by brancz** [comment]
I see. Ok this has to do with how the blackbox exporter works. The "UP" that you see in the targets page in Prometheus just refers to the ability to scrape the blackbox exporter successfully. The probe itself still fails though.

**Comment by paulfantom** [comment]
Closing as the issue appears to be answered. If you need additional clarification, please reopen it.

**Comment by DareLekan** [comment]
Good day. I am facing a similar issue here. I have alertmanager and blackbox configured. However, both shows different information for same endpoint. What am I doing wrong. Please help.
![prometheus config 1](https://user-images.githubusercontent.com/77133189/173334810-955e7bf2-b6fb-4188-9791-58abb8ad5a71.JPG)
![prometheus config 2](https://user-images.githubusercontent.com/77133189/173334815-d1143ada-71d1-491d-b873-0511069acebf.JPG)
![prometheus UI alertmanagere](https://user-images.githubusercontent.com/77133189/173334818-ffc1dbba-1051-4ef7-b457-7929d3b12740.JPG)
![prometheus UI alertmanagere22](https://user-images.githubusercontent.com/77133189/173334821-1c61c7cd-0634-49bd-8150-962fcbc5b830.JPG)
![prometheus UI alertmanagere33](https://user-images.githubusercontent.com/77133189/173334826-eabd92c9-1c83-4df0-9a25-67c82d3afa22.JPG)
![prometheus UI alertmanagere44](https://user-images.githubusercontent.com/77133189/173334829-ed7f4ccd-a587-4fc6-9929-46c7052b1051.JPG)
![prometheus UI blackbox](https://user-images.githubusercontent.com/77133189/173334832-ec2c9c11-f153-4a64-a132-06749efee0b0.JPG)


I have attached screenshot to help in explaining my pain point
