### ISSUE TITLE
Node address priority can lead to unreachable targets. 

### ISSUE THREAD

**Issue by alekc** [prometheus-operator/prometheus-operator#3247]
**What is missing?**
Currently prometheus operator uses following logic to determine ip address for a node (which will be used later on for target discovery like kubelet or node-exporter)

```go
func nodeAddress(node v1.Node) (string, map[v1.NodeAddressType][]string, error) {
	m := map[v1.NodeAddressType][]string{}
	for _, a := range node.Status.Addresses {
		m[a.Type] = append(m[a.Type], a.Address)
	}

	if addresses, ok := m[v1.NodeInternalIP]; ok {
		return addresses[0], m, nil
	}
	if addresses, ok := m[v1.NodeExternalIP]; ok {
		return addresses[0], m, nil
	}
	return "", m, fmt.Errorf("host address unknown")
}
```
In my environment I have some nodes which are behind the nat, so they have NodeInternalIP set to a private range, and public IP set as NodeExternalIP. 

Those internal ips are not routable from the rest of the cluster. So when they come up in the target list for kubeadm and node exporters, prometheus cannot scrape them because the target is not routable. 

Ideally we should support for a node to be able to give more priority for their external address (for example through annotation)

**Why do we need it?**

Without such fix it's impossible to scrape nodes which have unroutable internal ip (but they are part of the cluster and connected through flannel for example).

**Comment by brancz** [comment]
Would it make sense to rather have a flag that specifies the priority?

**Comment by alekc** [comment]
By a flag I suppose you mean the flag for prometheus which would change such priority globally?

That would work in my scenario (and to be honest in most of them), but if someone has some specific firewall rules they would probably still need to be able to change this behaviour on individual node base.

**Comment by brancz** [comment]
A flag on the prometheus operator that in order of specifying takes precendece for one over the other instead of the static code we have today. 

> That would work in my scenario (and to be honest in most of them), but if someone has some specific firewall rules they would probably still need to be able to change this behaviour on individual node base.

That makes me wonder, why are nodes not self descriptive about this, or maybe they are?

**Comment by alekc** [comment]
They are

I.e. this is my current cluster
```
k get nodes -o wide                                                                                                                                                                                  ─╯
NAME                   STATUS   ROLES    AGE   VERSION        INTERNAL-IP     EXTERNAL-IP      OS-IMAGE           KERNEL-VERSION     CONTAINER-RUNTIME
k3s-ingress-b17dd622   Ready    <none>   89m   v1.18.2+k3s1   10.69.148.xx    51.15.238.xx   Ubuntu 20.04 LTS   5.4.0-1011-kvm     containerd://1.3.3-k3s2
k3s-server-002         Ready    master   75m   v1.18.2+k3s1   10.64.8.xx      51.158.109.xx   Ubuntu
k3s-online-01          Ready    <none>   25h   v1.18.2+k3s1   62.210.202.52   <none>           Ubuntu 20.04 LTS   5.4.0-31-generic   containerd://1.3.3-k3s2
```

As you can see, I have `k3s-ingress-xx` and `k3s-server-xx` running with internal and external ip status, they are routable between them using internal ip and if prometheus was running on them it would not have any issue in scraping.

However, in my case, prometheus is running on `k3s-online-01` which is situated in another server farm and can reach 2 nodes from before only through their public ip, which brings us to a situation where first 2 servers are not scrapeable.

If we were to implement a flag, then everything would work because all of the targets are reachable by their public ip. 

In edge case scenario, however, lets assume that we have 4 servers, each of them having private (not routable from outside) and public ip. 2 of them running in one environment, and 2 others running in another one. If, by network policy,  servers in the same network environment cannot communicate between them by using external address, then global switch would not work, because with it we would be able to scrape targets in another server farm but not in the origin one. 

Does it make sense?

Potentially we might want to have both settings, 1 for global switch, and another for fine tuning (to avoid forcing people to annotate every single server).

**Comment by alekc** [comment]
Also, another valid point to consider is the annotation `flannel.alpha.coreos.com/public-ip-overwrite`

https://coreos.com/flannel/docs/latest/kubernetes.html
> flannel.alpha.coreos.com/public-ip-overwrite: Allows to overwrite the public IP of a node. Useful if the public IP can not determined from the node, e.G. because it is behind a NAT

If users explicitly set that annotation to the node, then there is a very good possibility that the node can only be reached by that ip.

**Comment by alekc** [comment]
I've tried to run a patched instance of prometheus operator, works fine as far as I can see, almost all relevant metrics are exposed in a correct way now. 

The only bit missing is node exporter, and I am bashing my head against the wall. By default, node exporter pods are using hostnetwork, and they are assigned node's ip. From relabling I cannot access host.status.NodeExternalIP so I cannot find a way for now to rewrite those targets.

**Comment by brancz** [comment]
It might actually be easier in your case to just write plain Prometheus configuration using the `node` role, and make use of it via the `additionalScrapeConfigs` feature. Note that you will need to grant Prometheus additional permissions to discover nodes in that case.

**Comment by alekc** [comment]
Mm I didn't need any additional permission to discover node (but I used the helm chart so it might be covered by it).
For any future googler, this is the syntax to achieve such relabling (note, in my case I used flannel annotation because it represents accurately the reachable ip for my instances, your use case might be different). 

```
- job_name: kubernetes-nodes
      metrics_path: /metrics
      scheme: http
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
        - source_labels: [__meta_kubernetes_node_annotation_flannel_alpha_coreos_com_public_ip]
          regex: (.*)
          target_label: __address__
          replacement: $1:9100
          action: replace
```

@brancz getting back to the original opening point, what do you think? should it be a global switch and/or specific node annotation?

**Comment by Adam-Jin** [comment]
I faced the same problem. At present, I have two inter-cloud vendors' nodes, and the intranet IP is not interoperable. At the same time, the nodes are all set up with externalip, but Prometheus uses the internal network IP to obtain metrics information, which of course cannot be obtained. The metrics-server has an option to specify the use of externalip access: --kubelet-preferred-address-types=ExternalIP, whether prometheus can also support such an option, which is very common in k3s scenarios

**Comment by simonpasquier** [comment]
@Adam-Jin what you're saying is that you'd be fine if the operator had a flag to specify which address it should pick for nodes?

**Comment by Adam-Jin** [comment]
> @Adam-Jin what you're saying is that you'd be fine if the operator had a flag to specify which address it should pick for nodes?

yes

**Comment by yelhouti** [comment]
In my case, I would prefer to use the ip/nodeName of the node-exporter pod, it avoids exposing the metrics publicly.
This would also be useful for kube-proxy as it would solve the need of exposing kube-proxy metrics on all interfaces.

**Comment by haanhvu** [comment]
Is this issue still valid now? I'm working on adding a flag to set node address priority. Will push soon.
