### ISSUE TITLE
Label selector for service is selecting not matching services

### ISSUE THREAD

**Issue by RickS-C137** [prometheus-operator/prometheus-operator#3252]
We have two clusters, one for production and one for development. The pods are deployed via Helm charts. One of the internally developed applications was updated so we rolled out the update on the clusters.
The Helm chart deployes, among other resources, a service and a corresponding servicemonitor. Before the upgrade the service had the label 'prometheus: caas' and the servicemonitor had the label selector 'prometheus: caas'. So far so good and everything was working fine.
The new version changes the label to 'prometheus: caas-rest-api' and the label selector in the servicemonitor also to 'prometheus: caas-rest-api'. 
And here comes the weird thing:

On the development cluster:
servicemonitor - labelselector: prometheus: caas-rest-api
service - label: prometheus: caas-rest-api
-> Prometheus is dropping the labels

servicemonitor - labelselector: prometheus: caas-rest-api
service - label: prometheus: caas
-> Prometheus is scraping the labels

On our production clusters the scraping is working as expected.
Both clusters are running Kubernetes 1.11.6 and Prometheus operator Helm chart v5.10.4.

I already tried helm delete --purge and deleting the namespace afterwards. We have several deployment with this Helm chart, all are acting the same. 
We are not able to explain this behavior. Does anybody have an idea what the problem could be?

**Comment by brancz** [comment]
> Both clusters are running Kubernetes 1.11.6 and Prometheus operator Helm chart v5.10.4.

That's very old, it's hard to tell if there was something up with those versions ~2 years ago. Could you share the two generated configurations? You can find those on the `/targets` page of Prometheus.

**Comment by RickS-C137** [comment]
The configuration on the /targets page for the non-working one is empty:
![image](https://user-images.githubusercontent.com/38781160/83486057-ac46bf00-a4a8-11ea-9c23-d83644f08db3.png)
And here's like a working one looks like:
![image](https://user-images.githubusercontent.com/38781160/83486315-3c850400-a4a9-11ea-955e-54e396c178d0.png)

**Comment by brancz** [comment]
And the generated config section shown in the `/config` page?

**Comment by RickS-C137** [comment]
Looks normal to me:
```- job_name: ecs-caas/caas/0
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /_metrics
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - ecs-caas
  basic_auth:
    username: metrics
    password: <secret>
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_prometheus]
    separator: ;
    regex: caas
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: http
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Node;(.*)
    target_label: node
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Pod;(.*)
    target_label: pod
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: http
    action: replace```

**Comment by brancz** [comment]
Sorry for all the questions, finally could you share the `Service` that you are expecting to be picked up by this?

**Comment by RickS-C137** [comment]
Yeah, that's the weird thing. When I set it to 'prometheus: caas-rest-api' it works! And when I set it to ´prometheus: caas' it won't. This is the cause for this thread. It makes no sense to me.

**Comment by brancz** [comment]
I think I'm maybe missing something, but that's exactly how label selectors work.

**Comment by RickS-C137** [comment]
Ok, I guess my descriptions was miss leading. I'm trying it like this:

Working:
label selector in servicemonitor: `prometheus: caas`
label on the service: `prometheus: caas-rest-api`

NOT working:
label selector in servicemonitor: `prometheus: caas-rest-api`
label on the service: `prometheus: caas-rest-api`

So the combination that should NOT work is working and vise versa.

**Comment by brancz** [comment]
hmm ... it does seem very weird, would it be possible to share the whole manifests? (including the Prometheus manifest)

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.
