### ISSUE TITLE
how to add a customize metric relabelling  for all Servicemonitor and PodMonitor

### ISSUE THREAD

**Issue by sunhubs** [prometheus-operator/prometheus-operator#3255]
**What did you do?**
I want to add customize metric relabelling for all the scrape jobs generated by servicemoitor and podmonitor. For example i want to relable [__meta_kubernetes_pod_label_app] to [app].
currently, i have to set for all the ServiceMonitor and PodMonitor yaml file to add:
`
relabelings:

    - sourceLabels: [__meta_kubernetes_pod_label_app]

      targetLabel: app
`
i think it is a bit annoying
**Did you expect to see some different?**
i just want to have a way to reduce this effort, for example a configuration to let the auto generated scrape_config contains the custom relabeling for all ServiceMonitor and PodMonitor as those default ones.
**Environment**
helm:v3.2.1
prometheus:v2.16.0

* Prometheus Operator version:
v0.38.1
    

* Kubernetes version information:
client 1.14.7
server 1.16.8
    

* Kubernetes cluster kind:
   AWS eks
    insert how you created your cluster: kops, bootkube, etc.

* Manifests:
No more need
```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:
No need logs
```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
No

**Comment by brancz** [comment]
This doesn’t exist but I think it’s an interesting feature to consider, especially when consistent practices across an organization exist

**Comment by sunhubs** [comment]
Thanks @brancz , but may I know, when will this be released?

**Comment by brancz** [comment]
Whenever someone implements it :)
