### ISSUE TITLE
Remove maxRetries option for remoteWrite

### ISSUE THREAD

**Issue by TakumaNakagame** [prometheus-operator/prometheus-operator#3256]
**What happened?**

Removes the maxRetries option in remoteWrite.

`max_retries` option in `remote_write` has been removed in v2.11.0.
https://github.com/prometheus/prometheus/pull/5649

However, this option remains in the PrometheusOperator. ( `.spec.remoteWrite.QueueConfig.maxRetries` )
https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#queueconfig.

This option does not work and prints an error.

```
level=error ts=2020-05-29T11:59:56.705Z caller=main.go:758 err="error loading config from \cTs"/etc/prometheus/config_out/prometheus.env.yaml\cTs": couldn't load configuration (--config.file=\cTs"/etc/prometheus/config_out/prometheus.env.yaml\cTs"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: unmarshal errors:\cTs line 555: field max_retries not found in type config.QueueConfig line 566: field max_retries not found in type config.QueueConfig"
```

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `0.39.0-debian-10-r8` (using Helm for [bitnami/prometheus-operator](https://github.com/bitnami/charts/tree/master/bitnami/prometheus-operator))
    

* Kubernetes version information:

    `v1.17.5`
    

* Kubernetes cluster kind:

    `kubespray:v2.13.0`

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
Yeah, we need to just exclude the field for versions >=2.11.0.

**Comment by raptorsun** [comment]
I'm going to remove this option :)
