### ISSUE TITLE
feat: Move api & client to a separate module

### ISSUE THREAD

**Issue by tamalsaha** [prometheus-operator/prometheus-operator#3269]
**What is missing?**
We currently programmatically create ServiceMonitor etc. We would like to be able to just depend on the api types and generated client/lister/informer. One option will be to release separate go modules from this repo or create separate repo for the api and generate client code.

**Why do we need it?**
This will make the go.mod simpler. Go modules don't transitively pass repalces.  Currently I have to add a `k8s.io/client-go => k8s.io/client-go v0.18.2` to every project that transitively depends on this repo. Having a separate module for api & clients will allow supporting a go.mod without any replaces.

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
Can you be more specific about which packages you'd like to extract into a separate Go module?

**Comment by bwplotka** [comment]
Also, be aware that having multiple of repos will be extremely hard to maintain. Something we touched here: https://github.com/grpc-ecosystem/go-grpc-middleware/issues/275 

Looks like some new pattern arises with nested modules + [modularise](https://github.com/modularise/modularise)

**Comment by tamalsaha** [comment]
- **api**: https://github.com/coreos/prometheus-operator/tree/master/pkg/apis
- **client**: https://github.com/coreos/prometheus-operator/tree/master/pkg/client

**Comment by tamalsaha** [comment]
Recently https://github.com/cloudevents/sdk-go did a single git repo but multiple Go module split. I think that works for external users.
