### ISSUE TITLE
Permanent, meaningful, discoverable home for the project

### ISSUE THREAD

**Issue by brancz** [prometheus-operator/prometheus-operator#3273]
There have been various discussions and asks to move the prometheus-operator into a more permanent, meaningful and discoverable home. Projects in the coreos org, primarily revolve around fedora-coreos, and that clashes with discoverablility a lot. It also incorrectly reflects the reality that this project is not entirely maintained by "coreos", but there are multiple non-Red Hat maintainers present.

Somewhat related, there are asks for homes for related projects, such as but not limited to:

* separate api and client repositories (https://github.com/coreos/prometheus-operator/issues/3269, https://github.com/coreos/prometheus-operator/issues/3097)
* a repository for a helm chart (https://github.com/coreos/prometheus-operator/issues/3169)
* a home for [kube-prometheus](https://github.com/coreos/kube-prometheus) (which currently suffers from the same symptoms as the prometheus-operator project

In a separate org it would be possible to govern the project in a way that doesn't make it seem to be a closed set of maintainers, but rather the community run project that it is.

As a side note, and as we all know a poor metric, but with >4.3k stars the project's popularity has outgrown our wildest dreams and just for that deserves its own home.

@lilic @s-urbaniak @paulfantom @pgier @simonpasquier @metalmatze @ant31 @gianrubio @gouthamve @mgoodness @vsliouniaev @coreos/team-monitoring

**Comment by lilic** [comment]
+1 (💯 ) from me

**Comment by brancz** [comment]
I meant to add it, but my proposal would be to move it to the [prometheus-operator](https://github.com/prometheus-operator) org, that I have reserved.

**Comment by paulfantom** [comment]
From my side we have 3 possible places where the project can go:

#### *prometheus-community* org

pros:
- discoverability
- neutral space
- established community

cons:
- community goal is to offer a neutral place for projects that are too small to be known by themselves or that are abandoned by the original author
- possible problems with creating additional repositories

#### organization dedicated to observability

pros:
- we can have multiple repositories with different maintainers for each
- better discoverability than now
- neutral ground (comparing to current situation)

cons:
- community needs to be re-established as right now it is dispersed
- generic organization can impact discoverability as such org might become a place for too many repositories


#### organization dedicated to prometheus-operator

pros:
- same as above
- slightly increases discoverability by focusing only on prometheus-operator

cons:
- same as above, but without the problem of having too many repositories



Looking at those options I would prefer if we moved to **prometheus-operator** organization as suggested by @brancz

**Comment by s-urbaniak** [comment]
+1 from me for moving to prometheus-operator org

**Comment by simonpasquier** [comment]
Same for me, I think that the **prometheus-operator** organization is the best choice.

**Comment by metalmatze** [comment]
I'm in favour of _organization dedicated to observability_ so that we don't spread our 15 projects across 10 different orgs, but wouldn't block having an prometheus-operator org, if that's the overall consensus.

**Comment by brancz** [comment]
I just realized that there were discussions in various directions in the past, and I want to make sure we're explicit in these, I personally think we should put the prometheus-operator in the prometheus-operator org, and kube-prometheus into it's own (maybe kube-observability?). That way we can emphasize the separation of the projects much like we always desired (RE https://github.com/coreos/prometheus-operator/pull/3333#issuecomment-662294842), while also emphasizing on the scope of each project individually.

**Comment by paulfantom** [comment]
>  I personally think we should put the prometheus-operator in the prometheus-operator org, and kube-prometheus into it's own (maybe kube-observability?)

I don't agree, separation on repository-level is fine, but those two projects are connected to each other and IMHO should belong to the same org.

Additionally in such case where do, we want to put helm charts and handle issues about it?

**Comment by brancz** [comment]
> Additionally in such case where do, we want to put helm charts and handle issues about it?

In the respective org. I think that would actually be good for people to understand the separation, I don't feel too strongly about it though.

**Comment by paulfantom** [comment]
Such an approach immensely decreases project discoverability and clouds how projects are connected to each other.

One more thing to consider is how issues are created and what features GitHub offers here. We currently have quite a lot of issues which are in respect to helm charts or to kube-prometheus and we probably will always have such reports in prometheus-operator repository. With repositories in one org, such issues can be easily moved to respective repository providing better developer experience. With multiple orgs it is not possible and people need to recreate their issues in other repos.

If we want it or not, prometheus-operator and kube-prometheus are strongly connected to each other even when kube-prometheus has different scope.

**Comment by brancz** [comment]
> how projects are connected to each other.

Well the intention is precisely to emphasize the difference and independence of the projects. :)

**Comment by paulfantom** [comment]
They are already independent as they live in different repositories. I think separation on a higher level (organization) would impact developer workflows without any additional benefits.

**Comment by brancz** [comment]
There's no reason why it would be final, so I'm happy with keeping them together for now, and should there be more voices in the future then we can still change the direction.

**Comment by paulfantom** [comment]
After migration, we should publish images into 2 repositories on quay (old one and new one) for 1 or 2 release cycles.

A good example of pushing to 2 repositories is in https://github.com/coreos/prometheus-operator/pull/3258

**Comment by bwplotka** [comment]
Creating many images is not a problem indeed, we do that on Thanos as well: https://github.com/thanos-io/thanos/blob/master/.circleci/config.yml#L79

In terms of org, I think I am with @metalmatze and would vote for `organization dedicated to observability` We can have totally different projects there with different maintainers and different governance. Then even if it's worse for discoverability now, it might be better once we build some reputation there.

> I don't agree, separation on repository-level is fine, but those two projects are connected to each other and IMHO should belong to the same org. (re kube-prom and prom-op)

This also makes it easier to reason about if we would have a single org for both of them.

Anyway, as Matthias, I happy with prometheus-op org as well, don't want to block.

**Comment by paulfantom** [comment]
Closing as this is done after https://github.com/prometheus-operator/prometheus-operator/pull/3384 and https://github.com/prometheus-operator/kube-prometheus/pull/630
