### ISSUE TITLE
Support --prometheus.ready_timeout flag for thanos-sidecar

### ISSUE THREAD

**Issue by musabmasood** [prometheus-operator/prometheus-operator#3275]
**What is missing?**

The `--prometheus.ready_timeout` flag for thanos-sidecar

**Why do we need it?**

The sidecar crashes if prometheus is not ready in 10 minutes, so we want to increase it as our prometheus is fairly big

**Prometheus Operator version:**

`8.14.0`

**Comment by brancz** [comment]
Happy to accept this if you want to create a PR :)

**Comment by PhilipGough** [comment]
I'll take a look a this one.
