### ISSUE TITLE
Parameterize terminationGracePeriod in operator

### ISSUE THREAD

**Issue by mchandrasekar90** [prometheus-operator/prometheus-operator#3278]
Ability to customize this value would help in running in managed kubernetes clusters where this is not allowed. It could be upto the individual to accept the risk and tune it

https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L295

**Comment by brancz** [comment]
I’ve never heard this being not allowed to be set. Do you have docs on which provider does this?

**Comment by paulfantom** [comment]
Closing in favor of https://github.com/prometheus-operator/prometheus-operator/issues/3433
