### ISSUE TITLE
Merges in release-0.35 are failing

### ISSUE THREAD

**Issue by s-urbaniak** [prometheus-operator/prometheus-operator#3282]
**What happened?**

After merging into `release-0.35` CI fails with:

https://travis-ci.org/github/coreos/prometheus-operator/jobs/698411430

```
The push refers to repository [quay.io/coreos/prometheus-operator-lint-dev]
c1f82f3bfe8b: Preparing
7a151fe67625: Preparing
1da8e4c8d307: Preparing
unauthorized: access to the requested resource is not authorized
Removing login credentials for quay.io
The command "./scripts/travis-push-docker-image.sh" exited with 1.
cache.2
store build cache
```

**Did you expect to see something different?**

No failure

**How to reproduce it (as minimally and precisely as possible)**:

See CI

**Environment**

CI

* Prometheus Operator version:

https://github.com/coreos/prometheus-operator/commit/8b9d024467383d84b55d7e5e0d4f7a33eb5007b3

* Kubernetes version information:

N/A

* Kubernetes cluster kind:

N/A

* Manifests:

N/A

* Prometheus Operator Logs:

N/A

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
It is failing due to lack of `*-dev` repos and our script works correctly only on  `master` due to: https://github.com/coreos/prometheus-operator/blob/master/scripts/travis-push-docker-image.sh#L20

**Comment by paulfantom** [comment]
It seems we have 2 issues here:
1) We wanted to push to repository to which we don't have credentials (or some other quay issue)
2) On release branches we are pushing images to repos with `-dev` suffix (unless we do a patch release). Which means our patches are not easily usable by others.

I think solving latter also solves the former so I would like us to figure out how do we proceed with patching already released versions. Should we do a patch release every time we patch something in `release-X.Y` branch or maybe we should add another container tag which would be mutable and tied to branch - something like `release-X.Y`?

@coreos/team-monitoring

**Comment by brancz** [comment]
We should do a patch release every time we patch something in `release-X.Y`.

**Comment by paulfantom** [comment]
Deprecated :)
