### ISSUE TITLE
docs: CRD Definitions (API Documentation)

### ISSUE THREAD

**Issue by ghostsquad** [prometheus-operator/prometheus-operator#3292]
Is there documentation for the CRD's such as the PrometheusRule?
I can't see to find a definitive guide to what fields are available, valid values, and behaviors.

In the readme (https://github.com/coreos/prometheus-operator?ts=4) it says:
> To learn more about the CRDs introduced by the Prometheus Operator have a look at the design doc.

The design doc does not describe the CRD's though
https://github.com/coreos/prometheus-operator/blob/master/Documentation/design.md?ts=4

---

I suspect there are a couple possible outcomes:

1. Documentation does exist, and so the action for this issue would be to update relevant README's to provide links

or

2. Documentation does not exist, so the action would be to create them and update relevant README's to provide links

**Comment by brancz** [comment]
Here :) https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md

What do you think we could have done differently to make this easier to find?

**Comment by brancz** [comment]
> Documentation does exist, and so the action for this issue would be to update relevant README's to provide links

If you have any suggestion, please contribute them! :)
