### ISSUE TITLE
Port important fixes or features back to v0.38.* for K8s prior to v1.16

### ISSUE THREAD

**Issue by benjaminhuo** [prometheus-operator/prometheus-operator#3293]
Does it make sense to port some important fixes or features without changing CRDs back to v0.38+ and make a new release to support k8s < 1.16 ?

Important PRs  without changing CRDs I can find are as following:

- https://github.com/coreos/prometheus-operator/pull/3126 fcb4b9ce85772514555f284eef9761f1650d4bc9
- https://github.com/coreos/prometheus-operator/pull/3179 3289cd23b4fe1806ad29f0bfa0961bc3a5f30190
- https://github.com/coreos/prometheus-operator/pull/3182 8d2152cd2561f0b3d4b7784d35aaa2f8c7962632
- https://github.com/coreos/prometheus-operator/pull/3233 35479618df72ebd997159fc3b08190e00f705181
- https://github.com/coreos/prometheus-operator/pull/3286 1ae8026b1b405c465befcdab3be6a80db85af53d

To include the above PRs, below commits have to be merged first in order:
- 5027e3cf3707ee357c966d1f943f5669efc97203
- e182cad921957165d39c473f4a4b679036767105

Thanks
Ben

**Comment by benjaminhuo** [comment]
@lilic what do you think?

**Comment by brancz** [comment]
I think things that actually fall into the bug category are definitely fine to backport. I don't think all of these fall into that category, but those that do, I think we're more than happy to accept PRs for backports! :)

**Comment by lilic** [comment]
Yes, anything that is a bug can and should be backported into the patch release, feel free to create those PRs, thanks! For feature work, we tend to not backport those.

**Comment by benjaminhuo** [comment]
In the PRs or commits I mentioned, only one PR is not a bug which is 
- https://github.com/coreos/prometheus-operator/pull/3286 1ae8026b1b405c465befcdab3be6a80db85af53d

As for PR https://github.com/coreos/prometheus-operator/pull/3182 8d2152cd2561f0b3d4b7784d35aaa2f8c7962632 , it's actually a bug although it's marked as enhancement is release notes.

I'll create a PR to release-0.38.2 branch

Ben

**Comment by benjaminhuo** [comment]
@lilic @brancz , I've created a branch release-0.38.2 in my own repo https://github.com/benjaminhuo/prometheus-operator/tree/release-0.38.2 , which upstream release branch should I submit a PR for this?

Thanks
Ben

**Comment by lilic** [comment]
Ideally we want to backport to all the releases so 0.38 and 0.39. So creating a PR against https://github.com/coreos/prometheus-operator/tree/release-0.39 and https://github.com/coreos/prometheus-operator/tree/release-0.38. Thanks!

**Comment by benjaminhuo** [comment]
@lilic I've created PR #3300 for release-0.38 branch , let me know if I should bump the version and then regenerate as well

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think this issue is still valid, please reopen it.
