### ISSUE TITLE
Add objectStorageConfigFile for ThanosSpec

### ISSUE THREAD

**Issue by ngc104** [prometheus-operator/prometheus-operator#3296]
**What is missing?**

In`ThanosSpec` there is an option `objectStorageConfig` that will add a line `--objstore.config=<content>` in the generated thanos-sidecar container.

However there is not option `objectStorageConfigFile` that will add a line `--objstore.config-file=<file-path>` in the generated thanos-sidecar container.

**Why do we need it?**

When you are using vault-injector, your pod comes with a *magic* initcontainer that will get the secret storage information from Vault and write them in a file named `/vault/secrets/xxx`. This is a solution more secure than common Kubernetes secrets that you decode easly with `base64 -d`.

The need is to be able to specify `objectStorageConfigFile` to Prometheus-Operator instead of `objectStorageConfig` and to have the thanos sidecar use the file generated by vault-injector.

More info on vault-injector and *magic* here : https://www.hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar/

**Environment**

* Prometheus Operator version:

Whatever version... I'm using 0.38.1 from prometheus-operator helm chart but there is no problem to add this feature in latest version of prometheus-operator.

**Anything else we need to know?**:

As soon as I can specify `objectStorageConfigFile` in the Prometheus-Operator configuration and get the `--objstore.config-file=<file-path>` this is OK.

Vault-injector is only a use-case. You can forget about it for the implementation of the option `objectStorageConfigFile`.

**Comment by brancz** [comment]
I think this is reasonable. If we can manage to implement something that doesn't confuse users too much, then I'd be happy with this, as I agree that container identity "attestation based" secret obtaining makes a lot of sense.

**Comment by ngc104** [comment]
Hello
Any news on this feature?

**Comment by piellick** [comment]
Hi everyone, there is a workaround ? Same problem for me.

**Comment by brancz** [comment]
I don't think anyone has taken this up yet, if someone wants to propose something that would be appreciated! :)

**Comment by paulfantom** [comment]
This is done in #3668
