### ISSUE TITLE
Monitor kublet

### ISSUE THREAD

**Issue by JennyMet** [prometheus-operator/prometheus-operator#3320]
Hi,

Not sure if it's support or bug...
**What did you do?**
We are using Prometheus operator (as-is) successfully for several of month, today we find the kublet was down for 20 min,
However we didnt get any alerts, doest the promtheus operator monitor it by default? if yes what could be the reason that we didnt get any alerts? for other components we are getting alerts in case of an issue

**Did you expect to see some different?**

**Environment**
k8s

* Prometheus Operator version:
0.39

* Kubernetes version information:
1.17
    `kubectl version`

```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
> However we didnt get any alerts, doest the promtheus operator monitor it by default?

That depends on your installation method and if ServiceMonitor responsible for kubelet was installed. 

You need to check 2 things (both in prometheus UI):
1. If kubelet target is scraped
2. If you have alerts for kubelet and/or generic `TargetDown` alert.

**Comment by JennyMet** [comment]
@paulfantom - Thanks, will check it today. in case we dont have it, how should I add it?  it will be great if you could provide reference / example ?

**Comment by paulfantom** [comment]
You can take a look at kube-prometheus project and [example manifests](https://github.com/coreos/kube-prometheus/tree/master/manifests), especially [one for kubelet](https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-serviceMonitorKubelet.yaml).

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
