### ISSUE TITLE
prometheus target showing down with 403 error

### ISSUE THREAD

**Issue by kamit78** [prometheus-operator/prometheus-operator#3321]
**What happened?**

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by kamit78** [comment]
We have configured Prometheus to monitor forgeRock application but one application target is down with 403 error . **When I  tried to curl/wget the same target url from withing prometheus pod using same credentials , it is working fine and scrap data from metrics endpoint ** We are using custom service monitor that connect with application service to get the data. I'm attaching screenshot of error for more information

<img width="932" alt="openig_error_prometheus_targe" src="https://user-images.githubusercontent.com/8327067/86793626-45a95800-c089-11ea-85b5-023c66964a8b.png">

It looks like a bug in prometheus-operator monitoring bundle

**Environment**

- Prometheus Operator version:  v0.32.0
 
- Insert image tag or Git SHA here
 
- Kubernetes version information:  1.14
 
- kubectl version: Major:"1", Minor:"16", GitVersion:"v1.16.0"

- Kubernetes cluster kind:  Amazon EKS

**Comment by brancz** [comment]
Looks like the endpoint may be expecting some sort of credentials that are authorized to access the endpoint. I would suggest you to first try and `curl` the endpoint and see if you can make that work. This doesn't seem like a problem with the prometheus operator, but just missing correct credentials configuration.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
