### ISSUE TITLE
Alert Configuration in Prometheus Operator Helm chart

### ISSUE THREAD

**Issue by AlehB** [prometheus-operator/prometheus-operator#3324]
Hello everyone,

We have installed Prometheus Operator Helm chart into our Kubernetes cluster and successfully able to get different information about the pods, nodes and etc in the Grafana dashboard.

![image](https://user-images.githubusercontent.com/2253605/87004777-aa1e0180-c1c6-11ea-8106-4eeef603bf61.png)

Now we would like to configure some basic alert notifications and send them to Telegram

Could you please help us with with the following questions

1. What exactly should we do to create an alert in Prometheus Operator Helm chart installation. For example "if the instance1 has Memory Usage > 70% - send an alert"

2. How can we send alert notifications to Telegram channel?

3. How can we monitor main URLs with Prometheus Operator?

Thank you in advance

**Comment by paulfantom** [comment]
We do not maintain prometheus-operator helm chart nor use it.

Generally speaking:
1 and 2: To create alert you need to add PrometehusRule object and configure alertmanager Secret as explained in https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md
3: You need blackbox_exporter and you can use newly added [Probe object](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#probe)

**Comment by paulfantom** [comment]
All helm-related issues should be targetted towards https://github.com/prometheus-community/helm-charts as this is were the development of those charts take place. Please open a new issue in the said repository if you feel this problem is still present.
