### ISSUE TITLE
Log format not standardized

### ISSUE THREAD

**Issue by wiegandf** [prometheus-operator/prometheus-operator#3326]
**What happened?**
We have set log format to json and log contains multiple log formats.
```
{"caller":"operator.go:427","component":"alertmanageroperator","key":"xyz","level":"info","msg":"sync alertmanager","ts":"2020-07-09T11:44:58.298690389Z"}
E0709 11:45:28.573097       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:311: Failed to list *v1.ThanosRuler: the server could not find the requested resource (get thanosrulers.monitoring.coreos.com)
``` 

**Did you expect to see something different?**
I expected to see one standardized log format.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `v0.40.0`
    

* Kubernetes version information:

    `v1.17.6`
    

* Manifests:

```
prometheusOperator.logFormat: json
```

* Prometheus Operator Logs:

see above

**Anything else we need to know?**:

**Comment by brancz** [comment]
We unfortunately cannot influence this, this is because Kubernetes libraries log a lot and don't let us configure the log format.

**Comment by lilic** [comment]
@wiegandf as Frederic mentioned this is a kubernetes problem, so maybe would be good to open issue to allow to configure the log format, if one does not exist. Until then I think documenting this would be good, do you mind opening PR to add to docs to avoid confusion for other people, thanks!

**Comment by vsliouniaev** [comment]
Prometheus solved this problem, so I think it should be possible to log k8s internal output here as well. Here is some output from a prometheus e.g.:
```
{"caller":"klog.go:86","component":"k8s_client_runtime","func":"Warningf","level":"warn","msg":"/app/discovery/kubernetes/kubernetes.go:361: watch of *v1.Endpoints ended with: an error on the server (\"unable to decode an event from the watch stream: context canceled\") has prevented the request from succeeding","ts":"2020-07-10T07:54:28.286Z"}
```

AFAIK it's done by switching klog dependency for klog-gokit [simonpasquier/klog-gokit](https://github.com/simonpasquier/klog-gokit)

**Comment by brancz** [comment]
Yeah this is possible. @vsliouniaev you want to give this a shot? I was actually just talking to @lilic about something vaguely related .. being we have 2 flags to set the log level of each of these it might be useful to unify these so people only have to set the gokit logger and then translate the log levels to the klog levels, for example

all = 10
debug = 8
info = 4
err =3

**Comment by vsliouniaev** [comment]
It will probably be some time before I can get to this, so anyone who would like to do it - feel free

**Comment by nrchakradhar** [comment]
Can I give this a shot?

**Comment by simonpasquier** [comment]
@nrchakradhar you're welcome!
