### ISSUE TITLE
Add new metric when prometheus is stuck on "creating config failed"

### ISSUE THREAD

**Issue by drazul** [prometheus-operator/prometheus-operator#3327]
**What is missing?**

There is no metric to alert when prometheus fail to create the new configuration before reload it.

**Context:**
We work on a shared kubernetes cluster with different teams and someone deleted, by mistake, one secret used to get the api credentials used by the service monitor. And because of that prometheus started to throw this error:

```
E0709 12:11:36.444821       1 operator.go:994] Sync "prometheus-operator" failed: creating config failed: could not generate basicAuth for servicemonitor my-app. secret username key "user" in secret "basic-auth" not found
```

And because of this error all the new service monitor we configure are not added to the configuration (maybe a related bug?)

**Why do we need it?**

We need to know when the create configuration procedure is failing to fix it as soon we notice to improve our reliability.

**Environment**

* Prometheus Operator version:

    `v0.38.1`

**Comment by brancz** [comment]
I think in this case we should just skip the ServiceMonitor (and maybe write a status into the ServiceMonitor, that this has happened)

**Comment by simonpasquier** [comment]
I'll work on this one.

**Comment by simonpasquier** [comment]
#3421 should add a `prometheus_operator_syncs` metric (name to be reviewed) that will track the number of Prometheus, Alertmanager and Thanos objects per sync status (ok/failed).
