### ISSUE TITLE
Incorrect ServiceMonitor blocks prometheus deployment

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#3329]
**What happened?**

During re-deploying a cluster I did following:

1. Created Prometheus object with:
```
serviceMonitorNamespaceSelector: {}
serviceMonitorSelector: {}
```
2. Added ServiceMonitor which references non-existing Secret via `bearerTokenSecret`
3. Prometheus pod wasn't created and prometheus-operator logs suggested incorrect ServiceMonitor
4. Waited for about an hour
5. Added a Secret to satisfy SM from 2.
6. prometheus pod came up

**Did you expect to see something different?**

Prometheus should start and show 0 targets and not be blocked by incorrect ServiceMonitor. 

**How to reproduce it (as minimally and precisely as possible)**:

0. Start prometheus-operator
1. Create Prometheus object
2. Create ServiceMonitor referencing not existing Secret via `bearerTokenSecret`
3. Observe :)

**Environment**

* Prometheus Operator version:

    `v0.40.0`
    

* Kubernetes version information:

    `1.18.4`
    

* Kubernetes cluster kind:

    k3s

* Manifests:

1. SealedSecret: https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/homeassistant/08_servicemonitor.yaml
2. Prometheus CR: https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/prometheus/05_prometheus.yaml
3. Prometheus-operator deployment: https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/prometheus-operator/04_deployment.yaml

* Prometheus Operator Logs:

Pods were rotated before I could gather logs.

**Anything else we need to know?**:

**Comment by brancz** [comment]
Did the Pod start and Prometheus failed to start, or the Pods didn't even start because the Secret couldn't be mounted?

**Comment by paulfantom** [comment]
Pods didn't start. After Secret was created pods were started.

**Comment by brancz** [comment]
Secrets and ConfigMaps are transferred into the namespace the Prometheus object is in, so my suggestion would be to always create the "transferred" one, but only fill them if secret/configmap is available and key exists in the referenced secret/configmap
