### ISSUE TITLE
HA prometheus with common PV and PVC

### ISSUE THREAD

**Issue by varunsrinath** [prometheus-operator/prometheus-operator#3331]
Hi Team,

Is it possible to have 2 Prometheus instances refer to same PVC? will that cause any DB conflicts or is this even possible theoretically?

I am trying to look for a setup where in case one Prometheus goes down while patching the other one has the data.  When we read  the data back i want to see if we can get data for all the timestamps without any missing data due to the patch.

**Comment by brancz** [comment]
Prometheus is specifically designed to require entirely distinct PVs, they must not be shared, as Prometheus relies on this for high availability purposes. Most people just load balance to all HA replicas, but my recommendation to make sure you have no gaps in data is to use the [thanos](https://github.com/thanos-io/thanos) [query](https://thanos.io/components/query.md/) component, which at query time will merge the data from multiple Prometheus servers.

**Comment by varunsrinath** [comment]
Right that’s what I was thinking too as indexing and compression of data
from different Prometheus would be different and will cause conflict.

The issue now I am facing is now is how to bind the 2 PVC created by the
operator with my 2 PVs.

I tried removing the volume name and use the label selector to see if they
would map. But no luck. Do you have any sample config that shows to set up
2 PV? And a sample of the claim template.

Thanks,
Varun

**Comment by brancz** [comment]
You will have to use a setup with 2 distinct PVs.

**Comment by varunsrinath** [comment]
Can you please share an example on how to do it?

**Comment by varunsrinath** [comment]
Should I be creating my PVCs manually without using claim template by
following certain naming convention?

**Comment by brancz** [comment]
Do create the PVCs through the template, but make sure there are either 2 PVs matching the requirements or that there is dynamic volume provisioning available.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
