### ISSUE TITLE
Only Manage Prometheus Server Configuration

### ISSUE THREAD

**Issue by veerabhadra** [prometheus-operator/prometheus-operator#3357]
**What did you do?**
In our environment we would like to use Prometheus Operator for managing configuration of Prometheus Server. However we would like to life cycle Prometheus Server not using Prometheus Operator. Can we deploy service monitors and not Prometheus Resources and achieve this functionality ?

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
These concerns are very intertwined, which is why this is not possible. Reloads, templating, etc. are all very much coupled and they need to be to be able to offer the experience here. Is there something specific that you can't do that you want to do?

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
