### ISSUE TITLE
Cleanup OWNERS file.

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#3367]
Since we now have a release shepherd, we should clean up OWNERS file to ease the process of choosing the next shepherd.

In addition, we need to come up with a governance policy to allow better community-based maintenance of the codebase. One possible solution would be to remove OWNERS file and replace it with GitHub feature of [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) or model maintainers document after [counterpart from thanos-io/thanos](https://github.com/thanos-io/thanos/blob/master/MAINTAINERS.md).

/cc @coreos/team-monitoring

**Comment by brancz** [comment]
I think the combination of the two would be a good idea.

**Comment by paulfantom** [comment]
Done with https://github.com/prometheus-operator/prometheus-operator/pull/3407 and https://github.com/prometheus-operator/prometheus-operator/pull/3398
