### ISSUE TITLE
prometheus operator pod 0.37 is reporting error "Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden"

### ISSUE THREAD

**Issue by nakfour** [prometheus-operator/prometheus-operator#3372]
**What happened?**
We upgraded our operator to 0.37 on Openshift 4.4 and the prometheus operator pod (namespace bound) is reporting the error below. 
```
prometheus-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" in the namespace "test-test"
E0728 15:36:36.219881       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:316: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:test-test:prometheus-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" in the namespace "test-test"
```

**How to reproduce it (as minimally and precisely as possible)**:
Install the operator from the catalog
**Environment**
OCP 4.4

* Prometheus Operator version:
0.37.0

**Comment by brancz** [comment]
My suspicion is that the the catalog entry was probably incorrectly bumped, and the permissions for this were not included.

**Comment by nakfour** [comment]
I checked the CSV for the operator, it does not have any rbac for "thanosrulers"

**Comment by brancz** [comment]
Could you open an issue on the catalog repo about this? We don't maintain the catalog entry so we rely on the community to bump maintain those.

**Comment by nakfour** [comment]
@brancz do you have a link to that repo?

**Comment by brancz** [comment]
I believe it is https://github.com/operator-framework/community-operators

**Comment by simonpasquier** [comment]
I believe it's been fixed by https://github.com/openshift/cluster-monitoring-operator/pull/939 (reported by https://bugzilla.redhat.com/show_bug.cgi?id=1882428). Anyway the issue doesn't belong to this repository.
