### ISSUE TITLE
collectd_exporter

### ISSUE THREAD

**Issue by Yalafeg** [prometheus-operator/prometheus-operator#3378]
Hello,

collectd_exporter  plugin "https://hub.docker.com/r/prom/collectd-exporter/" is usually used with prometheus to be able to automatically collect metrics from multiple servers. Is it a feature that can be easily added to this code? Is it planned to add the collected feature to this code?

Regards,

**Comment by paulfantom** [comment]
This would be out of scope for the project. Usually, you deploy your application in a way you prefer and add a ServiceMonitor to allow prometheus scraping it. More in https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/running-exporters.md

**Comment by Yalafeg** [comment]
Hello,

Thank you for your reply, I was able to create the service and collect the metrics from an external server (plugin collectd installed).
My problem now is that I am unable to get those values in the Prometheus already configured and installed on Kubernetes. Note that Prometheus and the collectd_exporter service are installed on the same namespace. Do you have any idea?

Regards,

**Comment by Yalafeg** [comment]
In other terms, under prometheus target section, I am unable to see the collectd_exporter
