### ISSUE TITLE
Secure Prometheus Config Reload

### ISSUE THREAD

**Issue by scott2449** [prometheus-operator/prometheus-operator#3381]
**What is missing?**
The current reload works via /-/reload endpoint which requires web.enable-lifecycle which also allows prometheus to be killed with /-/quit. For those of us exposing the Prometheus endpoint this is very problematic. Fortunately there is much better way to do this! https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/ (since 1.10). Once this is enabled you can send a `kill -1 1` (sighup process 1) from the sidecar instead.

**Why do we need it?**
Much lighter weight, more secure, and slightly faster. No need for web.enable-lifecycle at all!

**Environment**
All

* Prometheus Operator version:
N/A

**Anything else we need to know?**:
Nope

**Comment by scott2449** [comment]
When I say current I am specifically talking about https://github.com/coreos/prometheus-operator/blob/master/cmd/prometheus-config-reloader/main.go

**Comment by brancz** [comment]
Yeah I think this is a great one, we were waiting for the feature to be ubiquitous enough so that we could make use of it for this. I think there should be an old issue somewhere about this as well. If you would like to fix this, please go ahead! :)

**Comment by scott2449** [comment]
Will do! We are going to take a crack at this on our project. If it works well we'll make sure it's nice and tidy and submit a PR 👌

**Comment by scott2449** [comment]
Ooof at first I thought this was limited to the **configmap** reload... but the core reload is doing the same thing. IMO there should be 1 reloader to do both and neither should use the http endpoint. The unfortunately would require touching the operator helm, the operator itself, and the base helm. I pretty sure we are not going to get time for that... we also may need to abandon the operator completely and continue to manage ourselves.

**Comment by brancz** [comment]
The fact that there are two reloaders is a bit of tech debt, there is no reason why they can't be one. You're of course free to choose tools as you wish, I highly doubt that rolling everything from scratch and not making use of the 4+ years of this project has in experience of operating, configuring and running Prometheus is less work than changing the reloader a bit. Again you're of course free to do what you think is best for your situation.

**Comment by coderanger** [comment]
@scott2449 If you are exposing things through an Ingress, you can map the whole `/-/` path prefix to a different service, presumably one that does nothing but returns a 404 for all requests or similar.

**Comment by scott2449** [comment]
Well we already had most of it. This was just to kill some of that custom stuff. I finished a container that does this reliably with just a few lines of shell yesterday. Going to talk to my team today and see if they agree I taking a second pass just attempting to shim my reloader into the main reloader spot (just using the prom helm and not the operator, which is still an upgrade from us from the existing istio yamls being used). Just for reference in case I don't get to the PR stage I'll link a gist with shell code.

**Comment by scott2449** [comment]
https://gist.github.com/scott2449/ec0b81edbfe41170830df6a3beb2b2f3

**Comment by scott2449** [comment]
> @scott2449 If you are exposing things through an Ingress, you can map the whole `/-/` path prefix to a different service, presumably one that does nothing but returns a 404 for all requests or similar.

We use an istio virtual service ingress, we also have auth/https in front of it. We'd also want to block it from everything else even within the mesh. I don't argue it could be done. My point is that this is much more secure and clean.

**Comment by scott2449** [comment]
> https://gist.github.com/scott2449/ec0b81edbfe41170830df6a3beb2b2f3

Also added the yaml so folks can see the process namespace share and shared configmap setup

**Comment by simonpasquier** [comment]
FYI https://github.com/prometheus-operator/prometheus-operator/pull/5690 is in progress
