### ISSUE TITLE
RFE: Remove vendor/ directory

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#3386]
Since adding modules in golang, `vendor/` directory is not needed anymore. Removing it will reduce repository size, provide better developer experience when reviewing PRs and simplify tooling code in few cases as we won't need to ignore files in the directory.

/cc @brancz @lilic @metalmatze @s-urbaniak

**Comment by metalmatze** [comment]
If we (already) point the CI to use the proxy.golang.org then I'm fine with that. Might be the default in Go now anyway. :blush:

**Comment by paulfantom** [comment]
Indeed `proxy.golang.org` is [the default in go 1.13+](https://golang.org/doc/go1.13#introduction)
