### ISSUE TITLE
New Logo?

### ISSUE THREAD

**Issue by ryanj** [prometheus-operator/prometheus-operator#3389]
Feature: New Logo

The current logo could use some work

1. Are there any clear guidelines for new logo submissions?  Does CNCF have guidelines that we need to follow?
2. Have any suggestions on how to wrangle concept submissions? (aside from attaching images in comments below?)

**Comment by lilic** [comment]
Thanks for opening the issue! 🎉 

There are no guidelines, the current logo does not use any existing CNCF logos it was purely just symbols that indicate Prometheus and Kubernetes, so I would like to stay in this direction and not use directly the logos of the projects as to not violate any guidelines. I am also not sure if the current one violates any.

**Comment by paulfantom** [comment]
> Does CNCF have guidelines that we need to follow?

note: prometheus-operator is not (yet) a CNCF project.

**Comment by bia** [comment]
I made some sketches today, they might be a little too complex.
Should we pursue any of these? 
Any more ideas for changes?

![200806prom-operator1](https://user-images.githubusercontent.com/92439/89548426-51fb0f00-d807-11ea-890f-afb3f9d8110a.png)
![200806prom-operator2](https://user-images.githubusercontent.com/92439/89548429-532c3c00-d807-11ea-908e-05efae74d47d.png)
![200806prom-operator3](https://user-images.githubusercontent.com/92439/89548435-545d6900-d807-11ea-8e9e-00febb1e0f48.png)
![200806prom-operator4](https://user-images.githubusercontent.com/92439/89548648-938bba00-d807-11ea-9ded-624678640bf2.png)

**Comment by brancz** [comment]
Wow thank you so much for doing this @bia! I personally really like the 3rd one, I would just want to double check with the CNCF that this doesn't violate trademark uses. (maybe we should just apply for CNCF sandbox project and solve that issue once and for all? :smile: )

**Comment by lilic** [comment]
Thanks Bianca! Much better than my attempt :D 🎉 ❤️ 

Seems like it is trademarked sadly :( https://www.linuxfoundation.org/trademark-usage/

> A trademark should not be altered or amended in any way.  A mark should not be combined with any other mark, hyphenated, abbreviated or displayed in parts.  A trademark that is depicted as two or more words should not be compressed into one word. A logo should not be displayed with color variations, or with other elements superimposed on top of the logo.

Maybe we could combine just a simple fire image with the wheels from the Kubernetes logo. Ones that are not taken directly from Prometheus or Kubernetes?

**Comment by bia** [comment]
Ok! I’ll try that. :D 
Thanks for the feedback @brancz @lilic

**Comment by s-urbaniak** [comment]
Wonderful, thank you!! :tada:

**Comment by bia** [comment]
The wheel from the kubernetes logo has got 7 points (like the heptagon that contains it). Another 7 pointed wheel would look too similar to the logo and 6 or 8 pointed wheels look wrong : 

![200807prom-operator3](https://user-images.githubusercontent.com/92439/89657372-43772b00-d8cd-11ea-9fc2-a8e2cc560a69.png)


So I tried this
![200807prom-operator4](https://user-images.githubusercontent.com/92439/89655624-ac10d880-d8ca-11ea-9054-a5c47f83135c.png)

Thoughts?

**Comment by paulfantom** [comment]
I love those! 

I do prefer the first one though (flame in a blue wheel) as the second one is very similar to what people use in architectural diagrams when describing a prometheus instance in a kubernetes cluster. Especially considering [a number of official kubernetes logos which use blue heptagon as a background](https://github.com/kubernetes/community/tree/master/icons#control-plane-components-icons).

> Another 7 pointed wheel would look too similar to the logo and 6 or 8 pointed wheels look wrong

Maybe an odd number of points can help here, like a 9-point wheel? I also don't have issues with 7-point one unless this leads to trademark violation issues :thinking:

**Comment by bia** [comment]
Good point @paulfantom - how about this then? Maybe we can get away with it? 😉 

![200807prom-operator5](https://user-images.githubusercontent.com/92439/89686603-ef853a00-d8fe-11ea-959c-04bb428e2f9b.png)

**Comment by lilic** [comment]
Happy with this as well! Thanks Bianca! @prometheus-operator/prometheus-operator-reviewers PTAL :)

**Comment by bia** [comment]
Brilliant! Where should I upload svg and transparent png?

**Comment by squat** [comment]
+1 from me

**Comment by lilic** [comment]
@bia do you mind creating a PR to add it to the repo itself? After that we can manually change it. Thanks! 🎉

**Comment by brancz** [comment]
I love it! Thank you so much for taking the time for this @bia!

A really minor thing (and I really don't care if it's fixed or not, only if it's easy), it seems at the bottom half of the steering wheel, and the flame overlay there are slight edges showing.

**Comment by bia** [comment]
Thanks for the feedback @brancz ! It's no work at all to change. 🙂 
What do you mean exactly?

Are you talking about these artifacts from my sketching? They will disappear when I transpar-ify the logo.
![200807prom-operator5](https://user-images.githubusercontent.com/92439/89798188-2a1fea00-db2c-11ea-8989-9f622e903742.png)

**Comment by brancz** [comment]
Ah perfect, yes those edges and a small circle-like dent in the lower tip over the steering wheel coming from the bottom of the flame.

Again thank you so much! Very grateful that you're spending your time on this! :)

**Comment by paulfantom** [comment]
> Brilliant! Where should I upload svg and transparent png?

I think we can put logo files in `Documentation/logos`.

**Comment by tuladhar** [comment]
👋 Hi @bia - First of all, thank you for awesome logos. Do you mind if I use one of the unused logo for Kubernetes-related website? https://k8s-issues.purutuladhar.com/

**Comment by bia** [comment]
Hey @tuladhar I don't mind at all, glad that you like them. 😊
