### ISSUE TITLE
WAL Recovery Restart Loop (EKS)

### ISSUE THREAD

**Issue by ajcann** [prometheus-operator/prometheus-operator#3391]
I would like to re-open https://github.com/prometheus-operator/prometheus-operator/issues/3094 as we're experiencing this in a cluster which generates a great deal of metrics. In the event of a prometheus restart the WAL replay consistently takes longer than the liveness probe / readiness probes resulting in a restart loop.

**Comment by brancz** [comment]
As mentioned in other threads, I would prefer to keep focusing on improving Prometheus here and performing one time recoveries in cases like yours by setting `paused: true` in the Prometheus object, extending the liveness probe so the Prometheus is able to recover, and then remove `paused: true` again and let the Prometheus do a clean restart.

**Comment by TechIsCool** [comment]
#3211 has a great idea. I keep having to fix clusters in our platform because of this.

**Comment by ajcann** [comment]
What I've done for now is something like
```
  prometheusSpec:
    # Set absurdly high thresholds as a workaround not being able to disable these and not having enough time to WAL
    containers:
    - name: prometheus
      livenessProbe:
        failureThreshold: 1000
      readinessProbe:
        failureThreshold: 1000
```
combined with a persistent volume claim about 5x of max retention size in order to check around the checkpoints not being able to write to disk.

**Comment by ajcann** [comment]
> As mentioned in other threads, I would prefer to keep focusing on improving Prometheus here and performing one time recoveries in cases like yours by setting `paused: true` in the Prometheus object, extending the liveness probe so the Prometheus is able to recover, and then remove `paused: true` again and let the Prometheus do a clean restart.

This is certainly a good way to manually resolve the issue, but we have dozens of clusters running workloads 24/7, which I imagine isn't that unusual, so automatic recovery is a must for us.

**Comment by fernandocarletti** [comment]
@ajcann did you try using the `initialDelaySeconds` setting in the probes? it sounds odd that prometheus operator leaves a huge failureThreshold.

I'm having a similar issue in EKS.

**Comment by fernandocarletti** [comment]
Actually, I just found this: https://github.com/prometheus-operator/prometheus-operator/pull/1232#issuecomment-382791578

As far as I understood, the `failureThreshold` was supposed to be set only in the readiness probe for having it ready ASAP instead of waiting for the full `InitialDelaySeconds`. Hackish, but kinda makes sense. Doesn't seem to fit the liveness probe case though.

**Comment by brancz** [comment]
> Doesn't seem to fit the liveness probe case though.

Why do you say this? I think I'm happy with increasing the static failureThreshold though, since readiness and liveness is currently the same in Prometheus.

**Comment by fernandocarletti** [comment]
@brancz Unless I'm missing something, if you set a high `failureThreshold` for the `livenessProbe`, it will accept that the probe fails many times (`failureThreshold * periodSeconds`, the last one defaults to 10s). In the @ajcann's snippet, setting it to 1000, just gonna allow that the health check fails a thousand times until the pod detects that the container is in fact down (this translates to 2h+).

For the `readinessProbe` it makes sense since you want to allow that to fail for a long time until the container finally gets ready and then the pod endpoint is added to the service, but you don't want to keep it there if the endpoint is not responding.

Being the same endpoint does not means the readiness and liveness probes do the same thing.

**Comment by ajcann** [comment]
> @brancz Unless I'm missing something, if you set a high `failureThreshold` for the `livenessProbe`, it will accept that the probe fails many times (`failureThreshold * periodSeconds`, the last one defaults to 10s). In the @ajcann's snippet, setting it to 1000, just gonna allow that the health check fails a thousand times until the pod detects that the container is in fact down (this translates to 2h+).
> 
> For the `readinessProbe` it makes sense since you want to allow that to fail for a long time until the container finally gets ready and then the pod endpoint is added to the service, but you don't want to keep it there if the endpoint is not responding.
> 
> Being the same endpoint does not means the readiness and liveness probes do the same thing.

@fernandocarletti is correct here, I should only be adjusting the readiness probe to address the slow start up.

**Comment by brancz** [comment]
It boils down to, in Prometheus currently the liveness and readiness endpoints are equivalent, so either we have the probes equivalent as well or drop the liveness probe for now (I think this is the right way to go), as really what the endpoints represent is not whether the process is alive (it is) but rather whether it is _ready_ to serve traffic, when the WAL replaying. Hence I think we should remove the liveness probe for the time being until either 1) the endpoint improves or 2) WAL replaying becomes trivially fast that we don't care. Neither of those seem to be happening tomorrow so let's remove the liveness probe. Thoughts?

**Comment by paulfantom** [comment]
I would still prefer implementing [`startupProbe`](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes). However since this is available only in recent k8s versions I am fine with removing `livenessProbe` for now.

**Comment by brancz** [comment]
Yeah, let's give it until ~1.21 I would say, then `startupProbes` will have been around for long enough.

**Comment by fernandocarletti** [comment]
I'm a bit late here, I totally missed the older replies. But what happens if the process can't reply the requests but it is not dead? Isn't this the case for the liveness probe?

**Comment by juliantaylor** [comment]
Isn't this a bug in prometheus?
The liveness probe should be active during the WAL replay, only the readiness probe is false.

We also have a cluster with a lot of metrics and the WAL replay taking several minutes and have no issues.
Disabling the liveness probe seems like a bad idea at least for prometheus versions that work (which is for us at least 2.17 and 2.22 also seems to be ok so far but we only rolled it out last week)

**Comment by juliantaylor** [comment]
> It boils down to, in Prometheus currently the liveness and readiness endpoints are equivalent, so either we have the probes equivalent as well or drop the liveness probe for now 

this is not correct: https://github.com/prometheus/prometheus/blob/master/web/web.go#L442
the readiness function only becomes ready when prometheus sets itsself ready, the liveness probe is ok as soon as the webserver is initialized and does not wait for the WAL replay. We have explicitly tested this behaviour recently when switching the storage backend of our prometheus instances as we initially also assumed we need to use startup probes.

**Comment by simonpasquier** [comment]
> the readiness function only becomes ready when prometheus sets itsself ready, the liveness probe is ok as soon as the webserver is initialized and does not wait for the WAL replay.

Hmm, the `/-/ready` endpoint of Prometheus is wrapped by the same [ready handler](https://github.com/prometheus/prometheus/blob/daf382e4a9f5ca380b2b662c8e60755a56675f14/web/web.go#L491-L500) as the other endpoints so it returns `503 Status Unavailable` as long as the TSDB data hasn't been loaded (the `dbOpen` channel is closed [here](https://github.com/prometheus/prometheus/blob/daf382e4a9f5ca380b2b662c8e60755a56675f14/cmd/prometheus/main.go#L756) and the web server [waits](https://github.com/prometheus/prometheus/blob/daf382e4a9f5ca380b2b662c8e60755a56675f14/cmd/prometheus/main.go#L677) for it to be closed before [switching](https://github.com/prometheus/prometheus/blob/daf382e4a9f5ca380b2b662c8e60755a56675f14/cmd/prometheus/main.go#L690) the ready flag).

**Comment by juliantaylor** [comment]
yes but the livenessprobe `/-/healthy` which would restart pods in if it fails has no relation to the tsdb, only the webserver. The readiness probe will never kill a pod, it only causes to not receive traffic.
See the log file I posted in https://github.com/prometheus-operator/prometheus-operator/issues/3211#issuecomment-717777484 to see where the different probes become healthy.

**Comment by juliantaylor** [comment]
here the prometheus code:

```
	router.Get("/-/healthy", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		fmt.Fprintf(w, "Prometheus is Healthy.\n")
	})
	router.Get("/-/ready", readyf(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		fmt.Fprintf(w, "Prometheus is Ready.\n")
	}))
```

note the difference between the two in this part

    readyf(func(w http.ResponseWriter, r *http.Request)

and 

    func(w http.ResponseWriter, r *http.Request)

the liveness probe is not wrapped into the readiness check

**Comment by simonpasquier** [comment]
@juliantaylor I agree with your conclusion, sorry for the mistake. The `/-/healthy` endpoint should return OK as soon as the webserver is started which happens in parallel of the WAL replay.

There seems to have been some confusion in the original description:

> I would like to re-open #3094 as we're experiencing this in a cluster which generates a great deal of metrics. In the event of a prometheus restart the WAL replay consistently takes longer than the liveness probe / readiness probes resulting in a restart loop.

I suspect that only the readiness probe was responsible for the container being restarted. The same goes for #3094: looking at the data, I see no strong evidences that the liveness probe is involved.

cc @brancz @paulfantom

**Comment by juliantaylor** [comment]
A failing readiness probe should not cause a pod container to restart, only the liveness probe does that so that there are reported issues is odd, there may be a bug in prometheus itself.

@ajcann how big is your WAL data? how long does it take to replay? how many chunks are it (see startup logs)
Can you provide the prometheus log file of a failing startup? Ideally including the kubernetes events that are created too.

**Comment by djsly** [comment]
```
ts=2022-09-24T15:54:40.201Z caller=head.go:615 level=info component=tsdb msg="WAL segment loaded" segment=53921 maxSegment=53921
ts=2022-09-24T15:54:40.201Z caller=head.go:621 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=31.38426441s wal_replay_duration=5m25.289211442s total_replay_duration=6m45.362106883s
```
that's for my WAL file. only way to start up is to patch to avoid the operator from managing the prom resource and increase the startup timeout.

**Comment by mimmus** [comment]
@djsly  how to patch  to avoid restart?

**Comment by sumitkhaintel** [comment]
Hi @brancz I have tried to increase the failure threshold to 1000 but still my pod is crashing continously with below error.

 Warning  Unhealthy  9s (x2 over 24s)  kubelet            **Startup probe failed: HTTP probe failed with statuscode: 503**


ts=2023-02-22T18:28:23.376Z caller=tls_config.go:271 level=info component=web msg="TLS is disabled." http2=false address=[::]:9090
ts=2023-02-22T18:28:23.409Z caller=head.go:564 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2023-02-22T18:28:23.409Z caller=head.go:571 level=info component=tsdb msg="Chunk snapshot is enabled, replaying from the snapshot"
ts=2023-02-22T18:28:23.409Z caller=head.go:585 level=info component=tsdb msg="Chunk snapshot loading time" duration=48.098µs
ts=2023-02-22T18:29:15.062Z caller=head.go:608 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=51.65313474s
ts=2023-02-22T18:29:15.062Z caller=head.go:614 level=info component=tsdb msg="Replaying WAL, this may take a while"
ts=2023-02-22T18:29:33.470Z caller=head_wal.go:458 level=warn component=tsdb msg="Unknown series references" samples=7 exemplars=0 histograms=0 metadata=0
ts=2023-02-22T18:29:33.470Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=204
ts=2023-02-22T18:29:44.636Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=1 maxSegment=204
ts=2023-02-22T18:29:57.172Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=2 maxSegment=204
ts=2023-02-22T18:30:11.469Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=3 maxSegment=204
ts=2023-02-22T18:30:24.489Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=4 maxSegment=204
ts=2023-02-22T18:30:35.918Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=5 maxSegment=204
ts=2023-02-22T18:30:39.988Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=6 maxSegment=204
ts=2023-02-22T18:30:41.675Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=7 maxSegment=204
ts=2023-02-22T18:30:43.095Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=8 maxSegment=204
ts=2023-02-22T18:30:44.684Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=9 maxSegment=204
ts=2023-02-22T18:30:46.713Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=10 maxSegment=204
ts=2023-02-22T18:30:48.570Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=11 maxSegment=204
ts=2023-02-22T18:30:50.354Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=12 maxSegment=204
ts=2023-02-22T18:30:52.228Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=13 maxSegment=204
ts=2023-02-22T18:30:54.363Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=14 maxSegment=204
ts=2023-02-22T18:30:56.417Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=15 maxSegment=204
ts=2023-02-22T18:30:58.401Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=16 maxSegment=204
ts=2023-02-22T18:31:00.425Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=17 maxSegment=204
ts=2023-02-22T18:31:02.629Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=18 maxSegment=204
ts=2023-02-22T18:31:04.606Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=19 maxSegment=204
ts=2023-02-22T18:31:06.404Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=20 maxSegment=204
ts=2023-02-22T18:31:08.703Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=21 maxSegment=204
ts=2023-02-22T18:31:10.156Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=22 maxSegment=204
ts=2023-02-22T18:31:12.059Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=23 maxSegment=204
ts=2023-02-22T18:31:13.792Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=24 maxSegment=204
ts=2023-02-22T18:31:15.394Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=25 maxSegment=204
ts=2023-02-22T18:31:17.647Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=26 maxSegment=204
ts=2023-02-22T18:31:19.918Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=27 maxSegment=204
ts=2023-02-22T18:31:21.959Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=28 maxSegment=204
ts=2023-02-22T18:31:24.120Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=29 maxSegment=204
ts=2023-02-22T18:31:25.971Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=30 maxSegment=204
ts=2023-02-22T18:31:27.988Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=31 maxSegment=204
ts=2023-02-22T18:31:30.026Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=32 maxSegment=204
ts=2023-02-22T18:31:30.719Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=33 maxSegment=204
ts=2023-02-22T18:31:31.426Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=34 maxSegment=204
ts=2023-02-22T18:31:31.980Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=35 maxSegment=204
ts=2023-02-22T18:31:32.369Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=36 maxSegment=204
ts=2023-02-22T18:31:32.899Z caller=head.go:685 level=info component=tsdb msg="WAL segment loaded" segment=37 maxSegment=204

**Comment by dimm0** [comment]
Same here

**Comment by mac-lucky** [comment]
+1

**Comment by sgutwein** [comment]
+1

**Comment by apgapg** [comment]
> containers:
>     - name: prometheus
>       livenessProbe:
>         failureThreshold: 1000
>       readinessProbe:
>         failureThreshold: 1000

```yml
    containers:
      - name: prometheus
        livenessProbe:
          failureThreshold: 1000
        readinessProbe:
          failureThreshold: 1000
        startupProbe:
          failureThreshold: 1000
```

Startup probe must also be included
