### ISSUE TITLE
collect dockerd metrics from node

### ISSUE THREAD

**Issue by MartinForReal** [prometheus-operator/prometheus-operator#3397]
**What is missing?**

 I want to add a few ports to kubelet service in order to collect metrics data provided by dockerd. 

**Why do we need it?**
I need to collect metrics data from the node. 

**Environment**
docker 19.03.12

* Prometheus Operator version:

v0.40.0

**Anything else we need to know?**:
none

**Comment by brancz** [comment]
I thought that this might happen one day. I think at this point I would prefer extracting the node sync into a separate component, I do think this is useful and we should allow configuring pretty much anything a user desires, but I think it needs a bit of a refactor/rewrite.

**Comment by MartinForReal** [comment]
@brancz I would like to add a new operator to add node info to endpoint slice. Could you please help create a repo in prometheus-operator org please? I would send pr when I'm ready

**Comment by brancz** [comment]
On a second thought, maybe it's time to just remove this functionality entirely and make use of Prometheus' Kubernetes node service discovery directly. This was created in a time where the `additionalScrapeConfigs` feature didn't exist and we had to have an `Endpoints` object to collect cAdvisor and kubelet metrics.

**Comment by s-urbaniak** [comment]
Definitely a :+1: on deprecating the whole `--kubelet-service` and moving it into a small component of its own. prometheus-operator should be agnostic on the actual monitoring targets and leave it up to the user _how_ kubelet monitoring is being set up. We can provide guidance of course, by providing example manifests, jsonnet in kube-prometheus, etc.

**Comment by brancz** [comment]
Maybe we can start by documenting how to make use of `additionalScrapeConfigs` to discover nodes, add it to kube-prometheus (and disable the `--kubelet-service` flag in kube-prometheus) and then deprecate the functionality here. I wouldn't even create the separate component unless a clear need for it arises again.

**Comment by paulfantom** [comment]
I agree, we should deprecate `--kubelet-service` and promote usage of `additionalScrapeConfigs` option instead. Doing this in kube-prometheus sounds like a good first step.

**Comment by coderanger** [comment]
If the only thing being changed is the port, you can specify the port as an override in the ServiceMonitor anyway.

**Comment by brancz** [comment]
Yes this is what we do to collect cri-o metrics today as well.

**Comment by MartinForReal** [comment]
I see. Thanks for the info.
