### ISSUE TITLE
Expose EnforcedSampleLimit as metric

### ISSUE THREAD

**Issue by lilic** [prometheus-operator/prometheus-operator#3400]
EnforcedSampleLimit defines global limit on number of scraped samples and overrides any existing limits set for PodMonitor and ServiceMonitor.

**Why do we need it?**
Having this value in a metric allows us to create an alert to warn the admin that they are getting close to the limit, something like KubePersistentVolumeFillingUp alert. This means admin does not need to create this alert but it comes out of the box with the Prometheus operator mixin for example. This would be a warning level alert, for critical one there is already TargetDown alerts.

**Comment by brancz** [comment]
I think it's a bit more comparable to a CPU or memory, but I don't think which comparison matters here.

More importantly, there is an inconsistency here because technically a ServiceMonitor can be selected by multiple Prometheus objects, so it's ambiguous if two Prometheus objects selected the same ServiceMonitor what configuration to expose as a metric. I think because of this, in this situation only Prometheus or a sidecar next to Prometheus could really do this, but not the prometheus operator itself.

**Comment by lilic** [comment]
Sorry for not being clear enough, my thinking was to have the metric be tied to the Prometheus object rather than the servicemonitor, and only when the EnforcedSampleLimit is set, we would not be able to set it for when individual servicemonitors set the sample_limit true. WDYT?

**Comment by brancz** [comment]
Ah yes, super nice idea, I didn't think of this. Sounds good to me.

**Comment by nrchakradhar** [comment]
As per my understanding of collector.go
https://github.com/prometheus-operator/prometheus-operator/blob/59a2a22dba363be52d3ce25f6e130214cc50ed2c/pkg/prometheus/collector.go#L60-L65

Adding a new one like below will expose the metric I think.
`ch <- prometheus.MustNewConstMetric(descPrometheusSpecEnforcedSampleLimit, prometheus.GaugeValue, enforcedSampleLimit, p.Namespace, p.Name)`

descPrometheusSpecEnforcedSampleLimit needs to be defined similar to `descPrometheusSpecReplicas` at https://github.com/prometheus-operator/prometheus-operator/blob/59a2a22dba363be52d3ce25f6e130214cc50ed2c/pkg/prometheus/collector.go#L24

If my understanding is right, I can raise a PR for the same. @lilic 
I can later add an alert warning in mixin.

**Comment by nrchakradhar** [comment]
Gentle ping @lilic

**Comment by simonpasquier** [comment]
@nrchakradhar this looks good to me. Feel free to open a PR :)
