### ISSUE TITLE
Reconciliation loop latency metrics

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#3408]
**What is missing?**

Reconciliation loops duration histogram metrics. 

**Why do we need it?**

With such metrics, we can have better insight into the internal workings of prometheus-operator and possibly alert on increased latency of reconciled resource.

**Environment**

* Prometheus Operator version:

```
v0.41.1 and before
```

**Anything else we need to know?**:

**Comment by metalmatze** [comment]
It would be great to experiment with adding a Histogram and see if we get enough data, otherwise maybe a Summary is good?

**Comment by heylongdacoder** [comment]
Hi folks, I am trying to implement this. Do I need to customize the value for the histogram buckets? If yes, what value would be suitable?

**Comment by simonpasquier** [comment]
IMHO, the default histogram buckets would be too detailed for the operator, `{.1, .5, 1, 5, 10}` is probably enough.
