### ISSUE TITLE
Move quay.io/coreos/instrumented-sample-app image to the new org

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#3416]
**What is missing?**

the [quay.io/coreos/instrumented-sample-app](https://quay.io/repository/coreos/instrumented-sample-app) image hasn't been moved to the new prometheus-operator organization. For reference it's used in the [e2e tests](https://github.com/prometheus-operator/prometheus-operator/blob/0b2321d2bd52d887d7d3fec4349f59cc6a9be73d/test/framework/ressources/basic-auth-app-deployment.yaml#L19).

**Why do we need it?**

For consistency and easier maintenance. It might be worth having a dedicated repository for the sample app.

**Environment**

* Prometheus Operator version:

N/A

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
I would suggest we combine [instrumented-sample-app](https://github.com/prometheus-operator/prometheus-operator/tree/master/test/instrumented-sample-app) with [brancz/prometheus-example-app](https://github.com/brancz/prometheus-example-app) and either create new repository in prometheus-operator org or reuse https://github.com/brancz/prometheus-example-app

**Comment by simonpasquier** [comment]
https://quay.io/repository/prometheus-operator/instrumented-sample-app
