### ISSUE TITLE
Prometheus do not update config for fluent bit metrics.

### ISSUE THREAD

**Issue by antonLebiedyntsev** [prometheus-operator/prometheus-operator#3419]
Using helm chart of prometheus operator. 
Added config for prometheus operator for 
`  - name: "fluentbit-metrics-monitor"
    selector:
      matchLabels:
        app: fluent-bit
    namespaceSelector:
      matchNames:
        - logging
    endpoints:
      - port: "metrics"
        interval: 30s
        path: /api/v1/metrics/prometheus
  additionalPodMonitors: []`

Fluentbit provides metrics as expected. 

For some reason prometheus do not update config and do not add targets. 

Prometheus operator version helm prometheus-operator-8.2.16 app version 0.34.0.
Fluentbit helm chart fluent-bit-2.8.3 app version 1.3.2

**Comment by s-urbaniak** [comment]
please file an issue with the helm repository https://github.com/helm/charts/tree/master/stable/prometheus-operator. This repository does not maintain them any more, see https://github.com/prometheus-operator/prometheus-operator/tree/master/helm.
