### ISSUE TITLE
How to scrape metrics from a exporter ( just binary ) running on a AWS VM using prometheus operator ?

### ISSUE THREAD

**Issue by devops2stay** [prometheus-operator/prometheus-operator#3428]
Have a exporter running on a AWS VM. Also have prometheus & prometheus operator installed on Kubernetes cluster. Wanted to know if we can monitor this exporter via prometheus operator ? - Meaning scrape metrics and view it in prometheus dashboard ( Targets )
I understand Prometheus operator is kubernetes native and can monitor kubernetes cluster instances. But I am not sure it can monitor an exporter running on an external AWS vm not managed under kubernetes. I heard about "custom configuration" and "virtual-IP-based-bridge" methods to accomodate this external setup. But if this is the case, need some guidance on how to go about implementing them. Thank you so much for the support/assistance in advance !

**Comment by brancz** [comment]
Your best shot right now is the additional scrape configs feature.

**Comment by coderanger** [comment]
You could also manually construct a service's endpoints and use a ServiceMonitor.

**Comment by paulfantom** [comment]
Closing as the issue appears to be answered. If you need additional clarification, please reopen it.
