### ISSUE TITLE
Host the documentation on a public-facing website

### ISSUE THREAD

**Issue by scottrigby** [prometheus-operator/prometheus-operator#3431]
**What is missing?**

Question: do we want more easily browsable docs? Or is the goal to just point users here: https://github.com/prometheus-operator/prometheus-operator/tree/master/Documentation

**Why do we need it?**

This message at https://coreos.com/operators/prometheus/docs/latest/
> These docs are deprecated while they are being migrated to Red Hat. For the most up to date docs, please see the corresponding GitHub repository.

**Environment**

* Prometheus Operator version:

    `all`
    

**Anything else we need to know?**:

Context is linking to docs from the helm chart (rename in progress. See https://github.com/scottrigby/prometheus-helm-charts/pull/1)

**Comment by paulfantom** [comment]
I am not a fan of github pages and would prefer to do it with netlify, but I agree we should have a documentation site.

**Comment by simonpasquier** [comment]
I've changed the title of the issue so it doesn't mandate GitHub pages anymore.

**Comment by metalmatze** [comment]
I've started a new repo https://github.com/prometheus-operator/website and a current version is deployed to: https://prometheus-operator-metalmatze.netlify.app/

**Comment by simonpasquier** [comment]
https://prometheus-operator.dev is up and running (well almost because netlify has issues right now). I guess we can close it :)
