### ISSUE TITLE
Fix package name in go.mod

### ISSUE THREAD

**Issue by MartinForReal** [prometheus-operator/prometheus-operator#3443]
**What happened?**

I need to create servicemonitor object in my program. And when I try to compile my program. I found that the package name of operator is github.com/coreos/prometheus-operator

**Did you expect to see something different?**
I think it would be better if we renamed the whole project.

**Comment by MartinForReal** [comment]
workaround: I can still use github.com/coreos/prometheus-operator as package name to import code

**Comment by simonpasquier** [comment]
duplicate of https://github.com/prometheus-operator/prometheus-operator/issues/3393 :)
