### ISSUE TITLE
External service by start new node

### ISSUE THREAD

**Issue by frederiksf** [prometheus-operator/prometheus-operator#3446]
We are using prometheus with the prometheus operator and the servicemonitor. i would like to scrape the wmi exporter which is an external service running on the node off course without a k8s service. 

Our k8scluster is dynamic where nodes come and go. How can i create an k8s endpoint on the moment a new node becomes ready?

I saw on the internet i can create a static endpoint but this is not workable since we use autoscaler.

```BASH
kind: Endpoints
apiVersion: v1
metadata:
 name:  ip-10-2-30-51.eu-central-1.compute.internal
subsets:
 - addresses:
     - ip: 10.2.30.233
   ports: 
	   - name: metrics
       port: 5000
```
Does anybody solve this issue

**Comment by brancz** [comment]
Your best bet currently is the additionalScrapeConfigs feature.

**Comment by paulfantom** [comment]
We do have a windows jsonnet addon in kube-prometheus - https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/addons/windows.libsonnet.

Other than that `additionalScrapeConfigs` is the best bet as mentioned and possibly in the future it will be possible with Generic ScrapeConfig #2787).

Closing as the issue appears to be answered. If you need additional clarification, please reopen it.
