### ISSUE TITLE
Missing v0.38.2 container image

### ISSUE THREAD

**Issue by lblackstone** [prometheus-operator/prometheus-operator#3448]
**What happened?**
I was depending on the [0.38 bundle](https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-0.38/bundle.yaml), which was just updated to point to quay.io/coreos/prometheus-operator:v0.38.2

However, this image doesn't exist: https://quay.io/repository/coreos/prometheus-operator?tag=v0.38.2&tab=tags

I just noticed that the repo was renamed, so perhaps that's related.
`https://quay.io/repository/coreos/prometheus-operator` -> `https://quay.io/repository/prometheus-operator/prometheus-operator`

**Comment by simonpasquier** [comment]
Yes there's been a hiccup in the release process because of the project renaming, https://github.com/prometheus-operator/prometheus-operator/pull/3444 should fix this and we need to trigger a new release.

**Comment by simonpasquier** [comment]
Ah we need another patch to fix the image location in the bundle YAML...

**Comment by paulfantom** [comment]
0.38.2 images were manually pushed to repositories in quay.io/coreos organisation
