### ISSUE TITLE
prometheus-k8s-1 always CrashLoopBackOff

### ISSUE THREAD

**Issue by ne1000** [prometheus-operator/prometheus-operator#3454]
I have a issues, but I don't know if it's bug,  the prometheus-k8s-1 pod was always reboot，and prometheus-k8s-db uses NFS for persistence, how to fix it for me?

kubeadm version: 1.17.0
kubectl version: 1.17.0
kube-prometheus: v0.4.0
Docker version 19.03.4

`# kubectl get pods -n monitoring

NAME                                   READY   STATUS             RESTARTS   AGE
alertmanager-main-0                    2/2     Running            0          3d
alertmanager-main-1                    2/2     Running            0          3d
alertmanager-main-2                    2/2     Running            0          3d
grafana-867c579fc5-w7h49               1/1     Running            0          3d3h
kube-state-metrics-694d7954bf-vdxsm    3/3     Running            0          3d3h
node-exporter-787ts                    2/2     Running            0          3d3h
node-exporter-mw5z2                    2/2     Running            0          3d3h
node-exporter-x4xwr                    2/2     Running            0          3d3h
node-exporter-zvt58                    2/2     Running            0          3d3h
prometheus-adapter-84488ff4b5-t48ht    1/1     Running            0          3d3h
prometheus-k8s-0                       3/3     Running            0          44h
prometheus-k8s-1                       2/3     CrashLoopBackOff   665        44h
prometheus-operator-669d7cb8d9-glk94   1/1     Running            0          44h
`

`# kubectl logs -f prometheus-k8s-1 -n monitoring  prometheus-config-reloader

level=error ts=2020-08-25T01:27:39.116816099Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://localhost:9090/-/reload\": dial tcp 127.0.0.1:9090: connect: connection refused"
level=error ts=2020-08-25T01:27:44.117548087Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://localhost:9090/-/reload\": dial tcp 127.0.0.1:9090: connect: connection refused"
level=error ts=2020-08-25T01:27:49.11482389Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://localhost:9090/-/reload\": dial tcp 127.0.0.1:9090: connect: connection refused"
level=error ts=2020-08-25T01:27:54.122830097Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://localhost:9090/-/reload\": dial tcp 127.0.0.1:9090: connect: connection refused"
`

`# cat kube-prometheus-0.4.0/manifests/prometheus-prometheus.yaml

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: prometheus-data-db
        resources:
          requests:
            storage: 100Gi  
  baseImage: dockerhub.iov.cn/base/prometheus
  nodeSelector:
    kubernetes.io/os: linux
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.11.0
  secrets:
    - etcd-certs
`

`# cat storge-nfs/provisoner.yaml 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  namespace: monitor 
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: registry.cn-hangzhou.aliyuncs.com/open-ali/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: iov.cn/k8s 
            - name: NFS_SERVER
              value: 10.8.11.150
            - name: NFS_PATH
              value: /volume3/k8s-nfs
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.8.11.150 
            path: /volume3/k8s-nfs
`

`# cat prometheus-storageclass.yaml 

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-data-db 
provisioner: iov.cn/k8s
parameters:
  archiveOnDelete: "true"
`

`# kubectl get sc

NAME                   PROVISIONER    RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
prometheus-data-db    iov.cn/k8s   Delete          Immediate           false                  3d2h
`

`# kubectl get pvc -n monitoring

NAME                                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS           AGE
prometheus-k8s-db-prometheus-k8s-0         Bound    pvc-88973839-b961-472d-9843-36079fa8a32c   100Gi      RWO            prometheus-data-db     3d
prometheus-k8s-db-prometheus-k8s-1         Bound    pvc-5f22d6af-1cb9-4c69-a857-6765ac56732c   100Gi      RWO            prometheus-data-db     2d
`

**Comment by paulfantom** [comment]
@ne1000 you need something that can talk `remote_write` protocol and store your data (ex. Thanos or Cortex). After that you need to set up remote_write in Prometheus object, here is a reference: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#remotewritespec

**Comment by ne1000** [comment]
@paulfantom ok

**Comment by paulfantom** [comment]
Closing as this looks to be resolved. Please reopen if you feel it is still an issue.
