### ISSUE TITLE
cross-compiled failed

### ISSUE THREAD

**Issue by gupf0719** [prometheus-operator/prometheus-operator#3456]
1. cd ...prometheus-operator
2. GOOS=linux make build
then failed and show me the error

"go install: cannot install cross-compiled binaries when GOBIN is set"

**Comment by simonpasquier** [comment]
Hmm, which version of Go have you installed?

**Comment by gupf0719** [comment]
> Hmm, which version of Go have you installed?

go version go1.14.4 darwin/amd64

**Comment by gupf0719** [comment]
it is resloved
