### ISSUE TITLE
Alertmanager, retention

### ISSUE THREAD

**Issue by Asgoret** [prometheus-operator/prometheus-operator#3458]
Hi to everyone! 

Can somebody help with data retention in alertmanager? I found this [PR](https://github.com/prometheus-operator/prometheus-operator/pull/1710) but can't understand where in jsonnet config file put retention?

**Comment by paulfantom** [comment]
`retention` is a part of [`Alertmanager`](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec) spec and as such you need to configure it in your Alertmanager CR. A similar way to how you configure number of replicas for alertmanager or specify an image.

Example: https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/alertmanager/alertmanager.yaml#L28

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
