### ISSUE TITLE
kind/question , kind/design

### ISSUE THREAD

**Issue by shantpschauhan** [prometheus-operator/prometheus-operator#3461]
**Questions:**
1. Question: Is this possible or any way to use rolebinding (not the clusterrolebinding) to bind cluster role with Prometheus-operator service account to give required api access to the prometheus operator?
    Is this possible or any way to use rolebinding (not the clusterrolebinding) to bind cluster role with Prometheus service account to give required api access to the prometheus server?

2. Question : A Prometheus server deployed using prometheus-operator in a xyz namespace. Is this possible to limit deployed prometheus server in xyz namespace to monitor those applications only which are deployed in same xyz namespace.

3. Question: Is there any issue you see if deploying multiple prometheus servers by different prometheus-operator in different namespace but in same GKE k8s cluster. (there would be separate prometheus operator and prometheus server for each kubernetes namespace).
```
use case: we want different prometheus server in different namespace in same gke cluster.(there would be separate prometheus operator and prometheus server for each kubernetes namespace). and then prometheus server of each namespace will store the monitoring data of the application deployed in the same namespace. Also these different prometheus servers will have different alert manager. and these different prometheus server deployed in different namespace should not store/monitor any cluster wide data.  
```

**What did you do?**

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

  prometheus-operator:0.41.1

* Kubernetes version information:

 Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

   GKE cluster

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
1) Yes, if you specify the `--namespaces` flag the prometheus operator will only require roles for the namespaces specified.
2) "all namespaces" refers to all discovered, which means if you use the `--namespaces` flag set to xyz, then that's already the case. Alternatively you can label the namespaces and use the namespace selector for servicemonitors/podmonitors in the Prometheus object.
3) You want to make sure that the namespaces reconciled on do not overlap, and that all prometheus operators are running the same version, and more importantly the correct CRD schema/version.

**Comment by shantpschauhan** [comment]
Thanks @brancz  .
Can you please refer any web link or any example Yaml file to refer for point 1 and 2. That would be great help.

**Comment by shantpschauhan** [comment]
We tried using rolebinding to bind clusterrole with service account with specifying the --namespace=xyz-namespace
and now able to deploy the operator and the prometheus servers.
But we are getting the below error in the operator logs (issue while using while using rolebinding but we do not get any issue when using clusterrolebinding).  want to get rid of this error. 
In our use case we do not want any node level metrics to fetch or monitor by prometheus. Our use case is application and prometheus are deployed in same namespace xyz and prometheus should monitor only those applications deployed in this xyz namespace.
Please suggest.
"level=error ts=2020-09-07T13:23:46.229907128Z caller=operator.go:647 component=prometheusoperator msg="syncing nodes into Endpoints object failed" err="listing nodes failed: nodes is forbidden: User \"system:serviceaccount:prometheus-run12:prometheus-operator\" cannot list resource \"nodes\" in API group \"\" at the cluster scope""

**Comment by brancz** [comment]
You will need to remove the `--kubelet-service` flag if you want to run the Prometheus Operator in this less privileged way.

**Comment by shantpschauhan** [comment]
Thanks @brancz  for the clarification.
will let you know in case any issue.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
