### ISSUE TITLE
kind/question

### ISSUE THREAD

**Issue by shantpschauhan** [prometheus-operator/prometheus-operator#3462]
**Question:**
We are using 0.41.1 prometheus-operator version.

How to configure a particular prometheus server image and its tag instead of default/latest image 
while deploying prometheus server using prometheus operator. 
We want to use our private registry to keep the images there and to use these images from private registry. 
I did not see any available reference yaml file or documentation.

**What did you do?**

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
You can use [`image` field in Prometheus Spec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec)

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
