### ISSUE TITLE
AdditionalServiceMonitors Support

### ISSUE THREAD

**Issue by Romiko** [prometheus-operator/prometheus-operator#3470]
Hi,

Please can we have AdditionalServiceMonitors Support? Reading the documentation, it is not clear how to register additional service monitors?

e.g.

`{{- if and .Values.prometheus.enabled .Values.prometheus.additionalServiceMonitors }}
apiVersion: v1
kind: List
items:
{{- range .Values.prometheus.additionalServiceMonitors }}
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: {{ .name }}
      namespace: {{ template "prometheus-operator.namespace" $ }}
      labels:
        app: {{ template "prometheus-operator.name" $ }}-prometheus
{{ include "prometheus-operator.labels" $ | indent 8 }}
        {{- if .additionalLabels }}
{{ toYaml .additionalLabels | indent 8 }}
        {{- end }}
    spec:
      endpoints:
{{ toYaml .endpoints | indent 8 }}
    {{- if .jobLabel }}
      jobLabel: {{ .jobLabel }}
    {{- end }}
    {{- if .namespaceSelector }}
      namespaceSelector:
{{ toYaml .namespaceSelector | indent 8 }}
    {{- end }}
      selector:
{{ toYaml .selector | indent 8 }}
    {{- if .targetLabels }}
      targetLabels:
{{ toYaml .targetLabels | indent 8 }}
    {{- end }}
{{- end }}
{{- end }}
`

**Comment by brancz** [comment]
The helm charts are neither used nor maintained by the prometheus-operator maintainers. Therefore we don't know the setup, so we're unlikely to be able to help you. I recommend creating an issue on the upstream helm charts repo where these helm charts are maintained.

FYI I know the helm charts are moving currently so the maintainers may be busy until the move is done.
