### ISSUE TITLE
During some installations (same machine) the 'Workload Charts' does not work

### ISSUE THREAD

**Issue by srinathganesh1** [prometheus-operator/prometheus-operator#3472]
**What happened?**
![grafana err](https://user-images.githubusercontent.com/11017158/92240815-d4e0b980-eeda-11ea-8b35-6988e7d25b11.png)

**Did you expect to see something different?** Workload chart that shows info

**How to reproduce it (as minimally and precisely as possible)**: During Random Installs this happens

**Environment** GKE

* Prometheus Operator version: Latest (adding my terraform script)
resource "helm_release" "foo" {
  name       = "foo-watch"
  chart      = "stable/prometheus-operator"
  timeout    = 3000
}

    `Insert image tag or Git SHA here`
Image:      quay.io/coreos/prometheus-operator:v0.38.1

* Kubernetes version information:

   Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.2", GitCommit:"fb7add51f767aae42655d39972210dc1c5dbd4b3", GitTreeState:"clean", BuildDate:"2020-06-01T22:20:10Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:   GKE

More Info: I did query inspector and got this
![grafana err 2](https://user-images.githubusercontent.com/11017158/92241384-c515a500-eedb-11ea-9f33-fa4ab8407503.png)

**Comment by srinathganesh1** [comment]
Any way to manually fix this?

**Comment by brancz** [comment]
The helm charts are neither used nor maintained by the prometheus-operator maintainers. Therefore we don't know the setup, so we're unlikely to be able to help you. I recommend creating an issue on the upstream helm charts repo where these helm charts are maintained.
