### ISSUE TITLE
additionalScrapeConfigs query

### ISSUE THREAD

**Issue by KR411-prog** [prometheus-operator/prometheus-operator#3479]
Prometheus Operator chart version: 9.3.1

Insert image tag or Git SHA here

quay.io/coreos/prometheus-operator:v0.38.1

Kubernetes version information:

kubectl version 1.15

Kubernetes cluster kind: EKS

Issue:

I am trying to add a new label called "teamname" to the metrics scraped on kube-state-metrics.So my objective is to add teamname as an additional label to the metrics scraped at kube-state-metrics so in the PrometheusRule we can set the specific team name on the label.

I tried below config and it shows the job with new label "teamname"  ...But its not updating the existing job name  "monitoring/prometheus-operator-kube-state-metrics/0".Instead it only creates new label for the new job "kube-state-metrics".If I use same job name in this config,it throws error that the job already exist.**So I am not sure how to update the existing job to update kube-state-metrics.**

```
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: kube-state-metrics
      honor_labels: true
      honor_timestamps: true
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - monitoring
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
        separator: ;
        regex: prometheus-operator
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
        separator: ;
        regex: kube-state-metrics
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        separator: ;
        regex: http
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
        separator: ;
        regex: Node;(.*)
        target_label: node
        replacement: ${1}
        action: replace
      - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
        separator: ;
        regex: Pod;(.*)
        target_label: pod
        replacement: ${1}
        action: replace
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: job
        replacement: ${1}
        action: replace
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
        separator: ;
        regex: (.+)
        target_label: job
        replacement: ${1}
        action: replace
      - separator: ;
        regex: (.*)
        target_label: endpoint
        replacement: http
        action: replace
      - separator: ;
        regex: (.*)
        target_label: teamname
        replacement: "myteam"
        action: replace
```
The job shows the new label "teamname".
![image](https://user-images.githubusercontent.com/14121261/92500847-9d139380-f1b2-11ea-8ebc-2dd2023f6447.png)

However its not updating the original job kube-state-metrics with new label "teamname" instead it creates a new job.**Also,I find that the other labels such as service,job,namespace are missing eventhogh they are defined in the relabel_config.**
![image](https://user-images.githubusercontent.com/14121261/92501222-190ddb80-f1b3-11ea-97f5-dd9722010c6e.png)

Also,**PROMQL command shows results for teamname label but not for {teamname="myteam",job="kube-state-metrics"}**
![image](https://user-images.githubusercontent.com/14121261/92501254-26c36100-f1b3-11ea-89b6-a4dd94f96dff.png)

Please let me know what am I missing here..
I just want to add a new label during scrapping for kube-state-metrics.

**Comment by simonpasquier** [comment]
you shouldn't need to use `additionalScrapeConfigs` for this. Lets continue the discussion on #3460.
