### ISSUE TITLE
Configuration of file_sd_config

### ISSUE THREAD

**Issue by Yalafeg** [prometheus-operator/prometheus-operator#3495]
Hello,

I am trying to configure the Prometheus operator by adding the option file_sd_config. For a specific reason, I need to update the targets by adding them to the targets.json file and not by listing them into the file values.yaml.

1- I tried to configure it as additionalScrapeconfigs (I followed the documentation provided) with no luck.
2- I added the "file_sd_config" option into the file values.yaml by specifying the name of the file targets.json (under node_exporter section), Prometheus configuration was updated accordingly, BUT, I am unable to manage the targets.json file. How can I call a local file from Prometheus? I tried to create a configMap with no luck. 

I am not sure if I am doing a wrong configuration, Please can you provide me with any help to use file_sd_config with Prometheus-operator, since I didn't find any topic related.

Regards,

**Comment by lilic** [comment]
@Yalafeg can you share the entire configuration, might be easier to understand what went wrong, thanks!

**Comment by paulfantom** [comment]
@Yalafeg friendly ping for the configuration :)

**Comment by Yalafeg** [comment]
Hello, Thank you for your reply, the problem is solved by adding file_sd_config to the values.yaml and  configmap. Thank you.

**Comment by dogfei** [comment]
I had this problem too, can you tell me how it was solved? Thank you. @Yalafeg

**Comment by Yalafeg** [comment]
Hello @dogfei,

I created a configmap that contains the targets.json file and I added the related configuration to additionalScrapeConfigs under values.yaml file.

Configmap configuration:
targets.json:
----
[
  {
    "labels": {
      "job": "servers"
    },
    "targets": [
      "",
      ""
    ]
  }
]

Values.yaml:
    additionalScrapeConfigs:
     - job_name: servers
       file_sd_configs:
        - files:
          - /prometheus/..../targets.json

Regards,

**Comment by bjarteb** [comment]
This is how we configured Amazon MSK for scraping 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-msk-targets
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
data:
  targets.json: |-
    [
      {
        "labels": {
          "job": "jmx"
        },
        "targets": [
          "b-1.mynode.c4.kafka.eu-west-1.amazonaws.com:11001",
          "b-2.mynode.c4.kafka.eu-west-1.amazonaws.com:11001",
          "b-3.mynode.c4.kafka.eu-west-1.amazonaws.com:11001"
        ]
      },
      {
        "labels": {
          "job": "node"
        },
        "targets": [
          "b-1.mynode.c4.kafka.eu-west-1.amazonaws.com:11002",
          "b-2.mynode.c4.kafka.eu-west-1.amazonaws.com:11002",
          "b-3.mynode.c4.kafka.eu-west-1.amazonaws.com:11002"
        ]
      }
    ]
```

**values.yaml**

```
    configMaps:
    - broker-msk-targets

```

```
    additionalScrapeConfigs:

      - job_name: 'broker'
        file_sd_configs:
        - files:
          - '/etc/prometheus/configmaps/broker-msk-targets/targets.json'
```
