### ISSUE TITLE
Missing tag for pkg/apis/monitoring Go module

### ISSUE THREAD

**Issue by tamalsaha** [prometheus-operator/prometheus-operator#3497]
Please apply a tag `pkg/apis/monitoring/v0.42.0` to the last release so that we can use the apis/v1/monitoring package without needing to use commit hash.

In case you wanted to see an example, here is a good one: https://github.com/cloudevents/sdk-go/releases

cc: @metalmatze

**Comment by lilic** [comment]
Thanks for your issue, sounds like a good idea but since we have not done this before, I added label feature request. @prometheus-operator/kube-prometheus-reviewers for 👍 👎 on this, it would essentially mean we need to do two releases from now on.

**Comment by simonpasquier** [comment]
Yes it should be done as @tamalsaha described and added to the release document.

**Comment by simonpasquier** [comment]
I've pushed [pkg/apis/monitoring/v0.42.0 ](https://github.com/prometheus-operator/prometheus-operator/releases/tag/pkg%2Fapis%2Fmonitoring%2Fv0.42.0).

**Comment by tamalsaha** [comment]
Thanks for the quick fix. It is working. Please close the issue when you are done.
