### ISSUE TITLE
Help setting up prometheus-operator with terraform + configuring apps

### ISSUE THREAD

**Issue by nimrodishi** [prometheus-operator/prometheus-operator#3498]
Hi!
I'm using terraform to set up a new eks. I've installed `prometheus-operator` on it:

```
resource "helm_release" "prometheus_operator" {
  name       = "prometheus-operator"
  namespace  = "monitoring"
  repository = "stable"
  chart      = "prometheus-operator"
  version    = "9.1.0"
}
```
Is there any more setup needed?

I'm having some trouble with the next step.
I have a helm chart for an app. How and what do I need to modify/add to the chart for `prometheus-operator` to monitor it?
Is it enough to annotate, or do I need to add extra Services/ServiceMonitors?
All guides I see are a bit complex for my level, so I can also use some pointers to simple guides to walk me through this.

**Comment by lilic** [comment]
You need a Service and ServiceMonitor per application (or even multiple depending on your app), or a PodMonitor. Getting started should be simple enough and still relevant, hope that helps :) https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
