### ISSUE TITLE
Add support for TargetLimit 

### ISSUE THREAD

**Issue by lilic** [prometheus-operator/prometheus-operator#3499]
Prometheus from [v2.21.0](https://github.com/prometheus/prometheus/releases/tag/v2.21.0) includes a new configuration option of adding a `TargetLimit` per scrape config. We should add support for this by adding a field in `ServiceMonitor` and `PodMonitor`.

But besides that, I am proposing to add a global limit of `TargetLimit`, similar to `SampleLimit` having an `EnforcedSampleLimit`, we could have an `EnforcedTargetLimit`. Both `EnforcedSampleLimit` and `EnforcedTargetLimit` could be used together so an admin can help control cardinality in a multi-tenant environment.

Thoughts @prometheus-operator/prometheus-operator-reviewers? 

See https://github.com/prometheus/prometheus/issues/7340 and https://github.com/prometheus/prometheus/pull/7554

**Comment by simonpasquier** [comment]
Definitely ok with this addition.

**Comment by brancz** [comment]
Very cool idea

**Comment by s-urbaniak** [comment]
let's implement, agreed :+1:

**Comment by metalmatze** [comment]
Let's do it! All for it!

**Comment by arghya88** [comment]
Is anyone working on it? If not I am interested.

**Comment by lilic** [comment]
Thanks! Let me know if something is not clear!
