### ISSUE TITLE
how to manage config-out as it is a empty volume

### ISSUE THREAD

**Issue by zffocussss** [prometheus-operator/prometheus-operator#3510]
**What did you do?**
I want to control the promethues configuration file by configmap

**Did you expect to see some different?**

**Environment**
AKS
* Prometheus Operator version:

 `quay.io/coreos/prometheus-operator:v0.32.0`

`
kubectl describe Prometheus prometheus-operator-prometheus -n monitoring
 - Name:         prometheus-operator-prometheus
-  Namespace:    monitoring
 - Labels:       app=prometheus-operator-prometheus
              chart=prometheus-operator-6.19.1
              heritage=Tiller
              release=prometheus-operator
`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"ba1ce4122d67b0f7399a41afbbd8a7258d22ecb8", GitTreeState:"clean", BuildDate:"2020-04-21T00:13:25Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

    AKS

* the key configuration(config-out is referred):
```
 Containers:
   prometheus:
    Image:      quay.io/prometheus/prometheus:v2.12.0
    Port:       9090/TCP
    Host Port:  0/TCP
    Args:
      --web.console.templates=/etc/prometheus/consoles
      --web.console.libraries=/etc/prometheus/console_libraries
      --config.file=/etc/prometheus/config_out/prometheus.env.yaml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention.time=10d
      --web.enable-lifecycle
      --storage.tsdb.no-lockfile
      --web.external-url=http://prometheus-operator-prometheus.monitoring:9090
      --web.route-prefix=/
    Liveness:     http-get http://:web/-/healthy delay=0s timeout=3s period=5s #success=1 #failure=6
    Readiness:    http-get http://:web/-/ready delay=0s timeout=3s period=5s #success=1 #failure=120
    Environment:  <none>
    Mounts:
      /etc/prometheus/config_out from config-out (ro)
      /etc/prometheus/rules/prometheus-prometheus-operator-prometheus-rulefiles-0 from prometheus-prometheus-operator-prometheus-rulefiles-0 (rw)
      /prometheus from prometheus-prometheus-operator-prometheus-db (rw)

  Volumes:
   config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-prometheus-operator-prometheus
    Optional:    false
   config-out:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
```

**Comment by zffocussss** [comment]
Is there a way to manage the promethues configuration by configmap or other ways?

**Comment by zffocussss** [comment]
how can I specify the config file? 
--config.file=/etc/prometheus/config_out/prometheus.env.yaml

**Comment by paulfantom** [comment]
No, there is no such way. You need to use custom resources and configuration is synthesized by prometheus-operator. All options are described in [api.md](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md).

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
