### ISSUE TITLE
prometheus-operator's component=prometheusoperator never syncs in versions of the prometheus-operator > 0.40.0

### ISSUE THREAD

**Issue by stefancocora** [prometheus-operator/prometheus-operator#3512]
**What happened?**
The component prometheusoperator of prometheus-op never syncs in versions of the prometheus-operator > 0.40.0
which results in the prometheus application never getting created.

```
3:level=info ts=2020-09-16T15:55:30.722087867Z caller=operator.go:512 component=prometheusoperator msg="connection established" cluster-version=v1.18.8
4:level=info ts=2020-09-16T15:55:30.72215494Z caller=operator.go:521 component=prometheusoperator msg="CRD API endpoints ready"
```

Prometheus-operator 0.40.0 works as expected, it creates the prometheus application from the prometheus CRD.

```
3:level=info ts=2020-09-16T15:51:55.02647549Z caller=operator.go:461 component=prometheusoperator msg="connection established" cluster-version=v1.18.8
7:level=info ts=2020-09-16T15:51:55.026533103Z caller=operator.go:470 component=prometheusoperator msg="CRD API endpoints ready"
10:level=info ts=2020-09-16T15:51:55.837088245Z caller=operator.go:407 component=prometheusoperator msg="successfully synced all caches"
11:level=warn ts=2020-09-16T15:51:55.837306434Z caller=operator.go:1206 component=prometheusoperator msg="prometheus key=monitoring/k8s, field spec.baseImage is deprecated, 'spec.image' field should be used instead"
12:level=info ts=2020-09-16T15:51:55.837393824Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
20:level=info ts=2020-09-16T15:51:56.728471558Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
21:level=info ts=2020-09-16T15:51:57.057555242Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
31:level=info ts=2020-09-16T15:52:11.979209098Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
32:level=info ts=2020-09-16T15:52:12.14051631Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
```

**Did you expect to see something different?**
I expect to see the prometheus application to be created by the prometheus-operator in versions > 0.40.0 as it is by version 0.40.0

**How to reproduce it (as minimally and precisely as possible)**:
I've setup a repo to reproduce and test the prometheus-operator that anyone can use - [https://github.com/stefancocora/prometheus-operator-test-4cef](https://github.com/stefancocora/prometheus-operator-test-4cef)

This test repo contains:
- kind k8s cluster v1.18.8 configuration
- prometheus-op manifests created using jsonnet as explained in the kube-prometheus docs
- captured prometheus-operator logs from 0.40.0 and 0.42.0

**Environment**

**Prometheus Operator version:**

Tested prometheus-operator versions:
- 0.40.0
- 0.41.0
- 0.41.1
- 0.42.0

**Kubernetes version information:**

Tested prometheus-operator on 2 types of kubernetes clusters:
- k8s cluster version v1.18.8 - kind
- k8s cluster version v1.18.8 - bare-metal

**Kubernetes cluster kind:**

- bare-metal (created with kubeadm)
- kind

**Manifests:**

See the test repo above.

**Prometheus Operator Logs:**

See the test repo above.

**Comment by paulfantom** [comment]
It seems that you have issues with RBAC when using v0.42, which is expected considering that kube-prometheus from `release-0.4`, [used by you](https://github.com/stefancocora/prometheus-operator-test-4cef/blob/master/jsonnetfile.json#L11), doesn't have everything needed by prometheus-operator v0.42.
Additionally according to [kube-prometheus compatibility matrix](https://github.com/prometheus-operator/kube-prometheus#kubernetes-compatibility-matrix), `release-0.4` is not compatible with k8s 1.18

**Comment by stefancocora** [comment]
Thank you for pointing out my mistake @paulfantom :+1: 

It would be very useful if the prometheus-operator would log what/where it is having issues with.
That would be an important time saver.

Did some tests with later versions of the kube-prometheus lib
- `release-0.6`
- `master`

**release-0.6**

Even if `release-0.6` is marked as compatible with k8s v1.18.x in the kube-prometheus docs it didn't create a prometheus server, not sure which part of RBAC isn't working.
- deps: https://github.com/stefancocora/prometheus-operator-test-4cef/blob/2e617977474663a9b2b74a9400da4c54c9162954/jsonnetfile.json#L11
- logs: https://github.com/stefancocora/prometheus-operator-test-4cef/blob/2e617977474663a9b2b74a9400da4c54c9162954/logs/prom-op-0-42-0-release06/prom-op.log

**master**

When using the master ref for the kube-prometheus lib the prometheus-operator is able to create a prometheus server
- deps: https://github.com/stefancocora/prometheus-operator-test-4cef/blob/61a80ce22ba7e47fa2ffbd6e9c6cdff3a6e494f1/jsonnetfile.json#L11
- logs: https://github.com/stefancocora/prometheus-operator-test-4cef/blob/61a80ce22ba7e47fa2ffbd6e9c6cdff3a6e494f1/logs/prom-op-0-42-0-master/prom-op.log

There isn't anything obvious in the yaml manifests generated by kube-prometheus `release-0.6` compared with the manifests generated by kube-prometheus `master` (RBAC related: small permission fix re probes)

Do you have any other tips ?

**Comment by MonicaMagoniCom** [comment]
I'm experiencing the same problem but I did not deploy with the project kube-prometheus-stack. Any news?
