### ISSUE TITLE
Monitor active passive URLs using Prometheus Operator

### ISSUE THREAD

**Issue by jaisegrg** [prometheus-operator/prometheus-operator#3518]
Hi @dlespiau 

I have a requirement to monitor active passive URLs  and send notification if  both are down.
I have setup blackbox exporter and  its sending notification if any URL is down. As its an active passive setup, i dont need to alert when any one is UP.

Is there a way to monitor shell script using Prometheus Operator to accomplish this or any other methods?

Can you please help on this?

**Comment by brancz** [comment]
Prometheus works by alerting from time-series, so you do want to collect metrics for both targets, but your alerting rule can express your desired behavior.

**Comment by jaisegrg** [comment]
@brancz ,

Below is the alert rule configured for the same,

- alert: EndpointDown
      annotations:
        summary: Endpoint {{ $labels.instance }} down
      expr: probe_success == 0
      for: 10s
      labels:
        severity: critical

But it will alert if any one endpoint is down, But i need to alert only when both the endpoints are down as its active passive URLs. Need to make sure any one is UP all time.

**Comment by brancz** [comment]
You can for example do:

```
sum(probe_success{...}) == 0
```

The way alerts work in Prometheus is that any "line" of the result in the `expr` produces an alert, which is why for your example any probe that failed triggered the alert.
