### ISSUE TITLE
prometheus_operator_build_info metric

### ISSUE THREAD

**Issue by midnightconman** [prometheus-operator/prometheus-operator#3527]
**What is missing?**
prometheus and alertmanager have an info metric that indicates the deployed version of the application... can we create a `prometheus_operator_build_info` metric that would follow suit?

Here is an example of the metric for prometheus:
```
prometheus_build_info{branch="HEAD",endpoint="web",env="tools",goversion="go1.13.10",job="prometheus",pod="prometheus-main-1",revision="18254838fbe25dcc732c950ae05f78ed4db1292c",version="2.17.2"}
```

**Why do we need it?**
Without this I have to query kubernetes to determine which version of the prometheus-operator I have deployed.

**Environment**

* Prometheus Operator version: mostly `v0.41.1` right now, some `v0.39.0`

**Anything else we need to know?**:

**Comment by lilic** [comment]
@midnightconman thanks for the feature request, do you mind just also explaining what your use cases are for this metric, just curious how you would use it, thanks!

**Comment by paulfantom** [comment]
This is a valid feature request and we should implement it. Such a metric is a common way to discover what versions of the stack components are running and what was used to compile them. We can later ask users to provide output of this metric in issue templates.

@midnightconman could you create a PR?

**Comment by midnightconman** [comment]
Excellent... I think I can get started on a PR for this. I have some concerns about how to integrate the versioning into the build system, but I'll reach out if that isn't clear.

Thank you! 😸

**Comment by midnightconman** [comment]
@lilic - for prometheus and thanos (they both have a build_info metric like this), we have a grafana dashboard with a table panel that shows the current deployed version. Since we have over 55 prometheus clusters, this helps to let us know if we missed any in our upgrades 😜

**Comment by paulfantom** [comment]
> I'll reach out if that isn't clear.

Feel free to ping me either on PR or on slack (same nick as on GitHub). I was recently refactoring our build system, so everything is fresh in my head :smile:

**Comment by mszostok** [comment]
Hi @midnightconman, are you still going to work on that? If not then, I'm interested to take care of that 😊

/cc @paulfantom

**Comment by midnightconman** [comment]
@mszostok Feel free to take over... I got this far and ran into some issues: https://github.com/prometheus-operator/prometheus-operator/pull/3566

**Comment by mszostok** [comment]
@midnightconman thanks for the quick response, so I will take it over 👍
