### ISSUE TITLE
Horizontal scaling in Prometheus Operator

### ISSUE THREAD

**Issue by jaisegrg** [prometheus-operator/prometheus-operator#3528]
Is horizontal scaling available in Prometheus Operator?
How it can deal with when the resource quota limit exceeds?

**Comment by coderanger** [comment]
Prometheus is, in general, not horizontally scalable in an automated manner. You can do it, but you need to manually think through how to shard your data and then how to federate it so it's still useful. Prometheus Operator makes it much easier to spin up, say, one instance per team or per customer but that's not HPA-style autoscaling that I think you are imagining.

**Comment by brancz** [comment]
FWIW there is some work in progress to that will make autosharding potentially possible: https://github.com/prometheus-operator/prometheus-operator/pull/3241

**Comment by jaisegrg** [comment]
@brancz ,

Thank you for the information!!

I have 4 AKS clusters running Prometheus Operator. What are the chances of getting OOM issue? Below is the current CPU/Memory usage  and number of sample ingestion per second. Also the custom service monitors are configured with scrape interval 15s.

Can you please give some suggestions on optimizing the environment?

NAME                                                 CPU(cores)   MEMORY(bytes)
prometheus-prometheus-prometheus-oper-prometheus-0   23m          1265Mi
rate(prometheus_tsdb_head_samples_appended_total[5m]) - 2994.3222222222225

NAME                                                 CPU(cores)   MEMORY(bytes)
prometheus-prometheus-prometheus-oper-prometheus-0   30m          723Mi
rate(prometheus_tsdb_head_samples_appended_total[5m])   - 2984


NAME                                                 CPU(cores)   MEMORY(bytes)
prometheus-prometheus-prometheus-oper-prometheus-0   96m          184Mi
rate(prometheus_tsdb_head_samples_appended_total[5m]) - 1657.9777777777779


NAME                                                 CPU(cores)   MEMORY(bytes)
prometheus-prometheus-prometheus-oper-prometheus-0   18m          533Mi
rate(prometheus_tsdb_head_samples_appended_total[5m]) - 2240.5823725273053
