### ISSUE TITLE
Upgrade version in k8s client 

### ISSUE THREAD

**Issue by skonto** [prometheus-operator/prometheus-operator#3529]
Is there any plan to upgrade the k8s client version used in the operator. It seems too old. We are currently using the service monitor api in this project: https://github.com/openshift-knative/serverless-operator
Version mismathc causes issues like:
```
github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/podmonitor.go:72:5: too many arguments in call to c.client.Get().Namespace(c.ns).Resource("podmonitors").Name(name).VersionedParams(&options, scheme.ParameterCodec).Do
	have (context.Context)
	want ()
```
Should I create a PR?

**Comment by paulfantom** [comment]
We are using [k8s client go in version 0.18.8](https://github.com/prometheus-operator/prometheus-operator/blob/master/go.mod#L33), do you need 0.19? If so - why?

**Comment by skonto** [comment]
Hi, because this call https://github.com/prometheus-operator/prometheus-operator/blob/f6aba9769f1a9c6c199731cc63d21f5f0c909d25/pkg/client/versioned/typed/monitoring/v1/alertmanager.go#L73 in later versions does not require a ctx.

**Comment by skonto** [comment]
We can close this it is actually the opposite the project I am working on has an old version: https://github.com/kubernetes/client-go/blob/kubernetes-1.13.4/rest/request.go.
