### ISSUE TITLE
Add Slack Receiver type to AlertmanagerConfig CRD

### ISSUE THREAD

**Issue by grdryn** [prometheus-operator/prometheus-operator#3535]
**What is missing?**

In #3451 we added the AlertmanagerConfig CRD, with just the PagerDuty receiver type, meaning that alert notifications can only be routed to PagerDuty. Alertmanager supports several other Receiver types, with this being one (other issues will be created for the others).

**Why do we need it?**

We should be able to define all of the Alertmanager receivers in AlertmanagerConfig CRs.

**Anything else we need to know?**:

The proposal for AlertmanagerConfig CRD is [here](https://docs.google.com/document/d/1aVVttvocop8zNezwrNFbHh_HKRW_fhJUZqhmrr8fGK0/edit#heading=h.5ua2yyj2xm4h), and it includes some information on this receiver type.

The Alertmanager config docs [here](https://prometheus.io/docs/alerting/latest/configuration/) show how this receiver is expected to be in the resulting Alertmanager config.

**Comment by omegas27** [comment]
I am up for implementing this one when https://github.com/prometheus-operator/prometheus-operator/pull/3451 is merged
