### ISSUE TITLE
Flaky e2e test: E2E tests (alertmanager) 

### ISSUE THREAD

**Issue by lilic** [prometheus-operator/prometheus-operator#3540]
We seem to have had a flaky test for some time, here are some examples I did not have a chance to look into it yet, but it does finish after some retries.

https://github.com/prometheus-operator/prometheus-operator/runs/1155429560?check_suite_focus=true 
>         --- FAIL: TestAllNS/x/AMClusterAfterRollingUpdate (81.08s)
https://github.com/prometheus-operator/prometheus-operator/runs/1153860258?check_suite_focus=true
>         --- FAIL: TestAllNS/x/AMZeroDowntimeRollingDeployment (184.50s)

Seems like there are a couple of flakes, not just one. Might be as easy as retrying or as difficult as rewriting tests.

**Comment by simonpasquier** [comment]
Another flake here: https://pipelines.actions.githubusercontent.com/vPMnvJjkGBteTBBeHIuBuscIAxYyVzD3ZDtsis3lp8F0MLY5xH/_apis/pipelines/1/runs/129/signedlogcontent/16?urlExpires=2020-10-01T11%3A52%3A28.2712240Z&urlSigningMethod=HMACV1&urlSignature=tceE7Uj9qlkXbu3QFekc5Bjz2TuYbCSlH6hUQbNijB0%3D

BTW the e2e tests still use the [Alertmanager API v1](https://github.com/prometheus-operator/prometheus-operator/blob/434f9f7e0b75cd1bcb444cf4532a53112074af4e/test/framework/alertmanager.go#L257) and this should be changed.

**Comment by lilic** [comment]
@simonpasquier 
> BTW the e2e tests still use the Alertmanager API v1 and this should be changed.

Would be a good first issue maybe, do you mind opening it?

**Comment by simonpasquier** [comment]
Instead of returning the error from `GetAlertmanagerStatus()`, we should save it in `pollErr` and return no error.

https://github.com/prometheus-operator/prometheus-operator/blob/434f9f7e0b75cd1bcb444cf4532a53112074af4e/test/framework/alertmanager.go#L218-L221

**Comment by arghya88** [comment]
I will work on this.
