### ISSUE TITLE
Getting "Failed to list: resourceVersion: Invalid value"

### ISSUE THREAD

**Issue by OleksandrMykytenko** [prometheus-operator/prometheus-operator#3542]
**What happened?**
Prometheus operator generates lot of logs related to issues with parsing values from K8S.

**Did you expect to see something different?**
I'm not using Thanos and Alertmanager objects right now so I'm not impacted by these errors however I do not think that it's good sign.
**How to reproduce it (as minimally and precisely as possible)**:

**Environment**
AWS EKS cluster, version 1.17.
* Prometheus Operator version:
```
Pod Template:
  Labels:           k8s-app=prometheus-operator
  Service Account:  prometheus-operator
  Containers:
   prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.40.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
      --namespaces=monitoring,pilot,kube-system,dev
    Limits:
      cpu:     200m
      memory:  100Mi
    Requests:
      cpu:        100m
      memory:     50Mi
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>

```

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

AWS EKS

* Manifests:

* Prometheus Operator Logs:

```
E0924 11:14:57.444699       1 reflector.go:382] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:482: Failed to watch *v1.Secret: expected resource version to have 4 parts to match the number of ListerWatchers
E0924 11:15:14.444584       1 reflector.go:382] github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:217: Failed to watch *v1.StatefulSet: expected resource version to have 4 parts to match the number of ListerWatchers
E0924 11:15:34.437150       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:216: Failed to list *v1.Alertmanager: resourceVersion: Invalid value: "41998999/41998999/41998999/41998999": strconv.ParseUint: parsing "41998999/41998999/41998999/41998999": invalid syntax
E0924 11:16:06.822307       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:216: Failed to list *v1.Alertmanager: resourceVersion: Invalid value: "41998999/41998999/41998999/41998999": strconv.ParseUint: parsing "41998999/41998999/41998999/41998999": invalid syntax
E0924 11:16:35.443366       1 reflector.go:382] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:481: Failed to watch *v1.ConfigMap: expected resource version to have 4 parts to match the number of ListerWatchers
E0924 11:16:38.598088       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:216: Failed to list *v1.Alertmanager: resourceVersion: Invalid value: "41998999/41998999/41998999/41998999": strconv.ParseUint: parsing "41998999/41998999/41998999/41998999": invalid syntax
E0924 11:16:39.443122       1 reflector.go:382] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:318: Failed to watch *v1.StatefulSet: expected resource version to have 4 parts to match the number of ListerWatchers
E0924 11:17:24.833158       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:216: Failed to list *v1.Alertmanager: resourceVersion: Invalid value: "41998999/41998999/41998999/41998999": strconv.ParseUint: parsing "41998999/41998999/41998999/41998999": invalid syntax
E0924 11:17:47.442492       1 reflector.go:382] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:483: Failed to watch *v1.StatefulSet: expected resource version to have 4 parts to match the number of ListerWatchers
E0924 11:18:02.455326       1 reflector.go:178] github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:216: Failed to list *v1.Alertmanager: resourceVersion: Invalid value: "41998999/41998999/41998999/41998999": strconv.ParseUint: parsing "41998999/41998999/41998999/41998999": invalid syntax
E0924 11:18:32.445353       1 reflector.go:382] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:312: Failed to watch *v1.ConfigMap: expected resource version to have 4 parts to match the number of ListerWatchers
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
Ah can you try with v0.42.0? it's most certainly fixed by https://github.com/prometheus-operator/prometheus-operator/pull/3440.

**Comment by OleksandrMykytenko** [comment]
OK, upgraded to `0.42.0` and the issue is gone for now. However, i started seeing new one related to Probe feature introduced in `0.41` - `E0924 12:47:02.555086       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Probe: the server could not find the requested resource (get probes.monitoring.coreos.com)` ... RBAC has been updated to allow Prometheus operator all access to probes

**Comment by OleksandrMykytenko** [comment]
Do I need to create probe CRD by myself via applying https://github.com/prometheus-operator/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml or it should be provisioned by operator itself somehow?

**Comment by OleksandrMykytenko** [comment]
created CRD manually using example file. topic can be closed

**Comment by lilic** [comment]
@OleksandrMykytenko yes since a few releases ago you need to manage your own CRDs, the operator does not do that for you anymore.
