### ISSUE TITLE
Prometheus Operator OOM issues

### ISSUE THREAD

**Issue by jaisegrg** [prometheus-operator/prometheus-operator#3547]
We have 4 AKS clusters running Prometheus Operator currently in staging which is going to be in Production. What are the chances of getting OOM issue? Below is the current CPU/Memory usage  and number of sample ingestion per second for each cluster. Also the custom service monitors are configured with scrape interval 15s.

Can you please give some suggestions on optimizing the environment to avoid Out Of Memory issues?

NAME                                                 CPU(cores)   MEMORY(bytes)
prometheus-prometheus-prometheus-oper-prometheus-0   23m          1265Mi
rate(prometheus_tsdb_head_samples_appended_total[5m]) - 2994.3222222222225

NAME                                                 CPU(cores)   MEMORY(bytes)
prometheus-prometheus-prometheus-oper-prometheus-0   30m          723Mi
rate(prometheus_tsdb_head_samples_appended_total[5m])   - 2984

NAME                                                 CPU(cores)   MEMORY(bytes)
prometheus-prometheus-prometheus-oper-prometheus-0   96m          184Mi
rate(prometheus_tsdb_head_samples_appended_total[5m]) - 1657.9777777777779

NAME                                                 CPU(cores)   MEMORY(bytes)
prometheus-prometheus-prometheus-oper-prometheus-0   18m          533Mi
rate(prometheus_tsdb_head_samples_appended_total[5m]) - 2240.5823725273053

**Comment by jaisegrg** [comment]
@brancz ,

Can you please advise on this?

**Comment by simonpasquier** [comment]
As an outsider, iIt's hard to tell exactly how much RAM you'd need because it depends on many factors: number of metrics ingested, labels churn, rules evaluation and user queries.
Check https://www.robustperception.io/how-much-ram-does-prometheus-2-x-need-for-cardinality-and-ingestion and https://www.robustperception.io/why-does-prometheus-use-so-much-ram if you haven't already.
One approach would be to run without limits (or very large limits), measure what you get and adjust the limits accordingly.

**Comment by matthyx** [comment]
Sorry, but the OOM issue concerns the operator of the scraping pods?

We are also witnessing a huge memory usage on the operator, which doesn't make much sense because I thought this one only processes the CRD... not the actual metrics. Am I wrong?

**Comment by simonpasquier** [comment]
> We are also witnessing a huge memory usage on the operator, which doesn't make much sense because I thought this one only processes the CRD... not the actual metrics. Am I wrong?

No you're correct. Prometheus operator memory shouldn't be tied to the number of targets or samples. Can you quantify the increase?

**Comment by matthyx** [comment]
@simonpasquier thanks for coming back...
I have found the culprit: secrets... we have a huge amount of secrets in our cluster (around 14k) which overloads the cache as described in https://github.com/prometheus-operator/prometheus-operator/pull/3355
