### ISSUE TITLE
Where Prometheus Operator keeps data?

### ISSUE THREAD

**Issue by Mehmoodhassan** [prometheus-operator/prometheus-operator#3548]
I installed prometheus operator using helm in kubernetes and its working fine and displaying metrics on prometheus UI but i want all metrics in a file instead of UI, please tell me where promethus operator stores data in which directory.

**Comment by coderanger** [comment]
You can configure the storage used for Prometheus: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/storage.md

By default it uses a temporary emptyDir as this is universally available and allows quick testing of the operator. Persistent storage is strongly recommended unless you reeeeeally know what you're doing and have made your own arrangements for long-term storage.
