### ISSUE TITLE
End-to-end tests should use the Alertmanager API v2

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#3557]
the e2e tests still use the [Alertmanager API v1](https://github.com/prometheus-operator/prometheus-operator/blob/434f9f7e0b75cd1bcb444cf4532a53112074af4e/test/framework/alertmanager.go#L257) and this should be changed to the API v2 instead.

Discovered while looking at https://github.com/prometheus-operator/prometheus-operator/issues/3540.

**Comment by arghya88** [comment]
I can work on it

**Comment by simonpasquier** [comment]
Nice! Ping me if you've got questions :)
