### ISSUE TITLE
Prometheus operator secret length too long: must have at most 1048576 characters

### ISSUE THREAD

**Issue by kousik93** [prometheus-operator/prometheus-operator#3591]
**Environment:**
Prometheus Operator: Forked from v0.23
Prometheus: v2.12.0

**Problem**
Prometheus Operator compiles all the config required for prometheus into a secret. 
In our environment, we have a lot of namespaces, servicemonitors, promethuesrules.

We have hit a limitation with how long this secret can be. The error log from Prometheus Operator is:
```
level=info ts=2020-10-14T20:48:56.975635203Z caller=operator.go:911 component=prometheusoperator msg="sync prometheus" key=prometheus-operator/prometheus-operator

E1014 20:48:59.454086       1 operator.go:816] Sync "prometheus-operator/prometheus-operator" failed: creating config failed: Secret "prometheus-prometheus-operator" is invalid: data: Too long: must have at most 1048576 characters
```

Im not sure if this is a limitation from prometheus or Kubernetes.
Splitting this config up into multiple secrets might help here.

**Comment by simonpasquier** [comment]
Can you retry with the latest version of the operator? The configuration bits are gzipped now and in practice it's very unlikely that the compressed version exceeds the Kubernetes limit.

**Comment by kousik93** [comment]
Ah. Thanks a lot. This will definitely help. 
I will try it out. I guess, this can be closed then.
