### ISSUE TITLE
Support for Pod Topology Spread Constraints for Prometheus and Alertmanager CRDs

### ISSUE THREAD

**Issue by AshleyDumaine** [prometheus-operator/prometheus-operator#3595]
**What is missing?**
The Prometheus and Alertmanager CRDs support Pod affinities and anti-affinities as well as Node affinities, but not `topologySpreadConstraints`, which is a new feature (see https://kubernetes.io/blog/2020/05/introducing-podtopologyspread/ and https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/)

**Why do we need it?**
Having an even Pod spread across zones/regions for the StatefulSets generated by the Prometheus and Alertmanager CRDs would be useful for HA setups and is more flexible than using something like Pod anti-affinities with `topology.kubernetes.io/zone` for the `topologyKey`.

**Comment by brancz** [comment]
This makes sense. Would you like to contribute this feature @AshleyDumaine ?

**Comment by AshleyDumaine** [comment]
Sure, sounds good to me!
