### ISSUE TITLE
HA problem with pvc and pv not bound for replica 2

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus-operator/prometheus-operator#3602]
Hi for the sake of high availability I change the replica count to 2 if I use replica as 1 pvc and pv went to bound and instance is up and running fine where as if I use replica as 2 another one is creating fine but the pvc and pv is not coming to bound state it shows like two more claims are assigned to pv not acceptable.
How to solve that make the replica as 2 or more High availability with persistent

**Comment by coderanger** [comment]
That is a question for your cluster admins. The operator just creates a StatefulSet with a VolumeClaimTemplate. If your PV dynamic provisioning isn't working, that would be a local issue.

**Comment by mohanagandlla** [comment]
No, I was used the static allocation

**Comment by coderanger** [comment]
Then that's even more of a local issue, you'll need to ensure the statically created PVs match the requested PVCs exactly or bind them manually.

**Comment by mohanagandlla** [comment]
I did the same but it is an error throwing like "Two claims are bound to the same volume, this one is bound incorrectly"
