### ISSUE TITLE
makeing the replicas as 2 to get HA (manual storage provisioning persistent)

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus-operator/prometheus-operator#3603]
**What is missing?**
I have created the Prometheus instance replicas as 2 along with manual storage provisioning the first replica's PVC is bound successfully to PV and the second one is still in a pending state.
It is showing an error like "Two claims are bound to the same volume, this one is bound incorrectly"
**Why do we need it?**
for the sake of HA
**Environment**
Kubernetes 
* Prometheus Operator version:
latest one

**Comment by coderanger** [comment]
Hi there, I closed your last ticket with the same explanation. PV binding is up to your cluster administrators to debug. We cannot help with that. Please contact your admins.
