### ISSUE TITLE
How to monitor Jobs with the Prometheus Operator ?

### ISSUE THREAD

**Issue by okouyad** [prometheus-operator/prometheus-operator#3609]
I have a need to monitor some jobs in Kubernetes. 

I see two different ways to monitor **PodMonitor vs Service Monitor.** 

What would you recommend when it comes to monitoring jobs ?

**Comment by coderanger** [comment]
Jobs are definitionally transient so you would usually have to run a Push Gateway so things persist long enough to be scraped. It depends on how long your jobs run for though.

**Comment by okouyad** [comment]
My Jobs, are long running task. To keep short, my jobs, load entire tables from DBs, if not Entire DB into Kafka.

**Comment by okouyad** [comment]
Push Gateway ???

**Comment by okouyad** [comment]
Oh found what it is. did not know. Well sounds like for long running job that are kicked off manually like we do, a pull based model rather than a pushGateway is better ? Agreed?

**Comment by coderanger** [comment]
As long as you don't mind potentially losing the final scrapeInterval's worth of data as the job terminates, then a PodMonitor is fine. You wouldn't usually create a Service for Job pods. If you don't want to lose that last few seconds of data, you need a push gateway which is setup like a normal Deployment.

**Comment by okouyad** [comment]
The website says that you need to delete de data manually ?

**Comment by okouyad** [comment]
Anyway thank you to put in on the path Very helpfull
