### ISSUE TITLE
Manage Loki

### ISSUE THREAD

**Issue by ibotty** [prometheus-operator/prometheus-operator#3610]
[Loki](https://grafana.com/oss/loki/) is Grafana's log collection that is heavily inspired by prometheus.

Because it uses the same concepts as Prometheus' service discovery it might make sense to configure it similarly or maybe even with the same kubernetes object.

I might be able to contribute, but I don't feel qualified to propose an API.

**Comment by coderanger** [comment]
-1. Loki takes some ideas and storage tech from Prometheus and Cortex but running it has no relation to running Prometheus. There's no overlap on the operator tooling side.

**Comment by paulfantom** [comment]
I agree with @coderanger prometheus-operator shouldn't manage loki. Possibly another operator would be good for this task and it seems work for such operator was already started in https://github.com/giantswarm/loki-operator

**Comment by brancz** [comment]
I do want to note, configuring Loki collection similar to Prometheus' collection can be quite fruitful, and I would encourage you to do that. Essentially try to have the same labels on your Loki logs as you do on your Prometheus targets.

**Comment by midnightconman** [comment]
I use the prometheus-operator heavily for managing prometheus and thanos in my environment. I was just trying to use the prometheus-operator to allow me to easily add `prometheusRules` to a loki ruler (as the types are very similar -- logql just has additional characters in the `expr` field). This didn't work though, as the prometheus-operator complains about the extra characters (in this case `|`).

What are peoples thoughts around this? Maybe I can add logic to not lint certain prometheusRules by label selector or something?
