### ISSUE TITLE
Emit Kubernetes events when the operator recognizes invalid resources

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#3611]
**What is missing?**

The operator will reject resources that would trigger invalid configurations of Prometheus, Alertmanager and Thanos Ruler. While we already have [metrics](https://github.com/prometheus-operator/prometheus-operator/blob/2fda6f185b0f83b4aa09e47b6beffcdc2ca40739/pkg/operator/operator.go#L40-L45) in place, it would be useful to emit Kubernetes events.

**Why do we need it?**

It would be easier for the operator admins to troubleshoot rather than looking at the operator's logs.

Reported by @brancz on [Slack](https://kubernetes.slack.com/archives/C01B03QCSMN/p1603267460027600).

**Comment by arghya88** [comment]
I am interested to work on this

**Comment by simonpasquier** [comment]
sure go ahead. @dgrisonnet might be able to help you here.

**Comment by arghya88** [comment]
Is there an example operatorrs that I can look at?

**Comment by dgrisonnet** [comment]
you can look at the kubernetes sample-controller: https://github.com/kubernetes/sample-controller.

**Comment by nrchakradhar** [comment]
@arghya88 https://book-v1.book.kubebuilder.io/beyond_basics/creating_events.html can be helpful.
I guess the events have to be fired on the operator Deployment.

Multiple examples are available:
https://github.com/kubeflow/tf-operator/blob/master/pkg/controller.v1/tensorflow/status.go
https://github.com/argoproj/argo/blob/master/workflow/controller/controller.go

The places where to create the events could be a little more involved than the sample-controller.

**Comment by nrchakradhar** [comment]
@arghya88 Gentle ping to check if you are still working on this?

**Comment by FUSAKLA** [comment]
:wave: Hi, if not picked by anyone yet, I'll give it a shot.
It would be highly useful for our users when debugging.

**Comment by FUSAKLA** [comment]
So I started working on this, would appreciate some feedback there @simonpasquier or anyone else interested :pray:

**Comment by rexagod** [comment]
@FUSAKLA I assumed no one was working on this anymore. 😓 LMK if there's anything I can help with (I'll take a look at #5567)! Cheers!

**Comment by FUSAKLA** [comment]
Hi, I have it on top of my TODO list, but unfortunately currently blocked by investigating some incidents.
I hope that I'll get to it soon. Thanks for looking into it!

**Comment by rexagod** [comment]
@FUSAKLA Are you working on this?

**Comment by FUSAKLA** [comment]
Hi,  I'm deeply sorry for blocking this 🫤
I'd love to work on it but struggle to find a free time. So if anyone has the bandwidth, please feel free to finish this and I'd be grateful.
