### ISSUE TITLE
 When can vmoperator be added

### ISSUE THREAD

**Issue by QAQ-rookie** [prometheus-operator/prometheus-operator#3615]
I want to monitor vm nodes in my cluster, but I don't want  use to maintain it manually cluster endpoint, Is there any other way. 
can you provide vmoperator. thanks

prometheus in kubernetes cluster, vm in aliyun.
my Prometheus Operator version:   prometheus-operator:v0.36.0

**Comment by coderanger** [comment]
I don't really understand this question, but I can say fairly certainly that this is not a thing that we will implement. If you are talking about Prometheus' node_exporter, you run that using a DaemonSet, Service, and ServiceMonitor. Usually at least.
