### ISSUE TITLE
Scrape commit failed

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus-operator/prometheus-operator#3629]
Hi i am facing the error like Scrape commit failed
the logs msg is 
level=error ts=2020-10-28T07:16:56.185Z caller=scrape.go:1076 component="scrape manager" scrape_pool=monitoring-pro/prometheus-kubelet/1 target=https://xxxxxxxx:10250/metrics/cadvisor msg="Scrape commit failed" err="write to WAL: log samples: write /prometheus/wal/00000012: stale NFS file handle"
continuously getting the same error

and more over may i know the command to restart the prometheus server 
i used 
kill -HUP 1
kill _SIGHUP 1
these wont work for me  

now i have removed the target again that issue showing but now it is showing on node exporter

**Comment by simonpasquier** [comment]
NFS storage isn't supported by Prometheus, see the [upstream documentation](https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects).

**Comment by mohanagandlla** [comment]
Ya thank you I got it and may I know the command to restart the server without deleting the pod I have tried the above one not working

**Comment by simonpasquier** [comment]
`kill 1` should do it.

**Comment by mohanagandlla** [comment]
ya ok but it is restarting the container

**Comment by simonpasquier** [comment]
`kill -SIGHUP 1` will reload the configuration. That may or may not help with your issue though...

Since it's a problem with Prometheus and not the operator itself, I'm closing it for now.
