### ISSUE TITLE
meta.json no such file in directory

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus-operator/prometheus-operator#3634]
**What did you do?**
I have attached the mapr to the Prometheus on two instances at one instance it is working good coming to second one its not creating the meta.json file finally throwing an error 
This is the status of mount
posix                  1.0T     71.1G    952.9G   7% /prometheus
**What did you expect to see?**
wal corruption need to resolve
**What did you see instead? Under which circumstances?**

**Environment**

* Prometheus version:

	insert output of `prometheus --version` 2.22.0

* Logs:
```
level=error ts=2020-10-29T03:29:33.202Z caller=main.go:764 err="opening storage failed: block dir: \"/prometheus/01ENRA5TM45DGMR9PG0NF5R3M6\": open /prometheus/01ENRA5TM45DGMR9PG0NF5R3M6/meta.json: no such file or directory"
```
I have checked on all compacts there is no JSON file

**Comment by nrchakradhar** [comment]
Shouldn't this issue be raised with prometheus? I doubt if operator has any role here.

**Comment by simonpasquier** [comment]
Exactly it's an issue with Prometheus or more probably with your storage system.
