### ISSUE TITLE
Config loader is failing with below error

### ISSUE THREAD

**Issue by hussainsaify** [prometheus-operator/prometheus-operator#3644]
Hi Team,

I have installed kube-prometheus-stack chart with version 11.0.0 that is using prometheus-config-reloader with version 0.43.0. After installation the container is failing with below error

Kubernets version- 1.18(AWS EKS)

heus-kube-prometheus-kube-prome-prometheus-rulefiles-0 --reload-url=http://127.0.0.1:9090/-/reload
level=info ts=2020-11-03T13:18:13.940765141Z caller=main.go:147 msg="Starting prometheus-config-reloader" version="(version=0.43.0, branch=refs/tags/v0.43.0, revision=633ea519b2ce86396f6e006f7fd967c04bc45bda)"
level=info ts=2020-11-03T13:18:13.940825651Z caller=main.go:148 build_context="(go=go1.14.10, user=simonpasquier, date=20201027-10:39:39)"
**expand environment variables: found reference to unset environment variable "NAMESPACE"**

Can you please help me with this issue? Please let me know in case you need any other information.

Thanks,
Hussain

**Comment by simonpasquier** [comment]
Can you check the (unzipped) configuration from `/etc/prometheus/config/prometheus.yaml.gz`? There seems to be a `$(NAMESPACE)` in the generated configuration that the prometheus-config-reloader tries to expand.

**Comment by hussainsaify** [comment]
Looks like it is looking for NAMESPACE to be supplied as an environment variable but I am not sure how it was working earlier.

**Comment by simonpasquier** [comment]
I don't think anything as changed in that regard: `prometheus-config-reloader` always tried to expand `$(...)` strings in the configuration file.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
