### ISSUE TITLE
Old version of Prometheus

### ISSUE THREAD

**Issue by albertyfwu** [prometheus-operator/prometheus-operator#3656]
Am I misunderstanding this? I was trying to use `ExternalLabels` in my AlertManager config, and it did not work.

I found https://github.com/prometheus-operator/prometheus-operator/issues/2774, which mentions that 2.10.0 has it implemented.

However, in the `go.mod` file below, I see that prometheus is on v1.8.2. Isn't this an ancient version?

https://github.com/prometheus-operator/prometheus-operator/blob/ce5107a42150654dad09de7d5b7529704d98208b/go.mod#L26

**Comment by albertyfwu** [comment]
Actually, I'm a bit confused.

I just switched from `ExternalLabels` to `CommonLabels` in AlertManager, and they work again now.

**Comment by simonpasquier** [comment]
go.mod can't use the "real" tag because Prometheus doesn't respect Go modules semver. But the last part of the reference (e.g. `0a7fdd3b7696`) provides the commit SHA.
