### ISSUE TITLE
Prometheus metric `http_requests_total` only reports for resources in monitoring namespace

### ISSUE THREAD

**Issue by Tejeev** [prometheus-operator/prometheus-operator#3662]
**What did you do?**
Prometheus is deployed as part of Rancher Monitoring 

**What did you expect to see?**
When I execute 'http_requests_total', it should return http requests stats of pods users deployed.

What did you see instead? Under which circumstances?
It only returned data for resources in the Monitoring namespace.  User deployments are omitted

Do I have to expose http_requests_total from my applications (pods) using the Prometheus client library? Or is there any other way around?

**Environment**
Azure kubernetes Service (aks)

Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Tejeev** [comment]
I believe brancz attempted to address this in https://github.com/prometheus-operator/prometheus-operator/issues/763 but his updates were not clear to me.

**Comment by simonpasquier** [comment]
Do you have configured service/pod monitors to scrape metrics from your application? Is prometheus configured to monitor other namespaces than `monitoring`?

> Prometheus is deployed as part of Rancher Monitoring

The question would probably better answered by the Rancher project.
