### ISSUE TITLE
Slack receivers are not being populated using managed secret for alertmanager

### ISSUE THREAD

**Issue by leandrocostam** [prometheus-operator/prometheus-operator#3665]
**What happened?**
Following the steps described [here](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/alerting.md#manually-managed-secret), you should be able to define alertmanager config using managed secret. When adding receivers of slack_config type, operator is not creating it properly. It's working with webhook and pagerduty, but not using slack_config. I'm able to see the correct information in my managed secret, but the `<mysecret-name>-generated` secret does not have slack_config receivers.

**Did you expect to see something different?**
I want to see slack receivers properly populated by operator.

**How to reproduce it (as minimally and precisely as possible)**:
Create alertmanager config file `alertmanager.yaml`:

```yaml
global:
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'myslack'
receivers:
- name: 'myslack'
  slack_configs:
  - api_url: http://slack.example.com
    send_resolved: true
```

Create  secret:

```bash
kubectl create secret generic alertmanager-example --from-file=alertmanager.yaml
```

Check managed secret:

```bash
kubectl get secret alertmanager-example -o=jsonpath="{.data.alertmanager\.yaml}" -n monitoring | base64 -d
global:
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'myslack'
receivers:
- name: 'myslack'
  slack_configs:
  - api_url: http://slack.example.com
    send_resolved: true
```

Check generated secret:
```bash
kubectl get secret alertmanager-example-generated -o=jsonpath="{.data.alertmanager\.yaml}" -n monitoring | base64 -d
global:
  resolve_timeout: 5m
route:
  receiver: myslack
  group_by:
  - job
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
- name: myslack
templates: []
```

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.43.2`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-a84824", GitCommit:"a84824a1c7b79853d0c57143ea42c9de1788dbba", GitTreeState:"clean", BuildDate:"2020-08-05T01:08:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

    `eks`

* Manifests:

     `Already attached.`

* Prometheus Operator Logs:

     `No error logs from operator.`

**Anything else we need to know?**:

No.

**Comment by simonpasquier** [comment]
Ah! When `AlertmanagerConfigSelector` is not nil, the operator will only render receivers that are supported by the `AlertmanagerConfig` CRD (e.g. OpsGenie, PagerDuty and webhook). Receivers of other types are discarded without notice unfortunately. It should at least have been called out in the docs, sorry for this.

**Comment by simonpasquier** [comment]
The fix would be to extend the internal [`receiver`](https://github.com/prometheus-operator/prometheus-operator/blob/dd1e5214da02a9f4a3c3637b76e56fb3a54303e6/pkg/alertmanager/amcfg.go#L97-L104) struct with all receiver configs supported by Alertmanager.

**Comment by leandrocostam** [comment]
@simonpasquier Yes, after removing `AlertmanagerConfigSelector` it worked just fine. Thank your for troubleshooting the issue.

**Comment by metroshica** [comment]
Looks like support for the Slack receiver in the AlertmanagerConfig CRD was merged in recently https://github.com/prometheus-operator/prometheus-operator/pull/3618 so I expect this should be resolved with the next release.

**Comment by simonpasquier** [comment]
@metroshica yes but the issue exists nonetheless for other receiver types like Pushover for instance.
