### ISSUE TITLE
docs: user-guide for linting needs an update

### ISSUE THREAD

**Issue by barakplasma** [prometheus-operator/prometheus-operator#3667]
In the documentation [user-guide for linting](https://github.com/prometheus-operator/prometheus-operator/blob/ce0f2cb240f8503020c92e063300e83fb35ef33d/Documentation/user-guides/linting.md#example), the example script's docker command is broken.

It seems like the docker command broke since the image was changed.

The following command does work, and I would be happy to modify the script to improve the documentation. (where `app-base/prometheus.yaml` is an example file from my project)
```sh
$ docker run -t --rm --volume "$(pwd):/data:ro" quay.io/coreos/po-tooling \
/go/bin/po-lint /data/app-base/prometheus.yaml
```

**Comment by brancz** [comment]
Please feel free to fix the docs! :)

**Comment by lilic** [comment]
Seems like the PR was merged for this. Closing this issue, if a new one shows up lets open a new one. Thanks for issue and contribution @barakplasma!
