### ISSUE TITLE
Custom terminationGracePeriodSeconds for Operator

### ISSUE THREAD

**Issue by diyavicky** [prometheus-operator/prometheus-operator#3673]
Team,

In our private cloud infra, we have limitation on terminationGracePeriodSeconds(<180) seconds.
Also we have explicitly specified this parameter in Operator Deployment manifest like below but still prometheus CRD creations is getting failed.

**terminationGracePeriodSeconds: 60**

Error:
 Warning  FailedCreate  12s (x13 over 32s)  statefulset-controller  create Pod prometheus-prometheus-resource-0 in StatefulSet prometheus-prometheus-resource failed error: admission webhook "opa.xxxcloud.io" denied the request: priorityClassName p3 requires a terminationGracePeriodSeconds <= 180

Is there an option to fix this issue?

**Comment by diyavicky** [comment]
Can someone advise on this?

Thanks!

**Comment by vsliouniaev** [comment]
I believe that you can override the configuration of an individual container by using the `spec.containers` field as documented here: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec

**Comment by diyavicky** [comment]
@vsliouniaev @simonpasquier Could you please advise the variable that can used to specify custom terminationGracePeriodSeconds? In the above document am not seeing anything specific to this.

Thanks!

**Comment by diyavicky** [comment]
@vsliouniaev @simonpasquier As of now this works only with the default terminationGracePeriodSeconds: 600 seconds. As our cluster is managed, we can allocate max of 180 seconds only. In this scenario prometheus CRD creation is broken.

Please advise on this!

Thanks!

**Comment by simonpasquier** [comment]
@vsliouniaev AFAICT `terminationGracePeriodSeconds` works at the pod level so `spec.containers` won't help here.

Closed in favor of #3433 where the discussion can continue. It looks like you're hitting the same issue as described in https://github.com/prometheus-operator/prometheus-operator/issues/3278.
