### ISSUE TITLE
AlertmanagerConfig CRD Error

### ISSUE THREAD

**Issue by diyavicky** [prometheus-operator/prometheus-operator#3674]
Team,

We are using latest version of prometheus operator and when we try to apply AlertmanagerConfig CRD seeign the below error.
Could you please advise what's causing this issue?

Thanks!

**error: unable to recognize "01_alertManager_config.yml": no matches for kind "AlertmanagerConfig" in version "monitoring.coreos.com/v1alpha1"**

> ---
> apiVersion: monitoring.coreos.com/v1alpha1
> kind: AlertmanagerConfig
> metadata:
>   name: alertmanager-config
>   labels:
>     alertmanagerConfig: notification-channel
> spec:
>   route:
>     groupBy: ['job']
>     groupWait: 30s
>     groupInterval: 5m
>     repeatInterval: 15m
>     receiver: 'slack-notify'
>   receivers:
>     - name: slack-notify
>       slack_configs:
>         - api_url: 'https://hooks.slack.com/services/xxxx'
>           username: 'Alertmanager'
>           channel: '#xxxxx'

**Comment by simonpasquier** [comment]
The `AlertmanagerConfig` CRD is probably missing from the cluster. You can check its presence with `kubectl get crd alertmanagerconfigs.monitoring.coreos.com`.

**Comment by diyavicky** [comment]
@simonpasquier ya its missing in the cluster. But as operator is already deployed with latest version it should have the CRD created right?

Please clarify on this.

Thanks!

**Comment by diyavicky** [comment]
Seeing only the below CRDs for coreos
➜  ~ kubectl get crd | grep -i monit
alertmanagers.monitoring.coreos.com                                2020-04-10T20:25:37Z
podmonitors.monitoring.coreos.com                                  2020-04-10T20:25:37Z
probes.monitoring.coreos.com                                       2020-09-03T23:48:24Z
prometheuses.monitoring.coreos.com                                 2020-04-10T20:25:38Z
prometheusrules.monitoring.coreos.com                              2020-04-10T20:25:38Z
servicemonitors.monitoring.coreos.com                              2020-04-10T20:25:38Z
thanosrulers.monitoring.coreos.com                                 2020-09-03T23:48:25Z

**Comment by simonpasquier** [comment]
> But as operator is already deployed with latest version it should have the CRD created right?

Not necessarily. Someone (yourself or your cluster admin) has to make sure that the CRDs are up-to-date which doesn't seem to be the case.

**Comment by simonpasquier** [comment]
see https://github.com/prometheus-operator/prometheus-operator#quickstart

**Comment by diyavicky** [comment]
@simonpasquier We have added Alertmangerconfig CRD to our cluster and am able to list that CRD.
We are trying to configure Slack notification with webhook endpoint. Looks like standard alertmanager receiver configuration parameters are different from Alertmangerconfig. 

I was referring the below documents but couldn't find all matching keys in configuration. Could you please advise on this.
 
https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/alerting.md

Error:
**_error: error validating "alertManager/01_alertManager_config.yml": error validating data: [ValidationError(AlertmanagerConfig.spec.receivers[0].webhookConfigs[0]): unknown field "apiURL" in com.coreos.monitoring.v1alpha1.AlertmanagerConfig.spec.receivers.webhookConfigs, ValidationError(AlertmanagerConfig.spec.receivers[0].webhookConfigs[0]): unknown field "channel" in com.coreos.monitoring.v1alpha1.AlertmanagerConfig.spec.receivers.webhookConfigs, ValidationError(AlertmanagerConfig.spec.receivers[0].webhookConfigs[0]): unknown field "text" in com.coreos.monitoring.v1alpha1.AlertmanagerConfig.spec.receivers.webhookConfigs, ValidationError(AlertmanagerConfig.spec.receivers[0].webhookConfigs[0]): unknown field "title" in com.coreos.monitoring.v1alpha1.AlertmanagerConfig.spec.receivers.webhookConfigs, ValidationError(AlertmanagerConfig.spec.receivers[0].webhookConfigs[0]): unknown field "username" in com.coreos.monitoring.v1alpha1.AlertmanagerConfig.spec.receivers.webhookConfigs, ValidationError(AlertmanagerConfig.spec.route): unknown field "httpConfig" in com.coreos.monitoring.v1alpha1.AlertmanagerConfig.spec.route, ValidationError(AlertmanagerConfig.spec.route): unknown field "resolveTimeout" in com.coreos.monitoring.v1alpha1.AlertmanagerConfig.spec.route]; if you choose to ignore these errors, turn validation off with --validate=false_**
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config-slack
  labels:
    alertmanagerConfig: slack-notification
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 10m
    repeatInterval: 15m
    receiver: 'slack-notify'
    resolveTimeout: 5m
    httpConfig:
      tlsConfig:
        insecure_skip_verify: true
      proxyUrl: 'http://dps.xxxx.com:443'
  receivers:
    - name: slack-notify
      webhookConfigs:
      - apiURL: 'https://hooks.slack.com/services/xxxxxx
        username: 'Alertmanager'
        channel: '#infra-alerts'
        sendResolved: true
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
        text: >-
          {{ with index .Alerts 0 -}}
          {{ end }}
          *Alert details*:
          {{ range .Alerts -}}
            *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          *Description:* {{ .Annotations.description }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}

**Comment by simonpasquier** [comment]
The format of the AlertmanagerConfig CRD is defined [here](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#alertmanagerconfigspec). Not every field of the Alertmanager's configuration is exposed.

Note that because of #3665, you should use `AlertmanagerConfig` resources if you're using only webhook, PagerDuty or OpsGenie receivers.

**Comment by diyavicky** [comment]
Thanks for looking into this Simon.

@simonpasquier Even after updating all parameters am not receiving alert with the configured webhook ednpoint.
Could you please advise on this?

Config file is reloaded properly though.

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config-webhook
  labels:
    alertmanagerConfig: slack-webhook-notification
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 10m
    repeatInterval: 15m
    receiver: 'slack-webhook-notify'
  receivers:
    - name: slack-webhook-notify
      webhookConfigs:
      - urlSecret:
          name: slack-notify-secret
          key: API_SECRET
        httpConfig:
          tlsConfig:
            insecureSkipVerify: true
          proxyURL: 'http://xxxxx:443'

**Comment by simonpasquier** [comment]
Have you checked the Alertmanager logs?

**Comment by diyavicky** [comment]
@simonpasquier Alertmanager logs doesn't have any errors. **hooks.slack.com** is a webhook endpoint for Slack. So will this be considered as webhookConfigs or slackConfigs?

If its slackConfigs as you already mentioned it is not supported with alertmanagerConfig CRD at this point?

Please advise!

**AlertManager Logs:**
level=info ts=2020-11-18T16:16:24.525Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2020-11-18T16:16:24.526Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config/alertmanager.yaml 

/etc/alertmanager/config/alertmanager.yaml :
/alertmanager $ cat /etc/alertmanager/config/alertmanager.yaml
route:
  receiver: "null"
  routes:
  - receiver: cs-automation-alertmanager-config-slack-slack-notify
    group_by:
    - job
    match:
      namespace: cs-automation
    continue: true
    group_wait: 30s
    group_interval: 10m
    repeat_interval: 15m
receivers:
- name: "null"
- name: cs-automation-alertmanager-config-slack-slack-notify
  webhook_configs:
  - send_resolved: false
    url: https://hooks.slack.com/services/xxxxx
    http_config:
      proxy_url: http://xxx
      tls_config:
        insecure_skip_verify: true
templates: []

**Comment by simonpasquier** [comment]
If you see nothing in the logs, it is because hooks.slack.com replied with 200 though the posted payload doesn't make any sense for it. I presume you have to wait for Slack to be supported in the next Prometheus operator release.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
