### ISSUE TITLE
Thanos deployment

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus-operator/prometheus-operator#3675]
Hi team I didn't see any Thanos deployment files might be I am missing something could you please provide the Thanos deployment with prometheus-operator by core os .
On any guidence links to download.

**Comment by simonpasquier** [comment]
You want to check https://github.com/thanos-io/kube-thanos. The prometheus operator only deals with Thanos ruler and sidecar.

**Comment by mohanagandlla** [comment]
Ok thank you
