### ISSUE TITLE
Add "Status" for ServiceMonitor

### ISSUE THREAD

**Issue by vincent-pli** [prometheus-operator/prometheus-operator#3676]
**What is missing?** 
Could we add `status` for `ServiceMonitor` or `PodMonitor`.
the state will be simple, just mark if the CR has been recognized by `operator`. 

**Why do we need it?**
Sometimes after created `ServiceMonitor`, we has no idea if it has been adopt since there will be many reason cause it not been adopt, for example, the `ns` not label correct or label not match
If there is a flag in `status` to tell people, will be very helpful.

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
Yes this is already tracked in https://github.com/prometheus-operator/prometheus-operator/issues/3335.
