### ISSUE TITLE
service account missing in the namespace Prometheus Resource created.

### ISSUE THREAD

**Issue by hoangelos** [prometheus-operator/prometheus-operator#3678]
I installed the operator using kustomize into a namespace called operators.  I'm using Kubernetes 1.17 cluster on Azure's AKS.  This is a multi-tenant environment.  In one of the tenant namespaces I installed the following Prometheus resources

`apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: k8s
  namespace: fake-tenant-ns
spec:
  replicas: 2
  serviceAccountName: prometheus-operator
  securityContext: {}
  serviceMonitorSelector: {}
  ruleSelector: {}
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  alerting:
    alertmanagers:
      - namespace: fake-tenant-ns
        name: alertmanager-main
        port: web`

After creating, the StatefulSet has this error event

  Warning  FailedCreate  7m24s (x180 over 44h)  statefulset-controller  create Pod prometheus-prometheus-0 in StatefulSet prometheus-prometheus failed error: pods "prometheus-prometheus-0" is forbidden: error looking up service account tenant1-ns/prometheus-operator: serviceaccount "prometheus-operator" not found

**Did you expect to see some different?**
Yes, I expect it to import the service account that was originally installed in the operators namespace in whichever namespace the Prometheus Resource was created.

**Environment**

* Prometheus Operator version:
prometheus-operator:v0.43.2

* Kubernetes version information:

```
bash> kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-04T15:01:15Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"e9496a9e13aa91e0fba8ae9b83ca9d61ee2bde36", GitTreeState:"clean", BuildDate:"2020-09-17T06:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

   AKS

**Comment by lilic** [comment]
Hey @hoangelos can you clarify a bit what you mean by the following, thanks!
> Yes, I expect it to import the service account that was originally installed in the operators namespace in whichever namespace the Prometheus Resource was created.

**Comment by hoangelos** [comment]
@lilic 

Yeah, so, I use kustomize to install prometheus-operator into the namespace operators.  After deploying it, we see a secret for prometheus resources created in the operators namespace.  We have a tenant namespace called ds-<tenant>-ns, and we've included a Prometheus resource with no secretName.   There's no secretName imported to the ds-<tenant>-ns.

**Comment by brancz** [comment]
I'm not sure I can follow. The `Prometheus` resource works much like a `StatefulSet` if you specify a `serviceAccountName` in it, then you are also responsible for creating this `ServiceAccount`.

**Comment by hoangelos** [comment]
Most of the Kubernetes operators we use copy their own service account automatically from wherever it was installed. 

Is that it’s behavior if you don’t specify serviceAccountName?

**Comment by brancz** [comment]
If you don't specify a `serviceAccountName` then the `default` ServiceAccount of that namespace will be used, just like always when you leave `serviceAccountName` empty in any `Pod`.

**Comment by hoangelos** [comment]
Ok, so i guess I’m requesting a feature. Most of the other operators we use. Grafana is a good example.  You don’t have to install the service account yourself.  The operator copies the service account from the namespace it is in.

**Comment by brancz** [comment]
What do you mean when you say "copy"? Are you actually saying it copies a ServiceAccount including roles and rolebindings? Or are just just saying it creates _a_ ServiceAccount automatically? Since Prometheus ServiceAccount is actually important and needs more permissions than most things (most things should not need _any_ permissions unless they are somehow talking to the Kubernetes API), I don't think the Prometheus Operator should be able to grant this, as the Prometheus Operator itself does not need those permissions. It's a matter of principle of least privilege.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time and appears to be answered. If you need additional clarification, please reopen it.
