### ISSUE TITLE
Update Prometheus Operator available via Community Operators

### ISSUE THREAD

**Issue by anishasthana** [prometheus-operator/prometheus-operator#3684]
**What is missing?**

Community Operator Version is outdated. 

**Why do we need it?**

The latest version of the Prometheus Operator available in the community operators repository is [0.37](https://github.com/operator-framework/community-operators/tree/master/community-operators/prometheus/0.37.0 ), which came out in March.

Since the latest tagged release of the operator is 0.43.2 it would be great if we could update the version of the operator that is available via Operator Hub. Support for features such as probes would go a long way :-)

**Environment**
OpenShift

* Prometheus Operator version: 0.43.2

**Comment by s-urbaniak** [comment]
This doesn't seem to be a question related to prometheus-operator per se. Note that we don't include distribution specific deployments here, these are handled elsewhere, i.e. helm has its own repo at https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack. I suggest to open an issue in OperatorHub itself. We do not maintain that repository.
