### ISSUE TITLE
Frequently Compaction failed in Prometheus DB

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus-operator/prometheus-operator#3687]
Hi I was facing the WAL compaction fail and in logs I have seen this 

level=error ts=2020-11-14T17:02:36.468Z caller=db.go:685 component=tsdb msg="compaction failed" err="delete persisted head block after failed db reload:01EQ3V61MKYGSW91GP411WRBTQ: unlinkat /prometheus/01EQ3V61MKYGSW91GP411WRBTQ/chunks: directory not empty"

This issue is geting a lots of time I am not sure there the mistake is...!
I am using the posix type mapr to store the data(PV and PVC).

**Comment by simonpasquier** [comment]
This is more a question about Prometheus than the operator itself. What's your PV/PVC flavor? What's the content of the `/prometheus/01EQ3V61MKYGSW91GP411WRBTQ/chunks` directory?

**Comment by mohanagandlla** [comment]
I am using the mapr system POSIX type and static way of memory 
Inside the chunks directory the content is 

/prometheus/01EQ3V61MKYGSW91GP411WRBTQ/chunks $ ls -lart
total 795398
-rw-r--r--    1 xxxxxxxxx  xxxxx    536870843 Nov 14 17:01 .fuse.fuse000001
-rw-r--r--    1 xxxxxxxxx  xxxxx   277615125 Nov 14 17:01 .fuse.fuse000002
drwxr-xr-x    3 xxxxxxxxx  xxxxx            2 Nov 17 08:23 ..
drwxr-xr-x    2 xxxxxxxxx  xxxxx            2 Nov 17 08:23 .

even i delete it manually also it not done the directory is not deleting. Again some fuse files are auto creating.

/prometheus $ rm -rvf 01EQ3V61MKYGSW91GP411WRBTQ
removed '01EQ3V61MKYGSW91GP411WRBTQ/.fuse.fuseindex'
removed '01EQ3V61MKYGSW91GP411WRBTQ/chunks/.fuse.fuse000002'
removed '01EQ3V61MKYGSW91GP411WRBTQ/chunks/.fuse.fuse000001'
**rm: can't remove '01EQ3V61MKYGSW91GP411WRBTQ/chunks': Directory not empty**
removed directory: '01EQ3V61MKYGSW91GP411WRBTQ'

**Comment by simonpasquier** [comment]
> even i delete it manually also it not done the directory is not deleting. Again some fuse files are auto creating.

then it's an issue with mapr rather than Prometheus.

**Comment by mohanagandlla** [comment]
ok
