### ISSUE TITLE
Inconsistent naming between base Alertmanager and AlertmanagerConfig CRD receiver keys

### ISSUE THREAD

**Issue by longtomjr** [prometheus-operator/prometheus-operator#3690]
The capitalization for the `AlertmanagerConfig` CRD receiver keys differ from how the words are broken up in the base Alertmanager config
https://github.com/prometheus-operator/prometheus-operator/blob/131dad67dd1537387b751f9829ba04dbc3675a00/pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go#L78-L84
vs
```
# Configurations for several notification integrations.
email_configs:
  [ - <email_config>, ... ]
pagerduty_configs:
  [ - <pagerduty_config>, ... ]
pushover_configs:
  [ - <pushover_config>, ... ]
slack_configs:
  [ - <slack_config>, ... ]
opsgenie_configs:
  [ - <opsgenie_config>, ... ]
webhook_configs:
  [ - <webhook_config>, ... ]
victorops_configs:
  [ - <victorops_config>, ... ]
wechat_configs:
  [ - <wechat_config>, ... ]
```
https://prometheus.io/docs/alerting/latest/configuration/#receiver

I can see this going both ways, since the capitalization is consistent with the company branding `WeChat` and `PagerDuty`. I think it makes sense to use the camel casing for separating words (and ignoring the case in branding), in the same way Alertmanager use the snake casing without the branding part. 

I think having this be consistent with Alertmanager makes sense, especially since the word separation is unambiguous.

**Comment by lilic** [comment]
Thanks for the issue. At least we can choose to go one way and agreed, being consistent with alertmanager is the right way, as we do this with other config fields.

From what I can gather we need the change the following two, or did I miss any:
- weChatConfigs -> wechatConfigs
- pagerDutyConfigs -> pagerdutyConfigs

cc @simonpasquier and @grdryn for further thoughts on this.

**Comment by simonpasquier** [comment]
I'm fine with it, consistency is definitely good. I only see the 2 fields @lilic mentioned that would need a change.

**Comment by grdryn** [comment]
Sounds good to me. :+1:

**Comment by lilic** [comment]
@longtomjr are you interested in doing the changes and opening a PR? No worries if not, we can add a help-wanted in case anyone wants to pick up as its a good first issue.
