### ISSUE TITLE
Multi tenancy Possibility for Prometheus

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus-operator/prometheus-operator#3700]
Hi 
Can we have the possibility for multi tenancy for Prometheus which is from operator.

**Comment by lilic** [comment]
@mohanagandlla Hey! We have several mechanisms already, like thanos ruler and the ability to create different Prometheus instances, etc. but might help if you can explain you specific use case.

**Comment by mohanagandlla** [comment]
Ya sure For example I have an instance which is scraping the all data from all components now my use case is like I want to privilege to specified ns for one person and some other ns for some other person how to do it.

**Comment by lilic** [comment]
So you are more wanting to know how to multi-tenancy on a query level then? You want one Prometheus instance to scrape metrics from all namespaces, but users to only have access to see their own namespace metrics? Is this what you mean by privilege?

**Comment by mohanagandlla** [comment]
Yes

**Comment by brancz** [comment]
This is exactly what we built [prom-label-proxy](https://github.com/prometheus-community/prom-label-proxy) for, and we even dropped a note in the [example use](https://github.com/prometheus-community/prom-label-proxy#example-use) section how this can be achieved.

**Comment by mohanagandlla** [comment]
This is really pretty cool I will go with this

**Comment by coderanger** [comment]
This feels possibly out of scope for the operator given that the topology can get fairly arbitrary depending on your scale. label proxy works well on the small end but for a larger setup something like Cortex would probably be better. Also depends on how "hard" your tenant boundaries are, do you expect active cross-tenant attacks or just logical divisions.

**Comment by brancz** [comment]
For what it's worth, both Thanos and Cortex essentially only perform enforcing a tenant at query time, it might look different but that's the start, what happens afterwards depends on the concrete storage choice and concrete setup. It doesn't have anything to do with prom-label-proxy being scalable or not.

I do agree though that integrating some arbitrary tenancy mechanism is out of scope for the prometheus-operator, this is up to the end user to decide.

Looks like prom-label-proxy was what @mohanagandlla was looking for, so closing here.
