### ISSUE TITLE
Add .spec.minReadySeconds as configurable option

### ISSUE THREAD

**Issue by wiardvanrij** [prometheus-operator/prometheus-operator#3711]
**What is missing?**
.spec.minReadySeconds

**Why do we need it?**
In a HA setup using Cortex or Thanos, I want to have 0 downtime deployments. 
Best-case now is to run 3 replica's of Prometheus. 

Yet if there was an option to rollout slowly between instances, it would be fine to run a replication of 2. 

Current behaviour: 

- Prometheus 1 gets terminated -> starts again
- Loads WAL and eventually (scrape) configs. (I'm not really sure yet if a Pod already has the 'ready' status after reading wal or after reading dynamic scrape configs.)
- The moment the pod is ready, prometheus 2 gets terminated.
- Prometheus 1 has no data yet from "current" period. 
- For example Grafana instantly alerts "no data" as there is no evaluation property on that alert: https://github.com/grafana/grafana/issues/29397

What is possible, is to add a successThreshold like:

```
spec:
  containers:
  - name: prometheus
    readinessProbe:
      successThreshold: 30
      periodSeconds: 5
```
This gives Prometheus time to: 
- Load dynamic config (again, could be wrong here)
- Start scraping

Yet this is not enough. Because components need to know about the now ready state of this prometheus, there is a little delay. It's hard to pinpoint the delay but I would estimate it would be < 0.2 second. Enough to let Grafana at-least throw an alert: no data.

By implementing a minReadySeconds combined with an increased successThreshold, it would be possible for Prometheus to get a proper ready state (from my point of view ;) ). Yet also allowing services to catch up before the other replica gets terminated.

**Comment by brancz** [comment]
I think this is generally a sound idea. I wonder if we could start with a value that is not configurable, that hopefully works for everyone? What do you think?

**Comment by wiardvanrij** [comment]
I've actually came into a discussion with someone, who pointed out that minReadySeconds would not perse resolve my "issue". It was more that a phased roll-out could be done with statefulsets partitioning. I thought I could achieve this with minReadySeconds, but I might actually be mistaken. 

Nonetheless, being able to change things in the prometheus operator statefulset via the CRD's would be awesome.

**Comment by PhilipGough** [comment]
I'll take a look at this once since it looks like `MinReadySeconds` has been added to ss (although still feature gated) in https://github.com/kubernetes/kubernetes/pull/101316
