### ISSUE TITLE
Confusing documentation for serviceMonitorNamespaceSelector and podMonitorNamespaceSelector

### ISSUE THREAD

**Issue by framled** [prometheus-operator/prometheus-operator#3720]
**What happened?**

Documentation in the link below is kind of incomplete or a bit confusing.

https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec

Current doc says:
| Field | Description |
|--|--|
|serviceMonitorNamespaceSelector| Namespaces to be selected for ServiceMonitor discovery. If nil, only check own namespace.|
|podMonitorNamespaceSelector | Namespaces to be selected for PodMonitor discovery. If nil, only check own namespace.|

I propose:
| Field | Description |
|--|--|
|serviceMonitorNamespaceSelector| Namespace's labels to match for ServiceMonitor discovery. If nil, only check own namespace.|
|podMonitorNamespaceSelector | Namespace's labels to match for PodMonitor discovery. If nil, only check own namespace.|

**Comment by brancz** [comment]
Sounds great! Would you like to propose this change?

**Comment by framled** [comment]
Yeah sure!

**Comment by framled** [comment]
PR #3723

**Comment by paulfantom** [comment]
Closing as #3723 was merged.
