### ISSUE TITLE
ability to change --storage.tsdb.max-block-duration value

### ISSUE THREAD

**Issue by dorsany** [prometheus-operator/prometheus-operator#3724]
**What is missing?**
support the ability to change `--storage.tsdb.max-block-duration` value. currently it's hard coded to `2h` :

https://github.com/prometheus-operator/prometheus-operator/blob/1d47c7497313e9685a8f8cbe14550f215d8c309e/pkg/prometheus/statefulset.go#L808-L810

and also the `--storage.tsdb.min-block-duration` key

probably need also to change some things in helm charts and [here](https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/apis/monitoring/v1/types.go)

**Why do we need it?**
we have some memory limit in our bare metal servers, and with `--storage.tsdb.max-block-duration=2h` we are getting `OOM`. Changing it to `30m` can help. 
In addition, writing do disk faster can help us in case of brutal shutdown which can cause data loss. 
probably there are more scenarios to why changing it..

**Environment**
k8s 1.17
bare metal

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

chart version: `version: 12.3.0`
app version: `0.43.2`

**Anything else we need to know?**:
related: https://github.com/prometheus-operator/prometheus-operator/issues/3351

**Comment by simonpasquier** [comment]
We don't want to promote something that is discouraged by upstream. Expect to prevent compaction in the Thanos case, there is no "good" reason to decrease `storage.tsdb.max-block-duration`. Which Prometheus version are you running?

**Comment by dorsany** [comment]
Hi  @simonpasquier ,  I have got the OOM issue on `v2.19.3` Prometheus version.
Maybe it's discouraged by upstream, but it's configurable.
So why not to expose this configuration and let the end user to handle the consequences?

**Comment by simonpasquier** [comment]
>  Maybe it's discouraged by upstream, but it's configurable,

sure but you can notice that the flags are hidden and not listed by `prometheus --help`. Changing this setting is really a band-aid solution and has side effects such as degraded data compression. You need to allocate more memory to Prometheus or shard the metrics collection.

>  so why not to expose this configuration and let the end user to handle the consequences?

See discussions in #1375.

**Comment by dorsany** [comment]
> You need to allocate more memory to Prometheus or shard the metrics collection
more memory: can be issue on a bare metal server. 
shard the metrics collection: We need to test it if this can be done with 1 Prometheus replica and to see if it won't get OOM

**Comment by abhi4u1947** [comment]
Still open issue:

https://github.com/prometheus-operator/prometheus-operator/issues/4414#issuecomment-2402832211
