### ISSUE TITLE
HA for alert-manager

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus-operator/prometheus-operator#3729]
Hi I just want to enable the HA for alert manager I saw the documentation only like https://coreos.com/operators/prometheus/docs/0.17.0/high-availability.html no where I found how to enable this feature with and.**How to maintain the gossip function between those**  Do we have any guidencies to make as HA (alertmanager) ?
I am using the Operator version 0.42.0 
Alert-manager version 0.21.0

**Comment by simonpasquier** [comment]
Setting the `spec.replicas` field of the Alertmanager resource to a value greater than 1 will automatically setup the gossip clustering.

**Comment by mohanagandlla** [comment]
Thank you for that even If i have maintain the more than 1 replica i am getting this error
evel=warn ts=2020-12-08T13:19:51.634Z caller=cluster.go:438 component=cluster msg=refresh result=failure addr=alertmanager-test1-0.alertmanager-operated.depl.svc:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-test1-0.alertmanager-operated.depl.svc:9094: lookup alertmanager-test1-0.alertmanager-operated.depl.svc on x.x.x.x:53: no such host\n\n"

**Comment by simonpasquier** [comment]
Does the log message repeat over time or does it happen only once?

**Comment by mohanagandlla** [comment]
It has repeated 3 times and now not repeating at

**Comment by simonpasquier** [comment]
Then everything is fine. It needed a bit of time for the DNS server to update its data.

**Comment by mohanagandlla** [comment]
OK I good to hear thank you.
