### ISSUE TITLE
permission denied on both containers in Prometheus at operator version 0.44.0

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus-operator/prometheus-operator#3734]
Hi team i am using the operator version as 0.44.0 there I am facing the issue like permission issue on both the containers 
on Prometheus container the permission issue on queries.active and on config container also the permission same 
* Prometheus config-reloader container Logs:

```
level=error ts=2020-12-10T04:13:04.073966942Z caller=reloader.go:240 msg="apply error" err="hash file: open /etc/prometheus/config/prometheus.yaml.gz: permission denied"
```

* Prometheus container Logs:
```
level=error ts=2020-12-10T03:29:18.107Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log
```

**Comment by simonpasquier** [comment]
Do you use persistent storage?

**Comment by mohanagandlla** [comment]
Yes I have used too

**Comment by simonpasquier** [comment]
Can you share the YAML Prometheus resource as well as the pod definition? Please also communicate your Kubernetes version/environment. Given that persistent storage is covered in the end-to-end tests, it might be an issue with Kube.
