### ISSUE TITLE
Design Doc is missing info about recently added CRDs

### ISSUE THREAD

**Issue by mrueg** [prometheus-operator/prometheus-operator#3740]
**What happened?**
Looked at https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/design.md which is linked in https://github.com/prometheus-operator/prometheus-operator#customresourcedefinitions
**Did you expect to see something different?**
I expected it to provide information on all CRDs and it's missing ThanosRuler, Probe and AlertmanagerConfig CRD.

**Comment by lilic** [comment]
Hey, thanks for the issue! 👋 I would not say it's bug, so removed that and added docs label instead. But yes this should be updated! Our API docs are up to date as they are generated https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#thanosruler

What are you missing from those docs? What would you like to see added about AlertmanagerConfig, ThanosRuler and Probe?

@prometheus-operator/prometheus-operator-reviewers we should really make it a condition to add some basic docs when adding a new API, wdyt?

**Comment by s-urbaniak** [comment]
> we should really make it a condition to add some basic docs when adding a new API, wdyt?
yes, agreed, we apparently missed adding those.

**Comment by simonpasquier** [comment]
We mention the new CRDs in the README.md but agree that we should be more cautious in the future. It's also hard to know exactly what to update given there's no website hosting the docs (hint #3431).
