### ISSUE TITLE
Update thanos example automatically via jsonnet

### ISSUE THREAD

**Issue by lilic** [prometheus-operator/prometheus-operator#3741]
In our Thanos ruler and query [examples](https://github.com/prometheus-operator/prometheus-operator/blob/31bf4b889a5ea6de4c1907e299066787fcd73bae/example/thanos/thanos-ruler.yaml) seem to still be using the image for Thanos v0.11, we should add these manifests to our jsonnet generation, so when we update them automatically when we bump versions of Thanos we support to the latest.

Full [example](https://github.com/prometheus-operator/prometheus-operator/tree/31bf4b889a5ea6de4c1907e299066787fcd73bae/example/thanos).

**Comment by simonpasquier** [comment]
@mikechengwei feel free to open a PR and link to this issue :)

**Comment by mikechengwei** [comment]
Thanks

**Comment by mikechengwei** [comment]
This issue can be closed.

**Comment by lilic** [comment]
Thank you!
