### ISSUE TITLE
Alerts should not be required to match an AlertmanagerConfig's namespace

### ISSUE THREAD

**Issue by jutley** [prometheus-operator/prometheus-operator#3750]
**What is missing?**

Alertmanager routes created from AlertmanagerConfig resources only apply to alerts that have a namespace label that matches the namespace of the AlertmanagerConfig. I found this to be a very surprising design decision, because in our case, it does not match any of our use cases.

AlertmanagerConfig resources should be able to work as a "global" configuration, where their routes have the ability to apply to all of their routes.

**Why do we need it?**

We centrally manage our Alertmanager configuration, which means that all alerts would need to be labelled with this central configuration's namespace. This just doesn't make any sense.

Many of our alerts deliberately do not include a namespace label. For example, we have many alerts on Kafka lag, and Kafka does not have any notion of a namespace. The Kafka metrics exporter has a namespace, but not a namespace that is meaningful to the teams that are using Kafka.

We have many namespaces per team. Using this new CRD would require that we define the same AlertmanagerConfigs in each of a team's namespaces, or to universally apply all the AlertmanagerConfigs in all the namespaces. This is just redundant and leads to an incredibly complex routing tree.

**Environment**

* Prometheus Operator version:

`quay.io/prometheus-operator/prometheus-operator:v0.44.1`

**Anything else we need to know?**:

Before the AlertmanagerConfig CRD, we had to configure Alertmanager by generating the full config which included embedded secrets, turn this whole configuration into a secret, then apply it. This approach is very unfriendly for any gitops-based deployment flow. Internally, we solved this by generating a configmap via helm with templated alertmanager configuration, using an encrypted secret with template values, and running a small controller to periodically update the secret with the completed configuration.

I thought this new CRD would allow me to define my Alertmanager configuration with references to an external secret. This would allow us to delete all our complex custom logic around Alertmanager config generation. This nearly works as expected, but the `namespace` label requirements get in the way.

**Comment by buckner** [comment]
#3733 and #3737 also mention this. I agree - my use case is nearly the same, so I'm also experiencing this issue

**Comment by jutley** [comment]
Ah, I thought I searched for this issue, but apparently I did not. I will close this issue and add my two cents onto the other issues.

**Comment by AndresPineros** [comment]
This has already been solved in VictorMetrics Operator: https://github.com/VictoriaMetrics/operator/issues/390

We should really get the same fix in the main operator. The most common use case is that AlertManager routes aren't self-serviced. I understand this is a really flexible solution intended for large teams with many divisions, but it just shouldn't be enforced. Now I have to go back to the ugly ConfigSecret that is 5% secret and 95% configuration.
