### ISSUE TITLE
AlertmanagerConfigs discovery through namespaces

### ISSUE THREAD

**Issue by xxxbobrxxx** [prometheus-operator/prometheus-operator#3754]
**What happened?**

Hi! There is a bug with `AlertmanagerConfigs` discovery if `--alertmanager-instance-namespaces` CLI argument is defined.

If `--alertmanager-instance-namespaces` defined to a particular value and `alertmanagerConfigNamespaceSelector` is set to `{}` - `AlertmanagerConfigs` resources will be only discovered from namespaces defined in `--alertmanager-instance-namespaces`
- `--alertmanager-instance-namespaces` not defined -  `alertmanagerConfigNamespaceSelector` works as expected.

**Did you expect to see something different?**

Values of `--alertmanager-instance-namespaces` CLI argument should not influence on `AlertmanagerConfigs` discovery if `alertmanagerConfigNamespaceSelector` defined.

**Environment**

* Prometheus Operator version:

    `0.44.1`
    

* Kubernetes version information:

   `1.18`
    

* Kubernetes cluster kind:

    EKS

**Anything else we need to know?**:

Thanks!

**Comment by simonpasquier** [comment]
Hmm, I'd say that it works as expected since `--alertmanager-instance-namespaces` works for `Alertmanager` custom resources. It may be that we need to add another flag to control from which namespaces to discover `AlertmanagerConfig` resources but I wouldn't call this a bug.

**Comment by xxxbobrxxx** [comment]
But for *Monitor CRD resources `--prometheus-instance-namespaces` has no such logic, thats because I marked this as a bug. For PrometheusRule I did not checked yet.

**Comment by simonpasquier** [comment]
Sorry I misread your initial report and I thought that you were reporting that the operator should discover AlertmanagerConfig resources only in namespaces defined by `--alertmanager-instance-namespaces`. I've tested and indeed there's a bug.
