### ISSUE TITLE
FAQ should mention serviceMonitorNamespaceSelector/pod/rul

### ISSUE THREAD

**Issue by tux-o-matic** [prometheus-operator/prometheus-operator#3793]
**What is missing?**
The FAQ/Troubleshooting documentation makes no mention of the ```serviceMonitorNamespaceSelector```and similar NamespaceSelectors when covering how CR are reconciled.

**Why do we need it?**
These parameters are essential and also behave differently if not present in a ```Prometheus```CR, set to just ```{}```or provided with a set of match rules.

**Prometheus Operator version**
Any since those parameter were introduced in 2018.

**Comment by simonpasquier** [comment]
:wave: do you want to contribute something? I know that @nrchakradhar has already nice [diagrams](https://github.com/prometheus-operator/prometheus-operator/issues/3553#issuecomment-726733177) illustrating the various possibilities.

**Comment by tux-o-matic** [comment]
@simonpasquier , I tried to go for something simple which hopefully everybody agrees to.
I know it would have helped myself when searching in this project for reconciliation issues.
