### ISSUE TITLE
Documentation and examples around shards and replication support in the operator

### ISSUE THREAD

**Issue by nickytd** [prometheus-operator/prometheus-operator#3795]
Hi 
Can you please refresh the documentation around sharding support and prometheus replication? 

Thanks
Niki Dokovski

**Comment by lilic** [comment]
@nickytd hey, can you explain what needs refreshing, I am not sure much changed since that was merged? Or is it just general lack of docs that you need?

**Comment by nickytd** [comment]
Hi Lili,
I tried getting the sharing configuration together with a kube-state-metrics sharding enabled but that didn't work out of the box. First if you configure 2 shards and 2 replicas in the operator only 2 prometheus pod instances are created for the statefulset ( expected 4 I think) and once we have more than 1 the targets discovery doesn't recognise any longer the instances of kube-state-metrics exporter. I think it helps in general if there is a well described config example that demonstrates the setup and can be used as a starting point.

**Comment by lilic** [comment]
>( expected 4 I think)

That might be another issue open for this, can you have a look at it and comment there if its the same https://github.com/prometheus-operator/prometheus-operator/issues/3801 Thank you!

**Comment by mikechengwei** [comment]
I would be happy to help finish this requirement.

**Comment by nicolastakashi** [comment]
Could be nice if we have any documentation or example about resharding.

**Comment by mikechengwei** [comment]
I have submit a pr about it. refer #3991

**Comment by paulfantom** [comment]
@mikechengwei #3941 is about different issue.
