### ISSUE TITLE
Is the Prometheus Operator no more updated on operatorhub.io?

### ISSUE THREAD

**Issue by martin-schaefer** [prometheus-operator/prometheus-operator#3798]
I am using https://operatorhub.io and its framework to install operators on a Kubernetes cluster. I've noticed this Prometheus operator is also available from https://operatorhub.io/operator/prometheus, but it sems to be outdated there (0.37). Are new versions of this operator no more provided through https://operatorhub.io?

**Comment by coderanger** [comment]
I don't think that entry is managed by this project, you can see the Maintainers link is to the OpenShift operators team. IIRC this repo doesn't have any OLM metadata in it so that's being managed elsewhere.

**Comment by paulfantom** [comment]
OLM metadata (CSVs) are maintained in https://github.com/operator-framework/community-operators/tree/master/community-operators/prometheus.

**Comment by martin-schaefer** [comment]
I've checked it and yes, you are right, these are other maintainers which haven't updated it recently. In the meantime I have made a terraform module (Using this mostly anyway) for the Prometheus operator based on bundle.yaml. I would be able to share the module if someone is interested.
