### ISSUE TITLE
How can I have the prometheus replicas distributed and using the same PV ?

### ISSUE THREAD

**Issue by chromafunk** [prometheus-operator/prometheus-operator#3803]
So, the thing is : I have successfully configured a prometheus-operator + thanos setup. What I'm seeing is that when I configure the prometheus pods to be replicated on this HA cluster ( replicas 4 ), four stateful sets are created, one on each worker node. My question is, how can I just run replicas of only one statefulset on different worker nodes ? Is it possible to do this by load-balancing prometheus replicated pods ? Running four prometheus statefulsets is wasteful because each one of them is claiming a persistent volume, besides using CPU and RAM.  If you have some information or documentation I can follow to achieve this, it'd be great. Thanks !

**Comment by coderanger** [comment]
No, that’s not how volumes work.
