### ISSUE TITLE
Rename Prometheus Operator Service

### ISSUE THREAD

**Issue by jbroenstrup** [prometheus-operator/prometheus-operator#3805]
I would like to be able to deploy separate instances of prometheus into the same namespace. This seems to fail, due to the fixed name of the service. Is it possible to change the name of the service? Mine is always named "prometheus-operated".

**Comment by s-urbaniak** [comment]
What you are referring to is the governing service that point to the synthesized Prometheus statefulsets. In the case of a second Prometheus in the same namespace the same governing service will be referenced, which in turn will add the IPs of all pods of the separate Prometheus instances to the same governing service.

If you want a dedicated service to expose your second Prometheus instance, you have to create it manually.

Generally: I just tried locally (to verify if we have a bug with creating additional Prometheus instances in the same namespace) but it seems to work just fine.

**Comment by paulfantom** [comment]
Closing as the issue appears to be answered. If you need additional clarification, please reopen it.

**Comment by Junnplus** [comment]
I had the same confusion, I also deply separate instances of prometheus into the same namespace, I want each prometheus instance to have its own separate service instead of being in the same service `prometheus-operated`.
