### ISSUE TITLE
Allow independent setting of requests/limits for CPU/memory in configmap-reloader

### ISSUE THREAD

**Issue by JJJJJones** [prometheus-operator/prometheus-operator#3825]
**What is missing?**

Independent setting of requests/limits for [CPU](https://github.com/prometheus-operator/prometheus-operator/blob/master/cmd/operator/main.go#L173)/[memory](https://github.com/prometheus-operator/prometheus-operator/blob/master/cmd/operator/main.go#L174)

**Why do we need it?**

Not everyone who removes CPU limits (to get rid of annoying CPUThrottlingHigh alerts or ensure that sidecars aren't unnecessarily throttling) wants to throw out CPU requests because they're important in scheduling. Requests and limits aren't always set equivalent. 

**Environment**

* Prometheus Operator version: 0.43.0

**Anything else we need to know?**:

I'm writing up a PR to address this.

**Related links**

Config Reloader added CPU/memory setting with [0.29.0](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.29.0). [PR](https://github.com/prometheus-operator/prometheus-operator/pull/2403/files)
[Similar](https://github.com/prometheus-operator/prometheus-operator/pull/2144) [headaches](https://github.com/prometheus-operator/prometheus-operator/issues/2171)  
[PR that made the flag also set requests](https://github.com/prometheus-operator/prometheus-operator/pull/2958)
[Work on reducing the CPUThrottlingHigh annoyance with inhibition](https://github.com/prometheus-operator/kube-prometheus/issues/861)

**Comment by simonpasquier** [comment]
We now have dedicated CLI arguments for limits and requests.
