### ISSUE TITLE
[Alertmanager] global: smtp_require_tls configuration flag is not propagated to generated Alertmanager config secret

### ISSUE THREAD

**Issue by mdostal-hci** [prometheus-operator/prometheus-operator#3829]
**What happened?**
I have created a secret "alertmanager-test" with alertmanager.yaml contents:
```
global:
  smtp_require_tls: false
  resolve_timeout: 7m
  smtp_from: alertmanager@sampledomain.com
  smtp_hello: localhost
  smtp_smarthost: localhost:25

route:
  receiver: "null"
receivers:
- name: "null"
```

and appropriate alertmanager config object with reference to "configSecret: alertmanager-test". It was parsed by prometheus-operator to "alertmanager-generated" secret, but generated secret was missing "global: smtp_require_tls" configuration option.

**Did you expect to see something different?**
global:smtp_require_tls option should be present in generated secret.

**How to reproduce it (as minimally and precisely as possible)**:
See above, I will prepare PR with failing test.

**Environment**

* Prometheus Operator version:
v0.45.0

* Kubernetes version information:
version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"gohttps://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack1.13.9", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:
RKE

* Relevant manifests
```
apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Alertmanager
  metadata:
    annotations:
      meta.helm.sh/release-name: eit
      meta.helm.sh/release-namespace: monitoring
    labels:
      app: kube-prometheus-stack-alertmanager
      app.kubernetes.io/managed-by: Helm
      chart: kube-prometheus-stack-13.2.1
      heritage: Helm
      release: eit
    name: kube-prometheus-stack-alertmanager
    namespace: monitoring
  spec:
    alertmanagerConfigNamespaceSelector: {}
    alertmanagerConfigSelector: {}
    configSecret: alertmanager-test
    externalUrl: http://alertmanager.somedomain.com/
    image: quay.io/prometheus-alertmanager:v0.21.0
    listenLocal: false
    logFormat: logfmt
    logLevel: info
    paused: false
    portName: web
    replicas: 1
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi
    retention: 120h
    routePrefix: /
    securityContext:
      fsGroup: 2000
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: kube-prometheus-stack-alertmanager
    version: v0.21.0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
* Anything else to know:
Installed through Helm via [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) Helm chart.

**Comment by mdostal-hci** [comment]
PR created as https://github.com/prometheus-operator/prometheus-operator/pull/3830

**Comment by s-urbaniak** [comment]
cc @simonpasquier maybe you can advise?
