### ISSUE TITLE
Add `dnsConfig` parameter on `PrometheusSpec` and to `AlertmanagerSpec`

### ISSUE THREAD

**Issue by stafot** [prometheus-operator/prometheus-operator#3836]
**What is missing?**

Add `dnsConfig` parameter on `PrometheusSpec` and to `AlertmanagerSpec` to be able to custimize dns configuration on Prometheus and Alertmanager StatefulSets' pods.

**Why do we need it?**
Pod's DNS Config field enable users more control on the DNS settings for the pods.

**Environment**
All
* Prometheus Operator version:
All

**Anything else we need to know?**:
If there are no objections on this proposal I ll raise a PR to implement this in the near future.

**Comment by KostaGorod** [comment]
still relevant

**Comment by Sispheor** [comment]
Hello there. It's indeed still relevant. On K8S cluster deployed with solution like Talos it becomes even mandatory unfortunately...

**Comment by simonpasquier** [comment]
@Sispheor would you like to contribute? #3899 is stale but it should provide a good starting point.

**Comment by stafot** [comment]
I have some time to refactor the stale PR, address some of the comments and sync it with the current codebase. If anyone else wants to contribute too on this effort is more than welcome to.
