### ISSUE TITLE
Patch prometheus container args with custom args

### ISSUE THREAD

**Issue by betorvs** [prometheus-operator/prometheus-operator#3848]
**What is missing?**

I want to enable `--enable-feature=exemplar-storage` to test new examplars endpoint but when I use 
```
spec:
  containers:
  - args:
    - --enable-feature=exemplar-storage
    name: prometheus
```
It replace all args from prometheus container.
 
**Why do we need it?**

To use `--enable-feature` in prometheus > v2.25.0.

**Environment**

* Prometheus Operator version: v0.42.1 from quay.io repository.

**Anything else we need to know?**:

We don't want to rewrite all args for prometheus container:
```
- --web.console.templates=/etc/prometheus/consoles
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=48h
    - --web.enable-lifecycle
    - --storage.tsdb.no-lockfile
    - --web.external-url=https://prometheus.example.local
    - --web.route-prefix=/
    - --storage.tsdb.max-block-duration=2h
```
In my case I'm using kube-prometheus jsonnet and it adds a lot of args if I rewrite it manually I will need to review every time I update kube-prometheus.

**Comment by brancz** [comment]
I'm actually happy with having feature flags as a first class feature. The nature of the field and documentation should be enough to clarify that any use of it exempts it from support. Do you want to add this?

**Comment by QuentinBisson** [comment]
I can take care of adding this to the prometheus crd. Can you assign it to me?

**Comment by brancz** [comment]
Done! :)
