### ISSUE TITLE
Fields incorrectly marked as deprecated

### ISSUE THREAD

**Issue by brancz** [prometheus-operator/prometheus-operator#3854]
**What happened?**

`podMonitorSelector` and `serviceMonitorSelector` are being marked as deprecated entirely by tools because of their comments. We should change this comment to just write out the behavior instead of using the typical deprecated format.

**Did you expect to see something different?**

These fields are not deprecated entirely, just a certain behavior, so only that should be called out and not the entire field be deprecated.

**How to reproduce it (as minimally and precisely as possible)**:

Use the Jetbrains Kubernetes plugin (in GoLand) to write/edit a Prometheus resource

**Comment by rexagod** [comment]
@simonpasquier I think we can close this now, this seems to have been reworded in https://github.com/prometheus-operator/prometheus-operator/commit/e70b29a007e9613acffad468297bc236b4f2c582#diff-b4a3c944005e67c959c04552108ff3b629b572d7244d586b0558651bd96eacdaL44.

**Comment by nicolastakashi** [comment]
@simonpasquier looking here https://github.com/prometheus-operator/prometheus-operator/blob/18a2bad4f7742ff8c97dc73322289ec1eced1d74/pkg/apis/monitoring/v1/prometheus_types.go#L65

Seems it's resolved.
Maybe we should now advise the usage of ScrapeConfig instead of additional scrape config.
WDYT?

**Comment by simonpasquier** [comment]
>  Maybe we should now advise the usage of ScrapeConfig instead of additional scrape config.

Agreed both the legacy behavior (setting all selectors to nil) and `.spec.additionalScrapeConfigs` should redirect to the new ScrapeConfig CRD.
