### ISSUE TITLE
jsonnet-ci jq update doesn't work

### ISSUE THREAD

**Issue by giacomolicari** [prometheus-operator/prometheus-operator#3869]
**What happened?**
When I try to run:

`docker run --rm --user 1000:1000 -v $(pwd):$(pwd) --workdir $(pwd) quay.io/coreos/jsonnet-ci:latest jq update` 

inside my kube-prometheus (version **release-0.3**) I get the following error:

```
GET https://github.com/prometheus/prometheus/archive/.tar.gz 404
archive install failed: unexpected status code 404
retrying with git...
Initialized empty Git repository in /kube-prometheus/vendor/.tmp/jsonnetpkg-github.com-prometheus-prometheus-documentation-prometheus-mixin-master603347009/.git/
fatal: Couldn't find remote ref master
```

and then

```
error: pathspec 'master' did not match any file(s) known to git
```

**Did you expect to see something different?**
I would expect the command to work as usual.

**How to reproduce it (as minimally and precisely as possible)**:
Go into the directory kube-prometheus (version **release-0.3**) - https://github.com/prometheus-operator/kube-prometheus/tree/release-0.3 .

Run `docker run --rm --user 1000:1000 -v $(pwd):$(pwd) --workdir $(pwd) quay.io/coreos/jsonnet-ci jb update`

The issue is reproducible on all jsonnet-ci versions (not only latest and master).

**Environment**
No environment variables are needed.

* Prometheus Operator version:

    `release-0.3`
    

* Kubernetes version information:

    `1.15.12`

**Comment by VincenzoDo** [comment]
Hello @giacomolicari,

looks like Prometheus repository changed from "master" to "main". You can fix this by changing the corresponding entry in the jsonnetfile.json (under version):

    "source": {
        "git": {
          "remote": "https://github.com/prometheus/prometheus",
          "subdir": "documentation/prometheus-mixin"
        }
      },
      "version": "main",
      "name": "prometheus"
    }

**Comment by giacomolicari** [comment]
Thank you @VincenzoDo for the hints, you helped me solve the issue for the moment.

In my case I've got the following jsonnetfile.json:

```
{
  "version": 1,
  "dependencies": [
    {
      "source": {
        "local": {
          "directory": "jsonnet/kube-prometheus"
        }
      },
      "version": "",
      "name": "kube-prometheus"
    }
  ],
  "legacyImports": true
}
```

So I edited the file and set the following content:

```
{
  "version": 1,
  "dependencies": [
    {
      "source": {
        "git": {
          "remote": "https://github.com/prometheus/prometheus",
          "subdir": "documentation/prometheus-mixin"
        }
      },
      "version": "main",
      "name": "prometheus"
    },
    {
      "source": {
        "local": {
          "directory": "jsonnet/kube-prometheus"
        }
      },
      "version": "",
      "name": "kube-prometheus"
    }
  ],
  "legacyImports": true
}
```

Now everything works as expected when running `quay.io/coreos/jsonnet-ci` the first , but after every latter execution the jsonnetfile.json file gets overridden, so it becomes necessary to update the file before running any code again.

**Comment by paulfantom** [comment]
jsonnet-ci image is no longer used as we moved to a different way of managing tooling dependencies.
