### ISSUE TITLE
Global default podTargetLabels for ServiceMontor and PodMonitor

### ISSUE THREAD

**Issue by fredr** [prometheus-operator/prometheus-operator#3871]
**What is missing?**
A way to globally config podTargetLabels for ServiceMonitors and PodMonitors

**Why do we need it?**
In our clusters, each team create ServiceMonitors or PodMonitors as part of their applications. We have a labeling convention that all teams follow, where we have some common labels such as app, team etc. Some of these labels we always want to target, so that we get them in our metrics in prometheus. We can add them to podTargetLabels, but then we need to add that in all of our ServiceMonitors and PodMonitors. 

**Environment**

* Prometheus Operator version: 0.45.0

**Anything else we need to know?**:
I started a thread about this on [slack](https://kubernetes.slack.com/archives/CFFDS2Z7F/p1614163550054000), and was asked by @paulfantom to add it as a issue here.

**Comment by paulfantom** [comment]
We are already doing a similar thing with `enforcedNamespaceLabel` and I think this is a logical next step to allow users to configure what they wanted to be enforced. For me, this could allow much more flexible tenancy models in the future.

I wonder what is the team's perspective on this. cc @prometheus-operator/prometheus-operator-reviewers

**Comment by carlpett** [comment]
If this is something that would be accepted, we're willing to put in the time to implement this, as we're in the exact situation as @fredr.
