### ISSUE TITLE
AlertmanagerConfig restricts the current namespace

### ISSUE THREAD

**Issue by bkmeneguello** [prometheus-operator/prometheus-operator#3885]
When configuring an AlermanagerConfig, it adds the resource's namespace as a required label matcher [here](https://github.com/prometheus-operator/prometheus-operator/blob/3efe14cd34c87ba387258c4afab60273dc789af2/pkg/alertmanager/amcfg.go#L142). This forces me to create one AlermanagerConfig per namespace to capture alerts from many namespaces and forces me to group my alerts by namespace, which is sometimes undesirable. Also, my Opsgenie secret must be replicated to each one of these namespaces, which could lead to security vulnerabilities.
Could this matcher be a default configuration but remove it if required? Or this behavior has some reason to exist?

**Comment by brancz** [comment]
There's an existing issue where this is being discussed: https://github.com/prometheus-operator/prometheus-operator/issues/3737

Do you mind if we close this as a duplicate?
