### ISSUE TITLE
Prometheus remote_write metadata cannot be disabled

### ISSUE THREAD

**Issue by universam1** [prometheus-operator/prometheus-operator#3889]
**What happened?**

Prometheus remote_write metadata cannot be disabled
```
metadata_config:
  send: false
```

**Did you expect to see something different?**

should be configurable

**How to reproduce it (as minimally and precisely as possible)**:

CRD does not support these flags

ref: https://github.com/prometheus/prometheus/pull/6815
ref: https://github.com/thanos-io/thanos/issues/3772

**Comment by mikechengwei** [comment]
I will help finish it.

**Comment by simonpasquier** [comment]
Closed by #3915
