### ISSUE TITLE
Support configuring prometheus using additionalScrapeConfigs only

### ISSUE THREAD

**Issue by Shadi** [prometheus-operator/prometheus-operator#3911]
Hello,

We want to configure one of our prometheus instances using additionalScrapeConfigs, mainly because the configuration is simple and using a pod or servicemonitor adds a little bit of relabeling logic we don't need, but currently not specifying a servicemonitor causes the prometheus instance configuration to be "unmanaged" 

**What is missing?**

a property for manually writing simple scrape configuration, additionalScrapeConfigs can be reused for that(and renamed)

**Why do we need it?**

Provide a way to manually write simple scraping config.

**Anything else we need to know?**:

I think this might be fixed by changing the check here to also check if additionalScrapeConfigs is empty: 
https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/prometheus/operator.go#L1416

**Comment by simonpasquier** [comment]
Probably related to #2787

**Comment by simonpasquier** [comment]
The operator now offers the ScrapeConfig CRD which already supports static config, file SD, HTTP SD, ...

As such, we don't plan to invest more into additionalScrapeConfigs.
