### ISSUE TITLE
Add a new prometheusRulesExcludeFromEnforceLocalNamespace to exclude namespace labeler for local namespace

### ISSUE THREAD

**Issue by amuraru** [prometheus-operator/prometheus-operator#3919]
**What is missing?**

Currently when `enforcedNamespaceLabel` is configured there is no way to exclude for ns labeling all the rules in a given namespace. While `prometheusRulesExcludedFromEnforce` exists this is hard to manage for helm based installation of the prometheus-operator where a set of "built-in" mixins based PrometheusRules are installed as part of the installation.

More specifically, `kube-prometheus-stack` helm chart is installing along with `Prometheus` CR a set of PrometheusRules that should be excluded for ns labeling as they are applicable for all namespaces watched by the operator, e.g: 
https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.yaml#L28-L31.

To keep this things simple my proposal would be to add another bool flag at Prometheus spec level `prometheusRulesExcludeFromEnforceLocalNamespace` (shorter name welcome :D) that when set will instruct the ns labeler to exlclude *all* `PrometheusRule`s created in the same namespace as the watching `Prometheus` CR

**Why do we need it?**

Use `enforcedNamespaceLabel` with community `kube-prometheus-stack` helm chart

**Environment**

* Prometheus Operator version:
0.46

**Comment by paulfantom** [comment]
This looks like a hack to fix a shortcoming of the installation method.

Since this would essentially duplicate what `prometheusRulesExcludeFromEnforce` is intended to do, it has the potential to complicate UX while not giving many benefits to end-users.

**Comment by amuraru** [comment]
Closing as wont do
