### ISSUE TITLE
Use Probe CRD with service discovery

### ISSUE THREAD

**Issue by mcinquin** [prometheus-operator/prometheus-operator#3923]
**What is missing?**
Probe would be used with Service Discovery

**Why do we need it?**
I use Consul as Service Discovery and i need to implement Blackbox Exporter for all my instances.
Maintain a static list of targets is painful

**Environment**
GCE instances with Consul
GKE
Prometheus-Operator hosted on GKE

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
The new ScrapeConfig CRD supports the Consul SD.
