### ISSUE TITLE
Prometheus-Operator automatically finds monitoring based on files, adds invalid, requests support, thanks!

### ISSUE THREAD

**Issue by cuizhiyang** [prometheus-operator/prometheus-operator#3927]
Does prometheus_operator support to add configuration file to monitor external host of K8S cluster, such as monitor machine based on Prometheus + Consul automatic discovery, the way I add ConfigMap to CRD resource in Prometheus does not work, is there any solution?Like 
-job_name: consul_exporter
	consul_sd_configs:
	  - server: '10.x.x.x:8500'
	relabel_configs:
	  - source_labels: [__meta_consul_tags]
	regex: .*,prome,.*
	action: keep
	  - source_labels: [__meta_consul_service]
	target_label: job

**Comment by lilic** [comment]
@cuizhiyang yes there is a way to do this via additional scrape configuration https://github.com/prometheus-operator/prometheus-operator/blob/be98a9ef311ccafa862e095069344ccb6f47579c/Documentation/additional-scrape-config.md 

I am assuming you tried this with the above, can you maybe explain what did not work?

**Comment by cuizhiyang** [comment]
cat  prometheus-additional.yaml
- job_name: consul_exporter
        consul_sd_configs:
          - server: 'consul.tk8s.com'
        relabel_configs:
          - source_labels: [__meta_consul_tags]
                regex: .*,prome,.*
                action: keep
          - source_labels: [__meta_consul_service]
                target_label: job

![image](https://user-images.githubusercontent.com/37775902/112115737-7cfa6d80-8bf4-11eb-98dd-e710eab3aac0.png)

I have tried to access the above configuration method, but the server registered in Consul cannot be automatically obtained by accessing the Prometheus dashboard. Under the same situation, I can normally obtain the registered server in Consul if I directly modify the configuration file by deploying Prometheus, please help to check if there is any problem with my configuration file.Thank you very much!

**Comment by cuizhiyang** [comment]
kubectl create secret generic additional-scrape-configs --from-file=prometheus-additional.yaml --dry-run -oyaml > additional-scrape-configs.yaml

Above I generated the secret command!

**Comment by cuizhiyang** [comment]
Sorry, I have found the problem and found that there is something wrong with the format of the configuration file, which has been modified. The correct configuration file is as follows

- job_name: consul_exporter
  consul_sd_configs:
    - server: 'consul.default.svc.cluster.loacl:8500'
  relabel_configs:
    - source_labels: [__meta_consul_tags]
      regex: .*,prome,.*
      action: keep
    - source_labels: [__meta_consul_service]
      target_label: job
