### ISSUE TITLE
Enable volumes and volumesMount on Thanos SideCar

### ISSUE THREAD

**Issue by nicolastakashi** [prometheus-operator/prometheus-operator#3937]
**What is missing?**

Currently, there is no way to mount volumes in a side-car container

**Why do we need it?**

Since we are able to use `objectStorageConfigFile`, mount volumes on the sidecar container will enable us to use secrets as volumes in a different path than `/prometheus`

**Environment**

N/A

* Prometheus Operator version: `v0.46.0`

**Anything else we need to know?**:

N/A

**Comment by simonpasquier** [comment]
This looks similar to https://github.com/prometheus-operator/prometheus-operator/issues/3322. Do you want to give a try?

**Comment by nicolastakashi** [comment]
@simonpasquier if you want, I can open a merge request with a possible solution that I've implemented in a fork that I made.

**Comment by simonpasquier** [comment]
@nicolastakashi sure go ahead.

**Comment by nicolastakashi** [comment]
@simonpasquier Done dude!

Can you take a look: https://github.com/prometheus-operator/prometheus-operator/pull/3966

I will fix the existing conflict

**Comment by simonpasquier** [comment]
closed by https://github.com/prometheus-operator/prometheus-operator/pull/4238
