### ISSUE TITLE
Enable securityContext to Thanos sidecar container

### ISSUE THREAD

**Issue by nicolastakashi** [prometheus-operator/prometheus-operator#3993]
**What is missing?**

Possibility to defined `securityContext` to Thanos sidecar container.

**Why do we need it?**

Sometimes we need to define specific security contexts such as readOnlyRootFilesystem or allowPrivilegeEscalation and we can`t do that on the current version

**Environment**

* Prometheus Operator version:

    `v0.46.0`
    
    

**Anything else we need to know?**:

N/A

**Comment by stafot** [comment]
@nicolastakashi If no other candidates to take it, I could work on it.

**Comment by simonpasquier** [comment]
you should be able to use a strategic merge patch as described in https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/strategic-merge-patch.md

**Comment by simonpasquier** [comment]
Answered by my previous comment, I'm closing it for now.
