### ISSUE TITLE
Incorrect build context in config-reloader image logs

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#3995]
**What happened?**
Started prometheus config reloader and second log line indicates build context which is incorrect:
```
level=info ts=2021-04-16T08:39:05.36818227Z caller=main.go:148 build_context="(go=go1.16.3, user=simonpasquier, date=20210413-15:46:43)"
```

**Did you expect to see something different?**
I expected to see build context which comes from CI, possibly sth like `root@....`

**How to reproduce it (as minimally and precisely as possible)**:
Start config-reloader from quay.io

**Environment**

* Prometheus Operator version: 0.47.0

* Kubernetes version information: Not relevant

* Kubernetes cluster kind: Not relevant

* Manifests: Not relevant

* Prometheus Operator Logs:

```
Not relevant
```

**Anything else we need to know?**:

This was spotted in https://github.com/prometheus-operator/kube-prometheus/issues/1099 issue.

CC @simonpasquier

**Comment by paulfantom** [comment]
Possibly this line is causing it: https://github.com/prometheus-operator/prometheus-operator/blob/master/Makefile#L58. We should probably change it to something that indicates it was built by CI and not by a maintainer.

**Comment by simonpasquier** [comment]
Nice catch! Not sure if we need to keep `BuildUser`?
