### ISSUE TITLE
Does Prometheus operator and application support Active Active Disaster recovery ?

### ISSUE THREAD

**Issue by munipravy** [prometheus-operator/prometheus-operator#3997]
Looking for Disaster recovery set up for Prometheus, does this operator support ?

**Comment by coderanger** [comment]
No for prom-operator, no controller in Kubernetes supports multi-primary operations. We use active-passive with leader election through the K8s API. Prom itself doesn't really support anything but Cortex and Thanos both support multi-primary operations (in fact I don't think there is any way to do active-passive).

**Comment by paulfantom** [comment]
Closing as the issue appears to be answered. If you need additional clarification, please reopen it.
