### ISSUE TITLE
Updating Prometheus-operator fails to load rules

### ISSUE THREAD

**Issue by MonicaMagoniCom** [prometheus-operator/prometheus-operator#4013]
We have deployed prometheus-operator v0.18.0 into our Kubernetes cluster, together with Prometheus v2.2.1 (I know it is an old version but I inherited this work from previous developers).
I would like to update to v0.20.0 but, once done, from the prometheus UI rules disappear and it says 'no rules defined'. 

**This is the format of a rule:**
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cc-rules
  labels:
    role: prometheus-rulefiles
    prometheus: prometheus
data:
  prometheus-cc.rules: |+
    groups:
    - name: prometheus_cc_rules
      rules:
      .......

**This is the prometheus-operator.yml**
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - prometheuses/finalizers
  - alertmanagers/finalizers
  - servicemonitors
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - ''
  resources:
  - services
  - endpoints
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ''
  resources:
  - nodes
  - namespaces
  verbs:
  - list
  - watch

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: default

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  #namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-nodepool
                    operator: In
                    values:
                      - pool-1
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.20.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 51Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator

And from the logs of the prometheus config-reloader, there is this error:
"Updating rule files temporarily failed." err="open /etc/prometheus/config/configmaps.json: no such file or directory"

Any idea?

**Comment by paulfantom** [comment]
Sorry, prometheus-operator v0.20.0 is almost [3 years old](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.20.0) and as an open-source project, we tend to support only the latest versions of the operator. There are many changes in the rule loading path (one of which is the introduction of PrometheusRule CRD) and we do recommend to upgrade your environment.

**Comment by MonicaMagoniCom** [comment]
Hi Paul, thank you for your answer. I agree with you, the problem is related to the rules.They seem to be converted properly but then they are not loaded.
Do you suggest to update the operator step by step or to directly go to the latest version available?

**Comment by paulfantom** [comment]
> Do you suggest to update the operator step by step or to directly go to the latest version available?

Both will be hard as there are many changes between 0.18 and 0.47. If you have a lot of time but need to have this working most of the time I would recommend upgrading version after version and fixing stuff on the way. However, it might be simpler just setting up the secondary stack from the ground up based on 0.47, comparing both, and deprecating the older one when ready.
