### ISSUE TITLE
Grafana chart incorrectly shows missing data as 0

### ISSUE THREAD

**Issue by caleb15** [prometheus-operator/prometheus-operator#4022]
**What happened?**
Grafana dashboard shows missing data as 0

**Did you expect to see something different?**
I expected missing data to not be shown, so I could see that it is missing. 0 gives the false impression that the data is actually at 0.

**How to reproduce it (as minimally and precisely as possible)**:
Use https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack to deploy prometheus and grafana. Go to Kubernetes / Compute Resources / Pod chart and look at the top cpu usage graph. Somehow get into a situation where you have missing data. (we need to look into this \*cough\*).

**Environment**

* Prometheus Operator version: 
 
Unknown, but I deployed prometheus-stack relatively recently. I took a look at the grafana configuration on the main branch and it looks like it's still an issue.

* Kubernetes version information:

N/A

* Kubernetes cluster kind:

N/A

* Manifests:

N/A

* Prometheus Operator Logs:

N/A

**Anything else we need to know?**:
I can try submitting a PR fixing this. It's pretty simple - just a change of `"nullPointMode": "null as zero",` to `"nullPointMode": "null",`.

**Comment by paulfantom** [comment]
All dashboards are coming from [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) project. Please open an issue there.

**Comment by caleb15** [comment]
thanks, I raised https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/603

In that case https://github.com/prometheus-operator/prometheus-operator/issues/1182 should be transfered over as well right :thinking:

**Comment by paulfantom** [comment]
> In that case #1182 should be transfered over as well right? thinking

yes :)
