### ISSUE TITLE
Unable to make PodMonitor scrape pods while in startingProbe

### ISSUE THREAD

**Issue by costimuraru** [prometheus-operator/prometheus-operator#4031]
**What happened?**

We have a Kubernetes application which has a startupProbe. During this period, the pod is alive and is processing some warmup requests before it becomes ready. The pods are monitored using a PodMonitor. We noticed that the prom scraping starts working only after the pod becomes ready (after the startupProbe has completed). This means we are not able to see any metrics in Prometheus while the pod is doing the warmup. We tried searching for a way to instruct the PodMonitor to scrape the pods even if they are not Ready (perhaps with an initialDelay), but no luck.

**Did you expect to see something different?**
We expected the metrics to be scraped from the pods as long as the /metrics endpoint is alive (even if the pod is still bootstrapping and is not ready).

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod with a startupProbe. Check if Prometheus is scraping it (via PodMonitor) while it's in the middle of that startupProbe.

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
What is in prometheus `/targets` page regarding this PodMonitor when the pod is starting up?
