### ISSUE TITLE
Root AlertmanagerConfig and namespace matcher as optional

### ISSUE THREAD

**Issue by Shashankft9** [prometheus-operator/prometheus-operator#4033]
This is to track the objectives of comment added here: 
https://github.com/prometheus-operator/prometheus-operator/issues/3737#issuecomment-797577859

As I can understand, these are the pointers on which work could be done: 
- adding the `baseAlertmanagerConfiguration` with root `alertmanagerConfigName` as a field in the alertmanager CRD spec. For this particular `alertmanagerConfig`, namespace matcher will be skipped.
- adding `global` and `templates` keys.
- adding `enforcedNamespaceLabel`.

**Comment by LiuVII** [comment]
and update?

**Comment by simonpasquier** [comment]
I believe that the main concerns have been resolved with the latest v0.61.1:
* One can define the main configuration using  `AlertmanagerConfig` CRD (with the `spec.alertmanagerConfiguration` field).
* It is possible to disable the namespace enforcement when AlertmanagerConfig objects are merged in the resulting configuration using `spec.alertmanagerConfigMatcherStrategy.type: None`.
