### ISSUE TITLE
Support authentication using OAuth 2.0

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#4036]
**What is missing?**

Since v2.27.0 (https://github.com/prometheus/prometheus/pull/8761), Prometheus supports OAuth 2.0 authentication for scrapes, remote write, ...

**Why do we need it?**

To be on par with Prometheus capabilities.

**Comment by paulfantom** [comment]
Seems like we need to create new API object and use it in following CRDs:
- Prometheus (for remote-write)
- ServiceMonitor
- PodMonitor
- Probe

OT: Looks to me like we should start working on generic ScrapeConfig so such options could be put in one place and inherited. This should at least simplify adding such features to the last 3 CRDs/APIs.
