### ISSUE TITLE
replicaExternalLabelPrefix

### ISSUE THREAD

**Issue by qudongfang** [prometheus-operator/prometheus-operator#4044]
**What is missing?**

`replicaExternalLabelPrefix ` configuration option.

**Why do we need it?**

Thanos-query running in Kube-mgmt talks to multiple prom clusters across multiple regions.
For example:

- Kube cluster: `us-east-1`

> `replicaExternalLabelPrefix = us-east-1.prom`, and then `prometheus_replica=us-east-1.prom.1`

- Kube cluster: `eu-west-1`

>  `replicaExternalLabelPrefix = eu-west-1.prom`, and then `prometheus_replica=eu-west-1.prom.1`

**Environment**

multiple prom clusters.

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
Do you mean that you want the operator to provide more flexibility when generating the external `prometheus_replica` label (e.g. being able to have `prometheus_replica: us-east-1.$(POD_NAME)`)? 
Why don't you add another external label (using `externalLabels`) which indicates the region/zone?

**Comment by qudongfang** [comment]
Thanks for the suggestion. This works fine.

> `prometheus_replica: us-east-1.$(POD_NAME)`)?

At the same time, The `$(POD_NAME)`  seems to be unreasonably long to me in my case `prometheus-${releaseName}-kube-prom-prometheus-0`.

It would be **nice to have** some flexibility to customize it.
