### ISSUE TITLE
slack_api_url_file value is missing

### ISSUE THREAD

**Issue by BenCoughlan15** [prometheus-operator/prometheus-operator#4045]
**What happened?**

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

Use config from here: 
https://github.com/prometheus/alertmanager/commit/59c7fd5053d503037702ad10e4a733aac89e615a

* Prometheus Operator Logs:

```
failed: provision alertmanager configuration: base config from Secret could not be parsed: yaml: unmarshal errors:\n  line 2: field slack_api_url_file not found in type config.plain"
```

**Anything else we need to know?**:

the file to change is : https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/alertmanager/types.go

The code changes are: 

line 54 : SlackAPIURLFile  string          `yaml:"slack_api_url_file,omitempty" json:"slack_api_url_file,omitempty"`

line158: 	APIURLFile    string            `yaml:"api_url_file,omitempty" json:"api_url_file,omitempty"`

**Comment by simonpasquier** [comment]
Thanks for the report. Do you want to tackle it?

**Comment by BenCoughlan15** [comment]
Sure, but I can't see how to raise a PR 🤔

**Comment by djamaile** [comment]
If @BenCoughlan15 doesn't want to, I can pick this up?

**Comment by paulfantom** [comment]
@djamaile go for it! If you need help, feel free to ping us in `#prometheus-operator-dev` channel on [kubernetes slack](http://slack.k8s.io/).

**Comment by djamaile** [comment]
Oh sorry didn't see I could pick this up. Will go at it now, if I need any help I will look for it in the slack channel 👍

**Comment by Wikiwix** [comment]
This issue is still relevant. Looks more like the WIP fix is stale 🙁
