### ISSUE TITLE
Setting the `--storage.tsdb.no-lockfile` isn't necessary anymore

### ISSUE THREAD

**Issue by beorn7** [prometheus-operator/prometheus-operator#4048]
**What happened?**

The operator sets the `--storage.tsdb.no-lockfile` flag, which needlessly disables the check for multiple instances of Prometheus using the same data directory.

**Did you expect to see something different?**

Not set the `--storage.tsdb.no-lockfile` flag.

**How to reproduce it (as minimally and precisely as possible)**:

Start Prometheus, check out the UI, go to Status → Command Line Flags. Search for `storage.tsdb.no-lockfile`. It is set to `true`.

**Environment**

* Prometheus Operator version:

Any version after PR #855 gat merged.

* Kubernetes version information:

Irrelevant.

* Kubernetes cluster kind:

Irrelevant.

* Manifests:

None are relevant.

* Prometheus Operator Logs:

N/A.

**Anything else we need to know?**:

#855 introduced the flag because Prometheus back then had an unreliable locking implementation. It later reverted to the locking behavior of Prometheus 1.x, which AFAIK never caused any problem anywhere.

**Comment by djamaile** [comment]
Can I pick this up?
