### ISSUE TITLE
`app` label removed from prometheus in 0.48.0 

### ISSUE THREAD

**Issue by keithlayne** [prometheus-operator/prometheus-operator#4050]
I upgraded to 0.48.0 via the prometheus-community/kube-prometheus-stack chart, and experienced breakage because the `app` label was removed from prometheus, and service selectors no longer matched. This seems like an unintentional break.

@metalmatze suggested I file an issue here.

I missed this line in the release notes, or I would have been more confused:

> Deprecation notice:
app labels will be removed in v0.50.

See also:

prometheus-community/helm-charts#1009
prometheus-community/helm-charts#1010

**Environment**

* Prometheus Operator version: `0.48.0`

* Kubernetes version information: `1.20.6`

* Kubernetes cluster kind: `kops`

* Manifests: N/A

* Prometheus Operator Logs: N/A

**Comment by simonpasquier** [comment]
I can confirm that the breakage wasn't intentional. We'll work on a v0.48.1 patch release.

**Comment by keithlayne** [comment]
C'mon github, you're supposed to close this automatically. Thanks @fpetkovski!
