### ISSUE TITLE
read WAL backfill checkpoint read records corruption in segment

### ISSUE THREAD

**Issue by anothersrewhocancode** [prometheus-operator/prometheus-operator#4053]
**What happened?**
one instance of Prometheus is going in CrashLoopBackOff

**Did you expect to see something different?**
yes to see it running

**How to reproduce it (as minimally and precisely as possible)**:
kubectl logs prometheus-k8s-1 -c prometheus -n monitoring

**Environment** kops cluster 

* Prometheus Operator version: v2.4.2

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:
Client Version: v1.21.0
Server Version: v1.18.0

    `kubectl version`
    

* Kubernetes cluster kind: kops

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:
* ```
apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"Prometheus","metadata":{"annotations":{},"labels":{"prometheus":"k8s"},"name":"k8s","namespace":"monitoring"},"spec":{"alerting":{"alertmanagers":[{"name":"alertmanager-main","namespace":"monitoring","port":"web"}]},"externalUrl":"http://127.0.0.1:9090","replicas":2,"resources":{"limits":{"cpu":"300m","memory":"900Mi"},"requests":{"cpu":"200m","memory":"800Mi"}},"retention":"168h","ruleSelector":{"matchLabels":{"prometheus":"k8s","role":"prometheus-rulefiles"}},"serviceAccountName":"prometheus-k8s","serviceMonitorSelector":{"matchExpressions":[{"key":"k8s-app","operator":"Exists"}]},"storage":{"class":"ssd","resources":null,"selector":null,"volumeClaimTemplate":{"metadata":{"annotations":{"annotation1":"prometheus"}},"spec":{"resources":{"requests":{"storage":"200Gi"}},"storageClassName":"ssd"}}},"version":"v2.4.2"}}
    creationTimestamp: "2021-05-26T11:45:19Z"
    generation: 11
    labels:
      prometheus: k8s
    name: k8s
    namespace: monitoring
    resourceVersion: "118568453"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/prometheuses/k8s
    uid: 783279b3-ca4e-4a5c-9920-07acf8f451bb
  spec:
    alerting:
      alertmanagers:
      - name: alertmanager-main
        namespace: monitoring
        port: web
    externalUrl: https://prometheus-dev.nrlock.com
    image: quay.io/prometheus/prometheus:v2.4.2
    replicas: 2
    resources:
      limits:
        cpu: 300m
        memory: 7500Mi
      requests:
        cpu: 200m
        memory: 800Mi
    retention: 168h
    ruleSelector:
      matchLabels:
        prometheus: k8s
        role: prometheus-k8s-rules
    securityContext:
      fsGroup: 65534
      runAsGroup: 65534
      runAsNonRoot: true
      runAsUser: 65534
    serviceAccountName: prometheus-k8s
    serviceMonitorSelector:
      matchExpressions:
      - key: k8s-app
        operator: Exists
    storage:
      volumeClaimTemplate:
        metadata: {}
        spec:
          resources:
            requests:
              storage: 200Gi
          storageClassName: ssd
    version: v2.4.2
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:
* level=info ts=2021-05-31T11:28:38.869322801Z caller=main.go:423 msg="Stopping scrape discovery manager..."
level=info ts=2021-05-31T11:28:38.869389458Z caller=main.go:437 msg="Stopping notify discovery manager..."
level=info ts=2021-05-31T11:28:38.869402714Z caller=main.go:459 msg="Stopping scrape manager..."
level=info ts=2021-05-31T11:28:38.869414374Z caller=main.go:433 msg="Notify discovery manager stopped"
level=info ts=2021-05-31T11:28:38.86945039Z caller=main.go:419 msg="Scrape discovery manager stopped"
level=info ts=2021-05-31T11:28:38.869480606Z caller=manager.go:638 component="rule manager" msg="Stopping rule manager..."
level=info ts=2021-05-31T11:28:38.869503638Z caller=manager.go:644 component="rule manager" msg="Rule manager stopped"
level=info ts=2021-05-31T11:28:38.869525916Z caller=notifier.go:512 component=notifier msg="Stopping notification manager..."
level=info ts=2021-05-31T11:28:38.869544522Z caller=main.go:608 msg="Notifier manager stopped"
level=info ts=2021-05-31T11:28:38.869559395Z caller=main.go:453 msg="Scrape manager stopped"
level=error ts=2021-05-31T11:28:38.869804466Z caller=main.go:617 err="opening storage failed: read WAL: backfill checkpoint: read records: corruption in segment 2 at 31837470: unexpected full record"

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
the only solution is to delete your /prometeus/wal directory. There's little that the operator can do here.

**Comment by paulfantom** [comment]
Closing as the issue appears to be answered. If you need additional help, please reopen this issue or contact us in `#prometheus-operator` channel on [kubernetes slack](http://slack.k8s.io/).
