### ISSUE TITLE
Add end-to-end test to verify the upgrade from the current stable version to the next one

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#4067]
**What is missing?**

As per $TITLE, we don't exercise the upgrade path in the e2e tests.

**Why do we need it?**

#4050 is a regression introduced in v0.48.0 (fixed by #4055) that could have been caught earlier instead of breaking end-users.

**Comment by mikechengwei** [comment]
I think i can do it.
