### ISSUE TITLE
Please support multiple in Additional Scrape Configuration

### ISSUE THREAD

**Issue by xuanyuanaosheng** [prometheus-operator/prometheus-operator#4072]
I found and test that the additional scrape configurations only support one secret at https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/additional-scrape-config.md.

Could you please support multiple prometheus-additional.yaml ?  This can better classify the different monitor point.

**Comment by paulfantom** [comment]
IMHO it would be better to focus on https://github.com/prometheus-operator/prometheus-operator/issues/2787 and deprecate `AdditionalScrapeConfig` completely.

**Comment by simonpasquier** [comment]
Closing it now that we have the ScrapeConfig CRD.
