### ISSUE TITLE
Support mute_time_intervals syntax (AlertManager >= v0.22.0)

### ISSUE THREAD

**Issue by eugenberend** [prometheus-operator/prometheus-operator#4078]
**What happened?**

An option `mute_time_intervals` new for Alertmanager v0.22.0 cannot be applied if prometheus-operator is used:

```
level=error ts=2021-06-07T15:10:58.004349204Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"******/prometheus-operator-alertmanager\" failed: provision alertmanager configuration: base config from Secret could not be parsed: yaml: unmarshal errors:\n line 80: field mute_time_intervals not found in type config.plain\n line 133: field mute_time_intervals not found in type config.plain"
```

and this configuration option does not appear in the actual config after deploy.

**Did you expect to see something different?**

I expected that this option would be passed into AM config.

**How to reproduce it (as minimally and precisely as possible)**:

* specify `mute_time_intervals` in alertmanager values
* apply configuration with `helm install` or whatever you use

**Environment**

* Prometheus Operator version:

v0.47.0

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

managed

**Comment by eugenberend** [comment]
@paulfantom @simonpasquier Hi guys, it would be cool if you approve [this](feat: Add support for mute_time_intervals, target_matchers and source_matchers Alertmanager config #4111) PR from @Jammicus ❤️

**Comment by simonpasquier** [comment]
Closed by https://github.com/prometheus-operator/prometheus-operator/pull/4335
