### ISSUE TITLE
Support target_matchers and source_matchers syntax (Alertmanager >= v0.22.0) in AlertmanagerConfig CRD

### ISSUE THREAD

**Issue by tbuchier** [prometheus-operator/prometheus-operator#4087]
**What happened?**
Hello, I'm trying to set some inhibit_rules using the new syntax in 0.22.0:
https://prometheus.io/docs/alerting/latest/configuration/#inhibit_rule
where `target_match` , `source_match` have been deprecated and replaced by:
`target_matchers` and `source_matchers` that now support PromQL syntax for matching.

However the AlertmanagerConfig don't support them:

```
❯ kubectl explain alertmanagerconfig.spec.inhibitRules
KIND:     AlertmanagerConfig
VERSION:  monitoring.coreos.com/v1alpha1

RESOURCE: inhibitRules <[]Object>

DESCRIPTION:
     List of inhibition rules. The rules will only apply to alerts matching the
     resource’s namespace.

     InhibitRule defines an inhibition rule that allows to mute alerts when
     other alerts are already firing. See
     https://prometheus.io/docs/alerting/latest/configuration/#inhibit_rule

FIELDS:
   equal	<[]string>
     Labels that must have an equal value in the source and target alert for the
     inhibition to take effect.

   sourceMatch	<[]Object>
     Matchers for which one or more alerts have to exist for the inhibition to
     take effect. The operator enforces that the alert matches the resource’s
     namespace.

   targetMatch	<[]Object>
     Matchers that have to be fulfilled in the alerts to be muted. The operator
     enforces that the alert matches the resource’s namespace.

```

So the config changes are ignored..

**How to reproduce it (as minimally and precisely as possible)**:
Deploy Prom-operator in v0.48.0, use a simple Alertmanager config that use the new matchers such as:
https://github.com/prometheus/alertmanager/blob/master/doc/examples/simple.yml

* Prometheus Operator version: 
v0.48.0

Thanks

**Comment by paulfantom** [comment]
It is not a bug as prometheus-operator does not support alertmanager v0.22 yet.

Issue relates to https://github.com/prometheus-operator/prometheus-operator/issues/4078

**Comment by brunokoeferli** [comment]
The support for the new `matchers` syntax inside `route` block is also missing. Can it be added within the same feature or should I open a new one?

**Comment by simonpasquier** [comment]
@brunokoeferli yes it should be covered by this issue IMHO.
