### ISSUE TITLE
Add support for CRI-O metrics

### ISSUE THREAD

**Issue by saschagrunert** [prometheus-operator/prometheus-operator#4088]
**What is missing?**

The operator synchronizes the kubelet endpoints via the `--kubelet-service` flag:

https://github.com/prometheus-operator/prometheus-operator/blob/5f8ce3a01c88d99060e253a010f9d6f3c906f80f/pkg/prometheus/operator.go#L584-L675

We have the same issue with CRI-O metrics, which should live in it's own `ServiceMonitor` object in the future. To achieve this, we would have to change the operator to allow synchronizing the endpoints for the container runtime.

**Why do we need it?**

There is no other clear way to build a service containing all node IPs targeting a specific port.

**Comment by paulfantom** [comment]
> There is no other clear way to build a service containing all node IPs targeting a specific port.

If you have one service for which you are sure to have endpoints on all nodes (like the kubelet Service), you can attach relabelings to the ServiceMonitor and gather metrics from other endpoints, example: https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/control-plane/service-monitor-kubelet.yaml#L95-L116. Alternatively you can deploy Service and manage Endpoint objects manually.

I don't think it is a good idea to implement CRI-specific features in prometheus-operator.

**Comment by saschagrunert** [comment]
Yes, thats how it works today. AFAIU the goal is to have CRI-O metrics living in its own `ServiceMonitor`. For that we need a Service referencing all nodes as endpoints on a specific port, right? How could we achieve that without touching the operator code?

**Comment by paulfantom** [comment]
Prometheus-operator is not about managing CRI-O nor about governing resources belonging solely to CRI-O, hence I don't see why it should deploy Service object for CRI-O.

In the case of Service object for kubelet, it is needed by the operator for the correct operation of the operator and it is not deployed only to get metrics from kubelet.

**Comment by saschagrunert** [comment]
Got it, thank you for the clarification @paulfantom. Do you think that using a service monitor is the wrong approach, if we assume that we serve CRI-O metrics via TLS for each node?

**Comment by paulfantom** [comment]
Using ServiceMonitor is a correct approach and TLS has nothing to do with it :) This is more about what object is deployed in a cluster. Since CRI-O is not deployed as Pods then PodMonitor cannot be used, however, as Service can be provisioned by a third party then ServiceMonitor is a good choice here.

As for TLS, it already looks like you need some third party to provision at least 3 objects into a cluster:
- Service
- Secret with TLS data
- ServiceMonitor referencing Service and Secret

**Comment by saschagrunert** [comment]
This makes sense, we will move forward without changing anything within this operator, thank you again!
