### ISSUE TITLE
Emit event on silence creation

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#4094]
**What is missing?**

I think it would be nice to emit a kuberentes event when alertmanager silence is created/updated. 

**Why do we need it?**

To offer better integration of silences with kubernetes ecosystem

**Environment**

* Prometheus Operator version: all

    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:

In some way this relates to https://github.com/prometheus-operator/prometheus-operator/issues/3335 as in both cases we first need a reliable way of communicating with operands APIs.

**Comment by simonpasquier** [comment]
I'm not sure that it's something the operator should be responsible for since silences are out of its scope (unless we revisit #2398)

**Comment by paulfantom** [comment]
I think #2398 is orthogonal. That issue is about translating K8S API into alertmanager API. This is in the other direction, Alertmanager API -> K8S object, so more like getting status information and appending it to CR. However, since silences have TTL and events have TTL it looked to me like a better match than `.Status`

**Comment by simonpasquier** [comment]
Not completely orthogonal IMO since both issues mean that the operator would be responsible for interacting with the Alertmanager API to create/update Kube resources. For now, I'm not sure that it falls under the responsibilities of the Prometheus operator. My take would be that the [silence-operator](https://github.com/giantswarm/silence-operator) is the right place to hook this up.

**Comment by paulfantom** [comment]
> both issues mean that the operator would be responsible for interacting with the Alertmanager API to create/update Kube resources.

I don't fully agree. In the case of creating silences via CRD, it is a user who creates kubernetes object, not the prometheus-operator. In case of this issue, the user creates silence in alertmanager API, and prometheus-operator only translates it into k8s object. To me, this feature is more of an advanced `.Status` than anything else. 

As for silence-operator, it is responsible for declaratively creating silences, which means there is already an object in kubernetes created by the user that is mapping to alertmanager silence and it would be good only to populate this object `.Status`. I don't see what event should be emitted there as the action is started by the user using k8s API.

That said I started to think if this wouldn't be an abuse of the k8s event system. Silence isn't really related to k8s, so maybe emitting an event isn't a good idea at all :thinking:
