### ISSUE TITLE
Remove po-lint

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#4099]
`po-lint` was useful when there was no tools like [`kubeconform`](https://github.com/yannh/kubeconform) (which we use in kube-prometheus project). And support for CRDs in kubernetes was at earlier stage. Right now `po-lint` seems like a largely unused code.

We would need to change docs at https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/linting.md to point to `kubconform` and it's usage. This should be fairly easy as we already have usage example in https://github.com/prometheus-operator/kube-prometheus/blob/main/Makefile#L41-L43

**Comment by slashpai** [comment]
I am taking this one

**Comment by slashpai** [comment]
> I am taking this one

I will wait till discussion is finalised in https://github.com/prometheus-operator/prometheus-operator/pull/4060 to start with this one

**Comment by slashpai** [comment]
We don't generate schemas as in kube-prometheus right? I tried it locally to see how it works so without ignore option it has larger number of failures

```go
░▒▓    ~/gi/s/prometheus-operator  on   remove_polint !1 ?1  kubeconform -kubernetes-version "1.20.0" -skip CustomResourceDefinition -summary example 
example/additional-scrape-configs/prometheus-additional.yaml - failed validation: error unmarshalling resource: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type map[string]interface {}
example/mixin/alerts.yaml - failed validation: error while parsing: missing 'kind' key
example/additional-scrape-configs/prometheus.yaml - Prometheus prometheus failed validation: could not find schema for Prometheus
example/non-rbac/prometheus.yaml - Prometheus main failed validation: could not find schema for Prometheus
example/rbac/prometheus/prometheus.yaml - Prometheus prometheus failed validation: could not find schema for Prometheus
example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml - ServiceMonitor prometheus-operator failed validation: could not find schema for ServiceMonitor
example/storage/persisted-prometheus.yaml - Prometheus persisted failed validation: could not find schema for Prometheus
example/thanos/prometheus-servicemonitor.yaml - ServiceMonitor prometheus-self failed validation: could not find schema for ServiceMonitor
example/thanos/prometheus.yaml - Prometheus self failed validation: could not find schema for Prometheus
example/thanos/prometheus-rule.yaml - PrometheusRule prometheus-example-alerts failed validation: could not find schema for PrometheusRule
example/thanos/thanos-ruler.yaml - ThanosRuler thanos-ruler failed validation: could not find schema for ThanosRuler
example/user-guides/alerting/alertmanager-config-example.yaml - AlertmanagerConfig config-example failed validation: could not find schema for AlertmanagerConfig
example/user-guides/alerting/alertmanager.yaml - failed validation: error while parsing: missing 'kind' key
example/user-guides/alerting/prometheus-example-rules.yaml - PrometheusRule prometheus-example-rules failed validation: could not find schema for PrometheusRule
example/user-guides/alerting/prometheus-example.yaml - Prometheus example failed validation: could not find schema for Prometheus
example/user-guides/alerting/alertmanager-example.yaml - Alertmanager example failed validation: could not find schema for Alertmanager
example/user-guides/getting-started/example-app-service-monitor.yaml - ServiceMonitor example-app failed validation: could not find schema for ServiceMonitor
example/user-guides/getting-started/prometheus-admin-api.yaml - Prometheus prometheus failed validation: could not find schema for Prometheus
example/user-guides/getting-started/prometheus-pod-monitor.yaml - Prometheus prometheus failed validation: could not find schema for Prometheus
example/user-guides/getting-started/prometheus-service-monitor.yaml - Prometheus prometheus failed validation: could not find schema for Prometheus
example/user-guides/alerting/alertmanager-selector-example.yaml - Alertmanager example failed validation: could not find schema for Alertmanager
example/user-guides/getting-started/example-app-pod-monitor.yaml - PodMonitor example-app failed validation: could not find schema for PodMonitor
Summary: 64 resources found in 61 files - Valid: 34, Invalid: 0, Errors: 22, Skipped: 8

░▒▓    ~/gi/s/prometheus-operator  on   remove_polint !1 ?1       
```


with ignore missing schemas option

```go
░▒▓    ~/gi/s/prometheus-operator  on   remove_polint !1 ?1  kubeconform -kubernetes-version "1.20.0" -skip CustomResourceDefinition -ignore-missing-schemas -summary example
example/additional-scrape-configs/prometheus-additional.yaml - failed validation: error unmarshalling resource: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type map[string]interface {}
example/mixin/alerts.yaml - failed validation: error while parsing: missing 'kind' key
example/user-guides/alerting/alertmanager.yaml - failed validation: error while parsing: missing 'kind' key
Summary: 64 resources found in 61 files - Valid: 34, Invalid: 0, Errors: 3, Skipped: 27

░▒▓    ~/gi/s/prometheus-operator  on   remove_polint !1 ?1 
░▒▓    ~/gi/s/prometheus-operator  on   remove_polint !1 ?1         
```

@paulfantom Should we add example with missing schemas or add option to generate schema and then validate?

**Comment by paulfantom** [comment]
We do not, we only generate CRDs. I believe schemas are out of scope and can be easily created from CRDs if needed (Take a look at https://github.com/prometheus-operator/kube-prometheus/blob/main/scripts/generate-schemas.sh and https://github.com/yannh/kubeconform/blob/master/scripts/openapi2jsonschema.py)

**Comment by slashpai** [comment]
I checked https://github.com/prometheus-operator/kube-prometheus/blob/main/scripts/generate-schemas.sh but I was wondering if need to have it here just for the user to verify or just skip them like this run below

```
░▒▓    ~/gi/s/prometheus-operator  on   remove_polint !1 ?1  kubeconform -kubernetes-version "1.20.0" -skip CustomResourceDefinition -ignore-missing-schemas -summary example
example/additional-scrape-configs/prometheus-additional.yaml - failed validation: error unmarshalling resource: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type map[string]interface {}
example/mixin/alerts.yaml - failed validation: error while parsing: missing 'kind' key
example/user-guides/alerting/alertmanager.yaml - failed validation: error while parsing: missing 'kind' key
Summary: 64 resources found in 61 files - Valid: 34, Invalid: 0, Errors: 3, Skipped: 27

░▒▓    ~/gi/s/prometheus-operator  on   remove_polint !1 ?1 
```

**Comment by paulfantom** [comment]
Skipping doesn't make any sense. Especially since `po-lint` was created to validate CRs which we would be skipping with `kubeconform` when there are no schemas.

As a stop-gap I would propose to include following in a documentation document:
- an amended version of https://github.com/prometheus-operator/kube-prometheus/blob/main/scripts/generate-schemas.sh to generate schema files using CRDs from https://github.com/prometheus-operator/prometheus-operator/tree/master/jsonnet/prometheus-operator.
- instruction how to use those with `kubeconform` - basically this command: https://github.com/prometheus-operator/kube-prometheus/blob/main/Makefile#L43

And if we see that users are using this in the field, we can get back to including schemas in a permanent place.

Personally, I would love to see improvements in what is generated from CRDs and how it is hosted. This includes `API.md` and schemas. For example, we could leverage https://github.com/giantswarm/crd-docs-generator or alike to generate API docs and link to schemas there or sth like that. Either way, I feel this needs a permanent home/link and some discussion on how to structure it correctly so we don't break user workflows. WDYT about opening a new issue about it?

**Comment by james-callahan** [comment]
I see the use-case for `po-lint` as possible to grow, e.g. it could do more detailed linting of prometheus rules (like `cortextool check`/`cortextool lint`).

Is there some tool that is part of prometheus-operator that I can use to convert e.g. a `PrometheusRule` resource to a prometheus config file?

**Comment by paulfantom** [comment]
> I see the use-case for po-lint as possible to grow, e.g. it could do more detailed linting of prometheus rules (like cortextool check/cortextool lint).

I agree that it would be ideal. However, the problem is that it is not maintainable in the long run as we would need to create and keep up to date a tool that is built from multiple other tools. IMHO it is easier to give people the ability to convert `PrometheusRule` into the native prometheus format (described below) and allow them to use tools like `cortextool` or `promtool` directly.

---
> Is there some tool that is part of prometheus-operator that I can use to convert e.g. a PrometheusRule resource to a prometheus config file?

`PrometheusRule` is a simple wrapper on prometheus rules groups. So doing the following gives rules file:
```shell
cat "PrometheusRuleFile.yaml" | gojsontoyaml -yamltojson | jq '.spec.groups'
# or
cat "PrometheusRuleFile.yaml" | yq e '.spec.groups'
# or
kubectl get prometheusrule <name> -o json | jq '.spec.groups'
```

Side note: I am using a fairly simple script to do validation with `promtool` across all `PrometheusRule` files found in the repository with https://github.com/thaum-xyz/ankhmorpork/blob/master/hack/verify-prometheus-rules.sh

**Comment by james-callahan** [comment]
> `PrometheusRule` is a simple wrapper on prometheus rules groups. So doing the following gives rules file:
> 
> ```shell
> cat "PrometheusRuleFile.yaml" | gojsontoyaml -yamltojson | jq '.spec.groups'
> # or
> cat "PrometheusRuleFile.yaml" | yq e '.spec.groups'
> # or
> kubectl get prometheusrule <name> -o json | jq '.spec.groups'
> ```

As far as I know, things are slightly different, particularly snake_case vs camelCase.

**Comment by paulfantom** [comment]
> As far as I know, things are slightly different, particularly snake_case vs camelCase.

That is true for all prometheus-operator CRD apart from `PrometheusRule` one. The `PrometheusRule` is a simple wrapper as seen for example in API docs: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusrulespec

As for snake_case vs camelCase, all native prometheus fields in rule objects are single word keys, hence they are snake_case and camelCase at the same time ;) This breaks with non-prometheus native key of `partial_response_strategy` used by Thanos Ruler, but this case is one of few exceptions where operator CRD is using snake_case instead of camelCase.

**Comment by FUSAKLA** [comment]
Hi, just wondering if it is planned to add any documentation about how to replace the po-lint functionality?
It's a bit unfortunate that it was just removed from documentation with no other note about how to solve the issue :/
