### ISSUE TITLE
Support label_limit, label_name_length_limit and label_value_length_limit configuration fields

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#4107]
**What is missing?**

Prometheus v2.27.0 introduced 3 new configuration fields to prevent Prometheus from ingesting metrics with "excessive" labels:
* `label_limit`
* `label_name_length_limit` 
* `label_value_length_limit`

The Prometheus operator should expose these fields in its CRDs.

See https://github.com/prometheus/prometheus/issues/8291 for details.

**Why do we need it?**

Feature parity with Prometheus :)

**Environment**

* Prometheus Operator version:

N/A

**Anything else we need to know?**:

Like with `enforcedSampleLimit` and `sampleLimit`, we want to enforce minimal values at the Prometheus CRD level as well as support individual limits per ServiceMonitor, PodMonitor and Probe resources.

**Comment by slashpai** [comment]
If this not urgent I would like to work on it to get better understanding of CRDs :)
