### ISSUE TITLE
Unable to migrate metrics data from existing EBS volume 

### ISSUE THREAD

**Issue by vinga2805** [prometheus-operator/prometheus-operator#4125]
Steps I followed:

===================

1. Took the snapshot of the volume before deleting the stable/prometheus
2. Created a new AWS EBS volume 
3. Created PV.

===============

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage
  labels:
     app: prometheus-storage
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://ap-south-1a/vol-*************
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  volumeMode: Filesystem

========

 4. Added storagespec in the values.yaml

========

     storageSpec:
      volumeClaimTemplate:
        spec:
                #storageClassName: prometheus
          volumeName: prometheus-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
              #  selector: {}

=========
5. Installed the chart

======

helm install prometheus prometheus-community/prometheus-operator -n prometheus -f prod_values.yaml

=======

6. I see now PVC getting created and status in bound

=========

ubuntu@ip-172-31-39-123:~/ct-prom$ kubectl  get pvc -n prometheus
NAME                                                                                                     STATUS   VOLUME               CAPACITY   ACCESS MODES   STORAGECLASS   AGE
prometheus-prometheus-prometheus-oper-prometheus-db-prometheus-prometheus-prometheus-oper-prometheus-0   Bound    prometheus-storage   20Gi       RWO            gp2            36m

=========

Problem:
========

1. When I exec inside the pod i dont see the volume getting mounted inside /prometheus folder.
2. Ideally it should have created a directory /prometheus/prometheus-db 

===========

/prometheus $ df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  20.0G      5.9G     14.1G  29% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     3.9G         0      3.9G   0% /sys/fs/cgroup
/dev/xvdbq               19.6G    221.1M     19.3G   1% /prometheus

===========

===========

/prometheus $ ls -ltr /prometheus/
total 32
-rw-rw-r--    1 nobody   2000             0 Jun 23 04:58 lock
drwxrwsr-x    2 nobody   2000          4096 Jun 23 04:58 chunks_head
drwxr-sr-x    3 1000     2000          4096 Jun 23 05:33 01F8VNQXVH9B8VAAAY0CTBWAT4
drwxrwsr-x    3 1000     2000          4096 Jun 23 05:33 wal
-rw-rw-r--    1 1000     2000         20001 Jun 23 06:01 queries.active

========

**Comment by fpetkovski** [comment]
Hi @vinga2805, is the volume getting properly attached to the container? Can you check this in the pod definition?

**Comment by paulfantom** [comment]
Linking slack conversation for anyone who wants to help: https://kubernetes.slack.com/archives/CFFDS2Z7F/p1624428278449300
