### ISSUE TITLE
Probe Sharding

### ISSUE THREAD

**Issue by fenfir** [prometheus-operator/prometheus-operator#4126]
**What is missing?**

I am missing the ability to shard metrics from Probes. 

**Why do we need it?**

We are using an instance of prometheus-operater with 2 shards and our Probe scrapes are getting duplicated. I see that this has been handled for PodMetrics and ServiceMontiors. 

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:

I am willing to do the work but would like some guidance on how to approach it. Since there is already a function to generate the shard relabel configs, I see 2 possibilites:

1. Apply the config as it is normally applied with `__address__` and the user will need to add a `__address__` label
2. Extend the function and the Probe CRD to have a shardLabel field that is passed to the shard function instead of `__address__`

**Comment by simonpasquier** [comment]
Good question! I would expect that we apply the hashmod function to the `__param_target` label instead of `__address__` for regular targets. @lilic WDYT?
