### ISSUE TITLE
Prometheus pod going down due to compaction

### ISSUE THREAD

**Issue by vignesh-v-nutanix** [prometheus-operator/prometheus-operator#4139]
```
level=info ts=2021-06-29T12:14:19.081Z caller=manager.go:934 component="rule manager" msg="Stopping rule manager..."
level=info ts=2021-06-29T12:14:19.081Z caller=main.go:706 msg="Scrape manager stopped"
level=info ts=2021-06-29T12:14:21.687Z caller=manager.go:944 component="rule manager" msg="Rule manager stopped"
level=error ts=2021-06-29T12:14:25.801Z caller=db.go:780 component=tsdb msg="compaction failed" err="compact head: persist head block: 2 errors: populate block: context canceled; context canceled"
level=info ts=2021-06-29T12:15:07.572Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."
level=info ts=2021-06-29T12:15:07.573Z caller=main.go:885 msg="Notifier manager stopped"
level=info ts=2021-06-29T12:15:07.666Z caller=main.go:897 msg="See you next time!"```
I keep getting this error and the pods are getting restarted

**Comment by vignesh-v-nutanix** [comment]
yes i have i get this error, right now
```level=error ts=2021-06-30T05:18:30.321Z caller=head.go:746 component=tsdb msg="Loading on-disk chunks failed" err="iterate on on-disk chunks: corruption in head chunk file /prometheus/chunks_head/000582: out of sequence m-mapped chunk for series ref 2090695"```

**Comment by coderanger** [comment]
I already responded on Slack. You'll likely need to remove corrupted blocks from your Prometheus database however assisting with this is out of scope for us as a project IMO. We don't know your requirements or how corrupted your DB is so I encourage you to do some research and work out a repair plan.
