### ISSUE TITLE
Consider turning on dependabot

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#4141]
**What is missing?**

Automated tracking of dependency releases

**Why do we need it?**

To simplify the release process and update dependencies earlier in the development process. This has a potential to find bugs introduced by dependencies earlier in the development process.

**Environment**

All

**Anything else we need to know?**:

dependabot is a native github feature now - https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates

/cc @brancz @metalmatze @simonpasquier

**Comment by paulfantom** [comment]
With this proposal, PRs like https://github.com/prometheus-operator/prometheus-operator/pull/4142 would be automated.

**Comment by simonpasquier** [comment]
I'm all for reducing toil. It might not be able to resolve all the things (e.g. not sure how it deals with `replace`) but it's worth trying.

**Comment by simonpasquier** [comment]
this is done
