### ISSUE TITLE
Validating Url in alertmanagerconfig

### ISSUE THREAD

**Issue by just1900** [prometheus-operator/prometheus-operator#4153]
**What is missing?**
we need to validate url in alertmanagerconfig.

I find there are some check logic already, like `checkWechatConfigs`
https://github.com/prometheus-operator/prometheus-operator/blob/2388bfa557c9836d5ff01e620a129d33852670ff/pkg/alertmanager/operator.go#L1176-L1185
but  the check logic in `checkWechatConfigs` is actually different than the logic in alertmanager, which check the scheme of an url additionally.
https://github.com/prometheus/alertmanager/blob/8491f816296b26bd4efe3aa4164fe72a7cd329de/config/config.go#L541-L553

Besides, there are also other kind of configs' checking are missing, like webhook
https://github.com/prometheus-operator/prometheus-operator/blob/2388bfa557c9836d5ff01e620a129d33852670ff/pkg/alertmanager/operator.go#L1154-L1174

**Why do we need it?**
Just running into an issue, here are logs from alertmanager during restart
```
level=error ts=2021-07-07T08:01:25.728Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="unsupported scheme \"\" for URL"
```
As a result, I think we also need to validate the url pattern configured in receiver, otherwise, alertmanager may be hang on the status of CrashLoopBackOff after restart.

* Prometheus Operator version:
My version is v0.47.0, the code above referenced from branch `master`, seems like no difference.

**Comment by paulfantom** [comment]
I feel like the admission webhook is a way to go here. Maybe you want to pick up https://github.com/prometheus-operator/prometheus-operator/issues/3710 ?

**Comment by just1900** [comment]
@paulfantom as I mentioned there, I think it's also reasonable to check before rendering alertmanagerconfig into alertmanager's config. How do you think?

**Comment by paulfantom** [comment]
I think those two things are not excluding each other. We can have a safety check on operator side as a last resort, but having admission webhook is causing a faster feedback loop. With webhook, we can immediately notify user that the configuration is incorrect (`kubectl apply` can error out), whereas with operator we can only note this in log messages.

Additionally from maintainer POV it is less code to manage as we don't need to care about keeping sync of this logic across multiple alertmanager version :)

**Comment by just1900** [comment]
Yes, it's absolutely not excluding, and should be better to have a webhook to gain the fail-fast ability.
So, let's revisit #3710, any ideas about the current state of the webhook?
