### ISSUE TITLE
It's not possible to do `kubectl rollout restart` on the managed statefulsets

### ISSUE THREAD

**Issue by mujx** [prometheus-operator/prometheus-operator#4155]
**What happened?**

It seems that the operator isn't propagating the restart on all the pods and only the pod with the highest ordinal number is restarted.

**Did you expect to see something different?**

I'm expecting `kubectl rollout restart sts` to perform a restart on all the pods.

**How to reproduce it (as minimally and precisely as possible)**:

- Install prometheus operator with more than one replicas for prometheus and alertmanager (or use `kube-prometheus-stack`)
- Run `kubectl rollout restart sts <alertmanager_sts or prometheus_sts>`

* Prometheus Operator version: `v0.46.0`
    
    

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by paulfantom** [comment]
I can confirm this is the case on 0.49.0.

Out of curiosity, why the pod restart is necessary in your case? Operator and config-reloader should handle restarts and reloads when needed, so I wonder what is the case that is not covered.

**Comment by mujx** [comment]
I'm running some authentication sidecars on the statefulsets and an automatic reload mechanism is not yet implemented.

**Comment by fpetkovski** [comment]
The way `kubectl rollout restarts` works is by adding an annotation on the pods managed by the deplotyment/statefulset. The operator is not detecting this field as being managed by someone so it removes it. I assume this is why the statefulset starts to rollout and then stops after the first pod is replaced.

**Comment by paulfantom** [comment]
I did not check in the code, but if what @fpetkovski is saying is correct then we have incorrect handling of metadata and we should possibly port solution from https://github.com/openshift/cluster-monitoring-operator/blob/2f35619d5b51058f918acbdb794109d5a6c8f163/pkg/client/client.go#L1347-L1366 to prometheus-operator. Any takers for creating a PR?

**Comment by mujx** [comment]
I can take a look @paulfantom
