### ISSUE TITLE
Operator doesn't delete admission secret created by it on uninstalling the operator

### ISSUE THREAD

**Issue by VineethReddy02** [prometheus-operator/prometheus-operator#4161]
**What happened?**
Prometheus-Operator created the TLS secret for admission webhooks i.e. `release1-kube-prometheus-admission` (note I am using Prometheus-Operator as a part of Kube-Prometheus stack). But on uninstalling the prometheus-operator the secret created by the operator isn't deleted. 

**Did you expect to see something different?**
I expect the secret created by the operator needs to be deleted while uninstalling the operator. 

**How to reproduce it (as minimally and precisely as possible)**:
Installing the Operator and uninstalling it. 

**Environment**

* Prometheus Operator version:
`quay.io/prometheus-operator/prometheus-operator:v0.47.0`

**Comment by fpetkovski** [comment]
Hi @VineethReddy02, the operator does not create and manage the webhook. As described in the [user guide]( https://github.com/prometheus-operator/prometheus-operator/blob/release-0.47/Documentation/user-guides/webhook.md), the tls secret and admission webhooks need to be created by a different user (or operator), and therefore cleaned up by that user (or operator) accordingly during uninstallation.
