### ISSUE TITLE
ConfigReloader does no longer define port name

### ISSUE THREAD

**Issue by joancafom** [prometheus-operator/prometheus-operator#4162]
**What happened?**

Up to version 0.48.1, the ConfigReloader container defined a `containerPort` and assigned the name `reloader-web` to it:

https://github.com/prometheus-operator/prometheus-operator/blob/1e955299682630e4085adc2253f5689031eb0d0e/pkg/operator/statefulset.go#L49-L55

It seems that this behaviour was dropped in the new version 0.49.0, and the container is instantiated without any reference to ports. Hence the mapping between the port name `reloader-web` and the actual port number is lost:

https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/operator/config-reloader.go#L214-L223

This is not something critical at all, but any reference to this port name will fail as it is no longer defined. For instance, if I were to define specific configuration for the `readinessProbe` for this container using [Strategic merge patch](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/strategic-merge-patch.md), referencing to `reloader-web` as the port against which to perform the request will result in K8s being unable to resolve it.

```
...
  Normal   Created    26s               kubelet, minikube  Created container config-reloader
  Normal   Started    26s               kubelet, minikube  Started container config-reloader
  Warning  Unhealthy  4s (x2 over 14s)  kubelet, minikube  Liveness probe errored: strconv.Atoi: parsing "reloader-web": invalid syntax
```

Maybe this is something that was consciously implemented and I lack the context here, but I was just wondering if instead, this behaviour was not included by accident when the old `pkg/operator/statefulset.go` was removed.

https://github.com/prometheus-operator/prometheus-operator/pull/3955/files#diff-6595f2f124c533ff8b163a8126478d8bad06c8cabc3019e06e185cb47f6ec700

**Did you expect to see something different?**

The same behaviour as in previous versions where `containerPort` and its port name mapping, `reloader-web`, were explicitly defined in the container instantiation.

**How to reproduce it (as minimally and precisely as possible)**:

N/A

**Environment**

Any

* Prometheus Operator version:

    `v0.49.0`
    
    

* Kubernetes version information:

    `N/A`
    

* Kubernetes cluster kind:

    N/A

* Manifests:

```
N/A
```

* Prometheus Operator Logs:

```
N/A
```

**Anything else we need to know?**:

**Comment by fpetkovski** [comment]
Hey @joancafom thanks for reporting this. The port was indeed removed in the PR you referenced. Would you be interested in contributing a patch for this? It should be a fairly straightforward fix.

**Comment by joancafom** [comment]
Hi @fpetkovski 

Thanks for your prompt response! Although the changes seem to be fairly straightforward, I reckon I won't have the time to work on them any soon.

**Comment by n1lesh** [comment]
@fpetkovski @simonpasquier: I would like to work on this.

**Comment by fpetkovski** [comment]
Hi @n1lesh, thanks for the initiative. Feel free to submit a PR whenever you have something ready :)
