### ISSUE TITLE
Prometheus default interface for receiving http post

### ISSUE THREAD

**Issue by CarlosEssun** [prometheus-operator/prometheus-operator#4164]
**What did you do?**

In prometheus 2.28.1 version, I can write metric data directly through http post application/x-protobuf /api/v1/wrie. May I ask if the same interface is on prometheus-operator? I directly test /api/v1/wrie and return 404 status code.
**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:
* Version | 2.18.2
* Revision|a6600f564e3c483cc820bae6c7a551db701a22b3
    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
Whether there is a direct write interface, if so, how to enable it or there is a related introduction in the location of the document.
If the current version is not available, whether subsequent versions will consider adding this interface.
Thank you

**Comment by fpetkovski** [comment]
Hi @CarlosEssun, this is a functionality of Prometheus itself, the operator only manages the Prometheus instance. So you can keep using the endpoint on the Prometheus instance created by prometheus-operator, but the operator itself will not support this endpoint.

**Comment by simonpasquier** [comment]
@CarlosEssun are you asking about how to enable the remote write API endpoint in Prometheus?

You should be able to pass the `remote-write-receiver` feature flag like this:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  enableFeatures:
  - remote-write-receiver
  ...
```
