### ISSUE TITLE
Expose Shards as metric

### ISSUE THREAD

**Issue by DWizGuy58** [prometheus-operator/prometheus-operator#4168]
**What is missing?**
Shards defines the number of shards to distribute targets onto. Exposing this as a metric could be useful.

**Why do we need it?**
We noticed that scaling up/down the `shards` by more than 1 requires manual intervention due to data not being resharded to the changed number of shards. We would like to detect when changes to this config are made but not reflected in the number of shards available, indicating that the desired state of shard count has not been reached. This will help us with alerting and detecting when metrics are likely to be missing.

**Environment**

* Prometheus Operator version:
My version is v0.47.0, the code above referenced from branch master, seems like no difference.

**Comment by simonpasquier** [comment]
It looks like a useful metric. Do you want to submit a PR?

**Comment by DWizGuy58** [comment]
yes, I can work on this

**Comment by DWizGuy58** [comment]
#4173
