### ISSUE TITLE
Operator doesn't support matchers field in Alertmanager routes

### ISSUE THREAD

**Issue by yeya24** [prometheus-operator/prometheus-operator#4174]
**What happened?**

I use an alertmanager config with the new `matchers` field. However, the generated secret cannot be parsed by the operator.

I tried the `amtool` and the config file can be parsed successfully. So I assume prometheus operator should support it too, as it is using the same alertmanager version `0.22.2` in its go module.

```
~/prom/alertmanager-0.22.2.darwin-amd64/amtool check-config lib/alertmanager-config.yaml
Checking 'lib/alertmanager-config.yaml'  SUCCESS
Found:
 - global config
 - route
 - 1 inhibit rules
 - 11 receivers
 - 0 templates
```

The error logs are

```
level=error ts=2021-07-16T21:27:30.35212449Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"gitops-platform-metrics/main\" failed: provision alertmanager configuration: base config from Secret could not be parsed: yaml: unmarshal errors:\n  line 12: field matchers not found in type alertmanager.route\n  line 16: field matchers not found in type alertmanager.route\n  line 20: field matchers not found in type alertmanager.route\n  line 25: field matchers not found in type alertmanager.route\n  line 28: field matchers not found in type alertmanager.route\n  line 31: field matchers not found in type alertmanager.route\n  line 34: field matchers not found in type alertmanager.route\n  line 37: field matchers not found in type alertmanager.route\n  line 40: field matchers not found in type alertmanager.route\n  line 43: field matchers not found in type alertmanager.route\n  line 46: field matchers not found in type alertmanager.route\n  line 49: field matchers not found in type alertmanager.route\n  line 53: field matchers not found in type alertmanager.route"
```

**How to reproduce it (as minimally and precisely as possible)**:

Use a config that consists of `matchers` field.

**Environment**

* Prometheus Operator version:

    Tested in `0.48.1` and `0.49.0`

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by yeya24** [comment]
OK. Looks like this is expected as we are still using the old config format https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/alertmanager/types.go#L66.

But `AlertmanagerConfig` already switches to the new config format. When will it be available for secrets?

**Comment by LinAnt** [comment]
AlertmanagerConfig would work, but since there is no way of dropping the namespace from the generated routes, we cannot use them :/

Something like https://github.com/prometheus-operator/prometheus-operator/issues/4033 would be an excellent solution for us :+1:

**Comment by buckner** [comment]
I'm running into this same issue. Anyone know if there is any traction or progress on making matchers available for secrets?
