### ISSUE TITLE
Delegate admission webhook handling to a separate binary

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#4182]
**What is missing?**

Simple ("one-click install") way to deploy admission webhook. With an end goal to have a simple way of enabling webhook in kube-prometheus.

The idea is taken from how cert-manager handles admission webhook deployment and how they can easily ship two sets of manifests without pointing people to documentation.

Additionally, this would allow switching from ServiceMonitor to PodMonitor if we want to.

**Why do we need it?**

To simplify the deployment of admission webhook and improve UX.

**Environment**

* Prometheus Operator version: ALL

**Anything else we need to know?**:

cert-manager example - https://github.com/thaum-xyz/ankhmorpork/blob/bcaae0eb8b6957baf2b93861a74789d152d837b1/base/cert-manager/02_cert-manager.yaml#L1022-L1086

cc @brancz @simonpasquier

**Comment by simonpasquier** [comment]
Closed by #4494
