### ISSUE TITLE
Questions on Probe Config

### ISSUE THREAD

**Issue by winshenting** [prometheus-operator/prometheus-operator#4188]
**What did you do?**
In one probe config, I want to config 3 jobs. However, after apply, it shows only last job. 
Can one probe config support multiple jobs.

**Comment by fpetkovski** [comment]
Hello, could you send the probe that you've applied?

**Comment by paulfantom** [comment]
> Can one probe config support multiple jobs.

Each `Probe` is meant to translate into one job, but each job can have multiple targets.
Example for static config: https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/manifests/blackboxExporter/promDemoProbe.yaml
Example for ingress: https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/manifests/blackboxExporter/ingressProbe.yaml
