### ISSUE TITLE
Add option to configure Prometheus feature flag `retry_on_http_429` on Prometheus CR

### ISSUE THREAD

**Issue by dhohengassner** [prometheus-operator/prometheus-operator#4192]
**What is missing?**

Prometheus added a feature flag to enable/disable retries on HTTP 429 (too many requests) responses.

Feature got introduced with: https://github.com/prometheus/prometheus/pull/8477/

**Why do we need it?**

This feature is very useful if rate limiting got hit but the requests should be or not be retried later.  
More background can be found [here](https://github.com/prometheus/prometheus/issues/8474).

**Comment by slashpai** [comment]
I will take look at this

**Comment by paulfantom** [comment]
@slashpai any progress on this?

Note: Since the field is experimental in prometheus, we also should mark it as such.

**Comment by slashpai** [comment]
No I haven't looked at it yet. I will try to do it next week :)
