### ISSUE TITLE
Expose storage.remote.read-concurrent-limit flag

### ISSUE THREAD

**Issue by bennetty** [prometheus-operator/prometheus-operator#4194]
**What is missing?**
allow storage.remote.read-concurrent-limit flag to be set from the operator
**Why do we need it?**
While doing some testing on thanos sidecar, setting the storage.remote.read-concurrent-limit seemed to improve the query performance of the thanos sidecar while increasing the maxConcurrency did not have a similar impact
**Environment**

* Prometheus Operator version: v0.42.1
* Prometheus version v2.28.1
* Thanos version: v0.21.1

**Anything else we need to know?**:

if this is a feature that is needed i dont mind picking it up :)

**Comment by simonpasquier** [comment]
While I definitely understand the requirement, I think that the current approach of supporting each and every CLI argument of Prometheus isn't sustainable anymore.
Thinking out loud, it might be more convenient to let users append flags that aren't widely used to the generated command line arguments. If we want to keep things safe and avoid people breaking their systems, the operator could discard user-provided flags that conflict with the generated flags (though it might be not be so simple).

**Comment by midnightconman** [comment]
I am also running into this issue, where I would like to raise the remote_read concurrency limit to allow more connections from my thanos-sidecar (at the moment I peg at 10 99% of the time)... can we do both? Add this flag via the normal mechanisms (the flags in prometheus are pretty stable these days, so I don't think there should be much resistance here) and then open a new issue to look at the other flag merging method? @simonpasquier 

If the flags changed often I would totally agree with you, but prometheus hasn't changed flags in 2 months (these are the overlapping blocks work they just did, bad example), before that is 8 months, 2 years, and many 3-4 years in the github blame (https://github.com/prometheus/prometheus/blame/48a101be1b59dce6f9285b40d686be24f7793473/cmd/prometheus/main.go#L101).

**Comment by jimethn** [comment]
Also looking for a way to set `storage.remote.read-concurrent-limit`.

**Comment by yp969803** [comment]
@jimethn, nope remoteRead is different stuff, we have to pass "storage.remote.read-concurrent-limit" as flag to prometheus, I think we should create a new field with additionalFlags

**Comment by yp969803** [comment]
We can add flags via additionalArguments feild in promethes spec, so what does this issue what to do, do we also have to give option to add flags during initializing operator. @simonpasquier

**Comment by ArthurSens** [comment]
Yeah, not much to be done here. We already have `additionalArgs` as @yp969803 mentioned.

I'm closing this one but feel free to re-open if I've missed something
