### ISSUE TITLE
Add sample and target limits to Probes

### ISSUE THREAD

**Issue by dgrisonnet** [prometheus-operator/prometheus-operator#4197]
**What is missing?**

We can't configure sample and target limits for Probes.

**Why do we need it?**

We need this feature to limit the number of samples and targets scraped by a Probe. This would also allow for the limits at the Prometheus level to be enforced to all kinds of scraping resources. Currently, these limits are only supported by ServiceMonitors and PodMonitors so if we were to add Probe to a cluster with high-level limits defined, they wouldn't be applies to Probes as one would expect.

**Environment**

* Prometheus Operator version: latest

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
FYI: This is exactly the reason we should [implement generic ScrapeConfig](https://github.com/prometheus-operator/prometheus-operator/issues/2787) and inherit its options in other CRDs. This way we would implement core concepts once and they could be accessed in all *Monitors.

**Comment by slashpai** [comment]
I can add this to Probe

Implementing scrapeconfig api will take some time
