### ISSUE TITLE
Add a stale bot to close stale pull requests/issues

### ISSUE THREAD

**Issue by PhilipGough** [prometheus-operator/prometheus-operator#4231]
When looking through the list of open PR's, it is apparent some are entirely abandoned, outdated etc. There are some PR's almost 4 years old that are unlikely to be advanced at this point.

I wonder if we should consider extending the stale bot to close PR's that match this state?

**Comment by PhilipGough** [comment]
I see this also applies to the issues backlog and there is currently no `stale` bot

**Comment by paulfantom** [comment]
We already have stalebot enabled. The configuration is in https://github.com/prometheus-operator/prometheus-operator/blob/master/.github/stale.yml and bot is active as seen in https://github.com/prometheus-operator/prometheus-operator/issues/4188

**Comment by paulfantom** [comment]
I am not in favor of automatically closing PRs, no matter how old they are. However we could possibly modify stalebot config to only mark PRs as stale after some time of inactivity. This way we could force human intervention to take a look if the PR is still relevant. WDYT?

**Comment by paulfantom** [comment]
> I see this also applies to the issues backlog and there is currently no stale bot

Stalebot is active (example: https://github.com/prometheus-operator/prometheus-operator/issues/4188) and configuration is in https://github.com/prometheus-operator/prometheus-operator/blob/master/.github/stale.yml

**Comment by PhilipGough** [comment]
@paulfantom sounds good. I noticed there are *lots* of PR's that are likely in state that unless we/bot go and close them, they will remain open and abandoned forever. If they are closed the author would be notified and they would have the opportunity to think about it and potentially re-open at that point.

It was mostly a case of some housekeeping and no strong opinions on it either way.

**Comment by simonpasquier** [comment]
> However we could possibly modify stalebot config to only mark PRs as stale after some time of inactivity.

Marking old PRs as stale makes sense to me. At least it sends the correct signal to the reviewers.
