### ISSUE TITLE
Support consuming certs for PodMonitor as files

### ISSUE THREAD

**Issue by xbglowx** [prometheus-operator/prometheus-operator#4243]
**What is missing?**
ServiceMonitor allows for consuming certs as SecretOrConfigMap or string, but PodMonitor doesn't. Would be great to add `caFile`, `certFile`, and `keyFile` to PodMonitor.

**Why do we need it?**
To make ServiceMonitor's and PodMonitor's `tlsConfig` similar. Is there a reason they shouldn't be?

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.48.1`

**Comment by xbglowx** [comment]
This issue might be a dup of https://github.com/prometheus-operator/prometheus-operator/issues/3922 and/or https://github.com/prometheus-operator/prometheus-operator/issues/4121

**Comment by simonpasquier** [comment]
Yes this is similar to #3922 and #4121. We're not yet settled on the approach. Can you describe your use case and requirements more specifically?

**Comment by xbglowx** [comment]
> Yes this is similar to #3922 and #4121. We're not yet settled on the approach. Can you describe your use case and requirements more specifically?

We have istio deployed, so in order for Promtheus to be able to scrape Pods directly it would need to have access to a valid mTLS cert. Services allow for accessing the cert via file, which works great using [this](https://istio.io/latest/docs/ops/integrations/prometheus/) example of having the cert injected into the Prometheus Pod via a volume mount.

**Comment by simonpasquier** [comment]
Thanks @xbglowx so it looks identical to the other 2 issues. Would you mind closing that one?
