### ISSUE TITLE
Remove dead code supporting Prometheus v1.x

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#4244]
#2822 dropped support for Prometheus v1.x officially but there's still at least one place where the operator checks for v1.x

https://github.com/prometheus-operator/prometheus-operator/blob/98ed425ec9adbbe83871e2fd78276cdf5184c8b0/pkg/prometheus/promcfg.go#L419-L426

**Comment by slashpai** [comment]
I will check this :)
