### ISSUE TITLE
Need support for ppc64le architecture

### ISSUE THREAD

**Issue by amintek** [prometheus-operator/prometheus-operator#4250]
**What did you do?** Need support for ppc64le architecture

**Did you expect to see some different?**

**Environment**
Linux/ppc64le

* Kubernetes version information:
v1.17.2
 
* Kubernetes cluster kind:
   kubeadm

**Comment by simonpasquier** [comment]
duplicate from https://github.com/prometheus-operator/prometheus-operator/discussions/4252
