### ISSUE TITLE
grafana stuck in ContainerCreating

### ISSUE THREAD

**Issue by Awot83** [prometheus-operator/prometheus-operator#4257]
hello 

i followed theses steps of installation : 
1. git clone https://github.com/prometheus-operator/kube-prometheus.git
2. kubectl create -f manifests/setup
3. kubectl create -f manifests/

but the pod grafana information of "**kubectl get pods -n monitoring"** says  : **the pod grafana-xxxxxxx is stuck in ContainerCreating** 

the log from :  kubectl get events --all-namespaces  --sort-by='.metadata.creationTimestamp'
shows : 
`
similar events): Unable to attach or mount volumes: unmounted volumes=[grafana-config], unattached volumes=[grafana-dashboard-namespace-by-pod grafana-dashboard-apiserver grafana-dashboard-k8s-resources-workload grafana-storage grafana-dashboard-kubelet grafana-dashboard-alertmanager-overview grafana-dashboard-pod-total grafana-datasources grafana-dashboard-k8s-resources-cluster grafana-dashboard-namespace-by-workload grafana-dashboard-controller-manager grafana-dashboard-nodes grafana-dashboard-k8s-resources-workloads-namespace kube-api-access-bn5mp grafana-dashboards grafana-dashboard-prometheus-remote-write grafana-dashboard-k8s-resources-node grafana-dashboard-k8s-resources-namespace grafana-dashboard-node-rsrc-use grafana-dashboard-scheduler grafana-dashboard-node-cluster-rsrc-use grafana-config grafana-dashboard-proxy grafana-dashboard-k8s-resources-pod grafana-dashboard-workload-total grafana-dashboard-prometheus grafana-dashboard-cluster-total grafana-dashboard-persistentvolumesusage]: timed out waiting for the condition
monitoring   31s         Warning   FailedMount   pod/grafana-8df68868b-hrlrj   MountVolume.SetUp failed for volume "grafana-config" : secret "grafana-config" not found
`
could you help with this issue ? 
Best regards

**Comment by slashpai** [comment]
Could you please share `kubectl describe` output as well

Also since this is issue related to kube-prometheus this should have been created in https://github.com/prometheus-operator/kube-prometheus

@simonpasquier can we move this issue to kube-prometheus?
