### ISSUE TITLE
Need support for ppc64le architecture

### ISSUE THREAD

**Issue by amintek** [prometheus-operator/prometheus-operator#4258]
What did you do? Need support for ppc64le architecture so i can deploy kube-prometheus

Did you expect to see some different?

Environment
Linux/ppc64le

    Kubernetes version information:
    v1.17.2

    Kubernetes cluster kind:
    kubeadm

**Comment by simonpasquier** [comment]
see https://github.com/prometheus-operator/prometheus-operator/pull/2947#issuecomment-915331480

**Comment by PhilipGough** [comment]
@amintek - as per Simon's comment - this should be relatively straightforward. Extending the list of supported architectures with `ppc64le` at https://github.com/prometheus-operator/prometheus-operator/blob/master/scripts/push-docker-image.sh#L19 and adding same to the manifest https://github.com/prometheus-operator/prometheus-operator/blob/master/scripts/push-docker-image.sh#L75 should allow CI to publish the image you need.

Would you like to give it a go?

**Comment by n1lesh** [comment]
@PhilipGough I can do it.

**Comment by amintek** [comment]
@PhilipGough thanks for the reply, do i need to clone the repo locally, then execute the "push-docker-image.sh" script (after extending the list of supported architectures) ?

**Comment by PhilipGough** [comment]
@amintek the workflow is as follows:

1. Fork the repository
2. Make the relevant changes as described in https://github.com/prometheus-operator/prometheus-operator/issues/4258#issuecomment-916781641
3. Push the changes to your branch and create a pull request

I don't think you will need to execute the script directly. You can of course do that locally to verify your changes which is always a good idea, but following the steps above means CI should do the work.
