### ISSUE TITLE
Is it possible to have multiple prometheus instances at the same time?

### ISSUE THREAD

**Issue by AlexZhenWang** [prometheus-operator/prometheus-operator#4261]
Hi, I deployed prometheus using prometheus operator in my cluster with one prometheus instance, everything is working well. But after I set `prometheus.prometheusSpec.replicas` to 2 for creating more than 1 prometheus instance, those two instances are keeping crashing with `Readiness probe failed: HTTP probe failed with statuscode: 503` error.

Is this the expected behaviour when creating more than one prometheus instance at the same time? Is it not supported to have multiple prometheus instances?

**Comment by PhilipGough** [comment]
@AlexZhenWang you should for sure be able to create multiple replicas as you have described, so if that is not working it would be a bug, but I feel it is likely the e2e tests would have prevented that.

What is the output of `kubectl describe` on the crashing pods?
