### ISSUE TITLE
Alertmanager cannot find my AlertmanagerConfig using alertmanagerConfigNamespaceSelector

### ISSUE THREAD

**Issue by leo-lao** [prometheus-operator/prometheus-operator#4263]
**What did you do?**
I set up my prometheus and alertmanager using kube-prometheus,
then I tried to let my alertmanagerconfig(in namespace default) recognized by alertmanager(in namespace monitoring).

my AlertmanagerConfig looks like this:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  creationTimestamp: "2021-09-15T06:41:18Z"
  generation: 1
  labels:
    alertmanagerConfig: aa
  name: aa
  namespace: default
  resourceVersion: "18347153"
  uid: 5930da64-9b32-45b8-a711-1d6a48971607
spec:
  receivers:
  - name: pagerduty
    pagerdutyConfigs:
    - sendResolved: false
      serviceKey:
        key: serviceKey
        name: pagerduty-d
  route:
    groupBy:
    - '...'
    groupInterval: 5m
    groupWait: 30s
    receiver: pagerduty
    repeatInterval: 12h
```

Alertmanager looks like this 
```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  creationTimestamp: "2021-08-26T06:22:50Z"
  generation: 27
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.22.2
  name: main
  namespace: monitoring
  resourceVersion: "18361102"
  uid: 8d36cbda-c051-4956-ad49-4afd4cb2763d
spec:
  alertmanagerConfigNamespaceSelector:
    matchExpressions:
    - key: namespace
      operator: In
      values:
      - default
      - monitoring
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: aa
  image: quay.io/prometheus/alertmanager:v0.22.2
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.22.2
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 4m
      memory: 100Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: 0.22.2
```
after I appied above yaml files, I cannot find my aa configs in  alertmanager webUI.
I also tried differnent selectors  for Alertmanager yaml
```
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: aa
  alertmanagerConfigNamespaceSelector:
    matchLabels:
      namespace: default
```
also not working

finally following selector works: 
( leo is alertmanagerConfig in namespace monitoring, and alertmanager is  in the same namespace )

```
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: leo
  alertmanagerConfigNamespaceSelector:{}
```
my questions are:
* Does prometheus-operator support reading alertmanagerConfig in another namespace?
* If yes, is there any mistakes I made there?

**Environment**

kube-prometheus  release-0.9 / 2021-08-19

prometheus-operator 0.50.0

kubernetes 1.21.1

**Comment by leo-lao** [comment]
How to set prometheus-operator log level to debug?  
previous issues give such tips

**Comment by fpetkovski** [comment]
You can set the `--log-level` option to `debug`. The operator arguments are documented here: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/operator.md

**Comment by leo-lao** [comment]
> You can set the `--log-level` option to `debug`. The operator arguments are documented here: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/operator.md.
> 
> To answer your questions, the operator does support reading AlertmanagerConfigs from different namespaces. The `matchExpressions` actually works on namespace labels not on namespace names.

Thanks for answering.
As far as I can see, Alertmanager and AlertmanagerConfig should be in the same namespace, 
and AlertmanagerConfig only support route alerts from the same namespace.

That is to say, I need to deploy all my deployments to `monitoring` namespace?

Is there any methods supporting multiple namespaces in prometheus-operator?

**Comment by fpetkovski** [comment]
Hi @leo-lao,

you can add the following match expression to the Alertmanager resource
```
  alertmanagerConfigNamespaceSelector:
    matchLabels:
      alertmanager: aa
```
Then add the `alertmanager: aa` label to the namespaces that you want to scrape. 

Using `alertmanagerConfigNamespaceSelector: {}` is equal to scraping all namespaces regardless of their labels.

**Comment by leo-lao** [comment]
Thanks for your reply! 
I have solved this problem like this 


![alertmanager](https://user-images.githubusercontent.com/20881696/134282720-c85432a1-f99c-4162-8c93-35f651292513.png)

**Comment by zero-below** [comment]
Stumbled across this, but for future, this does seem to work, without needing to label your namespaces:
`  alertmanagerConfigNamespaceSelector:
    matchExpressions:
      - key: random-label-that-doesnt-exist-anywhere
        operator: DoesNotExist
`
