### ISSUE TITLE
Enable MultiNamespace or AllNamespaces mode in Operator Lifecycle Manager/OperatorHub

### ISSUE THREAD

**Issue by etsauer** [prometheus-operator/prometheus-operator#4265]
It appears that the latest version of the prometheus-operator that is listed in OperatorHub only supports a SingleNamespace install mode. This prevents OLM users from installing the operator in a manner where it can be used to monitor workloads across namespaces. I'm not sure if there was a reason it was done this way originally (maybe testing at the time wasn't working), but this operator is certainly designed to work across namespaces.

**What is missing?**

Ability to install prometheus-operator via Operator Lifecycle Manager on OpenShift/OKD and use it across namespaces. Need to set `supported: true` under either `type: MultiNamespace` or `type: AllNamespace` (or both?).

https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/prometheus/0.47.0/prometheusoperator.0.47.0.clusterserviceversion.yaml#L459-L467

**Why do we need it?**

So that we don't need to stand up a monitoring stack in every namespace

**Environment**

OpenShift/OKD

* Prometheus Operator version:

0.47.0

**Anything else we need to know?**:

**Comment by etsauer** [comment]
Opened https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/210 in the operators repo as well

**Comment by simonpasquier** [comment]
We don't maintain the OLM version of the operator so there's nothing we can do it. Since you've opened an issue on the OLM side, I'm closing this one for now.
