### ISSUE TITLE
ThanosRulerSpec.labels should preserve default replica label `thanos_ruler_replica`

### ISSUE THREAD

**Issue by r0bj** [prometheus-operator/prometheus-operator#4271]
Currently `ThanosRulerSpec.labels` logic is described as:
"If not provided, default replica label `thanos_ruler_replica` will be added as a label"

So in order to add any single custom label we need also manually add replica label required by Thanos Querier (needed for deduplication of Thanos Ruler instances https://thanos.io/tip/components/rule.md/#external-labels).
For example if you want to add just a single label `region=us-west` to the Thanos Ruler you would need to add label and also replica label `thanos_ruler_replica` manually:
```
labels:
  region: us-west
  thanos_ruler_replica: $(POD_NAME)
alertDropLabels:
- thanos_ruler_replica
```

This makes configuration of external labels more complex, it's prune to mistakes and it's inconsistent with `PrometheusSpec.externalLabels`.
What's more important Thanos Ruler configuration without replica labels is kind of broken setup: running multiple ruler replicas results in clash during compaction.

So logic of `ThanosRulerSpec.labels` should be probably more similar to how `PrometheusSpec.externalLabels` works - just add labels to default `thanos_ruler_replica` , not replace it completely with custom set.

* Prometheus Operator version: 0.50.0

**Comment by simonpasquier** [comment]
@r0bj do you want to contribute the improvement?

**Comment by r0bj** [comment]
@simonpasquier I prepared PR for this issue: https://github.com/prometheus-operator/prometheus-operator/pull/4283
