### ISSUE TITLE
Ensure that duration fields are valid

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#4282]
**What is missing?**
The operator doesn't prevent invalid values for duration fields like `PrometheusSpec.Retention` (same is true for `EnforcedBodySizeLimit`).

**Why do we need it?**
Avoid breaking Prometheus :)

**Environment**

* Prometheus Operator version: N/A

**Anything else we need to know?**:

**Comment by slashpai** [comment]
I had thought about that while creating PR but didn't get enough time back then. I will fix that

**Comment by simonpasquier** [comment]
Cool! FWIW the AlertmanagerConfig CRD also has duration fields like `groupInterval`, `groupWait` and `repeatInterval`. The check should happen when the operator selects the resources and rejects the ones that are invalid.

**Comment by simonpasquier** [comment]
The same validation should be run on
* `ScrapeInterval`, `ScrapeTimeout`, `EvaluationInterval`, `MetadataConfig.SendInterval`, `QuerySpec.Timeout`, `Thanos.ReadyTimeout`, `RemoteWriteSpec.RemoteTimeout`, `RemoteReadSpec.RemoteTimeout` and `AlertmanagerEndpoints.Timeout` for Prometheus resources.
* `Interval` and `ScrapeTimeout` for service/pod monitors and probes.
* `ClusterGossipInterval`, `ClusterPushpullInterval` and `ClusterPeerTimeout` for Alertmanager.
* `EvaluationInterval` for ThanosRuler.

**Comment by PhilipGough** [comment]
@simonpasquier is this closed by #4308

**Comment by slashpai** [comment]
@PhilipGough We will be able to close once https://github.com/prometheus-operator/prometheus-operator/pull/4352 is merged as well, that was last one part of this fix :)
