### ISSUE TITLE
Back-off pulling image "quay.io/prometheus-operator/prometheus-operator:v0.51.0"

### ISSUE THREAD

**Issue by Ghost---Shadow** [prometheus-operator/prometheus-operator#4290]
**What happened?**

I ran

```sh
kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml
```

Although CRDs were created, the `prometheus-operator-74894744f9-hftdj` pod gives this error.

There is no v0.51.0 in quay

https://quay.io/repository/prometheus-operator/prometheus-operator?tab=tags

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

Kubernetes 1.22
I also have loki stack installed

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"50317190d44dbdb51ae7ff430917b32ba96188b5", GitTreeState:"clean", BuildDate:"2021-06-30T14:20:31Z", GoVersion:"go1.15.13 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

oracle cluster

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
Yep we had a CI glitch which is why though the v0.51.0 tag exists, the Releases page doesn't show it :-)
