### ISSUE TITLE
The correct way to configure federation on high availability Prometheus

### ISSUE THREAD

**Issue by ethernoy** [prometheus-operator/prometheus-operator#4312]
I configured two different set of high availability Prometheus instances A and B. Both A and B have 2 replicas, A needs to scrape B to form a federation. I tried service monitor to form this federation, it ends bad because when using service monitor, each of A will scrape both B instances and result in unnecessary duplicated metrics. I ended up using additionalScrapeConfig on A to scrape the session-sticky service of B to avoid this issue.

I know this may be an anti-pattern, hence I would like to know if there is a more elegant way to achieve this.

**Comment by simonpasquier** [comment]
`additionalScrapeConfig` is probably the best answer for now.
