### ISSUE TITLE
multiple storage classes

### ISSUE THREAD

**Issue by kfox1111** [prometheus-operator/prometheus-operator#4336]
**What is missing?**

The ability to specify multiple storage classes for alertmanager/prom.

**Why do we need it?**
Say you spawn a ha prom/alertmanager now, but use your rook-ceph as your backend storage. If ceph has a problem, alerts break.
Having the ability to have your instances spread out across multiple types of storage would provide higher availability.

**Comment by fpetkovski** [comment]
I am not sure if the prometheus-operator is the right project for this. Kubernetes PVCs don't support multiple storage classes, which means that PO would have to implement some fallback logic to handle this use case. To me this problem seems to be better suited for a Kubernetes storage component.
