### ISSUE TITLE
AlertManager doesn't send alerts to Opsgenie if the alert is closed in Opsgenie

### ISSUE THREAD

**Issue by rjonala** [prometheus-operator/prometheus-operator#4341]
I am using AlertManager to send alerts to Opsgenie. If I close a firing alert in Opsgenie(KubernetesDeploymentReplicasMismatch for 1min), AlertManager wouldn’t send to Opsgenie(even though the event is still happening, I see alert firing in AlertManager but don’t see in Opsgenie). 

Is there any config that I need to change in AlertManager/Opsgenie to overcome this issue?

**Comment by PhilipGough** [comment]
@rjonala - I think we (or someone else with an eerily similar issue) discussed this on a [Slack thread](https://kubernetes.slack.com/archives/CFFDS2Z7F/p1634608037381700).

The TL;DR is that you should set send_resolved to true and AlertManager will close the alert in OpsGenie when the alert is no longer firing. Does this solve your problem?

**Comment by paulfantom** [comment]
There are 2 issues described in this thread:
1) Alert not closed in OpsGenie - the solution is as @PhilipGough wrote, do not set `send_resolved: false` ([it is `true` by default](https://prometheus.io/docs/alerting/latest/configuration/#opsgenie_config))
2) Lack of command propagation from OpsGenie to alertmanager (Closing in OpsGenie do not close alert in alertmanager) - This problem does not have a solution as there is no way to "close" an alert in prometheus. I would recommend to not close an alert while incident is happening, but only "ack" it in OpsGenie. This way the problem solves itself.
