### ISSUE TITLE
Add labels to CRDs

### ISSUE THREAD

**Issue by paulfantom** [prometheus-operator/prometheus-operator#4344]
**What is missing?**

Labels in CRDs metadata.

**Why do we need it?**

In some environments it can become difficult to track matching of features available in CRDs and features supported by operator binary.
It would be good to add the same labels as we are using in operator deployment metadata to CRDs metadata.

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:

**Comment by Nageshbansal** [comment]
Hey! @paulfantom, can I work on this issue?

**Comment by rexagod** [comment]
@Nageshbansal Are you still interested in taking this up?

**Comment by rexagod** [comment]
Ah looks like @paulfantom has a PR open for this.
