### ISSUE TITLE
Quickstart stop to work using kubectl apply

### ISSUE THREAD

**Issue by RafalKorepta** [prometheus-operator/prometheus-operator#4348]
**What happened?**

In the README.md there is Quickstart section that says to run `kubectl apply -f bundle.yaml`. This doesn't work as `kubectl apply` adds annotation section. In Redpanda operator our tests starts to failed with the following error:

```bash
The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
``` 

The https://github.com/prometheus-operator/prometheus-operator/pull/4326 changed the content of the [bundle.yaml](https://github.com/prometheus-operator/prometheus-operator/blob/master/bundle.yaml) file. The recommended way of  

**Did you expect to see something different?**

I was expected to change the README.md to say `kubectl create -f bundle.yaml` or don't introduce breaking change.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
kind create cluster
kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml
```

* Prometheus Operator version:

Latest `bundle.yaml` from this repository after https://github.com/prometheus-operator/prometheus-operator/pull/4326 PR

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

It's [kind](https://kind.sigs.k8s.io/) version `kind v0.11.1 go1.16.4 darwin/amd64` with kind nodes in version 1.22

* Manifests:

https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/master/bundle.yaml

* Prometheus Operator Logs:

None

**Anything else we need to know?**:

**Comment by stefanandres** [comment]
https://github.com/kubernetes/kubectl/issues/712 suggests to wait for server-side apply (https://github.com/kubernetes/enhancements/issues/555). 
When using a recent enough k8s version (don't known which, 1.21 works though) you can use server-side apply instead

```
helm show crds prometheus-community/kube-prometheus-stack --version "20.0.1"| kubectl apply --server-side=true --overwrite=false --force-conflicts -f -
```
