### ISSUE TITLE
TLS assets secret hits 1 MB etcd object size limit

### ISSUE THREAD

**Issue by gottwald** [prometheus-operator/prometheus-operator#4353]
**What happened?**
We're using service monitors to monitor https endpoints that need client tls certificates to retrieve metrics. After a certain amount of service monitors (250 ish) the operator is not able to save the tls-assets secret due to the k8s etcd object size limit.

**Did you expect to see something different?**
I'd expect it to keep working and scale beyond 250 service monitors

**How to reproduce it (as minimally and precisely as possible)**:
Create a big amount of service monitors with tls configs that include different client certs and drive the tls-assets secret size above 1048576 bytes.

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.47.0`
    
    

* Kubernetes version information:

    `Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

    cluster-api

* Prometheus Operator Logs:

```
level=error ts=2021-10-29T10:17:49.181607935Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"monitoring/k8s\" failed: creating tls asset secret failed: failed to create TLS assets secret for Prometheus k8s in namespace monitoring: Secret \"prometheus-k8s-tls-assets\" is invalid: data: Too long: must have at most 1048576 bytes"
```

**Comment by simonpasquier** [comment]
The same fix needs to go into Alertmanager.
