### ISSUE TITLE
Support for pagerduty links/images in the AlertManagerConfig CRD. 

### ISSUE THREAD

**Issue by ninjaslothx** [prometheus-operator/prometheus-operator#4370]
**What is missing?**
The [pager duty alertmanager config](https://www.prometheus.io/docs/alerting/latest/configuration/#pagerduty_config) currently has support for sending links and images as part of the pager duty events v2 api payload. 
However this is currently is missing from the AlertManagerConfig CRD spec. 

**Why do we need it?**
It allows to better enrich the events with links like runbooks. 
Currently this has to be suppled as an extra details section or does via the AlertManager configuration directly which not all users/deployment teams would have access to.

**Anything else we need to know?**:
Ref for the Events API fields for additional context. 
https://developer.pagerduty.com/api-reference/b3A6Mjc0ODI2Nw-send-an-event-to-pager-duty

**Comment by simonpasquier** [comment]
@PhilipGough do you have time to have a look at this?

**Comment by PhilipGough** [comment]
@simonpasquier missed this one. I'll investigate and work on this ASAP
