### ISSUE TITLE
Impact of moving config-reloader to a port other than 8080

### ISSUE THREAD

**Issue by franck102** [prometheus-operator/prometheus-operator#4371]
**What did you do?**
I need to modify the listening port of the init-config-reloader and config-reloader containers in the prometheus pod, to free up the 8080 port that we have to use for another extra container. 

I cannot find any documentation / design explaining what would be impacted if I do this: what if anything needs to talk to those 2 containers on port 8080, and is there a way to configure the operator (or other clients) to talk to a different port?

**Did you expect to see some different?**

Some design documentation describing when and from where the config-reloader HTTP ports are accessed :)

**Environment**

Kubernetes version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3"}

* Prometheus Operator version:

quay.io/prometheus-operator/prometheus-operator:v0.50.0

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:15:16Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

   AWS EKS

* Manifests:

config-reloader container in the prometheus sts, where I want to replace 8080 with 8081:
```
 config-reloader:
    Image:      quay.io/prometheus-operator/prometheus-config-reloader:v0.50.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Command:
      /bin/prometheus-config-reloader
    Args:
      --listen-address=:8080
```

**Comment by fpetkovski** [comment]
Hi @franck102, thanks for submitting the issue. I believe the config-reloader only exposes metrics on that port. If you decide to use a different port, you might need to adjust monitoring configuration.

We currently don't have any user-facing docs for the config reloader since it's more of an implementation detail. If you have an idea where this information should be, feel free to just raise a PR :)
