### ISSUE TITLE
Support documenting different types in po-docgen

### ISSUE THREAD

**Issue by PhilipGough** [prometheus-operator/prometheus-operator#4376]
**What is missing?**

It seems if we add some types to the sources for the API types (`alertmanager_config_types.go`, `v1/types.go`, ...) unless they are defined as a struct, they will not be added to the documentation.

We rely on kubebuilder annotations to generate the CRD's, and we might want to define the following enum as consts for example:

```go
// Day of the week
// +kubebuilder:validation:Enum=monday;tuesday
var Day string

const Monday Day = "monday"
...
```

Right now,  it seems that https://github.com/prometheus-operator/prometheus-operator/blob/fe746efdf6ee4fa483590af7e8366acc1daf8871/cmd/po-docgen/api.go#L143 only generates documentation from structs.

I think we can support other types (if this is seen as required) with some work:

```go
	if identType, ok := kubType.Decl.Specs[0].(*ast.TypeSpec).Type.(*ast.Ident); ok {
		if identType.Name == "string" {
			// ...
			continue
		}
		if identType.Name == "int" {
			// ...
			continue
		}
	}
```

**Comment by paulfantom** [comment]
What if we ditched `po-docgen` and used some other, community-maintained CRD docs generator? There is a nice thread about it in https://github.com/open-telemetry/opentelemetry-operator/issues/325.

**Comment by simonpasquier** [comment]
I'm in favor of dropping `po-docgen` too but it might be good to evaluate a couple of solutions beforehand? https://github.com/fybrik/crdoc#similar-tools has a list of alternatives and if I'm not wrong, @fpetkovski has experience with https://github.com/ahmetb/gen-crd-api-reference-docs

**Comment by paulfantom** [comment]
`gen-crd-api-reference-docs` was also chosen for opentelemetry-operator in https://github.com/open-telemetry/opentelemetry-operator/pull/505 and I am all for using this tool for our docs too.

**Comment by PhilipGough** [comment]
@paulfantom I assume you meant crdoc which is used in the linked PR?  https://github.com/open-telemetry/opentelemetry-operator/pull/505/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R254

@simonpasquier - the linked PR uses `crdoc` but it is just a RFC and we can investigate other options if desired.

There is some due diligence done on the provided options already by [Grafana folks](https://github.com/grafana-operator/grafana-operator/issues/519#issue-987010686) - crdoc is the only tool generating markdown.

**Comment by paulfantom** [comment]
Oh, seems like in the meantime they changed from `gen-crd-api-reference-docs` to `crdoc`.

**Comment by simonpasquier** [comment]
It looks like we are done :)

https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1beta1.Weekday

![image](https://user-images.githubusercontent.com/2587585/179519124-6c9a1cf3-4a44-446b-ba60-4fbc3d8b2fc0.png)
