### ISSUE TITLE
Multiple installation of prometheus using kube-stack-prometheus

### ISSUE THREAD

**Issue by muralidharansomasundaram** [prometheus-operator/prometheus-operator#4381]
Hi Team,

is it possible to install multiple prometheus installation using same kube-stack-prometheus in same space ..?

Do we need to have multiple prometheus-operator for multiple separate Prometheus to manage all prometheus lifecycle or we can manage using single prom-operator.

**Comment by paulfantom** [comment]
Yes, just add another `Prometheus` object and adjust `ServiceMonitorSelector`, `PodMonitorSelector`, `ProbeSelector`, `RuleSelector`
