### ISSUE TITLE
Can't get prometheusrule

### ISSUE THREAD

**Issue by mensylisir** [prometheus-operator/prometheus-operator#4382]
**What happened?**

Failed to get Prometheus rule through Prometheus operator API

**Did you expect to see something different?**

The prometheusrule can be obtained successfully

**How to reproduce it (as minimally and precisely as possible)**:
```
func getMonitorClient(clusterName string) (*versioned.Clientset, error) {
	client, err := getBaseParam(clusterName) # Kubernetes.Clientset, It can get all resouce from kubernetes 
	if err != nil {
		return nil, err
	}
	monitoringClient := versioned.New(client.DiscoveryClient.RESTClient())
	return monitoringClient, nil
}

func GetPrometheusRule(custername, namespace, prometheusrule_name) (*monitoringV1.PrometheusRule, error) {
	client, err := getMonitorClient(custername)
	if err != nil {
		return nil, err
	}
	pr, err := client.MonitoringV1().PrometheusRules(namespace).Get(context.TODO(), prometheusrule_name, metav1.GetOptions{})
	if err != nil {
		return nil, err
	}
	return pr, nil
}
```
Return error

```
{"msg":"v1.GetOptions is not suitable for converting to \"meta.k8s.io/v1\" in scheme \"pkg/runtime/scheme.go:101\""}
```

**Environment**

* Prometheus Operator version:

    ```
    app.kubernetes.io/version=0.50.0
   ```
    
    

* Kubernetes version information:

    ```
    Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
   ```
    

* Kubernetes cluster kind:

    ```
      kubespray
    ```

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by mensylisir** [comment]
pkg.runtime.codec.go/EncodeParameters() errors
This is get deployment
![image](https://user-images.githubusercontent.com/11365685/141037232-18203c4b-3cbe-435b-82d6-4332cac2c23d.png)
This is get PrometheusRule
![image](https://user-images.githubusercontent.com/11365685/141037318-05773dec-7cfc-4f5e-ba26-6976cb1bd09d.png)

**Comment by fpetkovski** [comment]
It's hard to know what the problem is without looking at the entire codebase. Could you set up a minimal repository with a main.go  file that we can look at?
