### ISSUE TITLE
Back-off pulling image "quay.io/thanos/thanos:v0.11.2"

### ISSUE THREAD

**Issue by haifzhu** [prometheus-operator/prometheus-operator#4386]
**What happened?**
use prometheus-operator create thanos in example manifests, error in image pulling:
Back-off pulling image "quay.io/thanos/thanos:v0.11.2"
the docker image quay.io/thanos/thanos:v0.11.2 is not found

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by fpetkovski** [comment]
Hi @haifzhu, could you add a link to the manifests that you applied?

**Comment by paulfantom** [comment]
Image of `quay.io/thanos/thanos:v0.11.2` never existed on quay.io as thanos do not have 0.11.2 release - https://github.com/thanos-io/thanos/tags?after=v0.12.0-rc.1
