### ISSUE TITLE
spec.podMetadata.annotations changes not applied starting with v0.50.0

### ISSUE THREAD

**Issue by mtougeron** [prometheus-operator/prometheus-operator#4392]
**What happened?**

Starting with v0.50.0 when the `Prometheus` resource has an updated value for `spec.podMetadata.annotations` the changes are not applied to the StatefulSet. Prior versions updated as expected.

**Did you expect to see something different?**

Expected the StatefulSet to have the new annotations applied to the Pods.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Prometheus resource without a value for `spec.podMetadata.annotations`
2. Add a value to `spec.podMetadata.annotations`

and

1. Create a Prometheus resource with a value for `spec.podMetadata.annotations`
2. Modify the value or remove the value from `spec.podMetadata.annotations`

**Environment**

* Prometheus Operator version:

0.50.0, 0.51.1, 0.51.2, v0.52.0

* Kubernetes version information:

Shouldn't be relevant but I tested with 1.19.x & 1.20.x clusters

**Anything else we need to know?**:

I believe this was introduced via https://github.com/prometheus-operator/prometheus-operator/pull/4185

**Comment by kirkharris1** [comment]
cc @mujx since he contributed #4185 and is best placed to help
