### ISSUE TITLE
Allow alertmanager to be deployed as a Deployment

### ISSUE THREAD

**Issue by Xartos** [prometheus-operator/prometheus-operator#4394]
**What is missing?**

_At least from what I can find_

When creating an alertmanager object, you should be able to set the type of deployment to use.

e.g. `StagefulSet`, `Deployment`

**Why do we need it?**

Since you can run alertmanager without any persistent volume it makes little sense to run it as a stateful set since that limits the kubernetes scheduler to move the pod.

**Environment**

* Prometheus Operator version: v0.48.1

    `Insert image tag or Git SHA here`
    
    
    
```
Image:    quay.io/prometheus-operator/prometheus-operator:v0.48.1
Image ID: docker-pullable://quay.io/prometheus-operator/prometheus-operator@sha256:2e7b61c86ee8b0aef4f5da8b6a4e51ecef249c9ccf4a329c5aa0c81e3fd074c1
```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
Alertmanager needs stable DNS names and as such, it is not recommended to provision it as a Deployment.

**Comment by paulfantom** [comment]
Adding Deployment would require rewriting a quite substantial part of the operator related to alertmanager. I don't see much value in doing so just for the edge case of running 1 alertmanager replica as Deployment. Especially considering that scaling from 1 to n+1 replicas would require changing Deployment to Statefulset too.

What is the exact issue in regards to using statefulset and scheduling?
