### ISSUE TITLE
kube-prometheus-stack Helm Chart 20.0.1 fails to install with argocd

### ISSUE THREAD

**Issue by KlavsKlavsen** [prometheus-operator/prometheus-operator#4399]
**What happened?**

First it fails with : #4355 

And when I select argocd replace (to use create instead) - it works, but it then fails with this error:
Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://latest-kube-prometheus-sta-operator.default.svc:443/admission-prometheusrules/mutate?timeout=10s": service "latest-kube-prometheus-sta-operator" not found

and no such service is defined anywhere?

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:
Install with argocd 2.1.6

**Environment**
kubernetes 1.20.7.

anything else of interest I can provide?

**Comment by KlavsKlavsen** [comment]
We tried installing with plain Helm - and it seems to be a bug in Prometheus - not really related to the helm chart - see https://github.com/prometheus-community/helm-charts/issues/1507 ?

**Comment by KlavsKlavsen** [comment]
It seems it was due to a webhook from previous version not being removed by argocd when updating.

**Comment by guy-frontegg** [comment]
@KlavsKlavsen What was the webhook? 
did you manage to solve this? we are still having issues

**Comment by KlavsKlavsen** [comment]
```
kubectl delete MutatingWebhookConfiguration latest-kube-prometheus-sta-admission
```
fixed it for me :)
