### ISSUE TITLE
serviceMonitorSelector with specific label causes all prometheus metrics/queries to fail

### ISSUE THREAD

**Issue by hughhm** [prometheus-operator/prometheus-operator#4410]
**What happened?**
In the helm chart when setting:
```
serviceMonitorSelector:
  matchLabels:
    prometheus: serviceMonitor
```
All metrics suddenly stop being collected and prometheus cannot be queried. Same occurs with all lowercase label value. 

No issues with using `serviceMonitorSelectorNilUsesHelmValues: false` or `true` however it would be nice to select only specific serviceMonitors that do not use the release name.

**Did you expect to see something different?**
Service monitors with provided label should be picked up as targets and prom should continue working. 

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:
  `prometheus-operator/prometheus-operator:v0.50.0`

  Used in kube-prometheus-stack helm chart.

* Kubernetes version information:

    `Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

    aws EKS

* Manifests:

```
prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        prometheus: serviceMonitor
```

* Prometheus Operator Logs:

None relevant.

**Anything else we need to know?**:

**Comment by slashpai** [comment]
Looks like this issue should be logged in helm chart repo https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

**Comment by paulfantom** [comment]
I cannot reproduce it with plain prometheus-operator (not installed via helm) and it looks like helm chart issue. As @slashpai please report it in helm chart repo.

**Comment by hughhm** [comment]
Thanks, will repost on the helm chart repo. The label is on my ServiceMonitor objects, and in fact it looks like they are picked up as targets, the issue is really that it breaks metrics collection/history.

**Comment by paulfantom** [comment]
If they are seen as targets, how does it break metrics collection?

**Comment by hughhm** [comment]
> If they are seen as targets, how does it break metrics collection?

Well thats the million dollar question isn't it mate

**Comment by paulfantom** [comment]
I mean what are the errors in `/targets` section that suggest metrics collection is broken?

**Comment by hughhm** [comment]
There aren't any, nor does the operator post any errors/warnings. If i query directly on prometheus or check any of our dashboards in Grafana there is no data. Once i revert the change, the period in which the change was implemented does not have any data as seen with any Graph. Part of the reason i have found this issue to be so strange and frustrating, i was certain for a while that i had done something wrong however after checking multiple times against the documentation and other issues i can't see what it could be.
