### ISSUE TITLE
go mod tidy error  invalid version: unknown revision

### ISSUE THREAD

**Issue by 631068264** [prometheus-operator/prometheus-operator#4421]
**What happened?**

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:
 main branch

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:
```
➜  prometheus-operator git:(main) go mod tidy
go: github.com/thanos-io/thanos@v0.23.1 requires
        github.com/efficientgo/e2e@v0.11.1-0.20210829161758-f4cc6dbdc6ea requires
        github.com/efficientgo/tools/core@v0.0.0-20210129205121-421d0828c9a6: reading https://goproxy.io/github.com/efficientgo/tools/core/@v/v0.0.0-20210129205121-421d0828c9a6.mod: 404 Not Found
        server response: not found: github.com/efficientgo/tools/core@v0.0.0-20210129205121-421d0828c9a6: invalid version: unknown revision 421d0828c9a6

```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
@631068264 can you share your solution?

**Comment by 631068264** [comment]
set Goland Go module env  GOPROXY=https://goproxy.cn ，perhaps is the network problem
