### ISSUE TITLE
PodMonitor matchExpressions on multiple label values picking "last" value in 0.52.0+ Operator

### ISSUE THREAD

**Issue by diranged** [prometheus-operator/prometheus-operator#4435]
**What happened?**

We upgraded from the 0.50.0 to 0.52.0 operator, and one of our `PodMonitor` resources started to return no targets - which was strange because we made no other changes. The unique thing about this one `PodMonitor` is that it had an "In" list of multiple "Values". The `PodMonitor` is a near exact copy of this from Strimzi: https://github.com/strimzi/strimzi-kafka-operator/blob/f167e82b2ae265a52e464dbddff5a64b904ab30a/examples/metrics/prometheus-install/strimzi-pod-monitor.yaml#L60-L63

We then tested replacing the `values` key with `values: [ "Kafka" ]`, and we began to get metrics. Then we changed it to `values: [ "Kafka", "KafkaConnect" ]` and while we did get values, we ONLY got values for the `KafkaConnect` pods, not the `Kafka` pods.

I suspect that change #4327  breaks the "or" logic in some way, causing the _last_ one to win. In our case, thats `"KafkaMirrorMaker2"` which we aren't running any of, which is why we lost _all_ metrics.

**How to reproduce it (as minimally and precisely as possible)**:

Install the 0.52.0 operator, then install Stimzi Kafka, and finally install the PodMonitor I referenced above.

**Environment**

* Prometheus Operator version: 0.52.0
* Kubernetes version information: 1.21
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: EKS

**Comment by slashpai** [comment]
This issue was fixed in 0.52.1, can you upgrade to that version and try?

**Comment by kingdonb** [comment]
I've just come across this issue, and I can confirm v0.52.1 does fix it.

There isn't a chart release which packages prometheus-operator v0.52.1 yet, so I set these values in order to test the upgrade:

```
prometheusOperator:
  image:
    tag: v0.52.1
  prometheusConfigReloader:
    image:
      tag: v0.52.1
```

(Our guides are impacted until the chart rev is published, tracking at https://github.com/fluxcd/flux2/issues/2192)

**Comment by diranged** [comment]
I can confirm that 0.52.1 fixes the bug. Thanks!

**Comment by slashpai** [comment]
Thanks for confirming :)
Can you close the issue if that is fixed?
