### ISSUE TITLE
Custom interval in podMonitorSelector?

### ISSUE THREAD

**Issue by betonetotbo** [prometheus-operator/prometheus-operator#4436]
Prometheus: v2.17.2
Operator: 0.39.0 
- Can I update to 0.52.1 ? Will it work with that version of prometheus?)

The main question:

Can I set a custom scrape interval in podMonitorSelector in Prometheus resource in prometheus operator?

This is my current podMonitor selector config:

   podMonitorNamespaceSelector: {}
    podMonitorSelector:
      matchExpressions:
      - key: camel.apache.org/integration
        operator: Exists

My current global intervals are:

  evaluationInterval: 60s
  scrapeInterval: 60s

For the podMonitor I need something like 10s and maintain the 60s for all other scrapes.

**Comment by fpetkovski** [comment]
You can set the `interval` field in this resource: https://github.com/prometheus-operator/prometheus-operator/blob/release-0.39/Documentation/api.md#podmetricsendpoint

**Comment by simonpasquier** [comment]
Closing the issue since this is already supported as @fpetkovski explained. Feel free to reopen/comment if we missed something.
