### ISSUE TITLE
Fix prometheus CRD being too big

### ISSUE THREAD

**Issue by sathieu** [prometheus-operator/prometheus-operator#4439]
When installing `prometheus-operator`, using `kubectl apply` or the Helm chart thru ArgoCD, the installation fails because the  `prometheuses` CRD is too big. This was reported already (#4367, #4348, #4355, ...), but the fix is not enough ( #4349).

I've proposed a PR to the Helm chart (https://github.com/prometheus-community/helm-charts/pull/1510), but they want the fix to be upstream, i.e. here 📍 .

I see several ways to fix this:

- shrink the CRD itself, and add a test for `kubectl apply` to avoid future regressions
- Only fix the ArgoCD side, by adding the `argocd.argoproj.io/sync-options: Replace=true` annotation
  - ideally, with kubebuilder itself (this was probably rejected: https://github.com/kubernetes-sigs/kubebuilder/issues/1140 https://github.com/kubernetes-sigs/kubebuilder/issues/387)
  - with a kustomize patch
  - with a sed patch

**Comment by simonpasquier** [comment]
> shrink the CRD itself, and add a test for kubectl apply to avoid future regressions

I'm not sure how we could reduce the size of the CRD...

**Comment by fpetkovski** [comment]
I would say this is rather a Kubernetes, or more precisely, a kubectl problem. Even if we shrink the CRD now, at one point it might grow again. 

@sathieu if you decide to replace the CRD, make sure that operation does not involve deleting and creating it again. That might lead to you losing all CRs for the deleted CRD.

**Comment by sathieu** [comment]
@fpetkovski The k8s bug is here: https://github.com/kubernetes/kubernetes/issues/82292

**Comment by sathieu** [comment]
A possible workaround would be to truncate the descriptions with `crd:maxDescLen=0`, like in https://github.com/crossplane/crossplane/pull/702.

**Comment by paulfantom** [comment]
The alternative fix is to use `kubectl apply --server-side` instead of plain `kubectl apply`. This wouldn't add kubectl specific annotation which is the main source of issue here.

**Comment by sathieu** [comment]
@paulfantom My usecase is within ArgoCD. ` kubectl apply --server-side` is not implemented yet (https://github.com/argoproj/argo-cd/issues/2267). And even if it's implemented, it will probably need an annoation too.

**Comment by paulfantom** [comment]
> A possible workaround would be to truncate the descriptions with crd:maxDescLen=0, like in crossplane/crossplane#702.

Crossplane workaround predates server-side apply functionality being GA in kubectl, by using it we would be removing meaningful information about the fields and reduce ability to use `kubectl explain`.

> My usecase is within ArgoCD. kubectl apply --server-side is not implemented yet

Good time to ping them with following-up on implementation. FluxCD did this recently - https://github.com/fluxcd/flux2/issues/1889

**Comment by primeroz** [comment]
> I would say this is rather a Kubernetes, or more precisely, a kubectl problem. Even if we shrink the CRD now, at one point it might grow again. 

Even if that is true how can a "kubernetes specific operator" ignore such a limitation ? 

Sure the day that it gets fixed on kubernetes side it will be amazing but until then IMHO _this is something a kubernetes operator_ needs to take into account. 

I know there are _workarounds_ but given how big is the set of tools people use to deploy manifests it is just a useless friction added on the user experience. 

* not all tools support `server side apply`
* `replace` is a pain since it needs the resource to already exist making `gitops` quite impossible 
* delte then create is not only impossible to achieve with gitops is also very dangereous 

Just saying that out of the **416633** bytes of the prometheus CRD removing the descriptions will shrink it to **220019** bytes , small enough to be used. 

> Crossplane workaround predates server-side apply functionality being GA in kubectl, by using it we would be removing meaningful information about the fields and reduce ability to use kubectl explain.

is that more important than being able to use the operator ? :)

**Comment by Cheshirez** [comment]
Server-Side Apply is not in so common use at the moment, so pushin apply with `--server-side` manually or forcing support of it to CD tools may decrease overall stability, especially when it come to resolving conflicts.

Would agree with the last, that resource definition could be reviewed and adjusted as it overgrow current k8s sizes for CRD. 
From usage or debug perspective - people are rather checking Prometheus documentation or GitHub issues than `kubectl explain`.

**Comment by gw0** [comment]
If you use ArgoCD to normally install `kube-prometheus-stack` it fails, because it uses `kubectl apply` in the background which causes this CRD too long issue. If you manually recreate the CRDs, it occasionally works, but sooner or later ArgoCD self-healing will cause issues again.

If you use ArgoCD to install with Replace=true `kube-prometheus-stack` it fails, because it uses `kubectl recreate` and PVC resources complain that they can not be mutated.

The best option is probably to split the installation of `kube-prometheus-stack` into two ArgoCD apps:
- an ArgoCD app just for installing the CRDs with `Replace=true` directly from Git with correct tag, snippet:
```
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-31.0.0
    directory:
      recurse: true
    syncOptions:
    - Replace=true
```
- an ArgoCD app that installs the Helm chart with `skipCrds=true` (new feature in ArgoCD 2.3.0), snippet:
```
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 31.0.0
    helm:
      releaseName: ...
      skipCrds: true
      values: |
        ...
```

**Comment by njnygaard** [comment]
> If you use ArgoCD to normally install `kube-prometheus-stack` it fails, because it uses `kubectl apply` in the background which causes this CRD too long issue. If you manually recreate the CRDs, it occasionally works, but sooner or later ArgoCD self-healing will cause issues again.
> 
> If you use ArgoCD to install with Replace=true `kube-prometheus-stack` it fails, because it uses `kubectl recreate` and PVC resources complain that they can not be mutated.
> 
> The best option is probably to split the installation of `kube-prometheus-stack` into two ArgoCD apps:
> 
>     * an ArgoCD app just for installing the CRDs with `Replace=true` directly from Git with correct tag, snippet:
> 
> 
> ```
>     repoURL: https://github.com/prometheus-community/helm-charts.git
>     path: charts/kube-prometheus-stack/crds/
>     targetRevision: kube-prometheus-stack-31.0.0
>     directory:
>       recurse: true
>     syncOptions:
>     - Replace=true
> ```
> 
>     * an ArgoCD app that installs the Helm chart with `skipCrds=true` (new feature in ArgoCD 2.3.0), snippet:
> 
> 
> ```
>     repoURL: https://prometheus-community.github.io/helm-charts
>     chart: kube-prometheus-stack
>     targetRevision: 31.0.0
>     helm:
>       releaseName: ...
>       skipCrds: true
>       values: |
>         ...
> ```

Sorry if this is off topic for this repo, but I can't seem to get this to work in for ArgoCD `v2.4.0+185e580`.
I tried to add `skipCrds: true` to the manifest in the ArgoCD UI, right above `values`, and it seems like it doesn't stick around after apply.

```yaml
project: staging
source:
  repoURL: 'https://prometheus-community.github.io/helm-charts'
  targetRevision: 35.0.0
  helm:
    values: >+
      # Default values for kube-prometheus-stack.
```
Any tips?

**Comment by Cheshirez** [comment]
@njnygaard most probably you'll need to upgrade ArgoCD using latest 4.x helm chart, as old CRDs don't contain skipCrd.
Or you can update CRDs for argo applications manually:
```
kubectl replace -f https://raw.githubusercontent.com/argoproj/argo-helm/master/charts/argo-cd/crds/crd-application.yaml
```

**Comment by slamer59** [comment]
Hello,
I tried to split in two Apps since I use argoCD. It doesnot seems to work. 

_Failed sync attempt to 90224b658ebc179a1fb5ba05677a58f76b56c52e: one or more objects failed to apply, reason: CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes (retried 5 times)._

> If you use ArgoCD to normally install `kube-prometheus-stack` it fails, because it uses `kubectl apply` in the background which causes this CRD too long issue. If you manually recreate the CRDs, it occasionally works, but sooner or later ArgoCD self-healing will cause issues again.
> 
> If you use ArgoCD to install with Replace=true `kube-prometheus-stack` it fails, because it uses `kubectl recreate` and PVC resources complain that they can not be mutated.
> 
> The best option is probably to split the installation of `kube-prometheus-stack` into two ArgoCD apps:
> 
>     * an ArgoCD app just for installing the CRDs with `Replace=true` directly from Git with correct tag, snippet:
> 
> 
> ```
>     repoURL: https://github.com/prometheus-community/helm-charts.git
>     path: charts/kube-prometheus-stack/crds/
>     targetRevision: kube-prometheus-stack-31.0.0
>     directory:
>       recurse: true
>     syncOptions:
>     - Replace=true
> ```
> 
>     * an ArgoCD app that installs the Helm chart with `skipCrds=true` (new feature in ArgoCD 2.3.0), snippet:
> 
> 
> ```
>     repoURL: https://prometheus-community.github.io/helm-charts
>     chart: kube-prometheus-stack
>     targetRevision: 31.0.0
>     helm:
>       releaseName: ...
>       skipCrds: true
>       values: |
>         ...
> ```

**Comment by Guyverix** [comment]
The above fix appears to work correctly with ArgoCD build v2.4.6+a48bca0 with no additional changes needed... At least it appears to have worked properly.  I am still kicking the tires since I am an ArgoCD and Kubernetess n00b.

**Comment by goshlanguage** [comment]
> > If you use ArgoCD to normally install `kube-prometheus-stack` it fails, because it uses `kubectl apply` in the background which causes this CRD too long issue. If you manually recreate the CRDs, it occasionally works, but sooner or later ArgoCD self-healing will cause issues again.
> > If you use ArgoCD to install with Replace=true `kube-prometheus-stack` it fails, because it uses `kubectl recreate` and PVC resources complain that they can not be mutated.
> > The best option is probably to split the installation of `kube-prometheus-stack` into two ArgoCD apps:
> > ```
> > * an ArgoCD app just for installing the CRDs with `Replace=true` directly from Git with correct tag, snippet:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >     repoURL: https://github.com/prometheus-community/helm-charts.git
> >     path: charts/kube-prometheus-stack/crds/
> >     targetRevision: kube-prometheus-stack-31.0.0
> >     directory:
> >       recurse: true
> >     syncOptions:
> >     - Replace=true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > * an ArgoCD app that installs the Helm chart with `skipCrds=true` (new feature in ArgoCD 2.3.0), snippet:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >     repoURL: https://prometheus-community.github.io/helm-charts
> >     chart: kube-prometheus-stack
> >     targetRevision: 31.0.0
> >     helm:
> >       releaseName: ...
> >       skipCrds: true
> >       values: |
> >         ...
> > ```
> 
> Sorry if this is off topic for this repo, but I can't seem to get this to work in for ArgoCD `v2.4.0+185e580`. I tried to add `skipCrds: true` to the manifest in the ArgoCD UI, right above `values`, and it seems like it doesn't stick around after apply.
> 
> ```yaml
> project: staging
> source:
>   repoURL: 'https://prometheus-community.github.io/helm-charts'
>   targetRevision: 35.0.0
>   helm:
>     values: >+
>       # Default values for kube-prometheus-stack.
> ```
> 
> Any tips?

I think the Application spec may have changed. I've updated my local Application to:

```yaml
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-39.9.0
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
    - Replace=true
```

**Comment by simonpasquier** [comment]
With https://github.com/prometheus-operator/prometheus-operator/pull/4937, you can now run `make stripped-down-crds.yaml` which would generate CRD manifests with empty description fields and it should avoid the "CRD being too long" problem.

**Comment by Ornias1993** [comment]
> With #4937, you can now run `make stripped-down-crds.yaml` which would generate CRD manifests with empty description fields and it should avoid the "CRD being too long" problem.

Would it be an option to also offer a stripped-down bundle?

**Comment by rufreakde** [comment]
Since this issue is also coming up often on declarative CD tooling I wanted to add a feature request that could solve this as well on HELM level to spread the awareness and maybe make this feature request more visible for helm developers.

https://github.com/actions/actions-runner-controller/issues/2125

**Comment by komalthakur853** [comment]
I am using a custom app which is build by my org and I am facing this issue again and again , If I pass creds in helm they break and the error is generated of libraries of go and python , Right now I have to apply that manually but not sure will server side help as there is kubectl version fixation in my app. I am using below commands as temporarily.

**# Prometheus Operator CRDs**

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml

**# VictoriaMetrics Operator CRDs**

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/VictoriaMetrics/operator/master/config/crd/bases/operator.victoriametrics.com_vmagents.yaml

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/VictoriaMetrics/operator/master/config/crd/bases/operator.victoriametrics.com_vmclusters.yaml

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/VictoriaMetrics/operator/master/config/crd/bases/operator.victoriametrics.com_vmnodescrapes.yaml

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/VictoriaMetrics/operator/master/config/crd/bases/operator.victoriametrics.com_vmpodscrapes.yaml

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/VictoriaMetrics/operator/master/config/crd/bases/operator.victoriametrics.com_vmprobes.yaml

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/VictoriaMetrics/operator/master/config/crd/bases/operator.victoriametrics.com_vmrules.yaml

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/VictoriaMetrics/operator/master/config/crd/bases/operator.victoriametrics.com_vmsingles.yaml

kubectl apply --server-side --validate=false -f https://raw.githubusercontent.com/VictoriaMetrics/operator/master/config/crd/bases/operator.victoriametrics.com_vmstaticscrapes.yaml
