### ISSUE TITLE
Unable to get kube-controller and scheduler metrics

### ISSUE THREAD

**Issue by rshiva777** [prometheus-operator/prometheus-operator#4440]
**What did you do?**
My controller and scheduler are running on 127.0.0.1 port as per the VA assesment report.

**Did you expect to see some different?**
After running them on port 127.0.0.1, i am able to see target down on prometheus page

**Environment**
kubernetes 1.20.0 version

* Prometheus Operator version:
v2.24.0

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `[root@****]# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

kubespray

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:
![image](https://user-images.githubusercontent.com/42074614/145022350-56f95319-38b0-4a7b-8747-5dcbbb75460b.png)

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
Scheduler needs to be exposing metrics endpoint on an IP that is accessible in kubernetes network. When using 127.0.0.1 ip, the expected result would be the one you described.
