### ISSUE TITLE
Sharding

### ISSUE THREAD

**Issue by MalulDekel** [prometheus-operator/prometheus-operator#4442]
Hey I have question regards prometheus at scale with shards. 

First of all why increase of the shards number will result on x time replicas and x time shards?
What is the different between replicas and shards pods? 
How thanos works with prometheus when sharding is enabled?

I have done lots of research on that topic but I couldn't find enough data so if you can refer links it will be great also. 
Thanks!

**Comment by mikechengwei** [comment]
Replicas ensure instance service high availability, and shards sure data distribute on multiple instances.

**Comment by MalulDekel** [comment]
> Replicas ensure instance service high availability, and shards sure data distribute on multiple instances.

First of all thanks for the quick replay!

Can you explain farther?

The replicas pods ensure HA of what if the data is being scraped and held by the shards pods?

**Comment by mikechengwei** [comment]
> 

yes

**Comment by mikechengwei** [comment]
> > Replicas ensure instance service high availability, and shards sure data distribute on multiple instances.
> 
> First of all thanks for the quick replay!
> 
> Can you explain farther?
> 
> The replicas pods ensure HA of what if the data is being scraped and held by the shards pods?

yes.

**Comment by MalulDekel** [comment]
> > > Replicas ensure instance service high availability, and shards sure data distribute on multiple instances.
> > 
> > 
> > First of all thanks for the quick replay!
> > Can you explain farther?
> > The replicas pods ensure HA of what if the data is being scraped and held by the shards pods?
> 
> yes.

Ok so the replicas exposes the data that reside on the shards if I understood correctly

**Comment by paulfantom** [comment]
As mentioned above, `shards` is responsible for data distribution and `replicas` is reponsible for making prometheus HA.

---

To explain it a bit more let's take a look at a basic setup with an application with 2 replicas that are scraped using single ServiceMonitor configuration. First let's start with a default setup of `shards: 1` and `replicas: 2` and look at prometheus data scrape flow:

![Screenshot from 2021-12-08 10-18-46](https://user-images.githubusercontent.com/3531758/145182126-4ebe7c2d-a346-4fdb-992d-5cd0a7f381ec.png)

As seen above such setup would result in having all data in each prometheus instance and thus grant high availability, but no data distribution. So let's take a look at how data can be distributed in the simplest way by using `shards: 2` and `replicas: 1` (to simplify I am assuming that hashmod algorithm used to define data distribution made it so data from app-replica-0 landed on prometheus shard 0):

![Screenshot from 2021-12-08 10-14-50](https://user-images.githubusercontent.com/3531758/145181524-6c6a3c98-000e-4cc7-a268-05580954f471.png)

This would give us data distribution, but we are loosing high availability of prometheus instances (downtime of one prometheus instance leads to inability to retrieve some data). To fix this we can combine both and use setup of `shards: 2` and `replicas: 2`:

![Screenshot from 2021-12-08 10-25-36](https://user-images.githubusercontent.com/3531758/145183143-6e4e6091-3b9e-4e81-91ed-a3be8c5d8c7c.png)

Now as you can see there `shards` is only responsible for splitting scrape job and distributing it across prometheus servers (using hashmod) and `replicas` is about making that distributed data highly available.
