### ISSUE TITLE
tls: bad certificate 

### ISSUE THREAD

**Issue by mohan-nagandlla** [prometheus-operator/prometheus-operator#4513]
HI Team,

I have enabled the tls for Prometheus which is running with the version of 2.30.0  and the operator version is 0.53.1. I am using open SSL certs after pod deployment I am getting the below errors 

Promethus container logs 

```
ts=2022-01-21T05:29:30.787Z caller=stdlib.go:105 level=error component=web caller="http: TLS handshake error from 127.0.0.1:50242" msg="remote error: tls: bad certificate"
ts=2022-01-21T05:29:35.780Z caller=stdlib.go:105 level=error component=web caller="http: TLS handshake error from 127.0.0.1:50386" msg="remote error: tls: bad certificate"
```

config reload container logs
```
level=error ts=2022-01-21T05:27:15.783320475Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs"
level=error ts=2022-01-21T05:27:20.782436791Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs"
```

**Comment by fpetkovski** [comment]
Is your certificate valid? In the logs I see 
```
x509:  cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
```

**Comment by simonpasquier** [comment]
Though it doesn't look directly related, #4273 is still something we need to fix.

**Comment by mohan-nagandlla** [comment]
Yes it's was signed by my organization

**Comment by simonpasquier** [comment]
can you share the Prometheus resource definition?

**Comment by mohan-nagandlla** [comment]
```
kg depl po
NAME                      READY   STATUS    RESTARTS   AGE
prometheus-prometheus-0   2/2     Running   0          4h48m
[egmoanh@seskp1comp045 ~]$ kg depl prometheus -o yaml
apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    creationTimestamp: "2022-01-21T05:04:38Z"
    generation: 1
    managedFields:
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:replicas: {}
          f:secrets: {}
          f:serviceAccountName: {}
          f:serviceMonitorSelector:
            .: {}
            f:matchLabels:
              .: {}
              f:purpose: {}
          f:web:
            .: {}
            f:pageTitle: {}
            f:tlsConfig:
              .: {}
              f:cert:
                .: {}
                f:secret:
                  .: {}
                  f:key: {}
                  f:name: {}
              f:keySecret:
                .: {}
                f:key: {}
                f:name: {}
      manager: kubectl-create
      operation: Update
      time: "2022-01-21T05:04:38Z"
    name: prometheus
    namespace: depl
    resourceVersion: "1340817"
    uid: fe89c235-1b86-4dcc-87ab-d29fabba27d0
  spec:
    replicas: 1
    secrets:
    - certs
    serviceAccountName: prometheus
    serviceMonitorSelector:
      matchLabels:
        purpose: test
    web:
      pageTitle: tls-prometheus
      tlsConfig:
        cert:
          secret:
            key: tls.crt
            name: certs
        keySecret:
          key: tls.key
          name: certs
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

![image](https://user-images.githubusercontent.com/52690110/150511171-4b7d1380-a93a-4559-9676-a07028504c3e.png)


![image](https://user-images.githubusercontent.com/52690110/150511237-ab88ed10-1c1f-4599-956a-6c9963460e5a.png)

**Comment by simonpasquier** [comment]
The config reloader connects to the 127.0.0.1 address so it fails the certificate unless you add 127.0.0.1 to the IP SANs of the certificate.
And it might even not be sufficient as the config reloader may not trust the server certificate. In short we need to fix #4273.

**Comment by mohan-nagandlla** [comment]
Your reference is saying like enabling the Thanos sidecar But I don't want the Thanos

**Comment by mohan-nagandlla** [comment]
Why not to introduce the cert verification by putting the cert into /etc/ssl/cert/

**Comment by simonpasquier** [comment]
> Your reference is saying like enabling the Thanos sidecar But I don't want the Thanos

Thanos sidecar and the config reloader have the same issue because they both connect to 127.0.0.1.

> Why not to introduce the cert verification by putting the cert into /etc/ssl/cert/ or else TLS skip verification because this is http2 ...

Do you have the possibility to add "127.0.0.1" to the IP SANs of the server's certificate? Since the error you're saying isn't "x509: certificate signed by unknown authority", it looks like the reloader already trusts the server's certificate authority...

**Comment by mohan-nagandlla** [comment]
Nonits not possible to add IP SAN

**Comment by RemcoBuddelmeijer** [comment]
> > Why not to introduce the cert verification by putting the cert into /etc/ssl/cert/ or else TLS skip verification because this is http2 ...
> 
> Do you have the possibility to add "127.0.0.1" to the IP SANs of the server's certificate? Since the error you're saying isn't "x509: certificate signed by unknown authority", it looks like the reloader already trusts the server's certificate authority...

@simonpasquier Adding the IP SANS won't fix the issue. This is because even though the error does not say "x509: certificate signed by unknown authority" in the first place, that doesn't mean this won't be the case afterwards. 
In my use-case there was a self-signed certificate without the IP SANS, then after adding 127.0.0.1 to the IP SANS it still didn't work, the error: "x509: certificate signed by unknown authority".

Either there needs to be a possibility to update the trusted CA certificates, or TLS verification must be skipped for the config-reloader to the prometheus container. However, I can see communication about this on #4273.

**Comment by simonpasquier** [comment]
Right, to avoid discussions happening in both issues, lets close this one in favor of #4273.
