### ISSUE TITLE
Improve documentation and move possible validations via OpenAPI

### ISSUE THREAD

**Issue by slashpai** [prometheus-operator/prometheus-operator#4524]
**What is missing?**

While working on adding [validation for scrapeTimeout](https://github.com/prometheus-operator/prometheus-operator/pull/4491#discussion_r782103988), we noted that its a bit confusing and documentation is not clear how default values are set for CRD fields. We need to improve documentation on how default values are set and move validations possible using [OpenAPI](https://book.kubebuilder.io/reference/markers/crd-validation.html)

**Why do we need it?**

This is needed for better understanding and troubleshooting incase of issues

**Environment**

NA

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

0.53.1

**Anything else we need to know?**:

See discussion in the PR #4491

**Comment by slashpai** [comment]
@simonpasquier I think we have covered possible options in PRs linked, good to close?

**Comment by simonpasquier** [comment]
Yep, I think we're good.
