### ISSUE TITLE
Add validation for sourceLabels in RelabelConfig

### ISSUE THREAD

**Issue by nkleinberg** [prometheus-operator/prometheus-operator#4564]
**What is missing?**

validateRelabelConfig validates other fields in the RelabelConfig, but does not validate sourceLabels:

https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/prometheus/operator.go#L2160

**Why do we need it?**

An invalid sourceLabels field can cause the operator to create an invalid config which Prometheus can't load.  This makes the consequences of a bad ServiceMonitor worse than necessary.

**Comment by slashpai** [comment]
Thanks for logging the issue

Can you provide an example where prometheus load failed with invalid sourceLabels? Also possible to provide prometheus-operator logs?

@simonpasquier  I could be wrong but I think it will be tricky to validate sourceLabels as we would require to validate if provided label is valid or not by querying [label api](https://prometheus.io/docs/prometheus/latest/querying/api/#getting-label-names) once prometheus is up. Do/Can we do such validations in operator?

**Comment by simonpasquier** [comment]
@nkleinberg probably means that `sourceLabels: ["-foo"]` breaks since it doesn't respect the `^[a-zA-Z_][a-zA-Z0-9_]*$` regexp (see https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels).

**Comment by nkleinberg** [comment]
Yes exactly -- the bad "sourceLabels" value we had included a `-` character.  I don't see anything interesting from our logs around that time, just the usual
```component=prometheusoperator msg="sync prometheus"```

**Comment by slashpai** [comment]
sure thanks for confirming. I will submit patch for this
