### ISSUE TITLE
The fix of #4429 seems to break existing labelMap-actions

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#4572]
The fix of #4429 seems to break existing labelMap-actions. With v0.54 using kube-stack we are losing some PodMonitors (in this case from our Pulsar Cluster.

Log from the operator
```
level=warn ts=2022-02-10T21:36:06.190554556Z caller=operator.go:1957 component=prometheusoperator msg="skipping podmonitor" error="\"\" is invalid 'replacement' for labelmap action" podmonitor=pulsar/pulsar-zookeeper namespace=observability prometheus=prometheus-community-kube-prometheus
level=warn ts=2022-02-10T21:36:06.190682758Z caller=operator.go:1957 component=prometheusoperator msg="skipping podmonitor" error="\"\" is invalid 'replacement' for labelmap action" podmonitor=pulsar/pulsar-broker namespace=observability prometheus=prometheus-community-kube-prometheus
```

From looking at the podMonitors
```
...
    relabelings:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
```

this should be the problematic action. 

Source definition: https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/autorecovery-podmonitor.yaml#L41

Workaround seems to be to revert to v0.53.

_Originally posted by @mkoertgen in https://github.com/prometheus-operator/prometheus-operator/issues/3942#issuecomment-1035552992_

**Comment by simonpasquier** [comment]
@slashpai if you want to have a look :)

**Comment by slashpai** [comment]
We can close this since it's fixed now
