### ISSUE TITLE
server returned HTTP status 404 Not Found

### ISSUE THREAD

**Issue by bailuoxi66** [prometheus-operator/prometheus-operator#4573]
**What did you do?**
1. helm install prometheus-operator stable/prometheus-operator -n monitoring
![image](https://user-images.githubusercontent.com/35655760/153812359-df5b37db-eaac-4f4a-a680-0f755cd9eed4.png)

2. Deploy a custom service
![image](https://user-images.githubusercontent.com/35655760/153812501-4b0c5b4c-1143-437a-9c56-2ae83ff8b275.png)

3. To make prometheus-operator monitor custom services, prepare a servicemonitoring file
![image](https://user-images.githubusercontent.com/35655760/153812651-43bef2e3-2ae6-4b54-9149-b92b438a61d2.png)
helm upgrade prometheus-operator stable/prometheus-operator --values=values_servicemonitor.yml -n monitoring

4. View the target of prometheus ui
![image](https://user-images.githubusercontent.com/35655760/153812780-709ac4ae-8d73-488d-a23a-1f76a0843f76.png)

**Did you expect to see some different?**
State is UP 【[monitoring/elasticweb-elasticweb/0 (0/1 up)】

    `kubectl version`
    Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.3", GitCommit:"01849e73f3c86211f05533c2e807736e776fcf29", GitTreeState:"clean", BuildDate:"2021-02-17T12:35:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1

* Kubernetes cluster kind:

    helm install prometheus-operator stable/prometheus-operator -n monitoring

**Anything else we need to know?**:
port forwarding enabled

kubectl port-forward -n monitoring alertmanager-prometheus-operator-alertmanager-0 9093
kubectl port-forward -n monitoring prometheus-prometheus-operator-prometheus-0 9090
kubectl port-forward -n monitoring prometheus-operator-grafana-686b547754-vtz29 3000
kubectl port-forward -n devs elasticweb-sample-6c94798f95-2j9hx 8080

**Comment by simonpasquier** [comment]
there's nothing here indicating an issue with the operator. You could query the target's endpoint manually with curl to understand why it returns 404. Checking the application's logs might also be useful.

**Comment by pdxrlj** [comment]
How did you solve it
