### ISSUE TITLE
 Prometheus Operator: can not be used in agent mode with  ["--storage.tsdb.path" "--storage.tsdb.retention.time"]

### ISSUE THREAD

**Issue by haitaopanhq** [prometheus-operator/prometheus-operator#4599]
**What did you do?**

When I enabled the feature : prometheus.prometheusSpec.enableFeatures: agent  , deoloy the kube-prometheus-stack chart in a k8s cluster .

`kubectl  get pods -n prometheus`:

```
prometheus-prometheus-agent-kube-prom-prometheus-0     1/2     CrashLoopBackOff   9 (14s ago)   21m 
```

`kubectl  logs -f  prometheus-prometheus-agent-kube-prom-prometheus-0 -n  prometheus`:

```
ts=2022-02-27T09:57:08.203Z caller=main.go:187 level=info msg="Experimental agent mode enabled."
The following flag(s) can not be used in agent mode: ["--storage.tsdb.path" "--storage.tsdb.retention.time"]
```

but i do not how to deal this problem in Prometheus Operator Mode, the   CRD Prometheus wil auto update the   statefulset.apps/prometheus-prometheus-agent-kube-prom-prometheus resources

**Environment**

  1.  Prometheus Operator version: v0.54.1
  2.  Prometheus: v2.33.4

* Kubernetes version information:
  - kubectl version : 1.23
  - created by  kubeadmin tools

**Comment by panhaitao** [comment]
Thanks ！
