### ISSUE TITLE
Get nodes Kubernetes Labels

### ISSUE THREAD

**Issue by rubenssoto** [prometheus-operator/prometheus-operator#4610]
Hello Everyone,

I have some rules that I need to filter by nodes labels, how can I do that? For example on metric
container_memory_working_set_bytes I don't have any node label info.

thank you

**Comment by PhilipGough** [comment]
If I understand your question correctly, you are looking to join the metrics `container_memory_working_set_bytes ` and  `kube_node_labels` which is exposed from [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics)?

If that is the case, then you will need to add the following arg to your kube-state-metrics Deployment `- --metric-labels-allowlist=nodes=[*]` 

And assuming I add a label such as `kubectl label nodes <node-name> some-example=indeed` then my join would look like

`container_memory_working_set_bytes * on(node) group_left(label_some_example) kube_node_labels{}`
