### ISSUE TITLE
Prometheus: added command arguments for remote write receiver

### ISSUE THREAD

**Issue by ncauchois** [prometheus-operator/prometheus-operator#4613]
**What is missing?**

https://github.com/prometheus/prometheus/pull/10119 added the possibility of enable remote-write-receiver feature with flag `--web.enable-remote-write-receiver`.
But in prometheus-operator this argument cannot be passed to Prometheus container.

**Why do we need it?**

To have remote-write-receiver feature with flag `--web.enable-remote-write-receiver`.

**Environment**

* Prometheus Operator version: 0.54.0
* Prometheus version: 2.33.0

**Comment by slashpai** [comment]
Looks valid to me, I can work on this one if we decide to have this. I will let maintainers decide :)

**Comment by simonpasquier** [comment]
This looks good to me. Note that you can still use the `--enable-feature=remote-write-receiver` option via `spec.enableFeatures`.

**Comment by ncauchois** [comment]
Yes, but we will no longer be able to use this flag in next versions :
```
Activating the remote write receiver via a feature flag is deprecated. Use --web.enable-remote-write-receiver instead. This feature flag will be ignored in future versions of Prometheus.
```

**Comment by simonpasquier** [comment]
I believe that the feature flag isn't ignored yet.

**Comment by dmfrey** [comment]
I cannot find any information on how to enable this flag. How do you use it?

I've enabled the Observability addon to microk8s. I came across this issue after finding adding the flag to the arguments of the statefulset never passed them to the pod.

Can someone point me to documentation on enabling this with the operator?

**Comment by JoaoBraveCoding** [comment]
What version of prometheus-operator are you using? You shouldn’t edit the StatefulSet directly, you should instead set the field `enableRemoteWriteReceiver: true` in the Prometheus CR.
https://doc.crds.dev/github.com/prometheus-operator/prometheus-operator/monitoring.coreos.com/Prometheus/v1@v0.61.1

**Comment by dmfrey** [comment]
Yes, that's what I ended up doing. I was missing that aspect.

**Comment by Siradjedd** [comment]
i  added this to the values.yaml: 
prometheus:
   prometheusSpec:
       enableRemoteWriteReceiver: true
 
 BUT i'am still getting : remote write receiver needs to be enabled with --web.enable-remote-write-receiver
when i try to curl the endpoint using : curl -X POST http://endpoint_address/api/v1/write
--
Also i can't find that flag in the configurations file in prometheus ui.

**Comment by Wittman80** [comment]
> Agregué esto a values.yaml: prometheus: prometheusSpec: enableRemoteWriteReceiver: true
> 
> ## PERO sigo recibiendo: el receptor de escritura remota debe habilitarse con --web.enable-remote-write-receiver
> cuando intento rizar el punto final usando: curl -X POST http://endpoint_address/api/v1/write
> Tampoco puedo encontrar esa bandera en el archivo de configuraciones en la interfaz de usuario de Prometheus.

Me too, whit bitnami/prometheus:2.53.0-debian-12-r0 > and --enable-feature=remote-write-receiver NO FLAG ADD... any ideas?? is a bug?

**Comment by xiaoxlm** [comment]
just add field `enableRemoteWriteReceiver` under `spec`:

```yaml
spec:
  enableRemoteWriteReceiver: true
  ...
```
