### ISSUE TITLE
Is AWS EFS supported?

### ISSUE THREAD

**Issue by dantheman0207** [prometheus-operator/prometheus-operator#4631]
You can see [here](https://github.com/prometheus-operator/prometheus-operator/issues/3150#issuecomment-665911221) that it was recommended not to use EFS with Prometheus. Reasons cited were lots of bug reports coming in and that it was likely not POSIX-compliant despite AWS's claims to the contrary. Does this still hold? Is there an official position on whether EFS or any other NFS is supported?

I appreciate the help.

That EFS is not supported is also mentioned [here](https://github.com/prometheus/prometheus/issues/5617#issuecomment-664907964),  and again in the same issue [here](https://github.com/prometheus/prometheus/issues/5617#issuecomment-747724957).

**Comment by fpetkovski** [comment]
The lack of support is called out in the official prometheus docs: https://prometheus.io/docs/prometheus/latest/storage/

```
CAUTION: Non-POSIX compliant filesystems are not supported for Prometheus' local storage as unrecoverable 
corruptions may happen. NFS filesystems (including AWS's EFS) are not supported. NFS could be POSIX-compliant, 
but most implementations are not. It is strongly recommended to use a local filesystem for reliability.
```

**Comment by dantheman0207** [comment]
Thanks!
