### ISSUE TITLE
Provide Short Names for Custom Resource Definitions

### ISSUE THREAD

**Issue by pschulten** [prometheus-operator/prometheus-operator#4640]
**What is missing?**
CRDs don't provide a short name

**Why do we need it?**
Convenience :)

**Anything else we need to know?**:
I think it's quite common to provide short names for CRDs nowadays:
* keda.sh: ScaledObject: Short Names: so
* autoscaling.k8s.io: VerticalPodAutoscaler: Short Names: vpa
* cilium.io: CiliumNode: Short Names: cn

**Comment by slashpai** [comment]
I will give it a go :)
