### ISSUE TITLE
Admissions controls in prometheus-operator after k8s v1.25

### ISSUE THREAD

**Issue by rparke** [prometheus-operator/prometheus-operator#4648]
**What is missing?**
Dynamic Admissions controls for Pods.

**Why do we need it?**
prometheus-operator manages creation of its pod security policy objects. psps have been depricated since kubernetes version 1.21 and will be removed in 1.25. As a result many cluster admins are moving to write their own policy for admissions control of pods (and in fact other resources) using tools like Open Policy Agent, kyverno, _etc._. 

As far as I'm aware it's not clear what prometheus-operator will be replacing psps with (if anything), or how prometheus-operator will integrate with the range of Dynamic admissions controllers present on clusters. 

**Environment**

Not applicable

* Prometheus Operator version:

Not applicable

**Anything else we need to know?**:

This is just a request for clarity (and seemed the most applicable issue template to use). Fundamentally I don't personally think it's an issue prometheus-operator simply provides nothing as a replacement for psps, and leaves admissions controls as a job for the cluster administrator (a job they'll almost certainly be doing anyway). But in terms of forward planning, it would be useful to know exactly what approach prometheus-operator is taking so we're ready to upgrade once kuberenetes v.1.25 is ready.

**Comment by rparke** [comment]
Possibly. I'm dealing with a stack that I didn't build at the minute. My (possibly mistaken) understanding was that operator created its own psps. I take it this isn't the case?

**Comment by simonpasquier** [comment]
> I take it this isn't the case?

correct the operator doesn't create/manage PodSecurityPolicys.

**Comment by rparke** [comment]
Ah great. My confusion was that we use ansible to deploy the operator (via helm), and since there was no task to create the psp I'd assumed it was created by the operator.

I'll close
