### ISSUE TITLE
Add support for active time intervals in AlertmanagerConfig CRD

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#4656]
**What is missing?**

Alertmanager v0.24 (to be released soon) supports active time intervals (see https://github.com/prometheus/alertmanager/pull/2779). The functionality would need to be added to the AlertmanagerConfig CRD too.

Similar to what happens in Alertmanager, the existing `spec.muteTimeIntervals` field needs to be deprecated in favor of `spec.timeIntervals`. The operator could seamlessly merge both fields in the generated configuration:
* using `time_intervals` if the Alertmanager's `spec.version` is >= v0.24.
* `mute_time_intervals` otherwise.

**Why do we need it?**

Feature parity with upstream Alertmanager.

**Environment**

* Prometheus Operator version: N/A

**Anything else we need to know?**:

**Comment by slashpai** [comment]
I will give it a go

**Comment by simonpasquier** [comment]
The plan is to make the change as part of the new v1beta1 AlertmanagerConfig (see #4677).

**Comment by from-nibly** [comment]
Any news on adding support for active_time_intervals?

**Comment by simonpasquier** [comment]
This issue is tagged with `help_wanted`, anybody is free to contribute a PR :)

**Comment by simonpasquier** [comment]
#5135 implemented the support for active time intervals in the generated configuration. We still need to add similar support to the AlertmanagerConfig CRD (both v1alpha1 and v1beta1).
