### ISSUE TITLE
Add validation for the OpsGenie's responders

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#4659]
**What is missing?**

~~Alertmanager v0.24 (to be released soon) supports for `teams` responders in the OpsGenie receiver configuration. The same needs to be added to the AlertmanagerConfig CRD.~~

Proper validation of the responder field for the OpsGenie integration:
* At the OpenAPI spec level with `// +kubebuilder:validation:Enum` marker
* When generating the configuration to ensure that the responder specification is supported by the given Alertmanager version.

**Why do we need it?**

Feature parity.

**Environment**

* Prometheus Operator version: N/A

**Anything else we need to know?**:

**Comment by mikechengwei** [comment]
Ref: #https://github.com/prometheus/alertmanager/pull/2685 , i think prom-operator not need to add new filed to support teams, because teams feature  reuse the original `type` field. WDYT? @simonpasquier

**Comment by mikechengwei** [comment]
ok
