### ISSUE TITLE
Installing 2 operators fight for clusterrole monitoring-edit

### ISSUE THREAD

**Issue by zfrhv** [prometheus-operator/prometheus-operator#4669]
**What happened?**
Installed the operator in 2 namespaces, and each of the tries to modify `ClusterRole/monitoring-edit` for his own need.

**Did you expect to see something different?**
I expected each operator to create his own `ClusterRole`

**How to reproduce it (as minimally and precisely as possible)**:
Install 2 operators in 2 different namespaces. and see that `metadata.labels["olm.owner.namespace"]` is keep changing.
its not a problem if you install operator with the same version, but it is a problem if you have different versions.
each operator tries to configure his own permissions.
for example `openshift-monitoring` will conflict with your own operator for that `ClusterRole`.

**Environment**
  openshift 4.8.19

* Prometheus Operator version:
  `v0.47.0`

* Kubernetes version information:

  `v1.21.4+6438632`

* Kubernetes cluster kind:

  Openshift UPI installation on vmware

* Manifests:

* Prometheus Operator Logs:
no errors and nothing about `ClusterRole`.
(im in airgapped network so it make take a while to get out the logs)

**Anything else we need to know?**:
I think the solution would be to create `ClusterRole` with name `$(NAMESPACE)-monitoring-edit`, this will avoid conflicts.
yet using the operator fails `openshift-monitoring` because of that `ClusterRole` (even when the operator is namespaced)

**Comment by simonpasquier** [comment]
:wave: the maintainers of this repository don't maintain the OLM bundle. you'll have to ask https://github.com/k8s-operatorhub/community-operators directly.

**Comment by zfrhv** [comment]
ooo ok :0
