### ISSUE TITLE
Get rid of `github.com/pkg/errors` dependency

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#4682]
https://github.com/pkg/errors has been archived and is no longer maintained. 

~~At least 2 options are available:~~
* ~~Use a drop-in replacement like https://github.com/emperror/errors.~~
- [ ] Use the [`errors`](https://pkg.go.dev/errors) package from the standard Go library.
- [x] Add a `depguard` rule in the golang-cilint configuration to prevent future use of `github.com/pkg/errors`.

See also https://github.com/thanos-io/thanos/issues/5176

**Comment by simonpasquier** [comment]
Personally I'd be fine with using the standard `errors` package since the code doesn't rely on advanced capabilities of `github.com/pkg/errors` such as stack trace logging.

**Comment by slashpai** [comment]
will do this

**Comment by PhilipGough** [comment]
@slashpai - thanks, its yours :)

**Comment by slashpai** [comment]
Not stale I am working on this

**Comment by slashpai** [comment]
@simonpasquier  I was wondering if we want to consider https://github.com/cockroachdb/errors as replacement to github.com/pkg/errors

**Comment by chiukapoor** [comment]
Hello Team, Is anyone working on this issue? If not, may I work on it?

**Comment by slashpai** [comment]
@chiukapoor please feel free to work on :)

**Comment by chiukapoor** [comment]
@slashpai may you please assign the issue to me

**Comment by slashpai** [comment]
> @slashpai may you please assign the issue to me

Generally commenting on issue is needed to start working on :). I can assign it to you though

**Comment by simonpasquier** [comment]
@chiukapoor please submit as many PRs as you wish. In general, smaller changes are easier to review and faster being merged :)

**Comment by simonpasquier** [comment]
Hmm shouldn't we keep the issue opened until all occurrences of github.com/pkg/errors have been replaced?

**Comment by ArthurSens** [comment]
Oh yes, my mistake
