### ISSUE TITLE
Support http_sd_configs/file_sd_configs for CRD ServiceMonitor/PodMonitor

### ISSUE THREAD

**Issue by Kuckkuck** [prometheus-operator/prometheus-operator#4685]
The custom resources `ServiceMonitor` and `PodMonitor` are missing the Prometheus config feature for `http_sd_configs` and `file_sd_configs`. To remove jobs from the default Prometheus config and move them to the CRD ServiceMonitor, it makes sense  to at least add the feature for ServiceMonitor to retrieve config from the http_sd_configs: url.

**What is missing?**
ServiceMonitor and PodMonitor need support for `http_sd_configs`/`file_sd_configs` section with the `url` parameter. Prometheus exporters like the snmp-exporter needs target/module lists, which are retrieved by Prometheus via a http_sd_configs section.

**Comment by simonpasquier** [comment]
This is similar to #2787, that is a new CRD able to suport any Prometheus scrape configuration.
