### ISSUE TITLE
Prometheus path

### ISSUE THREAD

**Issue by xobot42** [prometheus-operator/prometheus-operator#4692]
Hello. In `serviceMonitor` manifest in section endpoints we have this structure:

`  endpoints:
    - port: http
       path: /actuator/prometheus`

And in the `service` manifest this:

`metadata:
    annotations:
      prometheus.io/scrape: True
      prometheus.io/path: /actuator/prometheus`

Could you explain please. Should I use both of them `path` or is one enough? And which one is in priority?

**Comment by fpetkovski** [comment]
You do not need the annotations in the Service object, the ServiceMonitor should have all the information it needs.

**Comment by xobot42** [comment]
@fpetkovski thanks
