### ISSUE TITLE
how to update container args

### ISSUE THREAD

**Issue by hjfeng1988** [prometheus-operator/prometheus-operator#4700]
My prometheus need reverse proxy,One domain name reverse proxy a variety of services.So I need to modify prometheus args `--web.route-prefix=/prometheus`.

I had look for everything,but can't found where to update.

**Comment by PhilipGough** [comment]
@hjfeng1988 does https://github.com/prometheus-operator/prometheus-operator/blob/9c0db5656f04e005de6a0413fd8eb8f11ec99757/Documentation/user-guides/strategic-merge-patch.md work for you?

**Comment by hjfeng1988** [comment]
@PhilipGough tks,It works.

But prometheus start failure,I give up such a need.
