### ISSUE TITLE
Lack of clear documentation about how to have Pods/Services picked up by Prometheus

### ISSUE THREAD

**Issue by mbihoop** [prometheus-operator/prometheus-operator#4701]
I've been searching the web and reading for an hour now, I understood what instructions I needed to give my users in 2018/2019 - annotate your pods/services and go to the pub. 

Now, in 2022 I still can't understand what is necessary with the new way of doing things. I'm not a moron, and I've been doing this stuff for > 2 decades +. 

Can someone please clarify or point out the relevant documentation of how to expose Pod metrics so that Prometheus will scrape the metrics. I know the annotations approach no longer works out of the box (which I think is a bad idea as that's what 90% of users wanted). 

If there is no documentation, I'm happy to contribute a readme file. Just give me some pointers and I'll throw a document together.

**Comment by thomassuedbroecker** [comment]
@PhilipGough The documentation works perfect for the example application, but if you going to add custom ServiceMonitors and Prometheus instances in different namespaces, it seems the the automatic scrape of the _ServiceMonitor_ doesn't work.  

I used that [useful blog post](https://www.infracloud.io/blogs/prometheus-operator-helm-guide/) to inspect in detail the _cat prometheus.yml_ on the prometheus instance pod, wondering why ServiceMonitors aren't listed.

In the _default_ namespace I run the example which works fine and I created a new instance in a different namespace but _ServiceMonitor_  isn't loaded into the  _cat prometheus.yml_ file. I also checked the labels.

**Comment by mbihoop** [comment]
_I think_ ServiceMonitor won't work for my use case as I need to monitor distributed databases that are not fronted by a Service (each Pod runs on a separate node and is exposed individually).
I understand some of the user demands that must have prompted this design, one thing that has been lost from the original design is the fact that one could look at a Pod or Pod Template and instantly know whether it was being scraped by Prometheus and how the scraping was configured. Now, one has to look for these other ServiceMonitor/PodMonitor objects and iterate through all of them in order to know what is being scraped.

**Comment by PhilipGough** [comment]
Hi @thomassuedbroecker - PTAL [troubleshooting guide](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/troubleshooting.md#troubleshooting-servicemonitor-changes) to debug why your targets are not being discovered/scraped.

Hi @mbihoop - perhaps take a look at [PodMonitor](https://github.com/prometheus-operator/prometheus-operator/blob/2809ca11242cb6fdc107257a8e0a77ea37055810/Documentation/design.md#podmonitor)

**Comment by mbihoop** [comment]
@PhilipGough Thanks - I understand now what's available, it's a little more complex than what I was used to before but is clearly documented. I'll close this out.

**Comment by thomassuedbroecker** [comment]
Hi @mbihoop, I made a long blog post [MONITOR YOUR CUSTOM OPERATOR WITH PROMETHEUS](https://suedbroecker.net/2022/04/08/monitor-your-custom-operator-with-prometheus/) maybe that helps to understand better. Greetings Thomas

FYI: @PhilipGough maybe you want to take a look also. Feedback is always welcome  ;-)
