### ISSUE TITLE
Add Telegram Receiver type to AlertmanagerConfig CRD

### ISSUE THREAD

**Issue by askoriy** [prometheus-operator/prometheus-operator#4703]
Alertmanager since [0.24.0](https://github.com/prometheus/alertmanager/releases/tag/v0.24.0) supports native Telegram integration.

But currently prometheus-operator still doesn't support it, and configuring telegram resulting
```
level=error ts=2022-04-01T13:05:48.759330324Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"monitoring/prometheus-kube-prometheus-alertmanager\" failed: provision alertmanager configuration: base config from Secret could not be parsed: yaml: unmarshal errors:\n  line 6: field telegram_configs not found in type config.plain"
```
So please add support of `telegram_configs` in AlertmanagerConfig CRD

**Comment by PhilipGough** [comment]
@askoriy - would you like to give it a go?

**Comment by angelbarrera92** [comment]
Im having the same issue :)

**Comment by angelbarrera92** [comment]
I did something here #4726. Who can take a look/review it?
