### ISSUE TITLE
There's nothing dynamic about ProbeSpec targets 

### ISSUE THREAD

**Issue by OneCricketeer** [prometheus-operator/prometheus-operator#4704]
**What happened?**

I read ProbeSpec documentation saying "dynamically discovered targets to probe", but it's clearly not referring to the staticConfig, and I don't have Ingress objects I want to scrape. 

If it is only dynamic for Ingress resources, I feel that should be explicitly stated in `ProbeSpec` rather than nested in the Target spec, and us making the assumption that other types of dynamic discovery can be supported. 

**Did you expect to see something different?**

**Anything else we need to know?**:

What I was looking for was something close to `ec2_sd_config`, (dynamically discovering external resources, not part of k8s), and written as a Probe rather than  modifying the Prometheus scraper spec itself. 

E.g. The Blackbox exporter is running as a k8s service, and I want to dynamically target a set of EC2 instances in an ASG (http/s, or tcp port checks, for example) not a static list of addresses, and not any available Prometheus metrics endpoint that may or may not be running on those instances (such as what `ec2_sd_config`needs)

**Comment by OneCricketeer** [comment]
> documentation should be improved

Yes, [`ProbeSpec`](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#probespec) docs should clarify what "dynamic" means. 

Second part of my request is more of a feature-request, or if I am using the wrong tool overall, feel free to let me know. Basically, is there a way for the `Probe` resource to take advantage of Prometheus's service discovery modules to find any external endpoints, rather than statically list them out, or otherwise have some external script that will gather that list, then template it into a `helm upgrade --set ... ${new_values}`, for example?

**Comment by simonpasquier** [comment]
> Yes, [ProbeSpec / targets](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#probespec) docs should clarify what "dynamic" means.

would you like to submit a PR to improve the description?

>Second part of my issue is more of a feature-request, or if I am using the wrong tool overall, feel free to let me know.

for now you'd probably want to use `additionalScrapeConfigs`. Eventually we want to add a `ScrapeConfig` CRD that woull support all Prometheus scrape options (see https://github.com/prometheus-operator/prometheus-operator/issues/2787).

**Comment by OneCricketeer** [comment]
> submit a PR

I would if I knew what "dynamic" was referring to

**Comment by OneCricketeer** [comment]
> for now you'd probably want to use additionalScrapeConfigs

This doesn't seem to be what I want either. I want to scrape a blackbox-exporter. This works, as expected. Rather, I want to be able to discover it's targets rather than statically list those.

I feel this is more a limitation of the Blackbox exporter, so will move my issue there
