### ISSUE TITLE
如何修改alertmanager的配置文件，

### ISSUE THREAD

**Issue by jibingjie2** [prometheus-operator/prometheus-operator#4717]
我尝试修改alertmanager的配置文件，首先我创建一个secret指定我的配置文件，然后修改alertmanager的sts，把secret指向我创建好的，当我退出后，它又指向了原有的secret。
然后我看到一个crd，alertmanagerconfig，它看起来像是可以修改alertmanager的配置文件，但是我在网上浏览了很多信息，都没有找到它的使用方法。
最后，我的目的是修改alertmanager的配置文件，怎么样可以实现

**Comment by jibingjie2** [comment]
> 改掉alertmanager的那个secret后alertmanager会自动读取配置文件进行更新

它默认的secret删掉会立即重建，要怎么修改

**Comment by daviderli614** [comment]
这个secret不需要删除，只需要把secret内容获取，然后调用client-go把他update就可以修改
或者直接kubectl edit secret进去修改

**Comment by jibingjie2** [comment]
调用client-go把他update就可以修改这种方式我暂时不太了解
直接edit进去修改保存退出后，它依然会恢复原本的配置

**Comment by daviderli614** [comment]
应该不会，我把secret修改后是生效的

**Comment by jibingjie2** [comment]
![image](https://user-images.githubusercontent.com/101303865/163517088-d85795fb-855a-4a53-9604-820b3a81d85f.png)
我将它编辑后，保存退出。
![image](https://user-images.githubusercontent.com/101303865/163517152-aaf2432f-b922-4576-aef3-c69ff8b1c324.png)
它依然显示830Bytes。
![image](https://user-images.githubusercontent.com/101303865/163517200-69b52f78-6884-4821-bce6-822e3bf9f1b0.png)
再进去看，它又是原样

**Comment by daviderli614** [comment]
你应该改另外一个secret，它叫alertmanager-xxx-alertmanager

**Comment by jibingjie2** [comment]
我似乎并没有看到你所说的secret，包括别的namespace我也有查看，并不存在
![image](https://user-images.githubusercontent.com/101303865/163518576-e85df23c-eb32-49e8-9b94-3fe69415d35f.png)

这些是我的镜像版本
![image](https://user-images.githubusercontent.com/101303865/163518607-c8b56e6a-eefe-4123-85a1-18b8c13edcfc.png)

**Comment by daviderli614** [comment]
你试一下改上图那个叫alertmanager-main的secret

**Comment by jibingjie2** [comment]
谢谢，成功了，修改了alertmanager-main后，alertmanager-main-generated会一同发生改变，并且alertmanager-main-generated也能手动修改了
