### ISSUE TITLE
Incomplete documentation 

### ISSUE THREAD

**Issue by yngwiewang** [prometheus-operator/prometheus-operator#4721]
[https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/rbac.md](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/rbac.md)

> The Prometheus Operator reconciles `services` called `prometheus-operated` and `alertmanager-operated`, which are used as governing `Service`s for the `StatefulSet`s. To perform this reconciliation

I thik it should be

The Prometheus Operator reconciles `services` called `prometheus-operated` and `alertmanager-operated`, which are used as governing `Service`s for the `StatefulSet`s. To perform this reconciliation it needs to `get`, `create`, `update` and `delete` `Service`s.

Is that right? Could I create a PR for this?

@simonpasquier @brancz

**Comment by simonpasquier** [comment]
@yngwiewang sounds good to me, go for it!
