### ISSUE TITLE
prometheuses, alertmanagers, thanosrulers CRD should add scale subresources

### ISSUE THREAD

**Issue by nashtsai** [prometheus-operator/prometheus-operator#4727]
**What is missing?**
prometheuses, alertmanagers, thanosrulers CRD should add [scale subresources](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource)

**Why do we need it?**

So `kubectl scale ...` would just work and provided documentation stated "When the scale subresource is enabled, the /scale subresource for the custom resource is exposed. The autoscaling/v1.Scale object is sent as the payload for /scale."

**Environment**

* Prometheus Operator version:

    `prometheus-operator/prometheus-operator:v0.53.1`

**Anything else we need to know?**:

**Comment by slashpai** [comment]
will do this

**Comment by slashpai** [comment]
Reopening this since we are reverting the change https://github.com/prometheus-operator/prometheus-operator/pull/4952
I will submit another patch for same to consider HPA

**Comment by NetanelK** [comment]
It seems like alertmanagers and thanosrulers CRDs still miss the `/scale` subresource.
Will it be fixed?
