### ISSUE TITLE
Failed to resolve alertmanager-main-2.alertmanager-operated:

### ISSUE THREAD

**Issue by kapilgarg83** [prometheus-operator/prometheus-operator#4747]
Hi,

I just restarted by Alertmanager PODs and below is the error now
ALL 3 pods are crashing now. Anyone have any idea..??

_component=cluster msg="failed to join cluster" err="3 errors occurred:\n\t* Failed to resolve alertmanager-main-0.alted:9094: lookup alertmanager-main-0.alertmanager-operated on 10.100.0.10:53: no such host\n\t* Failed to resolve alertmanager-main-1.alertmanager-operated:9094: lookup alertmanager-main-perated on 10.100.0.10:53: no such host\n\t* Failed to resolve alertmanager-main-2.alertmanager-operated:9094: lookup alertmanager-main-2.alertmanager-operated on 10.100.0.10:53: no such
          level=info ts=2022-04-21T14:13:55.822Z caller=cluster.go:253 component=cluster msg="will retry joining cluster every 10s"_

 level=warn ts=2022-04-21T14:13:55.822Z caller=main.go:316 msg="unable to join gossip mesh" err="3 errors occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operatalertmanager-main-0.alertmanager-operated on 10.100.0.10:53: no such host\n\t* Failed to resolve alertmanager-main-1.alertmanager-operated:9094: lookup alertmanager-main-1.alertmanager-op.0.10:53: no such host\n\t* Failed to resolve alertmanager-main-2.alertmanager-operated:9094: lookup alertmanager-main-2.alertmanager-operated on 10.100.0.10:53: no such host\n\n"
          level=info ts=2022-04-21T14:13:55.822Z caller=cluster.go:671 component=cluster msg="Waiting for gossip to settle..." interval=2s
          level=info ts=2022-04-21T14:13:56.338Z caller=coordinator.go:113 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
          level=error ts=2022-04-21T14:13:56.339Z caller=coordinator.go:118 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml must specify a default receiver"

**Comment by simonpasquier** [comment]
you've got an invalid configuration file
```
level=error ts=2022-04-21T14:13:56.339Z caller=coordinator.go:118 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml must specify a default receiver"
```
