### ISSUE TITLE
Add Lark/Feishu support to AlertmanagerConfig

### ISSUE THREAD

**Issue by GalvinGao** [prometheus-operator/prometheus-operator#4751]
**What is missing?**
- feishu.cn, or its international product larksuite.com is an all-in-one collaboration platform. They provides a pretty simple webhook for bots to integrate with, but the format of the webhook is somewhat complicated. Adding native support allows the users to integrate prometheus alertmanager way more easily.

**Why do we need it?**
- Webhook templates could work in this case, however to reduce the initial learning cost for users this might still be a good idea.

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.55.1`
    
    

**Anything else we need to know?**:
- I'm happy to contribute a PR if the maintainers feel good about this :D

**Comment by simonpasquier** [comment]
this isn't a question for the Prometheus operator project but rather Alertmanager.
