### ISSUE TITLE
how to not load the history metrics from disk after resttart prometheus pod

### ISSUE THREAD

**Issue by bruse-peng** [prometheus-operator/prometheus-operator#4761]
**What did you do?**

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

my prometheus opreator metrics store on the disk,  one day i delete the servicemonitor, 30 mintiues later i can still find the target on prometheus, then i restart the prometheus pod, the pod will load all history metric from disk  then  the kubernet node out of memory agian and again,so i have two issue:
1、why the tartget still can be find on prometheus when i delete servicemonitor
2、how to resolve not load all history metric from disk when i restart prometheus pod

**Comment by simonpasquier** [comment]
> why the tartget still can be find on prometheus when i delete servicemonitor

without more details it's hard to tell. First thing would be to check the prometheus operator logs.

> how to resolve not load all history metric from disk when i restart prometheus pod

I assume that you've configured persistent storage for Prometheus. You can configure an emptyDir volume instead if you don't need/want to retain data across restarts.

**Comment by bruse-peng** [comment]
> configured persistent storage for Prometheus

yes  i want persistent storage for Prometheus,but i configure an emptyDir volume, how can make sure data not be lost after i resstart prometheus pod

**Comment by simonpasquier** [comment]
I'm not sure to follow exactly but if you want persistent storage then read https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md.
