### ISSUE TITLE
Alertmanagerconfig injecting namespace into config for non kubernetes alerts

### ISSUE THREAD

**Issue by charris-ca** [prometheus-operator/prometheus-operator#4764]
**What is missing?**

   Ability to turn automatic namespace add to Alertmanagerconfig resources

**Why do we need it?**

   We are trying to use kubernetes resources with our deployment mechanism as our gitops hub for all alerts.  We have alerts outside of prometheus that are sending to this alertmanager instance, but want to manage that config with the alertmanagerconfig resource.  We are currently forced to add a namespace label to alerts that are not coming from kubernetes for them to fire.

* Prometheus Operator version:

   v0.53.1

I know this was brought up in this issue, but didn't see any progress being made.  I think consensus is that the operator should have a configurable value for turning the namespace injector on

**Comment by simonpasquier** [comment]
I believe that the main concerns have been resolved with the latest v0.61.1:
* One can define the main configuration using  `AlertmanagerConfig` CRD (with the `spec.alertmanagerConfiguration` field).
* It is possible to disable the namespace enforcement when AlertmanagerConfig objects are merged in the resulting configuration using `spec.alertmanagerConfigMatcherStrategy.type: None`.

**Comment by charris-ca** [comment]
Awesome thank you!
