### ISSUE TITLE
metricRelabelings do not always work

### ISSUE THREAD

**Issue by jeremiahhguo** [prometheus-operator/prometheus-operator#4775]
**What did you do?**
Hi, we use a service monitor to scrape metrics from a service and we would like to add a prefix to all metric name with metricRelabelings  (see service monitor config below). But we found our metricRelablings do not always work: we see same metrics from same pod at around same time both with and without this prefix in our metric-ingestion-pod log (see log examples at bottom). I wonder do folks have any insight on why this may happen?

Service monitor config:
![image](https://user-images.githubusercontent.com/78013315/167210883-d36f1ae5-a7b9-453e-b89a-b27c777f89f9.png)

Same metric from same pod one with prefix and one without:
![image](https://user-images.githubusercontent.com/78013315/167211395-1f945984-742a-4b51-a095-0876f7f7b822.png)

**Did you expect to see some different?**
We expect the prefix to be always added

**Environment**

* Prometheus Operator version:
quay.io/prometheus-operator/prometheus-operator:v0.55.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"d0b89678ea884ca501cba708c56d2ea41debbf2c", GitTreeState:"clean", BuildDate:"2022-01-31T09:05:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1

* Kubernetes cluster kind:
managed cluster from Azure kubernetes services

**Comment by simonpasquier** [comment]
check your `endpoints` field: it's a list of 5 items while you probably want a single item, e.g.

```
endpoints:
- interval: 15s
  path: /metrics
  port: metrics
  ...
```

JFYI these metrics seem to have unbounded cardinality as they have labels such as timestamps.

**Comment by jeremiahhguo** [comment]
@simonpasquier this works. Thank you!
