### ISSUE TITLE
Add support for `attach_metadata` into ServiceMonitor/PodMonitor

### ISSUE THREAD

**Issue by TaylorMutch** [prometheus-operator/prometheus-operator#4779]
**What is missing?**

As of Prometheus 2.35 we can add the `attach_metadata` option to a `kubernetes_sd_config` to allow us to add `node` labels to pods discovered in the scrape config.

**Why do we need it?**

To be able to expose node metadata as a label on pod metrics, such as for `node_exporter` metrics. This is useful for monitoring items such as `nf_conntrack` on hosts and looking up the node by hostname rather than instance IP.

**Environment**

* Prometheus Operator version: `0.56.2`

**Anything else we need to know?**:

**Comment by fpetkovski** [comment]
Attaching metadata is currently available for the pod role only, so I assume this field would only apply to the PodMonitor resource.

**Comment by slashpai** [comment]
working on this

**Comment by TaylorMutch** [comment]
To confirm my understanding, why would this only be supported on the PodMonitor?

**Comment by TaylorMutch** [comment]
> Attaching metadata is currently available for the pod role only, so I assume this field would only apply to the PodMonitor resource.

Oh I see; I suppose this means we would need to use a PodMonitor on things like node-exporter, which isn't how the kube-prometheus-stack implements this. I wonder if this should be changed on the node-exporter chart used by kube-prometheus-stack. Thanks
