### ISSUE TITLE
Publish new operator releases to Operator Hub 

### ISSUE THREAD

**Issue by ctrought** [prometheus-operator/prometheus-operator#4786]
**What is missing?**

Hello! We’d love to see regular releases of prometheus-operator via OpenShift Operator Hub. The latest version available to us OpenShift users through OperatorHub is quite old, v0.47.0. 

Someone else brought this up in the openshift GH repo and they suggested contacting the prometheus operator authors/contributors to submit. I would submit myself but I don’t have the expertise. We have a few hundred installs of the prometheus operator from the integrated operatorhub in OCP in a multi-tenant environment all still running 0.47.0! Hopefully it is something the team would consider - thanks in advance!

https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/751

**Why do we need it?**

For OKD/OCP/K8S users to be able to use the latest prometheus-operator via OperatorHub and keep them up to date through OLM. Users installing via OperatorHub are currently relying on a very old version of prometheus-operator.

**Anything else we need to know?**:
The process to submit OLM packaged operators [documented here](https://redhat-openshift-ecosystem.github.io/community-operators-prod/).

**Comment by simonpasquier** [comment]
We (Prometheus operator maintainers) don't maintain the OLM version of the operator so there's nothing we can do unfortunately. 

The request should go to https://github.com/k8s-operatorhub/community-operators. AFAIK there's nobody actively looking into it so your best option is probably to submit the PR there yourself (the code is at https://github.com/operator-framework/community-operators/tree/master/community-operators/prometheus).

**Comment by simonpasquier** [comment]
@ctrought yes I get that but unfortunately we have no maintainers available to commit for this. While I understand the frustration, I believe it's better that we don't make false promises: though the work may feel small, it's yet another thing that the team would have to support and maintain.

**Comment by ctrought** [comment]
> @ctrought yes I get that but unfortunately we have no maintainers available to commit for this. While I understand the frustration, I believe it's better that we don't make false promises: though the work may feel small, it's yet another thing that the team would have to support and maintain.

Thanks and understood. I've submitted PR's to them as you suggested.

**Comment by danielloader** [comment]
Hate to necro closed issues, but I thought I'd ask here for others.

@ctrought - did you ever get these Pull requests merged? Noticed the latest version on OperatorHub is still v0.47.0?

Finding it rather laborious trying to install the Prometheus operator at the same time as the Grafana operator given neither installs like the other!

**Comment by ctrought** [comment]
> Hate to necro closed issues, but I thought I'd ask here for others.
> 
> @ctrought - did you ever get these Pull requests merged? Noticed the latest version on OperatorHub is still v0.47.0?
> 
> Finding it rather laborious trying to install the Prometheus operator at the same time as the Grafana operator given neither installs like the other!

I did end up submitting a PR, but as I'm an OpenShift user I only submitted to the OH repo for OCP. 

https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1232
