### ISSUE TITLE
Add support to configure the property max_exemplars

### ISSUE THREAD

**Issue by faustodavid** [prometheus-operator/prometheus-operator#4791]
**What is missing?**
Add support to configure the property `max_exemplars`. 
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#exemplars
```
storage:
  exemplars:
    max_exemplars: 10000000
```

**Why do we need it?**
To increase the max allowed exemplars.

**Comment by slashpai** [comment]
working on this

**Comment by faustodavid** [comment]
Hey @slashpai are you already working on this issue? otherwise, I can create a PR for it :)

**Comment by slashpai** [comment]
Hello @faustodavid I was working on this side, thought to submit PR by end of the week. 
But if you want to try attempting go ahead :)

**Comment by faustodavid** [comment]
Hey @slashpai I think my PR got ignored 😅 , you mentioned you were working on this as well, maybe you can submit yours or help reviewing mine? I really would like to have this feature because at the moment my exemplars just last like 5 minutes.

**Comment by slashpai** [comment]
> Hey @slashpai I think my PR got ignored 😅 , you mentioned you were working on this as well, maybe you can submit yours or help reviewing mine? I really would like to have this feature because at the moment my exemplars just last like 5 minutes.

I will try to review that today :)

**Comment by faustodavid** [comment]
> > Hey @slashpai I think my PR got ignored 😅 , you mentioned you were working on this as well, maybe you can submit yours or help reviewing mine? I really would like to have this feature because at the moment my exemplars just last like 5 minutes.
> 
> I will try to review that today :)

Thanks!
