### ISSUE TITLE
add external node with changed ip addess

### ISSUE THREAD

**Issue by keren-benzion** [prometheus-operator/prometheus-operator#4802]
I have followed the following :https://github.com/prometheus-operator/prometheus-operator/issues/4752# 

and it indeed add external target to the promethues which can be monitored. the only problem with that in my case is that the ip of the external node which I am trying to collect it's metrics is being changed all the time ( in this case I am talking on spot instances in AWS) 

Do you know if there is something that can be done in order to face this issue? 
I am trying to do the same as the github issue I mentioned above. I am trying to add external node as target to promethues operator in kubernetes. 

thanks !

**Comment by fpetkovski** [comment]
You can add an additional scrape config, but the operator won't be able to keep track of the node changing IPs.

**Comment by keren-benzion** [comment]
Is there a way to monitor EC2 instances that does change ip addresses using Prometheus?

**Comment by fpetkovski** [comment]
Not with the prometheus operator, unless you expose each EC2 instance through a static address or a domain name
