### ISSUE TITLE
unable to configure remote_write endpoint (api/v1/write) TLS and client auth settings

### ISSUE THREAD

**Issue by conall88** [prometheus-operator/prometheus-operator#4808]
Hi,

I'm trying to configure the prometheus operator (as part of the kube-prometheus-stack helm charts) so that the `api/v1/write` endpoint used for receiving `remote_write` data is available behind a kubernetes  ingress, for other prometheus instances or the grafana agent to remote_write to.  I'm reasonably new to kubernetes, and very new to helm, so I hope i don't cause too much facepalming!

I inspected the remote_write spec at:
[https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#remotewritespec](url)

But this seems to imply that this instance will be doing the writing, not the reading of the incoming data. Is there something i'm missing here?

Right now the current behavior I have is:

- can reach the api/v1/write endpoint fine via kubectl port-forward, but it complains if a GET is done to it instead of a POST, which makes sense/is expected.
- When I try to reach the endpoint while not port-forwarded, and not behind a reverse proxy, browser complains of a certificate common name mismatch, as browser presents the ingress subdomain certificate from the kubernetes cluster, and it can't be reached as HSTS is enabled.
- When the endpoint is proxied via cloudflare,  the browser returns an error: ERR_SSL_VERSION_OR_CIPHER_MISMATCH, the certificate is never presented.

My questions would be:
- Where do I define which certificate prometheus should present when querying this endpoint?
- Where do I define client auth/ Cert based auth?

Is this api endpoint instead configured by the WebConfig spec? :
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#webspec

I've been trying to configure similar to what the spec describes, but I can't seem to get my web.config.file to pass validation.:

`Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Prometheus.spec.web.tlsConfig.cert): invalid type for com.coreos.monitoring.v1.Prometheus.spec.web.tlsConfig.cert: got "string", expected "map", ValidationError(Prometheus.spec.web.tlsConfig.keySecret): invalid type for com.coreos.monitoring.v1.Prometheus.spec.web.tlsConfig.keySecret: got "string", expected "map"]`

```
## WebTLSConfig defines the TLS parameters for HTTPS
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#webtlsconfig
    web:
      tlsConfig:
        cert: prometheus-tls-cert
        keySecret: prometheus-tls-cert

    ## Enable the receiver for remote_write
    enableRemoteWriteReceiver: true
```
where "prometheus-tls-cert" is a secret mounted on the pod by a mount called "secret-prometheus-tls-cert", including a tls.crt and tls.key file respectively.

**What did you do?**

Attempted to config prometheus instance spawned by prom-operator to be the target for remote_write for grafana agent.

**Did you expect to see some different?**

Expected to see options to enable configuration as a remote_write target

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.56.0`

```
image of prometheus:
      repository: quay.io/prometheus/prometheus
      tag: v2.35.0
```

* Kubernetes version information:

```
    `kubectl version`
    Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12+IKS", GitCommit:"8e414e117f0710d5de97d4ba4945c700b8cf224e", GitTreeState:"clean", BuildDate:"2022-04-20T19:07:09Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    insert how you created your cluster: 

IBM Cloud Kubernetes Service 1.23
`https://cloud.ibm.com/docs/containers?topic=containers-getting-started`

* Manifests:

```
insert manifests relevant to the issue
[values.zip](https://github.com/prometheus-operator/prometheus-operator/files/8756341/values.zip)

urls has been made anonymised.

```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

Required values for Grafana Agent MetricsInstance:

`piVersion: monitoring.grafana.com/v1alpha1
kind: MetricsInstance
metadata:
  name: primary
  namespace: grafana-agent
  labels:
    agent: grafana-agent-metrics
spec:
  remoteWrite:
  - url: prometheus.somewhere.com
    basicAuth:
      username:
        name: primary-credentials-metrics
        key: username
      password:
        name: primary-credentials-metrics
        key: password`

**Comment by fpetkovski** [comment]
What you're interested is remote-read, and you need to enable it in Prometheus by toggling a feature flag: https://prometheus.io/docs/prometheus/latest/feature_flags/#remote-write-receiver. This can be done through the `enableFeatures` field in the `Prometheus` spec.

TLS is not enabled by default and I assume your ingress controller will do TLS termination so you won't need to configure anything in Prometheus itself.

**Comment by conall88** [comment]
receiver is already enabled :

![image](https://user-images.githubusercontent.com/10930485/169983350-77cbd928-9db0-4a04-9139-e1875473ec5a.png)

**Comment by conall88** [comment]
just ingress would be fine. Here's the currently implemented ingress rule spec:

`spec:
  ingressClassName: public-iks-k8s-nginx
  rules:
    - host: write.prometheus.somewhere.com
      http:
        paths:
          - path: /api/v1/write
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090`
                  
`kubectl describe ingress prometheus-kube-prometheus-prometheus -n prometheus
Name:             prometheus-kube-prometheus-prometheus
Namespace:        prometheus
Address:          169.50.4.234
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                           Path  Backends
  ----                           ----  --------
  write.prometheus.somewhere.com
                                 /api/v1/write   prometheus-kube-prometheus-prometheus:9090 (172.30.xxx.xxx:9090)
Annotations:                     meta.helm.sh/release-name: prometheus
                                 meta.helm.sh/release-namespace: prometheus`
                                                   
And the service:

`kubectl describe svc/prometheus-kube-prometheus-prometheus -n prometheus
Name:              prometheus-kube-prometheus-prometheus
Namespace:         prometheus
Labels:            app=kube-prometheus-stack-prometheus
                   app.kubernetes.io/instance=prometheus
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/part-of=kube-prometheus-stack
                   app.kubernetes.io/version=34.10.0
                   chart=kube-prometheus-stack-34.10.0
                   heritage=Helm
                   release=prometheus
                   self-monitor=true
Annotations:       meta.helm.sh/release-name: prometheus
                   meta.helm.sh/release-namespace: prometheus
Selector:          app.kubernetes.io/name=prometheus,prometheus=prometheus-kube-prometheus-prometheus
Type:              ClusterIP
IP Families:       <none>
IP:                172.21.28.232
IPs:               172.21.28.232
Port:              http-web  9090/TCP
TargetPort:        9090/TCP
Endpoints:         172.30.xxx.xxx:9090    (matches above)
Session Affinity:  None
Events:            <none>`

**Comment by fpetkovski** [comment]
Isn't the domain name you're using different than the one on the certificate?

**Comment by dickescheid** [comment]
I am having issues with remoteWrite.
I have tried passing the configurations like so:

```    ## The remote_write spec configuration for Prometheus.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#remotewritespec
    remoteWrite: 
      - url: https://prometheus-remote-path-inter.net/api/prom/push
        basicAuth:
          username: 123456
          password: c3RlYWx0aGlzcGFzc3dvcmQ=
    # - url: http://remote1/push
    ## additionalRemoteWrite is appended to remoteWrite
    additionalRemoteWrite: []
```

and after doing a `helm upgrade monitoring prometheus-community/kube-prometheus-stack -f production.yaml --namespace monitoring`
I get the following message:

```
W0610 10:46:47.926177   27931 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Prometheus.spec.remoteWrite[0].basicAuth.password): invalid type for com.coreos.monitoring.v1.Prometheus.spec.remoteWrite.basicAuth.password: got "string", expected "map", ValidationError(Prometheus.spec.remoteWrite[0].basicAuth.username): invalid type for com.coreos.monitoring.v1.Prometheus.spec.remoteWrite.basicAuth.username: got "integer", expected "map"]
```

When trying to put the `basicAuth` part in `additionalRemoteWrite` the error changes:

```
W0610 11:01:07.168239   28297 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
coalesce.go:223: warning: destination for kube-prometheus-stack.prometheus.prometheusSpec.additionalRemoteWrite is a table. Ignoring non-table value ([])
coalesce.go:223: warning: destination for kube-prometheus-stack.prometheus.prometheusSpec.additionalRemoteWrite is a table. Ignoring non-table value ([])
Error: UPGRADE FAILED: YAML parse error on kube-prometheus-stack/templates/prometheus/prometheus.yaml: error converting YAML to JSON: yaml: line 55: did not find expected '-' indicator
```

**Comment by simonpasquier** [comment]
@dickescheid the username and password fields are secret key selectors:

```
     basicAuth:
          username:
            name: remotewrite-secret
            key: user
          password:
            name: remotewrite-secret
            key: password
```

See https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#basicauth

**Comment by dickescheid** [comment]
whoops 😅 , thanks a lot !
