### ISSUE TITLE
No indication that too many PrometheusRules have been registered

### ISSUE THREAD

**Issue by ChrisSteinbach** [prometheus-operator/prometheus-operator#4832]
**What happened?**

When the number of PrometheusRules published to the operator goes over the limit for what fits in a single config map (prometheus-xxx-rulefiles-0) a new config map is created for the remaining rules (prometheus-xxx-rulefiles-1) but this configuration is silently ignored.

**Did you expect to see something different?**

We expected that either the second rulefiles config map would be read and used by prometheus, or that we would see an error in one of the logs, or some indication that one or more rules have been ignored due to limitations.

**How to reproduce it (as minimally and precisely as possible)**:

Add new alerts via PrometheusRules until the config map prometheus-xxx-rulefiles-1 is created. Then search in the prometheus GUI for the alerts in that config map and you won't see them.

**Environment**

* Prometheus Operator version:

    `0.47.0 provided by Red Hat `
    
    

* Kubernetes version information:

    `v1.22.8+d48376b`
    

* Kubernetes cluster kind: 

    OpenShift

* Prometheus Operator Logs:

No relevant information was seen in the logs, and that's kind of what the issue is about.

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
Can you share the logs of the config-reloader as well as the final Prometheus configuration?
The statefulset definition would also be useful.

**Comment by ChrisSteinbach** [comment]
We solved our problem by removing obsolete test rules. And we did so before saving logs although, like I say, nothing was logged by the config-loader. At least nothing indicative of error.

If we reach the number of rules that trigger this problem again, we will add logs and config. Or create another issue if this one has been closed.
