### ISSUE TITLE
Creating K8s secret with Alertmanager config fails when compressed config is larger than 1MB

### ISSUE THREAD

**Issue by xulianghz** [prometheus-operator/prometheus-operator#4839]
prometheus-operator on Kubernetes Slack. Using K8s secret reload Alertmanager config. But K8s secret there is a limit of not more than 1MB. How to solve the problem of too many configurations?

**Comment by simonpasquier** [comment]
Thanks for the report. Are you using AlertmanagerConfig?

**Comment by slashpai** [comment]
This is fixed in https://github.com/prometheus-operator/prometheus-operator/pull/4906 and will be available in next prometheus-operator release (0.59.0)
