### ISSUE TITLE
Good day. I am facing a similar issue here. I have alertmanager and blackbox configured. However, both shows different information for same endpoint. What am I doing wrong. Please help.

### ISSUE THREAD

**Issue by DareLekan** [prometheus-operator/prometheus-operator#4849]
Good day. I am facing a similar issue here. I have alertmanager and blackbox configured. However, both shows different information for same endpoint. What am I doing wrong. Please help.
![prometheus config 1](https://user-images.githubusercontent.com/77133189/173334810-955e7bf2-b6fb-4188-9791-58abb8ad5a71.JPG)
![prometheus config 2](https://user-images.githubusercontent.com/77133189/173334815-d1143ada-71d1-491d-b873-0511069acebf.JPG)
![prometheus UI alertmanagere](https://user-images.githubusercontent.com/77133189/173334818-ffc1dbba-1051-4ef7-b457-7929d3b12740.JPG)
![prometheus UI alertmanagere22](https://user-images.githubusercontent.com/77133189/173334821-1c61c7cd-0634-49bd-8150-962fcbc5b830.JPG)
![prometheus UI alertmanagere33](https://user-images.githubusercontent.com/77133189/173334826-eabd92c9-1c83-4df0-9a25-67c82d3afa22.JPG)
![prometheus UI alertmanagere44](https://user-images.githubusercontent.com/77133189/173334829-ed7f4ccd-a587-4fc6-9929-46c7052b1051.JPG)
![prometheus UI blackbox](https://user-images.githubusercontent.com/77133189/173334832-ec2c9c11-f153-4a64-a132-06749efee0b0.JPG)

I have attached screenshot to help in explaining my pain point

_Originally posted by @DareLekan in https://github.com/prometheus-operator/prometheus-operator/issues/3245#issuecomment-1153749596_

**Comment by slashpai** [comment]
Could you please share the Probe configuration?

**Comment by DareLekan** [comment]
> Could you please share the Probe configuration?

Here @slashpai 
![blackbox probe](https://user-images.githubusercontent.com/77133189/173548998-73ef808a-7ef7-4257-9271-815f661ef2a0.JPG)

**Comment by DareLekan** [comment]
> hey sorry I was not clear earlier. I meant the Probe custom resource you created

Thanks @slashpai I am pretty new to this, however does the screenshot attached meet what you asked?
![alert probe 2](https://user-images.githubusercontent.com/77133189/173552395-ea4e7cba-0d59-4a33-8326-af873803134b.JPG)
![alert probe](https://user-images.githubusercontent.com/77133189/173552407-79a7fb5a-9199-43d0-a8d8-753a99471072.JPG)

**Comment by DareLekan** [comment]
> I suppose you would have created a [probe custom resource](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#probe) inorder to monitor these static targets in kubernetes cluster?
> 
> But I just reviewed your screenshots again and they point to localhost address for blackbox exporter. So I assume you are asking issue about blackbox exporter and not related to prometheus-operator's Probe resource

You are correct @slashpai I am asking about the blackbox exporter.

**Comment by slashpai** [comment]
I suppose that would be a question for https://github.com/prometheus/blackbox_exporter :)

**Comment by DareLekan** [comment]
> I suppose that would be a question for https://github.com/prometheus/blackbox_exporter :)

Thank you for the resource. I have followed the link

**Comment by slashpai** [comment]
Thank you, closing this issue since its related to blackbox-exporter
