### ISSUE TITLE
Add support for passing web.max-connections argument to Prometheus

### ISSUE THREAD

**Issue by vivekjainx86** [prometheus-operator/prometheus-operator#4850]
**What is missing?**
I didn't find any specification in PrometheusSpec to pass `--web.max-connections=<integer>` argument to Prometheus. Also, there is no support for passing configuration parameter to Prometheus which is not in PrometheusSpec.

**Why do we need it?**
It will be helpful if PrometheusSpec has all the configuration parameters that Prometheus has, or at least there should be a way to provide additional configuration parameters.

**Environment**

* Prometheus Operator version:

    `v2.32.1`

**Comment by slashpai** [comment]
@vivekjainx86 would you like to contribute? :)

**Comment by simonpasquier** [comment]
> or at least there should be a way to provide additional configuration parameters.

I've just filed #4851which is about this use case as it was an action item from our last office hours meetings :)

**Comment by JoaoBraveCoding** [comment]
With #4851 being closed shouldn't this be closed as well? Or do we want dedicated support for this?

**Comment by simonpasquier** [comment]
I'd keep the issue opened. The CRD should eventually allow setting this parameter: 

```
spec:
  web:
    maxConnections: 256
```

**Comment by grv180290** [comment]
You can try something like this. It works for me in the values.yaml for helm. 

```
          prometheusSpec:
            additionalArgs:
            - name: web.max-connections
              value: "10000"
```
