### ISSUE TITLE
Add support for additional CLI arguments to Prometheus, Alertmanager and Thanos Ruler

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#4851]
**What is missing?**

Users have no practical way to pass additional CLI arguments to the operands. One could use [strategic merge patch](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/strategic-merge-patch.md) to override the argument list generated by the operator but this is brittle and hacky since the operation replaces all items.

For most arguments (e.g. retention time, log level, ...), it is expected that arguments are exposed and managed by the CRDs but:
* It takes time to support arguments introduced by a new version of the operand.
* There's no plan to support hidden flags in the CRDs.

Based on the situation it sounds reasonable to allow users passing additional arguments with the following caveats:
1. The operator doesn't perform any version or validation check of the arguments.
2. There should be a clear message in the documentation that the feature is for advanced use cases and that it should be used carefully (e.g. passing an unsupported/broken argument means that the container will fail to start).
3. It's not possible to override an argument which is already exposed by the CRD (e.g. `spec.retention`).
4. It's not possible to override an argument which is managed already by the operator (e.g. [`--web.console.*`](https://github.com/prometheus-operator/prometheus-operator/blob/b4814089738e0b3576a81abc5b5549befba868c3/pkg/prometheus/statefulset.go#L353-L354)).

For the latter 2 points, the operator should fail the reconciliation when it happens.

Proposed API:

```
spec:
  additionalArgs:
  - '--foo'
  - '--bar'
```

For the Prometheus CRD, the Thanos sidecar should also support

```
spec:
  additionalArgs:
  - '--foo'
  - '--bar'
  thanos:
    additionalArgs:
    - '--foo'
    - '--bar'
```

**Why do we need it?**

#4850
https://github.com/prometheus-operator/prometheus-operator/discussions/4809
And probably other requests that I'm not aware of :)

**Comment by boernd** [comment]
@simonpasquier Are you already working on this? Otherwise we could contribute, see https://github.com/infonova/prometheus-operator/commit/eec58ffe90ec3ce032ee48faa94665d5be3410c1

**Comment by simonpasquier** [comment]
I'm not working on it, feel free to send a PR :)
