### ISSUE TITLE
ServiceMonitor not found

### ISSUE THREAD

**Issue by SoJoh** [prometheus-operator/prometheus-operator#4867]
Hello, 

I find our Prometheus Operator to ignore certain ServiceMonitors even though it recognizes the same configuration in other namespaces.

**Situation**

There are two namespaces each with a service and a service monitor.

v1-feat
- service/client
- servicemonitor/client-metrics

v1
- service/client
- servicemonitor/client-metrics

**Expected behavior**
Both Service Monitors should be loaded into Prometheus Configuration

**Actual behavior**
Only one of the Service Monitors is loaded into Prometheus Configuration

```v1/feat/service/client```
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: client
    meta.helm.sh/release-namespace: v1-feat
    creationTimestamp: "2022-06-24T11:26:12Z"
  labels:
    app: client
    app.kubernetes.io/managed-by: Helm
  name: client
  namespace: v1-feat
  resourceVersion: "250666086"
spec:
  clusterIP: 172.20.254.95
  ports:
  - name: http
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: client
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
```v1-feat/servicemonitor/client-metrics```
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: client
    meta.helm.sh/release-namespace: v1-feat
    creationTimestamp: "2022-06-24T11:26:12Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    release: prometheus-operator
  name: client-metrics
  namespace: v1-feat
  resourceVersion: "250666091"
  uid: efb5bebf-2832-494f-835b-00be8058fcb0
spec:
  endpoints:
  - interval: 15s
    path: /actuator/prometheus
    port: http
  jobLabel: app
  namespaceSelector:
    matchNames:
    - v1-feat
  selector:
    matchLabels:
      app: client
```
```v1/service/client```
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: client
    meta.helm.sh/release-namespace: v1
    creationTimestamp: "2022-05-17T11:33:06Z"
  labels:
    app: client
    app.kubernetes.io/managed-by: Helm
  name: client
  namespace: v1
  resourceVersion: "215861181"
  uid: 57b7c2ff-71bf-49a6-9dbc-ae5a996d985f
spec:
  clusterIP: 172.20.59.137
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: client
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
```v1/servicemonitor/client-monitor```
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: client
    meta.helm.sh/release-namespace: v1
  creationTimestamp: "2022-05-17T11:33:06Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    release: prometheus-operator
  name: client-metrics
  namespace: v1
  resourceVersion: "215861186"
  uid: c4d829d5-5454-4573-b7b8-1945d529b75d
spec:
  endpoints:
  - interval: 15s
    path: /actuator/prometheus
    port: http
  jobLabel: app
  namespaceSelector:
    matchNames:
    - v1
  selector:
    matchLabels:
      app: client
```

```kubectl -n metrics get prometheus -o yaml```
```yaml
apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    labels:
      chart: prometheus-operator-9.3.1
      heritage: Helm
      release: prometheus-operator-v1
    name: prometheus-operator-v1-prometheus
    namespace: metrics
  spec:
    alerting:
      alertmanagers: []
   [...]
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    ruleNamespaceSelector: {}
    ruleSelector: {}
    serviceAccountName: prometheus-operator-v1-prometheus
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
kind: List
```

**Operator Version** 2.18.2

**What was done already**
- Comparison of the services and servicemonitors --> They are in the same form and have same relations in regards to labels and so on
- Successful live reload of Prometheus configuration

**Prometheus Operator Logs**
No relevant logs

**Anything else we need to know?**:
- RBAC is used

**Comment by slashpai** [comment]
Version mentioned in issue seems to be that of helm chart. What version of prometheus-operator are you using?

**Comment by SoJoh** [comment]
Yeah right, this version is mentioned in the build info of Prometheus UI, but after double-checking, it actually seems like we are running **v0.38.1**.

**Comment by slashpai** [comment]
Does the prometheus service account has access to both namespaces which you are trying to monitor applications?
https://prometheus-operator.dev/docs/operator/troubleshooting/#troubleshooting-servicemonitor-changes will also help to troubleshoot better

**Comment by SoJoh** [comment]
I followed that guide already as good as I could.

This is the assigned clusterrole for the serviceaccount: 

```
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
  ```
  
  Also, the services are deployed from the same repository, same helm chart and same pipeline, only different images of the services. Therefore I could not find any differences in the namespaces in regards to RBAC or whatever.
  
 We also have the same setup for another environment on which we do not face this problems.

**Comment by marcinsztalmi** [comment]
@SoJoh Had similar issue with getting metrics from actuator. ServiceMonitror was picked up by Prometheus. I was even able to find it in configuration but still not showing in Targets and scraping metrics.
For me solution (workaround) was to provide just the path and remove interval and port so just:
```
spec:
  endpoints:
    - path: /actuator/prometheus
  selector:
    matchLabels:
      abc: xyz
```

**Comment by alaghusundhar** [comment]
I have the same issue as well . I can see the servicemonitor in the prometheus configuration and never shows up in targets and service discovery in prometheus

Configuration from Prometheus :
serviceMonitorNamespaceSelector: {}
serviceMonitorSelector: {}

Service monitor Configuration :
spec:
  endpoints:
  - interval: 30s
    path: /actuator/prometheus
    port: TCP
    scheme: http
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: springboot-hpa-app
