### ISSUE TITLE
[AlertmanagerConfig] Allow Any in alertmanagerConfigNamespaceSelector

### ISSUE THREAD

**Issue by roymartinezblanco** [prometheus-operator/prometheus-operator#4880]
**What is missing?**
Currently the alertmanagerConfig only supports a hard coded list of namespaces in the `alertmanagerConfigNamespaceSelector`. 

**Why do we need it?**
Allow/Add `any: true` similar to `ServiceMonitor`

**Comment by slashpai** [comment]
Can you provide more details what you are trying to do? :)

**Comment by roymartinezblanco** [comment]
Sure thing, let me provide more context.

Our use case is that our application teams host their applications in separate namespaces. 
`App A` will live in namespace `A`. Today alerts are created using the `alertManagerConfig` Object along with `PrometheusRule` for the alerts.

Our `alertManagerConfig` objects live in the same namespace (Monitoring) as our alert manager. The default behavior of the operator is to modify the matches of the `alertManagerConfig` and add the namespace where it lives. This creates a conflict because all routes will have the same namespaces matcher and because our applications have their own separate namespace the side effect is that they don't meet the match criteria therefore, no notification is sent.

Our workaround is to hardcode the namespace label in the `PrometheusRule` which is a little misleading since the query labels might have another namespace for when the alert reaches alert manager it will have the label it expects. I'm aware that we could also modify the Alert Manager Config and add `alertmanagerConfigNamespaceSelector` but this makes us have to maintain a list of namespaces. 

The ask/proposal is if we can modify `alertmanagerConfigNamespaceSelector` to allow `any` namespace similar to how the serviceMonitor works too to avoid the modification/Addition of the matcher.

@slashpai let me know if this provides a bit more clarity

**Comment by mpasteur** [comment]
Hi,

alertmanagerConfigNamespaceSelector can be set to {} which lead to an "any namespace" match.  

cheers
