### ISSUE TITLE
Hit Maximum secret size for alertmanager.yaml in kubernetes

### ISSUE THREAD

**Issue by timmow** [prometheus-operator/prometheus-operator#4902]
**What happened?**
When creating an alertmanager config with recievers and routes for 300 "teams" within our organisation, we hit an error with the maximum secret size similar to the error with prometheus config in [this issue](https://github.com/prometheus-operator/prometheus-operator/issues/2234).

I see the following in the logs
```
level=error ts=2022-07-07T14:09:54.349591481Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"monitoring/test\" failed: provision alertmanager configuration: create or update generated config secret failed: failed to update generated config secret: Secret \"alertmanager-test-generated\" is invalid: data: Too long: must have at most 1048576 bytes"
```

Would you be open to a similar fix to #2243 but for alertmanager.yaml if I was to raise a PR? i've done some tests and our generated config file is 1.4M, but gzipping it compresses to 28k - as the alertmanager configuration file we generate is very verbose

**Did you expect to see something different?**
I'd expect the config generation not to fail, or to reject the alertmanagerconfiguration if it is too large

**How to reproduce it (as minimally and precisely as possible)**:
Create a large alertmanagerconfig resource - ours is 1.6M - I may be able to provide a redacted version if this is useful

**Environment**

* Prometheus Operator version:

    `v0.53.1`
    
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

EKS

* Manifests:
I can provide a redacted version of our alertmanagerconfig resource if this is useful
```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
level=error ts=2022-07-07T14:09:54.349591481Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"monitoring/test\" failed: provision alertmanager configuration: create or update generated config secret failed: failed to update generated config secret: Secret \"alertmanager-test-generated\" is invalid: data: Too long: must have at most 1048576 bytes"
```

**Anything else we need to know?**:

**Comment by slashpai** [comment]
Related issue https://github.com/prometheus-operator/prometheus-operator/issues/4839
