### ISSUE TITLE
Is it possible to provision a persistent volume and persistent volume claim outside of prometheus operator scope

### ISSUE THREAD

**Issue by EvertonSA** [prometheus-operator/prometheus-operator#4922]
**What did you do?**

I'm trying to add PV storage to my prometheus instance but I need it to control persistent volume and persistent volume claims outside of prometheus-operator scope.

in the docs api, it says:

![image](https://user-images.githubusercontent.com/30481051/180152996-d19abdd9-b46e-466f-b341-a81ad17dfbc9.png)

so I assume controlling PVC outside of prometheus-operator is not an option.

is it true?

**Did you expect to see some different?**

need to control pvc and pv outside of prometheus-operator scope.

**Environment**

* Prometheus Operator version:

all

* Kubernetes version information:

na

* Kubernetes cluster kind:

na

**Comment by Iridias** [comment]
I second this request!
Although its possible to specify an existing PV (via `volumeName`) in the `volumeClaimTemplate.spec`, that's not that helpful, as every instance of the StatefulSet creates a new PVC - and the PV can bind to only one of them.

**Comment by ylallemant** [comment]
it would be an important feature for persistence !

**Comment by JoaoBraveCoding** [comment]
Not sure if it's possible but couldn't you use both `volumes` and `volumeMounts` to achieve this? By mounting your volume under `/prometheus`?

**Comment by simonpasquier** [comment]
You should be able to create the persistent volumes in advance because the names are predictable (e.g. `prometheus-<resource name>-0, `prometheus-<resource name>-1`, ...). See https://stackoverflow.com/questions/48270971/how-do-i-statically-provision-a-volume-for-a-statefulset.
