### ISSUE TITLE
Where does kubelet service and endpoints come from?

### ISSUE THREAD

**Issue by DesireWithin** [prometheus-operator/prometheus-operator#4938]
**What did you do?**

I'm learning prometheus and prometheus-operator(kube-prometheus). I deploy kube-prometheus on `cluster-1` and then deploy prometheus as statefulset on `cluster-2`.

When I trying to add kubelet as a monitoring object on `cluster-2` just as kube-prometheus did in `cluster-1`, I was surprised not to see kubelet service&endpoint in `cluster-2`.

After I deploy [setup folder](https://github.com/prometheus-operator/kube-prometheus/tree/main/manifests/setup) in `cluster-2`, kubelet service&endpoint appeared; after I delete [setup folder](https://github.com/prometheus-operator/kube-prometheus/tree/main/manifests/setup)(by `kubectl delete`), kubelet  service&endpoint have not been deleted.
 
I didn't find any kubelet definition in the folder, So I guess kubelet service&endpoint are generate by codes, right?

**Environment**

* Prometheus Operator version:

    `v0.42.1`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T12:01:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T11:52:32Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
  

* Kubernetes cluster kind:

  install by kubeadm on virual servers

* Manifests:

```
kube-prometheus: [Manifests](https://github.com/prometheus-operator/kube-prometheus/tree/main/manifests)
```

**Comment by DesireWithin** [comment]
It should be written in the code.
After I modify `--kubelet-service=kube-system/kubelet` in `prometheusOperator-deployment.yaml` to `--kubelet-service=kube-system/kubelet-my`, an `kubelete-my` endpoint(and service) appeared.

So, if I use prometheus alone instead of prometheus-operator, every time I modify kubernetes nodes(add or remove), I need modify kubelet endpoint too.

**Comment by simonpasquier** [comment]
> So, if I use prometheus alone instead of prometheus-operator, every time I modify kubernetes nodes(add or remove), I need modify kubelet endpoint too.

correct the Prometheus operator is responsible for updating the kubelet service if started with `--kubelet-service`.

**Comment by DesireWithin** [comment]
Mabybe it's out of scope of prometheus-operator, but I'm wondering is there another way to update kubelet endpoints automatically, I check the docs, [here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/) and [here](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/) , find nothing.

**Comment by simonpasquier** [comment]
I haven't heard of anything like this but if something built-in exists, the operator could use it for sure.

**Comment by ervinb** [comment]
To answer the original question in more detail, the operator maintains the `Service` and the `Endpoints`:
- the [kube-prom-kubelet Service](https://github.com/prometheus-operator/prometheus-operator/blob/712a2c1664dfe9aaf34fd216603f2953070eaf85/pkg/prometheus/server/operator.go#L656-L683) is a headless service, without any selectors, this `Endpoints` need to be managed "manually", in this case by the operator
- the [kube-prom-kubelet Endpoints](https://github.com/prometheus-operator/prometheus-operator/blob/712a2c1664dfe9aaf34fd216603f2953070eaf85/pkg/prometheus/server/operator.go#L608-L636) is fetching all the nodes from the Kubernetes API, and using their IPs to set up the endpoints

These 2 things are both defined in `syncNodeEndpoints` in the main loop, when `--kubelet-service` is [not empty](https://github.com/prometheus-operator/prometheus-operator/blob/712a2c1664dfe9aaf34fd216603f2953070eaf85/pkg/prometheus/server/operator.go#L128C1-L128C1).
