### ISSUE TITLE
Prometheus-operator listing duplicate targets for kube-scheduler

### ISSUE THREAD

**Issue by syedkalimi** [prometheus-operator/prometheus-operator#4949]
**What happened?**
i have followed the troubleshooting guide here and updated my kubelet service https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/troubleshooting.md
i am seeing that prometheus-operator is listing duplicate targets for kube-scheduler

**Did you expect to see something different?**
i would expect a single target for kube-scheduler to be listed.

**Environment**
self-managed k8s
* Prometheus Operator version: prometheus-operator:0.42.1

* Kubernetes version information: 1.23.1

**Anything else we need to know?**:

**Comment by slashpai** [comment]
Hello @syedkalimi Thank you for the report

Could you please explain a bit more about the issue and how you installed the operator?  Also the operator version used is a bit old :)
