### ISSUE TITLE
kube-prometheus-stack cannot parse YAML CRD

### ISSUE THREAD

**Issue by doryer** [prometheus-operator/prometheus-operator#4955]
**What happened?**

Trying to parse this CRD in my code with ruamel library ( Python 3.9 ) and getting parse error for this CRD: https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml#L72

I'm getting the error on lines 73/74 which is an enum that has string values that are arithmetic operators, that are not surrounded with ' sign, but as you can see in lines 72/75 they are surrounded with ' signs and it not failing on those lines.

Hoping for a fix

**Did you expect to see something different?**

All of the values surrounded with `'`

**How to reproduce it (as minimally and precisely as possible)**:

Trying to parse the YAML with ruyamel python library

**Environment**

Kubernetes, using python 3.10

* Prometheus Operator version:

  latest

* Kubernetes version information:

1.23.8

* Kubernetes cluster kind:

   kops

* Manifests:
https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml#L72

**Comment by simonpasquier** [comment]
Same issue as described in https://github.com/prometheus-operator/prometheus-operator/pull/4897. The generated YAML is valid according to the YAML spec so you need a fix in the Python library.

**Comment by PhilipGough** [comment]
Furthermore, I tried to force the generated output to quote the enum values via `// +kubebuilder:validation:Enum={"!=","=","=~","!~"}` but `make generate` does not produce a diff so there is nothing we can reasonably do here!
