### ISSUE TITLE
Azure AKS 1.21.9 to 1.22.11 - prometheus-prometheus-oper-operator is crashing with crd related errors after upgrade

### ISSUE THREAD

**Issue by zohebs341** [prometheus-operator/prometheus-operator#4992]
**What did you do?**

We have upgraded the Azure AKS cluster from 1.21.9 to 1.22.11, after that prometheus-prometheus-oper-operator pod is crashing and not coming up. If I disable crds, pod is not crashing.

But in 1.21.9, it was working fine with below parameter set to true.

Like this,  - --manage-crds=false

**Did you expect to see some different?**

Pod should be up and running without crashing.

**Environment**

Azure AKS 1.22.11

* Prometheus Operator version:

prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.38.1

* Kubernetes version information:

 Azure AKS 1.22.11

 Labels:           app=prometheus-operator-operator
                    chart=prometheus-operator-9.3.3
                    heritage=Helm
                    release=prometheus
  Service Account:  prometheus-prometheus-oper-operator
  Containers:
   prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.38.1

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here

level=info ts=2022-08-31T19:12:24.524270758Z caller=operator.go:294 component=thanosoperator msg="connection established" cluster-version=v1.22.11
level=info ts=2022-08-31T19:12:24.524287958Z caller=operator.go:452 component=prometheusoperator msg="connection established" cluster-version=v1.22.11
level=info ts=2022-08-31T19:12:24.524287558Z caller=operator.go:214 component=alertmanageroperator msg="connection established" cluster-version=v1.22.11
ts=2022-08-31T19:12:24.577567155Z caller=main.go:305 msg="Unhandled error received. Exiting..." err="creating CRD: Alertmanager: the server could not find the requested resource"


**Anything else we need to know?**:

It was working fine in AKS 1.21.9, but after the upgrade, it is crashing. In 1.22.11, a few CRD API versions have been deprecated. I am suspecting, it is something relevant to CRDs.

**Comment by slashpai** [comment]
The operator version used is a bit old. There may be issues fixed in newer versions. Can you try to use any of the latest version of operator?

**Comment by zohebs341** [comment]
@slashpai Thanks for your response.

As in values.yaml, for each component, a specific image is being used.

It would be great if you can assist with the upgrade process. Or just let me know the operator image which I should use.

Current Image tag in values.yaml:

image:
    repository: quay.io/coreos/prometheus-operator
    tag: v0.38.1

**Comment by slashpai** [comment]
I haven't worked much with helm charts. But If you are using [Prometheus community helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts%2Fkube-prometheus-stack) latest version of chart would be deploying latest version ie `0.58.0` IIUC.

**Comment by igrowheart** [comment]
Met the same issue on old prometheus operator while upgrading from eks 1.21  to 1.22. Anyone solved this?

**Comment by tfeitor** [comment]
> Met the same issue on old prometheus operator while upgrading from eks 1.21 to 1.22. Anyone solved this?

Did you find a way to solve this problem??

**Comment by simonpasquier** [comment]
The original issue is about prometheus-operator v0.38.1 which is a very old release. I'm closing this issue, feel free to reopen a new one if the problem persists with the latest operator version.

**Comment by Ozarklake** [comment]
To whom it may concern:

I encountered the same issue where my cloud provider automatically upgraded my k8s version to 1.22.x, which officially removed `apiextensions.k8s.io/v1beta1` that was used in CRD and replaced it with `apiextensions.k8s.io/v1`.

Unfortunately, the CRD definition in older versions of prometheus-operator uses this API (I'm not sure which version made the switch to `apiextensions.k8s.io/v1`).

To solve this problem:

1.  find and apply the new version of the CRD definition, which can be found in the [example/prometheus-operator-crd-full](https://github.com/prometheus-operator/prometheus-operator/tree/main/example/prometheus-operator-crd-full "prometheus-operator-crd-full") directory in this repository.
2.  upgrade the prometheus-operator version, and I recommend upgrading directly to the latest version.

If you have lost your previous maintenance files, the easiest way to upgrade prometheus-operator is to edit the deployments.apps/prometheus-operator file.

If you are using a similar version of prometheus-operator as I am (v0.37.0), then after upgrading prometheus-operator, you may encounter the following issues:

1.  The image repository address has changed from `quay.io/coreos/prometheus-operator` to `quay.io/prometheus-operator/prometheus-operator`.
2.  Some flags are no longer applicable in the new version, such as `-config-reloader-image`. If you encounter errors, simply remove them to use the default values.
3.  There will be some changes to RABC to adapt to the new version, but they can be resolved one by one based on the error messages.

Wish you success

**Comment by Neurobion** [comment]
> To whom it may concern:
> 
> I encountered the same issue where my cloud provider automatically upgraded my k8s version to 1.22.x, which officially removed `apiextensions.k8s.io/v1beta1` that was used in CRD and replaced it with `apiextensions.k8s.io/v1`.
> 
> Unfortunately, the CRD definition in older versions of prometheus-operator uses this API (I'm not sure which version made the switch to `apiextensions.k8s.io/v1`).
> 
> To solve this problem:
> 
> 1. find and apply the new version of the CRD definition, which can be found in the [example/prometheus-operator-crd-full](https://github.com/prometheus-operator/prometheus-operator/tree/main/example/prometheus-operator-crd-full) directory in this repository.
> 2. upgrade the prometheus-operator version, and I recommend upgrading directly to the latest version.
> 
> If you have lost your previous maintenance files, the easiest way to upgrade prometheus-operator is to edit the deployments.apps/prometheus-operator file.
> 
> If you are using a similar version of prometheus-operator as I am (v0.37.0), then after upgrading prometheus-operator, you may encounter the following issues:
> 
> 1. The image repository address has changed from `quay.io/coreos/prometheus-operator` to `quay.io/prometheus-operator/prometheus-operator`.
> 2. Some flags are no longer applicable in the new version, such as `-config-reloader-image`. If you encounter errors, simply remove them to use the default values.
> 3. There will be some changes to RABC to adapt to the new version, but they can be resolved one by one based on the error messages.
> 
> Wish you success

https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.39.0
[CHANGE] Switch to apiextensions.k8s.io/v1 CRD and require kubernetes v1.16 or newer (https://github.com/prometheus-operator/prometheus-operator/pull/3175, https://github.com/prometheus-operator/prometheus-operator/pull/3187)
