### ISSUE TITLE
The "GroupRule" struct is missing the "limit" field.

### ISSUE THREAD

**Issue by cuizhaoyue** [prometheus-operator/prometheus-operator#4998]
**What happened?**
I can't create a alerting rule with the "limit" field so that I can't limit the number of alerts an alerting can produce.

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `v0.59.0`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
the offical Prometheus is support the limit field in `group_rule` section.
Reference: https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#rule_group
![image](https://user-images.githubusercontent.com/34601995/188625487-0f0e2bc7-d0e5-490e-9d73-b4ca058f995c.png)

**Comment by simonpasquier** [comment]
The `limit` field is supported starting with Prometheus >= 2.31 and Thanos Ruler >= 0.24.
