### ISSUE TITLE
Concatenating labels (using empty 'separator') in relabelings not possible

### ISSUE THREAD

**Issue by mhindery** [prometheus-operator/prometheus-operator#5003]
**What happened?**

I have a ServiceMonitor with relabelings on its endpoints, and one of the relabeling configs must concatenate two labels. Its relabeling config is defined like this:

```yaml
    - sourceLabels: [label1, label2]
      separator: ""
      action: replace
      targetLabel: custom_label
```

This is exactly the same configuration as I have in a previous Prometheus setup without the prometheus operator, (having this in `prometheus.yml` instead of via a `ServiceMonitor`). This rule works in the other setup correctly and concatenates these labels.

It appears that the empty separator is not working, as it gets replaced by the default value ";". If I use any other separator in that spot, it does work with the provided value, so I'm certain the config is actually being used. Just when I use the empty string (both with single or with double quotes), the value is ignored and replaced by the default `;`.

This means it currently is not possible to concatenate two labels.

**Did you expect to see something different?**

Yes, using an empty string as separator should just concatenate the input without any separator.

**How to reproduce it (as minimally and precisely as possible)**:

Create a ServiceMonitor with endpoints contain a relabelings config, with the step I have above (of course with the labels you want to input&output).

**Environment**

* Prometheus Operator version:

    `quay.io/prometheus-operator/prometheus-operator:v0.58.0` (used via the kube-prometheus helm chart)

* Kubernetes version information:

```bash
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.11-gke.400", GitCommit:"b4e1ab06be827438def8aee0021791b413a0961d", GitTreeState:"clean", BuildDate:"2022-06-24T09:27:38Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

GKE

* Manifests: /

* Prometheus Operator Logs: /

**Anything else we need to know?**:

I know some Go, but don't know the workings of the Prometheus operator. But a quick search on `separator` in the repo shows the `RelabelConfig` struct having json tags `omitempty` (Source code: https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/apis/monitoring/v1/types.go#L1093). And an empty string is considered an empty value, so I suspect that is the culprit here; it does not allow you to intentionally provide the empty string as separator because it gets discarded as missing, and replaced by the default value later on.

**Comment by simonpasquier** [comment]
At first I thought that it was due to the latest CRD validations that were added recently but it looks like it's been the behavior forever.

https://github.com/prometheus-operator/prometheus-operator/blob/ad64869358bfc470bac56c48a1ecee6dfb8dc88c/pkg/prometheus/promcfg.go#L1481-L1483

I'm not sure exactly how we can deal with it without breaking the API guarantees :thinking: 

In the meantime, you might be able to workaround the issue with this construct?
```
    - sourceLabels: [label1, label2]
      separator: ";"
      regex: "(.*);(.*)"
      replacement: "$1$2"
      action: replace
      targetLabel: custom_label
```

**Comment by slashpai** [comment]
I was trying with

```go
	//+kubebuilder:validation:Pattern:="(.*)"
	//+kubebuilder:default=;
	Separator string `json:"separator,omitempty"`
```

But since string default is empty string, it will break the configs which doesn't specify value for separator since expected separator for those configs would be `;`
