### ISSUE TITLE
HA Cluster pushing via remote write - deduplication issue

### ISSUE THREAD

**Issue by rgarcia89** [prometheus-operator/prometheus-operator#5011]
Hi, I am currently pushing metrics via `remote_write` from a HA cluster to another. Unfortunately on the receiving prom cluster I am seeing everything double. Metrics from both replicas of the source cluster are being processed. From my understanding deduplication should be handling that by default, when deploying via the operator using the `prometheus_replica="prometheus-ap-0"`  label. Something seem to be wrong here. I am adding `cluster` and `stage` as `externalLabels` to the source cluster.
This is what I am getting back - Deduplication using the `prometheus_replica` label only isn't making a lot of sense from my point of view. Changing it to pod would work for this case. However, there are metrics that do not include a pod label. So it wouldn't work for every case. Any idea?

![image](https://user-images.githubusercontent.com/4134730/189607592-45fc71ce-d603-48ab-9089-d9c46d63f14d.png)

**Comment by slashpai** [comment]
It's working as expected. IIUC deduplication should be handled at receiver end. Do you use Thanos?

**Comment by rgarcia89** [comment]
@slashpai is that so? In that case I am wondering about the use case of the `replicaExternalLabelName` variable and also about the dedupe log entries that I see in the source prometheuses:

```
ts=2022-09-12T12:15:35.521Z caller=dedupe.go:112 component=remote level=error remote_name=43de30 url=https://prometheus-lab/api/v1/write msg="non-recoverable error" count=500 exemplarCount=0 err="server returned HTTP status 400 Bad Request: duplicate sample for timestamp"
```

**Comment by anannaya** [comment]
@rgarcia89 how did you fix the issue ?

**Comment by rgarcia89** [comment]
> @rgarcia89 how did you fix the issue ?

I have switched to Thanos as metric storage

**Comment by anannaya** [comment]
I used the below parameters
```
    externalLabels:
      dcname: "intg-us1"
      cluster: "intg-us1"
    replicaExternalLabelName: cluster
```
But the error is still not gone from promtheus pod from Source
```
ts=2023-06-15T12:59:02.054Z caller=dedupe.go:112 component=remote level=error remote_name=ddd-prometheus-0 url=https://prometheus-ai-0.staging.xxxxxx.com/api/v1/write msg="non-recoverable error" count=500 exemplarCount=0 err="server returned HTTP status 400 Bad Request: duplicate sample for timestamp"
ts=2023-06-15T12:59:02.054Z caller=dedupe.go:112 component=remote level=error remote_name=ddd-prometheus-1 url=https://prometheus-ai-1.staging.xxxxxx.com/api/v1/write msg="non-recoverable error" count=500 exemplarCount=0 err="server returned HTTP status 400 Bad Request: duplicate sample for timestamp"
ts=2023-06-15T12:59:02.068Z caller=dedupe.go:112 component=remote level=error remote_name=ddd-prometheus-2 url=https://prometheus-ai-2.staging.xxxxx.com/api/v1/write msg="non-recoverable error" count=500 exemplarCount=0 err="server returned HTTP status 400 Bad Request: duplicate sample for timestamp"
```

**Comment by rgarcia89** [comment]
Prometheus is not able to deduplicate. So you two options:
1. Scale down to 1 replica
2. Switch to Thanos as metric storage

**Comment by anannaya** [comment]
@rgarcia89  We do use thanos, But my requiremnt little weird i would like to move some of the namespace metrics  to remote prometheus cluster.

**Comment by rgarcia89** [comment]
@anannaya in that case it maybe is an option to only send the metric of one cluster server to your remote prometheus cluster. I got told during the kubecon europe that the following project is trying to fix that issue - however I haven't found time to test it so far. Maybe it is exactly what you are looking for https://github.com/jlevesy/prometheus-elector

**Comment by anannaya** [comment]
@rgarcia89  Thanks a lot.
