### ISSUE TITLE
[404] ThanosRuler in Design doc 

### ISSUE THREAD

**Issue by howieyuen** [prometheus-operator/prometheus-operator#5020]
the link of ThanosRuler section is 
https://prometheus-operator.dev/docs/operator/design/thanos.md

may be this ?
https://prometheus-operator.dev/docs/operator/thanos/

more info see here: https://prometheus-operator.dev/docs/operator/design/#thanosruler

**Comment by Sonali-Rajput** [comment]
Kindly review the PR

**Comment by Sonali-Rajput** [comment]
I have tried to fix the issue kindly review for the same 😊
