### ISSUE TITLE
Configurable TSDB OutOfOrderTimeWindow

### ISSUE THREAD

**Issue by jzelinskie** [prometheus-operator/prometheus-operator#5052]
**What is missing?**

While it hasn't been released yet, the next version of Prometheus will support configuring an out of order window for the TSDB.
Configuring this should be available in the Prometheus CR.

**Why do we need it?**

This helps immensely for clouds that silently migrate VMs and cause clock hiccups.
Without this change, a single out of order timestamp indefinitely locks up Prometheus.

**Environment**

* Prometheus Operator version: HEAD

**Anything else we need to know?**:

https://github.com/prometheus/prometheus/commit/c1b669bf9b0b1286ece53c977262089119783105
https://github.com/prometheus/prometheus/issues/11329
https://github.com/prometheus/prometheus/pull/11340

**Comment by codesome** [comment]
> Without this change, a single out of order timestamp indefinitely locks up Prometheus.

Could you please elaborate on this? How does an out-of-order sample lock up Prometheus?

**Comment by jzelinskie** [comment]
I believe the issue that I've seen manifested is caused by GCP live migrating our GKE node VMs. 
Once an inconsistent timestamp has been seen, all Prometheus scrapes fail with the behavior described in this issue: https://github.com/prometheus/prometheus/issues/8243

I believe v2.39.0 fixes this (due to the linked PRs), but it is not enabled by default, so the Prometheus Operator needs some way for folks to enable it.

Related to https://github.com/prometheus-operator/prometheus-operator/pull/5068

**Comment by simonpasquier** [comment]
Thanks for the clarification @jzelinskie. Once #5068 lands, we should be able to support for this without too much hassle.
