### ISSUE TITLE
Minikube quickstart outdated in Readme

### ISSUE THREAD

**Issue by RiRa12621** [prometheus-operator/prometheus-operator#5066]
The readme has an example how to get started with minikube and prometheus operator. This example has an outdated Kubernetes version in the command:

https://github.com/prometheus-operator/prometheus-operator/blob/fb52a0f0758ad7a9f4e9f45afdcce0b9d0569252/README.md?plain=1#L205

This leads to the following error:

```
$ minikube start --kubernetes-version=v1.10.0 --memory=4096 --extra-config=apiserver.authorization-mode=RBAC
😄  minikube v1.25.1 on Darwin 12.6 (arm64)
❗  Specified Kubernetes version 1.10.0 is less than the oldest supported version: v1.16.0
❗  You can force an unsupported Kubernetes version via the --force flag

❌  Exiting due to K8S_OLD_UNSUPPORTED: Kubernetes 1.10.0 is not supported by this release of minikube
```

**Comment by simonpasquier** [comment]
:wave: long time no see! Thanks for the report, this is a nice hacktoberfest issue :)
