### ISSUE TITLE
when using kubectl apply to deploy prometheus operator for the latest version in AKS , the prometheuses CRD was not installed, it gave an error saying the definition is too long.

### ISSUE THREAD

**Issue by divyanshurai07** [prometheus-operator/prometheus-operator#5104]
**What did you do?**

when using kubectl apply to deploy prometheus operator for the latest version in AKS , the prometheuses CRD was not installed, it gave an error saying the definition is too long.

**Did you expect to see some different?**

yes

**Environment**

AKS

* Prometheus Operator version:

    quay.io/prometheus-operator/prometheus-operator:v0.60.1
    
    

* Kubernetes version information:

   Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"4e608ea4d95b4ee29933376f99a419c7b6abfe33", GitTreeState:"clean", BuildDate:"2022-09-16T05:09:53Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

**Anything else we need to know?**:

**Comment by slashpai** [comment]
You have couple of options as fix
1. Use `kubectl create` instead of `kubectl apply`
2. Use `kubectl apply --server-side`  instead of `kubectl apply`
3. Run `make stripped-down-crds.yaml` which will generate a version of the CRDs with all description fields removed and you can use the generated file to run `kubectl apply`

**Comment by HamedAkhavan** [comment]
thanks @slashpai, `kubectl apply --server-side` worked for me

**Comment by ismail-temiz** [comment]
> You have couple of options as fix
> 
> 1. Use `kubectl create` instead of `kubectl apply`
> 2. Use `kubectl apply --server-side`  instead of `kubectl apply`
> 3. Run `make stripped-down-crds.yaml` which will generate a version of the CRDs with all description fields removed and you can use the generated file to run `kubectl apply`

I was having an issue with just one of the CRDs so for me running `make stripped-down-crds.yaml` and then grabbing the shortened vers of the CRD worked.
