### ISSUE TITLE
Failed to render chart: exit status 1: Error: parse error at (prometheus-operator/templates/prometheus-rules/postgres.yaml:22): function "query" not defined

### ISSUE THREAD

**Issue by vasuenduri** [prometheus-operator/prometheus-operator#5121]
**functions not working in prometheus alerts**

rules:
        - alert: VolumeOutOfSpace
          expr: 1 / kubelet_volume_stats_capacity_bytes * kubelet_volume_stats_used_bytes > .75
          for: 3m
          labels:
            environment: staging
            severity: warning
            type: "system"
          annotations:
            unit: percentage
            summary: "volume almost out of space"
            timestamp: '{{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}'
            value: "{{" {{ $value }} "}}"
            description: "More than 75% of the volume is filled"

Can anyone help me in validating the above code. 

**how to use prometheus functions in alerts?**

**Comment by simonpasquier** [comment]
`Failed to render chart` indicates that you deploy using Helm so you need to ask the question to the chart maintainers.

**Comment by simonpasquier** [comment]
to be more precise, you need to escape the `{{` and `}}`:

```
timestamp: '{{ "{{" }} with query "time()" {{ "}}{{" }} . | first | value | humanizeTimestamp {{ "}}{{" }} end {{ "}}" }}'
```

**Comment by vasuenduri** [comment]
thanks @simonpasquier , it's working.
