### ISSUE TITLE
Manual storage for 2nd replica in pending state

### ISSUE THREAD

**Issue by neha-kapila94** [prometheus-operator/prometheus-operator#5123]
Installed prometheus operator release-0.11 following guide
**https://github.com/prometheus-operator/kube-prometheus** 

To achieve HA we have set the Prometheus instance replicas as 2 along with manual storage following the guilde:
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md

Provisioning the first replica's PVC is bound successfully to PV but the second one is still in a pending state, to my understanding this is  because relation for PV and PVC is always 1:1, 2 PVCs cannot be bound to 1 PV.

Could you please suggest how to go about this?

**Comment by simonpasquier** [comment]
This could be a scheduling issue, you should probably look at the Kubernetes events.
