### ISSUE TITLE
Missing flow chart in documentation troubleshooting.md

### ISSUE THREAD

**Issue by beingnishas** [prometheus-operator/prometheus-operator#5128]
**What did you do?**
Referred documentation to troubleshoot https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/troubleshooting.md which has a missing flow diagram redirected to https://github.com/prometheus-operator/prometheus-operator/blob/main/img/custom-metrics-elements.png

**Did you expect to see some different?**
Yes 
**Environment**

* Prometheus Operator version:
github markdown page
 
* Kubernetes version information:
NA
* Kubernetes cluster kind:
NA
    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

NA

* Prometheus Operator Logs:

NA

**Anything else we need to know?**:

**Comment by slashpai** [comment]
@beingnishas  The image link is put in markdown in a way that it displays correctly in https://prometheus-operator.dev. Its correctly displayed in It will be displayed correctly in https://prometheus-operator.dev/docs/operator/troubleshooting

**Comment by beingnishas** [comment]
I see thank you for such a quick update! :)
