### ISSUE TITLE
Missing "description" filed in  AlertmanagerConfig / pagerdutyConfigs when using stripped-down-crds.yaml  CRDs

### ISSUE THREAD

**Issue by gites** [prometheus-operator/prometheus-operator#5129]
**What happened?**
After upgrading CRDs to v0.60.1 using stripped-down-crds.yaml  AlertmanagerConfig validation is failing:
```
 error validating data: ValidationError(AlertmanagerConfig.spec.receivers[1].pagerdutyConfigs[0]): unknown field "description" in com.coreos.monitoring.v1alpha1.AlertmanagerConfig.spec.receivers.pagerdutyConfigs;
```

**Did you expect to see something different?**
AlertmanagerConfig validation should  pass

**How to reproduce it (as minimally and precisely as possible)**:
1. Use v0.60.1 and `stripped-down-crds.yaml` for creating CRDs in cluster  
2. Define `AlertmanagerConfig/v1alpha1` with `receivers.pagerdutyConfigs` and custom alert description

**Environment**

* Prometheus Operator version:

    `v0.60.1 `
    
    

* Kubernetes version information:
* 
    `v1.21.14-eks-6d3986b`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

Looks like striping the `stripped-down-crds.yaml` file form keys descriptions also removed a `pagerdutyConfigs` CRD key named "description". After adding missing key to CRD definition I was able to use my AlertmanagerConfigs.

```
                          component:
                            type: string
  +                      description:
  +                        type: string
                          details:
                            items:
```

**Comment by slashpai** [comment]
Thanks for the report!
Would you like to contribute for the fix? stripped-down-crds.yaml is generated using [make command](https://github.com/prometheus-operator/prometheus-operator/blob/main/Makefile#L233-L235). The `for` loop condition need to be updated.

**Comment by slashpai** [comment]
This will be case for all types having `description` as field name

I see `OpsGenieConfig` has a field named `description` as well

**Comment by simonpasquier** [comment]
Ah, indeed the generation of stripped-down-crds.yaml is crude: it strips the `description` keys from all objects, not looking at the context. Not sure if we can fix it easily with more `jq` "magic".

https://github.com/prometheus-operator/prometheus-operator/blob/01a2744de896778eb78958835dffe77d30280d78/Makefile#L235

**Comment by sthaha** [comment]
@slashpai, I am happy to work on this if no else one is working on it

**Comment by slashpai** [comment]
@sthaha This may be interesting to you :)
