### ISSUE TITLE
Support _param_target based sharding for Probes

### ISSUE THREAD

**Issue by soasme** [prometheus-operator/prometheus-operator#5176]
**What is missing?**
The current prometheus-operator does not support sharding static config targets defined in a single Probe, because "sharding is done on the contents of the `__address__` target meta-label." but the `__address__` label is set to the Prober.URL, rather than Targets.StaticConfig.Static[*].

**Why do we need it?**
Enable more even distribution of all targets defined in a Probe.

**Environment**

* Prometheus Operator version:

    `0.60.1`
    
    

**Anything else we need to know?**:
Proposed code change: [source promcfg.go L1060-L1063](https://github.com/prometheus-operator/prometheus-operator/blob/v0.60.1/pkg/prometheus/promcfg.go#L1060-L1063), (not tested though):

```diff
func (cg *ConfigGenerator) generateProbeConfig(
	m *v1.Probe,
	apiserverConfig *v1.APIServerConfig,
	store *assets.Store,
	shards int32,
) yaml.MapSlice {
                 ...
		// Add configured relabelings.
		xc := labeler.GetRelabelingConfigs(m.TypeMeta, m.ObjectMeta, m.Spec.Targets.StaticConfig.RelabelConfigs)
		relabelings = append(relabelings, generateRelabelConfig(xc)...)
+               relabelings = generateAddressShardingRelabelingRulesForProbes(relabelings, shards)    
		cfg = append(cfg, yaml.MapItem{Key: "relabel_configs", Value: relabelings})
   
```

It seems such a code change sets hashmod and modulus for `_param_target`, rather than `__address__`.

**Comment by steven05jiang** [comment]
@simonpasquier please review the [fix](https://github.com/prometheus-operator/prometheus-operator/pull/5735). thanks!
