### ISSUE TITLE
Reject invalid PrometheusRule objects beforehand rather than failing the reconciliation

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#5191]
**What is missing?**

When the Thanos/Prometheus controllers detect an invalid PrometheusRule object (invalid PromQL expression for instance), they fail the reconciliation (and for Prometheus, the `Reconciled`  condition will be set to False). Instead the controllers should reject the invalid object and proceed (just like we do for service/pod monitors and probes).

**Why do we need it?**

In self-service environments, blocking the reconciliation means that one single user can block all other users if they push a bad rule.

**Environment**

* Prometheus Operator version: N/A

**Anything else we need to know?**:

Probably a good time to refactor the code handling the rules which is duplicated between pkg/prometheus and pkg/thanos.

**Comment by 1it** [comment]
Erm… Sorry, this is a [four years old problem](https://github.com/prometheus-operator/prometheus-operator/pull/1871), already. And still not going to be solved?

**Comment by simonpasquier** [comment]
@1it you missed #5221 which is going to fix it :)

**Comment by 1it** [comment]
Ah, OK. Thanks! I was about to start fixing this myself. 😅
