### ISSUE TITLE
Remote Read does not work for Thanos

### ISSUE THREAD

**Issue by nmtl99892010** [prometheus-operator/prometheus-operator#5200]
**What did you do?**
Hi,
I'm, trying to configure Prometheus remote read from Thanos, I used https://{thanos-query}/api/v1/query as the RUL, but it does not work in Prometheus. Logs shows nothing about remote read and the data can not read from Thanos, I'm not sure if missing something or setting a wrong configuration.
Actually , I also configured a remote write to thanos-receive and it works fine.
Now,   https://{thanos-query}/api/v1/query can be archived via post man with basic auth.
My question would be:
How to configure remote read to read the data from Thanos?

**Did you expect to see some different?**
In grafana, when using prometheus as a data source, you can query the data in remote thanos
**Environment**
Thanos 10.5.2 

chart: kube-prometheus-stack
version: 41.5.0

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
Configuration in Prometheus-operator configmap:

        "remoteRead":
        - "basicAuth":
            "password":
              "key": "remote-write-passwd"
              "name": "prometheus-remotewrite-secret"
            "username":
              "key": "remote-write-user"
              "name": "prometheus-remotewrite-secret"
          "url": "https://{thanos-query}/api/v1/query"
        "remoteWrite":
        - "basicAuth":
            "password":
              "key": "remote-write-passwd"
              "name": "prometheus-remotewrite-secret"
            "username":
              "key": "remote-write-user"
              "name": "prometheus-remotewrite-secret"
          "headers":
            "THANOS-TENANT": "xxx-xxx-xxxx"
          "url": "https://{thanos-receive}/api/v1/receive"
          "writeRelabelConfigs":
          - "action": "drop"
            "regex": "thanos_workaround_to_keep_all_metrics"
            "sourceLabels":
            - "namespace"

**Comment by simonpasquier** [comment]
I'm pretty sure that `/api/v1/query` isn't a valid remote-read endpoint. I'd expect that you configure the Grafana datasource with the Thanos query endpoint.

**Comment by nmtl99892010** [comment]
Thanks for your reply @simonpasquier , is it the only way to integrate with Thanos-remote-read feature(https://github.com/G-Research/thanos-remote-read) for the remote read from Prometheus?

**Comment by bwplotka** [comment]
This feature indeed require Store API being exposed on Thanos Querier managed by Prometheus Operator. I think it's fair feature request to expose it if it's not exposed yet (gRPC port).

**Comment by bwplotka** [comment]
Nice. I think then it's misconfiguration on @nmtl99892010 side.

First of all, using Prometheus Operator Prometheus to remote read from Thanos using https://thanos.io/tip/thanos/integrations.md/#storeapi-as-prometheus-remote-read sounds odd. You have the same APIs if you use Thanos Querier from Prometheus Operator. This Thanos Querier can be easily connected to Prometheus AND other Thanos components you might have (connected to Store API gRPC endpoint, NOT query HTTP).

**The advantage** of using Thanos Querier is that the fanout mechanism that joins data from multiple services is much faster and more efficient. Similarly, you can enable the new PromQL engine, which is 2-4x faster.

However, if you really insist on using https://thanos.io/tip/thanos/integrations.md/#storeapi-as-prometheus-remote-read and Prometheus as your point of view (your root PromQL engine and UI), you need to:

* Configure [Thanos-remote-read solution](https://thanos.io/tip/thanos/integrations.md/#storeapi-as-prometheus-remote-read) to talk to gRPC ports for Querier and Receiver (from your examples)
* Configure Prometheus to remote read from  [Thanos-remote-read](https://thanos.io/tip/thanos/integrations.md/#storeapi-as-prometheus-remote-read)

**Comment by nmtl99892010** [comment]
Hi @bwplotka , thanks for your reply and nice to hear that. Actually I'd rather to use Thanos Querier instead of Thanos-remote-read. I want to confirm which remote-write API URL should I configure for in Prometheus? Would you like to give an example.
Now I use https://{thanos-query}/api/v1/query and the {thanos-query} is thanos-query domain + http port
PS: Actually I use nginx to expose the thanos query API to the internet with basic auth.
Thanks !

**Comment by nmtl99892010** [comment]
Hi @bwplotka ,  how to understand "connected to Store API gRPC endpoint, NOT query HTTP", does that mean, I need to configure prometheus remote read endpoint directly to Store API gRPC endpoint, but not the query HTTP? Thanos

**Comment by nmtl99892010** [comment]
dose it mean if I want to use remote read in Prometheus, I must use thanos-remote-read as the endpoint?
Would you like to give an example for URL configuration in promethes remote write ? Maybe it's more clear for me. thanks
