### ISSUE TITLE
additionalAlertManagerConfigs option is not working 

### ISSUE THREAD

**Issue by ravindraprasad85** [prometheus-operator/prometheus-operator#5212]
**What happened?**
Alerts are not getting triggered to external endpoint
**Did you expect to see something different?**
Alert should trigger to external endpoint 
**How to reproduce it (as minimally and precisely as possible)**:

**Environment**
PROD/UAT/TEST
* Prometheus Operator version:
v0.58.0
    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1`
    

* Kubernetes cluster kind:
AWS EKS
    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
No issue in logs
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
Please provide more details about your environment: Prometheus & Alertmanager custom resources, logs, ...

**Comment by ravindraprasad85** [comment]
I have tried below two options in values.yaml (kube-prometheus-stack) which
is not working at all.
I need to send the alert from my prometheus to the external alertmanager.
My internal "alertmanager-kube-prometheus-stack-alertmanager-0" is disabled
as we need to send alerts to external alertmanager.
i have attached snaps where there is no Alertmanager endpoint

Method-1

  additionalAlertManagerConfigs:
      - static_configs:
        - targets: ["pmaas-db.xvz.mydomain.biz"]
        scheme: http
        server: pmaas-db.xvz.mydomain.biz:80

Method-2
    alertingEndpoints: []
       - name: "pmaas-db.xvz.mydomain.biz"
         namespace: ""
         port: http
         scheme: http
         pathPrefix: "/am0tid-cstcs-ccid-prod/api/prom/alertmanager"
         # static_configs:          #this is not supporting
         # - targets:
         #   - pmaas-db.xvz.mydomain.biz
         tlsConfig: {}
         bearerTokenFile: ""
         apiVersion: v2
         timeout: 10s

Thanks
Ravindra Prasad
7827979144

**Comment by ravindraprasad85** [comment]
upgrade.go:142: [debug] preparing upgrade for kube-prometheus-stack
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Prometheus.spec.alerting.alertmanagers[0]): unknown field "static_configs" in com.coreos.monitoring.v1.Prometheus.spec.alerting.alertmanagers, ValidationError(Prometheus.spec.alerting.alertmanagers[1]): unknown field "static_configs" in com.coreos.monitoring.v1.Prometheus.spec.alerting.alertmanagers, ValidationError(Prometheus.spec.alerting.alertmanagers[2]): unknown field "static_configs" in com.coreos.monitoring.v1.Prometheus.spec.alerting.alertmanagers]
helm.go:84: [debug] error validating "": error validating data: [ValidationError(Prometheus.spec.alerting.alertmanagers[0]): unknown field "static_configs" in com.coreos.monitoring.v1.Prometheus.spec.alerting.alertmanagers, ValidationError(Prometheus.spec.alerting.alertmanagers[1]): unknown field "static_configs" in com.coreos.monitoring.v1.Prometheus.spec.alerting.alertmanagers, ValidationError(Prometheus.spec.alerting.alertmanagers[2]): unknown field "static_configs" in com.coreos.monitoring.v1.Prometheus.spec.alerting.alertmanagers]

**Comment by ravindraprasad85** [comment]
Means, there is no possibility to add external alertmanager endpoint in Prometheus helm chart (values.yaml) ? How can i get this achieved ?

**Comment by simonpasquier** [comment]
Again the people in this project don't maintain the Helm charts, your need to ask to the helm-charts project.
