### ISSUE TITLE
Reduce the number of versions in the end-to-end migration tests 

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#5213]
I've checked on a recent CI run and [testPromVersionMigration](https://github.com/prometheus-operator/prometheus-operator/blob/1dfecab7c2706f3591d6bb6d5eb8f6b2518f1b45/test/e2e/prometheus_test.go#L824) takes more than 1500 seconds to complete. The reason is that the test starts from Prometheus v2.0.0 and deploys every Prometheus version up to the latest supported (v.2.40.5 today). Over time, the duration of the test can only increase up to the point where it will hit the global timeout. IMHO testing very old versions of Prometheus isn't terribly useful: nobody should be running a v2.0.0 Prometheus anymore and we should trim down the list of versions.

I suggest that we start the migration test from the before last [Prometheus TLS release](https://prometheus.io/docs/introduction/release-cycle/) up to the latest stable (right now there's only one TLS, v2.37 but as soon as the next LTS is out, it would be all versions >= v2.37.0). WDYT @PhilipGough @paulfantom?

**Comment by PhilipGough** [comment]
@simonpasquier yeah, that makes total sense to me. We should provide some sensible boundaries and i like your suggestion .

**Comment by xiu** [comment]
I got hit by these long CI steps and pushed #5302
