### ISSUE TITLE
The operator should check that the Thanos sidecar's version supports the `--prometheus.http-client` flag

### ISSUE THREAD

**Issue by kssanthosh** [prometheus-operator/prometheus-operator#5223]
**What happened?**
When applying the manifest after generating from thanos sidecar.sonnet

error parsing commandline arguments: [/bin/thanos sidecar --prometheus.url=http://localhost:9090/ --prometheus.http-client={"tls_config": {"insecure_skip_verify":true}} --grpc-address=:10901 --http-address=:10902 --objstore.config=type: s3
config:
  bucket: prometheus-data
  endpoint: s3.us-east-5.amazonaws.com
  access_key: xxxxx
  secret_key: xxxx--tsdb.path=/prometheus]: unknown long flag '--prometheus.http-client'
thanos: error: unknown long flag '--prometheus.http-client'

**Did you expect to see some different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**
Kops 1.25

* Prometheus Operator version:

    `v0.61.1`
    

* Kubernetes version information:

    `Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0"`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Insert Prometheus Operator logs relevant to the issue here
```

* Prometheus Logs:

```
Insert Prometheus logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by mouad-eh** [comment]
I will work on this

**Comment by MateSousa** [comment]
hey @mouad-eh , are you working on this??

**Comment by mouad-eh** [comment]
@MateSousa
Unfortunately, I didn't have time to work on it. Maybe I can take a look at it in the weekend.
If you are intrested you can go head and work on it. You don't need to ask for assignement from the maintainers, just showing interest is enough.

**Comment by MateSousa** [comment]
@mouad-eh thanks, I will work on this issue.
