### ISSUE TITLE
Missing Metrics in Prometheus on openshift 3.11

### ISSUE THREAD

**Issue by vijayibm** [prometheus-operator/prometheus-operator#5225]
**What happened?**

Hello Team,

We are running RedHat Openshift  3.11 in our both (Staging and production) environment.
Suddenly Our Grafana tool stop showing visual of node's data. Exp CPU utilization, Memory Utilization and swap etc.
While Investigation we found queries (node:node_cpu_utilisation:avg1m) is not showing data. But similar queries is working in Staging environment. Following are output of queries executed in both environment.

### Working

[user1@ocp-st-serverA ~]$ oc exec prometheus-k8s-0 -c prometheus -- curl 127.0.0.1:9090/api/v1/query?query=node:node_cpu_utilisation:avg1m | jq  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                 Dload  Upload   Total   Spent    Left  Speed100   926  100   926    0     0   398k      0 --:--:-- --:--:-- --:--:--  904k
{  "status": "success",  "data": {    "resultType": "vector",    "result": [      {        "metric": {          "__name__": "node:node_cpu_utilisation:avg1m",          "node": "compute1"        },        "value": [          1671016052.655,          "0.047625000001668694"        ]      },      {        "metric": {          "__name__": "node:node_cpu_utilisation:avg1m",          "node": "compute2"        },        "value": [          1671016052.655,          "0.04054166666658898"        ]      },      {        "metric": {          "__name__": "node:node_cpu_utilisation:avg1m",          "node": "compute3"        },        "value": [          1671016052.655,          "0.06375000000116415"        ]      },      {        "metric": {          "__name__": "node:node_cpu_utilisation:avg1m",          "node": "master1"        },        "value": [          1671016052.655,          "0.07262499999972838"        ]      },      {        "metric": {          "__name__": "node:node_cpu_utilisation:avg1m",          "node": "master2"        },        "value": [          1671016052.655,          "0.1156250000019402"        ]      },      {        "metric": {          "__name__": "node:node_cpu_utilisation:avg1m",          "node": "master3"        },        "value": [          1671016052.655,          "0.04591666666383376"        ]      }    ]  }
}
### Not Working

[user1@ocp-pr-serverA ~]$ oc exec prometheus-k8s-0 -c prometheus -- curl 127.0.0.1:9090/api/v1/query?query=node:node_cpu_utilisation:avg1m | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    63  100    63    0     0  33210      0 --:--:-- --:--:-- --:--:-- 63000
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": []
  }
}

##### =====================================================================

**Did you expect to see something different?**

Queries must provide output as like Staging.

**Environment**

Production 

Could you please help us to understand the issue and suggest/guide us how to fix it?

**Comment by JoaoBraveCoding** [comment]
I'm not a maintainer of this project, but I don't think this bug should be addressed here.

Nevertheless, it seems your Prometheus stopped being able to scrape node-exporter, that's why the metric is absent. But I might be missing something.
