### ISSUE TITLE
Ability to skip invalid prometheusrules CR

### ISSUE THREAD

**Issue by alexsuraykin** [prometheus-operator/prometheus-operator#5232]
**What is missing?**

Hi everyone

We have faced with next issue - if one CR prometheusrules has issues (for example syntax error) the operator gets stuck on this step and doesn't apply other rules and configurations. 

```log
level=error ts=2022-12-02T09:47:37.571305993Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"apps-monitoring/k8s\" failed: Invalid rule"
level=info ts=2022-12-02T09:47:57.369180929Z caller=operator.go:280 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2022-12-02T09:47:57.369546867Z caller=operator.go:741 component=alertmanageroperator key=apps-monitoring/k8s msg="sync alertmanager"
level=info ts=2022-12-02T09:47:57.581637373Z caller=operator.go:741 component=alertmanageroperator key=apps-monitoring/k8s msg="sync alertmanager"
level=info ts=2022-12-02T09:47:58.052120729Z caller=operator.go:1228 component=prometheusoperator key=apps-monitoring/k8s msg="sync prometheus"
level=info ts=2022-12-02T09:47:58.055475534Z caller=rules.go:328 component=prometheusoperator msg="Invalid rule" err="32:11: group \"m-alerts\", rule 4, \"CronJobFailed\": could not parse expression: 9:1: parse error: unclosed left parenthesis"
```

If i don't mistake invalid servicemonitors and podmonitors may be skipped by operator.

**Why do we need it?**

It would be nice if correct part of configuration will be applied by operator and invalid config will be noticed in the log. 

**Environment**

* Prometheus Operator version:

Prometheus-operator tag - v0.61.1

**Comment by simonpasquier** [comment]
:wave: I guess that it's the same issue as https://github.com/prometheus-operator/prometheus-operator/issues/5191?

**Comment by slashpai** [comment]
This is fixed in https://github.com/prometheus-operator/prometheus-operator/issues/5191
