### ISSUE TITLE
Missing AlertManagerConfig in the Operator's API reference page

### ISSUE THREAD

**Issue by plaes** [prometheus-operator/prometheus-operator#5247]
Reference to AlertManagerConfig API is missing from https://prometheus-operator.dev/docs/operator/api/ page.

**Comment by simonpasquier** [comment]
Are you looking for https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com%2fv1alpha1 & https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com%2fv1beta1?

**Comment by plaes** [comment]
> Are you looking for https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com%2fv1alpha1 & https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com%2fv1beta1?

Indeed, my mistake, but it's also quite confusing.

Maybe it makes sense to list all the APIs in top, and behind each API list the versions that are supported. For example:
* AlertManager (v1, v1beta, v1alpha)
* AlertManagerConfiguration (v1beta, v1alpha)
* ...

**Comment by simonpasquier** [comment]
feel free to have a look at https://github.com/prometheus-operator/prometheus-operator/tree/main/scripts/docs/templates which is where the templates are defined. I'm not sure that the [gen-crd-api-reference-docs](https://github.com/ahmetb/gen-crd-api-reference-docs) tool support this organization.
