### ISSUE TITLE
How to set google OAuth2 authentication in kube-prometheus helm chart

### ISSUE THREAD

**Issue by rfuelsh** [prometheus-operator/prometheus-operator#5250]
I am trying to follow https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/google/

to setup the google OAuth2 authentication in kube-prometheus helm chart via grafana.ini

[auth.google]
enabled = true
client_id = CLIENT_ID
client_secret = CLIENT_SECRET
scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
auth_url = https://accounts.google.com/o/oauth2/auth
token_url = https://accounts.google.com/o/oauth2/token
allowed_domains = mycompany.com mycompany.org
allow_sign_up = true

I am unable to find where to configure these above values in kube-prometheus helm chart values.yaml 

Please let me know how I can configure these via values.yaml or something else

Thanks!

**Comment by slashpai** [comment]
Since its helm chart related you should log issue at https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

**Comment by rfuelsh** [comment]
hi @slashpai - I appreciate
