### ISSUE TITLE
misleading log for alertmanagerConfig

### ISSUE THREAD

**Issue by haoyuan0** [prometheus-operator/prometheus-operator#5253]
**What happened?**
I was set the alertmanagerconfig CR for the k8s cluster, and misleading by this log.
https://github.com/prometheus-operator/prometheus-operator/blob/bbd7400711a99eda6c140c31e17f770355617b66/pkg/alertmanager/amcfg.go#L1683-L1686
1. The r.match wouldn't be empty if "matchType" not set in alertmanagerconfig CR like this.
```
matchers:
  - name: key1
    value: value1
```
2. The log for r.Match and r.MatchRE is not string type, will lead to "unsupported value type"
The log will be like this
```
level=warn ts=2022-12-27T06:28:50.879469406Z caller=amcfg.go:1685 component=alertmanageroperator alertmanager=prometheus-kube-prometheus-alertmanager namespace=prometheus receiver=prometheus/liuer-alert-webhook-test/webhook msg="'matchers' field is using a deprecated syntax which will be removed in future versions" match="unsupported value type" match_re="unsupported value type"
```

* Prometheus Operator version:
v0.61.1

**Comment by simonpasquier** [comment]
For 1, you can modify your definition to:

matchers:
  - name: key1
    value: value1
    matchType: "="

With AlertmanagerConfig v1beta1, `matchType` is a required field.

For 2, this is a bug indeed.
