### ISSUE TITLE
  How to close the alert of prometheus?

### ISSUE THREAD

**Issue by Hello-Linux** [prometheus-operator/prometheus-operator#5255]
**What did you do?**

### I use the thanos ruler service to send alert information to the alertmanager, but prometheus-operator itself is also sending alarm information to the alertmanager. How do I turn off the alert of prometheus itself?
I didn't find the off switch in the configuration
![000](https://user-images.githubusercontent.com/17851645/210060120-1ff3a2dc-2406-446d-8c7e-99a936bbccc0.png)

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
IIUC you're saying that Alertmanager receives the same alert from both Prometheus & Thanos Ruler? This is the case if you use the same PrometheusRule selectors for both. Can you share the Prometheus and ThanosRuler manifests?

**Comment by Hello-Linux** [comment]
@simonpasquier  I mean how to turn off the alertmanager alarm for prometheus-operator

**Comment by JoaoBraveCoding** [comment]
AFAIK the operator itself does not create any PrometheusRule that contains that alert. So it must come bundled together with other alerts in a PrometheusRule that you have deployed in your cluster.

If you are using kube-prometheus, that alert comes from prometheus/prometheus itself https://github.com/prometheus/prometheus/blob/dfd2b5340e38255cefc4f426398fb63032c83229/documentation/prometheus-mixin/alerts.libsonnet#L64-L77

**Comment by JoaoBraveCoding** [comment]
Are we able to close this @Hello-Linux?
