### ISSUE TITLE
Probe CRD: Support all available Prometheus SD variants 

### ISSUE THREAD

**Issue by jkroepke** [prometheus-operator/prometheus-operator#5269]
**What is missing?**

Looking at the Probe CRD, only `staticConfig` is supported in addition to the special ingress integration.

```
$ k explain probe.spec.targets
KIND:     Probe
VERSION:  monitoring.coreos.com/v1

RESOURCE: targets <Object>

DESCRIPTION:
     Targets defines a set of static or dynamically discovered targets to probe.

FIELDS:
   ingress	<Object>
     ingress defines the Ingress objects to probe and the relabeling
     configuration. If `staticConfig` is also defined, `staticConfig` takes
     precedence.

   staticConfig	<Object>
     staticConfig defines the static list of targets to probe and the relabeling
     configuration. If `ingress` is also defined, `staticConfig` takes
     precedence. More info:
     https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config.
```

**Why do we need it?**

I would like to use Probes to observe external systems living in Azure. If possible I would like to use the [azure_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#azure_sd_config) to monitor companion systems.

**Environment**

* Prometheus Operator version: v0.61.1

    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**: You do a great job, thanks for all your great work!

**Comment by simonpasquier** [comment]
I believe that your use case would be covered by https://github.com/prometheus-operator/prometheus-operator/issues/2787. We had one contributor that showed interest in moving this forward.

>  You do a great job, thanks for all your great work!

:bowing_man:

**Comment by jkroepke** [comment]
Thats true, thanks for the hint.

**Comment by jkroepke** [comment]
Seems to be part of 0.65
