### ISSUE TITLE
Documentation about volume expansion may trigger a recreation of the statefulset

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#5289]
> https://prometheus-operator.dev/docs/operator/storage/#resizing-volumes.
> First, update the storage request in the spec.storage field of the custom resource (assuming a Prometheus resource named example):

I tested it according to this document, and it seems that the statefulset is recrated in step 1.

> The operator should recreate the StatefulSet immediately, there will be no service disruption thanks to the orphan strategy and the volumes mounted in the Pods should have the updated size.

Doesn't this mean there's no restart of pods and no downtimes?

In order to do this without service disruption, it seems that we need to make replicas of the prometheus operator to zero because of blocking the recreation of the statefulset.

_Originally posted by @parkjeongryul in https://github.com/prometheus-operator/prometheus-operator/issues/4079#issuecomment-1396465595_

**Comment by simonpasquier** [comment]
Following comment from @parkjeongryul

```
Sure. Belows are our storage class and it supports volume expansion.

$ k get  storageclass rbd-ssd -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: rbd
    meta.helm.sh/release-namespace: kube-system
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2022-12-05T04:16:48Z"
  labels:
    app: rbd
    app.kubernetes.io/managed-by: Helm
    chart: rbd-v1
    heritage: Helm
    release: rbd
  name: rbd-ssd
  resourceVersion: "60047"
  uid: 224e347d-2908-4101-8e8f-00aaf44328ac
parameters:
  cephLogDir: /var/log/ceph
  clusterID: 96f95cff-c001-4a8f-87f0-fe5494b13c13
  csi.storage.k8s.io/controller-expand-secret-name: nv-rbd-ssd
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  csi.storage.k8s.io/fstype: xfs
  csi.storage.k8s.io/node-stage-secret-name: nv-rbd-ssd
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: nv-rbd-ssd
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  imageFeatures: layering
  pool: pgclsr1-rbd-ssd-rep
  thickProvision: "false"
provisioner: rbd.csi.navercorp.com
reclaimPolicy: Delete
volumeBindingMode: Immediate

I think the action of creating a new statefulset (when Prometheus CRD spec is modifed) is related to the logic of the prometheus operator.
```

**Comment by simonpasquier** [comment]
> I think the action of creating a new statefulset (when Prometheus CRD spec is modifed) is related to the logic of the prometheus operator.

When I tested the procedure, it didn't trigger a statefulset recreation but I'll check again. It would help if you can share the prometheus operator's and Kubernetes versions.

**Comment by parkjeongryul** [comment]
I used this prometheus operator image.

```yaml
  image:
    repository: quay.io/prometheus-operator/prometheus-operator
    tag: v0.60.1
    sha: ""
    pullPolicy: IfNotPresent
```

And my kubernetes cluster version is 1.23.

***

FYI. there is a article which is similar to our circumstance.
https://itnext.io/resizing-statefulset-persistent-volumes-with-zero-downtime-916ebc65b1d4

this article also says that make prometheus operator stop to block the recreation of statefulset.
> Scale Prometheus Operator (or any Operator that manages your StatefulSet) deployment to zero replicas: this means you can modify the Prometheus Object without any kind of reconciliation. Skip this step if your StatefulSet is not managed by an [Operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/).

**Comment by parkjeongryul** [comment]
I read the prometheus operator code. This part seems to be the logic of recreating statefulset.

https://github.com/prometheus-operator/prometheus-operator/blob/c0dfef0dc03784c0d16c8aaccd89100ac0115314/pkg/prometheus/operator.go#L1256-L1277


1. Maybe request of updating volumeClaimTemplate spec in statefulset was failed. (It is not supported at kubernetes level.)
2. And prometheus operator delete original statefulset.
3. Next sync period, Operator create new statefulset.

Did I analyze the problem correctly?

**Comment by parkjeongryul** [comment]
> Did I analyze the problem correctly?

If this is right, I have two questions.
1. What behavior does the prometheus operator intend? Which should be fixed, document or code?
2. Is there anything I can fix by creating PR? It would be nice if there was something I could contribute to.

**Comment by simonpasquier** [comment]
can you try setting `spec.paused: true` before? It should prevent the operator from recreating the statefulset.

**Comment by parkjeongryul** [comment]
I think it works well if i set paused to true.
Actually, It seems the same as preventing the operator from recreating.

If this is the intended manual for resizing when using the prometheus operator, it looks good to be added to the document.

**Comment by simonpasquier** [comment]
> If this is the intended manual for resizing pvc when using the prometheus operator, it looks good to be added to the document.

Yes. If you're ok with a short downtime then you can avoid setting `spec.paused: true` but I agree that the documentation should provide instructions that incur zero downtime. Do you want to give it a try and submit a PR?

**Comment by parkjeongryul** [comment]
Ok, I will do it.
