### ISSUE TITLE
livenessProbe override: change type of probe

### ISSUE THREAD

**Issue by hervenicol** [prometheus-operator/prometheus-operator#5294]
**What did you do?**

I'd like to have my custom liveness probe, based on a script, doing additional checks.
So I tried to override the `livenessProbe`, replacing it with  a `exec` probe instead of a `httpGet`, by updating my `prometheus` resource:

```
spec:
  containers:
  - livenessProbe:
    exec:
      command:
      - sh
      - /myscript.sh
```

It patched the statefulset as expected, but the merge resulted in having both `httpGet` and `exec`:
```
$ ks get sts prometheus-prometheus-agent -oyaml | grep -A 20 liveness
        livenessProbe:
          exec:
            command:
            - sh
            - /myscript.sh
          failureThreshold: 6
          httpGet:
            path: /-/healthy
            port: http-web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
```

And because of this, it can't create pods:
```
  Warning  FailedCreate      7m47s (x27 over 31m)  statefulset-controller  create Pod prometheus-prometheus-agent-0 in StatefulSet prometheus-prometheus-agent failed error: Pod "prometheus-prometheus-agent-0" is invalid: spec.containers[0].livenessProbe.httpGet: Forbidden: may not specify more than 1 handler type
```

I tried setting overriding `httpGet` without success.

**Did you expect to see some different?**

Maybe not "expect", but hoped I could find a way to replace the `httpGet` livenessProbe with an `exec` one.

**Environment**

* Prometheus Operator version:

    `prometheus-operator:v0.62.0`

* Kubernetes version information:

    `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"9710807c82740b9799453677c977758becf0acbb", GitTreeState:"clean", BuildDate:"2022-12-08T10:08:06Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else to know**

I've found the following related issues:
- https://github.com/prometheus-operator/prometheus-operator/issues/3587
- https://github.com/prometheus-operator/prometheus-operator/issues/4730

but in my case it looks like the basic merge is not enough.

**Comment by JoaoBraveCoding** [comment]
Disclaimer: I'm not a maintainer 
A couple of thoughts:
- This is indeed a bug but I'm not sure how we could solve it, IIUC strategic merge patch behaviour will depend on the key that's being modified, in this case, the `livenessProbe` should have the merge strategy set to `merge` instead of `replace`. So the other option I see would be check before adding probes if users are setting probes in the `containers` field 🤔  
- @hervenicol would it be possible for you to use the `ListenLocal` flag? If I'm not mistaken this flag makes it so Prometheus starts listening on localhost and that forces the operator to start using exec probes, then you would be able to set the command of the exec probe. It's a dirty hack but it might unblock you

**Comment by hervenicol** [comment]
The `ListenLocal` dirty hack unblocked me :+1: 
Thanks a lot!

Yet, if it's now considered a bug and there's a chance to have a cleaner fix, let's keep it open.

**Comment by simonpasquier** [comment]
Indeed strategic merge patch isn't helpful here.

> So the other option I see would be check before adding probes if users are setting probes in the containers field

We would need to account for use cases where strategic merge patch works fine (e.g. increasing the default failureThreshold value). One fix would be to sanitize the resulting container and keep the action passed in the patched container (e.g. if `livenessProbe.<action>` is set in the patched container, unset all other actions).

**Comment by veerendra2** [comment]
I'm having same issue. I upgraded Prometheus-Operator to `v0.65.1`.  Prometheus instance went down
```
Events:
  Type     Reason            Age                  From                    Message
  ----     ------            ----                 ----                    -------
  Normal   SuccessfulDelete  4m10s                statefulset-controller  delete Pod prometheus-prometheus-core-prometheus-0 in StatefulSet prometheus-prometheus-core-prometheus successful
  Warning  FailedCreate      86s (x16 over 4m9s)  statefulset-controller  create Pod prometheus-prometheus-core-prometheus-0 in StatefulSet prometheus-prometheus-core-prometheus failed error: Pod "prometheus-prometheus-core-prometheus-0" is invalid: spec.containers[0].livenessProbe.httpGet: Forbidden: may not specify more than 1 handler type
```
I see the operator is creating the sts with below `livenessProbe` config
```
...
livenessProbe:
  exec:
    command:
    - /bin/true
  failureThreshold: 1000
  httpGet:
    path: /-/healthy
    port: web
    scheme: HTTP
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 3
...
```
Then, I tried setting `listenLocal: true`, Prometheus instance is up and running 
```
k exec -it  prometheus-prometheus-core-prometheus-0 /bin/sh -n monitoring
/prometheus $ netstat -tulp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 localhost:9090          0.0.0.0:*               LISTEN      1/prometheus
tcp        0      0 localhost:http-alt      0.0.0.0:*               LISTEN      -
```
But I can't access prometheus endpoint.

is there any hack at prometheus-operator to make this working, like not to set multiple `livenessProbe`?
