### ISSUE TITLE
webexConfig for Alertmanager is missing

### ISSUE THREAD

**Issue by eumel8** [prometheus-operator/prometheus-operator#5295]
Just wondering, the [new Webex receiver](https://github.com/prometheus/alertmanager/releases/tag/v0.25.0) was implemented in https://github.com/prometheus-operator/prometheus-operator/pull/5254, thx to @simonpasquier , but maybe I have overseen, there is no implementation in alertmanagerconfigs.monitoring.coreos.com/v1alpha1 or alertmanagerconfigs.monitoring.coreos.com/v1beta1

Is there a plan or just no time? I'm curious to have this feature :-)

**Comment by xiu** [comment]
According to https://github.com/prometheus-operator/prometheus-operator/pull/5254#issuecomment-1370613809, the configuration generation part was done but the CRD still needs to be updated to support it.

This issue is similar to #5251.

**Comment by eumel8** [comment]
help wanted ... I would do my best
@xiu is it allowed to change existing CRDs like v1alpha1? thx

**Comment by xiu** [comment]
I'm not a maintainer but I would expect you can, @simonpasquier can you confirm?

**Comment by slashpai** [comment]
All sanitise part is taken care in https://github.com/prometheus-operator/prometheus-operator/pull/5254. This is not yet supported in CRD.

**Comment by xiu** [comment]
> help wanted ... I would do my best
@eumel8 are you taking this one on?

**Comment by eumel8** [comment]
@xiu ^^

**Comment by fctb** [comment]
any time when webex here working?

**Comment by eumel8** [comment]
available in https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.68.0

a working example can be catched up[ here](https://github.com/caas-team/use-cases/tree/main#alertmanagerconfig-for-webex-teams)
the used markdown template is described [here](https://github.com/caas-team/caas-project-monitoring/blob/feat/51.0.3/values.yaml#L145-L243)

thanks to @puffitos to get this feature finaly running
