### ISSUE TITLE
Prometheus operator should ignore resources with a deletionTimestamp

### ISSUE THREAD

**Issue by duizabojul** [prometheus-operator/prometheus-operator#5330]
**What happened?**

We have a setup with Prometheus operator deployed with Argo CD.

Let's say I have also a `monitoring.coreos.com/v1 Prometheus` resource deployed with Argo CD.

If I try to delete this resource, I delete it from my git repository, Argo CD will try to delete resource with a cascade deletion policy, so a finalizer and deletionTimestamp will be added on my Prometheus resource and kube api will try to delete all leafs resources (sts, secrets, cm, svc,...) before deleting the parent Prometheus resource. 

The problem here is Prometheus operator recreate them instantly because my Prometheus resource is always "alive" with a finalizer waiting for deletion of all leafs resources, so there is an infinite battle between Prometheus operator recreating resources and kubernetes deleting them. 

Eventually the Prometheus operator will not be quick enough to recreate resources and kubernetes will win the battle deleting all leaf resources and the parent resource will be deleted.

See [this issue](https://github.com/argoproj/argo-cd/issues/8712)   

Update: [Some logs of operator](https://pastebin.com/gQ4xDhNG) 

**Did you expect to see something different?**

Prometheus operator should not try to recreate resources if `monitoring.coreos.com` resources have a deletionTimestamp.

**Environment**

* Prometheus Operator version:

   quay.io/prometheus-operator/prometheus-operator:v0.63.0 

* Kubernetes version information:

    Client Version: v1.25.4
    Kustomize Version: v4.5.7
    Server Version: v1.24.10

* Kubernetes cluster kind:

    Minikube v1.28.0 but same behavior on EKS 1.24

**Comment by JoaoBraveCoding** [comment]
AFAIK this makes sense, I was not aware the operator was not checking `deletionTimestamp`, not sure if there is any historical reason to not do it. But if not then when I have a bit more time I'll try to contribute this change.

Disclaimer: I'm not a maintainer

**Comment by simonpasquier** [comment]
Reading https://github.com/argoproj/argo-cd/issues/8712

> When I try to delete the app, the argocd tries to delete prometheus statefulset.

Why does it want to do this? The prometheus operator sets proper owner references on all resources related to the Prometheus object so one should only delete the latter and Kubernetes will remove everything else...

**Comment by wotkddl21** [comment]
@simonpasquier 
I have no idea about the exact way or order how the argocd do send some requests to kube-apiserver to delete the argocd app.
In my case the k8s objects are listed in my argocd app, which is the prometheus-operator.
But there was no hierarchy among the prometheus object and the statefulset that the prometheus-operator should make from the prometheus object.

I will duble-check the hierarchy among them.

But according to @duizabojul's comment
``` bash
so a finalizer and deletionTimestamp will be added on my Prometheus resource
``` 
if the prometheus operator checks the deletionTimestamp of each object, then this issue would be solved.

**Comment by simonpasquier** [comment]
I'd like to fully understand before we make any change to the operator.

**Comment by wotkddl21** [comment]
@simonpasquier Today I try to reproduce the issue today so I made a new prometheus-operator-stack app in my argocd which is called test-prometheus and then delete it.
But the app was deleted well... (especially, the deployment of the prometheus operator deleted in parallel not waiting anything)
So there was no war between prometheus-operator and kube-apiserver.
I tried it several times to regenerate the problem, but I can't now.

**Comment by duizabojul** [comment]
> @simonpasquier Today I try to reproduce the issue today so I made a new prometheus-operator-stack app in my argocd which is called test-prometheus and then delete it.
> 
> But the app was deleted well... (especially, the deployment of the prometheus operator deleted in parallel not waiting anything)
> 
> So there was no war between prometheus-operator and kube-apiserver.
> 
> I tried it several times to regenerate the problem, but I can't now.  
> 
> 
> 
> 

It works if prometheus and prometheus-operator are deleted together. Try to deploy only the prometheus-operator (disable all except operator in values), and then deploy only prometheus with a coreos CR. Then try to remove the CR with a foreground cascading deletion (or remove CR from git if managed with argo CD).

**Comment by simonpasquier** [comment]
We'd need a minimal reproducer because I've never seen this type of issue.

**Comment by duizabojul** [comment]
- Install the operator: `kubectl create -f bundle.yaml`
- Add a prometheus resource. For example `kubectl apply -f prometheus.yaml` with the following file:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
  retention: 2d
  retentionSize: 10GB
  scrapeInterval: 10s
  evaluationInterval: 10s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
```

- Delete the resource with a foreground cascade deletion : `kubectl delete prometheus prometheus --cascade=foreground`
- Watch the battle between k8s and the operator

**Comment by simonpasquier** [comment]
I'm not seeing the same with the latest Prometheus operator as it should look at the deletion timestamp and return early if set.

https://github.com/prometheus-operator/prometheus-operator/blob/01dc7e1a847ba10322ecce85c44addc5b434ee2f/pkg/operator/resource_reconciler.go#L253-L255

**Comment by duizabojul** [comment]
I'm probably missing something but i just retried it again with [latest release](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.63.0) and it behave like I said, stateful set pod is recreated multiples times until k8s finally arrive to delete it before recreation.

**Comment by duizabojul** [comment]
I am maybe missing something but i just retried with the same exact steps of this [reply](https://github.com/prometheus-operator/prometheus-operator/issues/5330#issuecomment-1435639747) and the [latest release](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.63.0), and I got the sts pod and secrets recreating in loop until k8s managed to clean them all.

**Comment by simonpasquier** [comment]
Please run the Prometheus operator with `--log-level=debug` and share the logs.
Please also communicate all the versions you're using (as in the issue template).

**Comment by duizabojul** [comment]
Done in my first message
