### ISSUE TITLE
I need help to login in to kube prometheus stack prometheus to delete wal directory

### ISSUE THREAD

**Issue by laxmansoma1903** [prometheus-operator/prometheus-operator#5337]
**What did you do?**

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by laxmansoma1903** [comment]
   ~  kubectl -n monitoring exec -it prometheus-kube-prometheus-stack-prometheus-0   -- /sh                                                                 1 ✘  at gke-mfe-prod1 ⎈  at 16:23:56  

W0213 16:24:02.598657   93849 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "6a5bfe16a560c99cfe7036a3dc5ae1cb79a57d4d98056d1949c32d8c249416e7": OCI runtime exec failed: exec failed: unable to start container process: exec: "/sh": stat /sh: no such file or directory: unknown

**Comment by JoaoBraveCoding** [comment]
I'm not sure this is a question for this repo but it's 

```
kc exec -it -n monitoring prometheus-kube-prometheus-stack-prometheus-0 -- /bin/sh
rm -rf wal
```

**Comment by laxmansoma1903** [comment]
correct i tried that and receiving this error.

error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "a72ac4ebb0f43353e6f3d6fc26dd83d2ac76333e921b57366cb5a94cd97a3600": OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

**Comment by JoaoBraveCoding** [comment]
That's because the image you are using doesn't have a shell, maybe you will have success with `kubectl debug` you can use it on the pod
