### ISSUE TITLE
Add OCI label(s) to docker images

### ISSUE THREAD

**Issue by james-callahan** [prometheus-operator/prometheus-operator#5338]
**What is missing?**

The docker image label `org.opencontainers.image.source`

**Why do we need it?**

I'd like to take advantage of renovate's changelog support (https://docs.renovatebot.com/modules/datasource/docker/)

To do so, the recommended way is to add the standard OCI label `org.opencontainers.image.source` to docker images with a link to the github project.
A full list of pre-defined annotations is available at: https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys

**Environment**

N/A

**Comment by simonpasquier** [comment]
Sounds good to me :) I guess that the other predefined OCI annotations would be good to have too.
Do you want to send a PR?

**Comment by ksankeerth** [comment]
Hi @simonpasquier,

I'm interested in contributing  to this issue. I could add all the annotations mentioned in https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys. If I explain my approach, We can have  a shell script to extract the information needed for labels and generate docker files.  What do you think? 

Thanks,
Sankeerthan

**Comment by chiukapoor** [comment]
Hello @simonpasquier, May you please assign the issue to me?

In brief, we have to update the Dockerfile with predefined OCI annotations. Do we need to follow an automated way to do so or should we just manually update it?

**Comment by simonpasquier** [comment]
Updating the Dockerfile manually is fine by me.
