### ISSUE TITLE
Timeout in config-reloader not configurable

### ISSUE THREAD

**Issue by JHeilCoveo** [prometheus-operator/prometheus-operator#5346]
**What is missing?**

In `config-reloader` tool, the default timeout of 30 seconds when calling `/-/reload` endpoint of Prometheus is not configurable.

**Why do we need it?**

We currently face an issue where Prometheus takes longer than 30 seconds to reload its configuration.

For exemple :
> caller=main.go:1234 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=34.152274791s db_storage=2.48µs remote_storage=4.66µs web_handler=660ns query_engine=1.03µs scrape=1.68919009s scrape_sd=89.964915ms notify=27.572µs notify_sd=378.805µs rules=58.754µs tracing=6.2µs

And config-reloader tries and tries again until Prometheus responds in less than 30 seconds thus creating a huge load on it.

<details><summary>See config-reloader logs</summary>

> level=info caller=reloader.go:374 msg="Reload triggered" cfg_in=/etc/prometheus/config/prometheus.yaml.gz cfg_out=/etc/prometheus/config_out/prometheus.env.yaml watched_dirs=/etc/prometheus/rules/prometheus-prm-prometheus-rulefiles-0
> level=error caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
> level=error caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
> level=error caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
> level=error caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
> level=error caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
> level=error caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": context deadline exceeded"
> level=error caller=reloader.go:384 msg="Failed to trigger reload. Retrying." err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": context deadline exceeded"
> level=error caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
> level=error caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"http://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
> level=info caller=reloader.go:374 msg="Reload triggered" cfg_in=/etc/prometheus/config/prometheus.yaml.gz cfg_out=/etc/prometheus/config_out/prometheus.env.yaml watched_dirs=/etc/prometheus/rules/prometheus-prm-prometheus-rulefiles-0

</details>

**Environment**

* Prometheus Operator version:

    `v0.59.1`

**Anything else we need to know?**:

**Comment by JoaoBraveCoding** [comment]
AFAIK I'm not sure we would want to add a field to the CRD. However, this looks like something that at least we would want to make configurable using containerArgs. So from my side feel free to open a PR. 

Problematic part of the code https://github.com/prometheus-operator/prometheus-operator/blob/8c73904adee24013d8800336554d8709a565fb4a/cmd/prometheus-config-reloader/main.go#L167-L179

**Comment by JHeilCoveo** [comment]
I've created a small PR for prometheus-config-reloader.
