### ISSUE TITLE
Is there a way to dump the prometheus.yml generated by the operator for servicemonitor & podmonitor CRDs ?

### ISSUE THREAD

**Issue by vishiy** [prometheus-operator/prometheus-operator#5347]
Looking for a way to dump the prometheus.yml scrape config that was generated by the operator as a result of parsing servicemonitor & podmonitor crds. Is there a client tool in the operator project to do that? Or can the operator itself do it as an operation ? So basically given servicemonitor and podmonitor crds, woud like the prometheus.yml scrape config for them. Thanks in advance.

**Comment by JoaoBraveCoding** [comment]
AFAIK we don't have that functionality built-in, you can do it with `kubectl` + `jq` + `base64` + `gunzip` [1] is that good enough or were you looking for a go package?

[1] https://prometheus-operator.dev/docs/operator/troubleshooting/#has-my-servicemonitor-been-picked-up-by-prometheus

**Comment by achetronic** [comment]
> AFAIK we don't have that functionality built-in, you can do it with `kubectl` + `jq` + `base64` + `gunzip` [1] is that good enough or were you looking for a go package?
> 
> [1] https://prometheus-operator.dev/docs/operator/troubleshooting/#has-my-servicemonitor-been-picked-up-by-prometheus

Hello there, I would like to know if there is a go package for that :)
