### ISSUE TITLE
How to config prometheus and persist prometheus configuration

### ISSUE THREAD

**Issue by xiaofengzs** [prometheus-operator/prometheus-operator#5359]
### How to config prometheus?
I want to change prometheus default scrape_interval,   but can't find any document about it.
### How to persist prometheus config?
If prometheus instances restart or are re-created, I will loss my custom configuration. So i want to persist my configuration and load it as prometheus configuration.

**Comment by simonpasquier** [comment]
Can you share the YAML of the Prometheus resource?
