### ISSUE TITLE
alertmanager cant't start!

### ISSUE THREAD

**Issue by Hello-Linux** [prometheus-operator/prometheus-operator#5361]
**What happened?**
I accidentally deleted  the alertmanager statefulset resource and helm upgrade the values.yaml,but the alertmanager not deploy,then I change the alertmanager's config enable to false
```
alertmanager:

  ## Deploy alertmanager
  ##
  enabled: false
  ## Annotations for Alertmanager
```
but the k8s events show this error
```
Warning   FailedCreate          statefulset/alertmanager-kube-prometheus-stack-alertmanager          create Pod alertmanager-kube-prometheus-stack-alertmanager-0 in StatefulSet alertmanager-kube-prometheus-stack-alertmanager failed error: pods "alertmanager-kube-prometheus-stack-alertmanager-0" is forbidden: error looking up service account ubix-prod-monitoring/kube-prometheus-stack-alertmanager: serviceaccount "kube-prometheus-stack-alertmanager" not found
```
then I change the enable to true ,but helm upgrade can't install alertmanager, I can't find the statefulset for alertmanager
```
[root@ubix-k-prod docker_project]# kubectl get statefulset -n prod-monitoring
NAME                                                  READY   AGE
consul                                                1/1     15d
prometheus-kube-prometheus-stack-prometheus           2/2     8h
prometheus-kube-prometheus-stack-prometheus-shard-1   2/2     8h
thanos-ruler                                          2/2     4d8h
thanos-storegateway                                   2/2     4d20h
```
Why doesn't statefulset create itself?

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:
1. delete the alertmanager statefulset
2. helm upgrade the values.yaml,and not find alertmanager statefulset
**Environment**

* Prometheus Operator version:
kube-prometheus-stack-43.2.0.tgz

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
1.20
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
this is a question for https://github.com/prometheus-community/helm-charts.

**Comment by slashpai** [comment]
Closing since this is not related to prometheus-operator
