### ISSUE TITLE
How to change Grafana default http port to listen 80?

### ISSUE THREAD

**Issue by Hello-Linux** [prometheus-operator/prometheus-operator#5416]
**What happened?**
How to change Grafana default http port to listen 80?

**Did you expect to see something different?**
I change the port in grafana chart values.yaml,but the log show
```
logger=server t=2023-03-16T03:50:47.384317908Z level=error msg="Server shutdown" error="*api.HTTPServer run error: failed to open listener on address 0.0.0.0:80: listen tcp 0.0.0.0:80: bind: permission denied"
```

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by slashpai** [comment]
I think this is a question for https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
