### ISSUE TITLE
Allow version v2.43.0+stringlabels in Prometheus.spec.version

### ISSUE THREAD

**Issue by ondrejmo** [prometheus-operator/prometheus-operator#5434]
**What happened?**

`creating statefulset failed: StatefulSet.apps "prometheus-prometheus" is invalid: spec.template.labels: Invalid value: "2.43.0+stringlabels": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')`

**Did you expect to see something different?**

Deployed Prometheus `v2.43.0+stringlabels`.

**How to reproduce it (as minimally and precisely as possible)**:

Use `v2.43.0+stringlabels` as `.spec.version` of `Prometheus` resource.

**Environment**

* Prometheus Operator version:

    `v0.63.0`
    
    

* Kubernetes version information:

    `v1.25.7`
    

* Kubernetes cluster kind:

   k3s

**Anything else we need to know?**: 

   I believe that allowing `+` character in the `.spec.version` of the `Prometheus` resource will fix the issue.

**Comment by slashpai** [comment]
2.43 version is not yet supported in 0.63

https://github.com/prometheus-operator/prometheus-operator/blob/1a38cb5fde48aabe6dfb89b8b8388d45384d4660/pkg/operator/defaults.go#L51-L71

**Comment by slashpai** [comment]
Since this issue is logged adding a bit more context about new 2.43 prometheus feature here https://prometheus.io/blog/2023/03/21/stringlabel/

We would need to support this in prometheus-operator inorder to use it

**Comment by slashpai** [comment]
Happy to implement this I will wait for @simonpasquier's confirmation about the same :)

**Comment by ArthurSens** [comment]
> Have you tried setting `spec.version` to v2.43.0? It should work the same as long as you set `spec.image` to `prom/prometheus:v2.43.0+stringlabels`.

From the error shown in the PR description, the problem is when setting labels of the statefulset.

I believe the character `+` isn't valid for labels, so it needs to be sanitized first

**Comment by ondrejmo** [comment]
> Have you tried setting `spec.version` to v2.43.0? It should work the same as long as you set `spec.image` to `prom/prometheus:v2.43.0+stringlabels`.

Just tried it, it works, but the `+` needs to be replaced with `-` e.g. `prom/prometheus:v2.43.0-stringlabels`.

**Comment by mcbenjemaa** [comment]
@simonpasquier should we add compatibility of this image tag?

**Comment by simonpasquier** [comment]
@mcbenjemaa I don't think it is required as v2.43.0+stringlabels and v2.43.0 are the same as far as the operator is concerned (same arguments and configuration format).

**Comment by ondrejmo** [comment]
Since the `v2.44.0` version stringlabels are included in the default release/tag, the issue is no longer relevant.
