### ISSUE TITLE
Alertmanager and Prometheus statefulsets in terminating mode on AKS 1.24.9 version 

### ISSUE THREAD

**Issue by fromario007** [prometheus-operator/prometheus-operator#5437]
Hello
I attempted to deploy a kube-prometheus-stack on an AKS cluster version 1.24.9. However, I encountered an issue where the pods for Alertmanager and Prometheus, which are part of a statefulset, were not successfully deployed. Upon creation, these pods immediately transitioned into a terminating state
NAME                                                     READY   STATUS        RESTARTS   AGE
alertmanager-release-monitoring-kube-pro-alertmanager-0   0/2     Pending       0          0s
release-monitoring-grafana-5fb4c98d88-r2j99               3/3     Running       0          19m
release-monitoring-kube-pro-operator-7647b95df6-2dndd     1/1     Running       0          19m
release-monitoring-kube-state-metrics-7c484759cd-qwmwg    1/1     Running       0          19m
release-monitoring-prometheus-node-exporter-6gvs9         1/1     Running       0          19m
release-monitoring-prometheus-node-exporter-p87h4         1/1     Running       0          19m
release-monitoring-prometheus-node-exporter-rgjnv         1/1     Running       0          19m
release-monitoring-prometheus-node-exporter-sq69v         1/1     Running       0          19m
prometheus-release-monitoring-kube-pro-prometheus-0       0/2     Terminating   0          3s

The logs I am able to get:
kubectl logs alertmanager-release-monitoring-kube-pro-alertmanager-0 -f
ts=2023-03-22T16:14:39.902Z caller=main.go:240 level=info msg="Starting Alertmanager" version="(version=0.25.0, branch=HEAD, revision=258fab7cdd551f2cf251ed0348f0ad7289aee789)"
ts=2023-03-22T16:14:39.902Z caller=main.go:241 level=info build_context="(go=go1.19.4, user=root@abe8654564717, date=20221222-14:51:36)"
ts=2023-03-22T16:14:39.966Z caller=coordinator.go:113 level=info component=configuration msg="Loading configuration file" file=/etc/alertmanager/config_out/alertmanager.env.yaml
ts=2023-03-22T16:14:39.966Z caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config_out/alertmanager.env.yaml err="open /etc/alertmanager/config_out/alertmanager.env.yaml: no such file or directory"
-->

**What did you do?**
I tried to deploy an older version of the chart 40.0.0 but same result with statefulset.
On an AKS that has version 1.23.8 I did not had any issue deploying the Helm chart.
Is there anything I need to take in consideration when I deploying this helm chart on this new AKS version?
**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:
CHART VERSION 45.7.1
* Kubernetes version information:

    `kubectl version`

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"57fbbcc2804848b95cad5519f5ec9d6355430db9", GitTreeState:"clean", BuildDate:"2023-02-08T17:22:38Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.24) exceeds the supported minor version skew of +/-1

* Kubernetes cluster kind:

    AKS 1.24.9

**Comment by simonpasquier** [comment]
please ask Helm-related questions at https://github.com/prometheus-community/helm-charts.
