### ISSUE TITLE
Improve memory usage by using Metadata Informers

### ISSUE THREAD

**Issue by sthaha** [prometheus-operator/prometheus-operator#5438]
Following up on this discussion in this PR - [the same change should be done for the alertmanager and thanosruler controllers (but can be follow-up PRs).
](https://github.com/prometheus-operator/prometheus-operator/pull/5424#pullrequestreview-1348063676)

Lets investigate if using metadata informer gives us better results. 

@simonpasquier Since the root object for reconciliation is `namespace`, I wonder, if we should take this opportunity to  use metadata informer for watching all resources, if the `handle<CR-X>` only deals with metadata.

**Comment by sthaha** [comment]
I am happy to take up the issue.

**Comment by simonpasquier** [comment]
sure if we realize that for a given object, a metadata informer is enough then let's try it. The trigger with secrets (and configmaps probably) is that they can be large compared to ServiceMonitor, PodMonitor, etc.

**Comment by sthaha** [comment]
Makes sense @simonpasquier. I will submit a PR that updates `pkg/thanos` to use the new metadata-informer for cmap.
