### ISSUE TITLE
The config-reloader container has CPU requests of 200m

### ISSUE THREAD

**Issue by nemobis** [prometheus-operator/prometheus-operator#5446]
**What happened?**
I'm using the prometheus-operator on kubernetes 1.24. The config-reloader container reserves 200m CPU by its CPU requests, but needs barely 1m. This means that the my kubernetes node gets unnecessarily "full" while in reality it's idle. (The issue is compounded by other services with unrealistic CPU requests, like https://github.com/Azure/AKS/issues/3525 .)

**Did you expect to see something different?**
I'd like all containers on the prometheus-operator to have realistic resource requirements so that they don't crash but also don't reserve entire nodes for doing nothing.

**How to reproduce it (as minimally and precisely as possible)**:
An easy way to see all resource requests and limits is to install kube-capacity and issue `kube-capacity -c -n prometheus-operator`.

**Environment**

* Prometheus Operator version:

```
    Image:         relexkubeplatform.azurecr.io/quay.io/prometheus/prometheus:v2.42.0
    Image ID:      relexkubeplatform.azurecr.io/quay.io/prometheus/prometheus@sha256:d2ab0a27783fd4ad96a8853e2847b99a0be0043687b8a5d1ebfb2dd3fa4fd1b8
```

* Kubernetes version information:

1.24

**Comment by nemobis** [comment]
Thanks for checking. Sorry for the mixup, perhaps 200m was in an earlier version. 100m is still quite high: if a stock 2 vCPU node comes with a dozen services requesting a hundred times the CPU they need (which happened to me on AKS), the end result is that there isn't room for any real load.

**Comment by slashpai** [comment]
@nemobis You can change the default value using the `-config-reloader-cpu-request` argument

**Comment by nemobis** [comment]
Il 12/04/23 08:17, Jayapriya Pai ha scritto:
> @nemobis You can change the default value using the `-config-reloader-cpu-request` argument

Ok, but having an unreasonable default increases carbon emissions for 
everyone. Why not improve it?

**Comment by nemobis** [comment]
Sure. Any idea what could be the worst case scenario for config-reloader 
load? I've never managed to produce more than a negligible CPU load in 
the corresponding pod.

Il 13/04/23 14:24, Joao Marcal ha scritto:
> Still changing defaults it's never easy/recommended as this might break some users' set-ups.

Agreed, defaults need to be chosen with care and changes need to be 
clearly communicated.

I'm trying to think what kind of assumptions could break if the requests 
are brought closer to reality. The CPU weighting seems unlikely to 
matter, so perhaps it's about the initial allocation to a node.
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-limits-are-run

If config-reloader requests way more resources than it needs, and the 
pools allocatable CPU is less than 100m, a difference of 100m in 
requests may make a difference on whether the pod remains pending or 
not. Perhaps someone is relying on this behaviour in order to force the 
container to be scheduled on a node with a certain profile (e.g. request 
a node with at least 1 allocatable CPU by requesting barely more than 1 
CPU)? Or maybe someone is not able to reduce the portion of allocatable 
CPUs on their nodes <https://learnk8s.io/allocatable-resources> and 
relies on excessive CPU requests in order to create headroom for the OS? 
Not sure we'd need to support such use cases, but maybe someone can come 
up with better ones.

**Comment by JoaoBraveCoding** [comment]
> Sure. Any idea what could be the worst case scenario for config-reloader
load? 

I'm not too sure, but I guess it would be a big cluster where we would have to perform a change in many monitors 🤔 
as I said from my side before lowering this value I would have to look at how it normally behaves and how it looks on bigger clusters. However, with a cmd line flag existing nowadays, this is not soo much high up in our priorities but contributions are welcome!
I was looking back and this value is like this since config-reloader was introduced, @simonpasquier probably has some insight on why 100mi was picked.

**Comment by simonpasquier** [comment]
> I was looking back and this value is like this since config-reloader was introduced, @simonpasquier probably has some insight on why 100mi was picked.

Honestly, no :)

I'd be ok to decrease the default CPU requests since CPU is a compressible resource. But as @JoaoBraveCoding already said, we'd need some real data to understand what would a realistic value.

**Comment by ArthurSens** [comment]
Smaller requests becomes even more important as we advance with https://github.com/prometheus-operator/prometheus-operator/pull/5497 :)

**Comment by simonpasquier** [comment]
We discussed that during the last office hours meeting (notes [here](https://docs.google.com/document/d/1-fjJmzrwRpKmSPHtXN5u6VZnn39M28KqyQGBEJsqUOk/edit#bookmark=id.q3cajombe2f)) and agreed that we can improve the situation.
We agreed on 2 things:
* Change the current default values for the prometheus agent resources because 1) the CRD version is v1alpha1 so we have more freedom to change things and 2) the goal of the agent is to use less resources.
* Gather numbers from the community (please comment on this issue) and internally (@simonpasquier to collect information at Red Hat).

**Comment by ondrejmo** [comment]
It seems that the decrease to `10m` started to trigger [this alert](https://runbooks.prometheus-operator.dev/runbooks/kubernetes/cputhrottlinghigh/) in my cluster. Would it be possible to use something in the middle? e.g. `20m`

## Output example

```
CPUThrottlingHigh: 61.9% throttling of CPU in namespace monitoring for container config-reloader in pod alertmanager-alertmanager-0.
```

**Comment by ondrejmo** [comment]
> Il 19/06/23 10:35, Ondřej Molík ha scritto:
> It seems that the decrease to `10m` started to trigger [this alert]
> Really? What expression does it use? Based on the description, it's supposed to look at limits, not requests. This issue was only about requests.

https://github.com/prometheus-operator/kube-prometheus/blob/27a3f25bd9e89bc0c098a9555c5e418738984b34/manifests/kubernetesControlPlane-prometheusRule.yaml#L348

**Comment by oscgu** [comment]
I can see this happening in multiple Clusters now. It's always the alertmanager and prometheus-k8s pods where the config-reloader container is being throttled

**Comment by ArthurSens** [comment]
Could you reconfigure the requests and limits by passing an extra flag to the operator as [documented in the latest release](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.66.0)?

**Comment by oscgu** [comment]
How can I do that using the kube-prometheus jsonnet stack?

**Comment by simonpasquier** [comment]
@ebarped can you file another issue please?
