### ISSUE TITLE
Reduce code duplication from `createOrUpdateConfigurationSecret()` 

### ISSUE THREAD

**Issue by ArthurSens** [prometheus-operator/prometheus-operator#5455]
There might be room for reducing the duplication between agent & server? Again this can be a follow-up.

_Originally posted by @simonpasquier in https://github.com/prometheus-operator/prometheus-operator/pull/5385#discussion_r1140401155_
            
---

More precisely, the configuration from PrometheusAgent is a subset from Prometheus. Parts that are similar can probably be centralized in `pkg/prometheus` and parts that are exclusive for Prometheus Server can stay at `pkg/prometheus/server`

**Comment by sthaha** [comment]
I am happy to take this up if no one is working on. 
cc: @slashpai @simonpasquier
