### ISSUE TITLE
i only want to install  alertmanager with oporator

### ISSUE THREAD

**Issue by bruse-peng** [prometheus-operator/prometheus-operator#5470]
i only want to install  alertmanager with oporator, i do not want other component. what should i do?
other component i will user victoriametrics

**Comment by ArthurSens** [comment]
Just saw this now and a thought came up.


@prometheus-operator/prometheus-operator-reviewers, should we allow installing just a few CRD, even for the 'v1' API?

**Comment by simonpasquier** [comment]
@ArthurSens interesting idea. I definitely like the idea that the operator reports back if all prerequisites (CRDs and permissions) are met. I'm on the fence on whether it should degrade if it can't manage v1 CRDs but happy to hear more feedback.

**Comment by simonpasquier** [comment]
My main concern is that if you mess up the setup (e.g. "forget" to deploy the Prometheus CRD), it might be hard to understand why the operator doesn't react as expected.
But I also like the ability to run "smaller" operators like 1 for Alertmanager/AlertmanagerConfig and 1 for Prometheus/PodMonitor/ServiceMonitor/Probe/PrometheusRules...

**Comment by simonpasquier** [comment]
> Good point, we also need to think about the case where CRDs get installed after the operator thinking

I'd expect something/someone to restart the operator's pod...
