### ISSUE TITLE
resolve alertmanager-main-0.alertmanager-operated:9094

### ISSUE THREAD

**Issue by bruse-peng** [prometheus-operator/prometheus-operator#5498]
altermanger error log below, version:alertmanager:v0.25.0

ager-operated:9094: lookup alertmanager-main-2.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:03:44.435Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:03:59.437Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:04:14.437Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:04:29.435Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:04:44.435Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:04:59.436Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:05:14.437Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:05:29.437Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:05:44.435Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:05:59.435Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"

**Comment by slashpai** [comment]
👋🏻  Thanks for reporting issue

Could you please follow issue template https://github.com/prometheus-operator/prometheus-operator/blob/main/.github/ISSUE_TEMPLATE/support.md?

**Comment by bruse-peng** [comment]
Environment

Prometheus Operator version:

Insert image tag or Git SHA here

Kubernetes version information:
1.20.6

kubectl version
[root@VM_2_15_centos ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.3-tke.10", GitCommit:"02a1f2c1ac7af926ad01a8f70a8123107afdc56f", GitTreeState:"clean", BuildDate:"2020-07-22T07:27:20Z", GoVersion:"go1.12.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.6-tke.27", GitCommit:"9921bde307511509f8cbdf2391339b33a1207ba7", GitTreeState:"clean", BuildDate:"2022-10-08T04:02:09Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
[root@VM_2_15_centos ~]# 

Kubernetes cluster kind:
tencent tke k8s cluster

insert how you created your cluster: kops, bootkube, etc.

Manifests:

insert manifests relevant to the issue
Prometheus Operator Logs:
insert Prometheus Operator logs relevant to the issue here

kubectl logs -f alertmanager-main-0  -n monitoring -c alertmanager
ager-operated:9094: lookup alertmanager-main-2.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:03:44.435Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:03:59.437Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:04:14.437Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:04:29.435Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:04:44.435Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:04:59.436Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:05:14.437Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:05:29.437Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:05:44.435Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"
ts=2023-04-14T04:05:59.435Z caller=cluster.go:471 level=warn component=cluster msg=refresh result=failure addr=alertmanager-main-0.alertmanager-operated:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 10.57.252.89:53: no such host\n\n"

**Comment by JoaoBraveCoding** [comment]
Which version of prometheus-operator are you using? How was the operator installed?

From the error message, it's not clear at all that the problem is coming from Prom-Operator since it seems to be a networking problem

**Comment by bruse-peng** [comment]
> Which version of prometheus-operator are you using? How was the operator installed?
> 
> From the error message, it's not clear at all that the problem is coming from Prom-Operator since it seems to be a networking problem

version:quay.io/prometheus-operator/prometheus-operator:v0.64.0

install steps:
1、kubectl create -f  bundle.yaml 
2、install alertmanager with the crd kind of Alertmanager
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 3
  logLevel: debug
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: sams-qa

**Comment by venkatesh-1986p** [comment]
I am getting same struggling from past 30days can any one help us
