### ISSUE TITLE
Support for node-based discovery

### ISSUE THREAD

**Issue by grzesuav** [prometheus-operator/prometheus-operator#5509]
**What is missing?**

I would like to discover nodes, without services on it, to be able to scrape particular node endpoint and manage the config via CRD, i.e. `NodeMonitor` (similar to service monitor).

Currently I am using `additionalScrapeConfigs` with `node` discovery - https://prometheus.io/docs/prometheus/latest/configuration/configuration/#node

**Why do we need it?**

There are some native agents running on VM's, exposing prometheus metrics, I would like to scrape them. 

Important note - they are not kubernetes DeamonSets, they run natively on the VM

**Environment**

AKS

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
This would probably a good fit for the upcoming ScrapeConfig CRD #2787

**Comment by slashpai** [comment]
I will give this a try to implement :)

**Comment by slashpai** [comment]
IIUC we want to support this feature for 3 major CP's. I will have them in separate PR's 

I need to figure out how would we able to test this in e2e unless we have access to an instance? 

# List of EC2 service discovery configurations.
ec2_sd_configs:
  [ - [<ec2_sd_config>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ec2_sd_config) ... ]
# List of Azure service discovery configurations.
azure_sd_configs:
  [ - [<azure_sd_config>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#azure_sd_config) ... ]
# List of GCE service discovery configurations.
gce_sd_configs:
  [ - [<gce_sd_config>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#gce_sd_config) ... ]

**Comment by slashpai** [comment]
First we will focus on https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config's node role and then move to CP's.

**Comment by slashpai** [comment]
Since I am unable to edit issue adding as comment here for related issues


- [x] Kubernetes node monitoring https://github.com/prometheus-operator/prometheus-operator/issues/5711 (available in v0.68 version of prometheus-operator)
- [x] EC2  https://github.com/prometheus-operator/prometheus-operator/issues/5818 (will be available in v0.69 version)
- [ ] GCE
- [ ] Azure

**Comment by slashpai** [comment]
w.r.t node related discoveries this issue is now completed with support for in-cluster node monitoring and support for 3 major cloud providers.

Kube node v0.68
AWS v0.69
Azure and GCE will be available once v0.70 is released
