### ISSUE TITLE
Thanos link is missing in the source when the alert triggers in Prometheus stack v43.2.0

### ISSUE THREAD

**Issue by akheel5544** [prometheus-operator/prometheus-operator#5515]
**What happened?**
Thanos link is missing in the source when the alerts are triggered in Opsgenie.
Example:
Source: /graph?g0.expr=%281+-+absent%28kube_pod_status_ready%7Bcondition%3D%22true%22%2Cnamespace%3D%22tps-obelix%22%2Cpod%3D~%22.%2Acid-operator.%2A%22%7D%29%29+or+sum%28kube_pod_status_ready%7Bcondition%3D%22true%22%2Cnamespace%3D%22tps-obelix%22%2Cpod%3D~%22.%2Acid-operator.%2A%22%7D%29+%3D%3D+0&g0.tab=1

**Did you expect to see something different?**
The source should point to thanos link for example:

Source: **<thanos url>**/graph?g0.expr=%281+-+absent%28kube_pod_status_ready%7Bcondition%3D%22true%22%2Cnamespace%3D%22tps-obelix%22%2Cpod%3D~%22.%2Acid-operator.%2A%22%7D%29%29+or+sum%28kube_pod_status_ready%7Bcondition%3D%22true%22%2Cnamespace%3D%22tps-obelix%22%2Cpod%3D~%22.%2Acid-operator.%2A%22%7D%29+%3D%3D+0&g0.tab=1 

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**
The source url used to work in prometheus stack version: 41.7.3. but not showing in version: 43.2.0. Also, we have checked that web external url is properly configured in

        - name: prometheus
          args:
            - '--config.file=/etc/prometheus/config_out/prometheus.env.yaml'
            - '--storage.agent.path=/prometheus'
            - '--enable-feature=agent'
            - '--web.enable-lifecycle'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.external-url=<thanos url>'
            - '--web.route-prefix=/'
            - '--web.config.file=/etc/prometheus/web_config/web-config.yaml'

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

kubernetes version = 1.24.6

* Kubernetes cluster kind:

   helmrepository

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
@fpetkovski mentioned to me a related Thanos issue but I'm too lazy to find it. 
@akheel5544 maybe you know which issue I'm referring to?

**Comment by akheel5544** [comment]
**What happened?**
Thanos link is missing in the source when the alerts are triggered in Opsgenie.
Example:
Source: /graph?g0.expr=%281+-+absent%28kube_pod_status_ready%7Bcondition%3D%22true%22%2Cnamespace%3D%22tps-obelix%22%2Cpod%3D~%22.%2Acid-operator.%2A%22%7D%29%29+or+sum%28kube_pod_status_ready%7Bcondition%3D%22true%22%2Cnamespace%3D%22tps-obelix%22%2Cpod%3D~%22.%2Acid-operator.%2A%22%7D%29+%3D%3D+0&g0.tab=1

**Did you expect to see something different?**
The source should point to thanos link for example:

Source: <thanos url>/graph?g0.expr=%281+-+absent%28kube_pod_status_ready%7Bcondition%3D%22true%22%2Cnamespace%3D%22tps-obelix%22%2Cpod%3D~%22.%2Acid-operator.%2A%22%7D%29%29+or+sum%28kube_pod_status_ready%7Bcondition%3D%22true%22%2Cnamespace%3D%22tps-obelix%22%2Cpod%3D~%22.%2Acid-operator.%2A%22%7D%29+%3D%3D+0&g0.tab=1 

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**
The source url used to work in prometheus stack version: 41.7.3. but not showing in version: 43.2.0. Also, we have checked that web external url is properly configured in

        - name: prometheus
          args:
            - '--config.file=/etc/prometheus/config_out/prometheus.env.yaml'
            - '--storage.agent.path=/prometheus'
            - '--enable-feature=agent'
            - '--web.enable-lifecycle'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.external-url=<thanos url>'
            - '--web.route-prefix=/'
            - '--web.config.file=/etc/prometheus/web_config/web-config.yaml'

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

kubernetes version = 1.24.6

* Kubernetes cluster kind:

   helmrepository

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by akheel5544** [comment]
Can someone please help me in this issue. @slashpai

**Comment by akheel5544** [comment]
Hello @slashpai @simonpasquier. Can you please help me to resolve this issue.
