### ISSUE TITLE
Custom annotations to prometheus statefulset

### ISSUE THREAD

**Issue by michalschott** [prometheus-operator/prometheus-operator#5536]
**What is missing?**
Theres no ability to inject custom annotations to statefulsets

**Why do we need it?**
In my case, I'm using [polaris](https://github.com/FairwindsOps/polaris) as a validation webhook, rule exemptions can be defined by adding annotations to objects.

`podMetadata` is not enough, as this needs to be set on controller level

**Comment by simonpasquier** [comment]
Can you provide more details about what you're missing and what you'd expect to see happening?
Are you asking specifically about setting annotations to the statefulset created by the operator?

**Comment by michalschott** [comment]
Hey @simonpasquier, sorry for not being clear.

Yes, annotation needs to be set on STS level managed by operator, not on pods (podMetadata).

**Comment by simonpasquier** [comment]
The operator has a CLI argument (`--labels`) to add labels to all the resources that it manages. Would it help to add a `--annotations` flag?
As of today, you should be able to add the annotations to the statefulset manually and the operator should preserve them.

**Comment by michalschott** [comment]
@simonpasquier Indeed I could add them manually, but for empheral clusters I'd need to do it over and over, maybe as an extra step - long therm this is bot efficient norbscalable, especially with gitops approach.

Guess adding annotations flag, similar to labels would be enough.

**Comment by michalschott** [comment]
@JoaoBraveCoding @simonpasquier I opted in to add `--prometheus-annotations` flag instead, because there might be use case where we'd like not to add the same annotations to AlertManager or Thanos.
