### ISSUE TITLE
Add volumeMounts to ThanosRulerSpec

### ISSUE THREAD

**Issue by vCra** [prometheus-operator/prometheus-operator#5538]
**What is missing?**

Currently, we are able to add a volume to a ThanosRuler, via the `volumes` property, and which gets propagated to the generated StatefulSet. However, `ThanosRuler`, unlike with the spec for `Alertmanager`, `Prometheus` and `PrometheusAgent`, does not have a `volumeMounts` property, which means that it is not easily possible to mount the volume.

**Why do we need it?**

My current use case is to facilitate Stateless ruler operation to a secured Thanos Receive instance, which needs client certs and CAs mounting. 
However we should not just support this use case, but any other future use cases which could require a volume to be mounted within a Ruler instance (although it would be nice to have first-class support for this)

**Environment**

* Prometheus Operator version: `v0.58.0`

**Comment by simonpasquier** [comment]
Hmm ThanosRuler not having a `.spec.volumeMounts` field is probably an oversight as I see no good reason from deviating from the other CRDs. Do you want to contribute the change?
