### ISSUE TITLE
Check ScrapeConfig prerequisites in cmd/operator.go rather than the prometheus operators

### ISSUE THREAD

**Issue by xiu** [prometheus-operator/prometheus-operator#5546]
**Context**
This is a follow up after the merge of #5335.

From @simonpasquier in https://github.com/prometheus-operator/prometheus-operator/pull/5335#discussion_r1182651934
> I was thinking that it could be delegated to cmd/operator/main.go and we add a new parameter to the New() function to define whether scrape configs are enabled or not. It would also avoid code duplication between agent and server.

Move the logic that check prerequisites in `cmd/operator.go`.

**Comment by Azanul** [comment]
@simonpasquier I'd like to work on this. Please assign this to me.

**Comment by slashpai** [comment]
@Azanul Please free to work on. Generally commenting on issue is enough if you want to work on :)

**Comment by Azanul** [comment]
> @Azanul Please free to work on. Generally commenting on issue is enough if you want to work on :)

I'll keep that in mind

**Comment by ArthurSens** [comment]
I'm reopening this issue because I noticed that #5666 moved the pre-requisit checks in the server operator.

The goal of this issue was to reduce code duplication between Server/Agent when checking the ScrapeConfig pre requisites, so we also want to do the same in `pkg/prometheus/agent/operator.go` :)

**Comment by simonpasquier** [comment]
:facepalm: @Azanul would like to follow up on this one?

Basically we should remove these lines in the agent controller:
https://github.com/prometheus-operator/prometheus-operator/blob/ae6a3f7ca1bbc354110f891e20ee2d7cc2d17f5d/pkg/prometheus/agent/operator.go#L112-L139
