### ISSUE TITLE
Support for send_native_histograms

### ISSUE THREAD

**Issue by kenske** [prometheus-operator/prometheus-operator#5560]
**What is missing?**
The `send_native_histograms` for `prometheus.remote_write` [endpoint blocks](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.remote_write/#endpoint-block)

**Why do we need it?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write would be the correct link.

**Comment by slashpai** [comment]
Adding a note here this feature is added in  Prometheus `2.40 ` https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md#2400--2022-11-08
