### ISSUE TITLE
prometheus-config-reloader: Reduce the number of the exposed metrics Go

### ISSUE THREAD

**Issue by FUSAKLA** [prometheus-operator/prometheus-operator#5565]
The config-reloader exposes way more metrics than the Prometheus itself.

Worst are the histograms: 
 - `go_sched_latencies_seconds_bucket`:  720 metrics per instance
 - `go_gc_pauses_seconds_total_bucket`:  720 metrics per instance

Both caused high density histogram buckets. 

Not sure if it is needed at all? Even though user can drop those using relabeling in service monitor, it feels like not sane default.

Also, it uses deprecated way of initialization of the Go collector in https://github.com/prometheus-operator/prometheus-operator/blob/main/cmd/prometheus-config-reloader/main.go#L118

Maybe it could be caused by that.

I'd be happy to send a fix but wanted to get an ACK before.

[Example of config-reloader metrics](https://github.com/prometheus-operator/prometheus-operator/files/11441435/config-reloader-metrics.txt)

**Environment**

* Prometheus Operator version: v0.54.1

**Comment by JoaoBraveCoding** [comment]
Indeed by the example you just pasted it seems that by default we expose to many metrics. Furthermore AFAIK we never took the time to filter and reason about metrics exposed by the config-reloader so this issue seems to make sense.

**Comment by FUSAKLA** [comment]
Ha, we just upgraded from the mentioned quite old version 0.54.1 to the newest 0.65.1 and the number of metrics dropped from circa 1600 metrics per instance to 60 which seems to be more than reasonable.

So I suppose we can close this :tada: 

But thanks for consideration anyway! Happy that it's resolved.
