### ISSUE TITLE
Add params support to the ScrapConfig CRD (federation use case)

### ISSUE THREAD

**Issue by fluzzykitten** [prometheus-operator/prometheus-operator#5592]
ScrapeConfig CRD does not support federation scrapes because it does not allow setting the "http params"

`prometheus-operator:v0.65.1`

We would like to be able to define scraping federation endpoints through the use of a ScrapeConfig CRD. In order to scrape the federation endpoints, we need the ability to include the "desired match[] parameters" or the federation endpoint will return nothing.
https://prometheus.io/docs/prometheus/latest/federation/#configuring-federation

Currently, the spec for ScrapeConfig does not allow specifying HTTP params of scrape configs:
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
```
# Optional HTTP URL parameters.
params:
  [ [<string>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#string): [[<string>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#string), ...] ]
```

Per the Prometheus-Operator API Spec:
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1alpha1.ScrapeConfigSpec

**Comment by sthaha** [comment]
@xiu, @simonpasquier, @slashpai  , I am happy to work on this if no else has started with this one :-)

**Comment by slashpai** [comment]
@sthaha I don't see anyone mentioning working on it. Please free to work on :)

**Comment by sthaha** [comment]
@slashpai thank you, could you please assign the issue to me :-) ?

**Comment by Yasamal33** [comment]
Just have implemented scrapeConfing using CR and realized that there is no federation support in actual CRD implementation (0.66.0)

**Comment by ariep** [comment]
Another use case of this: using a blackbox exporter through a ScrapeConfig. That's a logical combination I think, and it's not possible right now as far as I understand, because you can't set the `module` url param in the ScrapeConfig. I tried adding it to the `metricsPath` but that doesn't work, presumably because prometheus adds another `?` suffix with the target and doesn't notice that there are already url parameters in the metrics path.
