### ISSUE TITLE
Supporting CEL once it gradautes

### ISSUE THREAD

**Issue by JoaoBraveCoding** [prometheus-operator/prometheus-operator#5605]
IIUC validation markers can't check that at least one of `.spec.targets.static` or `.spec.targets.ingress`  is defined. It should be possible with [CEL](https://kubernetes.io/docs/reference/using-api/cel/) though but it's still [beta](https://kubernetes.io/blog/2022/09/23/crd-validation-rules-beta/). Anyway, supporting/using CEL is probably a discussion to have in a separate issue.

_Originally posted by @simonpasquier in https://github.com/prometheus-operator/prometheus-operator/pull/5586#discussion_r1200436536_

**Comment by slashpai** [comment]
IIUC this is similar to https://github.com/prometheus-operator/prometheus-operator/issues/5079

**Comment by simonpasquier** [comment]
correct, closing as duplicate.

**Comment by JoaoBraveCoding** [comment]
Sorry, I forgot to check if there was already an issue 🤦
