### ISSUE TITLE
detecting support for endpointslices is broken (kubernetes 1.26 at least)

### ISSUE THREAD

**Issue by lbedford** [prometheus-operator/prometheus-operator#5613]
**What happened?**
Kubernetes 1.26 cluster with the kube-monitoring-stack helm chart installed.
prometheus-operator prints
level=warn ts=2023-05-28T15:36:35.616677237Z caller=operator.go:384 component=prometheusoperator msg="failed to check if the API supports the endpointslice resources" err="converting (v1.APIGroup) to (v1.APIResourceList): unknown conversion"
level=info ts=2023-05-28T15:36:35.616710276Z caller=operator.go:386 component=prometheusoperator msg="Kubernetes API capabilities" endpointslices=false

on startup

**Did you expect to see something different?**
I would expect to see
level=info ts=2023-05-28T15:36:35.616710276Z caller=operator.go:386 component=prometheusoperator msg="Kubernetes API capabilities" endpointslices=true

**How to reproduce it (as minimally and precisely as possible)**:
I extracted the relevant call from pkg/prometheus/server/operator.go (line 383):
`endpointSliceSupported, err := k8sutil.IsAPIGroupVersionResourceSupported(clientset.Discovery(), "discovery.k8s.io", "endpointslices")`

This is sufficient in a test:
```
package main

import (
	"fmt"
	"github.com/prometheus-operator/prometheus-operator/pkg/k8sutil"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
)

func main() {
	config, err := rest.InClusterConfig()
	if err != nil {
		panic(err.Error())
	}
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		panic(err.Error())
	}
	endpointSliceSupported, err := k8sutil.IsAPIGroupVersionResourceSupported(clientset.Discovery(), "discovery.k8s.io", "endpointslices")
	if err != nil {
		fmt.Printf("failed to check if the API supports the endpointslice resources\n")
		panic(err.Error())
	}
	fmt.Printf("endpointslice supported: %v\n", endpointSliceSupported)
}
```

**Environment**

* Prometheus Operator version:
`Image:      quay.io/prometheus-operator/prometheus-operator:v0.65.1`

* Kubernetes version information:
```
kubectl version --short
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.26.2
```

* Kubernetes cluster kind:
kubespray

* Prometheus Operator Logs:
```
$ kubectl logs -n monitoring -f monitoring-kube-prometheus-operator-7d99f86694-jkk5p
level=info ts=2023-05-28T15:36:34.590773986Z caller=main.go:222 msg="Starting Prometheus Operator" version="(version=0.65.1, branch=refs/tags/v0.65.1, revision=b5e9f22fffd6cc2632eb1c79c79b63bfa9158665)"
level=info ts=2023-05-28T15:36:34.59083216Z caller=main.go:223 build_context="(go=go1.20.3, platform=linux/amd64, user=Action-Run-ID-4895424603, date=20230505-16:19:39, tags=unknown)"
level=warn ts=2023-05-28T15:36:35.614353973Z caller=operator.go:163 component=prometheusoperator msg="ScrapeConfig CRD disabled because prerequisites are not met" err="unmet prerequisites: scrapeconfigs resource (apiGroup: \"monitoring.coreos.com/v1alpha1\") not installed"
level=warn ts=2023-05-28T15:36:35.616677237Z caller=operator.go:384 component=prometheusoperator msg="failed to check if the API supports the endpointslice resources" err="converting (v1.APIGroup) to (v1.APIResourceList): unknown conversion"
level=info ts=2023-05-28T15:36:35.616710276Z caller=operator.go:386 component=prometheusoperator msg="Kubernetes API capabilities" endpointslices=false
level=warn ts=2023-05-28T15:36:35.618612837Z caller=main.go:291 msg="Prometheus agent controller disabled because prerequisites not met" err="unmet prerequisites: prometheusagents resource (apiGroup: \"monitoring.coreos.com/v1alpha1\") not installed"
level=info ts=2023-05-28T15:36:35.620915948Z caller=main.go:114 msg="Starting secure server on [::]:10250"
```

**Anything else we need to know?**:
From what I can see, with this kubernetes version, changing "discovery.k8s.io" to "discovery.k8s.io/v1" is sufficient to fix it. But I don't know if that will break previous versions of kubernetes, as I don't have them setup here.

From experimenting with various things:
$APISERVER/apis/discovery.k8s.io
returns an APIGroup:
```
$ curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/apis/discovery.k8s.io
{
  "kind": "APIGroup",
  "apiVersion": "v1",
  "name": "discovery.k8s.io",
  "versions": [
    {
      "groupVersion": "discovery.k8s.io/v1",
      "version": "v1"
    }
  ],
  "preferredVersion": {
    "groupVersion": "discovery.k8s.io/v1",
    "version": "v1"
  }
}
```
where the code is expecting an APIResourceList.

With a version, it does the right thing:
```
$ curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/apis/discovery.k8s.io/v1
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "discovery.k8s.io/v1",
  "resources": [
    {
      "name": "endpointslices",
      "singularName": "",
      "namespaced": true,
      "kind": "EndpointSlice",
      "verbs": [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch"
      ],
      "storageVersionHash": "Nx3SIv6I0mE="
    }
  ]
}
```

**Comment by xiu** [comment]
Thanks for the report! Related:
* https://github.com/prometheus-operator/prometheus-operator/pull/5291
* https://github.com/prometheus-operator/prometheus-operator/issues/3862#issuecomment-1068260430
