### ISSUE TITLE
Add support for authentication to the ScrapeConfig CRD

### ISSUE THREAD

**Issue by aedwardstx** [prometheus-operator/prometheus-operator#5620]
**What is missing?**
The new ScrapeConfig CRD does not allow for specifying any authorization header for the different SD configs.

- [ ] authorization
- [ ] basicAuth

**Why do we need it?**

Authentication is required when scraping configs from a secured API in many environments. 

**Example prometheus config**
https://prometheus.io/docs/prometheus/latest/configuration/configuration/
```
# Sets the `Authorization` header on every scrape request with the
# configured username and password.
# password and password_file are mutually exclusive.
basic_auth:
  [ username: [<string>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#string) ]
  [ password: [<secret>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#secret) ]
  [ password_file: [<string>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#string) ]

# Sets the `Authorization` header on every scrape request with
# the configured credentials.
authorization:
  # Sets the authentication type of the request.
  [ type: [<string>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#string) | default: Bearer ]
  # Sets the credentials of the request. It is mutually exclusive with
  # `credentials_file`.
  [ credentials: [<secret>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#secret) ]
  # Sets the credentials of the request with the credentials read from the
  # configured file. It is mutually exclusive with `credentials`.
  [ credentials_file: [<filename>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#filename) ]
```

**Comment by xiu** [comment]
Hey @aedwardstx, thanks for opening this issue! Is this something you would feel comfortable to contribute?

**Comment by sthaha** [comment]
@xiu, @simonpasquier , I am happy to work on this if no else has started with it.

**Comment by xiu** [comment]
@sthaha haven't heard of anything, go for it :+1:

**Comment by dmitriishaburov** [comment]
> @xiu, @simonpasquier , I am happy to work on this if no else has started with it.

I've actually played with it today, and implemented it.

I'll create PR, but it can be closed if someone implements it better

**Comment by sthaha** [comment]
I have unassigned myself in favour of the #5642 raised by @dmitriishaburov
