### ISSUE TITLE
 Add support for consul_sd_config to scrapeConfigs CRD

### ISSUE THREAD

**Issue by heliapb** [prometheus-operator/prometheus-operator#5629]
**What is missing?**
Currently ScrapeConfig CRD doesn't now support consul_sd_config option.

**Why do we need it?**
Since Consul is a tool used for service Discovery, adding this to ScrapeConfig CRD would expand the use cases of this CRD. As currently to use consul for service discovery we need to rely on additionalScrapeConfigs to do so.
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#consul_sd_config

**Comment by nicolastakashi** [comment]
Hey folks!
I would like to work on that
