### ISSUE TITLE
Add basicAuth support to ScrapeConfig CRD

### ISSUE THREAD

**Issue by dmitriishaburov** [prometheus-operator/prometheus-operator#5634]
**What is missing?**
ScrapeConfig CRD doesn't supports `basic_auth` option

**Why do we need it?**
Some targets discovered with ScrapeConfig can require authentication. Would be nice to add basicAuth option to it, that references secret used for basic authentication. That feature already supported in many other prometheus-operator CRD's

**Comment by simonpasquier** [comment]
similar to #5620

**Comment by dmitriishaburov** [comment]
> similar to #5620

@simonpasquier not exactly, that's different configuration options.
 
`scrape_config.basic_auth` here vs `scrape_config.http_sd_config.basic_auth` in mentioned feature request

**Comment by simonpasquier** [comment]
I've rewritten the description of #5620 to make it clear that it's not specific to HTTP SD configs.

**Comment by dmitriishaburov** [comment]
Thanks, that's clear now 👍
