### ISSUE TITLE
Move PrometheusTracingConfig to `CommonPrometheusFields`

### ISSUE THREAD

**Issue by ArthurSens** [prometheus-operator/prometheus-operator#5635]
AFAICT it is technically possible to configure tracing in agent mode and it's even supported in remote write

https://github.com/prometheus/prometheus/blob/a8772a41782758e8153c494dcd207e770d8421a4/storage/remote/client.go#L204

_Originally posted by @simonpasquier in https://github.com/prometheus-operator/prometheus-operator/pull/5591#discussion_r1213268189_
            
---

We added support for configuring tracing in Prometheus Server in #5591, but as Simon pointed out, Prometheus Agents can also be configured in the same way.

Let's move the `PrometheusTracingConfig` field to [CommonPrometheusFields](https://github.com/prometheus-operator/prometheus-operator/blob/d9df32355c7b81f8737bd545270144ea606380ea/pkg/apis/monitoring/v1/prometheus_types.go#L56) and add the same configuration to [GenerateAgentConfiguration](https://github.com/prometheus-operator/prometheus-operator/blob/d9df32355c7b81f8737bd545270144ea606380ea/pkg/prometheus/promcfg.go#L2051)

**Comment by GauravJ3** [comment]
@ArthurSens Raised the PR for same.
