### ISSUE TITLE
Support new global scrape configuration parameters

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#5638]
**What is missing?**

https://github.com/prometheus/prometheus/pull/12126 adds new fields to the global config section:

```
    body_size_limit
    sample_limit
    target_limit
    label_limit
    label_name_length_limit
    label_value_length_limit
```

**Why do we need it?**

Feature parity.

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:

Need to wait for Prometheus v2.45.0.

**Comment by slashpai** [comment]
It will have to wait for 2.45 release?

**Comment by dmitriishaburov** [comment]
Just curious about https://github.com/prometheus-operator/prometheus-operator/pull/5646 - isn't it duplicating existing `enforcedSampleLimit/enforcedTargetLimit/enforcedLabelLimit/etc` field in Prometheus?

Would be kinda confusing to have 2 options that do effectively same job

**Comment by simonpasquier** [comment]
@dmitriishaburov AFAIU there are not exactly doing the same thing. From the Prometheus PR

> When scrape configs do not set these parameters, they get the default from the global config instead. Conversely, if a scrape config sets one of these limits, it will override the global one.

So you can have a scrape config with `sample_limit: 1000` and a global  `sample_limit: 500`.

On the other side, `.spec.enforcedSampleLimit`   ensures that all targets will have `sample_limit`  no greater than this value. E.g. if a ServiceMonitor says 1000 and the enforced limit says  500 then the final config will be `sample_limit: 500`.

And if you specify `.spec.enforcedSampleLimit`, there is probably no reason to set the new `.spec.sampleLimit` field at the same time: the enforced limit will always apply. The hard part is going to convey these subtleties in the docs...
