### ISSUE TITLE
Common Metric Relabeling for all the jobs in a cluster

### ISSUE THREAD

**Issue by mrajkumar21** [prometheus-operator/prometheus-operator#5643]
Hello,
Is it possible to add a common label to all the metrics in a cluster globally instead of editing each service monitor?

We have tried adding external labels, but the label is visible only on Alertmanager metrics, but we need it on Prometheus metrics too.
We really want it to be set on the TSDB timeseries itself 

EXPECTED:
E.g.: I want to add a label like "clustername", so instead of configuring this label in all servicemonitors

**Comment by mrajkumar21** [comment]
Hi Simon,

If I add the externalLabels in the kind:Prometheus, the label is visible only in alertmanager metrics and not in Prometheus.
I have attached the screenshot for your reference,


I have added ,

externalLabels:
    tclcluster: centos1-26

tclcluster label is visible in alertmanager and not there in Proemtheus.
Any way to have it globally at the Prometheus level?
![alertmanager](https://github.com/prometheus-operator/prometheus-operator/assets/91721176/34c6ef7a-e8bc-4582-8b7a-45c938ed92c9)
![PromUI](https://github.com/prometheus-operator/prometheus-operator/assets/91721176/9aa55037-b1df-4c98-acc8-164df41bc48d)

**Comment by simonpasquier** [comment]
My question really is: why do you want the labels to be present in Prometheus?

**Comment by stringang** [comment]
@simonpasquier 
`externalLabels` are only used to identify Prometheus instances and interact with external systems(federation, remote storage, Alertmanager), and they are not stored in the time series data?

**Comment by simonpasquier** [comment]
@stringang yes

**Comment by klinch0** [comment]
> My question really is: why do you want the labels to be present in Prometheus?

i want monitor my k8s cluster via servicemonitors and label they like:

env: infra



with external labels i can label only another clusters like:

env: dmz


i need

**Comment by nicolastakashi** [comment]
@klinch0 can you explain a little bit.
I didn't understand why you can't use externalLabels. 😄
