### ISSUE TITLE
Is there a way to dump the rules.yml generated by the operator for PrometheusRule CRDs ?

### ISSUE THREAD

**Issue by achetronic** [prometheus-operator/prometheus-operator#5645]
I was looking for a way to dump rules.yaml generated by the operator after parsing PrometheusRules. I saw that this is only dumped into a configmap when the Ruler is deployed, but i'm looking for something small (cli, or golang library and i will craft the CLI with it) that is able to do it. 

The intention is to know if there is a flag or something we can enable to get it. If not, the the intention is to do a controller to read the PrometheusRule CRs from the cluster and parse it to get this configmap, may be with a golang package or something. I haven't found anything already half done yet

Thank you in advance

**Comment by simonpasquier** [comment]
Nothing like this exists right now (at least i don't know about it). You should be able to use the existing code to build something similar.
Note that the operator may create multiple configmaps depending on how many PrometheusRule objects it needs to reconcile.

**Comment by achetronic** [comment]
> Nothing like this exists right now (at least i don't know about it). You should be able to use the existing code to build something similar.
> Note that the operator may create multiple configmaps depending on how many PrometheusRule objects it needs to reconcile.

Hey! , thank you for the answer. I needed to solve this for Grafana Mimir, so I will write here some workarounds just in case some people is looking for it 🙏🏻

I finally solved this using Grafana Agent only to detect PrometheusRules and upload them to it. 
[Here it is the documentation](https://grafana.com/docs/agent/latest/flow/reference/components/mimir.rules.kubernetes/)

Moreover, the config for Alertmanager on Mimir can be solved with a single ConfigMap with two keys, alertmanager.yaml and templates.yaml with the content you need. Mount them into a CronJobs pod with `mimirtool` Docker image that periodically upload the content to the `/alertmanager` endpoint in the gateway component
