### ISSUE TITLE
Incorrect year in releases

### ISSUE THREAD

**Issue by solomonty** [prometheus-operator/prometheus-operator#5654]
The year is 2022 instead of 2023 in the recent releases

https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.65.0

https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.65.1

https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.65.2

**Comment by slashpai** [comment]
I am not sure if we can edit this
@philipgough will we able to edit date? Also in changelog as well

**Comment by simonpasquier** [comment]
Thanks for the heads-up! I've fixed the release pages but we need to fix the CHANGELOG.md (ideally in the release-0.65 branch then merge back to main).

**Comment by philipgough** [comment]
oops, that was quiet an oversight...thanks Simon I'll take care of the PR

**Comment by xiu** [comment]
#5655 merged, now it just needs to be merged back to master :+1:

**Comment by slashpai** [comment]
This is fixed, merged back to main https://github.com/prometheus-operator/prometheus-operator/pull/5656
