### ISSUE TITLE
Ability to inject the shard number as an external label

### ISSUE THREAD

**Issue by EStork09** [prometheus-operator/prometheus-operator#5660]
**What did you do?**
Trying to differentiate between replicas on shards.

**Did you expect to see some different?**
I don't see any ways to get just the replica number as an external label

**Question**
Is there a way to get the number of the replica, so in #4621 it was requested to get the shard number, but is there a way to determine which replica it is part of? I currently have 3 shards and plan to bump to multiple replicas, rather than having a unique replica name for each one, is there a way to apply to each shard the replica number it belongs to rather than the name of the pod/replica itself?

If this doesn't exist I can open a feature request.

**Comment by simonpasquier** [comment]
Can you share more details about why you need the replica number?

**Comment by EStork09** [comment]
I am trying to remote write to a mimir instance, it doesn't seem to understand the idea of sharding. So if I use the default prometheus_replica label to do the HA handling, it will only take 1 shard and ignores all of the others. But if they all had a label to show which replica they belong to, it should just let it through. I am mainly just curious if that is even an option. I am also asking on the mimir side to see if they have a way to even handle this since sharding isn't exactly bleeding edge at this point.

**Comment by simonpasquier** [comment]
IIUC your requirement, you could do this with Prometheus operator:

```
metadata:
  name: foo
  namespace: default
spec:
  externalLabels:
    shard: "shard-$(SHARD)"
  replicas: 2
  shards: 2
```

In addition to the `prometheus="default/foo"` external label which applies to all, the different pods would end up with:

* prometheus-foo-0 => `shard="shard-0",prometheus_replica="prometheus-foo-0"`
* prometheus-foo-1 => `shard="shard-0",prometheus_replica="prometheus-foo-1"`
* prometheus-foo-shard-1-0 => `shard="shard-1",prometheus_replica="prometheus-foo-shard-1-0"`
* prometheus-foo-shard-1-1 => `shard="shard-1",prometheus_replica="prometheus-foo-shard-1-1"`

**Comment by simonpasquier** [comment]
you might also be able to use `remoteWriteRelabelings` to extract the shard id from the `prometheus_replica` external label? But it would probably be more convoluted.

**Comment by EStork09** [comment]
That's true but might get pretty expensive. I just combined the cluster label and the `$(SHARD)`, I would prefer if there was a way to only have the replica number, as it is a bit cleaner, but this works for me to move forward.
Basically this:
```
cluster="foo",ha_cluster="foo-0",prometheus_replica="prometheus-0"
cluster="foo",ha_cluster="foo-1",prometheus_replica="prometheus-shard-0-1"
cluster="foo",ha_cluster="foo-0",prometheus_replica="prometheus-1"
cluster="foo",ha_cluster="foo-1",prometheus_replica="prometheus-shard-1-1"
```

Thanks for your help on this!

**Comment by simonpasquier** [comment]
Reopening the issue as this is the second time that the request comes up (see #4621). I'm not sure if we need to expose a new field in the CRD for it but it should at least be documented.

**Comment by simonpasquier** [comment]
@EStork09 for posterity can you share the code snippet that you've used? It could help future users having the same question :)

**Comment by EStork09** [comment]
Sorry about that, here is our config for the prometheus operator:
```
prometheus:
  prometheusSpec:
    externalLabels:
      cluster: foo
      mimir_ha: foo-$(SHARD)
 ```
 And on the Mimir side to capture that with the HA Tracker:
 ```
limits:
  accept_ha_samples: true
  ha_replica_label: prometheus_replica
  ha_cluster_label: mimir_ha
```

**Comment by dipeti** [comment]
This should be documented as well - extremely useful feature.  Thanks for asking EStork09

**Comment by nicolastakashi** [comment]
Could this Prometheus feature help with this requirement? https://prometheus.io/docs/prometheus/latest/feature_flags/#expand-environment-variables-in-external-labels
