### ISSUE TITLE
Missing reload, after alertmanager template has been changed.

### ISSUE THREAD

**Issue by jkroepke** [prometheus-operator/prometheus-operator#5708]
**What happened?**

Since #3647, it is possible to store template on the alertmanager config secret. I have to upgrade the templates, nothing happends.

**Did you expect to see something different?**

I would expect a config reload.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the guide

https://github.com/prometheus-operator/prometheus-operator/blob/c840b7eaa857fc45f8a9be52cfd8d315f7c88e9f/Documentation/user-guides/alerting.md#using-a-kubernetes-secret

and manage the Altermanager trough an Kubernetes Secret. After apply the config, modify the template inside the Kubernetes secret and reapply the diff. 

**Environment**

* Prometheus Operator version:

  `v0.65.2`

* Kubernetes version information:

    `Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/arm64"}`
    

* Kubernetes cluster kind:

minikube

**Comment by l646505418** [comment]
hi @simonpasquier ，I am interested in this issue and can  work on it

**Comment by jkroepke** [comment]
feel free to start @l646505418

**Comment by l646505418** [comment]
@jkroepke  Hi, would mind telling me how to reproduce this issue? Because I tried to modify the alertmanage.yml in Kubernetes secrets by dashboard, I can see the alertmanager.yaml under  path: /etc/alertmanager/config/ of pod is updated too

**Comment by jkroepke** [comment]
If you read https://github.com/prometheus-operator/prometheus-operator/blob/c840b7eaa857fc45f8a9be52cfd8d315f7c88e9f/Documentation/user-guides/alerting.md#using-a-kubernetes-secret, you can store templates on the secret, too, e.g.: `template_1.tmpl`

Modify the templates would not result into a reload.

**Comment by l646505418** [comment]
> If you read https://github.com/prometheus-operator/prometheus-operator/blob/c840b7eaa857fc45f8a9be52cfd8d315f7c88e9f/Documentation/user-guides/alerting.md#using-a-kubernetes-secret, you can store templates on the secret, too, e.g.: `template_1.tmpl`
> 
> Modify the templates would not result into a reload.

I also tried modify the templates by secrets by Kubernets dashboard, it will reload, but sometimes will cost some time

**Comment by jkroepke** [comment]
The template file is updated, but the alertmanager did not get an reload signal to use the new templates.

**Comment by l646505418** [comment]
> The template file is updated, but the alertmanager did not get an reload signal to use the new templates.
> 
> The reloader sidecar will do nothing, if there is a new template.

oh I get it.😂

**Comment by jkroepke** [comment]
@l646505418 I did not looked deeper into it, but maybe the reloader support this case already. However the given flag is missing.

**Comment by l646505418** [comment]
> @l646505418 I did not looked deeper into it, but maybe the reloader support this case already. However the given flag is missing.

According to this blog: [https://prometheus.io/blog/2016/03/03/custom-alertmanager-templates/](url), seems the config-reloader will update the template file(now the promethus provides API:`/-/reload` to reload the config)

**Comment by jkroepke** [comment]
Thats exactly the bug, since it didn't happend.

**Comment by l646505418** [comment]
#5727
