### ISSUE TITLE
Endpoint.BearerTokenSecret must be pointer

### ISSUE THREAD

**Issue by setood** [prometheus-operator/prometheus-operator#5713]
Endpoint.BearerTokenSecret must be pointer:
https://github.com/prometheus-operator/prometheus-operator/blob/c840b7eaa857fc45f8a9be52cfd8d315f7c88e9f/pkg/apis/monitoring/v1/types.go#L396-L399

like in other places:
https://github.com/prometheus-operator/prometheus-operator/blob/c840b7eaa857fc45f8a9be52cfd8d315f7c88e9f/pkg/apis/monitoring/v1beta1/alertmanager_config_types.go#L556

I ran into this problem when I tried to create a servicemonitor with [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder), a BearerTokenSecret added in it and that cannot be removed.

my code is like that:
```go
import monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"

var monitor *monitoringv1.ServiceMonitor
k8sClient.Create(ctx, monitor);
```

**Comment by heliapb** [comment]
Hi @ArthurSens I would like to work on this one, could you please assign to me

**Comment by slashpai** [comment]
@heliapb Go ahead :)

**Comment by slashpai** [comment]
Completed in https://github.com/prometheus-operator/prometheus-operator/pull/5752
