### ISSUE TITLE
AlertManager to send plain text email needs html to be set to empty

### ISSUE THREAD

**Issue by sstarcher** [prometheus-operator/prometheus-operator#5718]
**What happened?**

Configured AlertManager to have `html: ''` to an empty string, but that configuration gets dropped by the time it gets to `alertmanager.env.yaml`.  The secret contains `html: ''`, but as it's processed that empty string gets dropped out and ends up getting the default which is invalid `html: '{{ template "email.default.html" . }}'`.

https://github.com/prometheus/alertmanager/issues/2374`

**Did you expect to see something different?**

I expected `html: ''` to be retained

**How to reproduce it (as minimally and precisely as possible)**:

Configure a receiver for email and set `html` to an empty string.

```
- name: receiver
  email_configs:
  - html: ''
    text: bob
```

* Prometheus Operator version:
    Image:      quay.io/prometheus-operator/prometheus-operator:v0.65.1

* Kubernetes version information:

v1.25.9

* Kubernetes cluster kind:

EKS

**Comment by devopstales** [comment]
You can override the html template with plain text too:
 ```
    html: 'You have the following alerts: {{ .CommonLabels.alertname }} in {{ .CommonLabels.namespace }}'
 ```

**Comment by sstarcher** [comment]
I believe the email will still contain html metadata, but I'll give that a try.

**Comment by gitdou8679** [comment]
Hello, 

Because it seems to have mandatory text/html send in the email : 

My first question and attempt : 
for html: how do you pass carriage return ? 
I tried some <div> and some <br> but its show it in one line with the div and br on Gmail

My solution few minutes after : 

In the receiver config : 
```
  receivers:
[...]
      emailConfigs:
[...]
          html: |
            {{ .CommonLabels.CUSTOMMESSAGE | safeHtml }}
```

In the rule, put a labels or annotations : 
```
        CUSTOMMESSAGE: |
          Hello,<br>
          This is a message with carriage returns
```
