### ISSUE TITLE
Improve Thanos Documentation

### ISSUE THREAD

**Issue by heliapb** [prometheus-operator/prometheus-operator#5722]
**What is missing?**

On the Thanos Ruler documentation we are missing examples for [Thanos Ruler](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/thanos.md#thanos-ruler) setup with Alertmanager. Considering is one of the major integrations with Ruler it would be beneficial for the community to have and example - for me personalty it took a bit of digging to figure it out as it was the first time using Ruler

**Why do we need it?**
To prove an example how to use it for the community. 

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:
Glad to help with this one

**Comment by simonpasquier** [comment]
>  Glad to help with this one

Feel free to go ahead! It is very much welcomed :)

**Comment by heliapb** [comment]
Hi @simonpasquier will pick this one up, thanks
