### ISSUE TITLE
Implement golden files for test assertion

### ISSUE THREAD

**Issue by nicolastakashi** [prometheus-operator/prometheus-operator#5724]
**What is missing?**

As we discussed in Office Hours on July 3rd we're going to implement the golden files strategy to improve the tests' readability as well as maintainability. 

This is an aggregator issue to track the progress of the required changes linked down below.

- [x] #5738 
- [x] #5739
- [x] #5740
- [x] #5741

**Why do we need it?**

- Improve tests maintainability
- Improve tests the readability

**Environment** N/A

* Prometheus Operator version: N/A

    
    

**Anything else we need to know?**: N/A

** References **

- [Testing in Go: Golden Files](https://ieftimov.com/posts/testing-in-go-golden-files/)
- [Golden - Go Package](https://pkg.go.dev/gotest.tools/v3/golden)

**Comment by philipgough** [comment]
@nicolastakashi are we good to close this one now?

**Comment by slashpai** [comment]
I think we still have tests for which we haven't implemented golden files we would need to add them in task lists
