### ISSUE TITLE
Adding the remote_write configuration for prometheus cannot be manually or automatically added

### ISSUE THREAD

**Issue by hunterlijunchen** [prometheus-operator/prometheus-operator#5736]
**What is missing?**

**Why do we need it?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:

**Comment by slashpai** [comment]
Can you explain the issue?

**Comment by slashpai** [comment]
Closing this one please reopen/open new one with issue description :)
