### ISSUE TITLE
Implement golden files for test assertion - Admission package

### ISSUE THREAD

**Issue by nicolastakashi** [prometheus-operator/prometheus-operator#5738]
**What is missing?**

As described in the main issue #5724 we should implement the golden files strategy to improve the tests' readability as well as maintainability.

**Why do we need it?**

- Improve tests maintainability
- Improve tests the readability

**Environment**

* Prometheus Operator version: N/A

**Anything else we need to know?**:

**Comment by ArthurSens** [comment]
fixed by https://github.com/prometheus-operator/prometheus-operator/pull/5785
