### ISSUE TITLE
Render bundle.yaml without `namespace: default`

### ISSUE THREAD

**Issue by laurivosandi** [prometheus-operator/prometheus-operator#5751]
**What happened?**

Tried to deploy Prometheus operator from released bundle.yaml https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.66.0/bundle.yaml into namespace `prometheus-operator`

**Did you expect to see something different?**

Manifest contains `namespace: default` so it's not possible to deploy it to `prometheus-operator` namespace

**How to reproduce it (as minimally and precisely as possible)**:

```
wget https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.66.0/bundle.yaml
kubectl apply -n prometheus-operator -f bundle.yaml
```

**Anything else we need to know?**:

Please remove `namespace: default` from rendered manifests so it can be deployed to other namespaces

**Comment by ArthurSens** [comment]
Can you use `sed` to rewrite the namespace?

**Comment by slashpai** [comment]
IIUC the error is from ClusterRoleBinding. As noted in [quickstart](https://github.com/prometheus-operator/prometheus-operator#quickstart) make sure to adapt the namespace in the ClusterRoleBinding if deploying in a namespace other than the default namespace.
