### ISSUE TITLE
Add basic auth to Prometheus and Alertmanager web pages

### ISSUE THREAD

**Issue by BrucePeng92** [prometheus-operator/prometheus-operator#5765]
**What did you do?**
I have reviewed the documentation for Prometheus and configured the web_ Config can add basic authentication
**Did you expect to see some different?**
I couldn't find where to modify the operator's CRD
**Environment**
prometheus-operator:v0.57.0
k8s version:1.24.13
* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by slashpai** [comment]
There is an issue already logged for this https://github.com/prometheus-operator/prometheus-operator/issues/4200 and 
draft PR for same https://github.com/prometheus-operator/prometheus-operator/pull/4942
