### ISSUE TITLE
Add msteams configuration to Alertmanager Config CRD

### ISSUE THREAD

**Issue by rgarcia89** [prometheus-operator/prometheus-operator#5766]
**What is missing?**
Microsoft Teams has been officially added to the Alertmanager via https://github.com/prometheus/alertmanager/pull/3324.
The configuration section for this needs to be added to the CRD now.

**Why do we need it?**
In order to make the msteams receiver configurable

* Prometheus Operator version:

    `prometheus-operator:v0.66.0`

**Comment by rgarcia89** [comment]
Seems like the next alertmanager release will include the msteams integration. Would be awesome if we could get the CRD update close to the final release. 

https://github.com/prometheus/alertmanager/releases/tag/v0.26.0-rc.0

**Comment by rgarcia89** [comment]
And there it is https://github.com/prometheus/alertmanager/releases/tag/v0.26.0 🎉

**Comment by nickyfoster** [comment]
Was CRD actually updated with msteams integration? I'm not able to find it.
