### ISSUE TITLE
Expose /metrics/cadvisor endpoint as a kubernetes service

### ISSUE THREAD

**Issue by Skybladev2** [prometheus-operator/prometheus-operator#5777]
Hello,

I need to expose `/metrics/cadvisor` endpoint to external monitoring tool (in this particular case, Zabbix agent running on a host).
However, this endpoint is protected with authentication, which works just fine in conjunction with adjacent prometheus and grafana deployment.

**What did you do?**
* Get an info about endpoint:
![image](https://github.com/prometheus-operator/prometheus-operator/assets/548735/7a076e0f-cfff-4dba-9342-3e98a6244652)

* From the shell of adjacent pod in random namespace make a curl request, got `Forbidden (user=system:serviceaccount:dev:default, verb=get, resource=nodes, subresource=metrics)`:
```
bash-5.1# curl -k -i -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://10.126.xx.xx:10250/metrics/cadvisor

HTTP/2 403
content-type: text/plain; charset=utf-8
content-length: 97
date: Sat, 29 Jul 2023 06:29:05 GMT

Forbidden (user=system:serviceaccount:dev:default, verb=get, resource=nodes, subresource=metrics)
```
Curling operator endpoint with the same path gives 404:
![image](https://github.com/prometheus-operator/prometheus-operator/assets/548735/ac50226b-9251-4a26-8fa0-e60b212611e5)

```
bash-5.1# curl -k -i -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://192.168.xx.xx:10250/metrics/cadvisor

HTTP/2 404
content-length: 0
date: Sat, 29 Jul 2023 06:32:28 GMT
```

However curling `/metrics` gives a response:
```
bash-5.1# curl -k -i -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://192.168.xx.xx:10250/metrics
HTTP/2 200
content-type: text/plain; version=0.0.4; charset=utf-8
date: Sat, 29 Jul 2023 06:35:52 GMT

# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 6.7193e-05
go_gc_duration_seconds{quantile="0.25"} 9.3294e-05
...
```

**Did you expect to see some different?**

I expected to see metrics at `https://10.126.xx.xx:10250/metrics/cadvisor` similar to curling `/metrics` prometheus endpoint which contains `container_oom_events_total` metric.

**Environment**

* Prometheus Operator version:

`quay.io/prometheus-operator/prometheus-operator:v0.61.1`

* Kubernetes version information:

```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:18:48Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

OpenShift deployed with kubespray

* Manifests:

N/A

* Prometheus Operator Logs:

N/A

**Anything else we need to know?**:

**Comment by slashpai** [comment]
0.67(latest version) has support for k8s node monitoring https://github.com/prometheus-operator/prometheus-operator/pull/5675. Is that something you are looking for?

**Comment by Skybladev2** [comment]
@slashpai Looks like it!
But I don't understand how to use it.
Are there any docs for this feature?

**Comment by slashpai** [comment]
There is an example in PR description :)

**Comment by Skybladev2** [comment]
> There is an example in PR description :)

Okay, thanks :)
Still need some context - what will be the endpoint for the cadvisor metrics in this case so I can feed this address to a monitoring agent?
