### ISSUE TITLE
Unable to configure pod anti-affinity with requiredDuringSchedulingIgnoredDuringExecution

### ISSUE THREAD

**Issue by HarshitaJha** [prometheus-operator/prometheus-operator#5782]
I am unable to configure prometheus operator with "requiredDuringSchedulingIgnoredDuringExecution". I tried the config below -
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              operator.prometheus.io/shard: "0"
          topologyKey: kubernetes.io/hostname
        weight: 100
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              operator.prometheus.io/shard: "1"
          topologyKey: kubernetes.io/hostname
        weight: 100
 
I even tried the above by keeping just one podAffinityTerm. That also didn't work. It said "error: prometheuses.monitoring.coreos.com "prometheus" is invalid". 
In the file, it showed this error- "* spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Required value
* spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[1].topologyKey: Required value"

The goal is to deploy prometheus with hard-affinity between replicas of the same shard (to ensure that replicas are never on the same worker node).

Image- quay.io/prometheus-operator/prometheus-operator:v0.58.0
Kubernetes version -v1.24.9

**Comment by slashpai** [comment]
Hello 👋🏻 

Could you please provide [more details](https://github.com/prometheus-operator/prometheus-operator/blob/main/.github/ISSUE_TEMPLATE/bug.md) that will be troubleshooting issue better :)

**Comment by HarshitaJha** [comment]
Hi. 
I think I have provided all necessary details to reproduce the issue. Let me repeat the same.

Basically, I am not able to set hard-affinity, i.e. "requiredDuringSchedulingIgnoredDuringExecution" in the prometheus-operator configuration. The configuration provided above is working if I change it to "preferredDuringSchedulingIgnoredDuringExecution".

Since I was making the change by editing the prometheus crd on a running cluster, it did not allow me to save the file and threw this error -
 It said "error: prometheuses.monitoring.coreos.com "prometheus" is invalid".
In the file, it showed this error- "* spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Required value

spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[1].topologyKey: Required value".

Image- quay.io/prometheus-operator/prometheus-operator:v0.58.0
Kubernetes version -v1.24.9

**Comment by simonpasquier** [comment]
This is because [requiredDuringSchedulingIgnoredDuringExecution](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#nodeselector-v1-core) and [preferredDuringSchedulingIgnoredDuringExecution](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#preferredschedulingterm-v1-core) fields don't have the same structure.
