### ISSUE TITLE
AzureAD remote write authentication support

### ISSUE THREAD

**Issue by MadsHT** [prometheus-operator/prometheus-operator#5783]
**What is missing?**

In [Prometheus v.2.45.0](https://github.com/prometheus/prometheus/releases/tag/v2.45.0) the `azuread` authentication method for remote write was introduced from [prometheus/prometheus#11944](https://github.com/prometheus/prometheus/pull/11944) and skimming through the crd and code it does not seem like either of those supports this ned `azuread` property.

**Why do we need it?**

We need it to simplify the process of remote writing metrics to our Azure monitor workspace.

**Environment**

* Prometheus Operator version:

    ![billede](https://github.com/prometheus-operator/prometheus-operator/assets/31923273/9a6a8230-e429-4d61-bfeb-c9be16f1d442)
    
    

**Anything else we need to know?**:

**Comment by heylongdacoder** [comment]
Hi @MadsHT, we need your opinion about this(https://github.com/prometheus-operator/prometheus-operator/pull/5852#discussion_r1308473369). 😄

**Comment by MadsHT** [comment]
@heylongdacoder Sorry for not replying, work and life got in the way, Awesome that you guys looked at this, and got it through! :D
