### ISSUE TITLE
Allow Additional Scrape Config in different Namespace

### ISSUE THREAD

**Issue by rgarcia89** [prometheus-operator/prometheus-operator#5786]
**What is missing?**
Scrape Config installation in different namespace then the one Prometheus is deployed

**Why do we need it?**
In my setup we are providing teams a prometheus stack on their clusters based on kube-prometheus. So far we are fine with the functions since users can create rules, probes and the alertmanager config in their namespaces. The namespace in which the prometheus stack resides is only available in read mode. So they cannot deploy anything into it. I have two teams however which would like to add additional scrape endpoints, which are located outside of the cluster, to the prometheus configuration. Unfortunately this is according to the following documentation only possible when deploying the additional scrape config to the same namespace in which prometheus is deployed. 

https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/additional-scrape-config.md

**Environment**

* Prometheus Operator version:

    `prometheus-operator:v0.66.0`
    
    

**Anything else we need to know?**:

**Comment by slashpai** [comment]
ScrapeConfig CRD is for this usecase https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1alpha1.ScrapeConfig :)

**Comment by rgarcia89** [comment]
Oh sorry guys this kind is new to me.
Thanks for the heads up :)
