### ISSUE TITLE
Malformed service URL when using ClusterDomain

### ISSUE THREAD

**Issue by vladimir-cich** [prometheus-operator/prometheus-operator#5799]
https://github.com/prometheus-operator/prometheus-operator/blob/3f7882c4dee8627e8581c81c2631aa84a78146d9/pkg/alertmanager/statefulset.go#L384C36-L384C49

`if config.ClusterDomain != "" {
		clusterPeerDomain = fmt.Sprintf("%s.%s.svc.%s.", governingServiceName, a.Namespace, config.ClusterDomain)
	} else {
		// The default DNS search path is .svc.<cluster domain>
		clusterPeerDomain = governingServiceName
	}`

Last comma shouldn't be there, because now it's creating malformed service url 

`alertmanager-rancher-monitoring-alertmanager-0.alertmanager-operated.cattle-monitoring-system.svc.cluster.local.:9094`

**Comment by simonpasquier** [comment]
AFAICT it was meant to be this way
https://github.com/prometheus-operator/prometheus-operator/issues/2934
https://github.com/prometheus-operator/prometheus-operator/pull/3138

**Comment by vladimir-cich** [comment]
Okay, I understand now.
