### ISSUE TITLE
Add support for metricRelabelings in ScrapeConfig

### ISSUE THREAD

**Issue by alexandrevilain** [prometheus-operator/prometheus-operator#5828]
**What is missing?**

Current ScrapeConfig API doesn't provide a way to apply relabel config to samples before ingestion. 
It's supported by prometheus using the `metric_relabel_configs` parameter.  Other CRDs like PodMonitor, ServiceMonitor and Probe are providing this feature with the `metricRelabelings` key.

**Why do we need it?**

When using ScrapeConfig user may need to apply relabel config to samples before ingestion.

**Environment**

* Prometheus Operator version: v0.66.0

**Anything else we need to know?**:

I'll provide a pull request to fix this.

**Comment by slashpai** [comment]
There is already an issue https://github.com/prometheus-operator/prometheus-operator/issues/5803 and fix PR open https://github.com/prometheus-operator/prometheus-operator/pull/5805 for this

**Comment by alexandrevilain** [comment]
Oh sorry @slashpai, I close both issue and PR!
