### ISSUE TITLE
Root directory of new persistent storage created with wrong permissions

### ISSUE THREAD

**Issue by mnlipp** [prometheus-operator/prometheus-operator#5833]
When using unusual StorageClasses for Prometheus storage, such as NFS or Rook-CephFS, it is required that Prometheus runs with a different `fsGroup`.

The [documentation](https://prometheus-operator.dev/docs/operator/storage/) for it could be clearer

**Comment by ArthurSens** [comment]
Actually the original issue has more information, so closing in favor of https://github.com/prometheus-operator/prometheus-operator/issues/5354#issuecomment-1689833229
