### ISSUE TITLE
Error: INSTALLATION FAILED: template: ack-prometheus-operator/templates/prometheus/rules/prometheus.rules.yaml:7:12: executing "ack-prometheus-operator/templates/prometheus/rules/prometheus.rules.yaml" at <semverCompare ">=1.10.0-0" $kubeTargetVersion>: error calling semverCompare: Invalid Semantic Version

### ISSUE THREAD

**Issue by sswolf** [prometheus-operator/prometheus-operator#5838]
I encountered an error while trying to install ack-prometheus-operator using ACK Kubernetes version 1.22.15 and Helm version 3.7. 

helm cmd:helm install ack-prometheus-operator -n monitoring  ./ack-prometheus-operator
Error: INSTALLATION FAILED: template: ack-prometheus-operator/templates/prometheus/rules/prometheus.rules.yaml:7:12: executing "ack-prometheus-operator/templates/prometheus/rules/prometheus.rules.yaml" at <semverCompare ">=1.10.0-0" $kubeTargetVersion>: error calling semverCompare: Invalid Semantic Version
chart download:https://aliacs-app-catalog.oss-cn-hangzhou.aliyuncs.com/charts-incubator/ack-prometheus-operator-12.0.0.tgz

**Comment by slashpai** [comment]
👋🏻  For helm chart issues log issue at https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack.

But looking at error looks like version format passed is wrong 🤔

**Comment by sswolf** [comment]
> 👋🏻 For helm chart issues log issue at https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack.
> 
> But looking at error looks like version format passed is wrong 🤔

The issue has been resolved, and the reason was that during the deployment using the 'ack' command-line tool, the 'kubeTargetVersionOverride' couldn't be correctly retrieved for the ACK Kubernetes version.
