### ISSUE TITLE
Add support for metric_relabel_configs to ScrapeConfig CRD

### ISSUE THREAD

**Issue by tapwaterbuffalo** [prometheus-operator/prometheus-operator#5845]
**What is missing?**
ScrapeConfig CRD current supports Prometheeus  [relabel_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) via the `relabelings` element but does not support [metric_relabel_configs](
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs) 

**Why do we need it?**
feature parity with prometheus configuration. 
metric_relabel_configs happen post-scrape and are needed in some cases to mutate or drop the metric
**Environment**
n/a
* Prometheus Operator version:
0.67.1
    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:

**Comment by slashpai** [comment]
already a PR https://github.com/prometheus-operator/prometheus-operator/pull/5805 is opened to address this
