### ISSUE TITLE
The scrapeconfig.md documentation has a typo

### ISSUE THREAD

**Issue by zhuqifu** [prometheus-operator/prometheus-operator#5853]
The scrapeconfig.md documentation has a typo

document_url: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/scrapeconfig.md#static_config

commit: e866557

As shown below
![image](https://github.com/prometheus-operator/prometheus-operator/assets/73975755/708edebc-1299-4d78-b7b7-27ae09fac754)

should be"apiVersion: monitoring.coreos.com/v1alpha1"
![image](https://github.com/prometheus-operator/prometheus-operator/assets/73975755/2b496771-3a78-4e7b-acf5-2b8ba4de5c69)

**Comment by slashpai** [comment]
Fixed in https://github.com/prometheus-operator/prometheus-operator/pull/5854
