### ISSUE TITLE
[alertmanager] webhook url_file parameter is missing

### ISSUE THREAD

**Issue by HaveFun83** [prometheus-operator/prometheus-operator#5857]
**What is missing?**

Since alertmanager v0.26.x is it possible to load an webhook url via `url_file`  https://github.com/prometheus/alertmanager/pull/3223

But it looks like the current prometheus-operator don't support it yet:

```
level=error ts=2023-08-28T15:42:18.393763099Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="sync \"monitoring-system/cluster\" failed: provision alertmanager configuration: failed to initialize from secret: yaml: unmarshal errors:\n  line 70: field url_file not found in type config.plain"
```

**Why do we need it?**

Allow a webhook url via secret

**Environment**

* Prometheus Operator version:

    `v0.67.1`
    
    

**Anything else we need to know?**:

If someone only have to add the new parameter 
```
URLFile string          `yaml:"url_file,omitempty" json:"url_file,omitempty"`
```
[here](https://github.com/prometheus-operator/prometheus-operator/blob/v0.67.1/pkg/alertmanager/types.go#L114)? 
I could also take over this. Just let me know

**Comment by heliochronix** [comment]
I've ran into the same issue, only for pushover `user_key_file` and `token_file`. Both are supported by alertmanager 0.26.x, which I am running, but prometheus-operator is rejecting the rules.

**Comment by slashpai** [comment]
@HaveFun83 Please feel free to work on the issue :)
