### ISSUE TITLE
Support `device`, `user_key_file` and `token_file` for Pushover integration

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#5859]
**What is missing?**

https://github.com/prometheus/alertmanager/pull/3200
https://github.com/prometheus/alertmanager/pull/3318

- [ ] Add to https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/alertmanager/types.go
- [ ] Add to https://github.com/prometheus-operator/prometheus-operator/tree/main/pkg/apis/monitoring/v1alpha1 and https://github.com/prometheus-operator/prometheus-operator/tree/main/pkg/apis/monitoring/v1beta1

**Why do we need it?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:

**Comment by ArthurSens** [comment]
https://github.com/prometheus-operator/prometheus-operator/pull/5479 is implementing Device support :)

**Comment by dongjiang1989** [comment]
#5886 is also implemented  `user_key_file` and `token_file` support.
