### ISSUE TITLE
Performance of  prometheus-operator

### ISSUE THREAD

**Issue by Ultrafenrir** [prometheus-operator/prometheus-operator#5889]
I'm running prometheus-operator installation that operate 70 prometheus instances, I would say after 30-40 it becomes way to slow. It take around 30-40 minutes to operator create new instance after deploy occur. Is there a way to speedup that process for large installations ? 

* Prometheus Operator version:
v0.63.0

* Kubernetes version information:

v1.19.7

* Kubernetes cluster kind:
   RKE

**Comment by simonpasquier** [comment]
First thing to try is to use the latest stable version of the operator (v0.67.1) and with a more recent version of Kubernetes (v1.19 is rather old).

**Comment by Ultrafenrir** [comment]
Hi @simonpasquier , thank you for fast response. Is there other tips except upgrading versions ? Because I don't believe it will help that much.

**Comment by simonpasquier** [comment]
no
