### ISSUE TITLE
Operator Life Cycle Manager: Prometheus Operator Install Fails: file monitoring.coreos.com_prometheusagents.yaml bigger than total allowed limit

### ISSUE THREAD

**Issue by Noah-Huppert** [prometheus-operator/prometheus-operator#5918]
**What happened?**
When using Operator Lifecycle Manager to install the operator from operatorhub.io https://operatorhub.io/operator/prometheus

I encountered the error:

```
time="2023-09-15T03:10:56Z" level=info msg="Using in-cluster kube client config"
time="2023-09-15T03:10:56Z" level=info msg="Reading file" file=/bundle/manifests/monitoring.coreos.com_alertmanagerconfigs.yaml
time="2023-09-15T03:10:56Z" level=info msg="Reading file" file=/bundle/manifests/monitoring.coreos.com_alertmanagers.yaml
time="2023-09-15T03:10:56Z" level=info msg="Reading file" file=/bundle/manifests/monitoring.coreos.com_podmonitors.yaml
time="2023-09-15T03:10:56Z" level=info msg="Reading file" file=/bundle/manifests/monitoring.coreos.com_probes.yaml
time="2023-09-15T03:10:56Z" level=info msg="Reading file" file=/bundle/manifests/monitoring.coreos.com_prometheusagents.yaml
time="2023-09-15T03:10:56Z" level=error msg="File with size 490794 exceeded 1048576 limit, aboring" file=/bundle/manifests/monitoring.coreos.com_prometheusagents.yaml
Error: error loading manifests from directory: file monitoring.coreos.com_prometheusagents.yaml bigger than total allowed limit
```

This indicates that the `monitoring.coreos.com_prometheusagents.yaml`  file was 490794 and exceeded the 1048576 limit. I'm assuming this might be referring to a character count?

**Did you expect to see something different?**
The operator should have installed if it was listed on operatorhub.io

**How to reproduce it (as minimally and precisely as possible)**:
Follow install instructions on https://operatorhub.io/operator/prometheus

**Environment**

DigitalOcean Kubernetes using Operator Lifecycle Manager

* Prometheus Operator version:
   v0.65.1

* Kubernetes version information:
   ```
   Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+k3s-", GitCommit:"", GitTreeState:"clean", BuildDate:"2023-05-13T14:15:17Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
   Kustomize Version: v4.5.7
   Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:49Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
   ```

* Kubernetes cluster kind:
   DigitalOcean

* Manifests:
   N/A

* Prometheus Operator Logs:
   N/A

**Anything else we need to know?**:
N/A

**Comment by simonpasquier** [comment]
this is more a question for https://github.com/k8s-operatorhub/community-operators.  This project doesn't maintain the OLM package.

**Comment by Noah-Huppert** [comment]
Thanks my mistake
