### ISSUE TITLE
Specifying only scrapeConfigSelector breaks the deployment of Prometheus

### ISSUE THREAD

**Issue by 616b2f** [prometheus-operator/prometheus-operator#5928]
in Docs there is this statement for `scrapeConfiigSelector`:

> Experimental ScrapeConfigs to be selected for target discovery. An empty label selector matches all objects. A null label selector matches no objects.
> 
> If spec.serviceMonitorSelector, spec.podMonitorSelector, spec.probeSelector and spec.scrapeConfigSelector are null, the Prometheus configuration is unmanaged. The Prometheus operator will ensure that the Prometheus configuration’s Secret exists, but it is the responsibility of the user to provide the raw gzipped Prometheus configuration under the prometheus.yaml.gz key. This behavior is deprecated and will be removed in the next major version of the custom resource definition. It is recommended to use spec.additionalScrapeConfigs instead.

This is currently not true because `spec.scrapeConfigSelector` is not checked in code see here:

https://github.com/prometheus-operator/prometheus-operator/blob/b8d05eb743dd4c9c73681e598d14a92347954025/pkg/prometheus/server/operator.go#L1407

I run today into it because I only use the instance for federation and do not have defined any of "spec.serviceMonitorSelector, spec.podMonitorSelector, spec.probeSelector" but only "spec.scrapeConfigSelector" and the operator does not bring up an instance of prometheus because of this restriction.

**Comment by simonpasquier** [comment]
thanks for the report which is legit! do you want to give it a go?
this line would also need an update:
https://github.com/prometheus-operator/prometheus-operator/blob/b8d05eb743dd4c9c73681e598d14a92347954025/pkg/prometheus/server/operator.go#L1487-L1488

**Comment by simonpasquier** [comment]
@charmitro sure unless @616b2f feels differently.

**Comment by cccsss01** [comment]
I have it able to load with adding matchLabels:

scrapeConfigSelector:
  matchLabels:
    prometheus: system-monitoring-prometheus

which is contrary to the documentation?

However, w/ 0.68.0, it still doesn't pull up the new added target w/in prometheus.

**Comment by 616b2f** [comment]
@cccsss01 @simonpasquier I guess @nidhey27 was faster. I am fine with someone else fixing it even if I would also give it a shot myself.
