### ISSUE TITLE
Enhance Scrapeconfig documentation

### ISSUE THREAD

**Issue by cccsss01** [prometheus-operator/prometheus-operator#5940]
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/scrapeconfig.md

The documentation states, "http_sd works the same way as the file_sd  but requires an endpoint providing that data rather than a file."

Can you clarify if http_sd, also requires a config map and mount for the prometheus resource.  The current grammar states that it does, but clarification would be great within the context of http_sd would be greatly appreciated.

Thank you!

**Comment by simonpasquier** [comment]
HTTP SD doesn't need a configmap. Do you want to update the documentation to make it clearer?
