### ISSUE TITLE
make config-reloader port configurable

### ISSUE THREAD

**Issue by kilitr** [prometheus-operator/prometheus-operator#5942]
**What is missing?**
The ability to configure the used port for the config-reloader.

**Why do we need it?**
I need to run prometheus in hostNetwork and port 8080 is not available in my environment.

**Environment**

* Prometheus Operator version:

    `prometheus-operator:v0.68.0`

**Anything else we need to know?**:

**Comment by nidhey27** [comment]
Hello @kilitr
Thank you for bringing up the requirement of having the ability to configure the used port for the config-reloader.

To better understand and potentially address the concern, I have a few clarifying questions:

1. When you mention the need to configure the used port for the `config-reloader,` are you referring to the port on which the `config-reloader` exposes its own metrics (currently controlled by the _**listen-address flag**_), or is this related to how the config-reloader interacts with Prometheus?
2. Have you encountered any specific issues or limitations when trying to set an alternate port for the config-reloader using existing configurations?

Your insights would be invaluable in helping me understand the context better and finding a suitable solution. Thanks in advance!

**Comment by ArthurSens** [comment]
Yes, the flag --listen-address should be enough to change the config-reloader port

**Comment by simonpasquier** [comment]
I think that the ask is to be able to customize the port number which is currently hardcoded to 8080. A `-config-reloader-port` CLI argument for the Prometheus operator binary is probably good enough? I'm not convinced that it needs to be exposed at the CRD level.
