### ISSUE TITLE
inhibition_rules missing from Alertmanager.spec.alertmanagerConfiguration

### ISSUE THREAD

**Issue by bsgrigorov** [prometheus-operator/prometheus-operator#5950]
**What happened?**
inhibition_rules are missing from alertmanagerConfiguration. Only thing I see is:
```
FIELDS:
   global       <Object>
     Defines the global parameters of the Alertmanager configuration.

   name <string>
     The name of the AlertmanagerConfig resource which is used to generate the
     Alertmanager configuration. It must be defined in the same namespace as the
     Alertmanager object. The operator will not enforce a `namespace` label for
     routes and inhibition rules.

   templates    <[]Object>
     Custom notification templates.
```

**Did you expect to see something different?**
There should be a field for inhibition rules because this alertmanagerConfiguration overwrites it with empty inhibition rules at the moment.

* Prometheus Operator version:
v0.68.0@sha256:70f02a0fd9181a4e1afd5135e2dbb5d4264f7828df1d567b4d83a3eab63deb01
    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by simonpasquier** [comment]
Inhibition rules should be defined in the main AlertmanagerConfig resource referenced by `name`.
https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1beta1.AlertmanagerConfigSpec

**Comment by bsgrigorov** [comment]
Can you elaborate what you mean by main AlertmanagerConfig? Also where can I define templates that are reloaded when I do helm upgrade?

**Comment by bsgrigorov** [comment]
Also in the doc it says ```List of inhibition rules. The rules will only apply to alerts matching the resource’s namespace.``` How do you make the inhibit rules match to all alerts?

**Comment by simonpasquier** [comment]
> Can you elaborate what you mean by main AlertmanagerConfig? 

Basically this: https://prometheus-operator.dev/docs/user-guides/alerting/#using-alertmanagerconfig-for-global-configuration

> Also where can I define templates that are reloaded when I do helm upgrade?

We don't maintain the Helm chart. Please ask https://github.com/prometheus-community/helm-charts

> How do you make the inhibit rules match to all alerts?

I agree that the documentation is unclear and should be updated. In case of the "main" AlertmanagerConfig, it's matching all alerts already.
