### ISSUE TITLE
Missing msteams_configs alertmanager in operator

### ISSUE THREAD

**Issue by bartwitkowski** [prometheus-operator/prometheus-operator#5980]
**What happened?**

Alertmanager version 0.26.0 is able to use native msteams_configs receiver.
I've configured kube-prometheus-stack with alertmanger config to use msteams_configs.
After deployment there is no alertmanager pod and in "Kind:  Alertmanager" resource there is an error:
```
Status:
  Available Replicas:  0
  Conditions:
    Last Transition Time:  2023-10-06T13:21:18Z
    Observed Generation:   1
    Reason:                StatefulSetNotFound
    Status:                False
    Type:                  Available
    Last Transition Time:  2023-10-09T08:17:35Z
    Message:               provision alertmanager configuration: failed to initialize from secret: yaml: unmarshal errors: line 34: field msteams_configs not found in type alertmanager.receiver
    Observed Generation:  1
    Reason:               ReconciliationFailed
    Status:               False
    Type:                 Reconciled
  Paused:                 false
  Replicas:               0
  Unavailable Replicas:   0
  Updated Replicas:       0
Events:                   <none>
```

**Did you expect to see something different?**

The prometheus-operator should allow msteams_configs in alertmanager.

**How to reproduce it (as minimally and precisely as possible)**:

Add this config to alertmanager receivers:
```
alertmanager:
  config:
    receivers:
      - name: teams
        msteams_configs:
         - send_resolved: true
            webhook_url: XYZ
```

**Environment**

* Prometheus Operator version:

Prometheus opertator version: 0.68.0
Kube-prometheus-stack version: 51.0.0

* Kubernetes version information:

1.25.5

* Kubernetes cluster kind:

AKS

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="sync \"monitoring/kps-kube-prometheus-stack-alertmanager\" failed: provision alertmanager configuration: failed to initialize from secret: yaml: unmarshal errors:\n  line 34: field msteams_configs not found in type alertmanager.receiver"
```

**Anything else we need to know?**:

Missing msteams in https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/alertmanager/amcfg.go#L509
"convertReceiver converts a monitoringv1alpha1.Receiver to an alertmanager.receiver"

**Comment by nicolastakashi** [comment]
Hey @bartwitkowski 
Thanks for this.
We already have an ongoing PR for this issue available here https://github.com/prometheus-operator/prometheus-operator/pull/5778

**Comment by nicolastakashi** [comment]
@bartwitkowski no worries, I'm gonna close this issue.
