### ISSUE TITLE
Documentation hyperlinks broken

### ISSUE THREAD

**Issue by DominikMoelter** [prometheus-operator/prometheus-operator#5992]
Most of [API documentation](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md) links are broken.

For example, when I click on "Alertmanager" at "monitoring.coreos.com/v1 - Resource Types" the link points to https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.Alertmanager but should point to https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#alertmanager

![2023-10-11_08-45-53_chrome](https://github.com/prometheus-operator/prometheus-operator/assets/58733212/9406e0b5-d592-402f-ad2e-8e18e54977ca)

**Comment by simonpasquier** [comment]
You want to look at https://prometheus-operator.dev/docs/operator/api/

**Comment by DominikMoelter** [comment]
Thank you a lot for providing another link.
