### ISSUE TITLE
Option to set or remove config-reloader resources

### ISSUE THREAD

**Issue by technagy** [prometheus-operator/prometheus-operator#6000]
**What is missing?**
There is no easy way to set resources for the config-reloader container in Prometheus, Alertmanager or ThanosRuler manifest kinds. There is a posibility to override the container specs under containers[]. but this doesn't allow to remove a limit or request. For example, I can't remove the CPU limit.

* Prometheus Operator version: 0.65.2

**Comment by simonpasquier** [comment]
Have you looked into the `-config-reloader-* options?
https://prometheus-operator.dev/docs/operator/operator/
