### ISSUE TITLE
Redirect all `os.Stderr` logs as appropriately structured `os.Stdout` logs

### ISSUE THREAD

**Issue by rexagod** [prometheus-operator/prometheus-operator#6035]
To be fair, we're not really consistent: if an error happens before setting up the log struct, it's logged to stderr.

I don't feel strongly about this but I think that we should be consistent and eventually redirect everything to stdout. So for this PR, I'd use `level.Info(log)`.

_Originally posted by @simonpasquier in https://github.com/prometheus-operator/prometheus-operator/pull/5932#discussion_r1366695947_

**Comment by rexagod** [comment]
(good first issue, feel free to @ me for any specifics)

**Comment by perylemke** [comment]
@rexagod I will assume this issue. Just change `fmt.Println(log)` to `level.Info(log)`?

**Comment by rexagod** [comment]
Hello Pery! 👋🏼 I'd say so. IMO we can start by replacing `os.Stderr` occurrences by behaviors that make sure logs are written to `os.Stdout` instead. To answer your [query on Slack](https://kubernetes.slack.com/archives/C01B03QCSMN/p1699882807749299?thread_ts=1699882451.244939&cid=C01B03QCSMN), a quick search can show you where such instances lie:

```
┌[rexagod@nebuchadnezzar] [/dev/ttys000] [main]
└[~/repositories/work/prometheus-operator]> rg --fixed-strings -- os.Stderr
pkg/alertmanager/operator_test.go
1240:				logger:     level.NewFilter(log.NewLogfmtLogger(os.Stderr), level.AllowInfo()),

pkg/client/informers/externalversions/factory.go
205://	        fmt.Fprintf(os.Stderr, "caches failed to sync: %v", v)

pkg/prometheus/promcfg_test.go
70:	logger := level.NewFilter(log.NewLogfmtLogger(os.Stderr), level.AllowWarn())

pkg/prometheus/agent/statefulset_test.go
190:	return level.NewFilter(log.NewLogfmtLogger(os.Stderr), level.AllowWarn())

pkg/prometheus/resource_selector_test.go
41:	return level.NewFilter(log.NewLogfmtLogger(os.Stderr), level.AllowWarn())

pkg/prometheus/server/statefulset_test.go
51:	return level.NewFilter(log.NewLogfmtLogger(os.Stderr), level.AllowWarn())

cmd/prometheus-config-reloader/main.go
101:		fmt.Fprintln(os.Stderr, err)
199:		fmt.Fprintln(os.Stderr, err)
```

**Comment by perylemke** [comment]
@rexagod,

A example to you see if is correct:

```go
logger, err := logging.NewLogger(*logLevel, *logFormat)
if _, err := app.Parse(os.Args[1:]); err != nil {
	level.Error(logger).Log("msg", "Failed to parse command line arguments", "err", err)
	os.Exit(2)
}
```

Or just change `os.Stderr` to `os.Stdout`?

**Comment by rexagod** [comment]
This looks good to me! Since `level` pipes all output to `stdout`, I'd have that wherever possible. But, as Simon mentioned on the parent issue (https://github.com/prometheus-operator/prometheus-operator/pull/5932#discussion_r1366695947), if anything goes wrong before the logger is initialized in the operator, there could be cases where those errors are logged to `stderr` instead. For these in particular, we'd want to use `Print*` since that logs to `stdout` by default, but for all others, using `level` sounds good.
