### ISSUE TITLE
Add Support prometheus-adpater custom metrics for K8s pod autoscaling

### ISSUE THREAD

**Issue by dongjiang1989** [prometheus-operator/prometheus-operator#6044]
**What did you do?**
prometheus-operator add support [prometheus-adpater](https://github.com/kubernetes-sigs/prometheus-adapter) . custom metrics for K8s pod autoscaling

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by nicolastakashi** [comment]
Hey, @dongjiang1989 can you provide more details, about which kind of support you're expecting?

**Comment by dongjiang1989** [comment]
> Hey, @dongjiang1989 can you provide more details, about which kind of support you're expecting?

1. deploy [prometheus-adpater](https://github.com/kubernetes-sigs/prometheus-adapter) 
2. crds for prometheus-adpater rules
3. config-reloader for configmap auto-reloader

**Comment by slashpai** [comment]
prometheus-adapter will be archieved soon in near future since keda.sh is getting lot of traction which supports lot of scalers including Prometheus. But we do still deploy prometheus-adapter as part of kube-prometheus project if that's what you are looking for.

**Comment by slashpai** [comment]
prometheus-adapter will be achieved soon in near future since [keda](https://keda.sh/) is getting lot of traction which supports lot of scalers including Prometheus and [metrics-server](https://github.com/kubernetes-sigs/metrics-server) is very stable to provide resource metrics API. But we do still deploy prometheus-adapter as part of [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus) project if that's what you are looking for.

**Comment by dongjiang1989** [comment]
> prometheus-adapter will be achieved soon in near future since [keda](https://keda.sh/) is getting lot of traction which supports lot of scalers including Prometheus and [metrics-server](https://github.com/kubernetes-sigs/metrics-server) is very stable to provide resource metrics API. But we do still deploy prometheus-adapter as part of [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus) project if that's what you are looking for.

Thank you for your reply. So far It is necessary as part of  prometheus-operator.  

prometheus-adpater  custom rules depends on  Prometheus [Recording rules](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/).

**Comment by dongjiang1989** [comment]
@nicolastakashi @slashpai  Is it necessary to add prometheus-adpater support to the current prometheus-operator version? I can complete this feature.

**Comment by nicolastakashi** [comment]
@dongjiang1989 since it's going to be deprecated soon in favor of Keda as @slashpai I don't think makes sense add support, you can always deploy prometheus-adapter using it's helm chart if it's required on your use cases.

**Comment by dongjiang1989** [comment]
> @dongjiang1989 since it's going to be deprecated soon in favor of Keda as @slashpai I don't think makes sense add support, you can always deploy prometheus-adapter using it's helm chart if it's required on your use cases.

Thanks. I first tried using KEDA.
