### ISSUE TITLE
failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"main\" not found

### ISSUE THREAD

**Issue by jibinrajck** [prometheus-operator/prometheus-operator#6045]
**What happened?**

Getting Error from Prometheus operator  - failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"main\" not found

**Did you expect to see something different?**

Yes. No error expected. 

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:
0.68.0
    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

   Client Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.7-eks-8ccc7ba", GitCommit:"89a3d8612b01cd88ef26d54e5fbf46e16abe262c", GitTreeState:"clean", BuildDate:"2023-08-15T16:06:50Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.9-eks-f8587cb", GitCommit:"2e0997b730999ec918be56b8ed945394905673c5", GitTreeState:"clean", BuildDate:"2023-09-18T22:09:26Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}

    

* Kubernetes cluster kind:
EKS - 1.26
    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

level=info ts=2023-10-26T08:25:21.205420855Z caller=main.go:224 msg="Starting Prometheus Operator" version="(version=0.68.0, branch=refs/tags/v0.68.0, revision=52526e3b0cfb5f3deaa967998ff88a5133f1ec0f)"
level=info ts=2023-10-26T08:25:21.205491794Z caller=main.go:225 build_context="(go=go1.20.7, platform=linux/amd64, user=Action-Run-ID-6123005285, date=20230908-14:52:38, tags=unknown)"
level=warn ts=2023-10-26T08:25:21.21665897Z caller=main.go:101 msg="scrapeconfigs CRD not supported" reason="unmet prerequisites: scrapeconfigs resource (apiGroup: \"monitoring.coreos.com/v1alpha1\") not installed"
level=info ts=2023-10-26T08:25:21.220038461Z caller=operator.go:356 component=prometheusoperator msg="Kubernetes API capabilities" endpointslices=true
level=warn ts=2023-10-26T08:25:21.302516316Z caller=main.go:101 msg="prometheusagents CRD not supported" reason="unmet prerequisites: prometheusagents resource (apiGroup: \"monitoring.coreos.com/v1alpha1\") not installed"
level=info ts=2023-10-26T08:25:21.304122077Z caller=main.go:113 msg="Starting insecure server on [::]:8080"
level=info ts=2023-10-26T08:25:21.308898685Z caller=operator.go:476 component=alertmanageroperator msg="connection established" cluster-version=v1.26.9-eks-f8587cb
level=info ts=2023-10-26T08:25:21.308939625Z caller=operator.go:485 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2023-10-26T08:25:21.308953725Z caller=operator.go:313 component=thanosoperator msg="connection established" cluster-version=v1.26.9-eks-f8587cb
level=info ts=2023-10-26T08:25:21.308985427Z caller=operator.go:481 component=prometheusoperator msg="connection established" cluster-version=v1.26.9-eks-f8587cb
level=info ts=2023-10-26T08:25:21.309019434Z caller=operator.go:490 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2023-10-26T08:25:21.308974179Z caller=operator.go:322 component=thanosoperator msg="CRD API endpoints ready"
level=info ts=2023-10-26T08:25:21.702796531Z caller=operator.go:274 component=thanosoperator msg="successfully synced all caches"
level=info ts=2023-10-26T08:25:21.704566779Z caller=operator.go:307 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2023-10-26T08:25:21.704946823Z caller=operator.go:655 component=alertmanageroperator key=monitoring-system/main msg="sync alertmanager"
level=info ts=2023-10-26T08:25:21.706922898Z caller=operator.go:413 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2023-10-26T08:25:21.707159637Z caller=operator.go:1189 component=prometheusoperator key=monitoring-system/k8s msg="sync prometheus"
level=error ts=2023-10-26T08:25:21.908365683Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring-system/main\" failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"main\" not found"
level=error ts=2023-10-26T08:25:22.108297356Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring-system/main\" failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"main\" not found"
level=error ts=2023-10-26T08:25:22.208681638Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring-system/main\" failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"main\" not found"
level=info ts=2023-10-26T08:25:22.217091925Z caller=operator.go:655 component=alertmanageroperator key=monitoring-system/main msg="sync alertmanager"
level=error ts=2023-10-26T08:25:22.305001796Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring-system/main\" failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"main\" not found"
level=error ts=2023-10-26T08:25:22.411964593Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring-system/main\" failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"main\" not found"
level=error ts=2023-10-26T08:25:22.427588893Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring-system/main\" failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"main\" not found"
level=error ts=2023-10-26T08:25:22.529742981Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring-system/main\" failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"main\" not found"
level=info ts=2023-10-26T08:25:22.535123003Z caller=operator.go:1189 component=prometheusoperator key=monitoring-system/k8s msg="sync prometheus"
level=error ts=2023-10-26T08:25:22.602523828Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring-system/main\" failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"main\" not found"
level=error ts=2023-10-26T08:25:22.909456208Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring-system/main\" failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"main\" not found"
level=error ts=2023-10-26T08:25:24.224378533Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring-system/main\" failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"main\" not found"
level=error ts=2023-10-26T08:25:26.807055541Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring-system/main\" failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"main\" not found"
level=error ts=2023-10-26T08:25:31.948687297Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring-system/main\" failed: failed to update status subresource: alertmanagers.monitoring.coreos.com \"main\" not found"

insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by nicolastakashi** [comment]
@jibinrajck can you also share your resources manifest?
It might help us troubleshoot the issue.

**Comment by jibinrajck** [comment]
`apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-10-26T07:34:42Z"
  generation: 1
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: pipeline-monitoring-b9cb893b
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.62.0
  name: prometheus-operator
  namespace: monitoring-system
  resourceVersion: "51657"
  uid: 06bed3da-942b-4147-951c-4b3200772dba
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: prometheus-operator
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 0.62.0
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --prometheus-config-reloader=<AWSaccountID>.dkr.ecr.ap-southeast-2.amazonaws.com/core.containerregistry.prod.ecr/prometheus-config-reloader:v0.68.0
        - --thanos-default-base-image=<AWSaccountID>.dkr.ecr.ap-southeast-2.amazonaws.com/core.containerregistry.prod.ecr/thanos:v0.2.2
        image: <AWSaccountID>.dkr.ecr.ap-southeast-2.amazonaws.com/core.containerregistry.prod.ecr/prometheus-operator:v0.68.0
        imagePullPolicy: IfNotPresent
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --logtostderr
        - --secure-listen-address=:8443
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - --upstream=http://127.0.0.1:8080/
        image: quay.io/brancz/kube-rbac-proxy:v0.14.0
        imagePullPolicy: IfNotPresent
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccount: prometheus-operator
      serviceAccountName: prometheus-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-10-26T07:34:42Z"
    lastUpdateTime: "2023-10-26T07:35:04Z"
    message: ReplicaSet "prometheus-operator-66c6f679c9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-10-26T08:25:21Z"
    lastUpdateTime: "2023-10-26T08:25:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1`

**Comment by jibinrajck** [comment]
OperatorDeployment.yaml

**Comment by jibinrajck** [comment]
[operator_deployment.txt](https://github.com/prometheus-operator/prometheus-operator/files/13183489/operator_deployment.txt)

**Comment by nicolastakashi** [comment]
@jibinrajck actually we need the alertmanager manifest 😄 
If you don't mind.
Sorry I wasn't clear on my last message.

**Comment by jibinrajck** [comment]
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    prometheus-operator-input-hash: "3555676216232625157"
  creationTimestamp: "2023-10-31T03:50:33Z"
  generation: 1
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: pipeline-monitoring-b9cb893b
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.25.0
  name: alertmanager-main
  namespace: monitoring-system
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Alertmanager
    name: main
    uid: 5deb0ba2-c123-4f45-9482-947e7d22c5a6
  resourceVersion: "22798"
  uid: 71306299-a67d-4c75-b78e-5d2e7dbeceb9
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      alertmanager: main
      app.kubernetes.io/instance: main
      app.kubernetes.io/managed-by: prometheus-operator
      app.kubernetes.io/name: alertmanager
  serviceName: alertmanager-operated
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: alertmanager
      creationTimestamp: null
      labels:
        alertmanager: main
        app.kubernetes.io/component: alert-router
        app.kubernetes.io/instance: main
        app.kubernetes.io/managed-by: prometheus-operator
        app.kubernetes.io/name: alertmanager
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 0.25.0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: alert-router
                  app.kubernetes.io/instance: main
                  app.kubernetes.io/name: alertmanager
                  app.kubernetes.io/part-of: kube-prometheus
              namespaces:
              - monitoring-system
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - --config.file=/etc/alertmanager/config_out/alertmanager.env.yaml
        - --storage.path=/alertmanager
        - --data.retention=120h
        - --cluster.listen-address=[$(POD_IP)]:9094
        - --web.listen-address=:9093
        - --web.route-prefix=/
        - --cluster.peer=alertmanager-main-0.alertmanager-operated:9094
        - --cluster.peer=alertmanager-main-1.alertmanager-operated:9094
        - --cluster.peer=alertmanager-main-2.alertmanager-operated:9094
        - --cluster.reconnect-timeout=5m
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: <AWS Account ID>.dkr.ecr.ap-southeast-2.amazonaws.com/core.containerregistry.prod.ecr/alertmanager:v0.26.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /-/healthy
            port: web
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: alertmanager
        ports:
        - containerPort: 9093
          name: web
          protocol: TCP
        - containerPort: 9094
          name: mesh-tcp
          protocol: TCP
        - containerPort: 9094
          name: mesh-udp
          protocol: UDP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /-/ready
            port: web
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 4m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
        - mountPath: /etc/alertmanager/config_out
          name: config-out
          readOnly: true
        - mountPath: /etc/alertmanager/certs
          name: tls-assets
          readOnly: true
        - mountPath: /alertmanager
          name: alertmanager-main-db
      - args:
        - --listen-address=:8080
        - --reload-url=http://localhost:9093/-/reload
        - --config-file=/etc/alertmanager/config/alertmanager.yaml.gz
        - --config-envsubst-file=/etc/alertmanager/config_out/alertmanager.env.yaml
        - --watched-dir=/etc/alertmanager/config
        command:
        - /bin/prometheus-config-reloader
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SHARD
          value: "-1"
        image: <AWS Account ID>.dkr.ecr.ap-southeast-2.amazonaws.com/core.containerregistry.prod.ecr/prometheus-config-reloader:v0.68.0
        imagePullPolicy: IfNotPresent
        name: config-reloader
        ports:
        - containerPort: 8080
          name: reloader-web
          protocol: TCP
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
          readOnly: true
        - mountPath: /etc/alertmanager/config_out
          name: config-out
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - --watch-interval=0
        - --listen-address=:8080
        - --config-file=/etc/alertmanager/config/alertmanager.yaml.gz
        - --config-envsubst-file=/etc/alertmanager/config_out/alertmanager.env.yaml
        - --watched-dir=/etc/alertmanager/config
        command:
        - /bin/prometheus-config-reloader
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SHARD
          value: "-1"
        image: <AWS Account ID>.dkr.ecr.ap-southeast-2.amazonaws.com/core.containerregistry.prod.ecr/prometheus-config-reloader:v0.68.0
        imagePullPolicy: IfNotPresent
        name: init-config-reloader
        ports:
        - containerPort: 8080
          name: reloader-web
          protocol: TCP
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
          readOnly: true
        - mountPath: /etc/alertmanager/config_out
          name: config-out
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: alertmanager-main
      serviceAccountName: alertmanager-main
      terminationGracePeriodSeconds: 120
      volumes:
      - name: config-volume
        secret:
          defaultMode: 420
          secretName: alertmanager-main-generated
      - name: tls-assets
        projected:
          defaultMode: 420
          sources:
          - secret:
              name: alertmanager-main-tls-assets-0
      - emptyDir:
          medium: Memory
        name: config-out
      - emptyDir: {}
        name: alertmanager-main-db
  updateStrategy:
    type: RollingUpdate
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: alertmanager-main-67c5cff654
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: alertmanager-main-67c5cff654
  updatedReplicas: 3
```

**Comment by nicolastakashi** [comment]
@jibinrajck this is the statefulset is created by the operator, I'd like the AlertManager Manifest.
The one with kind: AlertManager.
Would be easier to reproduce the issue 😄

**Comment by jibinrajck** [comment]
```
apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Alertmanager
  metadata:
    creationTimestamp: "2023-10-18T23:43:03Z"
    generation: 1
    labels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/instance: pipeline-monitoring-b9cb893b
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.25.0
    name: main
    namespace: monitoring-system
    resourceVersion: "18747"
    uid: 50630046-0090-4978-91c1-5d9dfa4794e9
  spec:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: alert-router
                app.kubernetes.io/instance: main
                app.kubernetes.io/name: alertmanager
                app.kubernetes.io/part-of: kube-prometheus
            namespaces:
            - monitoring-system
            topologyKey: kubernetes.io/hostname
          weight: 100
    image: <AWS_ID>.dkr.ecr.ap-southeast-2.amazonaws.com/core.containerregistry.prod.ecr/alertmanager:v0.26.0
    nodeSelector:
      kubernetes.io/os: linux
    podMetadata:
      labels:
        app.kubernetes.io/component: alert-router
        app.kubernetes.io/instance: main
        app.kubernetes.io/name: alertmanager
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 0.25.0
    replicas: 3
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 4m
        memory: 100Mi
    retention: 120h
    securityContext:
      fsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: alertmanager-main
    version: v0.18.0
kind: List
metadata:
  resourceVersion: ""
```

**Comment by simonpasquier** [comment]
Are you sure that the Alertmanager CRD (e.g. `kubectl crd alertmanager`) is up-to-date?

**Comment by jibinrajck** [comment]
Yes

**Comment by woniuzhang** [comment]
Hi, I have the same issue.
Environment

    Prometheus Operator version:
    v0.74.0
    Kubernetes version:
    v1.28.5-r0-28.0.39.4

**Comment by ngealy** [comment]
> Are you sure that the Alertmanager CRD (e.g. `kubectl crd alertmanager`) is up-to-date?

Updating the alertmanger CRD version fix the issue for me
