### ISSUE TITLE
Prometheus shards utilising uneven amount of memory 

### ISSUE THREAD

**Issue by bettaps** [prometheus-operator/prometheus-operator#6051]
**What happened?**
In our setup, we have 4 prometheus shards set up and recently due to the deployment of a new workload in the same cluster, we saw a sharp increase in memory utilisation only in shard-4 and since the memory limits did not support it, the pod started crashing.
Increased memory limits across all shards and I still see that memory utilisation in shard 4 is significantly greater than the other shards. My question is, shouldn't the targets be equally distributed among all the shards ? Why is it that shard-4 takes on more metrics/traffic than the other shards ? How could we modify this to so that there is equal cpu/memory utlisation amongst all shards  ?

**Did you expect to see something different?**
All shards should have somewhat similar memory and cpu utilisation.

**How to reproduce it (as minimally and precisely as possible)**:
Configure prometheus shards to use four shards, deploy a new workload ( like gpu-operator with dgcm metrics ) that sends additional metrics to prometheus. Shard-4 is observed to have significantly higher memory utilisation compared to other shards.
 
**Environment** 
EKS cluster

* Prometheus Operator version:
v0.59.2
    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-be83b3c", GitCommit:"d6adb24671245f68ce3cd985f6b68f124953968d", GitTreeState:"clean", BuildDate:"2023-09-27T17:22:23Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}

    

* Kubernetes cluster kind:

    AWS EKS

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

N/A

**Anything else we need to know?**:

**Comment by nicolastakashi** [comment]
Hey @bettaps!

As described here.

> Shards use the Prometheus modulus configuration which takes the hash of the source label values in order to split scrape targets based on the number of shards. Prometheus operator will create number of shards multiplied by replicas pods.
>
> [Prometheus Operator Documentation](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/shards-and-replicas.md)


This means this is not an equal load distribution between shards, and we may have one shard collecting metrics from more targets than others.

**Comment by bettaps** [comment]
Thanks @nicolastakashi . 
I also noticed this statement in the same document:
`Note that scaling down shards will not reshard data onto remaining instances. It must be manually moved. Increasing shards will not reshard data either. It will continue to be available from the same instances. `

Does this mean if increase number of shards, targets wont get distributed further meaning memory consumption would reduce across all shards ?

**Comment by mattiasnensen** [comment]
The solution I had to this was to use Vertical Pod Autoscaler per shard, where the VPA object was created when a new Prometheus StatefulSet was created. This no longer work after 0.71.x because they added a scale subresource for the Prometheus CRD.

**Comment by nicolastakashi** [comment]
> Thanks @nicolastakashi . I also noticed this statement in the same document: `Note that scaling down shards will not reshard data onto remaining instances. It must be manually moved. Increasing shards will not reshard data either. It will continue to be available from the same instances. `
> 
> Does this mean if increase number of shards, targets wont get distributed further meaning memory consumption would reduce across all shards ?

Actually this means the data existing on each shard will not be distributed along side the targets.

Right @simonpasquier ?
