### ISSUE TITLE
Ignore invalid CRDs and pick up valid CRDs without failing and add validation for relabeling and metricRelabeling fields for pod/svc monitors

### ISSUE THREAD

**Issue by rashmichandrashekar** [prometheus-operator/prometheus-operator#6056]
**What happened?**
When a podmonitor/svcmonitor CRD has an erraneous field for regex in the relabeling/metric relabeling fields, the crd creation succeeds since it can be a valid string but not a valid regex( ex- .*( ). This causes any subsequent valid CRDs being created from getting picked up. Also, the current generatePodMonitorConfig/generateServiceMonitorConfig doesnt do any validation for relabeling/metricRelabeling. Can leverage the **validateRelabelConfig** method here - https://github.com/prometheus-operator/prometheus-operator/blob/dfc150aa362f0260060979d0b53a524efb974168/pkg/prometheus/resource_selector.go#L236

**Did you expect to see something different?**
One error prone CRD should not affect the other valid CRDs. Instead it should log errors and continue picking up valid CRDs

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod/service monitor with regex field in relabelings set to ".*("

**Environment**
AKS

* Prometheus Operator version:
Using prometheus operator as a package in opentelemetry-operator. Reproduces with latest version.
Example usage here - https://github.com/open-telemetry/opentelemetry-operator/blob/55c5673d342fdc1880505f9153e1626bb9d16389/cmd/otel-allocator/watcher/promOperator.go#L241

**Comment by rashmichandrashekar** [comment]
kind/enhancement

**Comment by rashmichandrashekar** [comment]
Have also created a PR to fix this - https://github.com/prometheus-operator/prometheus-operator/pull/6057

**Comment by slashpai** [comment]
Relabel configs are validated while selecting servicemonitors/podmonitors eg: https://github.com/prometheus-operator/prometheus-operator/blob/dfc150aa362f0260060979d0b53a524efb974168/pkg/prometheus/resource_selector.go#L155-L163. 

This is not checked while generating since we will be rejecting once that are failing the validation instead of failing the reconciliation due to one/few wrong servicemonitors.

**Comment by slashpai** [comment]
Closing this as its not bug from operator's point of view and validations are done select methods
