### ISSUE TITLE
Publish prometheus-config-reloader image to a registry with IPv6 support

### ISSUE THREAD

**Issue by ialidzhikov** [prometheus-operator/prometheus-operator#6059]
**What is missing?**
The prometheus-config-reloader image is published to ghcr (`ghcr.io/prometheus-operator/prometheus-config-reloader`). 
At time time of writing this, ghcr does not support container image pulls over IPv6.

```
% host ghcr.io
ghcr.io has address 140.82.121.34
```

It would be great if the prometheus-config-reloader image is pushed to a registry that supports IPv6 (GCR/AR, quay.io, etc).

**Why do we need it?**
It is currently a blocker for the IPv6 story on our side as ghcr does not support image pulls over IPv6.

**Environment**

* Prometheus Operator version: N/A

    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:
N/A

**Comment by simonpasquier** [comment]
The image is also published on `quay.io/prometheus-operator/prometheus-config-reloader` which should support IPv6.

**Comment by ialidzhikov** [comment]
Thank you @simonpasquier ! This should do the trick as quay.io supports IPv6!
