### ISSUE TITLE
Prometheus Config Reloader Out of Sync

### ISSUE THREAD

**Issue by gmcquillan** [prometheus-operator/prometheus-operator#607]
**What did you do?**

Using prometheus operator, monitoring services. Works well for weeks. Then, eventually nearly all the targets are timing out. 

**What did you expect to see?**

I expected to see targets in prometheus match the pod IPs for the current active deployment.

**What did you see instead? Under which circumstances?**

Turns out that prometheus config reloader stopped reloading the config when deployments happened about 8 days ago. 

Investigation took place today: 9/7/2017 -- there weren't any logs from prometheus-config-reloader since 8/30/2017 -- even though there'd been many changes to deployments, etc. New deployments did not trigger reloads, and targets remained invalid.

Deleting the pod and having it come back immediately fixed the issue.

**Environment**

* Prometheus version information: 

    Prometheus version: quay.io/prometheus/prometheus:v1.7.1
    Prometheus Config Reloader version: quay.io/coreos/prometheus-config-reloader:v0.0.2

* Kubernetes version information:

	1.7.1

* Kubernetes cluster kind: 
        This is on-premise -- we configure most everything with PXE scripts.

* Prometheus Operator Logs:

Prometheus logs (nothing surprising):
```
time="2017-09-07T16:53:55Z" level=info msg="Done checkpointing in-memory metrics and chunks in 413.83729ms." source="persistence.go:665"
time="2017-09-07T16:58:55Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:633"
time="2017-09-07T16:58:55Z" level=info msg="Done checkpointing in-memory metrics and chunks in 205.282685ms." source="persistence.go:665"
time="2017-09-07T17:03:55Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:633"
time="2017-09-07T17:03:55Z" level=info msg="Done checkpointing in-memory metrics and chunks in 379.844598ms." source="persistence.go:665"
```

Prometheus Config Reloader logs (again nothing erroneous -- except that it hadn't updated in about eight days):
```
ts=2017-08-30T22:05:00Z caller=main.go:244 component=volume-watcher msg="ConfigMap modified."
ts=2017-08-30T22:05:00Z caller=main.go:204 component=volume-watcher msg="Updating rule files..."
ts=2017-08-30T22:05:00Z caller=main.go:209 component=volume-watcher msg="Rule files updated."
ts=2017-08-30T22:05:00Z caller=main.go:212 component=volume-watcher msg="Reloading Prometheus..."
ts=2017-08-30T22:05:00Z caller=main.go:219 component=volume-watcher msg="Prometheus successfully reloaded."
```

**Comment by brancz** [comment]
Just to make sure I understand correctly, were these Pods of deployments which were previously monitored, or did you add new `ServiceMonitor`s?

The Prometheus Operator generates the Prometheus config from the `ServiceMonitor` objects selected through the `serviceMonitorSelector` field, therefore, reloading is really only necessary when those `ServiceMonitor` objects are modified or new are added or deleted - as that would result in a changed config.

If these were deployments/pods, which were previously monitored, this sounds like a problem with the Kubernetes service discovery in Prometheus. It would be interesting if we could reproduce this behavior if this is the case, as it would essentially effect all users using Prometheus with Kubernetes service discovery.

**Comment by gmcquillan** [comment]
I'm not sure what the status of ServiceMonitors was. That's something to investigate. 

Mostly, I wanted to confirm that the config-reloader doesn't need to reload prometheus to pick up new targets. 

I'll keep looking into it. Thanks for the information.

**Comment by paulfantom** [comment]
This issue hasn't been updated in almost 2 years. If you think this is still valid, please reopen it.
