### ISSUE TITLE
MSTeams integration severity not recognized

### ISSUE THREAD

**Issue by rgarcia89** [prometheus-operator/prometheus-operator#6108]
**What is missing?**
With the former Prom2Teams integration I was using, Microsoft Teams was showing a orange bar for `severity = warning` and a red bar for `severity = critical`. This is not working with the Alertmanager MSTeams integration.

**Why do we need it?**
For better visibility 

* Prometheus Operator version: 6.9.1

**Anything else we need to know?**:
Prom2Teams
![image](https://github.com/prometheus-operator/prometheus-operator/assets/4134730/38e0f349-c0e7-4702-a8d2-222a4748f078)

Alertmanager MSTeams integration
![image](https://github.com/prometheus-operator/prometheus-operator/assets/4134730/9c86109e-0d51-4d17-a39e-3f2e1218258f)

**Comment by slashpai** [comment]
I think this issue should be created in https://github.com/prometheus/alertmanager?

**Comment by rgarcia89** [comment]
@slashpai will do ;)
