### ISSUE TITLE
`PrometheusAgent` does not have its spec explained in the api doc

### ISSUE THREAD

**Issue by ShadowJonathan** [prometheus-operator/prometheus-operator#6112]
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md

I can find `Prometheus` here, and looking at the sourcecode and from what i can gather from online snippets, `PrometheusAgent` is expected to be similar, but the only extra information I can find is [this doc](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/designs/prometheus-agent.md), which to me reads more like a blogpost or a newssnippet, instead of a proper spec.

**Comment by slashpai** [comment]
It's in alpha section.Its easier to navigate in website that in MD file https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1alpha1.PrometheusAgent
