### ISSUE TITLE
Sharding by namespace or app.

### ISSUE THREAD

**Issue by Lukiido** [prometheus-operator/prometheus-operator#6115]
**What did you do?**

Hey, I am sharding my Prometheus, and in some reading I want to share it based on app or namespace to help balance out my cardinaltiy and allow better scaling control. I understand this should be possible in Prometheus but I don't really see anyway to specify an additional prom in the helm chart, do I need to make a new crd for it, customize the chart, or did I miss a step some place?

All I have done so far is try to add additinalPrometheusSpec to the values file and see if it would provide another prom with a unique name for a test namespace. 

Thanks!

**Did you expect to see some different?**

**Environment**

Dev

* Prometheus Operator version:

45.8.1

* Kubernetes version information:

1.25

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by Sjd-Risca** [comment]
@Lukiido: please don't look for sharding but partitioning. Sharding means to distribute the same load across multiple instances evenly, but you are looking for partitioning such as separate the load on different prometheus's group instances base upon custom targeting policy (such as namespaces, labels, etc.). Keep in mind that while partitioning you can further apply a sharding policy inside the partition itself.
For partitioning see the different ``selector``s into the [API reference](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.Prometheus).
