### ISSUE TITLE
Prometheus Operator Error

### ISSUE THREAD

**Issue by shivagande** [prometheus-operator/prometheus-operator#6122]
**What happened?**
prometheus-operator-operator pod is in ERROR state.

**Did you expect to see something different?**
It should be in RUNNING state.

**How to reproduce it (as minimally and precisely as possible):**
By running AWS EKS cluster version with 1.23 and prometheus-operator-operator image version with v0.38.1.

**Environment:**
Development, Staging and Production.

**Prometheus Operator version:**
v0.38.1

* Kubernetes version information:
Client Version: v1.28.4

* Kubernetes cluster kind:
Terraform.

* Manifests:
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-operator-operator
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-operator-8.14.0
    heritage: Helm
    release: prometheus-operator
  name: prometheus-operator-operator
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-operator-operator
      release: prometheus-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-operator-operator
        chart: prometheus-operator-8.14.0
        heritage: Helm
        release: prometheus-operator
    spec:
      containers:
      - args:
        - --manage-crds=true
        - --kubelet-service=kube-system/prometheus-operator-kubelet
        - --logtostderr=true
        - --localhost=127.0.0.1
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.38.1
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        - --config-reloader-cpu=100m
        - --config-reloader-memory=25Mi
        image: quay.io/coreos/prometheus-operator:v0.38.1
        imagePullPolicy: IfNotPresent
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      serviceAccount: prometheus-operator-operator
      serviceAccountName: prometheus-operator-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tls-proxy-secret
        secret:
          defaultMode: 420
          secretName: prometheus-operator-admission
```
* Prometheus Operator Logs:
Defaulted container "prometheus-operator" out of: prometheus-operator, tls-proxy
ts=2023-11-27T11:02:37.472289481Z caller=main.go:209 msg="Starting Prometheus Operator version '0.38.1'."
ts=2023-11-27T11:02:37.479555133Z caller=main.go:99 msg="Staring insecure server on :8080"
level=info ts=2023-11-27T11:02:37.491241258Z caller=operator.go:452 component=prometheusoperator msg="connection established" cluster-version=v1.23.17-eks-4f4795d
level=info ts=2023-11-27T11:02:37.4913152Z caller=operator.go:214 component=alertmanageroperator msg="connection established" cluster-version=v1.23.17-eks-4f4795d
level=info ts=2023-11-27T11:02:37.491370302Z caller=operator.go:294 component=thanosoperator msg="connection established" cluster-version=v1.23.17-eks-4f4795d
ts=2023-11-27T11:02:37.555694671Z caller=main.go:305 msg="Unhandled error received. Exiting..." err="creating CRD: Alertmanager: the server could not find the requested resource"
```

**Comment by shivagande** [comment]
I have tried with updating the prometheus-operator-operator image version to 0.42.1. Now pod state got changes to CrashLoopBackOff. Below are the pod logs after changing to 0.42.1.

[prometheus-opeator.txt](https://github.com/prometheus-operator/prometheus-operator/files/13473528/prometheus-opeator.txt)

I have used above manifest to update the version. Thank you.

**Comment by simonpasquier** [comment]
You need to install the CRDs prior starting the operator.
Please use the latest stable release which is v0.69.1.

**Comment by shivagande** [comment]
Hi @simonpasquier,
    I'm using image version from coreos(https://quay.io/repository/coreos/prometheus-operator?tab=tags) there is no v0.69.1 version present in coreos. The latest version is 0.42.1.

CRD's were already installed. Below were the crd's present in the cluster.
alertmanagers.monitoring.coreos.com
prometheuses.monitoring.coreos.com
prometheusrules.monitoring.coreos.com
servicemonitors.monitoring.coreos.com

**Comment by simonpasquier** [comment]
the`--manage-crds` argument isn't supported anymore which is what the logs say already You need to install all CRDs before starting the operator.

**Comment by shivagande** [comment]
I have commented out the --manage-crds flag. All crd's were already installed to the cluster. I have pasted available crd's in my above comment. I still have the same issue.

**Comment by shivagande** [comment]
Here are the logs attached. 
[prometheus-opeator.txt](https://github.com/prometheus-operator/prometheus-operator/files/13476188/prometheus-opeator.txt)

**Comment by simonpasquier** [comment]
same error as before

````
flag provided but not defined: -manage-crds
```

**Comment by shivagande** [comment]
Hi @simonpasquier,
 I have attached new logs now it is showing that "flag provided but not defined: -logtostderr" the other flag.
[prometheus-opeator.txt](https://github.com/prometheus-operator/prometheus-operator/files/13476495/prometheus-opeator.txt)
