### ISSUE TITLE
Add support for Msteams cards summary

### ISSUE THREAD

**Issue by tobmad** [prometheus-operator/prometheus-operator#6131]
**What is missing?**

Missing support for `summary` in msteams cards, which shows up in notifications. Currently without  `summary` it just says "Card".
This feature was recently added to Alertmanager with https://github.com/prometheus/alertmanager/pull/3616, so will need to wait for the next release of AlertManager (currently 0.26.0).

**Why do we need it?**

**Environment**

* Prometheus Operator version: 0.69.1

**Anything else we need to know?**:

**Comment by heliapb** [comment]
Hi @nicolastakashi I would like to work on this issue, could you please assign it to me?

**Comment by simonpasquier** [comment]
@heliapb thanks for offering your help. It's enough to claim your interest in the issue so feel free to start working on it.
