### ISSUE TITLE
Don't fail when some of environment variables can't be expanded in the configuration file

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#6136]
**What is missing?**

If a monitoring object (ServiceMonitor, PodMonitor, PrometheusRules) contains a `$(FOOBAR)` value which isn't present in the config-reloader container, the reloader fails early and doesn't expand the final configuration.

https://github.com/prometheus-operator/prometheus-operator/issues/3644 is an example but we've seen others.

It would be better if the config reloader still expand the file and reports via a metric that some variables couldn't be expanded. 

**Why do we need it?**

In self-service environments, we don't want a single monitoring resource to block the configuration update.

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:

**Comment by yp969803** [comment]
@simonpasquier can you send the code snippets where reloader fails

**Comment by simonpasquier** [comment]
Here is an example

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: "$(PORT)"

**Comment by simonpasquier** [comment]
It depends what you mean by "actually failing the container" but the error log tells you that the the reloader didn't expand the configuration file and Prometheus doesn't run the up-to-date configuration.
