### ISSUE TITLE
All group rules in PrometheusRule are not taken into account if one of the expression a rule of of a group is wrong

### ISSUE THREAD

**Issue by kaiyuanlim** [prometheus-operator/prometheus-operator#6138]
**Issue moved from**
https://github.com/prometheus/prometheus/issues/13226

**What happened?**
Created a PrometheusRule with multiple groups.

I have group A, B and C.

Group C has a faulty expression in on its rule which is aws_ebs_volume_idle_time_sum > 100d
It should be aws_ebs_volume_idle_time_sum > 100

This however, caused all of the other groups in the PrometheusRule manifest to be ignored.
Hence, i lost records for a period of 1 month.
No error was thrown in the logs.

**Did you expect to see something different?**
If a rule in group C is problematic, it should not ignore rules group A and B

**How to reproduce it (as minimally and precisely as possible)**:
As mentioned as what had happen.
Here is a snippet:
`groups:

name: resource-consumption
interval: 1m
rules:
- record: sum:cpuusagetotal:30d
expr: sum_over_time(sum by (namespace) (sum by (namespace, pod) (irate(container_cpu_usage_seconds_total{namespace!=""}[5m])) and on(pod) kube_pod_status_phase{phase="Running"}==1 )[30d:1h])
- record: sum:allocatablecore:30d
expr: sum_over_time(max (sum by (namespace) (kube_node_status_allocatable{resource="cpu", unit="core", namespace!=""}))[30d:1h])
- record: sum:capacitycore:30d
expr: sum_over_time(max (sum by (namespace) (kube_node_status_capacity{resource="cpu", unit="core", namespace!=""}))[30d:1h])
- record: sum:cpurequests:30d
expr: sum_over_time(sum by (namespace) (sum by (namespace, pod) (kube_pod_container_resource_requests{resource="cpu", unit="core", namespace!=""}) and on(pod) kube_pod_status_phase{phase="Running"}==1 )[30d:1h])
- record: sum:memusage:30d
expr: sum_over_time(sum by (namespace) (sum by (namespace, pod) (container_memory_usage_bytes{namespace!=""}) and on(pod) kube_pod_status_phase{phase="Running"}==1 )[30d:1h])
- record: sum:memrequests:30d
expr: sum_over_time(sum by (namespace) (sum by (namespace, pod) (kube_pod_container_resource_requests{resource="memory", unit="byte", namespace!=""}) and on(pod) kube_pod_status_phase{phase="Running"}==1 )[30d:1h])
- record: sum:allocatablememory:30d
expr: sum_over_time(max (sum by (namespace) (kube_node_status_allocatable{resource="memory", unit="byte", namespace!=""}))[30d:1h])
- record: sum:capacitymemory:30d
expr: sum_over_time(max (sum by (namespace) (kube_node_status_capacity{resource="memory", unit="byte", namespace!=""}))[30d:1h])
name: cloudwatch
rules:
- alert: EBSVolumeIdleTime
expr: aws_ebs_volume_idle_time_sum > 100d
labels:
severity: warning
annotations:
description: "Volume with volumeId {{$labels.volume_id}} is idle for more than 100 days"
summary: EBS Volume idle for more than 100 days`

**Environment**
Production
* Prometheus Operator version:
Prometheus version v2.46.0

* Kubernetes version information:
v1.27

* Kubernetes cluster kind:

EKS

<img width="1590" alt="286938121-8abe8709-a187-4157-a473-91090eb2a843" src="https://github.com/prometheus-operator/prometheus-operator/assets/78371459/688ca6a1-48a8-42fa-8ddf-a87e3ee0a311">

**Comment by slashpai** [comment]
Prometheus Operator log should report the invalid PrometheusRule. Have you checked operator logs?

**Comment by simonpasquier** [comment]
Yes the operator rejects any PrometheusRules object which has at least 1 invalid expression. To detect it in the future, you want to have alerting rules on the prometheus operator metrics: https://monitoring.mixins.dev/prometheus-operator/

**Comment by kaiyuanlim** [comment]
Okay, i got the following error:
`level=info ts=2023-11-30T10:59:57.58517395Z caller=rules.go:89 component=prometheusoperator prometheus.......msg="Invalid rule" err="245:11: group \"cloudwatch\", rule 10, \"EBSVolumeIdleTime\": could not parse expression: 1:32: parse error: unexpected duration \"100d\""`

However, this is really bad that just because one rule is invalid in one group affects every other groups too.
If this affected only rules within the group, then it is fine.

Reason is that if other groups contains "record" rules that are important and costly, they are affected as they are no longer recorded until the error is fixed.

**Comment by slashpai** [comment]
Yes

**Comment by simonpasquier** [comment]
We understand how it had a bad consequence for you but it's always a trade-off between being strict and lenient. The option of dropping only the invalid rules is also problematic because valid rules may depend on a previous (dropped) rule.

As @slashpai already noted, an admission webhook service would have prevented it. #3335 and #3611 would also help when they are implemented.

**Comment by kaiyuanlim** [comment]
Correct me if I am wrong but the dependency problem could also happen in between groups from different PrometheusRules manifest right?

Because it was an odd debugging session for me that the recording from another PrometheusRules manifest was fine but not another.

**Comment by simonpasquier** [comment]
> Correct me if I am wrong but the dependency problem could also happen in between groups from different PrometheusRules manifests right?

It's less likely IMHO: when 1 rule depends on another one, you want them in the same group so they are evaluated in a predictable order.

**Comment by kaiyuanlim** [comment]
> > Correct me if I am wrong but the dependency problem could also happen in between groups from different PrometheusRules manifests right?
> 
> It's less likely IMHO: when 1 rule depends on another one, you want them in the same group so they are evaluated in a predictable order.

Exactly, which is why I didn't understand why a failure in group A will cause all rules in another group like B to fail.
If a rule in Group A is defective and causes all other rules in group A to fail or ignored then I can understand.

**Comment by kaiyuanlim** [comment]
Please look into the problem.

**Comment by simonpasquier** [comment]
@kaiyuanlim I'm afraid that we're not going to change the current behavior of the operator: when a PrometheusRules object contains an invalid rule expression, the operator rejects the whole object.
