### ISSUE TITLE
Errors about CRDs not present even if they are not needed

### ISSUE THREAD

**Issue by sebastienbonami** [prometheus-operator/prometheus-operator#6140]
**What happened?**

I'm doing Prometheus Federation and my federated Prometheuses don't need these components: _Alertmanagers_, _AlertmanagerConfigs_ and _ThanosRulers_.

I'm using this Helm Chart: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack/54.1.0

Even if I set `enabled` to `false` for `alertmanager` and `thanosRuler`, the operator is still watching for their CRDs.

The less CRDs to install the better as each time they are applied it's an overhead, so that's why I would like to avoid installing the ones that are not needed (https://github.com/prometheus-operator/prometheus-operator/tree/v0.69.1/example/prometheus-operator-crd).

**Environment**

* Prometheus Operator version: _v0.69.1_
* Prometheus Operator Logs (repeated every minute or so):
```
level=warn ts=2023-12-04T15:54:14.891376049Z caller=klog.go:108 component=k8s_client_runtime func=Warningf msg="pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: failed to list *v1alpha1.AlertmanagerConfig: the server could not find the requested resource (get alertmanagerconfigs.monitoring.coreos.com)"
level=error ts=2023-12-04T15:54:14.891484742Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1alpha1.AlertmanagerConfig: failed to list *v1alpha1.AlertmanagerConfig: the server could not find the requested resource (get alertmanagerconfigs.monitoring.coreos.com)"
level=warn ts=2023-12-04T15:54:23.849004248Z caller=klog.go:108 component=k8s_client_runtime func=Warningf msg="pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: failed to list *v1.ThanosRuler: the server could not find the requested resource (get thanosrulers.monitoring.coreos.com)"
level=error ts=2023-12-04T15:54:23.849040616Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1.ThanosRuler: failed to list *v1.ThanosRuler: the server could not find the requested resource (get thanosrulers.monitoring.coreos.com)"
level=warn ts=2023-12-04T15:54:32.908493503Z caller=klog.go:108 component=k8s_client_runtime func=Warningf msg="pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: failed to list *v1.Alertmanager: the server could not find the requested resource (get alertmanagers.monitoring.coreos.com)"
level=error ts=2023-12-04T15:54:32.9085719Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1.Alertmanager: failed to list *v1.Alertmanager: the server could not find the requested resource (get alertmanagers.monitoring.coreos.com)"
```

Thanks for your help.

**Comment by simonpasquier** [comment]
We should be able to use checkPrerequisites() to verify which CRDs are installed and start the respective controllers only when needed https://github.com/prometheus-operator/prometheus-operator/blob/88e86c5caf84dc85338c904e13b0656bf1b56a67/cmd/operator/main.go#L55-L65

I think that the operator should fail if no controller can start though.

cc @paulfantom as you were interested in running the operator with a smaller scope :)

**Comment by haanhvu** [comment]
I'll work on this
