### ISSUE TITLE
Support --enable-feature Argument in Alertmanager CRD

### ISSUE THREAD

**Issue by mmikitka** [prometheus-operator/prometheus-operator#6142]
**What is missing?**
Alertmanager provides capabilities that are only enabled via toggling feature flags with the `--enable-feature` argument. The `--enable-feature` argument was added in [this Alertmanager PR](https://github.com/prometheus/alertmanager/pull/3045).

Presently, prometheus-operator and the Alertmanager CRD do not support this `--enable-feature` argument.

**Why do we need it?**
Expose more Alertmanager configuration parameters to users of the Alertmanager CRD.

**Environment**
All environments

* Prometheus Operator version: N/A. This is a new feature request.

**Anything else we need to know?**:
N/A

**Comment by ArthurSens** [comment]
For code pointers, we want to replicate what was done in [Prometheus spec](https://github.com/prometheus-operator/prometheus-operator/blob/0d918323945ce87f0094c05c153075c0a6edc8de/pkg/apis/monitoring/v1/prometheus_types.go#L272-L279) and [args generation](https://github.com/prometheus-operator/prometheus-operator/blob/0d918323945ce87f0094c05c153075c0a6edc8de/pkg/prometheus/statefulset.go#L233-L235), but for Alertmanager.

In alertmanager, the API changes will happen [here](https://github.com/prometheus-operator/prometheus-operator/blob/0d918323945ce87f0094c05c153075c0a6edc8de/pkg/apis/monitoring/v1/alertmanager_types.go#L62) and args generation is [here](https://github.com/prometheus-operator/prometheus-operator/blob/0d918323945ce87f0094c05c153075c0a6edc8de/pkg/alertmanager/statefulset.go#L230)
