### ISSUE TITLE
config-reloader doesn't reload a valid configuration an invalid configuration was pushed

### ISSUE THREAD

**Issue by Chaitan1991** [prometheus-operator/prometheus-operator#6145]
`What` happened?

When a user enable the web authetication configs in prometheus helm chart , the prometheus instance rightfully asserted that it could not reload the config. A fix was put in place to revert the change and the new config was rolled out. However, the config reloader did not successfully reload the new config, and instead reported the following:

`{llevel=error ts=2023-12-07T07:53:53.204373032Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 401 Unauthorized; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2023-12-07T07:53:58.204153509Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 401 Unauthorized; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2023-12-07T07:54:03.204110075Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 401 Unauthorized; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2023-12-07T07:54:08.203986151Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 401 Unauthorized; have you set `--web.enable-lifecycle` Prometheus flag?"}
`

Note: web.enable-lifecycle is enabled.

After this, there were no attempts to trigger a reload, and as a result the prometheus instance was reporting metrics that the last reload was unsuccessful, despite a correct configuration.

Did you expect to see something different?

I expected to see a successful configuration reload

How to reproduce it (as minimally and precisely as possible):

**modify below web.yaml changes to enable authentication,**

apply changes

check prometheus logs to show that it cannot reload the configuration

watch the config-reloader logs
After a few minutes you will see that the reload is not successful, but it will not trigger any more reload attempts. If you also watch the prometheus logs, you will see no more attempts are made. Finally, check the prometheus metrics and status page, and you'll see that the last reload was unsuccessful.

Environment

Prometheus version: appVersion: v2.47.2

Anything else we need to know?:

I have performed a test in which I disabled the changes for authentication but still the above issue persists, so it is not prometheus itself at fault. Instead it has to be the config-reloader causing the issues.

**Comment by simonpasquier** [comment]
Can you give us the prometheus-operator and prometheus-config-reloader versoins?

**Comment by Chaitan1991** [comment]
> Can you give us the prometheus-operator and prometheus-config-reloader versoins?

Thanks for replying Simon, below are the versions, 

    Prometheus appVersion: v2.47.2 which is using below image for prometheus-config-reloader
    image:
      repository: quay.io/prometheus-operator/prometheus-config-reloader
      tag: v0.67.0

**Comment by Chaitan1991** [comment]
Sure, will try and will let you know!

**Comment by Chaitan1991** [comment]
Hi Simon, tested with below config

`image:
  repository: quay.io/prometheus-operator/prometheus-config-reloader
  tag: v0.70.0`

`level=info ts=2023-12-07T08:50:44.471520587Z caller=main.go:137 msg="Starting prometheus-config-reloader" version="(version=0.70.0, branch=refs/tags/v0.70.0, revision=c2c673f7123f3745a2a982b4a2bdc43a11f50fad)"
level=info ts=2023-12-07T08:50:44.471696336Z caller=main.go:138 build_context="(go=go1.21.4, platform=linux/amd64, user=Action-Run-ID-7048794395, date=20231130-15:42:49, tags=unknown)"
level=info ts=2023-12-07T08:50:44.472052511Z caller=reloader.go:246 msg="reloading via HTTP"
level=info ts=2023-12-07T08:50:44.472109246Z caller=reloader.go:282 msg="started watching config file and directories for changes" cfg= out= dirs=/etc/config
level=error ts=2023-12-07T08:50:46.493687236Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 401 Unauthorized; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2023-12-07T08:50:51.494422697Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 401 Unauthorized; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2023-12-07T08:50:56.494148651Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 401 Unauthorized; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error ts=2023-12-07T08:51:01.493895755Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="trigger reload: received non-200 response: 401 Unauthorized; have you set `--web.enable-lifecycle` Prometheus flag?"
level=error `

**Comment by simonpasquier** [comment]
`trigger reload: received non-200 response: 401 Unauthorized` -> did you configure authentication for prometheus?
