### ISSUE TITLE
The error was:   in "<unicode string>", line 5668, column 29

### ISSUE THREAD

**Issue by Sispheor** [prometheus-operator/prometheus-operator#6159]
When deploying via Ansible using the module K8S we get an error:
```
The error was:   in "<unicode string>", line 5668, column 29
```

This is due to the missing quote in some defintion:
```yaml
enum:
  - '!='
  - =
  - =~
  - '!~'
```

The fix consist into adding quote
```yaml
enum:
  - '!='
  - '='
  - '=~'
  - '!~'
```

**Comment by simonpasquier** [comment]
Thanks for the report! Unfortunately there's nothing we can do about it. The generated YAML is valid wrt to the YAML spec and the issue is with the pyaml library (see https://github.com/yaml/pyyaml/issues/89). More details in https://github.com/prometheus-operator/prometheus-operator/pull/4897.

**Comment by Sispheor** [comment]
Thanks. I close this one then.
