### ISSUE TITLE
Can't install po-lint (or any other command) with `go install`

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#6204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

`go install github.com/prometheus-operator/prometheus-operator/cmd/po-lint@latest` fails with

````
go: github.com/prometheus-operator/prometheus-operator/cmd/po-lint@latest (in github.com/prometheus-operator/prometheus-operator@v0.70.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
````

From https://github.com/bwplotka/bingo/issues/150

### Prometheus Operator Version

```shell
N/A
```

### Kubernetes Version

```yaml
N/A
```

### Kubernetes Cluster Type

Other (please comment)

### How did you deploy Prometheus-Operator?

Other (please comment)

### prometheus-operator log output

```shell
N/A
```

**Comment by dongjiang1989** [comment]
All replaces are disallowed when using "go install" with a version number, regardless of what kind they are; 
see https://github.com/golang/go/issues/40276, specifically the sections about "replace".

**Comment by simonpasquier** [comment]
po-lint has been removed.
