### ISSUE TITLE
Support label on managed kubelet service

### ISSUE THREAD

**Issue by rezonick** [prometheus-operator/prometheus-operator#6217]
**What is missing?**
- The operator can create and maintain a service for scraping kubelets using the `--kubelet-service=` parameter.
- I couldn't find a way to add additional labels for this service.

**Why do we need it?**
- In our ServiceMonitors, we are using specific service's labels as Prometheus metric labels (e.g. cluster) using the `targetLabels` feature of ServiceMonitors.

**Environment**

* Prometheus Operator version:
* 
    `v0.70.0`

**Comment by simonpasquier** [comment]
You could use the `--labels` flag of the operator to define additional labels (beware that the labels will be added to all objects managed by the operator).

**Comment by rezonick** [comment]
Ok, I used the `relabelings` attribute of the ServiceMonitor to add the needed labels, and it worked.
Thanks :).
