### ISSUE TITLE
`additionalScrapeConfigs` from multiple secrets/keys

### ISSUE THREAD

**Issue by 0x416e746f6e** [prometheus-operator/prometheus-operator#6228]
**What is missing?**

`additionalScrapeConfigs` from multiple secrets/keys

**Why do we need it?**

- enable managing of these configs separately.
  - e.g. one would be provisioned by terraform (no sensitive config), while another would be entered by the human operator (an external scraping target that is accessed via API key).
- group these configs under different keys per different category.

**Environment**

* Prometheus Operator version: `v2.45.0`

**Comment by slashpai** [comment]
We have [ScrapeConfig](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1alpha1.ScrapeConfig) as well now have you looked if that covers your scenario?

**Comment by 0x416e746f6e** [comment]
I am using [helm-chart](https://prometheus-community.github.io/helm-charts) to deploy prometheus.  Can these two (helm and `ScrapeConfig`) work together?

Just to test it out, I deployed a dummy `ScrapeConfig`, but it's not merged into the resulting `/etc/prometheus/config_out/prometheus.env.yaml` inside the prometheus pod.  I guess I am doing something wrong?

**Comment by simonpasquier** [comment]
You'd need to define `.spec.scrapeConfigSelector` and `.spec.scrapeConfigNamespaceSelector`. I don't know how it works with Helm though.

**Comment by 0x416e746f6e** [comment]
yes, thanks!  I am testing out `scrapeConfigSelector` configuration as we speak (there is an entry in `values.yaml` for it in helm).

**Comment by 0x416e746f6e** [comment]
thanks @slashpai, @simonpasquier.  `ScrapeConfig` object(s) work like a charm.
