### ISSUE TITLE
Support file paths for certificate, key and client CA in web TLS configuration

### ISSUE THREAD

**Issue by abohne** [prometheus-operator/prometheus-operator#6246]
### Component(s)

Prometheus

### What is missing? Please describe.

`prometheusSpec.web.tlsConfig` supports specifying ca, cert, and private key as a `ConfigMap` or `Secret`.  It should also support specifying them as a file path, similar to how `ServiceMonitor` endpoints' tlsConfig can contain ca/cert/keySecret or caFile/certFile/keyFile.

### Describe alternatives you've considered.

`prometheusSpec.additionalArgs` could probably be used in conjunction with an additional volume mounted with the web configuration file to manually achieve this.

## Environment
Kubernetes Version: 1.27
Prometheus-Operator Version: 0.70.0

**Comment by simonpasquier** [comment]
Can you share more details why using configmap/secret key references isn't working for you?

**Comment by abohne** [comment]
In our use case, we are using istio and have configured things according to https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings.  The istio sidecar in this setup outputs the CA, cert, and private key as files.  They do not provide a way to have the CA, cert, and private key output to a secret or configmap.

**Comment by simonpasquier** [comment]
See https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/proposals/202305-scrapeclasses.md which is going to solve this problem. The implementation is ongoing (#5618).

**Comment by abohne** [comment]
That seems geared towards configuring the endpoints that prometheus scrapes.  This issue is regarding securing prometheus itself with TLS.

**Comment by simonpasquier** [comment]
Oops, my bad, I was too hasty!
