### ISSUE TITLE
Support basic_auth_users on the HTTP endpoint

### ISSUE THREAD

**Issue by ETisREAL** [prometheus-operator/prometheus-operator#6248]
### What is missing? Please describe.

It would be really helpful to be enable basic_auth_users on the HTTP endpoint, similar to the possibility to set tls parameters on the spec.web field.

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by simonpasquier** [comment]
It looks like a duplicate of #4200?

**Comment by ETisREAL** [comment]
Yup it is. I guess +1 then
