### ISSUE TITLE
Allow turning off automountServiceAccountToken for Prometheus SA

### ISSUE THREAD

**Issue by oscarbm1998** [prometheus-operator/prometheus-operator#6270]
### Component(s)

Prometheus, Prometheus-Operator

### What is missing? Please describe.

We are currently running a kubernetes cluster which uses the kube-prom-stack for monitoring. For security reasons, we are currently turning off automounting serviceAccountTokens by default in all of our deployments including kube-prom-stack and if the Deployment really requires that, we put the corresponding mount manually into the requiring containers again. Unfortunately, this is not possible for the prometheus system, as there is no option to provide this as part of the config values for prometheus. Therefore the prometehus CRD has to be updated to provide the option to set automountServiceAccountToken: False and the prometheus-operator has to be updated to not default it to True. 

I created a github issue for this over in the prometheus community helm charts section which is linked here: https://github.com/prometheus-community/helm-charts/issues/4148

There it was responed by a user that they could update the CRD for us, but the operator would default the prometheus argument AutoMountServiceToken to true anyways. Therefore he said that i also had to create a github issue here, so the prometeheus operator could be updated to not auto default prometheus to AutoMountServiceToken. Link to that respond chain here: https://github.com/prometheus-community/helm-charts/pull/4170

## Environment
Kubernetes Version: 1.27.7
Prometheus-Operator Version: v0.70.0

**Comment by oscarbm1998** [comment]
The security concers comes from general research on the issue from the internet + recommendations from Azure Defender to disable it as can be seen here:

"Kubernetes clusters should disable automounting API credentials" - Disable automounting API credentials to prevent a potentially compromised Pod resource to run API commands against Kubernetes clusters. For more information, see https://aka.ms/kubepolicydoc.

We are already mounting the service account manually to other parts of the kube-prom-stack such as the AlertManager which has the option of turning the automountServiceAccountToken: False and therefore works. However for prometheus the Prometheus Operator always defaults the automountServiceAccountToken to True even if we want it to be false as can be seen here: https://github.com/prometheus-community/helm-charts/pull/4170#discussion_r1462370431. Therefore we want the option to disable it in the operator.

**Comment by simonpasquier** [comment]
The aka.ms link doesn't work for me but https://kyverno.io/policies/other/restrict-automount-sa-token/restrict-automount-sa-token/ is another stance on the topic. So yes, I agree that it makes sense to have the option.

Having said that, Prometheus is a bit different from Alertmanager because the `prometheus` container needs to talk to the Kubernetes API. At the minimum we need to explain the trade-off when setting `automountServiceAccountToken: false` and provide documentation explaining how to inject the SA token with strategic merge patch. Another option would be to support these 3 modes:
* `automountServiceAccountToken: true` (default, same as today).
* `automountServiceAccountToken: false` + automatically inject the SA token into the prometheus container.
* `automountServiceAccountToken: false`.

**Comment by oscarbm1998** [comment]
Hi again, sorry for the late response. I think the proposed solution at the end of your response (https://github.com/prometheus-operator/prometheus-operator/issues/6270#issuecomment-1919009758 ) where automountServiceAccountToken defaults to true, but with the option of setting it to false when required would be a good solution to this issue. 

Once could then also probably add some comments around what you just mentioned that prometheus needs to talk to the Kubernetes API to the values file or a CRD description explaining this.

**Comment by yp969803** [comment]
so for this "automountServiceAccountToken: false + automatically inject the SA token into the prometheus container" we have to generate token first using serviceAccountName and then inject it to pod using env variable to secrets

**Comment by oscarbm1998** [comment]
When automountServiceAccountToken is set to false, one has to mount the serviceAccountToken manually, by adding a volume mount to the spec of the component as such:
    - name: serviceaccount-token
      projected:
        defaultMode: 0444
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 3607
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace

**Comment by yp969803** [comment]
Can't find any k8 api for geting serviceaccount token, so do we have to create a trial pod with a volume mounted to location "/var/run/secrets/kubernetes.io/serviceaccount" to get the token value and then use this volume for manual mount ?

**Comment by simonpasquier** [comment]
@yp969803 I don't get your question. The idea is that the operator injects the snippet mentioned in https://github.com/prometheus-operator/prometheus-operator/issues/6270#issuecomment-1976542255 into the statefulset spec.

**Comment by yp969803** [comment]
@simonpasquier got it

**Comment by cdm-anv** [comment]
@simonpasquier : I'm facing this issue currently. The 3rd option. I would be happy if I could disable the automount (automountServiceAccountToken: false.) and add the ServiceAccountToken manually to the StatefulSet/Pod. Could this be implemented in the chart?

**Comment by Sheikh-Abubaker** [comment]
Is there any update on the issue ? I would like to work on it..

**Comment by simonpasquier** [comment]
@Sheikh-Abubaker feel free to submit a PR. The simplest option is to add a `spec.automountServiceAccountToken` field to the Prometheus CRD (like we do for Alertmanager) and document how to inject the SA token via strategic merge patch.
