### ISSUE TITLE
Enable minVersionKeepFiringFor for Thanos v0.34.0

### ISSUE THREAD

**Issue by dragoangel** [prometheus-operator/prometheus-operator#6279]
### Component(s)

ThanosRuler

### What is missing? Please describe.

As issue https://github.com/thanos-io/thanos/issues/6165 already resolved we can start support `keep_firing_for` in Thanos

### Describe alternatives you've considered.

N/A

## Environment
Kubernetes Version: ANY
Prometheus-Operator Version: v0.71.2

**Comment by simonpasquier** [comment]
Thanks for reporting the issue, you beat me! Would like to contribute the change?

**Comment by dragoangel** [comment]
Hello @simonpasquier, technically I think I could implement the change, but it would require entry time for me to get in it, which I unfortunately doesn't have atm, sorry

**Comment by simonpasquier** [comment]
@dragoangel no problem!

**Comment by DeamonMV** [comment]
@simonpasquier can you please check my PR https://github.com/prometheus-operator/prometheus-operator/pull/6283, if I understand all correct, this should solve this issue.

**Comment by slashpai** [comment]
Completed in https://github.com/prometheus-operator/prometheus-operator/pull/6283
