### ISSUE TITLE
Prometheus high memory usage with 1200+ ServiceMonitors

### ISSUE THREAD

**Issue by mramesh047** [prometheus-operator/prometheus-operator#6304]
## Description
Prometheus consuming a lot of memory (>980Gib) when there are 1200+ serviceMonitors, which is operator-managed using kubernetes resources.

We have reserved large memory optimized instance having 1024Gib RAM , still prometheus crashing with OOM.

here is the screenshot of labeling for a sample target/serviceMonitor. 
<img width="485" alt="image" src="https://github.com/prometheus-operator/prometheus-operator/assets/139512081/b12c7cf0-a81c-4c36-8ec1-79825314ed8f">

here is the footprint of go profiling, (for some reason its showing 395+Gib though kubectl top command show the usage more than 900Gib+)
![image](https://github.com/prometheus-operator/prometheus-operator/assets/139512081/922b7c42-5af6-4467-bdad-7eb70e185d11)

Not sure if there are limitations on number of ServiceMonitors to use? 

### Prometheus Operator Version

```shell
v0.67.1
```

### Kubernetes Version

```yaml
1.24
```

### Kubernetes Cluster Type

EKS

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### prometheus-operator log output

```shell
NA
```

**Comment by mramesh047** [comment]
There is a massive improvement in memory usage after optimizing the serviceMonitors from 1:1 mapping to 1:multiple



<img width="758" alt="Screenshot 2024-02-22 at 10 40 55 PM" src="https://github.com/prometheus-operator/prometheus-operator/assets/139512081/508db7d5-ba0f-410e-91a3-d6e3a54f7a15">

**Comment by HubertSzymanski** [comment]
> There is a massive improvement in memory usage after optimizing the serviceMonitors from 1:1 mapping to 1:multiple which keeps number of endpoints same.
> 
> Not sure if there is any leak in keeping maintaining/keeping the high count of serviceMonitors
> 
> <img alt="Screenshot 2024-02-22 at 10 40 55 PM" width="758" src="https://private-user-images.githubusercontent.com/139512081/307240539-508db7d5-ba0f-410e-91a3-d6e3a54f7a15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDUxOTksIm5iZiI6MTcxMTEwNDg5OSwicGF0aCI6Ii8xMzk1MTIwODEvMzA3MjQwNTM5LTUwOGRiN2Q1LWJhMGYtNDEwZS05MWEzLWQ2ZTNhNTRmN2ExNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxMDU0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjA1ODc3M2QzMGUyNGMwMTdiNWMyMjk0MTFlMGNiODJhZDU4ODA1MDMyYTY0ODg0NTYyNzMxYTYyOWI5ZjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-VnqfNxSRJkCzKJCIqoZ7bkF7poly_nKZOJ5UQZFaVg">

Hi @mramesh047 I'm having similar issues with my Prometheus stack. pprof shows that we are using 4318.95MB total but in Grafana it's 12GB+. 
Can you explain briefly what you meant by "optimizing the serviceMonitors from 1:1 mapping to 1:multiple", please?
