### ISSUE TITLE
Add livenessProbe configuration for the Thanos sidecar via CRD

### ISSUE THREAD

**Issue by peterbueschel** [prometheus-operator/prometheus-operator#6307]
### Component(s)

Prometheus

### What is missing? Please describe.

We would like to have the option to add a livenessProbe for the Thanos sidecar in the Prometheus CRD. That allows us to let the sidecar restart as soon as it becomes stuck.

We have this issue multiple times. Prometheus is fine, but its sidecar errors and does not recover anymore:

```bash
level=warn ts=... caller=sidecar.go:224 msg="heartbeat failed" err="2 errors: context deadline exceeded; read body: context deadline exceeded"
level=warn ts=... caller=sidecar.go:224 msg="heartbeat failed" err="perform GET request against http://localhost:9090/api/v1/status/config: Get \"http://localhost:9090/api/v1/status/config\": context deadline exceeded"
```

Also the query `thanos_sidecar_prometheus_up` ([also used in the mixin alerts](https://monitoring.mixins.dev/thanos/#thanos-sidecar)) returns 0 at these points in time.

A restart of the pod helps. But we would like to automate this via livenessProbe.

### Describe alternatives you've considered.

We can also alert on these issues and manually restart the pods. Another option would be to use the Thanos Receiver instead of the sidecar.

## Environment
Kubernetes Version: v1.26
Prometheus-Operator Version: v0.67.1

**Comment by simonpasquier** [comment]
It should already be possible to inject the liveness probe via strategic merge patch (https://prometheus-operator.dev/docs/operator/strategic-merge-patch/).
It would be interesting to know why the sidecar is stuck though.

**Comment by peterbueschel** [comment]
Hi @simonpasquier,

thank you. That gave me the hint that I can just add a livenessProbe into the prometheus CR. In our case we are using the kube-prometheus stack and there I could just add:

```
  // kube-prometheus.libsonnet
local kp = (...) +  
  {
    values+:: { ... } 
    ...
    prometheus+: {
	  ...
      prometheus+: {
        spec+: {
          containers+: [{
            name: 'thanos-sidecar',
            livenessProbe: {
              periodSeconds: 30,
              failureThreshold: 3,
              initialDelaySeconds: 300,
              httpGet: {
                path: '/metrics',
                port: 10902,
              },
            },
          }],
        },  // spec
      },  // prometheus
    }, // prometheus
  ..
 }; // kp
{
...
}
```

I have to verify that the probe is the right one, but at least I have now an option to define such a probe. Awesome - thanks a lot :+1: 

To find and fix the reason behind the issue would be of course the better option here. While debugging this, I could only find the mentioned "heartbeat failed" log lines. The good thing is, that this issue happened maybe once per month for one sidecar out of 35. I am open for debugging suggestions, but for now I happy to automatically recover from that issue.
