### ISSUE TITLE
Prometheus-operator  support for knative

### ISSUE THREAD

**Issue by yp969803** [prometheus-operator/prometheus-operator#6347]
### Component(s)

Prometheus-operator

### What is missing? Please describe.

Creating support for deployment of prometheus-operator on knative

**Comment by slashpai** [comment]
Hello 👋🏻 

Have you checked https://knative.dev/docs/serving/observability/metrics/collecting-metrics/?

IIUC this is already supported and in docs they are using [helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) which installs and configures prometheus-operator.

Are you looking for this or you have a particular usecase?

**Comment by yp969803** [comment]
Thanx @slashpai i am looking for the same
