### ISSUE TITLE
Add `ttl` to `alertmanagerconfigs` resource

### ISSUE THREAD

**Issue by onedr0p** [prometheus-operator/prometheus-operator#6360]
### Component(s)

AlertManagerConfig

### What is missing? Please describe.

A new field was added to the `pushover_configs` called `ttl`, it would be nice if the operator supported this new field

Refs:

- https://github.com/prometheus/alertmanager/pull/3474
- https://prometheus.io/docs/alerting/latest/configuration/#pushover_config

## Environment
Kubernetes Version: v1.29.2
Prometheus-Operator Version: 0.71.2

**Comment by slashpai** [comment]
IIUC this needs alertmanager version 0.27.0

**Comment by slashpai** [comment]
Do you want to contribute to the change?

**Comment by aerosouund** [comment]
Hello @slashpai 
I would be interested in taking this, in case @onedr0p isn't already working on it

**Comment by onedr0p** [comment]
Go for it, thanks @aerosouund !

**Comment by slashpai** [comment]
@aerosouund sure go ahead :)

**Comment by slashpai** [comment]
Here is a example PR https://github.com/prometheus-operator/prometheus-operator/pull/5886 how to add fields in alertmanagerconfigs

- [ ] Add to https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/alertmanager/types.go
- [ ] Add to https://github.com/prometheus-operator/prometheus-operator/tree/main/pkg/apis/monitoring/v1alpha1 and https://github.com/prometheus-operator/prometheus-operator/tree/main/pkg/apis/monitoring/v1beta1

Incase if you have any questions please feel free to ask

**Comment by aerosouund** [comment]
Hello @slashpai 

I have created a PR that adds the field, although i'd like to ask you where to add the functionality that uses this field.
i didn't find that in the prometheus operator there's an implementation of the `Notify` interface.

where do you think this functionality belongs ? or where do i start looking ? 
Thanks in advance

**Comment by onedr0p** [comment]
@aerosouund Alertmanager will be able to pick up the config and use, see the PR that added the functionality to AM here

https://github.com/prometheus/alertmanager/pull/3474

**Comment by slashpai** [comment]
You need to add the code to include this change in pkg/alertmanager/amcfg.go, unit test to pkg/alertmanager/amcfg_test.go

See the example PR I linked in previous comment

**Comment by afzal442** [comment]
hi @aerosouund just check in! 😄 Are you still following up with your PR? I wanted to take this up.

**Comment by aerosouund** [comment]
Hey @afzal442 
No, feel free to take this up

**Comment by onedr0p** [comment]
Thanks everyone involved for getting this into the operator, much appreciated!
