### ISSUE TITLE
Enhanced issue life-cycle management for Prometheus-Operator

### ISSUE THREAD

**Issue by mviswanathsai** [prometheus-operator/prometheus-operator#6373]
### What is missing? Please describe.

We are currently using the deprecated stale bot for issue life-cycle management, it is no longer maintained and does not support life-cycle management like that in the Kubernetes repo. 

### Describe alternatives you've considered.

 I think it might be a better alternative for us:
 1. To move to the stale action instead. Or,
 2.  I made a [fork](https://github.com/mviswanathsai/stale) of the stale action which includes Kubernetes-like lifecycle management.

The workflow of the fork (similar to Kubernetes):
1. `lifecycle/stale` label applied after 90 days of inactivity
2. `lifecycle/rotten` label applied after 30 days of lifecycle/stale
3. Closed after 30 days of `lifecycle/rotten`
4. These are the time parameters Kubernetes uses in its triage-robot, the params can be changed as we like in the workflow config.
 
 Slack discussion:
 https://kubernetes.slack.com/archives/C01B03QCSMN/p1709722826399829

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by simonpasquier** [comment]
I don't see where it says that the stale action is deprecated. Do you have a link?

**Comment by mviswanathsai** [comment]
The action is not, but the bot is. See [here](https://github.com/apps/stale).

**Comment by simonpasquier** [comment]
No problem!
