### ISSUE TITLE
Update the list of currently supported SDs using `ScrapeConfig`

### ISSUE THREAD

**Issue by mviswanathsai** [prometheus-operator/prometheus-operator#6382]
It has been some time and the list of SDs that is supported by `ScrapeConfig` is not up to date with the current list of SDs offered. It needs to be updated. This is the [link](https://prometheus-operator.dev/docs/user-guides/scrapeconfig/#use-scrapeconfig-to-scrape-an-external-target).

**Comment by SerikiAyodele** [comment]
@slashpai how do i assign this to myself?

Also, just to be clear the way i understand this task is, i will be adding a link that directs users to the ScrapeConfig documentation 

So this line:
"The following examples are basic and don't cover all the supported service discovery mechanisms. The CRD is constantly evolving, adding new features. Check the API documentation to see all the available fields."

Will become:
The following examples are basic and don't cover all the supported service discovery mechanisms. The CRD is constantly evolving, adding new features. Check the [API documentation]( https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1alpha1.ScrapeConfig) to see all the available fields.

Is this correct?

**Comment by slashpai** [comment]
@SerikiAyodele Commenting on the issue to work on is enough to start working on the issue :)

You need to update https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/scrapeconfig.md

May be like

> The following examples are basic and don't cover all the supported service discovery mechanisms. The CRD is constantly evolving, adding new features and support for new Service Discoveries. Check the [API documentation](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1alpha1.ScrapeConfig) to see all supported fields.

Once you create PR other maintainers can also review if any other change is required :)

**Comment by SerikiAyodele** [comment]
> @SerikiAyodele Commenting on the issue to work on is enough to start working on the issue :)
> 
> You need to update https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/scrapeconfig.md
> 
> May be like
> 
> > The following examples are basic and don't cover all the supported service discovery mechanisms. The CRD is constantly evolving, adding new features and support for new Service Discoveries. Check the [API documentation](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1alpha1.ScrapeConfig) to see all supported fields.
> 
> Once you create PR other maintainers can also review if any other change is required :)

Got it, thanks!
I have opened a [PR](https://github.com/prometheus-operator/prometheus-operator/pull/6391) here :)

**Comment by slashpai** [comment]
Closed in https://github.com/prometheus-operator/prometheus-operator/pull/6391
