### ISSUE TITLE
Support setting imagePullPolicy for config-reloader

### ISSUE THREAD

**Issue by agelwarg** [prometheus-operator/prometheus-operator#6399]
### What is missing? Please describe.

It looks like the operator takes a command line argument for influencing the config-reloader image (`-prometheus-config-reloader string`) but I don't think there's a way to influence the `imagePullPolicy`.  Additionally, I have opened https://github.com/prometheus-community/helm-charts/issues/4362 in the helm chart in order to take advantage of an option like this.  As mentioned in that ticket, this is in support of some occasions where I deploy in an airgap environment and never want to see an attempt to pull images.

### Describe alternatives you've considered.

None

## Environment
Kubernetes Version: v1.25.16+k3s4
Prometheus-Operator Version: v0.72.0

**Comment by QuentinBisson** [comment]
You can set it though:
https://github.com/prometheus-operator/prometheus-operator/blob/a9b337560d77d5e30321dd917bbc98f891ac0af7/pkg/apis/monitoring/v1/prometheus_types.go#L205

The ImagePullPolicy you set on the Prometheus CR is also used for the reloaders. What you cannot do is set a customer image policy per container
