### ISSUE TITLE
Add e2e test on secret update for PrometheusAgent

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#6414]
Ideally we'd need an e2e test to verify this but it's a bit more involved. I also think that we should reduce code duplication since all controllers have similar patterns for configmap/secret handlers but again it doesn't need to be in this be in this PR.

_Originally posted by @simonpasquier in https://github.com/prometheus-operator/prometheus-operator/pull/6412#pullrequestreview-1948360281_

**Comment by jamshidi799** [comment]
@slashpai may I pick this issue?
