### ISSUE TITLE
Reduce code duplication for configmap/secret event handlers in controllers

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#6415]
Ideally we'd need an e2e test to verify this but it's a bit more involved. I also think that we should reduce code duplication since all controllers have similar patterns for configmap/secret handlers but again it doesn't need to be in this be in this PR.

Alertmanager, Prometheus, PrometheusAgent and ThanosRuler controllers have very similar event handlers for secrets and configmaps (at least). It would make sense to have generic code working for all.

_Originally posted by @simonpasquier in https://github.com/prometheus-operator/prometheus-operator/pull/6412#pullrequestreview-1948360281_

**Comment by jamshidi799** [comment]
I'm interested, but I'm not sure how to proceed. I think we should move the event handler logic to the `pkg/operator` package, right?

**Comment by simonpasquier** [comment]
@jamshidi799 correct. The challenge is to design something which can integrate seamlessly in all controllers.
