### ISSUE TITLE
Prometheus-Operator reconciling Prometheus RBAC

### ISSUE THREAD

**Issue by ArthurSens** [prometheus-operator/prometheus-operator#6422]
### Component(s)

Prometheus, PrometheusAgent

### What is missing? Please describe.

During our [ContribFest in KubeCon Paris](https://sched.co/1YkTo), one of the hardest parts when setting up Prometheus instances with Prometheus-Operator was setting the right RBAC permissions of each instance.

We could lower the entry barrier if Prometheus-Operator could create all the necessary RBAC permissions for the Prometheus instances it is responsible for (commonly known as [roleSpecificNamespaces](https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheus-roleSpecificNamespaces.yaml) in kube-prometheus).

For that to be possible Prometheus-Operator needs write access to Roles and RoleBinding APIs, which is not ideal in production scenarios, so we could enable this behavior **_only when Prometheus-Operator already has permissions to write Roles and Rolebindings_**.

**Comment by simonpasquier** [comment]
Could this be part of the future kubectl plugin?

**Comment by ArthurSens** [comment]
Yeah, I don't see why not actually

Giving write access to role and rolebindings to Prometheus-Operator sounds pretty bad, let's focus on the plugin then

**Comment by simonpasquier** [comment]
FWIW this is the role of the [cluster monitoring operator](https://github.com/openshift/cluster-monitoring-operator/) in OpenShift: it manages Prometheus/Alertmanager objects + all dependencies like SA, RBAC, services, ...

**Comment by simonpasquier** [comment]
By definition yes. Any entity granting permission Foo to another service account needs to own the permission in the first place.
