### ISSUE TITLE
Add support for relabel configs per Alertmanager config

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#6445]
### Component(s)

Prometheus, ThanosRuler (possibly)

### What is missing? Please describe.

Prometheus v2.51 added the ability to have alert relabel configs per Alertmanager config. We need to support it in the Prometheus CRD.

https://github.com/prometheus/prometheus/pull/12551

### Environment Information.

N/A

**Comment by mviswanathsai** [comment]
I can take this up. Would that be fine?
