### ISSUE TITLE
Add testing instructions using podman

### ISSUE THREAD

**Issue by slashpai** [prometheus-operator/prometheus-operator#6488]
### Component(s)

Other (please comment)

### What is missing? Please describe.

We had testing instructions using podman as well but got accidently removed in https://github.com/prometheus-operator/prometheus-operator/pull/5903/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5. We can include instructions using podman in TESTING.md file as direct execution of command will fail on systems not using docker but podman

### Describe alternatives you've considered.

NA

### Environment Information.

NA

**Comment by codeknight03** [comment]
Changes underway. Seeing what would be the best option. Have a separate section for Podman instructions or have the commands with docker and commands with podman in the same section. Any strong opinions on that @slashpai ?

**Comment by slashpai** [comment]
No strong opinion but I think separate section may be better to avoid cluttering the commands?

**Comment by codeknight03** [comment]
Any requirement changes to this issue ?
