### ISSUE TITLE
Proposal: add support keda for K8s pod autoscaling

### ISSUE THREAD

**Issue by dongjiang1989** [prometheus-operator/prometheus-operator#6510]
## Description

Add support keda for K8s pod autoscaling

ref: https://landscape.cncf.io/?item=orchestration-management--scheduling-orchestration--keda

## Steps to Reproduce

1. CRD deploy keda
2. CRD Secret and TriggerAuthentication

### Prometheus Operator Version

```shell
None
```

### Kubernetes Version

```yaml
None
```

### Kubernetes Cluster Type

kind

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### prometheus-operator log output

```shell
None
```

**Comment by slashpai** [comment]
@dongjiang1989 Let me know if the above comment is usecase or you are looking something else?
