### ISSUE TITLE
Missing `prometheus_operator_kubernetes_client_http_requests_total` metric in v0.72

### ISSUE THREAD

**Issue by metalmatze** [prometheus-operator/prometheus-operator#6513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

We've upgraded from v0.68 to v0.72 and there's no more `prometheus_operator_kubernetes_client_http_requests_total` metric. 

## Steps to Reproduce

Upgrade von v0.68 to v0.72. 

## Expected Result

I expect the metric to be there. 

## Actual Result

Firing absent alert. 
```
name: SLOMetricAbsent
expr: absent(prometheus_operator_kubernetes_client_http_requests_total{job="prometheus-operator"}) == 1
for: 1m
```

### Prometheus Operator Version

`prometheus_operator_build_info`

```shell
prometheus_operator_build_info{branch="refs/tags/v0.72.0", container="kube-rbac-proxy", endpoint="https", goarch="amd64", goos="linux", goversion="go1.22.0", instance="10.0.6.33:8443", job="prometheus-operator", namespace="observability", pod="prometheus-operator-55fddb6479-bqhrl", revision="95e0561f60ef7c0dbbb9ed630089d2f26729b70d", service="prometheus-operator", tags="unknown", version="0.72.0"}
```

### Kubernetes Version

Doesn't matter.

### Kubernetes Cluster Type

GKE

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### Manifests

kube-prometheus.

### prometheus-operator log output

```shell
none
```

**Comment by kakkoyun** [comment]
@metalmatze Thanks for opening this! We are experiencing the same, but somehow, the metric mentioned is not exposed anymore.

cc @squat

**Comment by simonpasquier** [comment]
The plague of global variables and init functions! I tested and it seems to be the same issue than https://github.com/cilium/cilium/pull/26412. The "fix" is to force the global k8s metrics :shrug:
