### ISSUE TITLE
Correcting the documentation for xxxmonitornamespaceselector in prometheus crd

### ISSUE THREAD

**Issue by fettimbapro** [prometheus-operator/prometheus-operator#6550]
### What is missing? Please describe.

Greetings promethesians! 
I am a long time enjoyer of prometheus-operator, you guys are killing it!

I have a small note on the wording of the api.md documentation, while trying to edit the podmonitornamespaceselector-field, I tried to follow the documentation of using a "null value" in multiple different syntaxes, alas I finally got it to work by simply removing the line of code from the yaml manifest.

I propose a change in the description of all xxxmonitornamespaceselectors 

from:

Namespaces to match for xxxMonitors discovery. An empty label selector
matches all namespaces. A null label selector matches the current
namespace only.

to: 
 
Namespaces to match for xxxMonitors discovery. An empty label selector
matches all namespaces. A null label selector **(default value)** matches the current
namespace only.

This would clarify how an administer of prometheus would go about doing stuff.

Hope you have a great weekend!
Best regards,
Sam

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by simonpasquier** [comment]
thanks for the kind words! Do you want to contribute the change?

**Comment by AshwinSriram11** [comment]
I can work on this issue @simonpasquier. Also, is there any other changes needed in the description other than the one mentioned by @fettimbapro ?

**Comment by ArthurSens** [comment]
Fixed by #6605
