### ISSUE TITLE
wrong sample port name used in troubleshooting documentation

### ISSUE THREAD

**Issue by hmacias-avaya** [prometheus-operator/prometheus-operator#6552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

The troubleshooting documentation refers to a `metrics` sample port name but the sample provided uses `web` instead.

### Prometheus Operator Version

```shell
not applicable
```

### Kubernetes Version

```yaml
not applicable
```

### Kubernetes Cluster Type

kind

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### prometheus-operator log output

```shell
not applicable
```

### Anything else?

just a minor documentation glitch

**Comment by simonpasquier** [comment]
closed by #6553
