### ISSUE TITLE
Allow setting env vars for config-reloader created for Prometheus Kind

### ISSUE THREAD

**Issue by xbglowx** [prometheus-operator/prometheus-operator#6560]
### Component(s)

Prometheus

### What is missing? Please describe.

The ability to pass env vars to the config-reloader that is created by the operator that is for Prometheus Kind.

I originally created an issue under the helm chart, but I think a better place for it would be here instead? https://github.com/prometheus-community/helm-charts/issues/3982

### Describe alternatives you've considered.

I was able to use Kustomize to patch the config-reloader container that is part of the Operator Pod, since that is a resource that gets created directly from the helm chart, but can't do the same for the config-reloader that gets created by Prometheus kind.

## Environment
Kubernetes Version: 1.27.12
Prometheus-Operator Version: v0.71.2

**Comment by simonpasquier** [comment]
it should be possible using strategic merge patch: https://prometheus-operator.dev/docs/operator/strategic-merge-patch/#how-to-inject-an-environment-variable-in-an-existing-container

**Comment by simonpasquier** [comment]
But if the request is "I want the containers to pick up the correct GOMAXPROCS based on the CPU resource limits", I'd be open to integrate with https://github.com/uber-go/automaxprocs.

**Comment by xbglowx** [comment]
> it should be possible using strategic merge patch: https://prometheus-operator.dev/docs/operator/strategic-merge-patch/#how-to-inject-an-environment-variable-in-an-existing-container

Thanks and sorry that I totally missed that option.

**Comment by xbglowx** [comment]
> But if the request is "I want the containers to pick up the correct GOMAXPROCS based on the CPU resource limits", I'd be open to integrate with https://github.com/uber-go/automaxprocs.

Yes, this would be a nice to have, so that one doesn't have to worry about setting GOMAXPROCS in the first place.

**Comment by simonpasquier** [comment]
Closd by #6576
