### ISSUE TITLE
Prometheus Operator does not reflect the Custom recording rules 

### ISSUE THREAD

**Issue by velu4689** [prometheus-operator/prometheus-operator#6562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
We have deployed a prometheus operator stack with KSM & NE. However, we are unable to see the custom recording rules that we have added. It gets listed when we query using: kubectl get prometheusrules -n <>

However when we go prometheus UI, we do not see the recording rules listed in the config. Also, the metrics computed using recording rules did not reflect

## Expected Result
Reflect recording rules in prometheus ui

### Prometheus Operator Version

```shell
Prometheus operator version - v0.71.0
```

### Kubernetes Version

```yaml
1.24
```

### Kubernetes Cluster Type

Other (please comment)

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### prometheus-operator log output

```shell
Looks good
```

**Comment by slashpai** [comment]
Could you please provide the rule you are trying to add and prometheus operator logs?
