### ISSUE TITLE
`overrideHonorLabels` not behaving as documented  

### ISSUE THREAD

**Issue by Daniel-Vaz** [prometheus-operator/prometheus-operator#6616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

When creating a `Prometheus` object while setting `overrideHonorLabels: true`, instead of having all scrapes configured to have `honor_labels: true`, instead all references are removed, reverting to the default value `false`.

The [API Docs](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.PrometheusSpec) say:

>When true, Prometheus resolves label conflicts by renaming the labels in the scraped data to “exported_” for all targets created from service and pod monitors. (...)

When searching I found [this](https://github.com/prometheus-operator/prometheus-operator/blob/4c1706c4cf97c9e2db07635b3e517c1e0a949ec7/pkg/prometheus/promcfg.go#L320-L332). Which if I'm understanding correctly basically contradicts what the docs say. 

## Steps to Reproduce

1. Create a `Prometheus` object and set `overrideHonorLabels` to true;
2. Create some ServiceMonitors\PodMonitors;
3. Evaluate the generated Prometheus config and check the value of `honor_labels`.

## Expected Result

I want to achieve a scenario where `honor_labels: true` is automatically added into all scrape jobs in the generated config.

## Actual Result

All `honor_labels` references in the generated config are removed, defaulting to the default `false` value.

### Prometheus Operator Version

```shell
`v0.73.1`
```

### Kubernetes Version

```yaml
v1.28.5
```

### Kubernetes Cluster Type

kubeadm

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### prometheus-operator log output

```shell
Operator syncs config regularly nothing interesting there I believe:


level=info ts=2024-05-24T13:20:36.147111651Z caller=operator.go:766 component=prometheus-controller key=monitoring-system/kps-prometheus msg="sync prometheus"
```
```


### Anything else?

_No response_

**Comment by simonpasquier** [comment]
Yes the "bug" is in the documentation: when "overrideHonorLabels: true" then the operator sets "honor_labels: false" for all generated scrape configs.
I agree that it's confusing and we should have chosen a better field name but unfortunately we can't change it and a clarification in the docs is more than welcome.

> I want to achieve a scenario where honor_labels: true is automatically added into all scrape jobs in the generated config.

This would be a good use case for the new ScrapeClass functionality. cc @nicolastakashi

**Comment by mviswanathsai** [comment]
Poke @AshwinSriram11

**Comment by AshwinSriram11** [comment]
> Yes the "bug" is in the documentation: when "overrideHonorLabels: true" then the operator sets "honor_labels: false" for all generated scrape configs. I agree that it's confusing and we should have chosen a better field name but unfortunately we can't change it and a clarification in the docs is more than welcome.
> 
So should I just replace the original description with this as we don't have functionality for it? @simonpasquier

**Comment by simonpasquier** [comment]
@AshwinSriram11 correct

**Comment by mviswanathsai** [comment]
> I agree that it's confusing and we should have chosen a better field name but unfortunately we can't change it and a clarification in the docs is more than welcome.

I want to achieve a scenario where honor_labels: true is automatically added into all scrape jobs in the generated config.

This would be a good use case for the new ScrapeClass functionality. cc @nicolastakashi

Should we address this in a different issue and close this one?
