### ISSUE TITLE
Adding a Readme.md to alertmanager package.

### ISSUE THREAD

**Issue by codeknight03** [prometheus-operator/prometheus-operator#6691]
### Component(s)
Alertmanager CRD

### What is missing? Please describe.

We need a README.md in the alertmanager package for the following reasons : 
For contributors :  
1. When updating the CRD this could serve as a reference. 
2. When debugging issues with particular fields in the CRD the flow described in README should give a fair idea of where to look. 

For Users : 
1.  Though apparent by the naming, this one can help them understand the difference the beta and alpha apis. 

### Describe alternatives you've considered.

Not Applicable

### Environment Information.

Not Applicable

**Comment by slashpai** [comment]
I think I had logged a issue back sometime https://github.com/prometheus-operator/prometheus-operator/issues/6429
I think you are looking for same?

**Comment by codeknight03** [comment]
Yeah, exactly this one. Apologies might have missed on my issue search. Closing this and will continue on https://github.com/prometheus-operator/prometheus-operator/issues/6429 to add a PR for the same.

**Comment by slashpai** [comment]
no worries
