### ISSUE TITLE
Add scale subresource to the Alertmanager CRD

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#6712]
### Component(s)

AlertManager

### What is missing? Please describe.

To be able to scale Alertmanager objects, the CRD needs a scale subresource.

Follow-up from #4727

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by chowmean** [comment]
Hi @simonpasquier If no one has picked it up, can I start on this? This is what we are looking for right? https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource

**Comment by simonpasquier** [comment]
@chowmean please go for it! Alertmanager is stateful and I see no concrete strategy where we could "shard" the service (unlike with Prometheus) so the scale subresource should act on the replica count.

cc @ArthurSens @nicolastakashi

**Comment by ArthurSens** [comment]
Maybe you could sync with @afzal442? I think he started working on this (see https://github.com/prometheus-operator/prometheus-operator/issues/6609 and https://github.com/prometheus-operator/prometheus-operator/pull/6728), although it is still a draft for quite a while

**Comment by simonpasquier** [comment]
Ah, somehow I completely missed #6609! Let me close this one.
