### ISSUE TITLE
Support OAuth2 TLSConfig settings

### ISSUE THREAD

**Issue by jbreed** [prometheus-operator/prometheus-operator#6717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
Using an oauth2 provider using HTTPs results in TLS validation error. This was fixed in the underlying Prometheus container; however, has not been integrated into the CRDs and likely the operator codebase (haven't read the code, but verified the ServiceMonitor CRD and latest API docs still don't show it). 

## Steps to Reproduce

- Using an internal oauth2 provider signed by a non-public CA (IE: internal/private network CA)
- Configure a ServiceMonitor using oauth2 for receiving a token against an HTTPS endpoint

## Expected Result

Ability to use the oauth2 tlsconfig that was merged into the prometheus codebase at the end of 2021, or an additional/separate option for adding an internal CAs certificate to the trusted CAs without having to volume-mount over the /etc/ssl/certs/ca-certificates file used by the prometheus pod (current way to work around not having this).

## Actual Result

Error when communicating to the TLS oauth2 provider.

## Current work-around(s)

- Volume mount replacing the prometheus pod ca file
- (not tested, just assumed to work) Custom scrape configuration to add TLSConfig under oauth2
- (not recommended) use http
- (not tested or reviewed) ScrapeConfig CRD possibly could be used

## References
https://github.com/prometheus/common/issues/330
I believe this was in the release v2.31.0. 

I imagine if setting the scrape configuration manually (unsure if this is also missing in the scrape crd), then I imagine the pod will leverage it. 

### Prometheus Operator Version

```shell
unavailable at this time
```

### Kubernetes Version

```yaml
unavailable at this time
```

### Kubernetes Cluster Type

Rancher

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### prometheus-operator log output

```shell
unavailable
```

**Comment by jbreed** [comment]
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.OAuth2

**Comment by dongjiang1989** [comment]
I would like to work on this issue.
