### ISSUE TITLE
Add Ionos Service Discovery to ScrapeConfig CRD

### ISSUE THREAD

**Issue by AshwinSriram11** [prometheus-operator/prometheus-operator#6718]
### Component(s)

ScrapeConfig

### What is missing? Please describe.

Ionos sd support

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by AshwinSriram11** [comment]
I would like to work on this issue.

**Comment by nicolastakashi** [comment]
Amazing @AshwinSriram11 go for it, just align with @mviswanathsai and @slashpai

**Comment by slashpai** [comment]
sure go ahead new SDs are always welcome :)

**Comment by mviswanathsai** [comment]
My advice would be to take inspiration from the existing PRs, especially the newer ones: #6689, #6660 and #6651. The general idea is to validate as much as possible in the API level (`+kubebuilder:validation:`). 
Try to read the Prometheus code to understand what validations might be necessary. If you get stuck anywhere, reach out! happy to help.

**Comment by AshwinSriram11** [comment]
We can close this issue now that #6732 has been merged.
