### ISSUE TITLE
Navigation for API Reference page in website not working properly

### ISSUE THREAD

**Issue by AshwinSriram11** [prometheus-operator/prometheus-operator#6733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
If we look at the bottom of [API Reference](https://prometheus-operator.dev/docs/api-reference/api/) page, the prev and next page are ScrapeConfig CRD(Developer Guide) and Admission Webhook(Platform Guide). But, in reality the prev and next page should be Design page(Getting-Started guide) and Getting-Started page(Developer Guide). 

This issue is mentioned here but not in website/prometheus-operator repo because changes are needed in api.md file in this repo.

### Prometheus Operator Version

```shell
NA(docs issue)
```

### Kubernetes Version

```yaml
NA(docs issue)
```

### Kubernetes Cluster Type

kind

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### prometheus-operator log output

```shell
NA(docs change)
```

**Comment by ArthurSens** [comment]
Fixed by https://github.com/prometheus-operator/prometheus-operator/pull/6734
