### ISSUE TITLE
Refactor DNS SD Configuration options

### ISSUE THREAD

**Issue by mviswanathsai** [prometheus-operator/prometheus-operator#6739]
### What is missing? Please describe.

The ScrapeConfig API needs to be refactored, we are going one SD at a time.

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by ArthurSens** [comment]
> The ScrapeConfig API needs to be refactored, we are going one SD at a time.

With Simon on PTO (I'm not sure if JP is as well), it would be nice to have a bit more detail here 😅. What are we trying to accomplish with the refactoring? Why is it needed? Asking just in case my review will be needed to progress :)
