### ISSUE TITLE
ScrapeClasses: Support AttachMetadata

### ISSUE THREAD

**Issue by hamishforbes** [prometheus-operator/prometheus-operator#6752]
### Component(s)

Other (please comment)

### What is missing? Please describe.

I'd like to see Scrape Classes support configuring AttachMetadata.

I'm testing out making my prometheus deployments zone-aware.

I think this is possible with a scrape class that enables node metadata and a relabelling config to drop metrics targets from other zones.
Then I just need to create a Prometheus resource for each zone with a nodeSelector and the appropriate scrapeClass.

Having this on a default scrape class means that 
a) I don't have to go through and add it to every pod/service monitor I create
b) I don't have to hack it in to pod/service monitors I don't have full control over - e.g. deployed by 3rd party helm charts

### Describe alternatives you've considered.

A feature request to prometheus itself to expose a global config to enable node metadata by default.
A global config/flag in prometheus operator to enable node metadata by default, scrape classes seems a better fit though.

## Environment
Kubernetes Version: 1.30
Prometheus-Operator Version: 0.73

**Comment by nicolastakashi** [comment]
Yes, this makes sense for me.
@hamishforbes is this something you would like to contribute?

**Comment by hamishforbes** [comment]
> Yes, this makes sense for me. @hamishforbes is this something you would like to contribute?

I can have a crack at it, doesn't look too difficult at first glance!
