### ISSUE TITLE
Fix docs references in repo

### ISSUE THREAD

**Issue by slashpai** [prometheus-operator/prometheus-operator#6772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently docs checks are failing due to invalid links in README and other places due website restructuring.
Logging the issue to keep track of it.

cc: @AshwinSriram11 

### Prometheus Operator Version

```shell
NA
```

### Kubernetes Version

```yaml
NA
```

### Kubernetes Cluster Type

kind

### How did you deploy Prometheus-Operator?

Other (please comment)

### Manifests

```yaml
NA
```

### prometheus-operator log output

```shell
NA
```

### Anything else?

NA

**Comment by slashpai** [comment]
example run https://github.com/prometheus-operator/prometheus-operator/actions/runs/10058233051/job/27800859187

**Comment by simonpasquier** [comment]
@slashpai IIUC it only happens for the release-0.75 branch. The main branch is ok.

**Comment by slashpai** [comment]
my bad, I will close this then I noticed main branch PR is succeeding
