### ISSUE TITLE
Update OAuth2 field description in ScrapeConfig CRD

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#6815]
(nit) to be consistent with the other auth fields like `Authorization`.
```suggestion
	// OAuth2 configuration to use on every scrape request.
```

_Originally posted by @simonpasquier in https://github.com/prometheus-operator/prometheus-operator/pull/6814#discussion_r1706665812_

Also unit tests would be nice to add.

**Comment by mviswanathsai** [comment]
On it!

**Comment by mviswanathsai** [comment]
Should we also add `MinItems:=1` on all the list of SDs?
