### ISSUE TITLE
Docker SD: add MatchFirstNetwork field

### ISSUE THREAD

**Issue by slashpai** [prometheus-operator/prometheus-operator#6839]
### Component(s)

ScrapeConfig

### What is missing? Please describe.

match_first_network field is added in Prometheus 2.54

```
# Match the first network if the container has multiple networks defined, thus avoiding collecting duplicate targets.
[ match_first_network: [<boolean>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#boolean) | default = true ]
```

details: https://github.com/prometheus/prometheus/pull/10490

support this in ScrapeConfig for feature parity

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by Akhil-2001** [comment]
Hey, would you mind throwing some light on what exactly needs to be done under ScrapeConfig?

**Comment by dongjiang1989** [comment]
I would like to work on this issue. 😄
