### ISSUE TITLE
Can the built-in volume be overwritten by the user?

### ISSUE THREAD

**Issue by CooperWanng** [prometheus-operator/prometheus-operator#6850]
### What happened?

The prometheus statefulset generated by the operator has a default volume "prometheus-k8s-db", which is an emptyDir. Is there a way to modify this volume? I hope this volume can be a hostpath or other network storage.
But when I try to define prometheus-k8s-db again in the volume properties, the generated statefulset contains two volumes named prometheus-k8s-db
![image](https://github.com/user-attachments/assets/38a96526-11df-48e5-9a9a-883502dd3fe0)
![image](https://github.com/user-attachments/assets/6ccab37d-417c-4a0c-b4f3-ca0d359a35d6)

### Prometheus Operator Version

```shell
0.62.0
```

### Kubernetes Version

```yaml
1.25
```

### Kubernetes Cluster Type

Other (please comment)

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### prometheus-operator log output

```shell
none
```

### Anything else?

kubernets cluster deployed by the k8s binary file

**Comment by simonpasquier** [comment]
yes see https://prometheus-operator.dev/docs/platform/storage/
