### ISSUE TITLE
[Experiment the bot ] How to configure the prometheus custom resource to watch servicemonitors across namespaces

### ISSUE THREAD

**Issue by slashpai** [prometheus-operator/prometheus-operator#6859]
### What happened?

How to configure the operator to watch servicemonitors across namespaces

### Prometheus Operator Version

```shell
NA
```

### Kubernetes Version

```yaml
NA
```

### Kubernetes Cluster Type

kind

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### prometheus-operator log output

```shell
1.31
```

### Anything else?

NA

**Comment by ArthurSens** [comment]
@Dosubot can you help?
