### ISSUE TITLE
"PrometheusAgent CRD" seems not to support "scrapeConfigSelector"

### ISSUE THREAD

**Issue by mmuto118** [prometheus-operator/prometheus-operator#6863]
## Description
I am trying to add some scrape targets external to kubernetes cluster.
but adding  "scrapeConfigSlector" to "PrometheusAgent CRD"  results in an error"
I use kube-prometheus-stack in my cluster.
in case, I already conducted the below procedure,but It ended up with no appearance of prometheus target which I added to prometheus-additional.yaml.
I confimed that Prometheus Operator read additional-scrape-config secret, but the static_config targets did'nt show up in prometheus configure by Prometheus UI.
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/additional-scrape-config.md

I checked the maual reference below:
"Both the Prometheus and PrometheusAgent CRD have a scrapeConfigSelector field. " in the document is not updated?
https://prometheus-operator.dev/docs/developer/scrapeconfig/

## Expected Result
kubectl apply -f prometheusagent-crd.yaml is successfully applied.

## Actual Result
the below error occurs and  says "unknown field scrapeConfigSelector".

error: error validating "prometheusagent-crd.yaml": error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "scrapeConfigSelector" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation off with --validate=false

### Prometheus Operator Version

```shell
quay.io/prometheus-operator/prometheus-operator:v0.75.2
```

### Kubernetes Version

```yaml
v1.24.9+k3s1
```

### Kubernetes Cluster Type

Other (please comment)

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### Manifests

```yaml
■Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: prometheus-stack
  labels:
    prometheus: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  scrapeConfigSelector:
    matchLabels:
      prometheus: system-monitoring-prometheus


■PrometheusAgent CRD(scrapeConfigSelector field add by me)
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
    operator.prometheus.io/version: 0.75.2
  creationTimestamp: "2024-08-22T02:38:27Z"
  generation: 1
  name: prometheusagents.monitoring.coreos.com
  resourceVersion: "274464000"
  uid: 6d03e595-6ede-4ebb-8c23-fe660541c5f6
spec:
  scrapeConfigSelector:
    matchLabels:
      prometheus: system-monitoring-prometheus

■ScrapeConfig CRD
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: pve-config
  namespace: prometheus-stack
  labels:
    prometheus: system-monitoring-prometheus
spec:
  jobName: 'pve'
  staticConfigs:
    - targets:
      - x.x.x.x:9221  
      labels:
        job: pve
  metricsPath: /pve
  params:
    module: [default]
    cluster: ['1']
    node: ['1']
```

### prometheus-operator log output

```shell
level=info ts=2024-08-22T02:49:26.706705052Z caller=main.go:205 msg="Starting Prometheus Operator" version="(version=0.75.2, branch=refs/tags/v0.75.2, revision=35b0f457d8f705f1ac8282b4e22caa68a19c6c43)"
level=info ts=2024-08-22T02:49:26.706732988Z caller=main.go:206 build_context="(go=go1.22.5, platform=linux/amd64, user=Action-Run-ID-10070178014, date=20240724-04:03:08, tags=unknown)"
level=info ts=2024-08-22T02:49:26.706739428Z caller=main.go:207 feature_gates="PrometheusAgentDaemonSet=false"
level=info ts=2024-08-22T02:49:26.706896618Z caller=cpu.go:28 msg="Leaving GOMAXPROCS=7: CPU quota undefined"
level=info ts=2024-08-22T02:49:26.706931345Z caller=main.go:220 msg="namespaces filtering configuration " config="{allow_list=\"\",deny_list=\"\",prometheus_allow_list=\"\",alertmanager_allow_list=\"\",alertmanagerconfig_allow_list=\"\",thanosruler_allow_list=\"\"}"
level=info ts=2024-08-22T02:49:26.711190158Z caller=main.go:254 msg="connection established" cluster-version=v1.24.9+k3s1
level=info ts=2024-08-22T02:49:26.730330574Z caller=operator.go:361 component=prometheus-controller msg="Kubernetes API capabilities" endpointslices=true
level=info ts=2024-08-22T02:49:26.737397335Z caller=operator.go:324 component=prometheusagent-controller msg="Kubernetes API capabilities" endpointslices=true
level=warn ts=2024-08-22T02:49:26.754759737Z caller=server.go:160 msg="server TLS client verification disabled" client_ca_file=/etc/tls/private/tls-ca.crt err="stat /etc/tls/private/tls-ca.crt: no such file or directory"
level=info ts=2024-08-22T02:49:26.755444672Z caller=server.go:300 msg="starting secure server" address=[::]:10250 http2=false
level=info ts=2024-08-22T02:49:26.856703449Z caller=operator.go:283 component=thanos-controller msg="successfully synced all caches"
level=info ts=2024-08-22T02:49:26.856746743Z caller=operator.go:433 component=prometheusagent-controller msg="successfully synced all caches"
level=info ts=2024-08-22T02:49:26.856872848Z caller=operator.go:313 component=alertmanager-controller msg="successfully synced all caches"
level=info ts=2024-08-22T02:49:26.856935238Z caller=operator.go:418 component=prometheus-controller msg="successfully synced all caches"
level=info ts=2024-08-22T02:49:26.857632133Z caller=operator.go:572 component=alertmanager-controller key=prometheus-stack/promstack-kube-prometheus-alertmanager msg="sync alertmanager"
level=info ts=2024-08-22T02:49:26.858246076Z caller=operator.go:808 component=prometheus-controller key=prometheus-stack/promstack-kube-prometheus-prometheus msg="sync prometheus"
level=info ts=2024-08-22T02:49:26.905199264Z caller=operator.go:572 component=alertmanager-controller key=prometheus-stack/promstack-kube-prometheus-alertmanager msg="sync alertmanager"
level=info ts=2024-08-22T02:49:26.911450887Z caller=operator.go:808 component=prometheus-controller key=prometheus-stack/prometheus msg="sync prometheus"
level=info ts=2024-08-22T02:49:26.952738162Z caller=operator.go:808 component=prometheus-controller key=prometheus-stack/promstack-kube-prometheus-prometheus msg="sync prometheus"
```

**Comment by mmuto118** [comment]
@slashpai 
Thank you for the replay.
I did not update CRD matching the operator version "v0.75.2"
May I ask you a question, How should I update CRD is suted to "Operator v0.75.2" ?

**Comment by slashpai** [comment]
Not sure how you installed the operator, but CRDs corresponding to each release should be in release branch since you use `0.75` see https://github.com/prometheus-operator/prometheus-operator/tree/release-0.75/example/prometheus-operator-crd-full

**Comment by mmuto118** [comment]
@slashpai 
Thank you for giving a link.
I confirmed it later.
Prometheus Operator v0.75 was already deployed as kube-prometheus-stack using helm chart.

if I will be not able to solve this case by using CRD Update, I recheck and the blow link and then retry to configure  static_config all over again.
Do you know other ways to get static_config configuretion applied to prometheus operator?
Thank you.

**Comment by mmuto118** [comment]
I failed to update CRD by issusing the command "kubectl apply -f monitoring.coreos.com_prometheusagents.yaml"
The erros say:
The CustomResourceDefinition "prometheusagents.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
`
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  name: prometheusagents.monitoring.coreos.com
`

# link
https://github.com/prometheus-operator/prometheus-operator/blob/release-0.75/example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml

**Comment by simonpasquier** [comment]
see https://prometheus-operator.dev/docs/platform/troubleshooting/#customresourcedefinition--is-invalid-metadataannotations-too-long-issue

**Comment by ArthurSens** [comment]
@dosubot, your answer is incorrect. Could you remove your comment?

**Comment by mmuto118** [comment]
> see https://prometheus-operator.dev/docs/platform/troubleshooting/#customresourcedefinition--is-invalid-metadataannotations-too-long-issue

@ArthurSens 
Thank you for helping me out.
I solved the error "Too long: must have at most 262144 bytes" and confimed the CRD was applied to the my cluster correctly.

**Comment by mmuto118** [comment]
I report the current situation.
1) The crd of "monitoring.coreos.com_prometheusagents.yamlthes" was applied. its crd is located in the below link. 
https://github.com/prometheus-operator/prometheus-operator/tree/release-0.75/example/prometheus-operator-crd-full
2) I failed to apply prometheusagent  and got the error. 
"strict decoding error: unknown field "spec.scrapeConfigSelector"
like the below,I added  scrapeConfigSelector section to my yaml file.
`
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
    operator.prometheus.io/version: 0.75.2
  creationTimestamp: "2024-08-22T02:38:27Z"
  generation: 1
  name: prometheusagents.monitoring.coreos.com
  resourceVersion: "274464000"
  uid: 6d03e595-6ede-4ebb-8c23-fe660541c5f6
spec:
  scrapeConfigSelector:
    matchLabels:
      prometheus: system-monitoring-prometheus
  conversion:
    strategy: None
  group: monitoring.coreos.com
`

Does it means The CRD is not updated?

**Comment by mmuto118** [comment]
sorry to misunderstand how to configuretion "scrapeConfigSelector".
incorrect:
add "scrapeConfigSelector" section to CRD itself. 
corrent:
add "scrapeConfigSelector" section to "Kind:PrometheusAgent"
finally, I was able to get "scrapeConfigSelector" configuretions in effect in my cluster.
it resolves everything.
Thank you all for suppoting me.
