### ISSUE TITLE
Unable to deploy provided operator bundle

### ISSUE THREAD

**Issue by frzifus** [prometheus-operator/prometheus-operator#6905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

I am unable to deploy the operator into namespace that is **not** `default`. 

## Steps to Reproduce

1. Create a namespace
2. apply the bundle and add `-n <namespace>`

## Expected Result

Operator will be deployed into provided  namespace

## Actual Result

Getting an error message:
```
the namespace from the provided object "default" does not match the namespace "prometheus-operator-system". You must pass '--namespace=default' to perform this operation.
```

### Prometheus Operator Version

```shell
v0.76.1
```

### Kubernetes Version

```yaml
v1.29.4
```

### Kubernetes Cluster Type

Rancher

### How did you deploy Prometheus-Operator?

yaml manifests

### prometheus-operator log output

```shell
$ kubectl apply -n prometheus-operator-system -f https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.76.1/bundle.yaml
customresourcedefinition.apiextensions.k8s.io/podmonitors.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/probes.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/prometheusrules.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com created
clusterrolebinding.rbac.authorization.k8s.io/prometheus-operator created
clusterrole.rbac.authorization.k8s.io/prometheus-operator created
the namespace from the provided object "default" does not match the namespace "prometheus-operator-system". You must pass '--namespace=default' to perform this operation.
```

**Comment by simonpasquier** [comment]
For this to work, namespaced resources in bundle.yaml should not specify a namespace value. The change would need to happen in scripts/generate/build-rbac-prometheus-operator.sh IIUC.

**Comment by simonpasquier** [comment]
After looking more into it, it's not that simple because of the ClusterRoleBinding resource. The alternative is probably to document kustomize usage like:

````sh
kustomize edit set namespace <custom namespace> && kubectl apply --server-side --force-conflicts -k .
````
