### ISSUE TITLE
Support Prometheus v3 / `unsupported Prometheus major version 3.0.0-beta.0`

### ISSUE THREAD

**Issue by EconomicTouristsArmLate** [prometheus-operator/prometheus-operator#6939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
Prometheus [3.0.0-beta.0](https://github.com/prometheus/prometheus/releases/tag/v3.0.0-beta.0) has been cut. :tada: 
I want to try it, but operator doesn't let me.

I can understand if you won't add support until a full release is cut.
In that case i wonder though, how I can beta-test this release with prometheus-operator.

The breaking changes seem relatively noninvasive. From a quick (non-exhaustive) check, it seems to me that the operator will only be affected by the agent mode feature flag removal:

- `agent` featureflag now --agent flag -- https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/prometheus/agent/statefulset.go#L160-L162

## Steps to Reproduce
Deploy with prometheus spec changes as follows:

```
prometheus:
  prometheusSpec:
    image:
      tag: v3.0.0-beta.0
```

## Expected Result
Deploy instances of prometheus v.3.0.0-beta.0

## Actual Result
No prometheus pods are created.

### Prometheus Operator Version

```shell
quay.io/prometheus-operator/prometheus-operator:v0.76.1
```

### Kubernetes Version

```yaml
1.28
```

### Kubernetes Cluster Type

Other (please comment)

### How did you deploy Prometheus-Operator?

helm chart:prometheus-community/kube-prometheus-stack

### Manifests

```yaml
# kube-prometheus-stack.values.yaml
prometheus:
  prometheusSpec:
    image:
      tag: v3.0.0-beta.0
```

### prometheus-operator log output

```shell
level=error ts=2024-09-14T22:33:17.122085721Z caller=klog.go:126 component=k8s_client_runtime func=ErrorDepth msg="sync \"o11y/kps-prometheus\" failed: unsupported Prometheus major version 3.0.0-beta.0: %!w(<nil>)"
```

**Comment by slashpai** [comment]
I would wait to hear from other maintainers opinion on this but I am going to experiment with a draft PR :)

**Comment by simonpasquier** [comment]
Yes we want to support this ASAP.
