### ISSUE TITLE
Add `enableHTTP2` field to the ScrapeConfig CRD

### ISSUE THREAD

**Issue by mviswanathsai** [prometheus-operator/prometheus-operator#6970]
### Component(s)

ScrapeConfig

### What is missing? Please describe.

The ScrapeConfig CRD is meant to be a 1:1 mirror of the Prometheus scrape configuration. To that extent, it is currently missing a few fields like `enable_http2` and we want to add them. It is important to note that it may not be possible to add some fields.

You may take examples of `EnableHTTP` from existing service discoveries. (#6421 might be a good place to start)

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by chetak123** [comment]
I would like to work on this issue please

**Comment by slashpai** [comment]
go ahead 🙂

**Comment by mviswanathsai** [comment]
@chetak123 do you need any help with this?
