### ISSUE TITLE
Add `OAuth2` field to the ScrapeConfig CRD

### ISSUE THREAD

**Issue by mviswanathsai** [prometheus-operator/prometheus-operator#6971]
### What is missing? Please describe.

The ScrapeConfig CRD is meant to be a 1:1 mirror of the Prometheus scrape configuration. To that extent, it is currently missing a few fields and we want to add them. It is important to note that it may not be possible to add some fields.

You may take examples of `OAuth2` from existing service discoveries. (#6421 might be a good place to start)

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by Sid-80** [comment]
@slashpai I am willing to work on this issue!

**Comment by slashpai** [comment]
Sure go ahead 🙂

**Comment by Sid-80** [comment]
@slashpai @mviswanathsai 
I have just learned Golang. Can you help me in knowing other tools required to contribute to this incredible project!

**Comment by slashpai** [comment]
That should be goo enough to start writing the code. If you want to run the image locally docker/podman would be good to create kind cluster or minikube cluster

Take a look at https://github.com/prometheus-operator/prometheus-operator/blob/main/CONTRIBUTING.md and https://github.com/prometheus-operator/prometheus-operator/blob/main/TESTING.md that should help.

**Comment by Kamalesh-Seervi** [comment]
can I work on this

**Comment by mviswanathsai** [comment]
@Kamalesh-Seervi sure, you can go ahead and work on it.

**Comment by nutmos** [comment]
@mviswanathsai I tried checking the config and found OAuth2 was already implemented in ScrapeConfig. (Correct me if I'm wrong) I added the new test to validate it in the new PR. Please review.

**Comment by slashpai** [comment]
[OAuth2](https://github.com/prometheus-operator/prometheus-operator/blob/514f90aabf93ee64202d4f0ef60cd987961d71d5/pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go#L299) field is already implemented in ScrapeConfig. Implemented in https://github.com/prometheus-operator/prometheus-operator/pull/6814

**Comment by mviswanathsai** [comment]
Terribly sorry about that, not sure how I missed this. @nutmos

**Comment by slashpai** [comment]
No worries, I didn't notice it too. I was reviewing old issues and PR hence noticed this one
