### ISSUE TITLE
Store debug information from e2e tests on disk and upload to artifacts 

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#6973]
### What is missing? Please describe.

#6960 added the capability to collect troubleshooting information when e2e test cases fail. Right now the information is dumped to the standard output which can be hard to navigate. Instead it would useful to store the data on disk and upload  to GitHub artifacts.

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by slashpai** [comment]
IIUC this can be done easily with https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow#uploading-build-and-test-artifacts, may be we can log the output of test to /tmp and then use that file to upload to artifacts with a retention period

**Comment by slashpai** [comment]
more option explained in https://github.com/actions/upload-artifact

**Comment by simonpasquier** [comment]
To be more explicit (since we've discussed offline with @slashpai), my idea was that all debug info should be stored to a temp directory (with each sub-test debug into its own subdir) instead of being printed out to stdout because the debug info is massive and makes it harder to read the test.

The debugging workflow would look like:
1. open the GitHub action UI to look for the failed test.
2. download the test artifact.
3. look for debug info pertaining to the failed test.

I expect that we had more and more collected information over time.
