### ISSUE TITLE
Add testcases for empty string values in `[]string` structures

### ISSUE THREAD

**Issue by mviswanathsai** [prometheus-operator/prometheus-operator#6976]
## Description
Not really a feature, we just need to add a few testcases here. Originally reported and dealt with in #6921, we now have validations to prevent empty strings in fields which are a slice of string. However, some of the fields lack a testcase for something like `[]string{""}`. 
For example,
```
{
		name: "Invalid Filters with empty string value",
		scrapeConfigSpec: monitoringv1alpha1.ScrapeConfigSpec{
			EC2SDConfigs: []monitoringv1alpha1.EC2SDConfig{
				{
					Region: ptr.To("us-west"),
					Filters: []monitoringv1alpha1.Filter{
						{
							Name:   "foo",
							Values: []string{""},
						},
					},
				},
			},
		},
		expectedError: true,
	},
```
needs to be added. The fix would be adding missing testcases with empty strings for any string slice field.

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by leonhfr** [comment]
Hi @mviswanathsai, I'm willing to work on this issue to get acquainted with the repo!
