### ISSUE TITLE
Allow to configure `fallback_scrape_protocol` for each scrape CRD and globally

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#7077]
### Component(s)

Prometheus, PrometheusAgent

### What is missing? Please describe.

https://github.com/prometheus/prometheus/pull/15136 introduces a (breaking) change in Prometheus 3.0: Prometheus will reject targets not specifying an explicit and valid `Content-Type` (typically applications not using official/supported client libraries). As a workaround, users can define a fallback protocol. It needs to be supported for ServiceMonitor, PodMonitor and ScrapeConfig. It would also be useful to support as a global Prometheus/PrometheusAgent setting.

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by dongjiang1989** [comment]
@simonpasquier I would like to work on this issue. 😊

**Comment by slashpai** [comment]
@dongjiang1989 go ahead I didnt get enough time to work on it :)

**Comment by patrickshan** [comment]
For anyone who is looking for solution for this with prometheus-operator, a default `scrapeClass` can be defined with `fallbackScrapeProtocol` parameter which will be applied to all the scrape config.

**Comment by hack4e** [comment]
> For anyone who is looking for solution for this with prometheus-operator, a default `scrapeClass` can be defined with `fallbackScrapeProtocol` parameter which will be applied to all the scrape config.

@patrickshan Thanks, I've managed to resolve the issue by updating the Operator configuration using the configuration shown below.


```yaml
    scrapeClasses:
    - default: true
      fallbackScrapeProtocol: PrometheusText0.0.4
      name: default-scrape
```
