### ISSUE TITLE
`scrape_classic_histograms` renamed to `always_scrape_classic_histograms` in Prometheus v3

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#7088]
### Component(s)

Prometheus, PrometheusAgent

### What is missing? Please describe.

https://github.com/prometheus/prometheus/pull/15178

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by heliapb** [comment]
Hi @simonpasquier I would like to work on that issue
