### ISSUE TITLE
Always set Alertmanager API version to v2 for Prometheus v3 and above

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#7089]
### Component(s)

Prometheus

### What is missing? Please describe.

https://github.com/prometheus/prometheus/pull/13883

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by heliapb** [comment]
Hi @simonpasquier I would like to work on this issue.

**Comment by slashpai** [comment]
completed in https://github.com/prometheus-operator/prometheus-operator/pull/7102
