### ISSUE TITLE
Support `--web.enable-otlp-receiver` flag in the Prometheus/PrometheusAgent CRD

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#7090]
### Component(s)

Prometheus, PrometheusAgent

### What is missing? Please describe.

The OTLP receiver is stable with Prometheus v3, it can be exposed in the CRDs.
https://github.com/prometheus/prometheus/pull/14894

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by dongjiang1989** [comment]
@simonpasquier I would like to work on this issue.
