### ISSUE TITLE
Support `metric_name_validation_scheme` option in Prometheus global configuration

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#7091]
### Component(s)

Prometheus, PrometheusAgent

### What is missing? Please describe.

https://github.com/prometheus/prometheus/pull/14705

This issue needs to be coordinated with https://github.com/prometheus-operator/prometheus-operator/pull/7112 because `LegacyValidationConfig` scheme is incompatbile with the `NoUTF8EscapingWithSuffixes` translation strategy.

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by heliapb** [comment]
Hi @simonpasquier I would like to work on this issue.
