### ISSUE TITLE
Implement GitHub action linter

### ISSUE THREAD

**Issue by simonpasquier** [prometheus-operator/prometheus-operator#7094]
### What is missing? Please describe.

Preventing issues like https://github.com/prometheus-operator/prometheus-operator/pull/7093

https://github.com/rhysd/actionlint

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by slashexx** [comment]
I'm on this !

**Comment by slashexx** [comment]
@simonpasquier Kindly request you to review.
