### ISSUE TITLE
Default enable  `auto-gomaxprocs` and `auto-gomemlimit`

### ISSUE THREAD

**Issue by dongjiang1989** [prometheus-operator/prometheus-operator#7132]
## Description

Enable the `auto-gomaxprocs` and `auto-gomemlimit` feature flag by default.  Consistent with prometheus v3
Make the feature flag deprecated.

ref: https://github.com/prometheus/prometheus/releases/tag/v3.0.0

### Prometheus Operator Version

```shell
v0.78.1
```

### Kubernetes Version

```yaml
v1.28.8
```

### Kubernetes Cluster Type

kind

### How did you deploy Prometheus-Operator?

prometheus-operator/kube-prometheus

### prometheus-operator log output

```shell
None
```

**Comment by simonpasquier** [comment]
I'm not sure to understand the request, can you detail?
The operator doesn't expose the flags directly so users rely on the default Prometheus behavior.

**Comment by dongjiang1989** [comment]
Hmmm... 🤔️ Sorry, I missed something. 
It's currently on by default. 
I turn this issue off.
