### ISSUE TITLE
prometheusrules.monitoring.coreos.com to support labels at rules level

### ISSUE THREAD

**Issue by kchestnov** [prometheus-operator/prometheus-operator#7135]
### Component(s)

Prometheus, AlertManager

### What is missing? Please describe.

From official documentation https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/ 
Groups should support labels
```
groups:
- name: example
  labels:
    team: myteam
```

Recent promtool versions have added support https://github.com/prometheus/prometheus/commit/f253d36361ef67228ecf3bfc3d8b359e05d35606 

Request is to add it to CRD
https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml

**Comment by heliapb** [comment]
Hi @simonpasquier I would like to work on this one.
