### ISSUE TITLE
add scrape_config_files parameter support in prometheus.env.yaml 

### ISSUE THREAD

**Issue by san3Xian** [prometheus-operator/prometheus-operator#7148]
### Component(s)

Prometheus

### What is missing? Please describe.

The `scrape_config_files` parameter in Prometheus is not supported by operator 

### Describe alternatives you've considered.

Currently, Prometheus Operator does not provide a way to configure the `scrape_config_files` parameter in Prometheus CR configuration.   
In Kubernetes + Prometheus Operator setups, since each Kubernetes Secret can only store up to 1024 bytes, and the `prometheuses.spec.additionalScrapeConfigs` field in the Prometheus CR can only reference a single Secret, this can cause issues when there are many jobs or jobs with static targets defined in `static_configs` (without using service discovery mechanisms).   
This can lead to the Secret being filled up, preventing the addition of more job configurations.

Hope that Prometheus Operator enables support for `scrape_config_files`, and then allowing users to modify multiple ConfigMaps and mount them into Prometheus container filesystem as files. Prometheus would then read these ConfigMaps from a specified path via the `scrape_config_files` option.  

## Environment
Kubernetes Version: v1.26.7
Prometheus-Operator Version: v0.65.1

**Comment by slashpai** [comment]
Have you considered using scrape config instead of additionalScrapeConfig 
https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1alpha1.ScrapeConfig
https://prometheus-operator.dev/docs/developer/scrapeconfig/

**Comment by san3Xian** [comment]
> Have you considered using scrape config instead of additionalScrapeConfig https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1alpha1.ScrapeConfig https://prometheus-operator.dev/docs/developer/scrapeconfig/

This looks like a great feature, thanks a lot, I'll go and use it to experience it!

**Comment by slashpai** [comment]
Please feel free to reach out/reopen issue if face any issue.
Closing this for now
