### ISSUE TITLE
[Feature request] Fake CRDs for unit test similar to k8s.io/client-go/kubernetes/fake

### ISSUE THREAD

**Issue by yoyosir** [prometheus-operator/prometheus-operator#7188]
### Component(s)

ServiceMonitor

### What is missing? Please describe.

Would be really nice to have something similar to k8s.io/client-go/kubernetes/fake for CRDs like ServiceMonitor. This will make unit tests a lot easier.

## Environment
Kubernetes Version:
Prometheus-Operator Version:

**Comment by slashpai** [comment]
Could you please provide more details and which unit tests you are referring to?

**Comment by simonpasquier** [comment]
hmm are you looking for https://pkg.go.dev/github.com/prometheus-operator/prometheus-operator/pkg/client@v0.78.2/versioned/fake?
