### ISSUE TITLE
RuleSelector seems to not work as advertised.

### ISSUE THREAD

**Issue by SleepyBrett** [prometheus-operator/prometheus-operator#730]
**What did you do?**

I have the following in my prometheus spec:

    ruleSelector:
      matchLabels:  
        role: "prometheus-rulefiles"
        shared-prometheus: "true"

**What did you expect to see?**

When I inspect /etc/prometheus/rules/rule-* folders in the config reloader container I expect to see files from configmaps only with the above labels. 

**What did you see instead? Under which circumstances?**

The rules directories listed above contain the contents of all configmaps in my monitoring namespace, regardless of labeling.

**Environment**

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-15T08:51:09Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+coreos.0", GitCommit:"e14ebed378d5380b9936455584fa454daa67f23b", GitTreeState:"clean", BuildDate:"2017-09-14T21:52:44Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	bootkube

* Manifests:

Will provide more if above is not enough

* Prometheus Operator Logs:

    ....
    ts=2017-11-06T15:21:05Z caller=operator.go:293 component=prometheusoperator msg="Prometheus updated" key=monitoring/prometheus
    ts=2017-11-06T15:21:05Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
    ts=2017-11-06T15:21:44Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
    ts=2017-11-06T15:22:35Z caller=operator.go:293 component=prometheusoperator msg="Prometheus updated" key=monitoring/prometheus
    ts=2017-11-06T15:22:35Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
    ts=2017-11-06T15:22:55Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
    ts=2017-11-06T15:23:25Z caller=operator.go:306 component=prometheusoperator msg="syncing nodes into Endpoints object failed" err=null
    ts=2017-11-06T15:24:02Z caller=operator.go:293 component=prometheusoperator msg="Prometheus updated" key=monitoring/prometheus
    ts=2017-11-06T15:24:02Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
    ts=2017-11-06T15:24:33Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus

**Comment by brancz** [comment]
Did this happen in conjunction with a custom configuration?

**Comment by SleepyBrett** [comment]
Yes, I think we discussed over slack. It made me back out of using the operator ( the whole operator seems to lobotomize itself in the presence of a custom config )

**Comment by brancz** [comment]
fyi we recently added the `additionalScrapeConfigs` feature where you can use all the prometheus operator features but define your own custom scrape jobs, I believe that's what you initially were looking for with this issue, right?

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think the issue is still valid, please reopen it.
