### ISSUE TITLE
simplify and fix errors in networkpolicies docs

### ISSUE THREAD

**Issue by Morriz** [prometheus-operator/prometheus-operator#796]
Two issues:

- lowercase tcp and udp is not allowed since `apiVersion: networking.k8s.io/v1`
- it's not necessary to use `matchExpression` when referring to labels. So those can become `matchLabels`

See: https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/

**Comment by brancz** [comment]
We're happy for PRs to fix this :slightly_smiling_face: .

**Comment by Morriz** [comment]
Of course, but I am also using egress control, to avoid unwanted extraction of data. I will make a PR when I am satisfied with the whole

**Comment by brancz** [comment]
Perfect, that sounds, great, thanks!

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think the issue is still valid, please reopen it.
