### ISSUE TITLE
add labels to the prometheus configuration file in operator

### ISSUE THREAD

**Issue by zrbilvoe** [prometheus-operator/prometheus-operator#827]
How to add labels to the prometheus configuration file in operator

![image](https://user-images.githubusercontent.com/16753373/34040542-3c61c8fe-e1cf-11e7-828b-cf976e49799e.png)

https://grafana.com/dashboards/367

**Comment by brancz** [comment]
What you are seeing in the screenshot is merely an example, most important is that you actually collect metrics with the haproxy-exporter. The `alias` label for one is pretty arbitrary, so you could also adapt the dashboard itself to fit your infrastructure. The Prometheus Operator uses the Kubernetes service discovery built into Prometheus, not static scrape configs.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think the issue is still valid, please reopen it.
