### ISSUE TITLE
Prometheus Operator does not respect changes made by K8s initializers 

### ISSUE THREAD

**Issue by rlguarino** [prometheus-operator/prometheus-operator#873]
**What did you do?**

Tried starting a Prometheus cluster with Prometheus Operator on [Istio](https://istio.io) with auto-sidecar-injection turned on.

**What did you expect to see?**

A Prometheus cluster's statefulset is running and in the Istio Mesh. 

**What did you see instead? Under which circumstances?**

A Prometheus cluster starts but is not in the mesh. There are no istio-sidecar containers in the pod template.

If I watch the Prometheus statefulset while it's being created I can see that the Istio intiailizer adds the Istio pods to the template during the initialization phase. But then immediately after it seems the Prometheus operator updates the statefulset again to remove the pods added by Istio. Therefor the Stateful Set isn't part of the mesh and cannot talk to mesh endpoints.

**Environment**

Istio 0.4
Kubernetes 1.8.6
Prometheus Operator 0.15.0

* Kubernetes version information:
```
	Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	Bare Metal

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  resources:
    requests:
      memory: 400Mi
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor
spec:
  selector:
    matchLabels:
      app: www
  endpoints:
  - port: http-metrics
```

* Prometheus Operator Logs:

```
ts=2018-01-09T21:40:18Z caller=operator.go:156 component=alertmanageroperator msg="connection established" cluster-version=v1.8.6
ts=2018-01-09T21:40:18Z caller=operator.go:257 component=prometheusoperator msg="connection established" cluster-version=v1.8.6
ts=2018-01-09T21:40:18Z caller=operator.go:170 component=alertmanageroperator msg="CRD API endpoints ready"
ts=2018-01-09T21:40:18Z caller=operator.go:271 component=prometheusoperator msg="CRD API endpoints ready"
ts=2018-01-09T22:01:59Z caller=operator.go:307 component=prometheusoperator msg="Prometheus added" key=default/prometheus
ts=2018-01-09T22:01:59Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=default/prometheus
ts=2018-01-09T22:01:59Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=default/prometheus
ts=2018-01-09T22:01:59Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=default/prometheus
ts=2018-01-09T22:01:59Z caller=operator.go:343 component=alertmanageroperator msg="update handler" old=75042770 cur=75042772
ts=2018-01-09T22:01:59Z caller=operator.go:636 component=prometheusoperator msg="update handler" old=75042770 cur=75042772
ts=2018-01-09T22:01:59Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=default/prometheus
ts=2018-01-09T22:01:59Z caller=operator.go:636 component=prometheusoperator msg="update handler" old=75042772 cur=75042779
```

**Comment by cyphrsonic** [comment]
Is there any plan to address this issue? This is an issue for me too.

**Comment by brancz** [comment]
We are about to release a new version of the Prometheus Operator which should fix these issues, as we're entirely relying on the statefulset controller to take care of things, which should respect the sidecar injection.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think the issue is still valid, please reopen it.
