### ISSUE TITLE
Broken prometheus targets and grafana dashboard after kube-prometheus install

### ISSUE THREAD

**Issue by luisyonaldo** [prometheus-operator/prometheus-operator#879]
**What did you do?**
```
helm install prometheus-operator
helm install kube-prometheus
```

**What did you expect to see?**
All kubernetes components being target by prometheus exporters and grafana dashboards working.

**What did you see instead? Under which circumstances?**
Some targets not being show on prometheus and some grafana metrics not working because the target job label is wrong. 

**Environment**

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1+coreos.0", GitCommit:"59359d9fdce74738ac9a672d2f31e9a346c5cece", GitTreeState:"clean", BuildDate:"2017-10-12T21:53:13Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1+coreos.0", GitCommit:"59359d9fdce74738ac9a672d2f31e9a346c5cece", GitTreeState:"clean", BuildDate:"2017-10-12T21:53:13Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kubespray / kubeadm.

According to [kubeadm](https://github.com/kubernetes/kubeadm/blob/master/docs/design/design_v1.10.md)
> All static Pods gets tier:control-plane and component:{component-name} labels.

but in kube-prometheus exporters the service selector label is `k8s-app: {component-name}`. Maybe default could be set but also allow to override this value.

Also, on the grafana dashboard definition, some stats and graphs use some job label as target different from the one that is set in prometheus. Example, `apiserver` but in prometheus is set to `kubernetes`, `kube-scheduler` -> `kube-prometheus-exporter-kube-scheduler` and `kube-controller-manager` -> `kube-prometheus-exporter-kube-controller-manager`.

I think this is related to prometheus relabeling like
```
- source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
```
where job label is being reset to service's name , which is being define as `{{ template "exporter-kube-scheduler.fullname" . }}` in the helm chart.

I'm testing this on a local branch, is everything work will do a PR.

**Comment by brancz** [comment]
I'm not sure where it does this in the helm charts, but in the bare kube-prometheus manifests, we have the discovery services for different types of clusters:

https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/manifests/k8s

Sounds like we just need to have a "cluster type" variable in the helm charts and select the labeling through that.

**Comment by luisyonaldo** [comment]
still on WIP https://github.com/coreos/prometheus-operator/pull/881

**Comment by luisyonaldo** [comment]
about the grafana dashboard issue.. already validate it. Issue is that on promehteus relabeling the job name will be set to service name. So there are two options, set services names inside the exporters to match the ones defined in grafana dashboard config, or change the grafana ones to match the exporter services names. The later one imply needing to pass kube-exporter sub chart names to grafana.

What do you guys think?

**Comment by matjazp** [comment]
Are Grafana dashboard configs shared/copied between helm and contrib/kube-prometheus/hack/ installations?
If it is so, it is better to fix exporters.

**Comment by paulfantom** [comment]
This issue hasn't been updated for a longer period of time. Since then we made significant changes to prometheus-operator. If you think the issue is still valid, please reopen it.
